### ISSUE TITLE
[C2M4] Suggestion

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1000]
C2M4 ...

Currrently sectors 3583 and 3584 are instant death sectors. Sectors 3571 and 3567 allow access to sector 3583.
What I suggest is make sectors 3583 and 3584 have mild damage ( maybe type 105 ) and a rope or ladder near lines 13381 and 13375.
This  makes sense to me, since there is the sub nearby and this would explain how the crew got ashore, and if BJ is dumb enough to be in the water, he can escape.

**Comment by Ozymandias81** [comment]
The problem with this issue is that okay, it makes sense what you say, but for completeness the whole sea should be then 3d and swimmable and this would become a problem with the horizon, since GZDoom has some limits and we would see the sea getting "cut out". Better keep things as they are.
