### ISSUE TITLE
Vulkan Issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1002]
This crash has been happening for me with GZD 4.6 but not 4.5.
Execution could not continue . Could not allocate memory for vulkan buffer : out of device memory.
See ... https://forum.zdoom.org/viewtopic.php?t=72640&p=1195037

**Comment by x3003** [comment]
I think you have the wrong git site: https://github.com/coelckers/gzdoom/issues as it has nothing to do w/ boa.

**Comment by hawkwind3** [comment]
I didn't word it correctly. BOA 3.1 has been sporadically crashing with Vulkan. I only mentioned the doom link as it seems to be related.

**Comment by x3003** [comment]
Some more info on how to reproduce it would be welcome.
I run boa 3.1 (gzdoom 4.6) and git (gzdoom 4.7+) all the time w/ vulkan and I have no probs.

**Comment by Tormentor667** [comment]
@hawkwind3 can you please update to GZD 4.7 and let us know if it is any better? Until then, I will close this issue.
