### ISSUE TITLE
[C1M6] - wagon issue

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#1005]
Not that I did not saw that in former times, but now I kind of realized that...
This wagon has no railway, how the hell did he get there? :D 
I know it is there to "act" as sort of a wall, but this needs to be adressed. Either add railway under it, or place there... idk, trees?
![01](https://user-images.githubusercontent.com/73436978/126911346-8b883a2d-4f8b-4b12-a7eb-bb1a36777a18.PNG)

**Comment by Tormentor667** [comment]
Fixed
