### ISSUE TITLE
Cant proceed to the next mission

### ISSUE THREAD

**Issue by PayteR** [Realm667/WolfenDoom#101]
Hi, after mission, where i saved cpt. James Ryan im unable to proceed to the next mission. I stuck in briefeng room, where i want interact with that general, or what he is, and his golden "!" turns into gray and nothing hapened. Can you tell me at least cheat how to go to the next mission or some workaround, what could i fix this? thx. Here is screen caption, sorry for bad quality http://screencast.com/t/MmyLupVN

**Comment by Tormentor667** [comment]
Hi PeyteR, this is definitely strange and shouldn't happen. To cheat to the last mission, type "pukename mission #" where # is the number of mission you want to cheat to.

**Comment by Ozymandias81** [comment]
Btw it's hard to understand exactly what you did before... did you update the GZdoom build for some reasons? Which build of GZDoom are you using with BoA? Recent ones are buggered so I suggest to play / test BoA builds with [r343 of GZdoom](http://devbuilds.drdteam.org/gzdoom/gzdoom-x64-g2.3pre-343-g49605bc.7z) at least (go for the [32bit one](http://devbuilds.drdteam.org/gzdoom/gzdoom-g2.3pre-343-g49605bc.7z) if you have a 32bit OS) ...

**Comment by PayteR** [comment]
thx Tormentor for cheat, it helped. Interesting this is, that this didnt helped on that broken savegame, i needed to get back to older biefing mission to make it work.

i play standalone v1.0, nothing changed/added to this installation. I dont remember anything that could make this bug, i played this game straight from beginning without cheats. 

Check my attached savegame with that bug, maybe it can help to you
[save1.zip](https://github.com/Realm667/WolfenDoom/files/658832/save1.zip)

**Comment by Ozymandias81** [comment]
Your save game can't be of help on my side, probably it happened something [similar to this issue](https://github.com/Realm667/WolfenDoom/issues/95)... could be everything and it cannot be reproduced unfortunately... I suggest then to [follow carefully these instructions](http://realm667.com/index.php/en/forum-board/wolfendoom-blade-of-agony/838-serious-performance-issues-with-wolfendoom-blade-of-agony#5115) and to re-play the game from the beginning.
For now I'll mark this issue as Invalid but please keep us informed if you'll experience some more problems once you are done with my suggestions.

**Comment by PayteR** [comment]
I played that along with cheated next mission, don't have more time to check it again with that instructions, sorry. 

BTW it's just fantastic mod, most sophisticated Doom mod that i ever played, i'm looking forward for next missions, thank you!

**Comment by Gaerzi** [comment]
Are you loading any other mod along with BOA? I had the same issue because I was autoloading Jimmy's Jukebox; and it turns out that it has a script that clobbers the same global variables that BOA uses to keep track of the next mission...

**Comment by PayteR** [comment]
No mods, just vanilla standalone 1.0, executed with drag&drop boa_c1.pk3, brightmaps.pk3, lights.pk3 on gzdoom.exe (boa_c1.exe was deleted by Windows defender)

**Comment by Ozymandias81** [comment]
Thank you PayteR for your kind words, just tell us if you'll manage to re-play the Standalone following my instructions. :+1:
