### ISSUE TITLE
multiplayer question

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1012]
To be specific, on Android.
There already seems to be an android version (demo ?) available (read: being worked on). Is this by the boa team or is this an independent release ?

https://www.youtube.com/watch?v=8GbSm28vRXA

**Comment by Ozymandias81** [comment]
One can already start a MP sessions under GZDoom or Android ports, but game is not set to work it properly. You can even try it with old releases, but gameplay has not been tweaked to work under MP. Examples might be noticed under C1M6, C2M4, C3M2 and some other maps, specially SM01-2-3 maps.
