### ISSUE TITLE
inbetween animations

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1014]
When you select c1m1, inbetween the 2 animations at the start you might spot douglas already waiting, for a short period of time.

![Screenshot_BoA_20210730_155209](https://user-images.githubusercontent.com/77861029/127663641-38e4dfd0-bc5a-4fd9-9961-36595b0331e8.png)

**Comment by Ozymandias81** [comment]
Can you explain it better?

**Comment by x3003** [comment]
Well, you see the first animation, press use. For a short time, you get this shot of douglas and surrounding. Then the seconds animation starts.
Maybe there should be a black screen inbetween ?!

**Comment by x3003** [comment]
Hmm, still not working correctly.

**Comment by Tormentor667** [comment]
I can't reproduce that by all means.
