### ISSUE TITLE
[3.2] Flamethrower can't be reladed with alternative fire button

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1015]
When you use the alternative fire mode w/ the flamethrower, you can't reload w/ the alternative button.
This works good w/ the tesla device, but not w/ the flamethrower.

**Comment by Tormentor667** [comment]
@Ozymandias81 @Talon1024

**Comment by AFADoomer** [comment]
This should work now after dddb1d4f301ddd733ebf238f4b84ec9941d6c576.
