### ISSUE TITLE
[3.2] General observations

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1016]
General ...

- [x] 1. I noticed many areas where the sector flag " Not shown on textured automap" was not used. So when using the textured automap ( default P on MS keyboard ), control sectors and such, are seen.
- :x: 2. Many levels use "barbed wire " but it seems that only the prison camp variety does damage. I know there has been some update to this. Might just be easier for no barbed wire to do bump damage in any map.
- :x: 3. Overhead fans - is there a way that some might not be spinning ? And seems odd in cold climates ...
> I added handling for these to be able to be set as DORMANT a little while ago, but most maps don't have any changes made, yet. - AFADoomer, 14 Feb 22
- :x: 4. I noticed in map C3M1_A that venetian blinds are complete. I noticed a what appears to be a small 3d floor at x  7316, y -15926. With all other maps E1 and E2 I did not notice this. Could this be addressed ?
> Not worth the effort.

:x: 5. GZDoom\ Portal issue - sounds not travel through portals. A good example is, chuck a grenade through a portal - no explosion sound. I'm guessing the dev's are aleady aware of this ?
- :x: 6. GZDoom issue ? - I've noticed, when standing on a 3D floor, and an enemy is below shooting, that their bullet puffs/particles will render on the 3D floor. The reverse is true, when the enemy is above or on a 3D floor and BJ is below, the bullet puffs/particles will render on the ceiling of the 3D floor.
> GZDoom issue and not changeable.
- :x: 7. Invisible chaingunners - A real PIA. Cannot be seen or killed. And often placed in dumb spots. For example, C2M1, near sector 4128. I personally would not like them in any map ( especially easy skill ), but if necessary, better positioning, like inaccessible areas and behind "foliage" .
More thoughts with Invisible Chaingunners ( Thing Type 12788 ) - 
C2M1 - They are in the open and the player can walk right up to them. Makes no sense at all. Should be removed from this map entirely IMO.
C2M5_A - The best use of Type 12788. They are placed in an area that makes sense, and the player can go to, but not necessary to go to to complete the map.
C1M3 - Reasonable use of Type 12788. Placed in an inaccessible area and behind the texture tree_g04 ( foliage ), so makes sense. Exception being T694.
C3M2 - Reasonable use of Type 12788. Although I would personally prefer them a bit further west.

Devs ... please move this if in the wrong place.

**Comment by Ozymandias81** [comment]
Regarding 2, beside models which won't do any damage, I'll take care of everything else where it make sense.

**Comment by Username-N00b-is-not-available** [comment]
4 Did @hawkwind3 mean this one?
![image](https://github.com/Realm667/WolfenDoom/assets/59409713/838c846b-1478-45ff-972a-045dd8b1370f)
6
- [ ] Related. If an enemy and a player are separated by a 3Dfloor (one of them is standing on it and one below it), the outcome depends on who is standing on the 3D floor: if the player is above, the enemy will shoot; if the player is below, the enemy won't shoot.
Test e.g. on C2M4 on the (13600, -2950) floor, summoning `WMP40Guard`s.

7 C2M5_A contains no `MGTurretInvisible`s at all...
