### ISSUE TITLE
panels too high

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1017]
In c1m2, these panels (on 4 walls) are way too high. Again, for tall zombies only.

![Screenshot_Doom_20210731_215637](https://user-images.githubusercontent.com/77861029/127751263-0dfac55c-325d-42ad-bab7-75e966df3ed0.png)

![Screenshot_Doom_20210731_215647](https://user-images.githubusercontent.com/77861029/127751270-b7f2139d-c6eb-4452-a749-e0fc4e718604.png)

![Screenshot_Doom_20210731_215641](https://user-images.githubusercontent.com/77861029/127751337-c53933f0-8c41-4d62-b305-65c4a147ca49.png)

![Screenshot_Doom_20210731_215653](https://user-images.githubusercontent.com/77861029/127751341-c16de562-126a-4d49-8fdf-0fc8c6651d1c.png)

**Comment by hawkwind3** [comment]
ladder access ... ;) . And the "shadow" is way too dark on most of them.

**Comment by Tormentor667** [comment]
Fixed
