### ISSUE TITLE
C2M2- C3.1.1

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1018]
C2M2 ...

- [x] 1. Should not the splashes on the left and right of x 2389, y 2012 be at water surface level, not underwater ?
- [x] 2. FANWALL1 not animating on the ceiling of sector 4160. Yet this texture is in animdefs.txt. If not meant to animate, T1412 should be deleted to stop the fan sound.
- [x] 3. Switch too high at line 24063 and 24062. I think I have already mentioned line 24062. A Y offset of -37 fixes IMO.
- [x] 4. Floor of sector 3583 needs an offset of x 0, y 0.

:x:  5. Vulkan issue in sector 114 ( opengl too, but much less noticed ) ... but easily fixed.
This pic shows the issue in game ...
![C2M2 vulkan bug](https://user-images.githubusercontent.com/35204218/128618316-3cbd00f4-d39a-497e-bba0-087f0d54a152.jpg)
This pic shows the fix ...
![C2m2 sector 114 fix](https://user-images.githubusercontent.com/35204218/128618355-93fe622d-4220-43e8-a43b-ce678fcf2386.jpg)
Do this in UDB. Notice the new 3 lines. I suspect the creation of extra subsectors might have fixed it
- [x] 6. Texture on lines 1814, 1746, 1659, 1817, 1802, 1685, 1664 and 1805 need an offset of x -107, y -96.

**Comment by Ozymandias81** [comment]
Issue 5 doesn't happen with any kind of rendering API to me and I guess not anyone else from the team, you sem the be the only one to have it @hawkwind3
