### ISSUE TITLE
C2M3 - C3.1.1 more

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1019]
c2m3 ...

1. Lintel at sectors 1056/ 1233 could use an alignment.
2. Church - All the chandeliers are flickering but do not have a flame. All are flagged "dormant".
3. Some of Thing Types 19507 are not showing up. Some are flagged "dormant".
4. Can clip through T3077. Just needs moving a bit closer to the wall, like T3072.
5. T3256 and T3259 should not be flagged "dormant". There is light flicker.
6. Shouldn't I be seeing flames from the fireplace at x 17035, y -790, like the fire at x 13236, y -864 ?
7.  Using UDB ( Q ), fixing the alignment of one of sectors 1070 ( 3D floor ) ( x 0, y -50 ) negatively affects the other. Sectors in game are 1058, 1229, 1233 and 1056.

**Comment by hawkwind3** [comment]
Church main doors ...

8. Currently, only the right hand door ( from outside, facing the church doors ) opens, even if trying to open the doors from the left door. This does not make sense.
A simple fix ...
Copy lines 8464, 8465, 8459 and 8460 ( I had snap to geometry off ) 96 map units north, then just delete type and tag from said lines. Worked perfectly for me. :)

**Comment by Ozymandias81** [comment]
8 That's intentional, it gives you some surprise effect and also grants you coverage

**Comment by hawkwind3** [comment]
I don't think you understand. With my fix, the coverage is still there. The thing is, with the fix, the player, when outside the church, cannot open the right hand door by "activation/use" of the left hand door. Just makes sense. Currently it does not.

**Comment by Ozymandias81** [comment]
9 why it should be like that? It would look odd and empty this side of church facade
![image](https://user-images.githubusercontent.com/11136108/132855051-ade755ba-728b-438a-8c28-cd0d434b121d.png)

**Comment by hawkwind3** [comment]
re. point 9 ... Sorry I wasn't clear yet again. What I was thinking, is that the first screenshot could be completely walled off. Not a big deal.
Regarding my third screenshot, if you look hard you will see a 1mp gap where vertex 4004 is. There needs to be a line here going to line 5040 and fixed accordingly.
