### ISSUE TITLE
[ADDONS] Can't open the door when max amount of gold has been reached

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1024]
When using the score addon, you can get extra bonus', incl. extra gold. That also means that when playing all missions you might get upto 9999 (and no more). But when you wanna grab this gold item in c2m0_a to open the door, you can't, because the max has been reached.

![Screenshot_BoA_20210807_230622](https://user-images.githubusercontent.com/77861029/128616550-b63e077d-5e7f-4e97-ba55-3516ead23078.png)

**Comment by AFADoomer** [comment]
This is related to the other coin amount bug that you are reporting.  You shouldn't get that many coins, ever, so this should not be a problem if that is fixed... With your current score, you should have only received ~3500 bonus coins.

**Comment by x3003** [comment]
>You shouldn't get that many coins, ever,

Sorry, I can't help it. I just play the game and report back when there's a problem. Maybe the door should open when you touch the gold, not grab it ?!

**Comment by AFADoomer** [comment]
I think it's because you were also using the efficiency add-on...  Coins and treasure need to be exempted from its handling.

**Comment by Tormentor667** [comment]
Added "+INVENTORY.ALWAYSPICKUP" to the CoinItem base actor, this should solve this issue here.
