### ISSUE TITLE
different u-boat ?

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1029]
With the 3.1 release version, when you compare the captain's area of the u-boat, in c2m6_b it has alarm panels, but not in c2m6_c.

![Screenshot_BoA_20210808_170341](https://user-images.githubusercontent.com/77861029/128759276-9c9a963f-6dc6-4fc3-8043-78ea303f6bfb.png)

![Screenshot_BoA_20210808_170405](https://user-images.githubusercontent.com/77861029/128759158-ca092775-3423-4945-9f3f-6e002b656314.png)

**Comment by hawkwind3** [comment]
Just to add .... there are no alarm bells ( Type11516 ) in either sub and note the height difference with the periscopes.

**Comment by Ozymandias81** [comment]
I have already fixed it, just need to commit. Regarding alarms, it is fine that they are not there on c2m6_c, since they are useless in place there.

**Comment by Ozymandias81** [comment]
It is not a matter of continuity, those are actors meant to be placed on purpose. When playing SuperMario, for example, do you still get coins if you bump the same place when you repeat a level when losing a life? It is not about a glass of water on the table or a body of an enemy placed on the sector, it is like that if you had gold chests there on previous map, you get them and then see there again on next map.

**Comment by Tormentor667** [comment]
I will just take care of it ;)
