### ISSUE TITLE
Replenish to max strength instead of to half.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1034]
As a suggestion, it would be nice when you have a shield that has 200% strength, you can pick up items to replenish it from 101 - 200% again. Now you only do this till 100%.

**Comment by Tormentor667** [comment]
Yes, that would make sense, but only for "Shield Shards", not for helmets.

**Comment by x3003** [comment]
Well, there are more helmets found in the game than 'shield shards', so how to get to max strength then ?!

**Comment by Tormentor667** [comment]
It's more of a technical question. Shield Shards and Tesla Armor belongs to Astrostein where Helmets belong to the 1940's. I mean, how do you think is BJ able to recharge his tesla armor with helmets? ;) It's two types of armor.
