### ISSUE TITLE
enemies can live / fire underwater

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1035]
As said above, they can accidentally get into the water, but they can't drown and can fire at the player.

![Screenshot_BoA_20210813_141424](https://user-images.githubusercontent.com/77861029/129411197-36a82e80-5a2a-4917-aa8d-e89878e5cd8d.png)

**Comment by Tormentor667** [comment]
Instead of rewriting the behaviour, I'd suggest ensuring at these occasions, that enemies can't enter deep water. Where did that exactly happen?

**Comment by x3003** [comment]
Just at the beginning of c3m3_a, were you have the fields and the dogs.

**Comment by Tormentor667** [comment]
Fixed.
