### ISSUE TITLE
dogs can hurt you through the door

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1036]
When you touch this (thick ?) wooden door, the dogs on the other side can hurt you.

![Screenshot_BoA_20210813_162014](https://user-images.githubusercontent.com/77861029/129411800-c5fc85cc-c848-4af5-890f-920a192deb00.png)

![Screenshot_BoA_20210813_161952](https://user-images.githubusercontent.com/77861029/129411577-58b49f9c-53b2-4b9a-bd9a-039e54f133db.png)

**Comment by Tormentor667** [comment]
Fixed
