### ISSUE TITLE
[C3M6_B] Ascher can die

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1040]
Dunno if it's intended, but with the 3.1 version in c3m6_b ascher can actually die.

![Screenshot_BoA_20210821_010016](https://user-images.githubusercontent.com/77861029/130301107-96a982d0-ecc7-4471-b9cb-df9a5a0f22a8.png)

**Comment by Ozymandias81** [comment]
Did he die when touching lightnings?

**Comment by x3003** [comment]
Yes

**Comment by x3003** [comment]
With the latest git version, Ascher can still die over there.

![Screenshot_Doom_20211226_173048](https://user-images.githubusercontent.com/77861029/147414757-df4274ad-5461-4497-bf5f-afaa18dea8d4.png)

**Comment by Tormentor667** [comment]
Made the lines impassable now

**Comment by x3003** [comment]
Well, he can still die by pushing him into the light....

![Screenshot_BoA_20220610_152801](https://user-images.githubusercontent.com/77861029/173188372-d954d9a3-4eef-47d4-a413-1036161edc60.png)

![Screenshot_BoA_20220610_152808](https://user-images.githubusercontent.com/77861029/173188383-56f799ce-a1d0-4662-b93c-e0e043bd7813.png)

**Comment by Tormentor667** [comment]
This is strange, I made the lines impassable. Can the NPC walk over impassable lines @Talon1024 @AFADoomer
