### ISSUE TITLE
[C3M0_B] Zombie still trapped

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1042]
With the git version, in c3m0_b, this zombie still is trapped in his box.

![Screenshot_Doom_20210824_003845](https://user-images.githubusercontent.com/77861029/130528951-35afe6a8-d988-44b7-a560-e8d1ceb67c73.jpg)

**Comment by Ozymandias81** [comment]
Does it happen with 3.1 release under gzdoom 4.6 ?

**Comment by x3003** [comment]
Yes, I tried 3.1 & git.

**Comment by Tormentor667** [comment]
Found the bug and fixed it, can you retry if it works now?

**Comment by x3003** [comment]
> can you retry if it works now?

My connection is a bit slow, so after 350-400 MB the download somehow is cut off. So i'll try when I get my hands on the archive.

**Comment by Tormentor667** [comment]
Thank you for testing it again!
