### ISSUE TITLE
map marker

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1043]
If you mark something on a map, shouldn't it start w/ a 1 instead of a 0 ?

![Screenshot_BoA_20210828_154700](https://user-images.githubusercontent.com/77861029/131228001-a0c62d8d-3631-4388-9a50-46fbc32e14cd.png)

**Comment by hawkwind3** [comment]
No. Starting with 0 is doom behaviour. Start doom2.wad with gzdoom. Place a marker. It is 0.

**Comment by x3003** [comment]
Could be, but this doesn't mean it's correct.

**Comment by hawkwind3** [comment]
It's not a matter of "could be", it is just doom behaviour, unless the BOA devs have changed this before.

**Comment by Tormentor667** [comment]
We didn't, so it's actually an engine behavour. We suggest to report this on zdoom.org

**Comment by Talon1024** [comment]
It is possible to make the map marker numbers start at 1. The map marker number graphics (AMMNUMx) are defined in TEXTURES.txt, and the first one is [AMMNUM0](https://github.com/Realm667/WolfenDoom/blob/b2d01e1fb672ade08affd48e94b9d669d78ed745/TEXTURES.txt#L808).

**Comment by Tormentor667** [comment]
Am I hearing a volunteer? ;)
