### ISSUE TITLE
not hiding in box

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1044]
If you don't step on the platform (to hide in the box) fast enough [because it raises at some point], shouldn't you get a 'failed' on your screen instead of being able to continue ?

![Screenshot_BoA_20210827_224933](https://user-images.githubusercontent.com/77861029/131228050-c05b3c1d-057d-4950-8d09-62f6e6d1c9ef.png)

**Comment by Tormentor667** [comment]
Fixed
