### ISSUE TITLE
[C3M6_B] No bridge anymore

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1047]
With the 3.1 version, after the main battle the bridge is gone and the distance is too large. so you can't go to the castle anymore.
Dunno if it has anything to do w/ it, but I played w/ more weapons, low res & behaviour add-ons.

![Screenshot_BoA_20210829_134322](https://user-images.githubusercontent.com/77861029/131249604-c9004f7d-19fe-454f-a517-c39448ba4074.png)

**Comment by Tormentor667** [comment]
This is certainly strage, the script for the bridge is triggered by Hitler's death. It raises the stairs but also does a few more fancy things like deactivating swirls, deactivating floating objects and setting the misson objective with killing Hitler to accomplished. So, did all of that not happen or just the staircase builder not?

`//Stair Builder
	Stairs_BuildDown(377, 10, 16, 0, 0);
	floor_raisebyvalue(378, 60, 2560);
	ChangeFloor(391, "textures/BRIK_R56.jpg");
	SetSectorDamage(378, 0, "", 0, 0);`

This is the responsible part of the script, that raises the staircase.

**Comment by x3003** [comment]
On the previous run I did w/ some other add-ons only part is gone (as it should be ?) and you'll able to jump to the other side.
On this run, a complete section w/ the lights has been dropped, so you have a bigger gap.

**Comment by Tormentor667** [comment]
The question is: Is it reproducable on the same combination of addons or not? Maybe you can cheat the map and let us know if it is.

**Comment by x3003** [comment]
Yes, it's reproduceable. Also without add-ons. Same result.

![Screenshot_BoA_20210830_021700](https://user-images.githubusercontent.com/77861029/131270250-d07b57ae-e84d-40e8-8d53-315080464073.png)

![Screenshot_BoA_20210830_021807](https://user-images.githubusercontent.com/77861029/131270300-70885aa2-6898-4fb0-ab70-96703b09fc1a.png)

**Comment by x3003** [comment]
I reloaded my file which I've done w/ Eff/more weapons/score and it look like this.

![Screenshot_BoA_20210830_213401](https://user-images.githubusercontent.com/77861029/131395000-b3c29013-3a31-4533-912b-e6f25cf4c784.png)

**Comment by Tormentor667** [comment]
I did some experiments with testing the final battle and I have a suspicion now. I added a debug script (type "pukename fbdebug" to teleport to the final battle and initiate it) to test the final battle at any moment.

For now I think that you have been very fast with killing hitler, so the floor of the stairs was still lowering while he died and which made them not raise again. To fix this, I sped up the lowering of the staircases and on the other hand added a tagwait to the final script after killing Hitler.

Can you retry and let me know if that fixes the problem?

**Comment by x3003** [comment]
That seems to work. First I tested it w/ an older git version, then w/ this new map.
Only now part of the path doesn't collapse anymore, or wasn't that the idea ?

![Screenshot_Doom_20210831_222805](https://user-images.githubusercontent.com/77861029/131571765-7bc77266-fb56-4757-bde3-0d89ffdabc74.png)

**Comment by Talon1024** [comment]
> For now I think that you have been very fast with killing hitler, so the floor of the stairs was still lowering while he died and which made them not raise again. To fix this, I sped up the lowering of the staircases and on the other hand added a tagwait to the final script after killing Hitler.

If that's what's happening, you can call [TagWait](https://zdoom.org/wiki/TagWait) on each of the stair sectors to ensure they finish moving before moving them again.

**Comment by Tormentor667** [comment]
> 
> If that's what's happening, you can call [TagWait](https://zdoom.org/wiki/TagWait) on each of the stair sectors to ensure they finish moving before moving them again.

That's what I did, and now we have a new issue... but why?!

**Comment by Tormentor667** [comment]
Is this still reproducable or is it fixed meanwhile?

**Comment by Tormentor667** [comment]
Very good, thank you!
