### ISSUE TITLE
hollow leg

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1048]
With the 3.1 version, the leg of this statue is hollow, so you can go through it.

![Screenshot_BoA_20210829_134313](https://user-images.githubusercontent.com/77861029/131249685-73c427af-f075-4aec-9c00-bce202472836.png)

![Screenshot_BoA_20210829_135746](https://user-images.githubusercontent.com/77861029/131249688-16d5ebef-83b7-4690-877e-d38f23bb7760.png)

**Comment by Tormentor667** [comment]
Fixed
