### ISSUE TITLE
Word not in the middle

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1050]
With the latest git, the word 'Schlangenkopf' is not in the middle, but rotated, so a bit of the 'S' is on the right side of the screen.

![Screenshot_Doom_20210918_225632](https://user-images.githubusercontent.com/77861029/133908641-ed265899-c71e-4b3f-a5c1-ddc85e97467f.png)

**Comment by Tormentor667** [comment]
Does this only happen for this single screen? That’s strange because all of the offsets are exactly the same

**Comment by x3003** [comment]
Yes, there is no operation w/ a word that is this long.

**Comment by Tormentor667** [comment]
Found the issue and fixed it.
