### ISSUE TITLE
[3.2] AI player shoots surrendered enemies.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1053]
Not sure if something can be done about it, but i'll mention it anyway.
It's quite annoying that an AI player shoots at an enemy who have already surrendered.
Can this be changed ?

**Comment by Tormentor667** [comment]
@AFADoomer is this even possible?

**Comment by Username-N00b-is-not-available** [comment]
Noticed that enemies are too unlikely to surrender now, could not even test this...

**Comment by Username-N00b-is-not-available** [comment]
Yeah, confirmed this by spawning ```AscherArmed``` near a surrendering scientist on C1M2. Shall see what can be done...
