### ISSUE TITLE
[INTERMAP] Collectible Trophies can be "picked up" in Briefing Room.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1054]
Sourceport: GZDoom v4.6.1 (from Delta Touch v4.5)
Affected Level: INTERMAP
Issue: When you own at least one of the three Collectible Trophies (Cacoward, Naziward, Keenaward), you can bump into them within the Briefing Room and erroneously pick them up, triggering their pickup message and removing them from the map, though this thankfully doesn't add to your Gold stash. This can be repeated after each main mission, every time you enter INTERMAP.

**Comment by Talon1024** [comment]
Hopefully fixed in 6fc43720415f03bccf351e63363c0d0f6179ed4d
