### ISSUE TITLE
[C1M2] Enemies can detect player through Yellow Key Door, will attempt to shoot through it.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1055]
Sourceport: GZDoom v4.6.1 (through Delta Touch v4.5)
Affected Level: C1M2 (Operation: Exodus)
Issue: When you step through the prison entrance, and fight any hostiles within, enemies lurking beyond the Yellow Key door can see and hear the player, even going so far as to trip the alarm on their own. In addition, they will attempt to shoot through the (impenetrable) door if the player is within their view.

![Screenshot_2021-09-25-08-28-51-737_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/134773357-18817ffd-fc5b-4081-82b3-8b59fedf0462.jpg)

**Comment by MuadDib90** [comment]
This is not an issue, since it was deliberately changed to this state quite time ago (maybe a month? idk) after some "issue report" of soldiers not moving, even if they can "see" you through the door.

So this can be closed @Shockwave508. :)

**Comment by Shockwave508** [comment]
Aye.
