### ISSUE TITLE
[3.2] [INTERMAP] Meal "pickups" half-buried in the bar's tables.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1056]
Sourceport: GZDoom v4.6.1 (within Delta Touch v4.5)
Affected Level(s): INTERMAP, likely others too.
Issue: It seems that with certain table models/meshes, the meal "pickups" are partially-buried into them.

![Screenshot_2021-09-25-11-25-44-868_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/134778741-b3e064de-12ab-4564-9c0b-96f9149428f0.jpg)
![Screenshot_2021-09-25-11-25-51-210_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/134778751-a110d4be-f57a-44b6-a074-db335283a079.jpg)

**Comment by Tormentor667** [comment]
I can confirm this. Something has changed with the spawn offsets making the meals spawn too low.

**Comment by x3003** [comment]
It's not only in the bar, but also during missions.

**Comment by Tormentor667** [comment]
It's a general problem with how high the table master actors spawn the meals. Maybe @Ozymandias81 can take a look.

**Comment by Username-N00b-is-not-available** [comment]
These meals were spawned on height 24 instead of 27 as for all other items...

**Comment by Ozymandias81** [comment]
I remember adding those values in order to workaround scaled tables in maps. Wonder now how much it changed between 4.6.1 and 4.10
