### ISSUE TITLE
[Feature Request] Achievement Progress/Par Time trackers

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1057]
For certain cumulative achievements, would it be possible to "tag" them from the Briefing Room, so you can keep track of them during missions? Hard limit would likely be three at a time, like Doom Eternal's challenge trackers. 

There's also no real way to check your current mission's Par Time in-game, for the Speedrunner achievement (short of using the console to manually bring up the achievements menu). Would it be possible to display that underneath the Gold/Total Time display in the upper-left corner?

**Comment by Tormentor667** [comment]
I think the second suggestion is quite simply and @AFADoomer or @Talon1024 most propably should know how to do it. Regarding the first suggestion, no idea how hard it is to implement these though.

**Comment by Shockwave508** [comment]
The current implementation of the optional Par Time tracker seems a little "cramped" with nothing to differentiate level time and par time in the HUD. (i.e. ##:##  ##:##)

The way I think it might be better-implemented IMO would be three lines, top would be current level time, middle would be par time, with some sort of icon or other identifier, and bottom would be total game time, as always.

**Comment by Tormentor667** [comment]
That's a good suggestion

**Comment by Tormentor667** [comment]
As @AFADoomer is currently back in business here, I just would like to point you towards this. Is it easy to add and worth the effort?

**Comment by AFADoomer** [comment]
Updated the par time display in e789aa0577e28464718a853de330b2bf8cc5a1bf.

**Comment by Tormentor667** [comment]
Thank you! So this can be closed
