### ISSUE TITLE
who's fault is the terrible performance issues on large maps?

### ISSUE THREAD

**Issue by RichardEllicott** [Realm667/WolfenDoom#1060]
so i just upgraded my computer, while BOA is playable for me now, many maps E1M3 E2M3 spring to mind so far, have terrible CPU bottleneck issues

an issue i tried with GZDoom said it's the devs of BOA's fault, ignoring optimisation guidelines... however it just seems like BOA is just expanding in a logical direction (bigger levels)

is this problem with the BSP system in GZDoom?
It all seems a great shame.... people with older machines would love to play this game.... people with machines at my speed are less likely to bother

**Comment by Talon1024** [comment]
To see what the performance bottlenecks are, you could try entering `profilethinkers t` or `stat rendertimes` into the console.
