### ISSUE TITLE
[Feature/Game Mode Suggestion] Unlockable Challenge Arenas, like The Old Blood

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1061]
Currently, there is only one game mode in BOA, which is the three-episode campaign. Is it possible to implement unlockable Challenge Arenas as you progress through the story, much like those of _Wolfenstein: The Old Blood_? In that game, these are special, sectioned-off areas of the campaign, designed to throw a designated number of waves of Nazis, zombies, and what else have you at the player, leaving him with his skill, wits, and the resources at his disposal to survive as long as possible. However, in BOA's case, new maps would have to be built from scratch, to resemble more open-ended versions of various areas from the main campaign. In my opinion, it could help increase the longevity and replay value of the proposed co-op gameplay I've been hearing about.

**Comment by Tormentor667** [comment]
As this is a very nice idea, there is currently no plan or interested, to implement such a feature. The main goal now is to make the whole game coop-compatible and from then on, people are open to create their own additional content for BoA :)
