### ISSUE TITLE
New style grenades in hades mission

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1064]
With the latest git version. If you just did c2m0_b and are now doing c2m6_a/b , the grenades are still the ones as the previous mission. Even if you grab the old style grenades in the mission.

![Screenshot_Doom_20211017_173215](https://user-images.githubusercontent.com/77861029/137646453-2a363734-3a74-4491-87f2-53b1ef3c7ee4.png)

![Screenshot_Doom_20211018_000632](https://user-images.githubusercontent.com/77861029/137646653-6f03b9e3-baa3-4027-8101-6c27450de615.png)

**Comment by x3003** [comment]
Well, somewhere in c2m6_b they got to the oldstyle again, suddenly. Strange...

**Comment by Talon1024** [comment]
Yes, that's because you ran out of "Astrostein" grenades.
