### ISSUE TITLE
Critters can't drown

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1068]
The critters can't drown and walking as if the water doesn't exist. Can this be fixed ?

![Screenshot_Doom_20211017_140816](https://user-images.githubusercontent.com/77861029/138569594-43a879e9-62b8-4e03-bd63-a8627f054cc6.png)

**Comment by Tormentor667** [comment]
I think that's most propably doable, but a job for @Ozymandias81 @Talon1024 @AFADoomer

**Comment by AFADoomer** [comment]
Fixed in c04932c89e9d1d720180d40d2a8f8f4c9bce716a.
