### ISSUE TITLE
wrong texture

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1070]
With the git version, in c2m1, this texture should ofcourse be snow instead of a cloud.

![Screenshot_Doom_20211114_152713](https://user-images.githubusercontent.com/77861029/141685505-1c4552f2-faa0-4b87-a5f2-7a1622818838.png)

**Comment by hawkwind3** [comment]
I actually reported this one some time ago ...

https://github.com/Realm667/WolfenDoom/issues/971. See last post point 14.

Actually, I think the devs should look at my whole "closed" issue for this map. Have they all been fixed ?

**Comment by x3003** [comment]
No, this one is already open

**Comment by hawkwind3** [comment]
You misunderstand. I have reopened a closed issue that should have been still open.
New open issue #1074

**Comment by Tormentor667** [comment]
Fixed
