### ISSUE TITLE
new objective should be more clearly shown

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1072]
As said, when adding a new objective, it should be shown more clearly, maybe a few seconds in red. So it shows the player better which objective has been added.

![Screenshot_Doom_20211114_152042](https://user-images.githubusercontent.com/77861029/141685711-c2b6f006-ec9f-4cc6-8c20-a5d884ed6543.png)

**Comment by AFADoomer** [comment]
Implemented in 2cfdeb26128a4f71ed011bbd59c4b7fb5f8e2b78.

**Comment by x3003** [comment]
Looks ok, but maybe a second or so longer (to read) would be appreciated.

**Comment by AFADoomer** [comment]
Why?  It's not like it disappears from the list and can't be read after the red fade-in effect...
