### ISSUE TITLE
C2M1 - closed issues but should be open

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1074]
- [x] 11. Note that the floor of sector 1296 uses the flat METL_B16. Now compare the floors of sectors 6607 and 1294. These use the floor flat WOOD_F01 and have the same floor height. So the floor of sector 1296 should be WOOD_F01. 
- [x] 13. At x -1420, y 1395, The opened gate overlaps the texture showing in-game as Zellentrakt B showing as a texture clash. Putting the sign on the opposite wall should fix.
- [x] 14. Plane/slope error at x 283, y -2464. Sky texture on slope.
- [x] 15. Lines 22020 and 22000 should be impassible ( MIDG_S13 ) . how did I miss that before ...
- [x] 16. Wrong flat ceiling of sectors 5940 and 5941. Should be METL_G52.
- [x] 17. Can partly clip into the corners of T5832 ( Type 15225 ) This should apply to other maps that use this Thing type. Applies if Thing placed diagonally.
- [x] 18. T5794 needs to be moved slightly south ( wheel in wall ) .
- [x] 19. Wrong tex on lines 10923 and 10958.
- [x] 20. Y offset issue with lines 10075 etc. They have the Y offset of 192 on their front sidedefs but should be 200. See vertex 8265.
- [x] 21. Tex MIDG_B07_SM could have also been placed on lines 10081 and 10094.
- [x] 22. This map placed dumb ( IMO ) positions for invisible chaingunners.
- [x] 23.The AA gun at x 7183, y -6984 is in mid-air.

**Comment by Tormentor667** [comment]
Fixed all
