### ISSUE TITLE
gun is black

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1077]
In c2m5_b with the git version, this autogun (and only this one) somehow is black.

![Screenshot_Doom_20211125_003802](https://user-images.githubusercontent.com/77861029/143605660-10587767-753f-4c5d-b08c-6bee5ba9876d.png)

**Comment by Talon1024** [comment]
It's been like that for a long time. @Tormentor667 should know why.

**Comment by x3003** [comment]
That's odd. All the time I (test) play I never had this problem.

**Comment by Tormentor667** [comment]
The scaling is the problem, I just fixed it.

**Comment by x3003** [comment]
Hmm, with the latest git version, the gun is still black....

![Screenshot_Doom_20211210_222729](https://user-images.githubusercontent.com/77861029/145643632-4208e6cd-d260-4c8d-95c6-852e1931fb22.png)

**Comment by Tormentor667** [comment]
Supposed to be. It's not shootable, the color indicates that.
