### ISSUE TITLE
AI player should stay out.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1078]
A small suggestion. When you enter a secret space, the AI player should stay out instead of coming with the player inside of the secret.

![Screenshot_Doom_20211121_233123](https://user-images.githubusercontent.com/77861029/144323075-85dec5ab-f2c9-4a67-bda8-fb7cb5c8e5ad.png)

**Comment by Ozymandias81** [comment]
That can't be done afaik
