### ISSUE TITLE
petrol pump issue.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1081]
Could be mistaken here, but in ww2 pretty much every car, truck and tank was running on petrol (Benzin), so putting diesel pumps *everywhere* in the game makes no sense. Maybe 1 or 2 tanks (later on the war) and subs were running diesel I believe. So maybe someone can switch some pumps to petrol ones ?!

![Screenshot_Doom_20211120_212438](https://user-images.githubusercontent.com/77861029/144324134-d8cd10f9-7890-489a-a233-1e2aeb0985eb.png)

![Screenshot_Doom_20211114_223418](https://user-images.githubusercontent.com/77861029/144324921-2312de27-a18e-4d2a-973d-e44042299ec4.png)

**Comment by Tormentor667** [comment]
Fixed
