### ISSUE TITLE
stamina issue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1082]
If you got out of breath at the end of the level and get to the headquarters, bj is still out of breath. The stamina bar should be at 100% here.

![Screenshot_Doom_20211204_163010](https://user-images.githubusercontent.com/77861029/144715957-c0d36060-d80a-454b-b2a4-79140575cd82.png)

**Comment by x3003** [comment]
This code isn't correct. When starting it now says: "boa_c3.pk3:scripts/items/sprint.zs, line 158: Unable to resolve Stamina as type.
"

**Comment by Tormentor667** [comment]
So is it still buggy?

**Comment by x3003** [comment]
Looks fine over here.
