### ISSUE TITLE
tesla shield

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1083]
If you want to buy the tesla shield, it says [100%]. Shouldn't it say [+100%] ??? It now does +100% on the current shield health.

![Screenshot_Doom_20211204_143548](https://user-images.githubusercontent.com/77861029/144716118-8ed52b28-efd3-4a05-8b4a-2b41a36c700f.png)

**Comment by Tormentor667** [comment]
Fixed
