### ISSUE TITLE
Tracers gets through walls

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1084]
If you fight the girl here, some of the laser rays from her goes through this piece of wall i'm pointing at. Esp when you move right/left.
Strange, as I can't shoot from the other side through the wall.....

![Screenshot_Doom_20211130_003348](https://user-images.githubusercontent.com/77861029/144716234-170bfba2-8780-4aea-bd7d-1992144ce90b.png)

**Comment by Talon1024** [comment]
IIRC her shots bounce off of walls and floors, which is why they hit you.

**Comment by x3003** [comment]
No, this is a direct hit through the wall. It was too fast for a screenshot.

**Comment by hawkwind3** [comment]
x3003 is correct. She shoots straight lasers. While I did not experience the issue x3003 is getting, I did notice that T5313 ( Type 15249 - Ursel Metzger ) does have quite a large diameter of 62 - wider than her height !. And her height of 56 is less than the nearby Astro Suit Guards. And she cannot walk down the nearby steps.

**Comment by Tormentor667** [comment]
Summoning @Ozymandias81 here as he coded Ursel

**Comment by x3003** [comment]
Notice, when playing at the lowest level she isn't so aggresive, so she doesn't fire very often. But when you play it at almost the hardest level she reacts faster and fires the laser more, which sometimes goes through the wall. So if someone wants to test, don't use a lower level.

**Comment by hawkwind3** [comment]
I can finally confirm x3003's issue with Ursel. If the right conditions are met, it does happen. Seems to be angle related. For example, If Ursel is at or near line 28741 and the player is near or at sectors 6879/6899, she does indeed shoot through lines 28502/28496 and maybe even line 28563.

**Comment by Ozymandias81** [comment]
I did a [commit](https://github.com/Realm667/WolfenDoom/commit/135087099389a6e03f58a2d5d9a35de65224e8a9) a couple of days ago, this is related to something coming from BulletTracer... I am investigating the issue, but idk if I'll be able to fix it, it though doesn't seem related to EffectManager since I did a test comment out related lines from BulletTracer and the issue is still there.

**Comment by Ozymandias81** [comment]
Noticed something today: if I use PlayerTracer instead of BulletTracer as inherit class, the projectile works as expected, but it is not green obviously @AFADoomer @Talon1024 @Username-N00b-is-not-available

**Comment by Tormentor667** [comment]
What are the differences between the two?
