### ISSUE TITLE
misplaced items

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1086]
With the latest git version these are a bit misplaced in c3m0_b.

This barrel clips through an item.

![Screenshot_Doom_20211211_134240](https://user-images.githubusercontent.com/77861029/145677598-6a44ed3d-d4af-4767-a21e-e56667ca3849.png)

These guns aren't black, but they could never work right, as they are too close to the wall.

![Screenshot_Doom_20211211_135509](https://user-images.githubusercontent.com/77861029/145677603-12f18c4e-7b9b-4395-a21b-0e4ac18ace04.png)

![Screenshot_Doom_20211211_135519](https://user-images.githubusercontent.com/77861029/145677606-51e8ac1a-ef45-4e20-8364-c58bad87d880.png)

**Comment by Tormentor667** [comment]
Fixed

**Comment by x3003** [comment]
Eh, no it isn't.

![Screenshot_Doom_20211214_221608](https://user-images.githubusercontent.com/77861029/146080971-03ee1263-d713-4752-8ba7-70068b11cac7.png)

**Comment by Tormentor667** [comment]
Sorry my fault I only fixed the turrets

**Comment by x3003** [comment]
Hmm, strangely the turrets are now black.

![Screenshot_Doom_20211216_220824](https://user-images.githubusercontent.com/77861029/146450553-82bf2e8d-6bcc-48f0-9d61-53fe15ef73d2.png)

**Comment by Tormentor667** [comment]
Supposed to :)
