### ISSUE TITLE
pipes sometimes missing

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1087]
With the latest git version and gzdoom 4.8 pre89, in c3m0_b, these pipes are sometimes missing depending on your position.
It sometimes needs just 1 step to show/hide the pipes.
And these square bars (where the pointer is) in the third image shouldn't be there I think. They just don't look right.

![Screenshot_Doom_20211211_135216](https://user-images.githubusercontent.com/77861029/145677860-727c266e-1f21-42d1-b069-caf17ae7c172.png)

![Screenshot_Doom_20211211_135223](https://user-images.githubusercontent.com/77861029/145677863-a6d3d6a6-9e83-4fbc-b868-25fd4eb80c8f.png)

![Screenshot_Doom_20211211_135238](https://user-images.githubusercontent.com/77861029/145677886-68bcaf4b-97ea-4c57-af13-a9da6e0f0d1a.png)

![Screenshot_Doom_20211211_135303](https://user-images.githubusercontent.com/77861029/145677889-ed0acb93-cc33-4959-b6b1-8689c961a768.png)

**Comment by hawkwind3** [comment]
Basically already reported with #996 . Even so, I did not notice the first 2 pics when I played this, although obviously related to the same model.

**Comment by hawkwind3** [comment]
Yes. Also, have a look under the 3D floor where the model is. The open pipe does not look good IMO. The square box is a model issue, as it is part of the model. Would have to be reworked to remove. The simplest solution would be to remove T1974.

**Comment by Ozymandias81** [comment]
Regarding barrels, since they where working fine before (I mean not clipping thorugh walls, at least they where like that when I DID the code for them) I think it should be related to GZDoom, so better also playtest it with 4.6.0 and 4.7.0 using 3.1 release.

**Comment by x3003** [comment]
It's also present in the v3.1 release version.

![Screenshot_BoA_20211215_232613](https://user-images.githubusercontent.com/77861029/146274631-4c93872b-406c-4413-bcc6-d29c4d60c8b6.png)

![Screenshot_BoA_20211215_232616](https://user-images.githubusercontent.com/77861029/146274635-e7896a87-718d-4697-a24e-d6fa11cfac53.png)

**Comment by Ozymandias81** [comment]
I said about barrels, not disappearing models which is a limit present in GZDoom that can be circumvent by using RenderRadius, as I did yesterday.

**Comment by x3003** [comment]
This new model of the pipes doesn't dissappear anymore. So that's good.

**Comment by Tormentor667** [comment]
Awesome!
