### ISSUE TITLE
hitboxes in the way

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1092]
In c3m5_b you'll find a few areas where the hitboxes are still in the way. Maybe this can be fixed ?

![Screenshot_Doom_20211225_213020](https://user-images.githubusercontent.com/77861029/147414864-33bc6abb-f4e9-4329-9621-1ebac138dd1b.png)

![Screenshot_Doom_20211225_213118](https://user-images.githubusercontent.com/77861029/147414869-5e2ba9f3-94b5-4d42-9edf-84a2771f51a5.png)

![Screenshot_Doom_20211225_213248](https://user-images.githubusercontent.com/77861029/147414872-e656daae-d472-49f1-91d7-9c6103c96051.png)

![Screenshot_Doom_20211225_213846](https://user-images.githubusercontent.com/77861029/147414876-2f2dfa90-8d4d-40ce-b970-fe5a8bd58684.png)

**Comment by Tormentor667** [comment]
The problem with the rubbish is that the hitboxes are always cubes but the actual objects are pyramids. We unfortunately can't do anything here, so I have to close this unfixed.
