### ISSUE TITLE
C1M6: (from CaptainJ) Bats' idle frame is wrong i think.

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1097]
![grafik](https://user-images.githubusercontent.com/10298439/147454149-c9ce735d-0c70-497d-ba2a-6d933aae2fbe.png)

**Comment by AFADoomer** [comment]
These bats are tagged as dormant, and get activated when the player picks up the coins in the back of the room (It's supposed to be a trap, so the player can kill the scorpions, feel safe, then get attacked by bats when they pick up the coins).

It's been set up like this as long as I can remember.
