### ISSUE TITLE
(from CaptainJ) I guess you really can't miss this switch? Although it doesn't glow so you could miss this and i actually did miss it and had to watch pagb666's vid...

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1098]
![grafik](https://user-images.githubusercontent.com/10298439/147454174-02d70c07-7157-4821-889c-682202a0a247.png)

**Comment by x3003** [comment]
Did he mean this very well lit switch ?! This is w/ the latest git version.

![Screenshot_BoA_20220117_234602](https://user-images.githubusercontent.com/77861029/149845623-a085fd3f-94c3-4518-b445-183ce88b3a9a.png)

**Comment by Tormentor667** [comment]
I think so, it's quite bright lit.
