### ISSUE TITLE
[Suggestion] Text colors for startup screen

### ISSUE THREAD

**Issue by alexey-lysiuk** [Realm667/WolfenDoom#11]
Apple OS X version of GZDoom doesn't implement Hexen style startup screen yet. Doom style screen is displayed independently from the mod's settings.
Startup foreground and background colors are set the same value in [gameinfo.txt](https://github.com/Realm667/WolfenDoom/blob/master/gameinfo.txt#L4). The result is not quite pleasant. Is it possible to change the colors to have different values?
![boa_osx_startup](https://cloud.githubusercontent.com/assets/777125/14231820/61915c80-f99a-11e5-872a-8c74400723f8.png)

**Comment by Tormentor667** [comment]
Unfortunately not as it would break the Hexen startup screen

**Comment by alexey-lysiuk** [comment]
I see. I will try sort it out from the engine side.
