### ISSUE TITLE
[CaptainJ] The first final boss does not bleed. But tbh, it really does.

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1100]
![grafik](https://user-images.githubusercontent.com/10298439/147454243-17452a33-be4f-4a52-8a50-eefaad23ef23.png)

**Comment by AFADoomer** [comment]
What does this even mean?

**Comment by Tormentor667** [comment]
Pointed CaptainJ towards this.

**Comment by Ozymandias81** [comment]
Flagged invalid for now until further reply

**Comment by Tormentor667** [comment]
ANSWER FROM CAPTAINJ:
-----------
[More explanation about the first final boss bleeding.](https://streamable.com/lnmvmo) As you can see, it REALLY bleeds. As in literal way. See the blood splat flying around.

Also voice during the video is not mine!! I've been playing Vinesauce vid while doing things.

**Comment by AFADoomer** [comment]
Should be fixed after b28745708a87acb9ce820b427e5160e02f67fc9e.
