### ISSUE TITLE
[CaptainJ] Terrain audio error is there. Nazis would play grass footstep sound while they're in a building made out of concrete and stuff. That's weird.

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1101]
_Terrain audio error is there. Nazis would play grass footstep sound while they're in a building made out of concrete and stuff. That's weird._

**Comment by AFADoomer** [comment]
Where is this happening?  We need to know the floor texture in order to check the terrain definitions.

**Comment by Tormentor667** [comment]
Pointed CaptainJ towards this.

**Comment by Tormentor667** [comment]
ANSWER FROM CAPTAINJ:
-----------
Sure thing. Maybe i couldn't elaborate more or just made things more complex. Thankfully i had a spare time to go through Episode 1 again and record the videos that corrects said issues. So here we go, the first issue:

[Terrain textures playing wrong sounds.](https://streamable.com/el641f) As you can see, a few stone bricks and tiles play grass footstep sound effects for some reason, like what i described before. I recorded through every single levels of Episode 1 and eventually will search through Episode 2 and 3.

IDMYPOS is off but i do hope each area is remarkable enough to find them easily.

EDIT: The last part where BJ kicking the poor carpet is to point out that kicking impact quakes, and plays a bit of earthquake sound effect. Just noticed that while playing the game without the music.
