### ISSUE TITLE
[CaptainJ] Keys like Gold, Bronze, Silver and Catacomb ones are really good at being blended in the environment.

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1102]
_Keys like Gold, Bronze, Silver and Catacomb ones are really good at being blended in the environment. Plus they're small and don't glow in the dark at all so that made me roam around for 5 solid minutes there._

**Comment by Tormentor667** [comment]
What about adding a subtle glow to them?

**Comment by AFADoomer** [comment]
I think this is resolved now?

**Comment by Tormentor667** [comment]
It is!
