### ISSUE TITLE
medic field kit issue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1104]
With the latest git version. When you get the medic field kit and already have max health, the item still tries to heal you and show the icon.

![Screenshot_Doom_20211226_221441](https://user-images.githubusercontent.com/77861029/147511216-7ea0ba32-9df3-4129-b7da-e56798cf1307.png)

![Screenshot_Doom_20211226_215624](https://user-images.githubusercontent.com/77861029/147511317-56487c9f-f272-4fff-9324-70011c58c3c3.png)

**Comment by AFADoomer** [comment]
Should be resolved as of d6097e4b5196ba85f12bb7788441d17401397345.

**Comment by x3003** [comment]
Yes, seems fixed
