### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1105]
After the big fight, when bj and ascher meet again, in the endscript there's a typo. It now says "Hitler's dead". It should ofcourse be "Hitler is dead".

![hdead](https://user-images.githubusercontent.com/77861029/147512229-bffb5740-0b48-4fa3-882a-c93884796ef0.jpg)

**Comment by Tormentor667** [comment]
Fixed in spreadsheet
