### ISSUE TITLE
[3.2] Checkbox for enabling cheats when launching multiplayer games with launcher

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1107]
@mgrinzPlayer would you be so kind and could you add a checkbox to the multiplayer launcher that activates cheats on the server? (by adding '+sv_cheats 1' to the batch). This helps a lot for testing purposes.

**Comment by mgrinzPlayer** [comment]
Do you still need this checkbox?

**Comment by Tormentor667** [comment]
Yes, that would still help :)

**Comment by mgrinzPlayer** [comment]
You can close this issue.
