### ISSUE TITLE
[Coop] Tilt doesn't get resetted by respawn

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1111]
![2021-12-29_161425](https://user-images.githubusercontent.com/10298439/147676521-3ea236be-05ee-491a-9dd9-232ffb68668d.jpg)
When respawning in a multiplayer session, the visual tilt doesn't get resetted. Instead it stays.

**Comment by AFADoomer** [comment]
This should be resolved as of 4540e9f7f97c4a32edb00e6ff5b1336c2741b305.
