### ISSUE TITLE
[Coop] Player two using secret safe crashes player one

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1116]
![grafik](https://user-images.githubusercontent.com/10298439/147688208-2a11a17f-8d47-443f-961b-49ddd72726ed.png)

**Comment by Tormentor667** [comment]
Is there a specific reason for reopening it even though you fixed it?

**Comment by AFADoomer** [comment]
It closed automatically (by accident) when I used the word "fix" in the commit message.  I re-opened it so that the fix could be validated - I only tested by playing against myself on the same machine, not a real coop session.

**Comment by Tormentor667** [comment]
I can do a second coop session with a friend of mine in the first week of January, and then validate it. 

Let’s try to get all the bugs out of the way until then as the friend doesn’t have so much time available

**Comment by Tormentor667** [comment]
Still hadn't time yet to test it yet, but I consider it fixed until the second playthrough happens. If I find the bug still open, I will post another issue.
