### ISSUE TITLE
repairkit not needed

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1119]
In c3m0_b, you can destroy the cannons and then enter the amber room w/o getting the repairkit. Intended ?

![Screenshot_Doom_20220102_030646](https://user-images.githubusercontent.com/77861029/147864152-f632a487-316b-41a4-8513-f7982c0aacca.png)

**Comment by Tormentor667** [comment]
Definitely not

**Comment by x3003** [comment]
If you're fast, you can still use the switch to get in w/o using the repairkit.

![Screenshot_BoA_20220123_233833](https://user-images.githubusercontent.com/77861029/150700950-3c2e27c3-950d-4f6f-b471-6e316e24dc26.png)
