### ISSUE TITLE
C2M1 - updated issue #1074

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1120]
Issue #1074 states all issues fixed but this is not quite the case.

- [x] Point 17 - The other Thing Type 15225 that can be clipped through diagonally is T2388.
- [x] Point 19 - Not fixed. Lines 10923 and 10958 need the texture CABN_T06 instead.
- [x] Point 20 - Back sidedefs of lines 10080, 10079, 10078, 10077, 10076, 10075, 10074, 10073, 10072 and 22820 need a Y offset of 200. Partly my fault. I only stated front sidedefs before ...
- [ ] Point 22 - The invisible, non-shootable automatic turrets claim to be fixed. But they are still in the map. Thing Types 12788.

**Comment by Tormentor667** [comment]
Point 22 won't be changed, it's by design wanted. Rest is fixed.
