### ISSUE TITLE
[3.2] Message before train crash is too early

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1121]
In c3m5_a, the script where ascher says "UH OH!" just comes a little too early, just before the accident.

![Screenshot_Doom_20220107_145933](https://user-images.githubusercontent.com/77861029/148554650-f657c478-f5fc-47b4-b84a-ae978321fa3e.png)

**Comment by Tormentor667** [comment]
Well, it happens just before the crash, so he already notices, something is going wrong, isn't that fine?
