### ISSUE TITLE
[3.2] Ascher doesn't react towards fire-summoning SS

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1122]
With the latest git version, in c3m6_b, Ascher doesn't react to the enemy who gives fire.

![Screenshot_Doom_20220108_162119](https://user-images.githubusercontent.com/77861029/148649906-054af2cf-4d66-4fce-a97a-006abbf9888a.png)

![Screenshot_Doom_20220108_162227](https://user-images.githubusercontent.com/77861029/148649913-6124f482-d989-4fc5-8a7e-6a1ce3b61459.png)

![Screenshot_Doom_20220108_162256](https://user-images.githubusercontent.com/77861029/148649921-fc96eae7-c008-4550-ae77-218cdc43e800.png)

**Comment by Tormentor667** [comment]
Summoning @Talon1024

**Comment by x3003** [comment]
Dunno what happened, but it seems fixed in today's built. So closing for now.
