### ISSUE TITLE
Unknown function GetStrings

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#1123]
It seems there were some changes to scripts/libraries/reader.zs that weren't committed, because BoA won't start up.

    Script error, "/home/kevinc/misc/WolfenDoom/:scripts/eventhandlers/interactionhandler.zs" line 67:
    Unknown function GetStrings
    Script error, "/home/kevinc/misc/WolfenDoom/:scripts/eventhandlers/interactionhandler.zs" line 68:
    Unknown function GetStrings

**Comment by AFADoomer** [comment]
Just pushed it.  Sorry!
