### ISSUE TITLE
item icons still active

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1126]
With the latest git version, In 1 player coop mode. After a mission, the item icons are still onscreen while being in the base.

![Screenshot_BoA_20220112_234037](https://user-images.githubusercontent.com/77861029/149409813-b7014505-1931-4381-b3e0-6ff019e423d5.png)

You can even activate the scubagear...

![Screenshot_BoA_20220116_124334](https://user-images.githubusercontent.com/77861029/149681534-37889366-42c5-4a9a-9995-0e5f418dd7ec.png)

**Comment by AFADoomer** [comment]
This is the same behavior as in Chapter 3 release...  Is this wrong?

**Comment by Tormentor667** [comment]
Seems right to me. You just shouldn’t be able to toss a grenade

**Comment by x3003** [comment]
Why should you be able to activate *any* item inside the base anyway, like the scubagear ?!

**Comment by Tormentor667** [comment]
Good point :D

**Comment by AFADoomer** [comment]
Please let me know what you think after 0ec74ba5bf411847c340f297262105363118adef.  

Hid keys, ammo and weapon info, and stealth bar, and made inventory items not activate while in INTERMAP (tied to the presence of the HQ_Checker Inventory item, so there's normal behavior in the tutorial area).

See #1126

**Comment by Tormentor667** [comment]
I like it as it is now. Should be fine, what do you think @x3003 ?
