### ISSUE TITLE
trickster issue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1127]
With the latest git version, In 1 player coop mode. After playing c1m1, I got the trickster reward. Well, in this level you only get a few keys, so ofcourse you didn't get all of the (6) keys. So this rewards shouldn't be awarded in this level.

![Screenshot_BoA_20220109_200239](https://user-images.githubusercontent.com/77861029/149410235-a5867035-3885-4277-ac88-1954c3f469f6.png)

**Comment by AFADoomer** [comment]
That's not how the achievement works...it counts the keys in the map and uses that number to check...  But the code doesn't account for multi-player coop.

This raises the question...  most achievements are designed for single player only - should we disable those achievements for multi-player?  And do we want to add additional coop achievements?

**Comment by x3003** [comment]
Well, I did get all the keys in the map, that's the odd thing.

**Comment by Tormentor667** [comment]
I think some achievements should be deactivated for coop play and some could be added for multiplayer sessions

**Comment by Tormentor667** [comment]
I will open a new issue for that case
