### ISSUE TITLE
new objective

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1130]
In c1m2, when ryan tells you to 'get out', there should be a new objective added, saying 'escape the prison' or 'rendezvous with Douglas' or something like it.

![Screenshot_BoA_20220114_171132](https://user-images.githubusercontent.com/77861029/149623120-b7c14e76-c5a4-44f7-8f2d-24d80a179629.png)

**Comment by Tormentor667** [comment]
Out of curiosity, are all 6 objectives already in use in that map?

**Comment by MuadDib90** [comment]
> Out of curiosity, are all 6 objectives already in use in that map?

In CSV there are still only 5 entries.

**Comment by Tormentor667** [comment]
Then we could indeed add that. @Ozymandias81 could you take care of that? :)

**Comment by Tormentor667** [comment]
All three primary objectives are in use so I changed the texts instead.
