### ISSUE TITLE
Enemy shoot through cars

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1132]
With the latest git versiom, in c1m4, the enemy can see and shoot through some of the cars.

![Screenshot_BoA_20220116_215620](https://user-images.githubusercontent.com/77861029/149681631-3eea2042-0212-462e-b679-3edd94019e68.png)

![Screenshot_BoA_20220116_215830](https://user-images.githubusercontent.com/77861029/149681632-7f801707-200b-4ebe-b6bd-7a0b96a747bd.png)

**Comment by Tormentor667** [comment]
Fixed
