### ISSUE TITLE
intro kicks in unexpectedly

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1133]
With the latest git version, when starting c2m1, after 1m10secs the screen becomes black and the intro video kicks in.
After  pressing [space] the intro disappears and the game continues.

![Screenshot_Doom_20220118_232626](https://user-images.githubusercontent.com/77861029/150029218-b99d882a-680d-4494-b972-5ea32c482e38.png)

![Screenshot_Doom_20220118_232633](https://user-images.githubusercontent.com/77861029/150029223-90278d9a-9ca5-40aa-a3c9-853f6f94a9cd.png)

**Comment by AFADoomer** [comment]
Should be fixed in 5ee8dc725ff7dabbd586df1f99e8516dd56d390e.  The text display and camera change script wasn't being terminated when the player skipped the cutscene.

**Comment by x3003** [comment]
Seems fixed.
