### ISSUE TITLE
INTERMAP newspaper cutscene does not end properly

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#1134]
The newspaper cutscene at the start of Chapter 1 does not end properly. The screen does not fade to black, switch to the player's viewpoint, and fade back in again. Instead, the camera just stops moving, and the sepia colour map fades to the default colour map.

This only happens if you watch the cutscene to the end rather than skipping it.

**Comment by AFADoomer** [comment]
There's an Interpolation Special point that's not needed any more that's making the script terminate early.  I'll fix it.

**Comment by AFADoomer** [comment]
Should be fixed in 05a0493f0e4a783dd985ca8e48493860b1603ebb.

**Comment by x3003** [comment]
Not sure if it comes from **this** commit, but if you watch the beginning of c3m5_c (the animation) and don't press space, when the game continues here:

![Screenshot_Doom_20220128_154617](https://user-images.githubusercontent.com/77861029/151568069-4593fa7b-74cd-4103-aed2-ac43181fca97.png)

If you now press space, the screen becomes black for a few moments.

**Comment by AFADoomer** [comment]
Should be behaving correctly in 9ac140a58d1b0d4fd75c8efc1092eab46a816293.  The button checking script wasn't being terminated after the cutscene ended anymore...  Moved that command to the proper place in the ACS script.

**Comment by x3003** [comment]
My issue seems fixed.
