### ISSUE TITLE
[3.2] Intermission key-texts not aligned at the bottom

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1135]
With the latest git version, these new texts are wrongly aligned.
A few days ago it looked like this:

![Screenshot_Doom_20220122_161019](https://user-images.githubusercontent.com/77861029/150780360-23cd5178-9c9c-40d6-b011-3924a62041a1.png)

Now it looks like this:

![Screenshot_Doom_20220124_124847](https://user-images.githubusercontent.com/77861029/150780426-01218602-3d04-4545-a4c1-d1a00ab7f411.png)

![Screenshot_Doom_20220124_124939](https://user-images.githubusercontent.com/77861029/150780441-f20e0446-693f-4699-adbd-71bfcf17e3b0.png)

**Comment by AFADoomer** [comment]
What is your resolution?  And the value of your vid_scalefactor and hud_scale CVARs?

I thought that I had tried a sampling of all screen size cases, but I must have missed something.

**Comment by x3003** [comment]
1920*1080
The problem seems only in the intermap.

![Screenshot_Doom_20220124_145348](https://user-images.githubusercontent.com/77861029/150804620-fe7e716b-188e-4833-abb1-a87ae32db5e8.png)

**Comment by AFADoomer** [comment]
What about New Objective and Objective Complete messages?  They use the same message class, so are probably also drawn wrong for you.

**Comment by x3003** [comment]
No, they are alright. It's only during the intermap.

![Screenshot_Doom_20220124_195442](https://user-images.githubusercontent.com/77861029/150846196-f3ef74a9-896a-4d41-9f69-ae22f52d4e7a.png)

**Comment by x3003** [comment]
No, it's not only during the intermap. In c1m5, the 'kill xx krauts' text is also wrong.

![Screenshot_Doom_20220124_214300](https://user-images.githubusercontent.com/77861029/150862239-3e3f1f8d-1794-45f9-ad18-62a3c58d9aea.png)

**Comment by AFADoomer** [comment]
Ok, that narrows the problem down to a single coordinate calculation being wrong.  Thanks!

**Comment by AFADoomer** [comment]
Should be resolved in 4998979ae308af9b7988f998063e6e3c41e04880...  Please test and confirm.

**Comment by x3003** [comment]
It's now in the center again, it should only get at the bottom again ?!

![Screenshot_BoA_20220126_102552](https://user-images.githubusercontent.com/77861029/151147978-8c38015a-f1b6-4c78-95bf-46a0673b5c7e.png)

Like this:

![Screenshot_BoA_20220126_102726](https://user-images.githubusercontent.com/77861029/151148073-23e79cd6-b925-459a-b28f-db2a283bbe2e.png)

**Comment by AFADoomer** [comment]
No, that's where the briefing message prompts were up until I first added the key prompt drawing.

**Comment by Tormentor667** [comment]
@AFADoomer would you leave it like that or would it make sense to pull it (the intermission one) down to the screen border as well?

**Comment by AFADoomer** [comment]
I can do either...  What's best from an aesthetic perspective?

**Comment by Tormentor667** [comment]
From an aesthetic one, I'd say pull it to the bottom as well. Seems to be more consistent to me.

**Comment by AFADoomer** [comment]
Updated in c6c99bc06df3f0ba6441b60bfa617e3c698d255a.
