### ISSUE TITLE
useless bar

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1136]
At the end of c1m6, in the 'end credits' you have this blackbar above, which doesn't mean or do anything. Maybe remove it then ?!

![bb1](https://user-images.githubusercontent.com/77861029/150970037-674f86d3-9b13-4cc7-96c5-c9ff6c378495.jpg)

**Comment by AFADoomer** [comment]
It matches the startup screen and menu headers.

**Comment by x3003** [comment]
Could be, but it doesn't do anything here.

**Comment by Tormentor667** [comment]
We could consider placing an "EPILOGUE" graphic here similar to the bar texts in the main menue.

**Comment by AFADoomer** [comment]
@Tormentor667 - Can you generate such a graphic?  Easy to implement.

**Comment by Tormentor667** [comment]
Will just commit the graphic
