### ISSUE TITLE
[coop] repairkit issue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1138]
In 1 player coop mode, when you pickup a repairkit in c3m2, if you have 1 already, you can't pickup another.
But the system says you picked up 10+ repairkits.

![Screenshot_BoA_20220125_150116](https://user-images.githubusercontent.com/77861029/150996186-939d8d7d-6370-46b7-b454-883fce188795.png)

![Screenshot_BoA_20220125_153100](https://user-images.githubusercontent.com/77861029/150996305-9742b8ed-9775-4e50-8fb5-86739eb57931.png)

**Comment by AFADoomer** [comment]
What is 1 player coop mode?

Is this the latest build?

**Comment by x3003** [comment]
I started the game as: .\gzdoom.exe -iwad boa.ipk3 -host 1 +sv_cheats 0 -skill 1 +map C3M2

It's almost the latest, as I don't have that italian translation....

**Comment by AFADoomer** [comment]
Should be resolved in 19070ca477ae05c7fdd60b1a8f20513a8cd72e6f.

**Comment by x3003** [comment]
Seems fixed.
