### ISSUE TITLE
clue text missing

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1141]
With the latest git version, in c3m1, somehow the text is missing which clue you picked up.
In a previous build from a few days ago, it would say that you picked up the zombie head, arm and so on, but not in this one.

![Screenshot_BoA_20220126_105924](https://user-images.githubusercontent.com/77861029/151256694-23ed8f4d-6425-4cc3-bcf5-eedf8a2cda3c.png)

![Screenshot_BoA_20220126_110415](https://user-images.githubusercontent.com/77861029/151256710-e084bec1-9fd2-40c8-b070-7f2b2765754d.png)

**Comment by AFADoomer** [comment]
Fixed in 12570d40b9c5ab3d118620a7def375dba0b7e138.

**Comment by x3003** [comment]
It's fixed.
