### ISSUE TITLE
secret easy found

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1143]
With the latest git version, in c1m4. you can 'find' this secret by hovering above it in the water, so you don't even have to go in the cave for it.

![Screenshot_BoA_20220116_121346](https://user-images.githubusercontent.com/77861029/151257523-02fb1d3e-8cf8-43af-9d71-15956f5c1da7.png)

**Comment by AFADoomer** [comment]
This is not new behavior; It's been this way since at least C2 release, probably before.

**Comment by x3003** [comment]
I think I reported it before, but then someone changed the cave.

**Comment by x3003** [comment]
With the latest git version, it still displays the secret while hovering above it.

![Screenshot_Doom_20220128_124108](https://user-images.githubusercontent.com/77861029/151541285-3cebc092-8085-4286-93ea-d7c20a641bf2.png)

**Comment by AFADoomer** [comment]
Please check after f9891844fc20ab905e8b58d19c2fc873f638186d.  I left an incorrect argument value in place on one of the three lines across the entrance into the secret area.

**Comment by x3003** [comment]
Seems fine now.
