### ISSUE TITLE
empty room

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1144]
In c3m4, when you get to the sealed room, there's should be some ppl in there trying to get you killed.
But somehow it's empty. Rechecked it w/ an older build from oct. and yes, it was also empty in this one.

![Screenshot_BoA_20220127_142840](https://user-images.githubusercontent.com/77861029/151431653-441b9744-74ee-456c-85b7-234130a1abe9.png)

In this one it was still full of life: https://youtu.be/8xrKxGRPg7M?list=PLoxV-no_tlqxZ78rVLDnAVZuDLX19NaXx&t=936

**Comment by AFADoomer** [comment]
I think this was intentionally changed due to issues with shots fired through the portal not actually hitting enemies.

See #906 and 5708ac7a6c918d92c8eef85f17bbb4111c91b6cf.

**Comment by x3003** [comment]
Weird, I never had problems with it. I hope you can put some ppl in, else it looks too empty.

**Comment by Tormentor667** [comment]
> I think this was intentionally changed due to issues with shots fired through the portal not actually hitting enemies.
> 
> See #906 and [5708ac7](https://github.com/Realm667/WolfenDoom/commit/5708ac7a6c918d92c8eef85f17bbb4111c91b6cf).

That's exactly the problem and it's not solvable.
