### ISSUE TITLE
double text

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1145]
With the latest git version, in c1m4, when you want to activate a bomb, you'll get a double text.

![Screenshot_Doom_20220128_123722](https://user-images.githubusercontent.com/77861029/151542185-24569d92-b06c-4eca-a958-291c1ef056a9.png)

**Comment by AFADoomer** [comment]
Should be fixed after 48eea4dc0670799dd46d3e25908346dd2684215f.  The lower key prompt will no longer draw if the message text contained in-line key prompts.  This way lines that are not fully re-translated will still show the keys below, while the default strings draw the key prompts in-line only.

**Comment by x3003** [comment]
It's fixed.
