### ISSUE TITLE
[CaptainJ] Jumpscares

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1148]
![grafik](https://user-images.githubusercontent.com/10298439/151664280-48a01c5f-4e43-4998-a174-219b574a88e4.png)

- This door reading to sniper tower killed me build engine style after trying to pass through while it was opened. The first level is traumatizing enough, but please not the jumpscares...

**Comment by Tormentor667** [comment]
I checked the polydoor in the map and there is nothing saying that the polyobject crushes when moving. No idea how this could have actually happend.

**Comment by x3003** [comment]
I've played this level plenty, but never had an issue w/ a door.

**Comment by Tormentor667** [comment]
Closed for now until CaptainJ reports back.

**Comment by Tormentor667** [comment]
ANSWER FROM CAPTAINJ:
---------
[Jumpscare not happening at the Spire Door.](https://streamable.com/i0uay6) It's very weird because i did redownload the standalone version, stood near the door, wait until it closes and i certainly died. Even if most likely does not happen on your end, the door still hurts you if you get hit by a door closing.

Just to be sure, the version of the launcher inside of the Standalone file is GZDoom 4.6.0

**Comment by x3003** [comment]
It's not the door, it's this doorpost that kills. If you walk against it, you'll be dead.

![Screenshot_Doom_20220214_231617](https://user-images.githubusercontent.com/77861029/153955983-670aece2-7987-448c-b966-81c5a8a44a74.png)

**Comment by Tormentor667** [comment]
Fixed
