### ISSUE TITLE
[CaptainJ] Script error

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1149]
![grafik](https://user-images.githubusercontent.com/10298439/151664304-fc6e503a-1303-47a3-8bb4-3cc49773ebc2.png)

- Once i killed this Sniper, this script error message appeared.

**Comment by x3003** [comment]
This should already been fixed in git. Anyone else can confirm ?

**Comment by Tormentor667** [comment]
Yes, it is
