### ISSUE TITLE
[CaptainJ] Small jewel hole

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1150]
![grafik](https://user-images.githubusercontent.com/10298439/151664316-eb2d8bf4-2b16-4359-b354-61ec8fa8621d.png)

Well, the riddles of this Mansion, lacking clues are kinda understandable to make the player figure it out. But quite frankly this Jewel hole is so small, so much easy to miss.

**Comment by x3003** [comment]
This is already changed: https://github.com/Realm667/WolfenDoom/commit/d2c470727e5273a9c0d09b8038a4df49424e81f0
