### ISSUE TITLE
[CaptainJ] Soul blocking door

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1151]
![grafik](https://user-images.githubusercontent.com/10298439/151664334-e0d342a5-3c9b-452f-b3bb-924cbbfc946b.png)
Is Cursed Soul solid? Because i was about to leave the Restroom at the Theater but then the Soul blocked the doorway and i couldn't open for a few seconds.

**Comment by x3003** [comment]
Yeah, sometimes some random stuff happens. Which is great. One time I couldn't open a door, clipped myself through, only to discover that a bat kept the door shut. Never happened again, but really funny.

**Comment by Tormentor667** [comment]
@AFADoomer @Talon1024 @Ozymandias81 could you check if the pickable Soul items are able to block poly doors? That could be the reason for this issue.

**Comment by Talon1024** [comment]
Yes, they do. @AFADoomer did this to allow soul pickups to merge together.
