### ISSUE TITLE
[CaptainJ] Eisenherz mission too hard

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1152]
![grafik](https://user-images.githubusercontent.com/10298439/151664340-1f57deb2-fd76-422a-ba8c-59896e7a453e.png)
Hello Eisenherz my ol' friend... Well in 2nd try it kinda worked out well, but spotted some problems. Don't worry, it's not about the trivial whining i gave you before. I'll be talking about sections that most of people would agree that it's kinda unfair;

![grafik](https://user-images.githubusercontent.com/10298439/151664363-6a417295-77a1-4e66-b8b3-affef5d4202e.png)
First, this Chaingun Nest section. It's hectic enough to dodge all the bullets coming from enemy vehicle from distance. But then enemies suddenly appear as soon as i enter this section. I had to approach in front of the nest because this was the only way in. The war's big, yes. But let me have just a few seconds to think. Also Allied Troops in this section are not really helpful at all but being hazardous to your health: They block your view, your path to Chaingun, and sometimes shoot you in the back.

Second, I noticed that one Tank shell isn't powerful enough to destroy the enemy tanks in one shot. I've stumbled on the section where 3 vehicles come out and they can make your tank go... Bye. Literally bye. Panzerschreck does its job right so why my tank doesn't? And for some reason Repair Kit goes missing when i save and then load the game while riding a Sherman. So you have to dismount, and then save the game to prevent this glitch.

![grafik](https://user-images.githubusercontent.com/10298439/151664372-528996b8-b62b-4bbc-be7a-ef1e3acbd713.png)
So the Stukas just stopped flying.

**Comment by Arijit746255** [comment]
This mission is very good no doubt about it however, I it will be better if the fog density can be reduced a little. It is so dense to the point of no visibility. Turning off "Fog" under performance settings\weather settings is not doing anything.

<img width="954" alt="image" src="https://github.com/Realm667/WolfenDoom/assets/68688926/673ec2eb-bbe6-41ba-b38a-791b1622fb2e">
