### ISSUE TITLE
[CaptainJ] Not falling in any cases

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1153]
![grafik](https://user-images.githubusercontent.com/10298439/151664388-f79325ba-7f4e-4a8f-a5f7-24b2612bbebf.png)
If you head to the basement, this bridge breaks and you fall. But if you walk near the corner, you're not.

**Comment by x3003** [comment]
Yes, that's right. Here you can make the **decision** to jump in the hole or to head back and continue the mission.
So it looks like this is by design, not a bug.

**Comment by Tormentor667** [comment]
Good point. As this is an optional quest in general, we can live with that.
