### ISSUE TITLE
[CaptainJ] Everdropping ceiling

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1154]
![grafik](https://user-images.githubusercontent.com/10298439/151664407-9e1628b7-2097-4ab8-b170-2dddaca1ecad.png)
 So uhh i whacked a zombie in the head with the shovel and then this blood splat got stuck on the ceiling, dripping.

**Comment by x3003** [comment]
Is this reproducible for us ?

**Comment by MuadDib90** [comment]
I have come across this "issue" couple times through my testing, but I didn't thought back them it is a problem here. It stopped after seconds. (And yes, I watched it the whole time :D )

Was never able to reproduce it if I wanted to. It always happend at random. (At least for me, that is.)
I thought - and still think - it is just "harmless engine error", which pops up when border circumstances of an engine occur.

But feel free to correct me if I am wrong. I only deduce it from a player view who vaguely knows something.

**Comment by AFADoomer** [comment]
A while back I fixed where this was happening underwater when you killed sharks, causing severe lag...  thus particular state is very hard to reproduce, though.

**Comment by AFADoomer** [comment]
This should be fixed after a673875bedded19763895088c85af2139640a47e.
