### ISSUE TITLE
[CaptainJ] Misalignment Box

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1155]
![grafik](https://user-images.githubusercontent.com/10298439/151664420-aca4ca02-44b9-4b79-9eca-df24784c19b6.png)

This box has misaligned texture.

**Comment by hawkwind3** [comment]
Line 8299 needs an X offset change from 32 to 16.

Also, I noticed that line 8117 needs an X offset change from 32 to 16.

**Comment by Tormentor667** [comment]
Fixed
