### ISSUE TITLE
[CaptainJ] Texture error behind toilet paper

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1156]
![grafik](https://user-images.githubusercontent.com/10298439/151664432-918c332f-cb3b-4663-b2f4-3329be79388c.png)
This stall has mismatching toilet paper texture. Also disappearing crapping Nazi happened again.

**Comment by hawkwind3** [comment]
Wrong X offset for line 2607. Changing from -50 to 16 looks good to me.

**Comment by Tormentor667** [comment]
Fixed
