### ISSUE TITLE
[CaptainJ] Passage is large enough actually to traverse but you can't

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1157]
![grafik](https://user-images.githubusercontent.com/10298439/151664441-ac4cc337-18ea-4c17-ae6a-c0c43efd7a84.png)
I get that you must do something to access the armory, but that passage definitely looks accessible, even though it's deceiving and is not. (forgot to turn on IDMYPOS i'm so sorry, but it's from raubgold)

**Comment by x3003** [comment]
Why is this posted as a bug ? Captainj should search a bit harder for the entrance.

**Comment by AFADoomer** [comment]
He's saying that it looks like it's big enough to crawl through (it is), but you can't (it's an impassible line).  Made the opening shorter in 875594b570c67306d223e854463cf84f9b577e28.
