### ISSUE TITLE
[CaptainJ] Fadeout intro starts again after pressing space (maybe solved already?)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1159]
![grafik](https://user-images.githubusercontent.com/10298439/151664473-0c09d0eb-2d0c-4541-810f-ada979b75936.png)
The fade-out intro starts again as soon as i enter this house for some reason. (It's in C3M6_A)

**Comment by x3003** [comment]
Already reported and fixed in issue #966
