### ISSUE TITLE
[CaptainJ] Asher can fall into pits

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1160]
![grafik](https://user-images.githubusercontent.com/10298439/151664500-dec63a3a-02b1-434a-bb02-4d1ab32e480c.png)
So uhh your companion can fall into a pit. (It's in C3M6_A, but pretty sure it can happen on anywhere if level has pits)

**Comment by MuadDib90** [comment]
I am sure, I have mentioned it quite while ago...
Wasn't it solved already? :sunglasses:

**Comment by Tormentor667** [comment]
I have no idea, was it? :D

**Comment by pphotography** [comment]
I just found a similar behaviour, Asher got stucked in a room and does not climb a ladder to get out. Map is Wolfenstein (Position is on marker 4 in the map).
![20220814_18-43-59_screenshot_Stuck1](https://user-images.githubusercontent.com/49001045/184546838-ae5f739b-2364-4b63-8ed7-f767344cf17e.png)

![20220814_18-44-45_screenshot](https://user-images.githubusercontent.com/49001045/184546851-f4df2f13-2dfe-48bf-aac5-18e0f8a79e37.png)

**Comment by pphotography** [comment]
Happened again in C3M6_B Wolfenstein. In a 'medieval' area two rocks rolled along a hallway. I got away, but Ascher was pushed to a wall he cannot get out.
![20220817_20-31-37_screenshot](https://user-images.githubusercontent.com/49001045/185216878-971306fa-f7f8-48e2-875e-4dbacd9e7c4c.png)

**Comment by Tormentor667** [comment]
I simply think that this can't be improved overall as the AI of Doom (GZDoom) is simply too limited. 

Maybe @AFADoomer or @Talon1024 can prove me wrong but as long as this issue is not gamebreaking and just cosmetic, I'd close this for now.
