### ISSUE TITLE
[CaptainJ] Ghost infighting

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1162]
![grafik](https://user-images.githubusercontent.com/10298439/151664527-3869127a-d183-41bd-bca7-c2424599adb7.png)
 Ghosts can fight each other, unless it was intentional.

**Comment by x3003** [comment]
What's wrong w/ infighting ? I think every doom (based) game has something like it, even ashes 2063.

**Comment by Tormentor667** [comment]
Well, it depends on the type of enemy. Ghosts are supernatural enemies which have all the same goal: Killing you. Demons or humans for example are different in my eyes, especially if they are different species.
