### ISSUE TITLE
[GL? Vulkan? GZDoom?] 3D models show up really wrong

### ISSUE THREAD

**Issue by Redlor37** [Realm667/WolfenDoom#1163]
3D models show up like 2D sprites with a lot of z fighting, but they still have their normal hitbox.
![Screenshot_BoA_20220130_192937](https://user-images.githubusercontent.com/84392024/151712487-a1c22ea0-cc33-4818-838d-2ffba5dc4936.png)
![Screenshot_BoA_20220130_192832](https://user-images.githubusercontent.com/84392024/151712491-edd1cd7f-b063-41fd-8c04-347d1e6eae83.png)
![Screenshot_BoA_20220130_192843](https://user-images.githubusercontent.com/84392024/151712494-a0f2407d-dbc7-4259-9215-221038339fef.png)
![Screenshot_BoA_20220130_192927](https://user-images.githubusercontent.com/84392024/151712502-cb7a93aa-0e36-414a-b8b9-4a7f4a8c3ba4.png)

**Comment by Tormentor667** [comment]
What the fuck. With what engine are you playing the game?

**Comment by Tormentor667** [comment]
@Redlor37 without telling us details about the engine you have used, we can't check that any closer.

**Comment by Talon1024** [comment]
I have no idea what could be causing these sorts of issues, but my guess is an issue with the GPU or drivers you're using.

**Comment by Tormentor667** [comment]
So it's more a user-error than a game bug.
