### ISSUE TITLE
clip through rocks

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1164]
With the latest git version, in c1m4, you can clip through these colored rocks.

![Screenshot_Doom_20220202_001628](https://user-images.githubusercontent.com/77861029/152068120-4317aa27-1962-4eea-be0e-a44f1965c079.png)

![Screenshot_Doom_20220202_001704](https://user-images.githubusercontent.com/77861029/152068135-c534af21-d2ad-4cf2-ba69-4e5d0fb43686.png)

![Screenshot_Doom_20220202_001739](https://user-images.githubusercontent.com/77861029/152068146-8bcdbd13-0e72-4f60-a7db-1161a900046d.png)

**Comment by Tormentor667** [comment]
Fixed
