### ISSUE TITLE
some more clipping

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1166]
In c3m0_a, you can clip through these pipes.

![Screenshot_Doom_20220203_132007](https://user-images.githubusercontent.com/77861029/152657421-ceff0d98-cd6d-486b-8ed5-a38662e97695.png)

![Screenshot_Doom_20220203_132014](https://user-images.githubusercontent.com/77861029/152657424-e2da9488-f5a6-4114-b013-5b83959e7690.png)

**Comment by Tormentor667** [comment]
Fixed
