### ISSUE TITLE
[3.2] Display "unknown" primary objectives if none yet

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1167]
In C3M5_C you don't have primary objectives in the beginning. Instead of displaying the "Secondary Objectives" title directly below, could a line be added called "Unknown" instead @AFADoomer ?

![grafik](https://user-images.githubusercontent.com/10298439/152658297-a0448d15-3a44-4b4e-96c8-a89d4aefd915.png)

**Comment by x3003** [comment]
That's a new one then.
The built I got from just a few hours ago gave:

![Screenshot_Doom_20220205_223711](https://user-images.githubusercontent.com/77861029/152659954-6d22c04f-1623-42b9-9589-2ccd99089c3a.png)

And the built from just now gives:

![Screenshot_Doom_20220205_224114](https://user-images.githubusercontent.com/77861029/152659987-6f795dde-7105-457e-88e4-fdd66da7ac0b.png)

**Comment by Tormentor667** [comment]
Supposed to - the objectives appear as soon as you talk to Asher :)

**Comment by x3003** [comment]
Why not as first one, 'Talk to Ascher' ???

**Comment by Tormentor667** [comment]
> And in c3m5_b, checking the map and getting the primary from there is optional.

What do you mean by that?

> In c3m5_c, why not as first one, 'Talk to Ascher' ???

Because at this particular moment you have no idea that he is even on board and made it.

**Comment by x3003** [comment]
Well, when you start c3m5_b, there isn't a primary mission anymore. But one is **added** if you check the map.
But you don't need to check the map, so that part is **optional**. So you won't get a primary then.

**Comment by AFADoomer** [comment]
Added "Unknown" message in cf7ea511c5d8709f27c0bc8aad194bedd2bef361.

**Comment by x3003** [comment]
A little square in front of 'unknown' would make it a bit better. Now it looks out of place

![Screenshot_Doom_20220209_102508](https://user-images.githubusercontent.com/77861029/153165536-cb86617a-2fe9-45bb-a09c-86ca35c65f07.png)

**Comment by MuadDib90** [comment]
Well, I think it looks good this way...
With a square it would look like "an objective".

**Comment by Tormentor667** [comment]
Agreed with @MuadDib90

**Comment by AFADoomer** [comment]
Agreed - adding the square would make it look like it's actually an objective, versus not having any set.

**Comment by x3003** [comment]
>Because at this particular moment you have no idea that he is even on board and made it.

Unless he start chatting w/ you, eventhough you still didn't met him yet.

![Screenshot_Doom_20220207_120932](https://user-images.githubusercontent.com/77861029/153415082-12badd2d-2454-4c74-8ccd-0c4615f5b61f.png)

**Comment by MuadDib90** [comment]
Is there a way to "lock" everything until you find Ascher, so objectives appear? @AFADoomer Like you won't be able to get a repair kit or parachute, there won't be any exclamation mark, and so... Everything will unlock after you wander enough to find Ascher and talk to him. (Maybe only to allow to enter the corridors and rooms in the square pattern, so you are kind of "forced" in inconspicuously way to encounter Ascher?)

<details>
<summary>Picture</summary>

![Výstřižek](https://user-images.githubusercontent.com/73436978/153537487-23b61fdd-0043-4264-9050-49082d555091.PNG)

</details>

**Comment by Tormentor667** [comment]
This is indeed a very good idea. Isn’t it just like if you make an item dormant you can’t collect it?
