### ISSUE TITLE
missing description

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1169]
In c3m0_a, when picking up this key, there should atleast be a description of it, like 'you picked up a mysterious love key' or something like it. Now it doesn't say anything at all.

![Screenshot_BoA_20220201_142945](https://user-images.githubusercontent.com/77861029/152666060-3b71f26a-d02c-4319-a3e5-51b3dc228784.png)

**Comment by Tormentor667** [comment]
The right term would at least be "Heart Key" :D

**Comment by AFADoomer** [comment]
Addressed this as part of d5f326d580df45be8533d3a9bb1cbf6d1add80d8.

**Comment by x3003** [comment]
Looks fine.
