### ISSUE TITLE
unhandled type NativeStruct<CVar>

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1171]
With the latest built, you can't do a changemap anymore or save, you'll get 'unhandled type NativeStruct CVar'

![changemap_error](https://user-images.githubusercontent.com/77861029/152779335-fa51695c-2bfc-4b8f-a082-4280e4840890.png)
![save_error](https://user-images.githubusercontent.com/77861029/152779336-e58236f5-8e98-4df7-b802-be145af519fe.png)

**Comment by AFADoomer** [comment]
Scripts/eventhandlers/Screenlabelhandler.zs line 103 needs "transient" at the beginning of the line.

Sorry, didn't have the time expected this weekend to do proper testing 😦

**Comment by x3003** [comment]
That seems to work.
