### ISSUE TITLE
shovel icon only works 1 time

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1180]
When you get to this gate in c3m0_a, the icon only works 1 time. When you step back and try again, a second time (or more) it doesn't work anymore.

![Screenshot_Doom_20220213_013033](https://user-images.githubusercontent.com/77861029/153774736-90f2fc27-5585-4301-be4f-31d00a3c8cfb.png)

As a side effect, when you try it w/o shovel as in the 1st picture, then get the shovel and try to bash the lock, you'll have a hard time getting it off. Maybe try to bash it 30 or so times before getting it off and opening the gate. No problem when you get the shovel first (w/o activating the shovel icon) and trying to bash the lock then.

![Screenshot_Doom_20220213_013406](https://user-images.githubusercontent.com/77861029/153774970-8a641589-ab40-4d28-80ca-00abdbe253e4.png)

**Comment by AFADoomer** [comment]
Should be fixed after 4002684d70f1a3869ab5e1549bc6f79e222b46f3.  The line wasn't set as a repeatable action, so if you hit it with any other weapon it wouldn't work for the shovel.  Later, you probably hit one of the gates by accident, which calls the same script, so cleared the lock off.

**Comment by x3003** [comment]
That works, only when you stand in the middle, the gate won't open. It only opens when you stand a bit to the side.

**Comment by AFADoomer** [comment]
OK, try aeba458a2c9907d887ffc8a6e10e1d5e03dc63dc.

**Comment by x3003** [comment]
That works fine.
