### ISSUE TITLE
[GL, Standalone version] 3D models show up really wrong

### ISSUE THREAD

**Issue by Redlor37** [Realm667/WolfenDoom#1181]
Excuse me, i didn't check my issue for a while and i forgot to say what engine it was and what renderer i was using, also if it can help i'm using an AMD Radeon RX 570 as GPU and an AMD ryzen 5 for CPU.
Still, 3D models show up like 2D sprites with a lot of z fighting, but they still have their normal hitbox.
(my previus issue was #1163)
![Screenshot_BoA_20220130_192927](https://user-images.githubusercontent.com/84392024/153865612-b4555d10-da90-4ca8-931b-db59f9a1c083.png)
![Screenshot_BoA_20220130_192929_01](https://user-images.githubusercontent.com/84392024/153865627-eb933526-6cfe-43c9-95c2-fb1c19b895b4.png)
![Screenshot_BoA_20220130_192937](https://user-images.githubusercontent.com/84392024/153865645-4534ec2b-9fb6-4c3d-aec6-c0b6caaa22fc.png)
![Screenshot_BoA_20220130_192832](https://user-images.githubusercontent.com/84392024/153865653-4423a79e-d0c2-414e-b095-c5c2a5e5650c.png)
![Screenshot_BoA_20220130_192843](https://user-images.githubusercontent.com/84392024/153865662-38a71ffa-b578-4e05-a04c-0be97590a2a5.png)

**Comment by Redlor37** [comment]
It's the version 3.1, with open GL, if i switch to vulkan they show up properly.

**Comment by Redlor37** [comment]
But if i switch to vulkan it drops a couple of frames.

**Comment by Redlor37** [comment]
What do you mean with OpenGL ES, and also wit vulkan it doesn't just drop some frames, it lags a lot.

**Comment by Talon1024** [comment]
I thought OpenGL ES would be available to select in "Preferred Render Backend" in the Video Options menu, but apparently it isn't there in the latest GZDoom development builds.

Anyway, here's how you can activate the OpenGL ES renderer:

![Screenshot_Doom_20220216_135509](https://user-images.githubusercontent.com/6550500/154335957-9bac2bbd-37d2-49b3-89a8-2929c6493e4e.png)

**Comment by x3003** [comment]
Strangely enough the opengl es is not in the video menu, but only at startup.
When checking the video menu it says: preferred rendering api unknown.

**Comment by Redlor37** [comment]
It still doesn't work

**Comment by Redlor37** [comment]
I used the command method

**Comment by Redlor37** [comment]
Also openGL ES doesn't work entirely

**Comment by Redlor37** [comment]
My computer broke so i won't be able to test things for a bit
