### ISSUE TITLE
[CaptainJ] Gestapo door can opened although the texture is colored grey

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1184]
A tiny gripe of mine, but this Gestapo door can opened although the texture is colored grey, also has lock on its handle. It reveals after finishing the sequence but the tutorial told me that every grey door, or with a lock is always inaccessible. Could be misreading, but just saying.

![grafik](https://user-images.githubusercontent.com/10298439/153874428-25d402c1-e753-4c9a-aa52-2d85d91cfe37.png)

**Comment by MuadDib90** [comment]
The thing is, there is "no such door", if you come across it the first time, so player have no idea this leads somewhere. Thus it is not misleading.

![Screenshot_BoA_20220214_155157](https://user-images.githubusercontent.com/73436978/153887115-09e84d05-e241-4ab1-b05f-e8726314c3bd.png)

Only after hitting the switch in the next room, the passage opens, revealing a hidden room.
@Tormentor667 could you please tell to CaptainJ, he has no account here, right?

**Comment by x3003** [comment]
It's not a regular grey door, it's a **secret** grey door, which ofcourse you can get through. Someone is really nitpicking here.

**Comment by Tormentor667** [comment]
I should read and answer the issues on my own instead of just copy'n'pasting it ;) And yes, CaptainJ has no account here.
