### ISSUE TITLE
[CaptainJ] Wrong pickup sound for C4 explosives

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1185]
Lastly, i have a question. The Explosive Charges that are crucial to destroy Gun batteries play paper rustling sound effect. Other items like Mine Detector plays Backpack sound just fine. Is this actually intended?

**Comment by AFADoomer** [comment]
Should be fixed in 0caba811797ca3a8d0929751dc74b840fe558416.
