### ISSUE TITLE
[CaptainJ] C2M1 stealth mechanic problems

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1186]
[At the first part of C2M1 it shows that stealth mechanic of the game is quite half-baked.](https://streamable.com/h6yoen) If you get closer to the enemy then sure, it's your error. But this is the only part where i can't go undetected in first try. What's causing him to see under me? While turned back, even.

**Comment by x3003** [comment]
??? Seems fine with me. I've playing this level many times, even at 'mein leben'. If I can survive this level, anyone else can too, believe me. Just try a different technique to get across.

**Comment by AFADoomer** [comment]
Yeah, I'm pretty sure there is another guard (off screen top right) that kills you.  You aren't supposed to be able to go that way.  

We may need to make the ladder down more obvious...  extend the texture partway up the wall or something,  because I didn't notice it for a very long time.

**Comment by Tormentor667** [comment]
I will take care of the ladder.
