### ISSUE TITLE
Odd message shown

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1194]
In c1m3, when you don't have the explosives, you get the message 'with you!'. Maybe it should say something like 'get an explosive' or so ?!

![Screenshot_BoA_20220215_160046](https://user-images.githubusercontent.com/77861029/154089922-a9f395c3-33a6-471e-a38d-fa1030cf82bb.png)

**Comment by MuadDib90** [comment]
No, it is just the "last part" of a longer message, that should pop-up, if you try to put an explosive. When you have none, it should say something like "You don't have enough explosives with you!". Somehow only some last part of it appears the second try and from this point on.

I have seen this behavior in C3M0_A couple days ago when testing the ink ribbon line if you try to "use" a typewriter (to "save" the game as in Resident Evil -> easter egg).
The first time the whole line is displayed, any other times from that on, only some last part of it is displayed.

@AFADoomer do you have an idea what can cause this, considering latest commits? 🤔

**Comment by AFADoomer** [comment]
Yes, this is related to my update of the midprint handling.  Working a fix.

**Comment by AFADoomer** [comment]
Should be fixed in 34f9c64635b6b8276ee17ba53deaa1705bccd1cb.

**Comment by x3003** [comment]
There are a few issues.

- the current bullets in gun text has an offset
- the armor text has an offset
- the 'you dont have any [..]' text is first dim before it's getting brighter and better readable.

![Screenshot_Doom_20220217_093515](https://user-images.githubusercontent.com/77861029/154437619-296bcf7d-149f-4984-b055-1bb3774386dc.png)

**Comment by MuadDib90** [comment]
I see more offsets. I'll circle them to see them at first sight:
![154437619-296bcf7d-149f-4984-b055-1bb3774386dc](https://user-images.githubusercontent.com/73436978/154438991-819fd3e6-941e-4385-9afe-10730874e381.png)

**Comment by AFADoomer** [comment]
Drat. 

I fixed a bug and exposed accidental, now unnecessary compensation for the bug.  Not sure how I didn't notice this.

**Comment by AFADoomer** [comment]
OK, this should be properly fixed after cdd1e7bb65f9fb7882643ae62e58758d581b8ce4.

**Comment by x3003** [comment]
That seems to work,
