### ISSUE TITLE
Bubbles do not get removed, causing severe framerate issues.

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#12]
While I was playing through C2M0_A on the newly-fixed Linux version of GZDoom, I get a massive frame rate drop about halfway through the level, even if I turn off all special effects in the "BoA Options" menu and restart the level. I just found out why.

It seems that "Bubble" actors are not dying or otherwise getting removed.

![sonofaframerate](https://cloud.githubusercontent.com/assets/6550500/14575531/5d252be6-0330-11e6-8504-39df47e13899.png)

As soon as I removed the bubbles using the "remove" CCMD, my frame rate became smooth as cream.

**Comment by Ozymandias81** [comment]
Sorry for the late reply.
Did you try latest build of GZDoom though?

**Comment by Ozymandias81** [comment]
Nevermind, [fixed](https://github.com/Realm667/WolfenDoom/commit/5c2b43f86e6b3b861142ece5be9c3bab5ea6f44b).

**Comment by Tormentor667** [comment]
Thanks Ozymandias
