### ISSUE TITLE
[3.2] Single-use switches can be triggered multiple times.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1201]
With the latest GitHub builds, switches that are normally activated only once can be repeatedly triggered between on/off states to no effect. Examples I've seen so far are the door and gate switches on C1M1 and C1M2. Under normal circumstances, such switches should be "one-and-done".

GZDoom version: v4.7.1
Delta Touch version: v4.6

**Comment by AFADoomer** [comment]
Yeah, that's a side effect of 2edcdf67a73aa8537985cf706a65065780d878af.  I may need to revert that commit and just live with switch textures that don't do anything if they never have a line special assigned.

**Comment by x3003** [comment]
Dunno if it's the sideeffect of the commit, but this switch (and others ?) isn't working correctly anymore. Stays in 1 position.

![Screenshot_Doom_20220223_184739](https://user-images.githubusercontent.com/77861029/155420699-2f814ad8-8fbf-47d1-8016-71f3fbd8aef7.png)

**Comment by AFADoomer** [comment]
Switch on the side of a 3D floor + ACS texture change = edge case.  Should be fixed now.
