### ISSUE TITLE
[3.2, Keen Levels] DOS-themed Damage indicators?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1202]
Given how the Commander Keen HUD overrides that of BOA's whenever a Keen Cartridge is booted up, is it possible to make a simple red arrow for the damage indicator, to resemble something that came straight out of the DOS era, pixelated and whatnot?

**Comment by AFADoomer** [comment]
Probably, but that would make it even less like a DOS-era shooter.

**Comment by AFADoomer** [comment]
I say 'no' to this, then.
