### ISSUE TITLE
[3.2, HUD Suggestion] Have Health/Ammo counts change colors at certain thresholds.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1203]
Is it possible to have the HUD's health percentage flash red, or simply turn red outright, when at the 30% threshold, or lower? Too often in a firefight, I lose track of my health, even with the screen borders turning red when at such low health.

Is it also possible to have clip/reserve ammo either flash red when low, or go red when completely emptied, with the exception of your current grenade type, be it Standard or Astrostein Grenades?

Perhaps there could be a MENUDEF entry with a CVAR attached, to toggle this behavior?

**Comment by MuadDib90** [comment]
I must say I haven't problems with this by myself, but I can image it being added as another eye candy and also understand it can help a lot to some people.

**Comment by Tormentor667** [comment]
It's nice to have but I need to see it in action to tell if it should be on or off by default.

**Comment by AFADoomer** [comment]
Is the screen damage flash not enough to indicate low health?

**Comment by Tormentor667** [comment]
For me it is actually

**Comment by MuadDib90** [comment]
Well, I am satisfied too - as far as a tester.
