### ISSUE TITLE
barrels through barrack

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1205]
With the latest git version, in c3m1, these barrels go through a barrack.

![Screenshot_Doom_20220222_113408](https://user-images.githubusercontent.com/77861029/155166834-d2a39a18-9dc4-4abc-aa03-60aa970564a8.png)

![Screenshot_Doom_20220222_113422](https://user-images.githubusercontent.com/77861029/155166856-c09a71b3-ab68-4aad-b7b5-158411b6c31b.png)

**Comment by Tormentor667** [comment]
Fixed
