### ISSUE TITLE
enemy shoots through wood

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1207]
With the latest git version, in c3m5_b, the enemy can shoot through this piece of wood i'm pointing at.

![Screenshot_Doom_20220223_160604](https://user-images.githubusercontent.com/77861029/155372478-af6ee9a1-893d-42ac-af08-c9ce06813409.png)

**Comment by Tormentor667** [comment]
It's metal - but actually it's almost impossible to make the hitboxes of this object look exactly the same as the object itself due to the nature Doom's hitboxes are limited.

**Comment by x3003** [comment]
Not talking about the hitbox. I can't shoot through the 'metal' (normal), but the enemy on the other side of it (were i'm pointing the crosshair) can hit me in this position.

**Comment by x3003** [comment]
Reproduced.

![Screenshot_Doom_20220224_114016](https://user-images.githubusercontent.com/77861029/155508935-00f33912-4afc-487d-81f6-e0691262fbb5.png)

**Comment by Tormentor667** [comment]
Hitboxes in Doom are always rectangular, and to be honest, I have no idea why this happens but I am already sure it can't be fixed to a 100% extinct.
