### ISSUE TITLE
toilet is wrong

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1209]
In c3m6_b, there shouldn't be a normal toilet in the left position.
The enemy is sitting on the hole anyway.

![Screenshot_Doom_20220225_134526](https://user-images.githubusercontent.com/77861029/155719431-a006be95-2e67-4b01-b7b2-161b80c725c3.png)
 
![Screenshot_Doom_20220225_134421](https://user-images.githubusercontent.com/77861029/155719458-cbae1b79-a5c7-4d3d-b567-225952530fe6.png)

**Comment by AFADoomer** [comment]
Fixed in 3e48940fe0367de796e4379557aad2d1db6da00c.

**Comment by x3003** [comment]
Still sitting offset, but that might be the best position I guess ?

![Screenshot_Doom_20220226_225310](https://user-images.githubusercontent.com/77861029/155881139-96a172cc-8fba-43f7-b60b-c1815880ba7a.png)

**Comment by AFADoomer** [comment]
It's a single-direction sprite, and that's where the actor is placed in the map.
