### ISSUE TITLE
enemy disappears

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1210]
In c3m5_b, this enemy when sitting on the hole toilet, shoots 1x and then disappears (through the hole ?).
I didn't even shoot him...  ¯\_(ツ)_/¯

![Screenshot_Doom_20220225_134519](https://user-images.githubusercontent.com/77861029/155719916-84e5d581-f4c4-4737-b0ec-2320eb49bf2c.png)

**Comment by AFADoomer** [comment]
Fixed in 3e48940fe0367de796e4379557aad2d1db6da00c.  

This was a side effect of the actor getting moved in front of the toilet when he gets up; the actor is facing into the wall, so he would "get up" in the void.
