### ISSUE TITLE
move through glass

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1211]
In c3m6_a, bj can move through this piece of glass as if it doesn't exists. Maybe stopping him or destroy the glass first before moving through the opening ???

![Screenshot_Doom_20220225_124545](https://user-images.githubusercontent.com/77861029/155720132-17ff716e-8e5a-4bdd-b8dd-a6e616cef631.png)

**Comment by Tormentor667** [comment]
Fixed
