### ISSUE TITLE
switches

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1212]
With the latest git version, in c3m5_c this switch still only works 1 time. After that it got stuck in the down position.

![Screenshot_Doom_20220225_000707](https://user-images.githubusercontent.com/77861029/155720990-535da339-1aad-48cd-952c-7408316ce876.png)

And this one (and other like it) works multiple times [read: you can activate it to green/red], even when it shouldn't because the elevator (or door) still isn't all the way up/down.

![Screenshot_Doom_20220225_000745](https://user-images.githubusercontent.com/77861029/155721264-990c364c-b553-4770-9eae-d7aa5a13fe93.png)

**Comment by AFADoomer** [comment]
Saying "With the latest git version" makes this sound like it's a new problem...  The elevator switch has behaved this way since at least the 3.1 release.

Rewrote the elevator script in 95ed3eef648b03aafc4431ee934f32176e400bb7.

The red/green switch is a "live with it" problem.  It has always been able to be activated multiple times with no effect.

**Comment by hawkwind3** [comment]
Regarding the red/green switch, that works fine and as expected for me. Take the lift up and then noclip back to where the red/green switch is. The lift should come back down.

As a side point, note what happens with the ceiling of sector 420 when the lift rises. A 90 degree change.

**Comment by hawkwind3** [comment]
I see what you mean now. Continually using the switch while the lift is already in the lowered position is a bit daft anyway. Another side point ... there really should be a switch outside the lift when the lift is in its raised position. Should have been near sector 2377. Maybe one could be placed at sector 2541 ?

**Comment by x3003** [comment]
It's not only this elevatorswitch, it's this type of red/green switch. I couldn't reproduce it in the 3.1 version, so something has changed since.
