### ISSUE TITLE
difficult to get in

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1213]
In c3m6_a, to get into this hole is quite difficult. When you press down you go down a bit and suddenly you're on top of the hole again.
It really takes some time and effort to get in.

![Screenshot_Doom_20220226_221426](https://user-images.githubusercontent.com/77861029/155881214-e416aecf-4a74-42b5-8ad2-6cbcf92b1b7e.png)

**Comment by MuadDib90** [comment]
I tested it just now, but I don't have such problems. I can enter with any "resistance", so to speak.
Without usage of crouch key, or with it.

And must say from commit, when @AFADoomer improved ladders to use "fly cheat", I never experienced any inconvinience with ladders to this day. :confused:

Can you describe what "you do", when entering? So I can simulate it?

**Comment by Tormentor667** [comment]
Same here, just tried it and it works fine on my side.

**Comment by x3003** [comment]
It seems, if you go straight in it works. If you don't, just viewing a little left or right, the first steps you go down, but after that you're out fast again.

**Comment by AFADoomer** [comment]
This an engine limitation...  if you fly through a floor portal and touch a wall while transiting the portal, you get teleported to the top of the surrounding sector.  We saw this before in another map (descending ladder to crypt under church).

**Comment by MuadDib90** [comment]
I think I have imitated what you are experiencing.
I hardly can recall if I ever experienced "this".
The thing is if you wanna "go in" it seems normal to "aim in". But I can understand what you are getting at.
My huge guess is this it just an engine limit. So I don't think even @AFADoomer can do something about it...

**Comment by x3003** [comment]
>if you fly through a floor portal and touch a wall while transiting the portal, you get teleported to the top of the surrounding sector. 

But only if the hole is a bit smaller than usual (you can tough the sides), as it doesn't occur on other holes.

**Comment by Tormentor667** [comment]
Marked as "can't be fixed"
