### ISSUE TITLE
key icon color

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1214]
In c3m6_a, when you have the weird key, shouldn't the icon be green instead of orange ?

![Screenshot_Doom_20220226_222745](https://user-images.githubusercontent.com/77861029/155881307-06065ff6-1616-4e52-800c-082aba2a76ea.png)

**Comment by MuadDib90** [comment]
Are you playing continuously the episode from beginning, or with command "map c3m6_a" and some cheats?

**Comment by x3003** [comment]
no cheats used.... only map xxx

**Comment by MuadDib90** [comment]
> Is that even the right key for that door? If the required key was changed to that key, the line user_crosshair value needs to be updated.

What do you mean "right"? Like it could be different one with same graphics, but with diffent "metadata"; or somethin'?

I can confirm, when you buy a key from Fritz, this will open the door, but icon stays orange instead green.

**Comment by AFADoomer** [comment]
This was originally a normal Skull Key (that matches the texture on the door).  When it was changed to the 'for sale' version, the line special was updated to check the right key, but no one ever updated the line property for the orange/green indicator to check for the newly added version.

Notice that the image in orange isn't the same as the icon of the key in the top right corner...

**Comment by AFADoomer** [comment]
Fixed in fcd64208d0880111276731fa2ae7a1d8775459f8.

Also added a new pair of textures for the door itself that match the actual key used here.

**Comment by MuadDib90** [comment]
Good, repaired now. :wink: Works briliantly.
