### ISSUE TITLE
radio position

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1215]
In c3m6_b, this radio is under the table. Maybe it was hiding from the grenadeblast ?!

![Screenshot_Doom_20220226_224138](https://user-images.githubusercontent.com/77861029/155881364-07553c66-898d-4a92-8a8a-6e661e976fd7.png)

**Comment by MuadDib90** [comment]
Yes, one of the unrepaired issues in here #997

**Comment by Tormentor667** [comment]
Duplicate
