### ISSUE TITLE
Cannot pick up Totale Gier on C2M3

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#1217]
When I try to pick up this Totale Gier on C2M3, it just disappears:
![Screenshot_Doom_20220302_202039](https://user-images.githubusercontent.com/6550500/156478009-e3712668-75e2-4874-bfe4-284a679a0ed6.png)

**Comment by AFADoomer** [comment]
It has special 132 (Thing_Remove) as its action special, and both it and the associated pulse light (that was supposed to be removed) were tagged with the specified thing tag (150), so it's removing itself as soon as you pick it up.

Fixed in d8b58c44e4309b8f5263b66cb1a3c808574e5406
