### ISSUE TITLE
[C3M6_B] Specific Key Icon

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1218]
Yes, another one.... This door in c3m6_b is also missing it's key icons.

![Screenshot_Doom_20220227_132250](https://user-images.githubusercontent.com/77861029/156777752-1f2bda9f-f9d8-48ce-bde9-d1796c8a9b4d.png)

**Comment by Ozymandias81** [comment]
Isn't it the one on the right?

**Comment by x3003** [comment]
Well, I have the key, but there's no key icon as like with all the other doors.

**Comment by Tormentor667** [comment]
@Ozymandias81 can you take care?
