### ISSUE TITLE
[3.2] Coop lobby

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1219]
It's great coop mode is underway, but there is still no lobby for players to see how many others are online wanna play.
Is this planned ??? How else would you find another player for coop ?!?

**Comment by Tormentor667** [comment]
I have no idea what is needed for something like this to work actually.

**Comment by x3003** [comment]
You can see it for example in cube2 sauerbraten, but I've no idea how they centralize the servers.

**Comment by Tormentor667** [comment]
That’s the point :)

**Comment by x3003** [comment]
Well, but how should players find each other then ? Adding multiplayer is great, but if you can't play it, it's useless.

**Comment by Tormentor667** [comment]
Currently this is only possible if you exchange IPs for host and clients, no idea if @mgrinzPlayer would be able to implement something like that. I could at least share a server for that on my webhost.

**Comment by ColerXXX** [comment]
The best thing would be to play with friends, even better if in LAN since gzdoom multiplayer is quite latency sensitive.
Before there were VPN programs like Tunngle with public chatrooms where people could organize their game. Not sure what's up at the moment for the same purpose but I suppose that could be the way

**Comment by ColerXXX** [comment]
The best thing would be to play with friends, even better if in LAN since gzdoom multiplayer is quite latency sensitive.
Before there were VPN programs like Tunngle with public chatrooms where people could organize their game. Not sure what's the best option at the moment for the purpose, but I suppose that could be the way.

Very very happy that coop is coming over for this gem of game!

**Comment by mgrinzPlayer** [comment]
> share a server for that on my webhost
If gzdoom servers can send the "hearbeat" to your server, and if you host some basic information about those servers: IP, current map/skill/players. My launcher could download and parse it. It could be simple text format (or json or xml format).


Does gzdoom have "dedicated server" feature? From what I observed, gzdoom is always "a player" when running as server.


The other way around would be to not close the my launcher, write a code which would periodically gather data from boa.exe (gzdoom.exe) process then send those data to your server.  And that means it will use some "suspicious" API from Windows (Kernel32!GetProcAddress, OpenProcess, ReadProcessMemory, VirtualQueryEx, etc. ) resulting in, 100% guarantee, getting false positive from AVs.

**Comment by ColerXXX** [comment]
> Does gzdoom have "dedicated server" feature? From what I observed, gzdoom is always "a player" when running as server.

Exactly, also once started the game is not possible to join while in progress, also it needs number of players to be set on launch parameters. Imho at the current state it would need a public chatroom where people can organize their game, something like https://www.radmin-vpn.com/  I'm quite sure there are better options out there, or an opensource one using OpenVPN. like https://github.com/crnlc/PlayHide which has been discontinued unfortunately, it was quite good.

**Comment by x3003** [comment]
>I'm quite sure there are better options out there, or an opensource one using OpenVPN + Discord.

Well, they have a dedicated lobby and chat in 0AD. Dunno how they do it, but it works and w/o discord.

**Comment by ColerXXX** [comment]
^^ nice, good to know!

**Comment by Tormentor667** [comment]
Well, I am sure I can somehow set up a live chat on the webpage where people can meet up, I just wonder, if that works and if people are interested in something like that.

**Comment by ColerXXX** [comment]
I dunno if there's already a discord server but a dedicated section could be a good start. Then if it goes good also a live chat would worth it!

**Comment by x3003** [comment]
Just checked out the odamex launcher. Look pretty good, but I dunno if this can be done for boa w/ gzdoom.

**Comment by mgrinzPlayer** [comment]
From doomwiki
> The included launcher, OdaLaunch, is specifically designed for Odamex

Did anyone try Odamex with boa.ipk3 ?

**Comment by Tormentor667** [comment]
I am pretty sure that Odamex isn’t up to par with Gzdooms latest features

**Comment by x3003** [comment]
Well, odamex doesn't seems to work (start) boa, but for coop mode in boa this is what you would want:

![odamex_coop](https://user-images.githubusercontent.com/77861029/158030342-9a8208e5-5c31-4739-b6f9-7099f14d1a67.jpg)

**Comment by ColerXXX** [comment]
Yeah probably it could advertise servers when in "waiting for players" state so people can connect. Right

**Comment by Tormentor667** [comment]
Still, I can only serve a webserver on a shared hosting for any kind of infrastructure but I can not program anyth unfortunately.

**Comment by mgrinzPlayer** [comment]
I see @madame-rachelle is making some "discord" stuff to the main gzdoom branch https://github.com/coelckers/gzdoom/commits?author=madame-rachelle

But, still we can't join in-game. Unfortunately, I'm not familiar with doom engines (original and modern versions), ZScript and so on.

**Comment by Tormentor667** [comment]
Then I'd simply suggest leaving it as is.

@mgrinzPlayer one more suggestion though: Currently the 3 possible choices for choosing a map to play are the map names itself. Can this be changed to "Chapter 1", "Chapter 2" and "Chapter 3" instead (of C3INTRO e.g.)?

**Comment by madame-rachelle** [comment]
The Discord stuff is not meant for in-game joining or anything like that, it's only to show people what you're playing.

**Comment by mgrinzPlayer** [comment]
@madame-rachelle, 
My knowledge about Discord is at "total noob" level - I used only web interface to exchange some information ("Half-Life: Black Mesa" official discord channel, bug report "xen levels" room, and "cheatengine" official channel). Do you still need other software to play "local multiplayer"? I thought Discordapp has build-in "virtual LAN". Or you have to install additional software, quickgoogling, maybe this: https://github.com/gyf304/lpvpn


@Tormentor667, on it

**Comment by ColerXXX** [comment]
@mgrinzPlayer  nice one

**Comment by madame-rachelle** [comment]
You still need additional software. The software has to interface with the RPC. It's a pain in the butt, but it's actually quite simple to use.

**Comment by mgrinzPlayer** [comment]
Does [lpvpn](https://github.com/gyf304/lpvpn) currently work with Discord? Anyone tried?

**Comment by Tormentor667** [comment]
Perfect, works like a charm :)
