### ISSUE TITLE
Can't hit enemies

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1220]
In c2m5_a, you can't hit these enemies from this distance. You can hit the iceboss though.

![Screenshot_Doom_20220310_224039](https://user-images.githubusercontent.com/77861029/157888065-5898a7cb-2ad6-412c-b49f-080859b9ad95.png)

**Comment by Ozymandias81** [comment]
You are playing without fog activated, enemies are "disabled" specially snipers at a certain distance.
