### ISSUE TITLE
arrows

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1222]
In c2m2, there are 2 red doors. So maybe these 2 red arrows should point to the left **and** the right, instead of both to the left.

![Screenshot_Doom_20220306_175332](https://user-images.githubusercontent.com/77861029/157889003-8c369d45-0eea-445a-a858-51a17a50acb9.png)

**Comment by MuadDib90** [comment]
If I recall correctly, one of the red doors holds "a secret" afaik, so arrows pinpoint the "regular way" of going through the level. (And my personal opinion is to not show a player secrets, let him find them by his own.)

**Comment by Tormentor667** [comment]
Exactly :)

**Comment by x3003** [comment]
Hmm, never knew it was a secret...
