### ISSUE TITLE
gate gets stuck

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1223]
In c2m1, this gate gets stuck one way, but not the other.

![Screenshot_Doom_20220306_165933](https://user-images.githubusercontent.com/77861029/157889465-0c68efec-8b01-42bb-bbbf-75afa790be1f.png)

![Screenshot_Doom_20220306_165947](https://user-images.githubusercontent.com/77861029/157889500-ec3f14c9-c8fa-4ceb-af13-48522cc2bc09.png)

**Comment by Tormentor667** [comment]
Fixed
