### ISSUE TITLE
[3.2] Help comments obstructed

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1225]
Sometimes the dev comments blocks the help text. Maybe the help text can moved up a bit when dev comments are shown ?!

![Screenshot_Doom_20220306_161329](https://user-images.githubusercontent.com/77861029/157890415-2bb49bfb-9a97-440c-bdb2-5b667b8b4b50.png)

![Screenshot_Doom_20220306_161306](https://user-images.githubusercontent.com/77861029/157890546-04f7bb08-4c75-4ca4-9877-491a852949c2.png)

**Comment by Tormentor667** [comment]
Summoning @AFADoomer :)

**Comment by Username-N00b-is-not-available** [comment]
Help comments are for first playthroughs, and developer comments are for the further ones (they contain some spoilers IIRC). Not saying this issue cannot be fixed, though, but the messages on the first image would have blocked most of the player view.

**Comment by Tormentor667** [comment]
@AFADoomer can something be done about this with the message queue you actually realised some months/years ago?

**Comment by AFADoomer** [comment]
This should be fixed in a4d0f5fe2229fa79bfdf4d7b939a724763cd5a60.

**Comment by Tormentor667** [comment]
Awesome, thanks as well!
