### ISSUE TITLE
mirror destroyed

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1226]
In c2m1, when you destroy either one or both of these mirrors,

![Screenshot_Doom_20220306_170914](https://user-images.githubusercontent.com/77861029/157891154-f06de632-6cef-4e4a-806d-10db6295a232.png)

when you get to this position, this mirror is already destroyed, but not the other one on the other side.

![Screenshot_Doom_20220306_165735](https://user-images.githubusercontent.com/77861029/157891107-dd4287ca-6368-4720-be73-113dabcc53fa.png)

**Comment by Tormentor667** [comment]
Fixed
