### ISSUE TITLE
healthpack color idea

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1227]
In c2m0_b, maybe an idea is to change the red color of this healthpack to green as everything else in this map is green anyway.

![Screenshot_Doom_20220310_003659](https://user-images.githubusercontent.com/77861029/157891895-a8a8120d-95a2-4abb-a964-5c1fc0bba117.png)

**Comment by Tormentor667** [comment]
Well, red indicates health so I see no reason for changing that.
