### ISSUE TITLE
actors should get activated

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1232]
In c1m2, the actors in the left room should get activated when you enter the right room, as they should 'see' you through the glass.

![Screenshot_Doom_20220318_155555](https://user-images.githubusercontent.com/77861029/159027636-8fed7295-5f3d-441e-bf2a-715a5c0be8a9.png)

**Comment by Tormentor667** [comment]
Fixed

**Comment by x3003** [comment]
It makes more sense now, only they should know they cant shoot through the bulletproof glass ;)

**Comment by Tormentor667** [comment]
I like having them trying ;)

**Comment by x3003** [comment]
yeah I know, it's funny ;)

**Comment by x3003** [comment]
It doesn't work when doing coop mode however.

**Comment by Tormentor667** [comment]
What isn't working actually?

**Comment by x3003** [comment]
>What isn't working actually?

If you go into the right room, single player, the actors in the left room gets activated. But when you do this in 1 player coop mode, these aren't activated.

**Comment by Tormentor667** [comment]
Can you retry?
