### ISSUE TITLE
ryan through gate

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1233]
In c1m2, you can push ryan through this gate. And he walks back through it also.

![Screenshot_Doom_20220319_002123](https://user-images.githubusercontent.com/77861029/159120770-023735bd-9083-4e8d-bead-afaf0a215759.png)

**Comment by Tormentor667** [comment]
@AFADoomer I wonder: Which type of line blocking is relevant for the player followers?

**Comment by Ozymandias81** [comment]
I remember we had at some point removed relevant line blocking for followers since they might got stuck in different situations , but I might be wrong

**Comment by Tormentor667** [comment]
The question here is: Is it game-breaking and worth the effort fixing it? It's not worth the hassle.
