### ISSUE TITLE
guards getting stuck in wall

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1234]
With the latest git version, in c1m2, these 2 guards are stuck in the wall. To make sure it wasn't a one-off, i've tried the level twice....

![Screenshot_Doom_20220319_000825](https://user-images.githubusercontent.com/77861029/159120851-72d01846-cdfd-41e1-9996-c4fa472e3b0f.png)

**Comment by Tormentor667** [comment]
Fixed
