### ISSUE TITLE
alarm goes off to soon

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1235]
Maybe an idea is not to activate the alarm when you go this way, unless you opened the red doors first.
It's pointless because the gate is closed, ryan should know this also.....

![Screenshot_Doom_20220318_173628](https://user-images.githubusercontent.com/77861029/159121057-8b2b65b1-0abd-4385-89a9-3ad89dd0c5ec.png)

**Comment by Tormentor667** [comment]
Good point, fixed it
