### ISSUE TITLE
wrong secret shown on paper

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1236]
With the latest git version, in c1m4, the underwatersecret is shown on the paper, but not on the screen. As I didn't picked it up yet, it shouldn't be on the paper.

![sec](https://user-images.githubusercontent.com/77861029/159128388-c10b5e82-cddc-4ebd-9f0d-0abcf0217d86.JPG)

**Comment by Tormentor667** [comment]
I think the problem is the associated sector id... I am not sure though. @Talon1024 @Username-N00b-is-not-available could this be the reason? Because the secret was altered and the id's are not right anymore.
