### ISSUE TITLE
Music not found

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1237]
In c3m3_b, there seems to be some music missing (CMBT_HT) when going near/in the flaktower.

![Screenshot_Doom_20220320_215348](https://user-images.githubusercontent.com/77861029/159185753-5ecc1680-ae5c-4a92-96fd-943f5a478bd7.png)

**Comment by Tormentor667** [comment]
That's because it should have been a sound effect and not a music. Fixed it.
