### ISSUE TITLE
some more hitboxes

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1238]
Here are some more annoying hitboxes.

These rocks have some, these block you also when walking past it.

![Screenshot_Doom_20220320_234628](https://user-images.githubusercontent.com/77861029/160148488-8b02ede0-1072-4441-9f52-3ef4a495b6c4.png)
![Screenshot_Doom_20220320_234649](https://user-images.githubusercontent.com/77861029/160148502-f37ae150-b1d2-45ad-af57-5509d35b0bb4.png)

You can't shoot through it. 

![Screenshot_Doom_20220320_123342](https://user-images.githubusercontent.com/77861029/160148763-5b6f7e68-98d3-4c64-90bf-cd3c72cdfb03.png)

These can even blocks grenates.

![Screenshot_Doom_20220320_123144](https://user-images.githubusercontent.com/77861029/160148780-b7434446-d79d-4815-8d8f-dfbaabc85913.png)

Here, these statues block.

![Screenshot_Doom_20220319_214200](https://user-images.githubusercontent.com/77861029/160149121-8f873512-3908-4660-a9c0-3af104e68382.png)

![Screenshot_Doom_20220319_214146](https://user-images.githubusercontent.com/77861029/160149350-c2bb4cd7-d4bf-4324-b8d6-a95b2848ed72.png)

Even food can block bullets....

![Screenshot_Doom_20220319_213818](https://user-images.githubusercontent.com/77861029/160149467-b8871176-1efb-480c-a01a-d50b5a4a9564.png)

**Comment by Tormentor667** [comment]
Fixed, though some of the blocking stones can't be perfectly fixed as they are generated randomly
