### ISSUE TITLE
enemy won't die

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1239]
In c3m3_b, when an enemy unit falls in the 'bath', he won't die. He can even shoot back.

![Screenshot_Doom_20220320_231535](https://user-images.githubusercontent.com/77861029/160149919-a4cff41e-f6c0-4cd4-b383-5d56b25761ba.png)

![Screenshot_Doom_20220320_231456](https://user-images.githubusercontent.com/77861029/160149974-caac4830-8528-41aa-96d6-013cd9c50f31.png)

**Comment by MuadDib90** [comment]
Strange, I was reporting this exact thing like a year ago, and it WAS repaired,
Why it is popping up again...?
(I think @Tormentor667 repaired this one.)

**Comment by Tormentor667** [comment]
Well, fixed it again :)
