### ISSUE TITLE
shield partially under water

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1240]
In c1m5, this shield is partially under water. Intended ?

![Screenshot_Doom_20220319_214815](https://user-images.githubusercontent.com/77861029/160152170-74ba994c-7f00-4cdd-b091-bc7f7587612b.png)

**Comment by hawkwind3** [comment]
That's wierd. I just downloaded the latest c1m5 and the shield is in the correct position between the above torches.
The shield should be at position 7040, -400, 112 (88). I admit I'm not using all the latest files.

**Comment by Tormentor667** [comment]
The only thing I can imagine is, that it jumps sometimes as it is directly placed on the linedef. I moved it a bit, should not happen anymore from now on.
