### ISSUE TITLE
keen scoreboard issue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1242]
When dying a keen mission (started with map ...), the scoreboard stays in the intermap. 

![Screenshot_Doom_20220402_152017](https://user-images.githubusercontent.com/77861029/161387920-a7ee1fb3-fd03-4b93-85da-196ece2a2ca1.png)

**Comment by Tormentor667** [comment]
Summoning @AFADoomer here

**Comment by AFADoomer** [comment]
Should be fixed in accacc7dd48cc6ab193839a81d1c777b8ca28587

**Comment by x3003** [comment]
If you die now, you are presented w/ the intro of the game,

**Comment by AFADoomer** [comment]
That's what happens when you use 'map' to run the level...

**Comment by Ozymandias81** [comment]
@x3003 did you had chance to replay the game at this point and verify if the issue occurs again? Sadly it is the only proper way to test these things without cheats...

**Comment by x3003** [comment]
It seems ok now.
