### ISSUE TITLE
script error with gzdoom v4.7.1

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1243]
Maybe the git version already needs gzdoom v4.8+ ?
When starting with v4.7.1, it says: Script error, "boa_c3.pk3:scripts/boastatusbar.zs" line 1518: Unknown identifier 'PAUSED'

![gzdoom_script](https://user-images.githubusercontent.com/77861029/162450081-2d92147a-1645-4845-840b-771244352168.jpg)

**Comment by AFADoomer** [comment]
So it's not a bug and you've answered your own question?

**Comment by x3003** [comment]
I'm asking a question, coz I don't know the answer.

**Comment by Talon1024** [comment]
Yes, the latest git version requires a [GZDoom development build](https://devbuilds.drdteam.org/gzdoom).
