### ISSUE TITLE
[C1M2] Hovering Ryan (previously: Lockup when firing flamethrower)

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1244]
With the git version, in c1m2, when firing into this room (from 4 sides, where ryan stands now) with the flamethrower, the game locks up completely.

![boa_lockup](https://user-images.githubusercontent.com/77861029/162451688-e3376147-bd75-4c22-972c-a1d689f42ace.jpg)

![Screenshot_Doom_20220408_154533](https://user-images.githubusercontent.com/77861029/162451732-5811431a-4859-4b72-b7dc-b917d9f005c6.png)

I've got no lockup when firing in any other direction.
I've tried gzdoom all the way down to v4.8 pre 208, as v4.7.1 won't start the game.

Edit:

if you didn't released ryan yet (the alarm isn't activated ) and clipped through, the game doesn't lockup.

**Comment by Tormentor667** [comment]
This is interesting. I had these issues as well a few times at the exactl location but never was able to reproduce these until now. No idea what is going on here so I am summoning @Ozymandias81 @Talon1024 @AFADoomer

**Comment by Username-N00b-is-not-available** [comment]
It is because of Ryan himself rather than the room, I can reproduce this anywhere.

**Comment by x3003** [comment]
With the latest git version, boa/gzdoom still crashes when using the flamethrower.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 In what circumstances?

**Comment by x3003** [comment]
Yeah, the crash is gone. But now ryan think he's jesus, maybe he can walk on water too :))

**Comment by Username-N00b-is-not-available** [comment]
He can only stand or hover, not walk :-) Summoning @Talon1024 anyway, maybe he would have an idea about what prevents Ryan falling.

**Comment by Tormentor667** [comment]
Tried this today, everything works fine for me, Ryan is not floating and moving normally as supposed to do.
