### ISSUE TITLE
airship reversed texture

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1247]
In c3m6_a, this airship has a reversed texture on it.

![Screenshot_Doom_20220423_230140](https://user-images.githubusercontent.com/77861029/165943347-86cbaf96-a833-424f-ad0f-2552e4496cf5.png)

**Comment by Tormentor667** [comment]
Unfortunately I have no idea how to fix thas as the model has been prepared by someone else. If @Ozymandias81 is able to fix it, I am okay with it, otherwise keeping it as is would be fine as well.

**Comment by Ozymandias81** [comment]
Weird I remember it was fixed... I might give it a try.

**Comment by Ozymandias81** [comment]
I wasn't wrong, the model has been fixed before...
![image](https://user-images.githubusercontent.com/11136108/167293250-15d080df-1927-4e32-959f-2b05adb3a805.png)
![image](https://user-images.githubusercontent.com/11136108/167293254-125e217b-e792-4d54-b02e-57251f122ca4.png)
... so the problem could be mapwise, codewise or GZDoom related. Gonna check.

**Comment by Tormentor667** [comment]
Thank you!
