### ISSUE TITLE
vm execution aborted

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1248]
With the latest git version, in c3m2, when loading a saved game I get a 'vm execution aborted' error. 
I got the tank, got to the base and parked behind it. After this point you'll get this error, not while still on the side of the base (or any point before).

![vm execution](https://user-images.githubusercontent.com/77861029/166120750-45c947e4-d1d8-4a1d-a270-ba3687013420.png)

**Comment by Tormentor667** [comment]
Summoning @Talon1024 and @AFADoomer here

**Comment by AFADoomer** [comment]
Should no longer abort after ac36fe98abe14942b2fed1a4d05897538a59434d.

**Comment by AFADoomer** [comment]
On second thought, never mind.  This crashes internally somehow, as if the defined String array is somehow not in existence despite the Count call being made from the parent class.

**Comment by x3003** [comment]
It's so weird as it might not crash when loading, but when picking up a simple helmet (or talk to ascher) from the 1st base and save, it does crash when loading again.

**Comment by x3003** [comment]
Seems alright now.

>Should no longer abort after https://github.com/Realm667/WolfenDoom/commit/ac36fe98abe14942b2fed1a4d05897538a59434d.

If this doesn't work, is the patch going the be reverted ? Or does it actually do something ?!

**Comment by Talon1024** [comment]
> > Should no longer abort after [ac36fe9](https://github.com/Realm667/WolfenDoom/commit/ac36fe98abe14942b2fed1a4d05897538a59434d).
> 
> If this doesn't work, is the patch going the be reverted ? Or does it actually do something ?!

That commit was [already reverted](https://github.com/Realm667/WolfenDoom/commit/eb490bc5754226e450fb5413239847f52ee1fce5) before I committed my fix.
