### ISSUE TITLE
mirror destroyed

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1250]
Just as in report #1226 

When destroying 1 or 2 of these mirrors

![Screenshot_BoA_20220529_153203](https://user-images.githubusercontent.com/77861029/171043856-937885e2-0033-4759-b61c-b0f357d00585.png)

then this one get destroyed aswell.

![Screenshot_BoA_20220529_153117](https://user-images.githubusercontent.com/77861029/171043923-492dd08b-ed54-4d79-9822-6eb6d007e36b.png)

**Comment by Tormentor667** [comment]
Fixed, good spot!
