### ISSUE TITLE
disc in the wrong place

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1251]
In c1m6, you should get the disc into this place to open the doors

![Screenshot_BoA_20220529_120718](https://user-images.githubusercontent.com/77861029/171044159-6ad576ad-b3d7-4749-a5f4-149aa6dc72ea.png)

But you can also lean (and press ..use..) against this place to get the disc into place

![Screenshot_BoA_20220529_120708](https://user-images.githubusercontent.com/77861029/171044269-e31b2fa0-a2cd-4930-aa80-28c7a6cee311.png)

**Comment by Tormentor667** [comment]
Fixed
