### ISSUE TITLE
switch has the wrong size

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1252]
With the latest git version, in c1m2, these switches have different sizes.

![Screenshot_BoA_20220528_163029](https://user-images.githubusercontent.com/77861029/171044740-96775cd8-6e31-4aee-9dfe-03c75d371a41.png)

![Screenshot_BoA_20220528_163034](https://user-images.githubusercontent.com/77861029/171044753-7a6e2fd0-c905-4a0e-aded-07ff72ace2f6.png)

**Comment by MuadDib90** [comment]
I might be wrong, but wasn't it by any chance due to better visibility for player, so he won't spend too much time "finding the way"? @Ozymandias81

**Comment by Tormentor667** [comment]
Considering that both switches have a different function, there is no need to have them the same size. I made a change/fix anyway though.
