### ISSUE TITLE
exclamation marks not visible

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1257]
When you have the fog on, these exclamation marks aren't really visible. Maybe someone can make them bigger or brighter ?

![Screenshot_BoA_20220605_162502](https://user-images.githubusercontent.com/77861029/173188762-101f81c7-7ad4-45e6-bcf3-9b4ff607d08a.png)

**Comment by AFADoomer** [comment]
This can't be fixed with the current implementation because the marks are map things, and are affected by fog regardless of their brightness.

I can convert them to draw directly on the player's screen instead with only minor additions to the screen label code - but don't know if it's necessary for en edge case.

**Comment by x3003** [comment]
The downside is that you can also see them through doors & walls.
My propose was basically on c3m2 **only**, coz it has a lot of fog. Dunno if that can be done.

![Screenshot_BoA_20220619_141541](https://user-images.githubusercontent.com/77861029/174480604-a2c7d164-d726-405d-ad39-a6080c10bbc6.png)

![Screenshot_BoA_20220619_141618](https://user-images.githubusercontent.com/77861029/174480624-9ffb7a53-952e-4aa6-bcbd-27902dcc86a2.png)

**Comment by AFADoomer** [comment]
You can't see them through walls.  You *can* see them through windows.

Doors might be fixable.

**Comment by x3003** [comment]
Yeah, but in the second image you can see them through the windowframe, not the window.
The new ones are still hard to spot from a distance in the fog.

![Screenshot_BoA_20220619_150927](https://user-images.githubusercontent.com/77861029/174482758-008ceb72-acf7-4be6-bffc-f607004db899.png)

![Screenshot_BoA_20220619_150939](https://user-images.githubusercontent.com/77861029/174482829-4252add8-1234-453f-a2ad-79540789dd5f.png)

And some are just too high to see them

![Screenshot_BoA_20220619_143103](https://user-images.githubusercontent.com/77861029/174482788-8897a7da-1456-4cd6-936a-df94f64600a4.png)

**Comment by AFADoomer** [comment]
I'll revert the change.  Too many small gripes and complaints, despite this being exactly how modern games handle these things.  Screw it.  Not changing anything else.  Mark as [won't fix].

**Comment by x3003** [comment]
Yeah, the fix was maybe worse than the original code.

**Comment by AFADoomer** [comment]
Fuck you, too.

**Comment by hawkwind3** [comment]
Can I make a suggestion ...
How about exclamation marks, and the like, only appear on the compass ?
IRL you would not see an exclamation mark appear mid-air. 
( I do realise this would be the case with a compass, but hey ... )

**Comment by Tormentor667** [comment]
> Can I make a suggestion ... How about exclamation marks, and the like, only appear on the compass ? IRL you would not see an exclamation mark appear mid-air. ( I do realise this would be the case with a compass, but hey ... )

That won't happen.
