### ISSUE TITLE
[C3M5_C] Faster on top (tilt script)

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1259]
This one is funny. If the timer is running (and only then) when you lean towards the front (constantly) when the elevator is going up, you clip through a section and get to the top faster than the elevator.

![Screenshot_BoA_20220606_211936](https://user-images.githubusercontent.com/77861029/173188983-ff21f338-35a8-40e1-8478-e23098648de0.png)

**Comment by Tormentor667** [comment]
This has most propably something to do with the tilt script that @AFADoomer has implemented. Maybe he has an idea.

**Comment by Username-N00b-is-not-available** [comment]
Even if the tilt is very small (use ```pukename "SetTilt" 1 1``` in the console on TEST_LDR), you can easily Quake style bunnyhop to speeds around 60 (and outrun bullets at 15 degrees). You don't even have to strafe or turn the camera.

**Comment by Username-N00b-is-not-available** [comment]
Is there a reason why https://github.com/Realm667/WolfenDoom/blob/345c56325348afa8b49cad600d3d4414e631ae62/scripts/actors/player.txt#L274
has a ```!leveltilt``` condition? It was added in this early 2018 commit: https://github.com/Realm667/WolfenDoom/commit/7e4e004630e40c4597a5ebf4af81c21eec489222. If I remove it, there is no bunnyhopping anymore.
