### ISSUE TITLE
C3M0_A performance issues

### ISSUE THREAD

**Issue by DungeonMaster555** [Realm667/WolfenDoom#1263]
На c3m0 есть проблема со слишком большим спавном , что через какое то время играть становится невозможно, надеюсь что в выпуске 3.2 добавят настройки для управления их спавном или какой нибудь аддон.

**Comment by Tormentor667** [comment]
English please.

**Comment by DoomJedi** [comment]
On c3m0 there is a problem with too much spawn, that after a while it becomes impossible to play, I hope that in release 3.2 they will add settings to control their spawn or some kind of addon (google translate)

**Comment by Tormentor667** [comment]
Which one do you mean? C3M0_A or C3M0_B?

**Comment by DungeonMaster555** [comment]
> 

И то и другое

**Comment by DungeonMaster555** [comment]
> Какой из них вы имеете в виду? C3M0_A или C3M0_B?

c3m0_A

**Comment by DungeonMaster555** [comment]
> Я думаю, он имеет в виду особенно в городе, где их много нападает на тебя
 Лагает весь уровень от леса до города, хотя в городе немного слабее

**Comment by DoomJedi** [comment]
Yes, you probably means the city area, and after a while it causes big lags.

**Comment by DungeonMaster555** [comment]
> Да вы наверное имеете в виду городской район, а он через некоторое время вызывает большие лаги.

in the forest it also lags, and when there are too many zombies, it starts to lag even in a cave

**Comment by MuadDib90** [comment]
I remember there was a discussion about "too little" zombies in this level to be a "sufficient horror", so their increment ratio was raised. And thus on less powerful stations this happens.

I've played it many times, and the increment "as is" is fine by me (to be enjoyable). But I understand its negative effect. I have 2 ideas:
- Can we just set a variable depending on an actual number of zombies on a map, so with higher number on a map the increment is gradually (and rapidly) reduced.
- Or we can just set the max. number of zombies on a map at given time, and after reaching this particular number, the increment is set to "0"; in case you kill some zombies in this state, the incerement is again set "ON", so the max limit can be reached again.

Torm, is it OK to kind of "bypass" the issue (or at least reduce the effects) by one of these?

**Comment by DungeonMaster555** [comment]
> Я помню, как обсуждалось, что на этом уровне «слишком мало» зомби, чтобы быть «достаточно ужасным», поэтому коэффициент их приращения был увеличен. И при этом на менее мощных станциях такое бывает.
> 
> Я играл в нее много раз, и инкремент «как есть» меня устраивает (чтобы доставлять удовольствие). Но я понимаю его негативное влияние. У меня есть 2 идеи:
> 
> * Можем ли мы просто установить переменную в зависимости от фактического количества зомби на карте, чтобы при большем количестве на карте приращение постепенно (и быстро) уменьшалось.
> * Или мы можем просто установить макс. количество зомби на карте в данный момент времени, и по достижении именно этого числа приращение устанавливается на «0»; в случае, если вы убьете несколько зомби в этом состоянии, инсермент снова будет включен, так что максимальный предел может быть снова достигнут.
> 
> Торм, можно ли как-то "обойти" проблему (или, по крайней мере, уменьшить последствия) с помощью одного из них?

If you think about it, would it be better to set the max amount for undead spawn so that everyone can set the spawn limit as they want

**Comment by DungeonMaster555** [comment]
> Я помню, как обсуждалось, что на этом уровне «слишком мало» зомби, чтобы быть «достаточно ужасным», поэтому коэффициент их приращения был увеличен. И при этом на менее мощных станциях такое бывает.
> 
> Я играл в нее много раз, и инкремент «как есть» меня устраивает (чтобы доставлять удовольствие). Но я понимаю его негативное влияние. У меня есть 2 идеи:
> 
> * Можем ли мы просто установить переменную в зависимости от фактического количества зомби на карте, чтобы при большем количестве на карте приращение постепенно (и быстро) уменьшалось.
> * Или мы можем просто установить макс. количество зомби на карте в данный момент времени, и по достижении именно этого числа приращение устанавливается на «0»; в случае, если вы убьете несколько зомби в этом состоянии, инсермент снова будет включен, так что максимальный предел может быть снова достигнут.
> 
> Торм, можно ли как-то "обойти" проблему (или, по крайней мере, уменьшить последствия) с помощью одного из них?

in that case, it's better to add a setting for undead spawning so that everyone can set the zombie limit as they want

**Comment by DungeonMaster555** [comment]
in that case, it's better to add a setting for undead spawning so that everyone can set the zombie limit as they want
--
Отправлено из Mail.ru для Android понедельник, 25 июля 2022г., 10:19 +05:00 от MuadDib90  ***@***.*** :

**Comment by x3003** [comment]
And maybe deathhunter can be adjusted as well. In the last building you fight him 3 times or so, which is quite a lot and getting to the point it becomes quite annoying. Most ppl won't have a lot of ammo left in that building (until the last room) and fighting him is a bit tricky then.

**Comment by Ozymandias81** [comment]
Afaik the actor spawning zombies was already tweaked, mappers should define a limited amount of them and that's all, was it like this @AFADoomer ?

**Comment by Username-N00b-is-not-available** [comment]
I get especially large lags after the Nemesis (Death Hunter) is spawned or killed (at least for the first time). ```stat vm``` gives around 100k (per 10 tics) normally on the map, and after its death there is a spike to 1.5mil for a few seconds.

**Comment by Username-N00b-is-not-available** [comment]
Can't finish C3M0_A at all: one Kraut left. Might be because of a half-dead Officer in the Dr. Schabbs room.

**Comment by x3003** [comment]
Seems this map (the city) lags more than sometime ago. It's not only when deathhunter spawns, but also inside the bar and around the fire in the middle of the map.

**Comment by Talon1024** [comment]
This mission is completely playable for me. Most of the time, sprite rendering (shown as S in the `stat rendertimes`) output takes the most time (5ms for me).

Sprite rendering can be toggled using `toggle gl_render_things`.

The thinkers don't seem to be the main source of performance issues for me, since the highest total think time seems to come from the dynamic lights and `AlertLight`s.

BTW:
- I'm using the fullscreen HUD.
- I have all weather effects turned on
- `r_maxparticles` is set to 4096
- Grass rendering distance is set to 2048
- Scenery rendering distance is set to 4096
- Special effect rendering distance is set to 2048
- Tree rendering distance is set to 4096

**Comment by x3003** [comment]
In the city framerate might be 20-30 fps (sometimes higher), settings set to 16K, blur and so fxaa off w/ vulkan.
Think the biggest problem is that gzdoom doesn't support a gpu, but relies on the cpu. Also think that's why ppl w/ a faster gfxcard than 'ours' struggle so much (faster gpu, slower cpu).
