### ISSUE TITLE
I've rewritten the opening letter (french)

### ISSUE THREAD

**Issue by LightShaft** [Realm667/WolfenDoom#1264]
It was my first impression of the game and it didn't felt natural, I've corrected a few errors (the word « Basiquement » was used twice and does not really exist in our language, it wouldn't have been used in a letter in a WW2 context, it's a poorly translated « basically ») reworded some sentences and some other stuff to make it feel like a bit more « natural », like it's written on a letter, by a soldier in WW2 to a friend of his. Some sentences just felt wrong, like, nobody would ever write or talk like that in real life. I've copied the english equivalent to google translate and got the same thing. So yeah I guess the opening letter should feel less « google translated », therefore leaving a better first impression.

Maybe I'll do some other stuff too, for now it's really the opening letter that completely kicked me out of it just because it just felt wrong and I genuinely hated the use of « Basiquement »
[language.csv](https://github.com/Realm667/WolfenDoom/files/9388253/language.csv)

Is it how I'm supposed to submit a contribution tho ? It's not the first time I'm using Github but it's the first time I'm contributing so I'm sorry if that's not where I am supposed to be, I swear I've searched and tried to do good

**Comment by MuadDib90** [comment]
Hi @LightShaft, many thanks for that. It is true, that some of the lines for some languages were translated with the help of "autotranslator" of some kind (but not remember if this letter was the case though).

If this letter would be the only thing "to repair" from you, I can add/repair it myself (I presume it is repaired in enclosed CSV).

If you would be willing to check and repair also other stuff/lines (which would be really great), you'll need an access permission from @Tormentor667 to our CSV, where I could show you how to work with it. :) Torm, what do you say?

**Comment by Tormentor667** [comment]
I am more than open if a native french speaker is willed to improve our existing translation.

If there is interest please send me your email for accessing the google spreadsheet :)

**Comment by LightShaft** [comment]
@Tormentor667 I'd be happy to send my gmail account to do some corrections and a second read, but I'd rather not give it away publicly as it contains my real name.
The thing is, I don't know how often I could help out, so if there's no worries with that I'd be happy to help the best I can :)
Sorry for the answer 1 month later btw ...

**Comment by Tormentor667** [comment]
No problem, you can drop me a line at info@realm667.com with your GMail adress and I will invite you :)
