### ISSUE TITLE
C1M2 - Killing shark causes crash

### ISSUE THREAD

**Issue by a-mad-dragon** [Realm667/WolfenDoom#1265]
console says:
VM execution aborted: tried to read from address zero.
Called from FlatNumber.PostBeginPlay at boa.ipk3:scripts/actors/gatekeeper.zs, line 880

**Comment by Talon1024** [comment]
Are you using the score addon? This is (IIRC) a known issue with that addon.

**Comment by x3003** [comment]
There was already some kind of fix sometime ago. See commit #942 
You can try to copy the newer version of gatekeeper.zs in boa.ipk3, so you can continue playing.

**Comment by Ozymandias81** [comment]
It has been fixed laready long time ago, so gonna close this.
