### ISSUE TITLE
Some parts falls through floor

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1268]
In c1m2, when you shoot the enemy above, some parts incl blood falls through the floor.

![Screenshot_Doom_20220917_120812](https://user-images.githubusercontent.com/77861029/193397075-93149676-c764-46ee-b193-079d4290bdbb.png)

**Comment by x3003** [comment]
It's on smart.

**Comment by Username-N00b-is-not-available** [comment]
Can see this effect but it does not seem to change at all with the clipping options. Anyway here the best option would be to make the 3d floor at least 8 mapunits high instead of 8.
