### ISSUE TITLE
Refresh 3.1 with new GZDoom

### ISSUE THREAD

**Issue by KAMiKAZOW** [Realm667/WolfenDoom#1269]
Newer GZDoom releases fixed a few bugs that affected me and my hybrid graphics setup, most notably the refusal to run on the dedicated GPU despite being explicitly activated. I've started to play 3.1 on top of GZDoom 4.8.2 and so far there are no problems.

Since 3.2 seems to take some time until it's ready, I suggest making a 3.1.1 release that updates the engine and nothing else.

**Comment by Talon1024** [comment]
The first mission of Chapter 2 is broken on GZDoom 4.8.2. However, it is fixed in the latest GZDoom development builds.
