### ISSUE TITLE
destroyed gun goes through the wall

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1270]
In c3m4, when you destroy this gun, part of it goes through the wall. Which is strange, as when you destroy the other 2, these look fine.

![Screenshot_Doom_20221016_214452](https://user-images.githubusercontent.com/77861029/198268232-9c4eedf8-4350-4bd8-b9d6-623fdb8147df.png)

![Screenshot_Doom_20221016_214153](https://user-images.githubusercontent.com/77861029/198269220-439caf7e-0a3a-4849-83f8-bd9b673921e9.png)

This one is fine:

![Screenshot_Doom_20221016_214830](https://user-images.githubusercontent.com/77861029/198268560-e8b754ea-be17-4442-a09f-c4f5238a1ed4.png)

**Comment by Ozymandias81** [comment]
The cause of this issue belong to how Destroyed actors are managed with the zscript behavior, since it doesn't transfer properly the scale between frames. I don't know how to handle this, it needs to be sorted by @AFADoomer or if he can @Talon1024

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 This is not related to ZScript... The 3d model is not being destroyed (it can't be), rather there is an ACS script (written by my wrong hands) that replaces the Flak with its destroyed version when a (specific!) nearby shell is detonated. Of course it did not handle scaling...
The 20mm guns are destroyed as actors (they have 350 health, just enough to survive the nearby ammo explosion, but not a rifle bullet afterwards, hehe), not by scripts.
I do not remember myself having 'fixed' other maps in such a way, so I hope this is a one-time occurrence :-) Will commit later.
