### ISSUE TITLE
BoA 3.1 freezes on launch on GZDoom 4.9.0a (Linux Mint 21)

### ISSUE THREAD

**Issue by mrmatteastwood** [Realm667/WolfenDoom#1273]
**Steps to Reproduce:**
1. Download GZDoom 4.9.0a from https://zdoom.org/downloads and install on Linux Mint 21
2. Get latest Blade of Agony 3.1 from https://www.moddb.com/mods/wolfendoom-blade-of-agony/downloads/blade-of-agony-full-release-v30-standalone
3. Open terminal and go to folder where boa.ipk3 is
4. Launch by typing `gzdoom -iwad boa.ipk3 -file boa_dt.pk3`
5. Open main menu
6. Start new game
7. Select episode 1
8. Select default difficulty

**Current Results:**
The game freezes after step 7. Need to kill gzdoom by pressing Ctrl+C in terminal.

**Expected Results:**
The game should work.

**My System Specs:**
https://termbin.com/gx41

**Terminal Output:**
[boa-freeze-2022-11-09.txt](https://github.com/Realm667/WolfenDoom/files/9972004/boa-freeze-2022-11-09.txt)

**Notes:**
Encountered on Linux Mint 21. Not sure about other operating systems.
Issue also occurs when omitting `-file boa_dt.pk3` from launch command.

**Comment by Talon1024** [comment]
[This is a known issue](https://github.com/ZDoom/gzdoom/issues/1768). For now, use a GZDoom development build or GZDoom 4.7.2.
