### ISSUE TITLE
Some hitboxes

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1274]
There are some annoying hitboxes here:

In c3m6_a **standing** behind a rock.

![Screenshot_Doom_20221021_154414](https://user-images.githubusercontent.com/77861029/205744821-73e4f1e7-d1c0-4de1-ad7d-781608cd539c.png)

and some big ones around these statues in c3m6_b, which not only makes it hard to fire, but also harder to walk around them.

![Screenshot_Doom_20221022_140520](https://user-images.githubusercontent.com/77861029/205744859-d8fe7a7b-ae84-4605-b367-16c61e0483c0.png)

![Screenshot_Doom_20221022_141409](https://user-images.githubusercontent.com/77861029/205744878-19f29a5a-1d76-4d88-b193-cb76d8152465.png)

![Screenshot_Doom_20221022_141415](https://user-images.githubusercontent.com/77861029/205745128-3d58f362-8ed6-4a1b-9d0a-99b8eb9bb23a.png)

**Comment by x3003** [comment]
In c3m6_a the problem wasn't the rock, coz the hitbox is still there.

![Screenshot_Doom_20230121_230636](https://user-images.githubusercontent.com/77861029/213888880-e2e74af3-5baa-4099-be44-107518d63c38.png)

**Comment by Ozymandias81** [comment]
It is the rock cause it is set to random, but the EffectsManager messes up with scaling and something internal, I will force the big shape.
