### ISSUE TITLE
douglas is gone after a while

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1277]
In c2m6_c, when you don't make contact w/ douglas yet, but still check the area, when you come back he's gone. But still gives the message as if he's there.

![Screenshot_Doom_20221202_221829](https://user-images.githubusercontent.com/77861029/205746830-5354e34d-0e4c-44ef-9f3c-ea300adc91c5.png)

**Comment by Username-N00b-is-not-available** [comment]
Douglas on this position will now be removed much later, right before the second encounter.
