### ISSUE TITLE
some issues with c3m3_b

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1279]
First, the 'objective accompliced' should be given when entering the building, not while standing just short of it. Maybe push the line back a little.

![Screenshot_Doom_20221205_220846](https://user-images.githubusercontent.com/77861029/205748051-7d38044b-b3b5-4bcc-9c5b-10f8393c9e26.png)

Second, the end of the tank barrel goes through the door.

![Screenshot_Doom_20221205_220931](https://user-images.githubusercontent.com/77861029/205748059-8e650179-8165-46c3-9ae0-6441547a5768.png)

And I did my best to grab all these green objects, but still didn't had enough to get in, so maybe lower the number a bit ? And yes, I started from c3m1, not w/ map/changemap.

![Screenshot_Doom_20221204_174806](https://user-images.githubusercontent.com/77861029/205749079-e2c6c75e-a7eb-4e6f-818a-8d36414d3605.png)

**Comment by MuadDib90** [comment]
Regarding the 3rd issue, the difference is in - iirc - if you played the secret mission after the first one (to access it you have to obtain all 6 evidence in the first one).

**Comment by x3003** [comment]
Yeah, you're right on the 3rd issue. But it still would be nice to access if you didn't  played that mission. So many keep it at 50 if you've played that one and lower it if you haven't.

**Comment by MuadDib90** [comment]
Well, I think, Dan said to me - as I asked the same question - it is intentional as this...

**Comment by Tormentor667** [comment]
3rd is intentional.

**Comment by x3003** [comment]
>3rd is intentional.

Could be, but you **can** enter when you're on the lower level (even from pistol start), but not when on a higher one, which seems a little unfair.
