### ISSUE TITLE
can't break mirror

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1282]
In c2m6_b, you can't break this mirror by shooting directly at it. To break it, shoot **below** the windowframe.

![Screenshot_Doom_20230107_103406](https://user-images.githubusercontent.com/77861029/211144037-a3631b34-b7a2-4504-8ad0-986fffa8d34b.png)

**Comment by Tormentor667** [comment]
Fixed it (hopefully), even though it should have worked before already.

**Comment by x3003** [comment]
It works, almost. You can still hit under the mirror to break it. Where the mouse is pointing at, is about the point of breaking it.

![Screenshot_Doom_20230108_105739](https://user-images.githubusercontent.com/77861029/211190041-30abeac6-ca67-4ff8-9cbb-ad1a96a8f80f.png)

**Comment by Tormentor667** [comment]
I really don't get it. The bottom wall is not doing any action when beig hin. I can only imagine that it has something to do with the size of the projecle. Maybe @Talon1024 or @Ozymandias81 can take a look at it.

**Comment by Ozymandias81** [comment]
Solved, the space was too narrow, there was a wrong flag set (any non-missile) and also had to move the door on the opposite space. Now it works as intended.
![image](https://user-images.githubusercontent.com/11136108/211817882-88e6a8ab-4afb-413b-aaf3-c49a69dde258.png)

**Comment by x3003** [comment]
Yep, now it works as expected. 👍
