### ISSUE TITLE
guards explode when hit by shovel

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1283]
When you hit guards w/ the shovel when are standing on the toilet (and haven't turned around yet), they explode. I saw this on c3m0_a btw, but it's easier to reproduce on c2m6_b.

![Screenshot_Doom_20230107_103230](https://user-images.githubusercontent.com/77861029/211144308-7561c9eb-e3fb-457a-8224-e3579ec6803b.png)

**Comment by Username-N00b-is-not-available** [comment]
Fixed in my upcoming commit.
