### ISSUE TITLE
soldier can't stop shooting

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1287]
In c3m2, I found this soldier shooting constantly at the first responder (who came into the base) and surrendered. Later when I came back, after taking care of the radio, he was still shooting. But, when I was in line of fire, I also got hurt from the shots.

![Screenshot_Doom_20230107_233509](https://user-images.githubusercontent.com/77861029/211190128-60560204-e67b-41ce-a360-bb61d9816782.png)

![Screenshot_Doom_20230107_164407](https://user-images.githubusercontent.com/77861029/211190130-0ad5acb7-4429-4d7f-99d3-82921f92fb70.png)

**Comment by Username-N00b-is-not-available** [comment]
This type of PlayerFollower behaviour is likely to have been fixed by my yesterday commit. The marine will lose the target when the medic surrenders (and will not re-target the medic).
