### ISSUE TITLE
scrambled letter

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1288]
With the latest git version, in c2m3, this letter is a bit scrambled.

![letter1_1](https://user-images.githubusercontent.com/77861029/212374002-82d65b4c-fc9c-4ce1-9ccb-dab29cdf1e99.jpg)

![letter2](https://user-images.githubusercontent.com/77861029/212373738-9e2dd777-df40-49af-94eb-12b7e5604b93.JPG)

**Comment by Talon1024** [comment]
I think this is a GZDoom issue, rather than a BoA issue, and it may be related to [this commit](https://github.com/ZDoom/gzdoom/commit/aceafecce6cd0552e395a1265f9e556c7cf38b97), since the font used on that letter is a "sheet font".

**Comment by x3003** [comment]
Ahhhh. I checked w/ 4.11 pre29 and the issue is indeed gone.
