### ISSUE TITLE
Alarm goes off too soon

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1295]
In c1m2, the alarm goes off when you touch this door, w/o even opening it.
It would be nice if the activationline is triggered a bit later, when the player actually goes through the open door.

![Screenshot_Doom_20230421_173318](https://user-images.githubusercontent.com/77861029/233677807-f941ccce-69ae-490d-a489-3ab5c60f088d.png)

**Comment by Username-N00b-is-not-available** [comment]
Can be easily done, but this nitpick is too minor as for me. The alarm could have been triggered by a proximity device, not the door mechanism.
What do you think, @Ozymandias81 and @Tormentor667?

**Comment by x3003** [comment]
Yeah, it's a nitpick ;) But consider this as putting the dot on the i :)

**Comment by Username-N00b-is-not-available** [comment]
Will commit later.
