### ISSUE TITLE
douglas doesn't shoot dogs....

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1297]
....anymore

To reproduce:
-start boa
-map c1m0
- go find a dog, now douglas doesn't react anymore to the dog.

Checked the boa version from a week ago and that was still working correctly. 

![Screenshot_Doom_20230423_112036](https://user-images.githubusercontent.com/77861029/233832834-8fae1978-0d80-49a6-82c0-5eb8dd276bf4.png)

![Screenshot_Doom_20230423_113059](https://user-images.githubusercontent.com/77861029/233832841-3614fa0f-85e1-4659-aec0-ade86c5131cf.png)

**Comment by Username-N00b-is-not-available** [comment]
This is because of my recent surrendering enemies commit.
The dog has +NEVERTARGET set, looks like I'll have to do a workaround...

**Comment by x3003** [comment]
Only now, douglas shoots surrendered enemies again....

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Details, please..?

**Comment by x3003** [comment]
Well, first douglas didn't react to the dog, but he didn't kill a surrendered scientist in the lab (on c1m0).
After the fix,  he did react to the dogs again, but now he shoots a surrendered scientist again.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 He does **not** kill surrendering scientists on my machine (or I wasn't able to find circumstances in which he does). On which map and in which area have you seen this behaviour, what have you been doing?

**Comment by Username-N00b-is-not-available** [comment]
Hmmm, this one he indeed **does** kill. I wonder what's the difference between them...
![image](https://user-images.githubusercontent.com/59409713/233865106-a1c0c769-2d9a-4f3d-a3f2-e31af4c9c3d7.png)

**Comment by x3003** [comment]
>Hmmm, this one he indeed does kill.

Yes, that's the one.
