### ISSUE TITLE
unknown object when loading older savefiles

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1298]
Something has changed in the game.
When loading an older file (older than today) I get this message

![Screenshot_Doom_20230423_114249](https://user-images.githubusercontent.com/77861029/233833124-6059dea9-b0ea-45ec-a81d-ef0880cb1797.jpg)

But when pressing any key incl. ESC it only gives me more and more of those warnings.
And eventually it might even crash gzdoom (when pressing multiple times ESC).

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Please try the current commit...

**Comment by x3003** [comment]
>Have you by chance not deleted the savegames yet?

I have plenty, so I don't have to replay the whole game from the start if I wanna try something.

You fix seems to work.
