### ISSUE TITLE
sand storm inside building

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1299]
With the latest git version, in c1m6, there's a constant sand storm inside of this building.

![Screenshot_Doom_20230423_194132](https://user-images.githubusercontent.com/77861029/233857334-9f095fbe-4dda-4119-a07b-c9c5f9e39504.png)

![Screenshot_Doom_20230423_194142](https://user-images.githubusercontent.com/77861029/233857340-cfaf5d52-3996-4d1c-a340-df06db9a1f6a.png)

![Screenshot_Doom_20230423_194523](https://user-images.githubusercontent.com/77861029/233857355-e49c217c-0589-4a8f-899c-ef8c4343949b.png)

**Comment by Tormentor667** [comment]
Do particles ignore impassable walls?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Yes, they are way more simple than actors and basically only 'know' how to fade, rotate and move in a linear/quadratic fashion.

**Comment by Tormentor667** [comment]
Would be less bug-friendly as moving geometry.
