### ISSUE TITLE
Proposal for solving C1M0 framerate issues. (Please scroll down and read!)

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#13]
Title says it all. If there is no line of sight between the player and the grenade, the explosion does not appear, and the grenade does no damage.

To reproduce this bug, go to the training course, and try to pass the part where you have to hit buried targets with your grenades.

**Comment by AFADoomer** [comment]
Should be fixed [now](https://github.com/Realm667/WolfenDoom/commit/268aa9939d3633b59324751a2a1f8e0b23e57e73).

**Comment by Talon1024** [comment]
OK, thanks for the quick fix!

**Comment by Tormentor667** [comment]
Thanks for the fix AFA

**Comment by Talon1024** [comment]
I hear the changes that caused this issue in the first place were made to improve performance at the end of C1M0. In that case, how about creating some new `SceneryExplosion` actors that do nothing if they aren't in the player's LoS?

**Comment by AFADoomer** [comment]
Because making the actor do that is what broke the grenades in the first
place?

**Comment by Talon1024** [comment]
I'm talking about creating separate `SceneryExplosion` actor classes, not modifying the existing explosion actor classes.

**Comment by Ozymandias81** [comment]
Did a small change for the purpose today: let's see what others think.
With [this small tweak](https://github.com/Realm667/WolfenDoom/commit/68fbc960548c10aa18e936b4b78b046478082c66) I gain 10fps on my crappy rig (Athlon x2 3ghz, GeForce GT 610 1gb, 2gb total, Win7 sp1 32bit)

**Comment by Talon1024** [comment]
> (my personal interpretation anyway, don't know if it's exactly what he means though but it works ime)

Yep, that's exactly what I mean. Thanks for making these changes.

**Comment by Ozymandias81** [comment]
Well it seems there are no issues with such commit, so I close this another time... but feel free to re-open this if something more weird will pop up :+1: 
Anyway thanks a lot Talon1024 for your suggestions.
