### ISSUE TITLE
walking on the roof

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1301]
In c2m5_a, there is a spot on the train were you aren't suppost to go, but still can walk on the roof a bit further.
When that happens you see the sides move, instead of the train.

![Screenshot_Doom_20230428_084142](https://user-images.githubusercontent.com/77861029/235077240-e9f76be5-369c-4053-89ef-aaa7ef9fb455.png)

![Screenshot_Doom_20230428_084153](https://user-images.githubusercontent.com/77861029/235077244-0760c3d7-91ad-4eb9-9ecd-7f96f151ca63.png)

![Screenshot_Doom_20230428_084202](https://user-images.githubusercontent.com/77861029/235077250-c9828366-483e-496c-9921-27b26c1ab0bd.png)

**Comment by Username-N00b-is-not-available** [comment]
Added 'walkable' player-blocking lines around Y = 5536, will commit later.
