### ISSUE TITLE
missionitems shouldn't be there at the beginning

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1302]
In c2m5_a, most of the missionitems are there from the start. But when going to c2m5_b, these are re-added to the list.
So why not remove them (the lower 3 items) from the list in c2m5_a ?

![Screenshot_Doom_20230428_085115](https://user-images.githubusercontent.com/77861029/235077594-cbb51bba-2e6e-476f-bd33-463877bd5d8c.png)

![Screenshot_Doom_20230428_085630](https://user-images.githubusercontent.com/77861029/235077600-6d6e45ee-dfcc-45b3-aed8-17f894562367.png)

**Comment by Username-N00b-is-not-available** [comment]
Fixed it.

**Comment by x3003** [comment]
The only small problem now is, the user can't see the effect (red added objectives) because the objectives are turned off when going from c2m5_a to c2m5_b.
