### ISSUE TITLE
message too soon

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1303]
In c2m4, this message comes too soon. I think it should be shown when you actually beat the úbersoldat. A message in the middle of a fight is not good anyway.

![Screenshot_Doom_20230427_235714](https://user-images.githubusercontent.com/77861029/235078921-e77e6f3e-4b7f-4a43-8c08-d918df897115.png)

**Comment by Tormentor667** [comment]
Thank you for continuing testing :)

**Comment by Username-N00b-is-not-available** [comment]
Fixed.
