### ISSUE TITLE
double question marks

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1304]
Somehow there are double question marks with these papers.
When picking it up, one remains.

![Screenshot_Doom_20230428_123315](https://user-images.githubusercontent.com/77861029/235290118-6065122c-cf5c-4706-a9e7-bd70118e78c3.png)
![Screenshot_Doom_20230428_123326](https://user-images.githubusercontent.com/77861029/235290122-e9b13d9d-1b37-48cd-b106-2cc788d72ab1.png)
![Screenshot_Doom_20230428_152028](https://user-images.githubusercontent.com/77861029/235290123-fc243b79-3300-4f45-b322-487220039726.png)
![Screenshot_Doom_20230428_152041](https://user-images.githubusercontent.com/77861029/235290125-0e1c09f8-1246-4491-8446-7e592be65a9c.png)

**Comment by Username-N00b-is-not-available** [comment]
After AFADoomer added automatic spawning of markers on papers in https://github.com/Realm667/WolfenDoom/commit/21b1b67c441dd166ef361ac113545fde489318a8, the map-placed paper markers should be removed from all maps. However the markers are also used for safes, and maybe other things I do not know about. The way to go would be removing them manually from papers on all the maps.

**Comment by x3003** [comment]
The odd thing is, not every map has double question marks. This one doesn't.

![Screenshot_Doom_20230429_140750](https://user-images.githubusercontent.com/77861029/235302031-b3e8cb3e-d673-4775-bfbe-a859894b57db.png)

**Comment by Tormentor667** [comment]
I can remember that we discussed about adding question marks only on specific skill settings. Maybe that’s the deal?

**Comment by Username-N00b-is-not-available** [comment]
These marks won't show above Morgenspaziergang anyway. This is `skill 2` (Ordinary):
![image](https://user-images.githubusercontent.com/59409713/235345992-85beb91d-7fed-4d04-b2f7-1f438067bc6b.png)
This is `skill 1`:
![image](https://user-images.githubusercontent.com/59409713/235346013-2c7ee153-8c28-4952-be1a-bdae6e24151c.png)
The markers are currently both placed on maps and spawned by the paper actors; the second effect was added by AFADoomer not long before he left. So to fix this issue we either remove the map-placed actors, or the code part. If the problem is urgent, it can be solved by commenting out a single line (or two lines for complacency), but in my opinion the automatic spawning is superior. It's that I just did not want to edit all the maps at the time (planned to do that when we deal with more important issues).

**Comment by Tormentor667** [comment]
The automatic placement is definitely superior. So if I understand it correctly, we simply need to remove the question mark actors from the maps where they are placed near a paper, is that correct? I can do that if it's okay to you.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Yes, but that needs to be done on every map where the papers are (and not **all** question mark actors should be removed, only the ones which are above hint papers), so it would be quite a lot of hassle given the map loading times in the editor.
Thank you!
You can search for this thing type in UDB:
https://github.com/Realm667/WolfenDoom/blob/3552a946a3248f99ffd5eec40991f937adbca430/mapinfo.txt#L1272
and check whether it is above a hint paper or not.

**Comment by x3003** [comment]
It's not only the questionmarkactors. These papers are also affected, even on the same map.

These have one:

![Screenshot_Doom_20230430_223524](https://user-images.githubusercontent.com/77861029/235532648-ea2f2c8c-c09c-41fb-9486-61e03f87ac86.png)

![Screenshot_Doom_20230430_223549](https://user-images.githubusercontent.com/77861029/235532654-a48fa7b2-81bb-4a39-b8ef-999ef477d959.png)

And these have two:

![Screenshot_Doom_20230430_223509](https://user-images.githubusercontent.com/77861029/235532585-faa8dd0d-b03a-4888-a6f7-7cde5192f135.png)

![Screenshot_Doom_20230430_223829](https://user-images.githubusercontent.com/77861029/235532591-cb0f1754-c4a5-4d12-b823-70665064034a.png)

**Comment by Username-N00b-is-not-available** [comment]
OK, tomorrow I'll try to edit the maps.

**Comment by Tormentor667** [comment]
Thanks for taking care @Username-N00b-is-not-available
