### ISSUE TITLE
can't pickup grenade

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1305]
In c2m0_b, you can't pickup this grenade. The only way to pick it up is to clip to it.

![Screenshot_Doom_20230429_094023](https://user-images.githubusercontent.com/77861029/235291097-501e1b4c-89ec-4465-8ef6-ac9d00355f82.png)

**Comment by Username-N00b-is-not-available** [comment]
Heh, you can pick it up [even when the hatch is closed](https://doomwiki.org/wiki/Grab) by sprinting from the bed towards its position. There is also an option to jump near the alcove, then quickly crouch when still in air, and move forward.

**Comment by Tormentor667** [comment]
Shouldn’t we make it easier accessible?

**Comment by Username-N00b-is-not-available** [comment]
If it is moved closer to the edge, you will be able to take it consistently from the outside even without bumping. Or we can make a very tall hatch (around player height) which will make little sense to be in a prison cell.
The decision is yours anyway @Tormentor667 :-)

**Comment by Tormentor667** [comment]
What about making the height of the room where the object is placed in higher so the player can enter it without crouching?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Yeah, it's the better variant. 56 units would I think be sufficient, but it can also be 64.

**Comment by Tormentor667** [comment]
Thanks for taking care :)

**Comment by Username-N00b-is-not-available** [comment]
It does not look like the hatch was actually raised in this specific issue 😅, forgot about it... Let's reopen the issue.
