### ISSUE TITLE
radio placed too high

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1306]
In c2m5_b, this radio is placed too high.
So either move it on the desk or leave it out completely ?!

![Screenshot_Doom_20230428_095405](https://user-images.githubusercontent.com/77861029/235291232-7e264c48-74ef-4894-bfdd-b3bab213714d.png)

**Comment by Username-N00b-is-not-available** [comment]
Maybe it's a faulty radio that is waiting for maintenance.
I'll fix the other 4 recent issues, these are important.
