### ISSUE TITLE
Pipe is broken

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1307]
In c3m0_a this pipe seems broken.

![Screenshot_Doom_20230430_223257](https://user-images.githubusercontent.com/77861029/235532945-1a68c857-7ceb-48fe-8c3b-64b7aa09616d.png)

**Comment by Username-N00b-is-not-available** [comment]
Fixed in upcoming commit. Will this be better?
![image](https://user-images.githubusercontent.com/59409713/235613183-7ab6ee31-1298-40a8-9e8f-60f0a891e5ae.png)
