### ISSUE TITLE
snow inside buildings

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1308]
With the latest changes, it can now snow inside of buildings.
Just watch the white dots.

![Screenshot_Doom_20230501_232918](https://user-images.githubusercontent.com/77861029/235742838-8852c8ab-5916-49e2-913f-849f264a33e5.png)

![Screenshot_Doom_20230501_232839](https://user-images.githubusercontent.com/77861029/235742849-694bd6aa-5be9-4281-888c-5a71af13091c.png)

![Screenshot_Doom_20230501_232944](https://user-images.githubusercontent.com/77861029/235743000-3a2ceeeb-4afb-4522-a400-917b2237fc92.png)

**Comment by Talon1024** [comment]
Known issue. It's because the snowflakes are now particles, and particles don't interact with anything. I'm trying to mitigate this issue, but I don't want to slow down the game any more than I have to.

**Comment by Tormentor667** [comment]
How could that be solved?

**Comment by x3003** [comment]
Seems that this didn't only affected the snowparticles, but also the fireparticles.
 
![Screenshot_Doom_20230509_214915](https://github.com/Realm667/WolfenDoom/assets/77861029/240e9a04-c309-4df5-a11f-df4ca6d7b723)

![Screenshot_Doom_20230509_214954](https://github.com/Realm667/WolfenDoom/assets/77861029/c7769539-bac8-4bd4-9539-3ebbac16fc13)
