### ISSUE TITLE
Some locked doors are not actually locked

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#1309]
Some of the doors can be opened without the required keys. For example, I was able to open this door on C3M4 without the green key:
![Screenshot_Doom_20230507_120547](https://user-images.githubusercontent.com/6550500/236688996-90b115b9-b986-49da-9169-f0fe0e5501cd.png)

**Comment by Talon1024** [comment]
Maps left to check:

- [ ] C1M1
- [ ] C1M2
- [ ] C1M3
- [ ] C1M4
- [ ] C1M5
- [ ] C1M6
- [ ] C1M0
- [ ] C2M1
- [ ] C2M2
- [ ] C2M3
- [ ] C2M4
- [ ] C2M5_A
- [ ] C2M5_B
- [ ] C2M6_A
- [ ] C2M6_B
- [ ] C2M6_C
- [ ] C2M0_A
- [ ] C2M0_B
- [ ] C3M1_A
- [ ] C3M1_B
- [ ] C3M0_A
- [ ] C3M2
- [ ] C3M3_A
- [ ] C3M3_B
- [ ] C3M4
- [ ] C3M0_B
- [ ] C3M5_A
- [ ] C3M5_B
- [ ] C3M5_C
- [ ] C3M6_A
- [ ] C3M6_B

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 Do you check these in-game, or through an editor?

**Comment by Talon1024** [comment]
I'm checking these in-game.

**Comment by x3003** [comment]
yeah, you don't need the green key in c3m4

**Comment by Talon1024** [comment]
I took a quick look at C3M4 in UDB. Apparently, the switch that opens that door has the correct lock on it. My best guess is that this bug has something to do with @AFADoomer's toggle switch script.

**Comment by x3003** [comment]
Dunno about other doors, but atleast the green one in c3m4 is fixed.

**Comment by Tormentor667** [comment]
It would be cool if someone is able to contact AFA directly. He would be a big help atm.

**Comment by Talon1024** [comment]
I think I fixed this bug in 163d82326b2259a8ddeee000a99cc6e55266959b. Now I'm just making sure the bug is fixed for good.
