### ISSUE TITLE
Shooting light instead of enemy

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1310]
In c2m1, when you shoot the soldiers (in the towers) from about the waste down, you'll end up hitting the light bulb (and damaging it), so the light goes out. But the the bulb isn't even near the bodies of the enemy.

![Screenshot_Doom_20230425_003057](https://github.com/Realm667/WolfenDoom/assets/77861029/80208821-16a8-40ee-9dfd-ba50fd321340)

![Screenshot_Doom_20230505_154746](https://github.com/Realm667/WolfenDoom/assets/77861029/7ad38c86-2e8c-4c01-9e9d-648e1b6c61e9)

**Comment by Talon1024** [comment]
That's the "bullet drop" effect for you.

**Comment by x3003** [comment]
Can't be. I'm not that far before the towers.
And when the lights go out, I can actually hit the enemy.
