### ISSUE TITLE
Some clipping issues

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1312]
Some random clipping issues.

![Screenshot_Doom_20230519_133602](https://github.com/Realm667/WolfenDoom/assets/77861029/b28239bd-c01f-47b8-9867-86d8ee089aa6)

![Screenshot_Doom_20230514_215551](https://github.com/Realm667/WolfenDoom/assets/77861029/4cd44a99-1339-4c44-9874-bf6b94b34822)

![Screenshot_Doom_20230509_222601](https://github.com/Realm667/WolfenDoom/assets/77861029/0cb15401-1f86-463f-b0d2-559239ba10ca)

![Screenshot_Doom_20230506_160012](https://github.com/Realm667/WolfenDoom/assets/77861029/c235d429-f81b-44ab-86ed-daefd62ce87b)

![Screenshot_Doom_20230422_122035](https://github.com/Realm667/WolfenDoom/assets/77861029/6c7f1f7f-5fde-4a67-8cb4-f40b8e76ecf7)

![Screenshot_Doom_20230204_194409](https://github.com/Realm667/WolfenDoom/assets/77861029/ca423f3e-3a8d-4844-8215-755a54555132)

**Comment by x3003** [comment]
Some more issues

![Screenshot_Doom_20230715_232028](https://github.com/Realm667/WolfenDoom/assets/77861029/b2373567-5914-446e-9a05-3ca9ab7215c7)
![Screenshot_Doom_20230715_232037](https://github.com/Realm667/WolfenDoom/assets/77861029/87aafeb3-318e-4532-809d-6bfef204e619)
![Screenshot_Doom_20230715_232925](https://github.com/Realm667/WolfenDoom/assets/77861029/5abe5b77-583f-4281-bc52-ceec3facec23)

You can even clip w/ 2, really cozy ;)

![Screenshot_Doom_20230806_101826](https://github.com/Realm667/WolfenDoom/assets/77861029/bebab992-9d35-4d58-b3c1-6917652926af)

**Comment by hawkwind3** [comment]
Committed a fix to hopefully fix these. If OK please close this issue.
