### ISSUE TITLE
[Multiplayer] Position of multiplayer marker is off

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1318]
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/e51c0d50-cb9b-41af-8090-fda47bb9882a)
Shouldn't it be over the head of the player?

Summoning @AFADoomer

**Comment by AFADoomer** [comment]
It should, yes.  It looks correct on my end.  

What are your resolution/renderer/scaling settings?

**Comment by Username-N00b-is-not-available** [comment]
All hail @AFADoomer!
It's heartwarming to finally see a new post by yourself in the BoA repo.
To keep you busy right away 😈: there are multiple issues you can help with if you find time, in particular #1160 (by adding a new UDMF field on a line and overriding CanCrossLine?), #1193, #1225, #1244, #1249, #1262 (though unlikely to reproduce it), #1294 (in general, not just for these specific checkboxes), #1296 (it's BreakString). Had taken shots at some of them locally, but ultimately realized I'm not the person who knows the BoA code well enough to fix these.

---

As for this issue, on Vulkan it does not seem to occur (messed with some Display and Scaling options, still looks fine).

<details><summary>Off topic</summary>
However I can confirm that the cutscene darkened strips, like in @Tormentor667's picture, are not removed for the second player after the cutscene stops:

![image](https://github.com/Realm667/WolfenDoom/assets/59409713/7984e2d1-44ab-41b7-8f6a-60a6f8e0ac7e)
</details>

Maybe it's a desync, somehow undetected by the game?

**Comment by Tormentor667** [comment]
The GZDoom version I was using is
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/d1182305-9f40-452c-85fc-ec462f00c71c)

Resolution is 2560 x 1080 pixels
Render is OpenGL
Scaling is Adapt to screen sige (and default for everything), off for HUD aspect ratio and preserves

**Comment by Tormentor667** [comment]
Looks good to me with the latest versions, so closed.

![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/2abedf9b-a5b3-4ec7-857a-68e69e8ea5dc)
