### ISSUE TITLE
Very fatal error after silent kill in C2M5

### ISSUE THREAD

**Issue by Rxbsxn** [Realm667/WolfenDoom#132]
Hi, guys, I have found a strange bug in chapter 2 mission 5 and I decided to record it. Please check this out maybe you can find a solution to this error. I attach video and error screenshot.

https://www.youtube.com/watch?v=MmS8gui-6Ek&feature=youtu.be

https://ibb.co/m45YF5

**Comment by alexey-lysiuk** [comment]
Save report and attach to this issue. If you have saved games attach it too.

**Comment by Rxbsxn** [comment]
I uploaded save and crash files to drive, here is the link - https://goo.gl/j2Npsz
I also checked option with using knife to silent kill and the error don't exist in this case

**Comment by AFADoomer** [comment]
I can reliably replicate this bug in the released chapter 2 version of BoA, but I can't replicate it in the current development version of BoA.  

The issue was likely resolved in some of the changes we've made since the chapter 2 release (though I can't point to the code that would have been causing this in the first place).

**Comment by Ozymandias81** [comment]
This has been addressed and fixed since this commit, Mechanic had they health set to 2 for some reasons (bad copypaste)

 https://github.com/Realm667/WolfenDoom/commit/ca9f8e676918121b9d7f7b717215750bf806edad

**Comment by Ozymandias81** [comment]
Now it is [definitely fixed](https://github.com/Realm667/WolfenDoom/commit/e8ff3a5fbc5c1237d76537b59caed0869143e3be), thanks to AFADoomer

**Comment by AFADoomer** [comment]
This is actually an engine bug that was causing the crash - but since we don't need the Shovel to be silent anyway, removing the CPF_DAGGER flag from its attack function fixes the crash mod-side.

**Comment by Ozymandias81** [comment]
I reckon we had a similar issue back in the days, even with MaxED old stealth system... Weird.
