### ISSUE TITLE
[Steam Deck/SteamOS] Cannot launch game; weather effects are to blame.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1321]
I cannot seem to launch BOA on SteamOS, because there are too many argument calls from the weather effects. It only got as far as the clouds and snow, but I think the whole weather system is affected. Until this is fixed, the GitHub build is definitely not Deck-Verified.

![20230708101429_1](https://github.com/Realm667/WolfenDoom/assets/32436386/a7e15d61-677a-4356-8a56-7c3a73880003)

**Comment by Shockwave508** [comment]
Upon further investigation, seems BoASolidSurfaceFinderTracer is the culprit.

**Comment by Talon1024** [comment]
It looks to me like you're trying to run the latest git version of BoA on a stable build of GZDoom. Right now, you need a development build of GZDoom in order to run the latest git version. You can either grab a newer GZDoom build, or use the Chapter 3 release.

**Comment by Shockwave508** [comment]
Have no real way to do so, unless there's a dev version of the flatpak I'm not aware of.

**Comment by Talon1024** [comment]
I have no idea what you did or what you're doing, but the Flatpak version of BoA is **not** supposed to be the latest version from GitHub; it's supposed to be the version built from the 3.1 tag.

Anyway, I just removed the `ignoreAllActors` argument from the Trace calls, and that seems to have got BoA working on GZDoom 4.10.0 again.

**Comment by Talon1024** [comment]
[Here's the repository for the Flatpak version of Wolfenstein: Blade of Agony](https://github.com/flathub/com.realm667.Wolfenstein_Blade_of_Agony)
