### ISSUE TITLE
[C3M2] Tank repair kits disappear after quick load? 

### ISSUE THREAD

**Issue by r3538987** [Realm667/WolfenDoom#1328]
These were mine observations during gameplay.
![mspaint_2023-07-21_20-54-43](https://github.com/Realm667/WolfenDoom/assets/33725345/07f5aad9-dcb3-4162-b488-6c0dd3ee48f3)
Once created image got thought that maybe you have to scroll through items, and maybe then they will appear. Think I tried that but really not sure.

**Comment by Talon1024** [comment]
The repair kits are still in your inventory, but the inventory UI is invisible for some reason.
