### ISSUE TITLE
Various issues C1 dev build August/September 2023 done - but some still outstanding

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1329]
This hopefully is to do with a full download/build wolfendoom-master 27.7.23.
I'll mention the chapters seperately.

C1 ....

INTERMAP ...
- [x] 1.  Texture on line 3185 should be CABN_T04. Others could be changed in this area but this one is the one that can be seen.
- [x] 2. Tex on sidedef 8117 needs a negative scale.
- [x] 3. Tex on line 2264 could be moved closer to line 147.

M5 ...

- [x] 3. I could see the  joins in the skybox. Fixed with using sector effect 90.
- [x] 4. The top 4 globes at sector 3022 are too low. UPDATE - Seems that the 3D sector 1766 is affecting this. Just changing the Y offset for T's 2266, 2275, 2274 and 2270 from 40 to 39 fixes.
- [x] 5. Floor of sector 5208 needs an offset of 0, 0.
- [x] 6. Note that some of the lines using 3d linedef 9423 need an x offset fix.
- [x] 7. Sector 1545 should probably have the brightness level 136 to match adjoining sector 1533.
- [x] 8. Hanging utensils in kitchen ( near sector 4349 could use a  negative scale.
- [x] 9.  Where vertex 312 is, you don't see the whole window.
- [x] 10. Lines 19976, 19990, 3985, 19649, 19645, 19639, 19623 should have only been flagged "projectile shoot- through middle texture". Not "block every thing". ( But maybe the texture on line 19647 can be blocked from projectiles ? ) Oops. This has caused a warning message to the console on map start.
- [x] 11. A small 3d floor for sector 1113 for more realism.
- [x] 12. All WEB textures should have had a negative scale on one of the sidedefs.
- [x] 13. Bad polyobject door opening to sector 3218. Better, but the opened door outside still has an issue. Lines 14816 etc. need the scale changed to 1.45.
- [x] 14. For addition "realism", give lines 9401 and 9408 the flags "walkable middle texture" and "shoot-through middle texture".

M0 ...

UPDATE ... many here are stated as fixed but are not.

Many of the floors that use the tex crat_w03 ( with writing/eagle ) are the wrong way around. And check the floor of sector 4073 and sectors 4033/4034.
> I repaired all of these flats in the L2 storage area, however lots of crates like these remain here and in other maps. This should be done by a **script** that finds non-mirrorable textures (from a predefined list) applied to flats and auto-corrects them. --N00b

- [x] 15. On all those crates you just missed one - sector 4092. Fix is to remove the negative -2 scale offset and replace with 2, and Y offset 8. More on this - The crates outside are also affected. And the one at sector 1294. Removing negative scale, and then fix rotation and x/y offset fixes.
- [x] 16. Forgot to change the tex on lines 5107 and 5108 to METL_B10.
- [x] 17. Some of the crates where sector 5970 is, could  do with an X offset fix.
- [x] 18. Ceiling of sector 1004 should have been METL_F02, to match sector 1003.
- [x] 19. One of the sidedefs of lines 15882, 15884 and 14507 need a  negative scale.
- [x] 20. Sector 4653 needs a brightness level of 120.
- [x] 21. Sector 4751 needs a brightness level of 144.
- [x] 22. Floor of sector 1533 - crate - needs its negative offset cancelled and x/y offset fix.
- [x] 23. Ceilings of sectors 1477 and 1478 need the offset change Y92 , angle 90 degrees.
- [x] 24. Ceiling of sector 3731 erroneously has a negative offset -1. Set back to 1 to fix.

C1M2 point 15 - now a potential softlock ...

- [x] 16. If the player stays too long at sector 1806 and the gate closes, the player is trapped. Is there a way that the gate stays open ? If not, the action that was on line 17330 needs to be reinstated.

C1M2 point 11

- [x] 18. C1M2 - Sidedefs 5847 and 5857 need a negative scale.
- [x] 19. C1M2 - Where deco_kitchen1 and textures are, one of the sidedefs need a negative scale.

C1M3

- [x] 21. Lift at sectors 1314 and 1330 is still not right. Look up while travelling up and down.
- [x] 22.  I've been debating with myself as to whether to report this, but here goes ... The texture on lines 11149, 11147, 11496, 11152, 11159 and 11157 looks horrible to me imo.
- [x] 23. T1743 - radio sounds but no radio. ( another one, not the one reported before ) . Needs same as the one at sector 193.
- [x] 24. Some wierd Y offset with tex on line 2113 ( gzdoom issue ) UPDATE - The effect is caused by displacement textures enabled. Lower the floors of sectors 352 and 288 to -165 to fix.
- [x] 25. 3D control sector 636 needs a floor height of -240 and ceiling height of -176 and check sidedefs of lines attached. Some need an X offset fix. 

C1M1

- [x] 26. MIDG_B07 sidedef 10019 needs an offset of x -87. ( well, it looked good to me ) .

C1M4

 - [x] 27. Sector 2609 could have used a small 3d floor for more realism.
 - [x] 28. Globe at sector 1720 is OFF but still shows the red light. 

C1M6
- [x] 28. Should not linedef 69 have the flag "Projectile shoot-through middle texture" ?
- ❌  29. Probably should not experience the sandstorm at sector 771.
- [x] 30.  Web texture at lines 7155, 7202 could use a  negative scale on one of the sidedefs and offsets.

Resolved issues archive
---
<details><summary>Spoiler</summary>

M1 ...

- [x] T1336 and T1337 could be placed closer to the wall.

M2 ...

- [x] 1. Vent_M00 needs a mirror graphic at line 1203, and line 1193 when broken.
- [x] 2. Needs a line between vertices 11597 and 5648 and mid texture door_g02 placed.
- [x] 3. See screenshot. Nazis shoot closed door. Maybe the use of line flag "block monster line of sight" ? on lines 1743 and 5736.
> It was _5_743 --N00b, 07 Sep 2023

![shooting closed door](https://github.com/Realm667/WolfenDoom/assets/35204218/4c63a201-2dd9-4f11-8c1f-a6f29189bd6c)
- [x] 4. "block sound" lineflag seems not to work on lines 6385/6388. Maybe line 6388 impassible too ?
- [x] 5. Vent_M00 needs a mirror graphic at line 7709 when broken.
- [x] 6. Vent_M00 needs a mirror graphic at line 7729 when broken.

:x: 7. T1308 looked out of place as is facing wrong way. Cannot see fire. Can the model skin be reworked to show the fire grid both sides.

> It is just turned off, if you come closer and crouch you can see the bars --N00b, 07 Sep 2023

- [x] 8. T3266 and T486 need to be closer to the wall.
> Can't place them closer than 1mu --N00b, 07 Sep 2023
- [x] 9. CABN_T06 needed to be on line 883 and CABN_T06 on line 871. ( wrong way around ).
> You meant CABN_T06 and _T04 respectively. --N00b, 07 Sep 2023
- [x] 10. T3306 trolley too far into the wall.
- [x] 11. Really needed some visual blocking at line 17077 IMO. Maybe lowered bars ?
> I don't get the suggestion, maybe you meant some other linedef? --N00b, 07 Sep 2023
- [x] 12. Ceiling of sectors 1812, 1810 and 1808 Should be METL_B16.
- [x] 13. Sidedef 10995 needs an X offset of -27.
- [x] 14. Sidedef 10997 needs an X offset of --52.

:x: 15. The "gate" at polyobject sector 4479 cannot be opened from sector 1789 side. 3 dogs at sector 1806 are easy kills.

> It's sort of a trap for an unsuspecting player who is low on ammo and does not shoot the dogs beforehand, always has been like this IIRC. --N00b

M3 ...

- [x] 1. Odd rendering on line 1387.
- [x] 2. Vent_M00 needs a mirror graphic at line 2471, 2524 when broken.
- [x] 3. Poly door at sectors 1095/1096 partly opens into the flag at line 7155.
> Moved the anchors so that they won't clip into the walls. IDK what to do with the flag, however, beyond moving it 1mp to wall. --N00b

> Issue number 4 is missing... --N00b

- [x] 5. Still an issue when looking up while travelling the lift sectors 1330 and 1314.
Maybe making the texture METL_B08 brighter to match texture METL_B10 might help. Or make those sectors
true elevators, with moving ceiling, like the one in C1M5 sectors 653/4391.
> A 3D floor to mimic the above setup is also an option here.  --N00b

- [x] 6. With fog off, stand at sector and look out to sea. Similar has been  mentioned before.
> I would like to clarify: this is about the stock GZDoom fog, not BoA's. I've edited the area, however I also remember an issue about it (and having worked on it) so I can't say for sure that I fixed it now. --N00b, 07 Sep 2023

- [x] 7. T1742 is present - can hear it - but no actual radio unit.
> Same with T1743 (removed the latter). --N00b
- [x] 8. Sandbags at the start near the tank, eventually end up mid-air - see screenshots.
![sandbag start of level](https://github.com/Realm667/WolfenDoom/assets/35204218/637459d2-d7c0-4bb5-a918-81657fe0bf24)
![sandbags in air](https://github.com/Realm667/WolfenDoom/assets/35204218/1aa239b9-ed32-4838-9c8f-d3e78980e5b1)
> My bet is on the culling system. --N00b
- [x] 10. Offset 32, -33 would look much better for the tex on line 11168.

M4 ...

- [x] 1.  Railings - T1475, T1476, 1474, 1473 not attached to anything. All railings ?
A good positioned one is T1479.

> Old:
![image](https://github.com/Realm667/WolfenDoom/assets/59409713/ac8b6afe-8b65-4cbd-a201-cd6df6eb3274)

> New:
![image](https://github.com/Realm667/WolfenDoom/assets/59409713/7bbb97e3-a5e6-4ab1-9c27-7d0723478931)
> --N00b 08 Sep 2023

- [x] 2. Ceiling of sector 2629 looks wrong with brightness 128. Adjoining sector 2012 is 144.
- [x] 3. Tex on line 11076 is too far away from the wall.
- [x] 4. Can clip through the rear and the 4 barrels of T329 - flak gun.
- [x] 5. Tex on line 10348 too far away from the wall.

M5 ...

- [x] 1. Light bulbs at sector 3022 too far away from wall.
> Also fixed the swastika bulbs on the stage. --N00b
- [x] **[Not a bug]** 2. I didn't get to the defend the plaza stage and so quit. I just forgot the other part of the disk ...
- :x: 3. After picking up the 1st half of the solar disc, a secondary objective appears stating to find the 2nd half. IMO this should be an additional PRIMARY objective, since obtaining both halves is vital to completing the level.
> It's not yet known at that moment whether it might be useful, as is said by Douglas (he mentions selling it to Rojas). --N00b
- [x] 5. Floor of sectors 1218 and 5207 need an  offset of -96, -70.
- [x] 6. Suggest adding the light setting -16 for the ceiling of sector 2079 to match adjoining sector.
- [x] 7. A small 3d floor could have been used at sector 1258 for more realism.
> Also moved S1120 4mu east, and changed the colour of S1121 (there are two **black** tiles missing) for maximal nitpicking. "Who steals the tiles on every techbase?!" --N00b
- [x] 8.  Texture clash. see screenshot.
![texture clash](https://github.com/Realm667/WolfenDoom/assets/35204218/3546196b-ba28-47c9-b062-f128b7a01221)

M6 ...

- [x] Thing types 19072 vase, render into the wall at sector 818.

M0 ...

- [x] 1. Tex on lines 5522 and 5523, 5107 and 5108 would look better with offset x -9 y 0.
> Changed to METL_B10 --N00b
- [x] 2. Looked a bit out of place having the same ceiling flat for both sectors 5570 and 5585 imo.
> ...METL_B20 --N00b
- [x] 3. Ceiling of sector 1083 should probably have been METL_F02, to match sector 1082.

</details>

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3 Thank you very much for returning to BoA! Could you please elaborate on the plaza defense? Was it possible to exit the level normally (via Douglas), or you had to use cheats? Did you get the red key?

**Comment by hawkwind3** [comment]
You're welcome.
I remember achieving all objectives with the exception of defending the plaza. Worked for me before. I've nearly finished C3 and when that is done, I'll replay this level and report.

**Comment by hawkwind3** [comment]
Regarding the Paris mission. All good. I forgot to pick up both parts of the disk and the red key ...
Also regarding Douglas, If you click Douglas first, you miss the message from Juliette.

**Comment by hawkwind3** [comment]
- [x] 8. T3266 and T486 need to be closer to the wall.
> Can't place them closer than 1mu --N00b, 07 Sep 2023

Actually, you can. UDMF allows a small grid size. Set grid to 0.125 mp, go into visual mode, highlight the globe, right click, then change the Y position for both globes to 1200.1. I just did it and it works fine.

**Comment by hawkwind3** [comment]
Checked the latest C1M2. There was an issue with one of those globes. Maybe you have since fixed this ?

>❌ 15. The "gate" at polyobject sector 4479 cannot be opened from sector 1789 side. 3 dogs at sector 1806 are easy kills.
>
>    It's sort of a trap for an unsuspecting player who is low on ammo and does not shoot the dogs beforehand, always has been >like this IIRC. --N00b

Have a look at line 17330. This line is on the dog's side, but even the dogs cannot open sector 4479, since the action is for player only. So what is to open the poly sector 4479 ? If  meant for the player to open, the action should be on line 17331, not line 17330.

**Comment by Username-N00b-is-not-available** [comment]
Yeah, yesterday I put a wrong coordinate, today's commit will fix it. As for the dogs, I removed the action on the backside. The polyobject is to be activated only by line 6618.

**Comment by Username-N00b-is-not-available** [comment]
Just committed once more, the ones left are for someone else to fix. I'd like to say once more (in a separate comment) that repairing flat scaling (so the text is not mirrored) and offsets on crates might better be done by a script which would read the WAD TEXTMAPs (possibly just in binary).

**Comment by hawkwind3** [comment]
C1M2 point 15 - now a potential softlock ...

If the player stays too long at sector 1806 and the gate closes, the player is trapped. Is there a way that the gate stays open ?
If not, the action that was on line 17330 needs to be reintroduced.

**Comment by x3003** [comment]
>Also regarding Douglas, If you click Douglas first, you miss the message from Juliette.

If you already know what see says, you wanna skip it by going to douglas directly to end the level.
If you don't know, you're going to juliette first, as she is a (floor)tile further to the player, compared to douglas.

**Comment by hawkwind3** [comment]
> C1M2 point 15 - now a potential softlock ...
> 
>     * [ ]  1. If the player stays too long at sector 1806 and the gate closes, the player is trapped. Is there a way that the gate stays open ? If not, the action that was on line 17330 needs to be reinstated.
> 
> 
> C1M2 point 11
> 
>     * [ ]  2. I like what you did here. Just bear in mind that the player can still crouch under MIDG_C22.
> 
> 
> C1M3
> 
>     * [ ]  3. Lift at sectors 1314 and 1330 is still not right. Look up while travelling up and down.
> 
>     * [ ]  4.  I've been debating with myself as to whether to report this, but here goes ... The texture on lines 11149, 11147, 11496, 11152, 11159 and 11157 looks horrible to me imo.
> 
> 
> C1M1
> 
>     * [ ]  7. MIDG_B07 sidedef 10019 needs an offset of x -87. ( well, it looked good to me ) .
> 
> 
> C1M4
> 
>     * [ ]  8. Sector 2609 could have used a small 3d floor for more realism.
> 
> 
> C1M5
> 
>     * [ ]  9. The top 4 globes at sector 3022 are too low.
> 
>     * [ ]  10. Floor of sector 5208 needs an offset of -96, -70.

**Comment by hawkwind3** [comment]
I think Douglas could be placed further back, maybe at the reception desk. Up to the dev's though.
