### ISSUE TITLE
Invisible wall in C2M6 part1

### ISSUE THREAD

**Issue by Rxbsxn** [Realm667/WolfenDoom#133]
Everything is recorded on this video: https://www.youtube.com/watch?v=FKMqlELzH1c&feature=youtu.be
I give you also save with download: https://drive.google.com/drive/folders/0Bxx50iwHGjAPWTlHZ2ZpSWV5N00?usp=sharing

If it is fixed in actually game version please give me know

**Comment by Ozymandias81** [comment]
Yes, [this has been fixed](https://github.com/Realm667/WolfenDoom/commit/f770664d8be541e505d1a857aabbc53716334a3c) by me several commits ago. It was a very strange issue.
