### ISSUE TITLE
ice not slippery

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1335]
In c2m6_a this ice isn't slippery.

![Screenshot_Doom_20230729_111200](https://github.com/Realm667/WolfenDoom/assets/77861029/964f7fac-2463-4fc8-a6df-9af2b1c47370)

**Comment by hawkwind3** [comment]
Although different from the ice right near the start of the level, which is slippery and reflective, I agree with you. It should be slippery and just like the "ice pond" at the start, even more so, as is adjacent cold water and the layer is very thin, just like ice.

**Comment by Tormentor667** [comment]
Fixed
