### ISSUE TITLE
Tree blocking shot

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1338]
In c3m1_a, this tree is blocking the shot.

![Screenshot_Doom_20230730_120547](https://github.com/Realm667/WolfenDoom/assets/77861029/3d77462a-3d0e-49a5-ac2d-a4bbf44dcd2f)

**Comment by Username-N00b-is-not-available** [comment]
The tree variants are AFAIK chosen randomly, not sure how many hundreds of places on maps we can find where bullets can be blocked by thin air...
@Talon1024, what do you think, will anything major break on the maps if I make the bullets not collide with 3D model trees at all?

**Comment by Talon1024** [comment]
One level that immediately comes to mind is C2M3. The snipers at Giftmacher's house are very dangerous because they can hit you from a kilometer away. Allowing their bullets to pass through trees would make them even more dangerous, and you would be unable to see where the bullets are coming from.

**Comment by x3003** [comment]
This one is blocking the shot too. These trees seems to have a lot of 'empty space' around them. Maybe shave away some of it ?!

![Screenshot_Doom_20230902_130357](https://github.com/Realm667/WolfenDoom/assets/77861029/5d69e2f1-06c8-473f-9d71-8bea9987767f)

**Comment by x3003** [comment]
Maybe remove this tree. It block a lot of the shots. The distance between the 2 crosshairs is about the width of block.

![Screenshot_Doom_20240412_160712](https://github.com/Realm667/WolfenDoom/assets/77861029/99d522f8-c505-47b4-8170-4832b26c6e96)

![Screenshot_Doom_20240412_160721](https://github.com/Realm667/WolfenDoom/assets/77861029/abc5bd5b-ad8a-4d5b-8c34-46e1b3008ca5)

**Comment by hawkwind3** [comment]
Fixed issues in screenshots.
