### ISSUE TITLE
bullet trajectory changed on skill 4

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1343]
Strangely, the bullet trajectory on skill 4 is changed. You have to aim a lot higher to hit the enemy.
Tested w/ c2m5_a. Setting the game to skill 3 or lower works as expected.

You have to aim here to hit the enemy:

![Screenshot_Doom_20230820_123101](https://github.com/Realm667/WolfenDoom/assets/77861029/6431a3e5-dca1-4fdd-a01f-1100f1c43676)

**Comment by x3003** [comment]
Here, i'm trying to shoot just below the flag. Result is a hole that is way below, at the bottom of the stone.

![Screenshot_Doom_20231126_231220](https://github.com/Realm667/WolfenDoom/assets/77861029/2ab3cd4d-083b-4590-95bb-f420dff008c3)

And i'm only standing here, so the distance isn't that great.

![Screenshot_Doom_20231126_231226](https://github.com/Realm667/WolfenDoom/assets/77861029/37761b44-4094-4eab-9767-e803fcedd8a5)

**Comment by Tormentor667** [comment]
I think the bullet tractory addition is unfair as long as enemies take it into account but the player needs to learn it - especially with the sniper. What is the sniper worth, if the crosshair is not targeting correctly?

So I'd suggest removing that functionality at least from the player's sniper.

**Comment by x3003** [comment]
What i'm saying is that the trajectory on skill 0-3 is fine. Somehow it got changed with skill 4. That's (for me) the odd thing about it.

**Comment by Talon1024** [comment]
I added a Printf to `tracers.zs`, and apparently the Kar98k projectile's speed is 180 on skills 0-3, but for some reason it drops to 85 on skill 4.

I don't know all the details, but the `FastSpeed` for the bullet tracer base class is 85, so that may have something to do with that.
