### ISSUE TITLE
can't shoot through gate.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1344]
In c2m3, you can't shoot through this gate to hit the enemy.

![Screenshot_Doom_20230819_132607](https://github.com/Realm667/WolfenDoom/assets/77861029/61b1b3ed-85af-4aad-8fbd-10f13f452924)

**Comment by hawkwind3** [comment]
Confirmed. Good catch. Easy fix. Lines 17704 and 17711 need the flag " projectile shoot through middle texture".
