### ISSUE TITLE
enemy see and shoot through branches

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1346]
In c1m0, the enemy can see and shoot through the treebranches.
This is w/ a recent built. Works as expected w/ an older one (few months old).

On this spot they see and shoot you:

![Screenshot_Doom_20230820_102438](https://github.com/Realm667/WolfenDoom/assets/77861029/187fa29d-3fe2-41cf-b8d9-a7f2116b9842)

**Comment by hawkwind3** [comment]
Hmmm. I just checked the same area and had no problem with the latest build.

**Comment by hawkwind3** [comment]
Yes. I can now confirm this. If you didn't know already, you are being sniped by T4140 at sector 5699 ( or 5702 ) The issue I have, even with the fog off,  the sniper can see you, but you cannot see the sniper from sector 469 as the sniper rifle  round crosshair does not appear in the hud.

**Comment by hawkwind3** [comment]
Try this. Seems to be ok for me. I flagged lines 2781, 2782, 2783, 2784, 2785 and 2786 "block monster line of sight".
[C1M0.zip](https://github.com/Realm667/WolfenDoom/files/12459633/C1M0.zip)

**Comment by x3003** [comment]
>I flagged lines 

That seems to work for me.

**Comment by x3003** [comment]
They can still see and shoot you through the trees

![Screenshot_Doom_20230902_092256](https://github.com/Realm667/WolfenDoom/assets/77861029/cf5a06fd-94a5-4727-a225-2af1e55c5656)

![Screenshot_Doom_20230902_092319](https://github.com/Realm667/WolfenDoom/assets/77861029/1b2f07cc-5bcb-4983-9562-463c4c5d370c)

**Comment by hawkwind3** [comment]
I just checked again with my fix and your coordinates and still had no problem.. And the bullet puff in your screenshot is a radius issue, as you cannot shoot pass. Enemy cannot harm you either.
________________________________

**Comment by x3003** [comment]
>Your latest pic is not shown here for some reason. 

That was a mistake I deleted, as it works as expected.
