### ISSUE TITLE
Serious tree model issue latest BoA build for v3.2 - SOLVED ( sort of ).

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1347]
Running BoA 3.1 official does not have this issue, even if I update BoA 3.1 with the very latest gzdoom dev build 4.11 pre 279, but I have to change the gzdoom ini to gzdoom_portable.ini  .
A good example is in these pics. Load map C3M1_b, turn around 180 degrees and walk forward.

![tree models1](https://github.com/Realm667/WolfenDoom/assets/35204218/42d283e8-f088-4f54-b12d-14cb63856162)
![tree models2](https://github.com/Realm667/WolfenDoom/assets/35204218/dee5f459-85e6-4f8d-acb6-0b8bab70e84a)

**Comment by x3003** [comment]
Under 'rendering settings', the 'trees' setting might be too low.

**Comment by hawkwind3** [comment]
Nope. That's what I suspected too. I have all environment settings to beautiful and distance of 16384. As mentioned BoA v3.1 has no issue with this, just the latest dev build. Now if you have no problem, I'm at a loss.

**Comment by x3003** [comment]
I checked and I don't have a problem @ 16384, only when the setting is low.

**Comment by hawkwind3** [comment]
Problem must be mine then ... :( .

**Comment by hawkwind3** [comment]
SOLVED ...

Somehow a new setting in gzdoom_portable.ini was added ...
boa_culling=true
When I changed this to false, or removed the entry entirely, all was well.
Question remains ... how did this entry get included.

**Comment by Tormentor667** [comment]
From where does this come?

**Comment by hawkwind3** [comment]
I don't understand the question. I think all the info is provided here. Or can you be more specific.

**Comment by hawkwind3** [comment]
Bear in mind that this was just an example. It was happening with all maps. So if the fix was just for this map/tree, will not have any effect any where else. Anyway, as stated, this was solved. I just left this here if anyone has the same issue.

**Comment by Talon1024** [comment]
The fix was just for that map in that particular area, so that the corpses won't appear to hang from thin air.

I guess the actual issue here is that trees are invisible at the start of the maps?

**Comment by hawkwind3** [comment]
Just downloaded the latest map and I see what you have done. Interestingly, if the trees rendering is set to the lowest setting - 1024 -, at the very start of the level and just turning 180 degrees, the tree is not there but the hanging corpes are.

**Comment by hawkwind3** [comment]
I think that's because the trees are rendered and the corpses aren't

No. The corpses are always rendered.

**Comment by hawkwind3** [comment]
I suspect this has a lot to do with it ...

https://zdoom.org/wiki/Configuration_file

Windows users to check could try this experiment ( without the recent fix ), and backing up your .ini file ...

1. Install the latest BoA dev build.
2. Install the latest gzdoom dev build - https://devbuilds.drdteam.org/gzdoom/gzdoom-x64-g4.11pre-279-g22271d146.7z
3. Import the launcher from BoA 3.1.
4. Launch game as usual and go to map c3m1_b via console.
5.  Turn 180 degrees and what do you see ? And rendering settings have no effect. ( for me at least, unless I do the workaround).

**Comment by hawkwind3** [comment]
@Talon1024  ... You could do the same for the same tree in the previous level, C3M1_a ( T1693 at sector 1739 ).
And to answer your earlier question, yes, if more than 1024 ( I think ) map units away from the player.

**Comment by Tormentor667** [comment]
Okay, it seems as we have the same problem here as I had a few days ago with this one here: https://github.com/Realm667/WolfenDoom/issues/1372

I will close this, please continue the discussion in the new issue.
