### ISSUE TITLE
Paper is empty

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1349]
In c2m6_c this piece of paper doesn't contain any text anymore.

![Screenshot_Doom_20230903_101708](https://github.com/Realm667/WolfenDoom/assets/77861029/4c5c28f7-5231-4cc6-a1ff-055714cca420)

![empty](https://github.com/Realm667/WolfenDoom/assets/77861029/673621ae-de55-4330-a195-11a858c3d302)

**Comment by Username-N00b-is-not-available** [comment]
Any addons? Is this the current commit?
![image](https://github.com/Realm667/WolfenDoom/assets/59409713/9b100c08-6bda-4b71-9e9b-6cb889ee81cd)

**Comment by x3003** [comment]
No addons, latest git version, latest gzdoom version 347.

**Comment by x3003** [comment]
Oops, it's a fault in gzdoom. I checked a bunch of releases and the error starts w/ this built: https://github.com/ZDoom/gzdoom/actions/runs/5953953081
So pre 332 is still good and pre 335 is bad.

**Comment by Username-N00b-is-not-available** [comment]
I wonder what would be a minimal working example for this...

**Comment by x3003** [comment]
Yep, fixed. Thanks for the detailed reporting on gzdoom git, noob.
