### ISSUE TITLE
Dormant dogs act as if they were never dormant

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#135]
Title says it all. Dogs that are set as dormant will move around and attack the player as if they were never dormant, except the player won't be able to harm them.

Dormant dogs are used to choreograph stuff in C1M2 and C2M4, and possibly other missions.

**Comment by AFADoomer** [comment]
Should be fixed now...  Please confirm.

**Comment by Talon1024** [comment]
Yep, fixed. Thanks!
