### ISSUE TITLE
bj won't die, but he should

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1350]
My nitpick of the week. If you jump/fall from this place in c1m0, you are badly damaged, but you won't die. Maybe make the injury a bit higher ?!

![Screenshot_Doom_20230910_233102](https://github.com/Realm667/WolfenDoom/assets/77861029/02cfcc8c-89b8-44e2-8900-38da650c22f4)

![Screenshot_Doom_20230910_233113](https://github.com/Realm667/WolfenDoom/assets/77861029/ca946ec8-25fd-4b7b-a214-735ca6adc41e)

**Comment by hawkwind3** [comment]
Good catch !  :) . All those sectors where that lift is that have the floor height of -4240 should have the sector effect 115 - Instant Death.
