### ISSUE TITLE
Launcher Language files missing?

### ISSUE THREAD

**Issue by Blueberryy** [Realm667/WolfenDoom#1351]
there's no language folder for launcher files on this repo. please upload latest ones

**Comment by Tormentor667** [comment]
I think it's the wrong place to put them here because this is the pk3 folder, not the root of the release. I attached the language pack here though

[language.zip](https://github.com/Realm667/WolfenDoom/files/12642941/language.zip)

**Comment by Blueberryy** [comment]
should i upload one of these files with improved russian translation on Github repo? i wanna help with that

**Comment by Tormentor667** [comment]
Just post it here and I will incorporate it

**Comment by Tormentor667** [comment]
> should i upload one of these files with improved russian translation on Github repo? i wanna help with that

@Blueberryy do you want to share your language translation? Otherwise I'd close this.

**Comment by Blueberryy** [comment]
> > should i upload one of these files with improved russian translation on Github repo? i wanna help with that
> 
> @Blueberryy do you want to share your language translation? Otherwise I'd close this.

Yeah sorry, you can close this as i don't have much time right now uploading it.
