### ISSUE TITLE
Texture localization for BoA

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#1352]
It turns out that in GZDoom textures can also be localized: https://forum.zdoom.org/viewtopic.php?t=75523
I wonder if we should use this feature in BoA. What do you think @Tormentor667 @Ozymandias81 @Talon1024? My plan is to translate only the textures in English (such as the HQ signs), since other languages (not only German, but also French, and maybe some other ones I don't remember) are supposed to be foreign to the player.

Maybe I can do this for other languages too, not only Russian, since most phrases already have translations in the CSV. I plan to use (and modify) the letters from existing textures, IIRC by 2021 the fonts that were used for the signs had already been lost.

Looks like I deleted my previous work on this...

**Comment by Tormentor667** [comment]
That's cool, I wasn't aware of that. Regarding your proposal I am fine. Only translating english signs into foreign languages is fine to me. So the first step would be to check which one need to be translated.

**Comment by Username-N00b-is-not-available** [comment]
Going through the folders made me remember damn well myself doing the translations some 3 years ago... Here is my list (hopefully complete):

<details><summary>/graphics</summary>

- [ ] finale_epilogue
- [ ] finale_label_l
- [ ] M_EPIS
- [ ] M_SAVE
- [ ] M_SKILL
- [ ] M_START
- [ ] NOTAVAIL **(unused AFAIK)**
- [ ] paused **(unused AFAIK)**
- [ ] youdied **(unused AFAIK)**
- [ ] BOAHELP1 through BOAHELPC
- [ ] board_hd
</details>

<details><summary>/textures</summary>

- [ ] DECO_LOF
- [ ] DECO_MIA
- [ ] DEMO_END **(unused AFAIK)**
- [ ] DOOR_BRF
- [ ] MIRR_W05
- [ ] SIGN_DR1 through SIGN_DR4
- [ ] SIGN_G10 through SIGN_G12
- [ ] SIGN_G81 through SIGN_G89, SIGN_G93, SIGN_G98 **(G85 is AFAIK unused)**
- [ ] SIGN_INV
- [ ] SIGN_LAB
- [ ] SIGN_ROO
- [ ] Briefing textures
- [ ] GORE_W15, GORE_W16, GORE_Z15, GORE_Z16
</details>

Content in English that I will not translate:
- historical newspapers;
- movie posters;
- English names on cell signs (these are written by and for German guards);
- easter eggs;
- DDB_CRDT, DDB_LTTR **(the latter is unused AFAIK)**.

For the briefing textures, I would like to somehow obtain the messy font used for the operation names, such as in `textures/briefing/C1M1_1.png` (I ain't drawing letters of this size from scratch) — even though the operation names are in German, they were subject for translation in the CSV. @Tormentor667 Do you still have it by chance?

I wonder if I should do
- [ ] SEQ_001 through SEQ_004

(but I have to try anyway). Per-pixel editing would not be easy on SEQ_004 gradient, and that's not counting the font.

Writing to myself: also need to change the font on SIGN_Z91 to make it more consistent with other SIGN_Z** textures.

**Comment by Username-N00b-is-not-available** [comment]
This feature has been commented out from GZDoom in 2022 as stated by AFADoomer in that ZDF thread, reasons not yet known to me.
Though I've managed to reinvent this wheel via the well-known Crutch-Bug™ technology until the original feature gets restored in GZDoom (if ever). Soon to commit with a small batch of Russian textures.

The shortcomings: 
- the first player will dictate the translation to everyone during coop (as the job is done via the playsim function `ReplaceTextures`);
- we'll have to ensure that translated textures only occur with short names on the maps (I'll do this);
- the beginnings of the names of translated textures have to be replaced by the language name instead of using the GZDoom format `TEXNAME.lang.png`: 1) such textures would be confused with already existing ones, were they in `textures/`, 2) apparently they can't be moved to other folders than `textures/` without disappearing off `ReplaceTextures` radars, and 3) GZDoom seems to hold the good old tradition of 8-letter texnames in these functions;
- failure for dynamically set textures such as the briefing ones, including the door (though I plan to add another crutch — an ACS API to update translations of all textures, or just a specific one);
- entries that are shown in menus will also have to be processed one by one (with a method like `StringTable.Localize`);
- I'll turn grey if we have animated textures that need translating.

**Comment by Ozymandias81** [comment]
While idk if I will ever do italian localizations, this is a neat feature. Really GZDoom has improved a lot throughout the years

**Comment by Username-N00b-is-not-available** [comment]
It might have caused problems in Raze and was commented out during testing, never (yet) to be uncommented.

**Comment by Tormentor667** [comment]
This is sad to hear...
