### ISSUE TITLE
Opening safe instructions

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1353]
Screenshot taken from BoA 3.1. The instructions below do not show up in the latest git build 3.2. Intentional ?
![3 1 safe](https://github.com/Realm667/WolfenDoom/assets/35204218/e1ea0691-2a93-42cc-bd07-4e4346431683)

**Comment by Talon1024** [comment]
The instructions not showing up is not intentional.

The instructions show up in 1080p if HUD scaling is set to 1.

**Comment by hawkwind3** [comment]
Yes, it does work wit HUD scaling set to 1. Still a bug though, as no problem with 3.1, whatever scale setting.

**Comment by hawkwind3** [comment]
Applied the latest breakstring.zs, and found the issue still present. @x3003  can you confirm/

**Comment by Talon1024** [comment]
The issue is with interface.zs, not breakstring.zs

**Comment by hawkwind3** [comment]
Sorry about that. Fix confirmed.  :)
