### ISSUE TITLE
Ambient sounds sometimes not play

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1354]
When I play normally, start from HQ and enter the Astrostein mission E2M0_A , all the ambient sounds are gone ( well, at least the wave sound at the beach, insects, and the waterfall atm. But when I go to this level via the console - map e2m0_a , the sounds are there. Even saving, quitting, and loading the saved game doesn't help. May apply to other maps ?

**Comment by Talon1024** [comment]
I don't know why you're having this issue. Does it happen with other games, like Heretic?

**Comment by hawkwind3** [comment]
I don't know why either. And no, I don't think it happens with other games. Might be a gzdoom issue ? I forgot to mention, that this happened with official gzdoom 4.10.

**Comment by Tormentor667** [comment]
I just testet C2M0_A and couldn't reproduce the issue with GZDoom 4.11.3 - which version did you use @hawkwind3 ?

**Comment by hawkwind3** [comment]
I closed this. But it may reappear ... hopefully not.
