### ISSUE TITLE
Astrostein ending doesn't return to base (w/ multiple addons; shows Doom II cast sequence)

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1355]
When completing astrostein I didn't return to the base and got some weird screens instead.

![z0](https://github.com/Realm667/WolfenDoom/assets/77861029/801cdd1e-614f-471e-8c14-d36ed1e056ce)

After going through the exit above, you get these messages:

![z5_1](https://github.com/Realm667/WolfenDoom/assets/77861029/2f6d5da6-d9bf-4e2d-8109-76c296340a32)

Then you get these on screen. The game now just won't go to the base and exits.

![z1](https://github.com/Realm667/WolfenDoom/assets/77861029/3576b645-be0f-4e81-9a4e-9d5a5a2ffdff)

![z2](https://github.com/Realm667/WolfenDoom/assets/77861029/509b3d14-03be-405a-9ed8-1daab8ef35d1)

![z4](https://github.com/Realm667/WolfenDoom/assets/77861029/e5516821-4d08-4228-b561-90c7ab900aa4)

I've played all the levels before this one, so I should return to base.
Played the git version (used the launcher, boa.ipk3, GZDoom g4.12pre-3-g40ec46e6e), with add ons, score, zik, behaviour, more weapons and confiscated weapons.

[save18.zip](https://github.com/Realm667/WolfenDoom/files/12797679/save18.zip)

**Comment by hawkwind3** [comment]
Very strange indeed. I have just very recently played that level with the very latest git build, but not with a recent gzdoom dev. build. There is even a more recent dev build. Try that.

**Comment by x3003** [comment]
Up until now (incl. playing C1), I didn't have had any probs w/ these add ons.

**Comment by Talon1024** [comment]
I just tested beating C2M0_B with GZDoom 4.11.0, with no add-ons, and I was not able to reproduce this bug. However, I did noclip to the end of the level.

**Comment by x3003** [comment]
I included the savefile so anyone can try it w/ the official launcher and latest versions of boa/addons/gzdoom.

**Comment by hawkwind3** [comment]
Just now tried to load BoA with all the addons mentioned, and GZDoom crashed for me.
Also, with GZDoom 4.11 gzdoom exits when trying to run score and vampire addons.
Regarding the unofficial addons, for me,  personal addon works, which is Zik addon ? But confiscated addon does not work. GZDoom exits.

**Comment by x3003** [comment]
The score addon doesn't work on gzdoom 4.11 < pre 4xx.
I use these addons, zik is included here: https://github.com/Realm667/boa-addons/tree/main/source

**Comment by hawkwind3** [comment]
Bug confirmed, with or without your saved game, using gzdoom 4.11 and the latest builds of boa and the addons.

**Comment by Tormentor667** [comment]
Added your mapinfo.txt to the addons repo.
