### ISSUE TITLE
Suggestion - Use of the sector flag "not shown on textured automap"

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1356]
_Tormentor667's additional post_
Okay, I started adding the flags, the following maps are relevant

- [x] C1M0
- [x] C1M1
- [x] C1M2
- [x] C1M3
- [x] C1M4
- [x] C1M5
- [x] C1M6
- [x] C2M0_A
- [x] C2M0_B
- [x] C2M1
- [x] C2M2
- [x] C2M3
- [x] C2M4
- [x] C2M5_A
- [x] C2M5_B
- [x] C2M6_A
- [x] C2M6_B
- [x] C2M6_C
- [x] C3M0_A
- [x] C3M0_B
- [x] C3M1_A
- [x] C3M1_B
- [x] C3M2
- [x] C3M3_A
- [x] C3M3_B
- [x] C3M4
- [x] C3M5_A
- [x] C3M5_B
- [x] C3M5_C
- [x] C3M6_A
- [x] C3M6_B
- [x] SM01
- [x] SM02
- [x] SM03

_hawkwind3's original post_
I could be wrong, but I did not notice any map using the sector flag  "not shown on textured automap".
This, in conjuction with better use of the line flag "not shown on map" would greatly unclutter the automap AND hiding those secret and control sectors.

**Comment by Tormentor667** [comment]
What's actually the difference?

**Comment by hawkwind3** [comment]
GZDoom default key is p, which disables/enables the textured floor in the automap. A good use of the flag "not shown on textured automap" is the not showing of the skybox control sector. Options>Customize Map Controls>Toggle texture. But if the flag is used in map creation, the floor texture will not show even if toggle texture is on or off.

**Comment by Tormentor667** [comment]
Understood, this could come in handy ineed. Just did this on C2M3... the thing is, it takes ages :) I am not sure if all that work really is worth the effort in the end when it only comes to this aesthetics.

**Comment by hawkwind3** [comment]
Closed. All done.
