### ISSUE TITLE
November 2023 playthrough (4th skill)

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#1358]
I ran through the whole game on level 4 skill.
From what I can remember:

- [x] C3M4 - vehicle collision box not set - can "go through it"
<details>

<summary>Figure 1</summary>

![02](https://github.com/Realm667/WolfenDoom/assets/73436978/2c591fd7-0330-46ea-8397-8dd8e02acdd8)

![03](https://github.com/Realm667/WolfenDoom/assets/73436978/89dc82bb-7546-42a0-9b81-8ee26b93d86e)

</details>

- [x] C3M0_b - you can be soft-locked in yellow key area, if you do not accept a yellow key from Stierlitz, get the purple key and in here enter yellow zone via secret parth
<details>

<summary>Figure 2</summary>

![01](https://github.com/Realm667/WolfenDoom/assets/73436978/147e8e6d-cb42-4c32-8e57-9e93a015358b)

</details>
(I am not saying it is what one should be doing, OR will do; it is just possible and it not be should... ah, talking like Yoda again. :))

**Comment by Username-N00b-is-not-available** [comment]
Nice to meet you @MuadDib90!

**Comment by MuadDib90** [comment]
Hi @Username-N00b-is-not-available long time no see, how are you?
I saw you made some playthrough yourself...

**Comment by Username-N00b-is-not-available** [comment]
Quite a long time indeed. Real life idiosyncrasies don't leave much time for Dooming, and then there are also unfinished projects (my own and with other people)... I hope sometime in the future we'll make it to a BoA re-release.

**Comment by hawkwind3** [comment]
As a suggestion, a simple fix for this would be to make the door at sectors 807/809 a non-key door, then the player can then open door at sector 749/751 to continue.

**Comment by MuadDib90** [comment]
> Quite a long time indeed. Real life idiosyncrasies don't leave much time for Dooming, and then there are also unfinished projects (my own and with other people)... I hope sometime in the future we'll make it to a BoA re-release.

I understand.


> As a suggestion, a simple fix for this would be to make the door at sectors 807/809 a non-key door, then the player can then open door at sector 749/751 to continue.

As I am not familiar with "sectors" (and I can imagine I could find them if I open map in SLADE), I appology if this is the same solution:
<details>
  <summary>Fig.1</summary>

![01](https://github.com/Realm667/WolfenDoom/assets/73436978/38bdaa0e-4981-4765-bcd7-fbfe57fa8402)

</details>

**Comment by hawkwind3** [comment]
Yes. That's the door I mean.   👍
