### ISSUE TITLE
horizontally compressed Dog sprites

### ISSUE THREAD

**Issue by Corak667** [Realm667/WolfenDoom#136]
Just downloaded latest git version, runned on latest QZDoom, started Episode 2 and found dogs sprite graphics are horizontally too short, as i think, maybe it needs to be 2x wider (or it's some QZDoom incompatiblity?):
http://picsee.net/upload/2017-09-22/56596d2a3b8c.png

**Comment by Ozymandias81** [comment]
Please test on GZDoom before filling the Issue zone. I'll try later.

**Comment by Ozymandias81** [comment]
As I suspected, it's an issue within QZDoom: doberman is correctly scaled in game (and no properties have been changed inside the map though - C2M1). Please next time grab screenshot with console command **_idmypos true_**, so we can retrieve coords instantly.

https://imgur.com/a/HDvqZ
