### ISSUE TITLE
Out of breath going to another section

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1360]
If you're in this room in c2m2 and are out of breath, when the next section comes up, you're stripped of your weapons and still out of breath....

![Screenshot_Doom_20231126_174220](https://github.com/Realm667/WolfenDoom/assets/77861029/1dc0b549-6213-4d74-9db3-799316ccfb71)

![Screenshot_Doom_20231126_174243](https://github.com/Realm667/WolfenDoom/assets/77861029/ea299e9d-1428-47f9-895c-4d7631be24c0)

**Comment by MuadDib90** [comment]
The part of loosing your gear is on purpose (you have been tricked); as far as stamina, I think it is just saving the last state of a variable and then loading it.

**Comment by x3003** [comment]
>I just don't understand. :-)

It's the 'out of breath' situation. When going from one section to another, his weapons are taken by the enemy, right ?! Well in the meanwhile he **should** regain his breath (while being unconscious). Just like going from the end of the mission and going to the base. In this case he can't and isn't out of breath.

**Comment by MuadDib90** [comment]
Now I have finally understood you meant the description of situation he's in. 👍
