### ISSUE TITLE
No communication until meeting

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1362]
In c3m0_b, if you don't run into stierlitz (and doesn't give you the yellow key), he still can give you advice on what to do. How would he know that you're around when you didn't meet ?!

![Screenshot_Doom_20231126_121430](https://github.com/Realm667/WolfenDoom/assets/77861029/67c3ed1e-5d60-4bfe-a95f-b1450b1add83)

**Comment by Talon1024** [comment]
I'm thinking of putting yellow locks on the first few doors in the bunker. That way, you won't leave the first room in the bunker without talking to Stierlitz and getting the yellow key.
