### ISSUE TITLE
Secret #1 in C1M4 seems like an inescapable death trap

### ISSUE THREAD

**Issue by AA1999** [Realm667/WolfenDoom#1363]
Hi
So the first underwater secret in C1M4 (BOA 3.1) has you navigate through an underwater tunnel to reach it
However, by the time you reach the secret, your oxygen bar will be very close to 0 or 0

I tried spamming health items to heal myself when going back up but that didn't help either
For context:
![image](https://github.com/Realm667/WolfenDoom/assets/14325650/abb1e351-a936-4dbf-877c-e229107f603f)

I wasn't sure if it was a bug or just something I missed. Ty!

BOA version: 3.1
Addons score.pk3 efficiency.pk3 more_weapons.pk3 KCE.pk3 
GZDoom version: g4.12pre-164-gc95d611c1f-m - 2023-12-11 07:34:56 +0100 - SDL version

**Comment by Tormentor667** [comment]
Maybe placing a scuba gear nearby as a secret-helper might be of good use.

**Comment by x3003** [comment]
>Maybe placing a scuba gear nearby

Ehh ??? There is already scuba gear you can find in c1m4. And maybe the player even has some oxygen left from the one on c1m2...

**Comment by AA1999** [comment]
Weird enough, I didn't found any of the two scuba gears until Oxymandias mentioned it in C1M4 on the table

**Comment by Tormentor667** [comment]
> > Maybe placing a scuba gear nearby
> 
> Ehh ??? There is already scuba gear you can find in c1m4. And maybe the player even has some oxygen left from the one on c1m2...

Good point indeed, therefore closed :)
