### ISSUE TITLE
Kicking to open doors

### ISSUE THREAD

**Issue by superuser-does** [Realm667/WolfenDoom#1365]
This is a suggestion request, to make it possible for the standard kick action to open doors. 
When kicked, the door should sharply swing open, so the animation on kicking it should be much faster than opening it normally.

This feature would enhance the action hero fantasy presented by the game.
It speaks also to the past of the series: in Return to Castle Wolfenstein and Wolfenstein 2009, it's possible to open a door by kicking. Those games have limited stealth systems, and this way of opening doors will also alert enemies in the area.

_If implemented_, I think we should extend opening doors with Melee to the shovel too. In Wolfenstein 2009, the melee action varies depending on the weapon but works just as well for any weapon.
It only wouldn't look right with the BoA combat knife, unless there was a different animation (e.g. hitting the door backhanded, with the hilt).

**Comment by Tormentor667** [comment]
Even though it's a nice suggestion, I am not sure how easy it would be to implement it, considering hundreds of doors, controlled by simply action triggers that swing them.

@Talon1024 @AFADoomer is there anything in terms of ZScript making something like this possible?

**Comment by Tormentor667** [comment]
These feels pretty "action" now :) I like that addition. I wonder if we should somewhere add a note on a door, like "kick me open", so the player knows that this exists.

**Comment by superuser-does** [comment]
That's great, thanks! I had one more thought; would this be an issue for doors locked using a key? It could break the illusion a bit if you could kick a locked door open, only because you have the key in your possession.

**Comment by x3003** [comment]
This works pretty well, but not (yet ?) for all doors.

It works w/ these

![Screenshot_Doom_20240413_115110](https://github.com/Realm667/WolfenDoom/assets/77861029/55a3c86a-3901-4f37-b54c-db3da26f7d0a)

But not w/ these

![Screenshot_Doom_20240413_113436](https://github.com/Realm667/WolfenDoom/assets/77861029/8ed1e2a6-0088-4332-bca1-040c8df08858)
![Screenshot_Doom_20240413_114713](https://github.com/Realm667/WolfenDoom/assets/77861029/72321672-24d8-4e26-83d3-76badd8a32cb)
![Screenshot_Doom_20240413_114720](https://github.com/Realm667/WolfenDoom/assets/77861029/9eb34dda-b6ed-4cdf-b4f1-3be2afc782e0)
![Screenshot_Doom_20240413_114829](https://github.com/Realm667/WolfenDoom/assets/77861029/7f59f09b-bfb3-415a-aabd-1c27e26bc79c)

**Comment by AFADoomer** [comment]
Those are all walkable 3D midtex doors (for some reason - only the glass ones need to be), so the default tracer misses them.  I'll see what I can do.

**Comment by AFADoomer** [comment]
I think that this is resolved in 2b921da18e4d5e3db764cdc1b5127f4d17f333cd.

**Comment by x3003** [comment]
Dunno if it's fixed already, but some of the doors you can (strangely) only kick open from 1 side.
Like these:

![Screenshot_Doom_20240414_112950](https://github.com/Realm667/WolfenDoom/assets/77861029/7e1a3b77-a7eb-45eb-b108-0e5017bbeb2c)

![Screenshot_Doom_20240414_110929](https://github.com/Realm667/WolfenDoom/assets/77861029/bd185fd2-5627-4272-af3a-0658804073d2)

![Screenshot_Doom_20240414_110152](https://github.com/Realm667/WolfenDoom/assets/77861029/e96f909e-bb0d-40e3-9249-0f02cc543feb)

![Screenshot_Doom_20240414_110148](https://github.com/Realm667/WolfenDoom/assets/77861029/7ae51995-a7b5-453d-bc9b-367286d7b472)

And if you beat H. you'll get something odd:

![Screenshot_Doom_20240414_123654](https://github.com/Realm667/WolfenDoom/assets/77861029/f6134174-4d11-4001-a38d-61c6bb99df08)

**Comment by AFADoomer** [comment]
Ah.  Didn't account for ignoring translucent lines.  

Should be fixed in 0e6e246d83bc47221c3c2de7746bd7fe5990cf7a, and I added some handling in ACS to get rid of (really just move them all to 0, 0, so they aren't in the player area anymore) the polyobject doors that get covered up by impassible lines in c56890e9d4e48d03e6187f4f3c04a06d020d4bef.

**Comment by AFADoomer** [comment]
Should be fixed in 8df2d30edcd29f0d49a02874b944b30ebdb63298.  They weren't moving all of the way to the destination point, so I increased the speed so the move happens in one tick.

**Comment by x3003** [comment]
This is an odd one.
If you have a key to the innerlock, you don't need the other key when kicking this door because it's open all the time.

![Screenshot_Doom_20240429_230521](https://github.com/Realm667/WolfenDoom/assets/77861029/4a30674f-20f4-4ace-9221-1f8e8a9ac246)

**Comment by AFADoomer** [comment]
Yeah, that definitely breaks intended gameplay by making a one-way door no longer one-way...  @Tormentor667, how do you want to handle this?  Easter egg shortcut for players who happen to kick that door open?

The only reason kicked doors stay open is that if I let them close, they will close at the same speed that they opened (the action of opening the poly door essentially creates a thinker that remembers the attributes of the door, opens it at the specified speed, waits the right amount of time, then closes it at that same speed - and there's no way to change that speed short of duplicating the door handling logic myself).  There *is* a script library that would let me do that...  But is it worth it?

**Comment by Tormentor667** [comment]
Considering that the kicked-open door doesn’t break the gameplay we can leave it as is. I wonder who will even notice that ;)
