### ISSUE TITLE
Burning barrel too big

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1368]
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/fc40be55-6653-418e-bf08-158e1ce6fa31)
It should be about 60% of it's current size.

**Comment by Tormentor667** [comment]
Same goes to the sniper
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/00c39339-f2ad-41f1-a689-88ae75b829d0)

**Comment by Tormentor667** [comment]
And to this pot... what is wrong with the scaling on some objects? One parent object broken?
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/69d18dc0-b67b-4634-877f-d32b2a864b41)

**Comment by hawkwind3** [comment]
Could you please provide map and coordinates ?

**Comment by Tormentor667** [comment]
C2M3

**Comment by hawkwind3** [comment]
OK. Compared with the latest gdoom dev build/BOA dev build and public release 3.1. I cannot see any difference. Also all those sprites are scaled x1y1 so render unmodified.

**Comment by Tormentor667** [comment]
Okay, the bug is indeed already in v3.1 which doesn't make it any better. In v3.0 it looks like this and that's the right scaling:
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/a88f1176-4724-45b6-835b-135e3f946834)

Interestingly the pot and the sniper look the same in v3.0.
