### ISSUE TITLE
Missing water ambient sound

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1369]
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/8141b52a-8b4b-4d62-b4bb-6aac9b227b0e)

**Comment by hawkwind3** [comment]
Yes. I mentioned this some time ago. Seems to be intermittent. Sometimes the water sound is there, sometimes not.

**Comment by Tormentor667** [comment]
Fixed the issue, also changed the strength of the river sound.
