### ISSUE TITLE
C2M2: lift stuck. Lift rising only once after killing 8 drones, but not again

### ISSUE THREAD

**Issue by Corak667** [Realm667/WolfenDoom#137]
Found problem where you cannot return to the top floors again, if you press this button on the lift you will down to the floor with Drones, when you kill them all - the lift will rise once, and you can call it down by pressing on it's wall, but if you press this button again and go down - you cannot call it again - and simply you will stuck (because you need to kill drones, that already destroyed):
This lift:
http://picsee.net/upload/2017-09-22/0a273406003a.png
http://picsee.net/upload/2017-09-22/f9e62bdae396.png
http://picsee.net/upload/2017-09-22/e0e59f853f39.png

**Comment by Ozymandias81** [comment]
Even this has been [fixed](https://github.com/Realm667/WolfenDoom/commit/3d3e3a01fff8286c2237ce5141f58cdc031adf2f), Thank you very much Corak667.
