### ISSUE TITLE
Missing text mark icon (not sure if bug)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1371]
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/ed56457d-7b1f-41ed-b814-3265a8384e0e)

**Comment by hawkwind3** [comment]
Coordinates and map number ?

**Comment by Tormentor667** [comment]
Ah… C2M3 in the castle near the fire place.

**Comment by hawkwind3** [comment]
You are right.  It has been removed in the current dev build. Is present in 3.1 ( Thing 5586 Type 12383 ) .

**Comment by Tormentor667** [comment]
Do you have an idea when and from whom this has been removed?

**Comment by Tormentor667** [comment]
Okay it is indeed there in v3.1 - and it was not intended to be removed.
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/ca7c73a2-67e5-41fa-b84e-7645051ddfb3)

I have a suspition and I hope @AFADoomer can take a look at it. Afaik, he changed the programming of the notes to spawn the marks instead of placing them manually for v3.2. Maybe this isn't working in all occations,

**Comment by Tormentor667** [comment]
Another example of v3.1 in C1M!
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/2d5ce1e6-ceb1-45d3-9343-a7c4a82e8b5c)

and v3.2 in C1M1
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/6fac3ed7-ce76-44c8-a982-5bde1b1d1c48)

The markers are generally missing and I am sure it's because of @AFADoomer's improvement that doesn't seem to be working anymore.

**Comment by AFADoomer** [comment]
They only show up on lower two skill levels.

**Comment by hawkwind3** [comment]
Confirmed.

**Comment by Tormentor667** [comment]
I totally missed that fact. How hard would it be to change this to the first 3 skill settings? I think most players play the middle skill and I think they should not miss this feature.

**Comment by Tormentor667** [comment]
Thank you!
