### ISSUE TITLE
[C2M0_A] No music change dropping down into the pyramid

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1373]
I remember that the music changed when dropping down the pyramid in C2M0_A - this doesn't happen anymore in current dev builds. Error? 

![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/d7e7da15-41b4-4b8e-8850-e3c491298a0e)

**Comment by hawkwind3** [comment]
I just did a comparison and the music does not change for me. Compared with the public 3.1 and gzdoom 4.6 with current.

**Comment by Tormentor667** [comment]
Possibly. I remember that I made the music change as soon as you enter the tomb.

**Comment by Tormentor667** [comment]
Yes, checked even 2.0 and there was never a music change. Looks like I have totally saved some memories the wrong way. I just wonder if it would make actually sense to place a fitting music here for the tomb areas. Something more atmospheric. I will take care...
