### ISSUE TITLE
Headshot achievement 

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1375]
Now headshots are 'a thing', maybe make an achievement for it ?

**Comment by Tormentor667** [comment]
Is this implemented yet?

**Comment by AFADoomer** [comment]
I'm pretty sure these are just randomized alternate deaths, not an actual thing the player can directly cause to happen.

**Comment by x3003** [comment]
You can with the sniper rifle.

**Comment by AFADoomer** [comment]
Perhaps by coincidence?  

The only time the various Death.Headshot states are entered is from the code that plays a random death animation (normal, fall forward, or headshot).

There also is already an achievement - Clear Shot - for sniping an enemy from over 6000 map units away.

**Comment by Tormentor667** [comment]
Then I'd say we leave it as is, there is no need to further complicate the mechanics to make them even more buggy.
