### ISSUE TITLE
Coop sharekeys issue ?

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1376]
With latest gzdoom dev build and latest boa build, this shows up in the console at runtime ...

Log started: 2024-04-07 11:40:26
GZDoom version g4.12pre-480-g7a43d7f78
W_Init: Init WADfiles.
adding D:/gzdoom latest/gzdoom.pk3, 679 lumps
adding D:/gzdoom latest/game_support.pk3, 3307 lumps
adding ./boa.ipk3, 29897 lumps
adding D:/gzdoom latest/game_widescreen_gfx.pk3, 214 lumps
**Script error, "boa.ipk3:defcvars.txt" line 23:
Cannot set cvar default for non-config cvar 'sv_coopsharekeys'**

Update ... Seems to only show in the latest gzdoom dev build. Gzdoom stable 4.11.3a does not show this.

Update 2 ...My first update was wrong. It does indeed show up in gzdoom 4.11.3a as Tormentor667 pointed out. The wording is slightly different though ...

**Comment by x3003** [comment]
No problem here.
The only thing is that sv_coopsharekeys is always set to false, eventhough it's set to true in defcvar.
Even when you set this to true in the progam itself, when restarting, it's set to false again.

**Comment by hawkwind3** [comment]
... so you are not getting the red error message in the console with the latest gzdoom build ? Correct me if I'm wrong, but you don't use MS Windows ?

**Comment by x3003** [comment]
No, error here. I use Win10 x64

**Comment by hawkwind3** [comment]
Win 11 here. What gzdoom dev build are you using ?

**Comment by hawkwind3** [comment]
Attached screenshot using the latest boa dev build ( downloaded and compiled today ) and latest gzdoom dev build.
![coopsharekeys](https://github.com/Realm667/WolfenDoom/assets/35204218/8352d55d-c7e6-4d60-a13d-09d7b36e7660)

**Comment by x3003** [comment]
For testing, always the latest available. Might go back to test when something is broken...

**Comment by Tormentor667** [comment]
Just for the record, using the official latest build, same issue hiere
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/7aa22a00-f371-4939-b6fd-03ddf773bbde)

**Comment by AFADoomer** [comment]
This CVar (and others) are really just flags applied to the dmflags3 CVar.   You get the same error message if you try to set the default value for a compatibility flag CVar or most of the other sv_* CVars (like sv_weapondrop, sv_noautomap, etc)...  I don't know that this can be fixed mod-side.

**Comment by AFADoomer** [comment]
There's no way to set this mod-side, so I added handling to handle key sharing for BoA keys automatically, just like we already share compass items and interactive items.

**Comment by Tormentor667** [comment]
Awesome, thanks for the fix!
