### ISSUE TITLE
C2M4 - Enemy shooting at the very start of the level (on hard difficulity).

### ISSUE THREAD

**Issue by Corak667** [Realm667/WolfenDoom#138]
C2M4 (Tunis). Though Sgt. Ascher says "We're already cleaned the area..." - At the very start of the level there is some german soldier that shoots at hero and hurts him, so you need to hide quickly. NPC seems like dont see anything. it's just before mad desert ride. Two seconds and we're dead.
http://picsee.net/upload/2017-09-22/1e413ae1ff3e.png
http://f5.s.qip.ru/cMfvXkb5.png
That's on hardest difficulty - because enemy can shoot you from any long distance. Looks very illogical)

**Comment by Ozymandias81** [comment]
This has been fixed right [now](bd02af44cf16d3ae6dd1bd15cd99e3d42095fffc), thanks @Corak667 for noticing that.
