### ISSUE TITLE
latest c1m5 console warning

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1383]
Console message on start of c1m5 latest ...
![c1m5](https://github.com/Realm667/WolfenDoom/assets/35204218/870d92d2-3c74-41e6-94c8-dfa5a48eb084)

Blame me for this one. I requested the line flag "shoot-through middle texture" which has caused this error.

**Comment by x3003** [comment]
You only get this when doing 'map..', not when coming from the intermap.

**Comment by Tormentor667** [comment]
Should be fixed
