### ISSUE TITLE
C1 map fixes relating to issue #1329

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1384]
Too much of a hassle to set up pull requests. So I will post the fixed maps here.  C1 #1329

[C1M0.zip](https://github.com/Realm667/WolfenDoom/files/15033479/C1M0.zip)
Many stated as fixed in #1329 but were not. Done in attached.

[C1M2.zip](https://github.com/Realm667/WolfenDoom/files/15047761/C1M2.zip)
Points 18 and 19 fixed. Plus fix for #1386

[C1M3.zip](https://github.com/Realm667/WolfenDoom/files/15033685/C1M3.zip)
Points 22 to 25 fixed.

[C1M5.zip](https://github.com/Realm667/WolfenDoom/files/15033507/C1M5.zip)
Points 4, 5, 8, 9 and 12 fixed.

[C1M6.zip](https://github.com/Realm667/WolfenDoom/files/15033696/C1M6.zip)
Point 30 addressed.

[INTERMAP.zip](https://github.com/Realm667/WolfenDoom/files/15033712/INTERMAP.zip)
Points 1 and 2 fixed.

Some maps have had additional " mot shown on textured automap" and "not shown on map" flags added.

**Comment by Tormentor667** [comment]
Thanks kindly, just integrated your fixes and will add you now to the dev team which will make fixes from your side easier :)
