### ISSUE TITLE
Some doors shifted downwards

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1385]
With the latest git version, in c1m2 (and others ???), some of the doors seems shifted downwards.

This one is still fine

![Screenshot_Doom_20240419_172102](https://github.com/Realm667/WolfenDoom/assets/77861029/61df8c4b-5b5d-401f-b6c5-69f55fea6cde)

But these not

![Screenshot_Doom_20240419_170337](https://github.com/Realm667/WolfenDoom/assets/77861029/e056b06d-3ba4-48ee-bdf2-bb184aabf684)
![Screenshot_Doom_20240419_170340](https://github.com/Realm667/WolfenDoom/assets/77861029/b54555a8-6e7c-4973-987b-db88ca384a91)
![Screenshot_Doom_20240419_171033](https://github.com/Realm667/WolfenDoom/assets/77861029/285fedd6-4732-4d96-9a30-79ed7fd14ccf)
![Screenshot_Doom_20240419_171531](https://github.com/Realm667/WolfenDoom/assets/77861029/56c4dd59-f867-4a29-9a3f-111ddce7a478)
![Screenshot_Doom_20240419_171744](https://github.com/Realm667/WolfenDoom/assets/77861029/6b4b8d6b-265e-4063-b56f-2e09e8afa82c)
![Screenshot_Doom_20240419_171748](https://github.com/Realm667/WolfenDoom/assets/77861029/bcb18b10-a812-4f9b-905b-e3a5134e6294)

![Screenshot_Doom_20240419_174253](https://github.com/Realm667/WolfenDoom/assets/77861029/3c266a1f-5d8e-403d-9a62-119d57836238)
![Screenshot_Doom_20240419_174604](https://github.com/Realm667/WolfenDoom/assets/77861029/7db444ce-020c-4593-9419-65c28d31c5e2)
![Screenshot_Doom_20240419_174607](https://github.com/Realm667/WolfenDoom/assets/77861029/3f0dc709-00ed-4956-b38a-2fe937274bdb)
![Screenshot_Doom_20240419_174741](https://github.com/Realm667/WolfenDoom/assets/77861029/30665742-b8c6-4937-aec2-b153f4e20613)

And it looks these are shifted upwards

![Screenshot_Doom_20240419_223418](https://github.com/Realm667/WolfenDoom/assets/77861029/314163fb-e816-4e63-a395-225c8636af1d)
![Screenshot_Doom_20240419_223503](https://github.com/Realm667/WolfenDoom/assets/77861029/ad7f7cca-5917-432a-981f-cc5d3007b3de)

**Comment by Tormentor667** [comment]
Strange… was this fine before my commit?

**Comment by x3003** [comment]
When was your commit ?

**Comment by hawkwind3** [comment]
I might have fixed in the attached ...
[C1M2.zip](https://github.com/Realm667/WolfenDoom/files/15047919/C1M2.zip)
This includes the floor fix too. If you get to test before I do and find all is well, I'll update to #1384

**Comment by x3003** [comment]
It's also on c1m5 (and other maps ?)

![Screenshot_Doom_20240420_113628](https://github.com/Realm667/WolfenDoom/assets/77861029/ad67f56b-9ebd-4ed4-84ac-e1ff8a237b84)
![Screenshot_Doom_20240420_113639](https://github.com/Realm667/WolfenDoom/assets/77861029/9ea8f228-63f4-40d8-9604-84a02575f3a6)
![Screenshot_Doom_20240420_113643](https://github.com/Realm667/WolfenDoom/assets/77861029/aae034de-f434-4211-9fa3-cbb205d363c7)
![Screenshot_Doom_20240420_113656](https://github.com/Realm667/WolfenDoom/assets/77861029/b26934dc-97ad-4784-9b2c-751b19af4fb7)
![Screenshot_Doom_20240420_113707](https://github.com/Realm667/WolfenDoom/assets/77861029/4063d681-273a-46dc-805d-e17075a30709)

**Comment by hawkwind3** [comment]
Looks like all the control sector ceiling heights got stuffed up recently. This no doubt will affect all my recent upload  c1 fixes. Work to do and then test ALL C1 maps ...

**Comment by Tormentor667** [comment]
Strange. The only thing that has been done there afaik was changing the flag of the sector for he flat-rendering on the automap. Added your file, will reupload current state. Maybe you need to double-check if I uploaded the right version.

**Comment by x3003** [comment]
The door issue seems fixed.
