### ISSUE TITLE
Floor not level

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1386]
With the latest git version, in c1m2, this piece of floor isn't level anymore:

![Screenshot_Doom_20240419_165822](https://github.com/Realm667/WolfenDoom/assets/77861029/37a7bcbb-2498-486d-a9ac-4916b2715e01)

But this piece is fine:

![Screenshot_Doom_20240419_170201](https://github.com/Realm667/WolfenDoom/assets/77861029/4a9c6c7b-bfaf-451a-8b9e-063bf9e9c442)

**Comment by hawkwind3** [comment]
I've found the cause to this one. Control sectors 230 and 232 now have the wrong ceiling/floor heights, causing the sidedef texture on those control sectors to be rendered. Compare those sectors to 3.1 public. Sector 230 should have a floor/ceiling height of 184 and even sector 232 should have had a floor/ceiling height of 347. I will update C1m2.zip issue #1384 soon

**Comment by x3003** [comment]
Looks like it got broken on a commit @ 17/04/24, which also broke the doors. See https://github.com/Realm667/WolfenDoom/issues/1385

**Comment by hawkwind3** [comment]
https://github.com/Realm667/WolfenDoom/files/15047761/C1M2.zip

Fixed. I had to revert the 3d control sectors to the ones in 3.1

**Comment by Tormentor667** [comment]
Thank you!
