### ISSUE TITLE
objects disappear

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1387]
With the latest git version and gzdoom 4.11 (else you can't play this map), in c2m1, some objects are not there anymore.

![Screenshot_Doom_20240421_073148](https://github.com/Realm667/WolfenDoom/assets/77861029/94185811-72d8-4b9e-8a72-08e931c1c6c2)

![Screenshot_Doom_20240421_073332](https://github.com/Realm667/WolfenDoom/assets/77861029/072794ae-63de-4b53-b983-91936f74ce3d)
![Screenshot_Doom_20240421_080502](https://github.com/Realm667/WolfenDoom/assets/77861029/834e4fea-d393-4a63-815c-127a60fd09d8)

And some invisible objects block your path

![Screenshot_Doom_20240421_080334](https://github.com/Realm667/WolfenDoom/assets/77861029/7bf80dec-fa2c-4cce-8003-f94e42264443)
![Screenshot_Doom_20240421_080959](https://github.com/Realm667/WolfenDoom/assets/77861029/c5b88eb0-5003-46f8-bb18-fef50a0b8f2b)

**Comment by Tormentor667** [comment]
Strange... looks like 3d objects are not rendered for you. I tried on my machine with g4.11.3 (latest official release) and it worked
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/adbcdc45-e100-4b07-bfd3-20244d195cf7)

**Comment by x3003** [comment]
Still no 3d objects, with vulkan or opengl.
The built from 2 days ago still worked for me, the one from today isn't.

![Screenshot_Doom_20240421_120347](https://github.com/Realm667/WolfenDoom/assets/77861029/085617f0-b56a-4133-b6ab-58aaf2fc213c)

![Screenshot_Doom_20240421_121130](https://github.com/Realm667/WolfenDoom/assets/77861029/dbe3f066-717a-498d-975c-67de355a2ac7)

**Comment by Tormentor667** [comment]
Can you try a completely fresh install of GZDoom?

**Comment by AFADoomer** [comment]
Did you skip the opening cutscene or allow it to play through?  I was able to reproduce this when letting the cutscene play, but not when skipping it immediately.

Also, yikes, playing on current GZDoom dev builds totally breaks the stealth guards.

**Comment by x3003** [comment]
I normally either skip it or use 'map..' With both ways i get the same result.

>Also, yikes, playing on current GZDoom dev builds totally breaks the stealth guards.

That was already reported here ?

https://github.com/Realm667/WolfenDoom/issues/1370

**Comment by AFADoomer** [comment]
It was, but for all enemies - I didn't realize the stealth Nazis were completely broken.

**Comment by x3003** [comment]
The 3d objects are here again. Thx for fixing.
