### ISSUE TITLE
Framerate issues on mission C1M2 Exodus of the Flatpak

### ISSUE THREAD

**Issue by incrediblyimpressiveusername** [Realm667/WolfenDoom#1388]
Up until the mission C1M2 Exodus, the game runs perfectly fine on higher than maximum preset settings. But during that mission, the frame rate drops well below 1 fps even on lower than potato preset settings. (Although I should add that the settings don't seem to have much of any impact on performance or resource usage, neither when the game is running well, nor when it is barely running at all. Resource usage is consistently low, e.g. never more than 500MB of RAM in use.)

The extremely low frame rate happens exclusively outdoors and in the prison building with the kitchen and mess hall. And even there, the clouds and water, etc. all run perfectly smoothly at 144 fps as long as the menu is pulled up, but then it drops back to <1 fps when the menu is closed.

I'm fully aware of the caveat "this project pushes the engine to its absolute limits. If these tips don't solve your issues, you will unfortunately need to play the game on a better hardware setup. [...] If your performance still doesn't improve, even after exiting any programs running in the background, then your machine just isn't up to the task.".
But significantly less than 1 fps on potato settings with 16GB RAM and 8GB VRAM?! This can't be working as intended.

PS. This may be addressed by @hawkwind3's [recent fixes](https://github.com/Realm667/WolfenDoom/issues/1384), which haven't rolled out to the [flatpak](https://flathub.org/apps/com.realm667.Wolfenstein_Blade_of_Agony) yet.

**Comment by Tormentor667** [comment]
Which version did you play? With which GZDoom version?

**Comment by incrediblyimpressiveusername** [comment]
That would be BoA v3.1 with GZDoom v4.10.0

**Comment by Tormentor667** [comment]
Well, we shipped BoA v3.1 with GZDoom v4.6, so we can't give support on v4.10. Your only chance is to wait for BoA v3.2 and GZDoom v4.12.
