### ISSUE TITLE
C2M4 - Insane rush on truck with - Absolutely Impossible and imbalanced part of the game on hard levels.

### ISSUE THREAD

**Issue by Corak667** [Realm667/WolfenDoom#139]
Mission 4 (Tunis): Insane rush on truck with - Absolutely Impossible and imbalanced part of the game on hard levels.
I completed most levels on hardest level of difficulty without a trouble using a causious tactic, hiding, stealthly targeting from behind, taking better positions... But RUSHING without cover into 5-10 enemy units is insanity - thats where Tunis Truck Run leads without any choice, there is nearly 100 enemy and 5-10 in a row, and you cannot hide or evade damages, i used all my medikits, even there is infinite rocket launcher (but it's too slow) - I targeted very fast and precisely, from long distance... finally i gave up and passed this one on a God mode cheat. I think this place absolutely impossible to complete on hard levels, even on normal - it's very doubtful to survive, especially when there is 15 rifle soldiers targeting to you, and you have just 2-3 shots to cover them all. I think it's biggest imbalance in a game.
Better to give player option to make such run on a foot (maybe some underground passage if there is linear road in a big territory) - he will have much more chances to survive than on a truck without a cover.
I think also you targeted this truck run only for easy difficulty, because to survive there - enemy must see you only from short distances and most their shot must miss... On hard - they see you in kilometres and shoot maximally precisely, but you cannot evade.
Is any betatester tryed this on hard and maximum difficulty?

**Comment by Corak667** [comment]
Try to set a "smartiest" (fastest targeting) AI bot to complete this level and look if he can)

**Comment by Ozymandias81** [comment]
I'll keep this open, consider this addressed. Thanks.

**Comment by Ozymandias81** [comment]
I [took care of it](https://github.com/Realm667/WolfenDoom/commit/35b8408c39930e6e28860d14b9053fb15d54ca44), let's see if its better now.

**Comment by Corak667** [comment]
A bit less damage, but still unpassable, because enemys see you in kilometres and there is TOO MUCH of them, even if they deal you 1hp per shot - this will be extremely hard..
Example how i tried:
https://youtu.be/8f7yPLbs9GY

**Comment by Tormentor667** [comment]
Just took a look at your gameplay video: You simply suck at playing, that's the problem :)

**Comment by Corak667** [comment]
@Tormentor667 ok, I admit - I suck at playing. if you think so. Could you do it better on hardest level? Show how it could be done. Targeting to still not visible enemy in myst? Ok, i can easly predict where they are... Surviving 15 shots from unknown place? Ok... LOL)

**Comment by Ozymandias81** [comment]
I consider this closed, since I have managed to finish the truck sequence nicely way, and also now that Torm took care of aggressiveness for skills 4-5 we are definitely on the track imo.
If you "suck" with aiming, I suggest to activate crosshairs @Corak667 , or autoaiming (but this way some playism could be broken since BoA is not meant to be played with autoaim)
Thanks for your feedbacks, we'll wait more from you (and remember: play BoA on GZDoom only!) :muscle:

**Comment by Corak667** [comment]
@Ozymandias81 I use point crosshair, it's just very small, but i see it clearly, so it's not a problem. I aim very fast, but to acomplish this one - only autoaiming could really help, because need to re-aim on truck movement and also see enemy that are invisible behind mist, as i typed before.
You completed truck sequence on hardest difficulty?

**Comment by Ozymandias81** [comment]
You still playing the game with QZDoom, as images speaks for themselves.
Try recent changes on GZDoom and let's see how it is now.
