### ISSUE TITLE
[C2M5_A/B] Freeze when finishing C2M5_A

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1391]
After finishing C2M5_A and entering C2M5_B I get an engine freeze - the music of C2M5_B is already playing but GZDoom is dead. Was using v4.12
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/cf0da5f2-187f-4083-a941-80c86008c284)

Update: Noticed that warping to C2M5_B directly freezes GZDoom, so it has nothing to do with the end of C2M5_A.

**Comment by AFADoomer** [comment]
This is something to do with the updated RainSpawners - I haven't dug into the code, but I narrowed down the culprit actor by commenting out chunks of the DoomEdNums in MAPINFO until I was able to get the map to load.

@Talon1024 - Any ideas?

**Comment by AFADoomer** [comment]
I narrowed it down to the rain spawner actors in the wind tunnel puzzle room.  But I'm not sure how to fix it properly, short of adding a new actor for the simulated wind particle effect.

This whole map needs rain spawners cleaned up - there are multiple at different heights in the same x/y coordinates in every location they are used.

**Comment by hawkwind3** [comment]
Is this still an issue for others ? I "warp" to c3m5_a via the console and have no issue. Using the latest boa dev build and the latest gzdoom build as of this writing,  gzdoom 4.13 pre 72.

**Comment by Tormentor667** [comment]
Did you fully play _A and proceed to _B?

**Comment by hawkwind3** [comment]
Just did that now. No problem. Could not reproduce. Using GZDoom 4.13 pre 79 with Vulkan renderer.

**Comment by Tormentor667** [comment]
Okay, I need to retry then
