### ISSUE TITLE
[C3M5_B] Skybox is broken

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1394]
This is how it should look like:
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/0acd2554-e079-40f0-bbf8-7adc4a1d09f5)
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/d753cb37-530b-468a-8f45-da4bd980fd18)
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/475fadf1-c492-4ae5-a7e6-c1f34833896a)

This is what it looks:
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/14c72991-84e1-499b-a835-3422a16579bf)
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/15ae749a-f224-4b03-b4bb-1edafec35a38)
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/d8ce58e8-7abe-4137-8385-329e7ce8c2cb)

I think it's the same issue as this one https://github.com/Realm667/WolfenDoom/issues/1392 - as there are skyboxes in skyboxes (nested)

**Comment by AFADoomer** [comment]
These should be working again.

**Comment by Tormentor667** [comment]
Thank you, gonna try it later this evening.
