### ISSUE TITLE
Can't run boa anymore with gzdoom 4.11

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1397]
There are still some issues with gzdoom 4.12+ and because of that you might wanna go back to 4.11.
But, you can't run boa anymore w/ 4.11, but it does work w/ 4.13 pre 19
This issue is there from the built from 24/04+, as the one from 22/04 still works as expected.

Script error, "boa_c3.pk3:scripts/decorate/items/keys.zs" line 36:
Call to unknown function 'ShareItemWithPlayers'

**Comment by Tormentor667** [comment]
We will have to switch to 4.13 anyway so switch to a pre release

**Comment by x3003** [comment]
Could be, but there are still some issues to resolve w/ gzdoom before doing a pre release anyway.

Like:
https://github.com/Realm667/WolfenDoom/issues/1370
and:
https://github.com/Realm667/WolfenDoom/issues/1377

For me (but who am I ?!) these are blockers. You can't (pre)release w/ a partially broken gzdoom.

Until then, why not disable this piece of code until the engine works a bit better...

if (Inventory.TryPickup(toucher))
{
	if (multiplayer && !deathmatch) { ShareItemWithPlayers(toucher); }
	return true;
}

So why not enable this code later on, until all other reports got fixed ?!
