### ISSUE TITLE
Map C2M0_B serious softlock issue 

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1398]
SHOWSTOPPER - If the player takes the "sewer", sector 2980, before using a crate to block the lasers at sector 2992, player cannot finish the level. Suggest either a switch at sector 3078 to disable the lasers or a crate at sector 3078. OR make lift sector a 2 way lift with a ladder at sector 2980. If someone addresses this please use the latest map.

**Comment by Talon1024** [comment]
There is a way to disable the lasers after entering the building. You have to take the back door into the reactor room and disable the exposed reactor by shooting at it.

Perhaps we need a new crosshair to tell the player "Shoot this!".

**Comment by hawkwind3** [comment]
Thanks for this. I don't know how many times I've walked past that blue column with the exclamation mark. I just didn't look in that direction. Bug closed as not a bug.
