### ISSUE TITLE
exclamation mark hidden

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1399]
This exclamation mark is hidden part behind the board, part behind the wall

![Screenshot_Doom_20240427_110321](https://github.com/Realm667/WolfenDoom/assets/77861029/d08f8b29-1540-4ff3-bc3f-c6e594b23f17)

**Comment by hawkwind3** [comment]
This unfortunately due to code changes. Boa 3.1 has a seperate sprite - Type 12384 - but 3.2 beta now does not use these. Dev coders might explain this better.

**Comment by AFADoomer** [comment]
This should be good after b630f328d0da1c7487665a668e9f39e109fb3706.

**Comment by x3003** [comment]
It's now a question mark instead of an exclamation mark, but visible.
