### ISSUE TITLE
[?QZDoom issue?] When someone dies from flamethrower flame - he leaves flaming static sprite

### ISSUE THREAD

**Issue by Corak667** [Realm667/WolfenDoom#140]
When someone dies from flamethrower flame - he leaves flaming static sprite (not animated, only flame instead of burned coal body)
http://f5.s.qip.ru/cMfvXkb6.png
http://f3.s.qip.ru/cMfvXkbg.png
QZDoom issue maybe

**Comment by Ozymandias81** [comment]
Yes this belongs to QZDoom and not GZDoom, Closed. :+1: 

https://imgur.com/a/0uO8W
