### ISSUE TITLE
sluggish inside building

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1402]
With the git version, in c2m1, in this building playing getting very sluggish. Moving, turning, everything seems slower.
In the prison and later outside, there was no such problem.

![Screenshot_Doom_20240427_111622](https://github.com/Realm667/WolfenDoom/assets/77861029/0e0f066f-56de-4ab8-acdc-244eec8f6ce2)

![Screenshot_Doom_20240427_112430](https://github.com/Realm667/WolfenDoom/assets/77861029/daa1665b-cb2c-46dd-8746-385a76a29627)

**Comment by x3003** [comment]
Adding this one aswell. This place slows everything to a crawl, 1-2 fps, really unplayable. Before going into  this location, everything worked as expected. Went back to gzdoom 4.11 (from 4.13). Same problem.

![Screenshot_Doom_20240503_171326](https://github.com/Realm667/WolfenDoom/assets/77861029/e523c56c-7d8c-4789-8ade-dc99288f3086)

![Screenshot_Doom_20240503_171926](https://github.com/Realm667/WolfenDoom/assets/77861029/e056f342-5262-4487-ba27-72118afb5eee)

**Comment by AFADoomer** [comment]
Does this slowdown still happen after 3be068950fd7820a12e0897472730151069001fe?

I also fixed the other two tiers of lasers that are broken in your second Astrostein screenshot.

**Comment by x3003** [comment]
Now I get a steady 35 fps again instead of 1. So it looks fixed.
Dunno if it also fixes the slowness on c2m1.

**Comment by x3003** [comment]
Somehow something in the config was changed. cl_capfps was set to true, capping everything to 35 fps making things slower, I didn't touch the config file for ages, so it's a mystery.....
