### ISSUE TITLE
gate partially vanished when kicking open

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1403]
Most of this gate vanishes when kicking it open.

![Screenshot_Doom_20240427_112133](https://github.com/Realm667/WolfenDoom/assets/77861029/7a16bb12-3f69-469e-8a37-132ae1592afb)

**Comment by AFADoomer** [comment]
Does it do the same thing when opened normally?

**Comment by AFADoomer** [comment]
Should be good after bc7301664c19052cf073c0388cc0649fa11e5659.  Looks like there is a loss of precision in the engine's polybject rotation code at non-standard rotation speeds...

**Comment by x3003** [comment]
Seems fixed.
