### ISSUE TITLE
water looks a bit odd

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1404]
Here the water is seperated and flows in 2 different directions, so that looks odd.

![Screenshot_Doom_20240427_230544](https://github.com/Realm667/WolfenDoom/assets/77861029/b9ab15c4-2015-42d8-b5ad-9c36fc47201e)

**Comment by hawkwind3** [comment]
Not a bug. The map is designed that way. Same happens in boa 3.1. A good eye though. I never noticed this until you mentioned.

**Comment by x3003** [comment]
Maybe it's not a bug. but it looks kinda weird.
