### ISSUE TITLE
Air and staminar bars gone

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1405]
For me, Im not getting the stamina and air bars. And when I presh shift, I can constantly run. Latest gzdoom and boa git.

**Comment by x3003** [comment]
I don't have such problem. I use the latest git version (slightly modified, keys.zs) and gzdoom-x64-g4.12pre-362-g1c7f19535, which doesn't have the nervous guards. Wanna you wanna try that version.

**Comment by hawkwind3** [comment]
I notice that you did not get that issue from your recent screenshots, which led me to say "where have mine gone?" They show up for me in boa 3.1. Gzdoom-x64-g4.12pre-362-g1c7f19535 no longer exists on DRD dev builds. Could you post it here ? You say you have a slightly modified keys.zs. Could you post that too please.

**Comment by x3003** [comment]
>You say you have a slightly modified keys.zs. Could you post that too please.

Oh, I took it from the 22/04 git build, as the one from the latest git version doesn't work on 4.11/4.12 (for testing) and with my slightly modified version (in another post), the key pickup doesn't work anylonger 
And gzdoom 4.13 xx has the nervous guards & tank morph doesn't work anymore.
So for testing boa I try to get the best of both worlds..... ¯\_(ツ)_/¯

[gzdoom-x64-g4.12pre-362-g1c7f19535.zip](https://github.com/Realm667/WolfenDoom/files/15143514/gzdoom-x64-g4.12pre-362-g1c7f19535.zip)

**Comment by AFADoomer** [comment]
Make sure that your 'boa_hudmeterfade' and 'boa_sprintswitch' cvars are not set ('Display Options'>'HUD Options'>'Hud Meter translucency when full' and 'Cheats Settings'>'Unlimited Sprint' in the menus).

The default behavior for hud meters is for them to fade out when they are full.

Also, tank morph is fixed in current BoA...  Guards are still a problem, though.

**Comment by hawkwind3** [comment]
Thanks for that. I see now why you need the older zkeys.zs ... Screenshot of my issue. Both stamina and air do work, but not show up permanently when needed, only on the hud type in the screenshot.
![stamina_air bars](https://github.com/Realm667/WolfenDoom/assets/35204218/ac759027-8c01-4e2c-a0ec-f2866153f228)

**Comment by hawkwind3** [comment]
Thanks @AFADoomer. All good now. I did try the HUD translucency but didn't go far enough to display Always Show. Not a bug. Closed.
