### ISSUE TITLE
some doors shifted upwards

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1406]
A little follow up.....

These doors in this map are shifted upwards.

![Screenshot_Doom_20240428_220325](https://github.com/Realm667/WolfenDoom/assets/77861029/6c015cd3-a5c0-4c41-8da8-0a3343e713d9)
![Screenshot_Doom_20240428_221147](https://github.com/Realm667/WolfenDoom/assets/77861029/f9c205d1-fdfa-4831-af8a-e27dbb8c3db6)
![Screenshot_Doom_20240428_221202](https://github.com/Realm667/WolfenDoom/assets/77861029/cd9512be-e455-4b96-9c81-d78f00b66a59)
![Screenshot_Doom_20240428_221211](https://github.com/Realm667/WolfenDoom/assets/77861029/70c123f8-b778-4827-beea-99895e75b863)

**Comment by hawkwind3** [comment]
There will be 3d sector issues. Will need further work.

**Comment by hawkwind3** [comment]
Hopefully fixed now

**Comment by x3003** [comment]
Seems fixed.
