### ISSUE TITLE
GZoom crash with latest messagehandler.zs and maybe tank.zs.

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1408]
C2M4 - on entering the truck at the start, gzdoom crashes with this error message ...

VM execution aborted: tried to read from address zero.
Called from MessageBase.Init at boa.ipk3:scripts/eventhandlers/messagehandler.zs
Called from ObjectiveMessage.Init at boa.ipk3:scripts/eventhandlers/messagehandler.zs, line 704
Called from Objective.Completed at boa.ipk3:scripts/eventhandlers/objectivehandler.zs, line 93

P.S. I just added the latest tank.zs and messagehandler.zs to boa.ipk3. Should I have downloaded the whole git and compiled ?

**Comment by AFADoomer** [comment]
No, it's a missing null pointer check.  Testing a fix now.

**Comment by AFADoomer** [comment]
Should be fix in 8f045279779b3214db231cf32f1cd6a96a6a4ad3.

**Comment by hawkwind3** [comment]
Fix confirmed. Thank You. Closed.
