### ISSUE TITLE
subways are misplaced

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1409]
Besides the running subways, there are still some subways that are stationair on the track all the time.
The first image is from the 'broken' one, the one that never moves, but it's placed too much forward.
The other ones shouldn't be there.

![Screenshot_Doom_20240430_225907](https://github.com/Realm667/WolfenDoom/assets/77861029/2dea9e2c-4ddc-41ec-bdf8-f4f2850d810c)
![Screenshot_Doom_20240430_225916](https://github.com/Realm667/WolfenDoom/assets/77861029/e44776b4-6465-4a1a-8a6d-a99a0266925c)
![Screenshot_Doom_20240430_225843](https://github.com/Realm667/WolfenDoom/assets/77861029/ad3da48e-5f47-4ba0-83ba-b3fa0f9ebd40)

**Comment by hawkwind3** [comment]
There is only one stationary train. Same as in boa3.1. I don't get a second stationary train. Odd.

**Comment by x3003** [comment]
With me, there are stationary trains on all platforms. And except for the one that should stationary, there are also trans running on the other platforms.

**Comment by x3003** [comment]
From the other side it's even worse...  The animation looks totally broken.

![Screenshot_Doom_20240503_165949](https://github.com/Realm667/WolfenDoom/assets/77861029/737c663b-3187-468e-9f1b-f6e2511e6b27)

![Screenshot_Doom_20240503_165915](https://github.com/Realm667/WolfenDoom/assets/77861029/4e35f10b-cf80-4abe-8679-8b7fe3a2f373)

**Comment by Tormentor667** [comment]
So it’s a bug with the engine or with our build? I mean it worked fine in 3.1

**Comment by x3003** [comment]
Since 3.1, i've played it an x amount of times (with git), never had this problem before. Think i check it w/ another recent built to compare.

**Comment by AFADoomer** [comment]
This doesn't happen for me on the current GZDoom github build...

**Comment by AFADoomer** [comment]
I take it back.  Was able to recreate it somehow.

**Comment by AFADoomer** [comment]
Can you reliably recreate this?  Does it still happen after cfd3568caebe8fa142fb1b7058f5a2ed4b6a5321?

**Comment by x3003** [comment]
This seems fixed.
