### ISSUE TITLE
Tank fired shell issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1410]
I've only now noticed that the tank cannon shell fires out in a small arc. For example, use the panzer in e3m5_a. With the crosshair on, notice that the fired shell dips lower than the crosshair. Compare with using the panzerfaust, it fires straight like a rocket, and seemingly faster. I have not compared with the sherman.

**Comment by x3003** [comment]
Yeh, nice eh ?! You can get some nice 'curveballs' out of it. Personally I like the effect.

**Comment by hawkwind3** [comment]
I personally don't like it. The tank cannon behaves like a glorified grenade launcher, not the way a tank cannon should.

**Comment by x3003** [comment]
When you really wanna fire on things far away, like on the end of the street, a straight line is not what you want because there's stuff in the way.

**Comment by AFADoomer** [comment]
Added the 'boa_noprojectilegravity' CVar in 2331d71566208c3678d5ddf310c5d5b70da4fdc0 to allow players/servers to disable gravity effects on bullet tracers and rockets.

**Comment by Tormentor667** [comment]
Does it make sense to add an option too?

**Comment by AFADoomer** [comment]
Probably, yes...

**Comment by hawkwind3** [comment]
Great Job ! Works like a charm.  :) .
