### ISSUE TITLE
C2M5_B saucer hangar sky issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1411]
C2M5_B saucer hanger sky issue - now can see a skyblue triangle in the saucer hangar sky.

![blue triangle](https://github.com/Realm667/WolfenDoom/assets/35204218/137c98e4-b1ce-4925-b6b6-3b21bf71a7d0)

**Comment by x3003** [comment]
Yes, the aliens have arrived, watching us ;)

![Screenshot_Doom_20240526_200008](https://github.com/Realm667/WolfenDoom/assets/77861029/c7b4489b-0131-4c1c-9115-5d7a99a4e6b5)

**Comment by hawkwind3** [comment]
Seems that recent gzdoom builds have fixed this. Aliens have left the building. Closed.
