### ISSUE TITLE
animation broken

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1412]
If you stand 'here' before entering the door, the animation of the guard and dog are broken, they don't move. Not even when shooting them. They only 'run' the animation when entering the building a bit.

![Screenshot_Doom_20240505_123309](https://github.com/Realm667/WolfenDoom/assets/77861029/129b32b0-80e6-4d82-8dbd-f43ef07ad362)

![Screenshot_Doom_20240505_123117](https://github.com/Realm667/WolfenDoom/assets/77861029/98b78f2e-a068-4c0f-9c21-60dfc2c876ae)

![Screenshot_Doom_20240505_123131](https://github.com/Realm667/WolfenDoom/assets/77861029/c656a268-5cb8-4ccd-aabe-94ba9b58c3c6)

**Comment by AFADoomer** [comment]
This is due to culling and actor tick optimization not taking portals into account...  I'll see what I can do.

**Comment by AFADoomer** [comment]
OK, should be better after cf7fe93f68f137cb6578fd23fca996778eb84bcf.

I also changed this to a static portal and cleaned up the skybox.  There's still a spot where you can stand and the sniper will never wake up and see you, but that's the same behavior as previously with culling disabled (due to the portal line) - at least now after you shoot him once, he will fire back regardless of where you stand.

**Comment by x3003** [comment]
That seems to work, only this animation was weird.
This scientist was already surrendering, somehow he un-surrendered, got another weapon, fired and frooze.

![Screenshot_Doom_20240505_223558](https://github.com/Realm667/WolfenDoom/assets/77861029/13642ed0-bcad-4291-b7bc-d9673105c8dd)
![Screenshot_Doom_20240505_223653](https://github.com/Realm667/WolfenDoom/assets/77861029/b5447ea0-cf6b-43c4-b212-022890a6ea68)

**Comment by x3003** [comment]
These actors won't move until fired upon.

![Screenshot_Doom_20240506_001544](https://github.com/Realm667/WolfenDoom/assets/77861029/8e766818-c296-4dd3-8d2f-9e84a75e301b)

**Comment by hawkwind3** [comment]
These actors won't move until fired upon.

Try the latest. See how you go.

**Comment by x3003** [comment]
>These actors won't move until fired upon.

These always move before you get down the stairs,

>Try the latest. See how you go.

Did you make changes then ? I was using the latest built from yesterday.

**Comment by hawkwind3** [comment]
Both AFADoomer and myself did changes to this map yesterday. Might be worth redownloading this map and restest. AFADoomers fixes are in the map.

**Comment by x3003** [comment]
The changes are ok, but what's most annoying is the slowness inside the train/subway station (10-15 fps).
If you switch to c3m5_b the speed is there again (100-120 fps).
