### ISSUE TITLE
bathroom mangled

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1414]
This bathroom is completely mangled, while the other one on the same floor is still in one piece.

![Screenshot_Doom_20240506_001708](https://github.com/Realm667/WolfenDoom/assets/77861029/2e869437-c3ab-443f-93a2-d84063f17319)

**Comment by hawkwind3** [comment]
Fixed now. Originally  ( well in boa 3.1 ) there was an issue with that bathroom sector - 1927 - as the floor did not show up when seeing floor textures in UDB. And then subsequently even the floor and ceiling heights somehow got screwed since. All good now.
