### ISSUE TITLE
items appear out of nowhere

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1415]
Some of the items just appear out of nowhere when walking towards them. This happens inside a building, with the setting of 8192 lookahead. This sometimes happen with trees that are far away, but it shouldn't happen inside, just a meter or so away.

![Screenshot_Doom_20240506_232301](https://github.com/Realm667/WolfenDoom/assets/77861029/4dbe68fb-c310-4414-909f-3b29f310af3f)

![Screenshot_Doom_20240506_232309](https://github.com/Realm667/WolfenDoom/assets/77861029/fdc4c5ca-d387-4df8-a631-a9963ad5228d)

**Comment by AFADoomer** [comment]
This should be fixed after e208b81b03f0a57c78d5f09cbebe292097553990.  Chunk handling, and by extension the culling code, is now line portal aware.

**Comment by x3003** [comment]
Seems fixed,
