### ISSUE TITLE
c3m5_a got very slow

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1416]
While testing c3m5_a I found that the last couple of builds became very slow.

On the end of the 'main street' you might reach 3-5 fps, while an older build does 30-40 fps.

Tested w/ boa 3.1, no problem.
The last one that worked was: boa git 07/05/2024 & gzoom 4.12 pre 401.
The first one that was broken was boa git 08/05/2024 & gzoom 4.12 pre 401.
I used an older version of gzdoom to make sure it wouldn't interfere too much (because of recent changes).
Also, if I load in the savefile from 08/05 on the 07/05 build, it works fine.

![Screenshot_Doom_20240509_005034](https://github.com/Realm667/WolfenDoom/assets/77861029/5af10852-47ee-463d-9916-bba4b757a1c9)

**Comment by hawkwind3** [comment]
Something strange is going on here. Remember your issue #1412 ? I uploaded this map 3 days ago and you said it was ok. I just now checked and the master commit has the map just before my fixes dated 4 days ago ... ???

**Comment by AFADoomer** [comment]
Did I accidentally overwrite your changes at some point?  

Everything looks like it's here in the commit history...  https://github.com/Realm667/WolfenDoom/commits/master/maps/C3M5_A.wad

**Comment by AFADoomer** [comment]
This looks like it's related to culling traversing portals...  There are two within short range in that area.  If I disable the portal traversal, things speed back up.

**Comment by hawkwind3** [comment]
The only way you could have overwritten my upload is if you uploaded yours twice, and I doubt that. I still have my slightly updated version - which still needs some alignment work elsewhere. Will do that later.

**Comment by AFADoomer** [comment]
Any improvements after 351fb1c92919d189e542bfb3ce99b26c5efb1c4d?  

I added a check to eliminate some possible recursion...  @hawkwind3  - I am not planning to touch the map itself, so feel free to upload whatever you need to.

**Comment by x3003** [comment]
Re-checked. You can still get 5 fps in that last bit of street.

![Screenshot_Doom_20240511_071303](https://github.com/Realm667/WolfenDoom/assets/77861029/f1fa9ec9-1959-475c-b147-c2584cb2eb71)

**Comment by x3003** [comment]
With the latest version, it seems fixed.
