### ISSUE TITLE
C3M0_A - possible day/night cycle bug

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1417]
Please see screenshot. On level start, clip to the mansion. Note the different light levels on the walls. Does the rest of the mission in this map stay on nighttime ? If so, should not be a bug.

![day_night_sky](https://github.com/Realm667/WolfenDoom/assets/35204218/5c005622-50b3-4a4e-bf42-02971d040e0c)

**Comment by x3003** [comment]
I think it stays night, because you must repair the 3 boxes and then the 'street'lights go on.

**Comment by AFADoomer** [comment]
Those have been a problem for a long time.

The day/night cycle isn't actually free-running.  It sets to specific times as you make progress through the map, and the sun/moon move to catch up to the set time.  If you warp or clip to a specific spot, you are skipping those triggers.

Normally, by the time you've made it to this spot, the map has had time to shift to nighttime (getting red key, getting shovel, breaking lock, etc.).
