### ISSUE TITLE
C2M3 Secret Hint Paper bug

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1418]
I have mentioned this before at issue #1339 for this map point 16. 
More info... On picking up the secret hint paper - T2050 - and not getting any secrets to this point, the player is credited with
??? it disappeared from one of the houses, don't know where. This refers to the Total Gier on the rooftop, but the player has not got this yet.

**Comment by Tormentor667** [comment]
A possible issue could be that the sector ids changed during editing. If the sector ids are different the referring secrets don’t work anymore as they are stored in the google spreadsheet for the language.

You might want to check that first

**Comment by hawkwind3** [comment]
Was caused by the Totale Gier on the rooftop having 2 tags. This did not affect BOA3.1/gzdoom 4.6. Now fixed with  just 1 tag.

**Comment by hawkwind3** [comment]
Reopened. See screenshot. Picked up hint paper before getting any Things marked as "count as secret".
![c2m3 secrets bug](https://github.com/user-attachments/assets/a020ea9a-ddf1-460a-9efe-a49fc5d16dd0)
