### ISSUE TITLE
GZDoom 4.12.2 issue with fire and water spawners

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1419]
With fire and water spawners  ( at least ) with GZdoom 4.12.2,  the spawners go out and then respawn. A good check for this is at the start of C3M2. Notice that the campfire goes out and reignites ad finitum. Not a problem with gzdoom 4.12.1. I realise that GZDoom 4.12.2 has not officially been released but I thought worth mentioning.

**Comment by x3003** [comment]
I think you mean c2m3 [?!]. And yes, first the fire is out and then re-ignites in a blast.

![Screenshot_Doom_20240523_203704](https://github.com/Realm667/WolfenDoom/assets/77861029/1a9de553-8d19-4889-9d24-f2075a0de9b1)

**Comment by AFADoomer** [comment]
4.12.2 *is* officially released, they just never updated the download page for some reason.

I can't reproduce any issue with current(-ish) dev build either.  That said, disabling culling (boa_culling = false) would cause the fire to effectively never spawn any flames/smoke/embers- that's been fixed now as of 02ba38d64728ecf9c33640e5b0ce4d6577bfdb5f.

**Comment by hawkwind3** [comment]
@x3003 yes, I meant c2m3. Sorry about that. Good to see that you are "on the ball"  :) .
AAFADoomer - Yes, you are also correct. Why it was not officially released is a mystery. Even the dev builds have not been updated for nearly a month. Something is going on ...

**Comment by hawkwind3** [comment]
@AFADoomer - Your fix works perfectly in both gzdoom 4.12.1 and 4.12.2. Good Job !  👍  Closed.
