### ISSUE TITLE
Custom IWAD

### ISSUE THREAD

**Issue by raa-eruanna** [Realm667/WolfenDoom#142]
https://github.com/coelckers/gzdoom/commit/4fb355d8da8b752be74b2aa583b9890870ad18fb

Just writing to let you guys know this was committed - as I recall that was one of your obstacles towards full custom integrated IWAD support.

**Comment by AFADoomer** [comment]
Fantastic.  Thanks, Rachael!

**Comment by Tormentor667** [comment]
Thanks kindly, just a question: What does it exactly?

**Comment by raa-eruanna** [comment]
Allows you to do a lil something like this:

iwadinfo.txt:
<pre>IWad
{
	Name = "WolfenDoom: Blade of Agony"
	AutoName = "WolfenDoom.BoA.v3"
	Game = "Doom"
	Config = "Doom"
	StartupType = "Hexen"
	BannerColors = "E3E3E3", "E3E3E3"
}</pre>

Save that, put it in your pk3, rename your entire project's filename BladeOfAgony.ipk3 (or something like that, doesn't matter as long as it's ipk3) - then - open GZDoom and look at it appear on your iwad list, launch it, and watch as it (should) work on its own. :)

**Comment by Ozymandias81** [comment]
These are indeed great news, thanks for sharing!
So now we have to handle a brand new file extension when needed, the .ipk3 file, which sounds pretty intuitive though.

@raa-eruanna I have just a question: what happened to svn builds of QZDoom? I must admit that I am not exactly active since this summer on forums, but noticed that you stopped since 15 July...

**Comment by raa-eruanna** [comment]
QZDoom hasn't had anything new over GZDoom for a while now, and as long as that remains the case there's not much point in really maintaining it.

**Comment by Ozymandias81** [comment]
Got it. :)
Will keep this open just as a reminder though, thanks in advance.

**Comment by Ozymandias81** [comment]
Since this has been addressed and added, I am going to close it.
