### ISSUE TITLE
lock open with a kick instead of a shovel

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1420]
In c3m1_a you can kick this lock off when you have the shovel, instead of using the shovel itself. Maybe this can be changed so you can only use the shovel against the (or any) lock ?!

![Screenshot_Doom_20240525_121306](https://github.com/Realm667/WolfenDoom/assets/77861029/ea543165-27e2-4117-a082-7f64f01341aa)

**Comment by Tormentor667** [comment]
Yes that’s definitely important, or the shovel would be redundant

**Comment by hawkwind3** [comment]
A similar, but different, with scripting and map construct is in C3M0_A. And that one works as expected. The only other area that this might be important is the map ( number escapes me ) where you need the shovel to dig for secret treasure.
Also, this issue is present in boa 3.1.

**Comment by x3003** [comment]
> or the shovel would be redundant

The shovel is a good silent weapon and has good reach.

**Comment by hawkwind3** [comment]
This has since been improved. Now only the lock can be "broken" by kick/shovel. Remember all this was done before kicking came a reality. And both kick and shovel are impact weapons. I don't think this can be completely addressed.

**Comment by Tormentor667** [comment]
I think as long as you must have the shovel to kick open the lock, we can live with that. So I will close this.
