### ISSUE TITLE
Skybox issue C3M0_A recent GZDoom issue ?

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1421]
Sector Effect 90 - GZDOOM Skybox, does not work correctly with recent GZDoom's.
See Pic.  Look closely at the crosshair.
![C3M0_A skybox bug](https://github.com/Realm667/WolfenDoom/assets/35204218/150929c5-2a7a-4ac4-b294-c7c060fe700d)

**Comment by Tormentor667** [comment]
Looks to me like a rendering issue
