### ISSUE TITLE
No skybox rendered in either C3M3_A or C3M3_B

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1425]
As described on the tin.  Just F_SKY1 is rendered.
This one goes back to at least GZDoom 4.10.
Screenies attached. The good one, bottom,  is from BOA 3.1.

![no skybox c3m3a and b](https://github.com/Realm667/WolfenDoom/assets/35204218/36b1aad5-0152-40d0-96d7-9cd814d5999e)

![good skybox boa 3 1](https://github.com/Realm667/WolfenDoom/assets/35204218/08d18777-5206-4793-ad0f-95ca41db10a1)

**Comment by x3003** [comment]
Yes, it now looks like day, instead of night.

**Comment by hawkwind3** [comment]
Could be.

**Comment by AFADoomer** [comment]
Yes, because I'm sure the change in the engine that necessitated that fix has nothing to do with this...  🙄

**Comment by hawkwind3** [comment]
So what to do ?

**Comment by x3003** [comment]
I uncommented the old code and removed the new code in skyboxview and ran an older version of gzdoom. It ***is*** the fix that makes the sky not rendered.
Seems there's a catch 22 now.

**Comment by AFADoomer** [comment]
Of course the old code works in an old version of GZDoom. A change that was made in the engine is what broke things in the first place. 

My hacky fix apparently doesn't fully restore the original behavior.  

I currently have zero motivation to deal with any of this.

**Comment by x3003** [comment]
>My hacky fix apparently doesn't fully restore the original behavior.

No, but my point is that in order to fix a little bug that was there (in gzdoom) for many [?] years and most didn't care about, there's now a situation that possibly breaks a lot of wads. And yours is one of them, unfortunately.

**Comment by hawkwind3** [comment]
Fixed.
