### ISSUE TITLE
items appear/disappear when moving

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1426]
In c3m3_a some items appear when you get closer to them and others (trees) disappear. Also when rotating at the same spot.
The viewing distance is set to max, so it **shouldn't** be a problem.

![Screenshot_Doom_20240616_111133](https://github.com/Realm667/WolfenDoom/assets/77861029/b615968b-8577-47bb-8eb1-3a9281040325)
![Screenshot_Doom_20240616_111139](https://github.com/Realm667/WolfenDoom/assets/77861029/f3625332-0cda-4acf-b726-92a409dfaaaf)
![Screenshot_Doom_20240616_111202](https://github.com/Realm667/WolfenDoom/assets/77861029/f322087c-8485-4d78-b236-32f02683c07c)

**Comment by hawkwind3** [comment]
Try as i might, I could not reproduce. Using latest boa dev build no compression,Vulkan, and GZDoom 4.13 pre 71.
I did a minor edit of the area in question. That wall light was/is too low and renders partly in the brick. Same for the trolley.
Try the attached. if it fixes your issue, great. But I doubt it.
[C3M3_A.zip](https://github.com/user-attachments/files/15860476/C3M3_A.zip)

**Comment by x3003** [comment]
Your fix didn't fixed it.
The last version that works for me is the one from 20/04/2024. The version from 21/04 gives me some dissappearing items.

**Comment by hawkwind3** [comment]
@x3003 , you steered  me in the right direction. It all comes back to that damn boa culling =true/false in the gzdoom ini file ( or line 44 in cvarinfo.txt in boa.ipk3. Why I wasn't having the issue you had is because some time ago I had set my ini file to false. Setting to true gives the bug again ... If setting to false the issue is gone. You won't even get those trees showing up at the start of c3m3_a. Really, I think all this processing should be done before the player is spawned.

**Comment by AFADoomer** [comment]
Ok.  Set to to false as default then.  Have fun.  Bye!

**Comment by x3003** [comment]
It still doesn't work for me.

**Comment by hawkwind3** [comment]
Check either gzdoom.ini or gzdoom_portable.ini - whichever one you use, and check [BoA.LocalServerInfo.Mod] and see if this is set ... boa_culling=false

**Comment by x3003** [comment]
I can't set it in gzdoom_portable.iit, as gzdoom says 
    
Execution could not continue.
Script error, "boa_c3.pk3:cvarinfo.txt" line 44:
cvar 'boa_culling' already exists

So it's already set in the script.

**Comment by hawkwind3** [comment]
@x3003 Could you please post here a copy of either your gzdoom_portable.ini or gzdoom.ini file.
