### ISSUE TITLE
Can't kick door

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1429]
In c3m3_b, somehow this door can't be kicked open, it can't even be kicked.

![Screenshot_Doom_20240622_114051](https://github.com/Realm667/WolfenDoom/assets/77861029/22c98ac2-3729-45d6-b17d-3a45431caddc)

**Comment by hawkwind3** [comment]
I can kick the door open. Just did now. Question though ... are kicked open doors supposed to stay open ?

**Comment by x3003** [comment]
>are kicked open doors supposed to stay open ?

Yes.

**Comment by hawkwind3** [comment]
Correct. The sign at the door is causing the problem. A polyobject issue. Will see if I can do something about it tomorrow. Good catch !

**Comment by hawkwind3** [comment]
Fixed.

**Comment by x3003** [comment]
This works.

**Comment by x3003** [comment]
>Fixed in this case. There may be other instances of this issue out there ...

Like this one:

![Screenshot_Doom_20240815_113601](https://github.com/user-attachments/assets/c122b3b6-3d02-48c0-8c7f-177179e322b3)

**Comment by hawkwind3** [comment]
You have probably worked out that I'm working on this particular map. Yes, I noticed this too and have fixed this on - my yet to be commited - copy. Notice the cyan strip where the hinge would be. I've fixed that to along with quite a number of issues in this map.

Keep reporting them. I might have missed some. Saying that, I have noticed this in other maps which I haven't addressed yet.
