### ISSUE TITLE
Enemy not moving anymore

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1430]
In c2m4, these soldiers (and only these 4) are stationairy / not shooting anymore while seeing you.

![Screenshot_Doom_20240614_160640](https://github.com/Realm667/WolfenDoom/assets/77861029/3ac1a61e-14ac-4cbd-9be1-7cec9aaf6097)
![Screenshot_Doom_20240614_160649](https://github.com/Realm667/WolfenDoom/assets/77861029/571eb4e9-9be0-4005-8b08-577fa1bc9336)

**Comment by hawkwind3** [comment]
Not a bug. A deliberate change by me. Now all the windows in that building have been flagged "block monster line of sight" . The jerries were a bit dumb before, constantly shooting at "bullet proof" windows if they saw you. Now they don't waste their ammo. They just wait for you to come inside ...

**Comment by hawkwind3** [comment]
Closed.
