### ISSUE TITLE
Plant sway issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1432]
The use of boapixelate.txt is stopping all the flora from swaying. Seems to negate this effect that is in boashaders.txt.

**Comment by hawkwind3** [comment]
More on this ...

Seems to be that the "plant sway in the breeze" may not have worked at all. Doesn't seem to work even in boa 3.1. As an experiment, I deleted all the contents of boapixelate.txt. Lo and behold, all the sprite plants would sway. Quite a nice effect really. Shame it doesn't work as things stand ATM.

**Comment by Ozymandias81** [comment]
Commit https://github.com/Realm667/WolfenDoom/commit/b282de0e076c9bcf36550901369b80239f986f5e solved this and not issue 1433, sorry.
