### ISSUE TITLE
Tiny feedback message.

### ISSUE THREAD

**Issue by r3538987** [Realm667/WolfenDoom#1433]
Hello,
Back then in 2023 when played GitHub version, after completion, noted few points that caught my attention. So adding these here, so maybe someone give an comment. 
1) Certain switches (Catacombs) are really quite hard to find especially ones which you see for first time. Distinguishing them from rest stuff can be hard sometimes. 
2) Turret guys, their hitboxes are quite challenging, because in one stance they look away, in other - they look at you and shoot. Distance between two is noticeable. You peak from cornet, aim for enemy that looks to side, but he quickly turns, and now you look not on enemy.
3) Does game explains why radios has these arrows on top of then and why you have to destroy these? collectables/achievement?

**Comment by x3003** [comment]
1) There is the element of exploring and finding stuff out. You can't expect to give the player hints all the time.
2) Some hitboxes already have been reduced. Just find out if 'yours' is one of them.
3) Yes, some ppl wanna destroy stuff constantly. Give them some exrtra stuff to destroy. (　-_･) ︻デ═一  ▸

**Comment by r3538987** [comment]
About hitboxes, tried build after commit 72e04c6. 
https://webmshare.com/play/AZxdP 
Shooting turret guy in head doesn't damage him, this is pretty as it was year ago. So caught my attention.

**Comment by x3003** [comment]
Turret guys mostly need 2 shots, I believe.

**Comment by r3538987** [comment]
> Turret guys mostly need 2 shots, I believe.

Only it they land accordingly, and go through like in video. :)
