### ISSUE TITLE
hitboxes in the way

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1434]
In c2m5_b there are a few hitboxes, so you can't shoot the enemy (or he can't shoot you).

![Screenshot_Doom_20240707_011124](https://github.com/Realm667/WolfenDoom/assets/77861029/59bd21f3-b4de-4038-b88e-17438eade7f9)
![Screenshot_Doom_20240707_011109](https://github.com/Realm667/WolfenDoom/assets/77861029/79be6212-d8a5-4b3b-8a59-1b26d36eaf6c)
![Screenshot_Doom_20240707_011100](https://github.com/Realm667/WolfenDoom/assets/77861029/6296850e-7bb4-4550-9dfc-6b46f0b0b42d)

**Comment by hawkwind3** [comment]
Fixed. Actually it was not a hitbox issue. Somehow, and I'll never know how, the sides of the overhead gantries were given the block hitscan and projectile flags. UDB getting up to miscief.
