### ISSUE TITLE
wall issue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1435]
A few walls aren't connected to each other.

This one is correct: 

![Screenshot_Doom_20240429_225613](https://github.com/Realm667/WolfenDoom/assets/77861029/b4ac6e6e-1124-43e3-90f2-86a3219df2ed)

But there aren't:

![Screenshot_Doom_20240429_225618](https://github.com/Realm667/WolfenDoom/assets/77861029/ee947269-5991-47b0-ae9d-f69b666d17e5)

![Screenshot_Doom_20240507_223857](https://github.com/Realm667/WolfenDoom/assets/77861029/86aa7eb8-565d-4f65-b990-b7a08d15a279)

**Comment by hawkwind3** [comment]
Not a bug, but a dynamic light setting. Go to Display Options > Dynamic Light Options > and set Shadowmap quality to 1024 and shadowmap filter to Nearest and that issue is gone.
