### ISSUE TITLE
actors not activated

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1436]
In c2m5_b, when entering opening this door, 3 actors, the ones on the left and the top right aren't activated, while the ones on the right are. Even when stepping into the room, the left ones aren't activated for some time.

![Screenshot_Doom_20240707_091347](https://github.com/Realm667/WolfenDoom/assets/77861029/87c86340-dc3a-442d-80ad-d80f5c4719d8)

**Comment by hawkwind3** [comment]
Not a bug. Due to the direction they are facing, they won't move/attack until "they can see you''. Compare with boa 3.1. You will find that those 2 on the left could not move. They were stuck on the cratfe. I freed them ...

**Comment by x3003** [comment]
The ones on the right can't see me either, but they are moving from the time i open the door.

**Comment by hawkwind3** [comment]
Yes. To be expected. Those on the right are facing NW.
