### ISSUE TITLE
Jacket is gone

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1438]
In c2m6_a, there was a leather jacket here, but now it's gone.

![Screenshot_Doom_20240708_214249](https://github.com/Realm667/WolfenDoom/assets/77861029/dedf6b34-32c5-4192-8982-b12fa73d0b02)

In v3.1:

![Screenshot_BoA_20240708_215548](https://github.com/Realm667/WolfenDoom/assets/77861029/aaf8fcc9-8936-444f-b610-2bffa9004ca3)

**Comment by hawkwind3** [comment]
Fixed. It was "underwater" between the sea floor and the ceiling of the pier. It was positioned in UDB as being slighly rendered inside the pier. So it appears that GZDoom now has an issue as where to place these things. I just increased its Z height to render on the floor of the pier. I had a similar issue with the nearby chest. How that one was fixed I cannot tell.

**Comment by x3003** [comment]
Thx for the fast fix.
