### ISSUE TITLE
c2m5_b gets very slow

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1441]
Tested w/ the latest gzdoom version,
At the start of c2m5_b, when walking, it's already a bit choppy (always), but when going through the blue doors it's only getting worse, down to 5-10 fps. Which is pretty much impossible to play.

**EDIT:** The last version that was smooth is from 07/05/24, the built from a day later started the slowness.

![Screenshot_Doom_20240707_221456](https://github.com/user-attachments/assets/ed587d80-4529-4a95-b24d-a1d0c0988472)

![Screenshot_Doom_20240707_221847](https://github.com/user-attachments/assets/d22d69cc-ae35-4251-9d20-969c1bce345f)

![Screenshot_Doom_20240707_223514](https://github.com/user-attachments/assets/aeb43af2-8bbe-4bbb-afc2-38e4613737a4)

**Except** for the wind and fire rooms. There the speed comes back, altough it could be higher.

![Screenshot_Doom_20240707_234907](https://github.com/user-attachments/assets/6ca000c9-bf89-46a3-bb61-33c6f1168230)

![Screenshot_Doom_20240707_235445](https://github.com/user-attachments/assets/b015f6ec-4828-4254-b0c7-e598d44e7284)

But if you're done there, going to blow up the alien ship, it's back to slowness again.
Hope someone can check it out, as it's really annoying.

**Comment by hawkwind3** [comment]
Got around to playing this level again. Had no slowdowns at all ( with the exception of autosaves ) Generally stayed at about 60 fps. I tried to take screenshots, but when I did, the fps would drop to either 0 or 1 on the screenshot. I'm guessing a win11 issue.

**Comment by x3003** [comment]
It's still sluggish, but playable from the start, but when going to the blue area it's getting very slow. This will not happen on older builts, so something has changed. So what has changed on 08/05, which is the first one that slows down on my machine ???

![Screenshot_Doom_20240718_224434](https://github.com/user-attachments/assets/08f8babf-0758-4f96-824d-76163ab145be)

**Comment by hawkwind3** [comment]
I recreated your last screenshot. Before firing, I was getting between 90-100 pfs. Dropped momentarily to 55 with the explosion.
1. Could you please post the map that works fine for you. I could backtrack the changes to hopefully track down why you are having this issue.
2.  Could you please post your ini file. I can then compare to mine.
3.  What are your machine specs ?. Mine is nothing special - I3 -10105, gtx 1080, 8GB RAM, win 11.

**Comment by x3003** [comment]
I run the latest gzdoom / vulkan 1920x1080 fs on an amd r5 2600 gtx 1060 3 GB win 10, driver 556.12.
I start the level with map c2m5_b.

When saving the 'good' level and loading it in the 'bad' map, no slowdowns.
But when loading a 'bad' one in the 'good' one you'll notice the speed increase.

Compare: 
Save with the 0805 version:

![Screenshot_Doom_20240719_143958](https://github.com/user-attachments/assets/27531930-984f-4743-9bf8-24f6a2921a13)

Loading into the 0705 version:

![Screenshot_Doom_20240719_144106](https://github.com/user-attachments/assets/4821d685-da1c-4e7f-88d3-57cdbd83ccbc)

I copied the working map into the very latest git version and I see no difference, so it doesn't look like the error is in the map itself, but with a change elsewhere.

[c2m5_b_config.zip](https://github.com/user-attachments/files/16312338/c2m5_b_config.zip)

**Comment by x3003** [comment]
I debugged it a little more, the error comes from scripts/eventhandlers/ChunkHandler.zs
If I put the one from 07/05 into the git version, it works as expected.

**Comment by hawkwind3** [comment]
I'm glad you tracked it down to Chunkhandler.zs. Strange though, those 2 maps in the zip are exactly the same. See size and CRC. Also, those maps go back prior to even before June 6. I just checked my upload history to the git.

**Comment by x3003** [comment]
Thx for the help. Indeed there was a problem w/ the configfile. I applied some of your changes to mine, coz I couldn't fix some other issues (blurred switches / bigger icons). Ok, it's not 100 fps, but 80 will do. :)
I think mine is bigger because of some other games putting their settings there.

**Comment by hawkwind3** [comment]
I think I've pinpointed the actual cause in the ine file. I believe it to be ... 

[BoA.LocalServerInfo.Mod] //
boa_culling=true

@x3003  ( and others ) can you please confirm.

Like you, I also believe the issue stems from Chunkhandler.zs

**Comment by Tormentor667** [comment]
I wonder, how can we make sure that the standalone game ships with a correct ini so we do not have any issues like that for tue new standalone 3.2?

**Comment by hawkwind3** [comment]
Currently, this issue has nothing to do with GZDoom. It is a BoA 3.2 coding one. Also currently in the code cvarinfo.txt has this on line 44 
server bool boa_culling = false; 
This prevents a lot of the issues we are having. The main issue for me, is that I lose a lot of the rain effect.
Having culling set to true would be the ideal, but some fixing would need to be done.

Maybe a separate discussion on culling is called for ?

**Comment by Tormentor667** [comment]
Yes we definitely need that. Can you open an issue and describe most of that? We could try to contact @AFADoomer

**Comment by hawkwind3** [comment]
I'll let you open it. Should come from the Project Lead IMO. Hopefully should carry mor weight too.

**Comment by hawkwind3** [comment]
Closed. Should be ok now due to recent changes. Can always be reopened.
