### ISSUE TITLE
C1M5 old issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1446]
See Screenshot ...

![c1m5](https://github.com/user-attachments/assets/3fcb5be2-9a89-4a4f-86be-b78bc1a7136d)

If you try to recreate and fail to, just turn a bit left or right. Bug/Issue is even present in BOA 3.1/GZDoom 4.6.

Happens in all 4 corners of the bridge.

**Comment by x3003** [comment]
Confirmed. This piece of gate moves twice.

![Screenshot_Doom_20240801_225112](https://github.com/user-attachments/assets/6b5e0090-dc99-425b-918a-9e85ec7ccaba)

Also this piece isn't connected while the others are.

![Screenshot_Doom_20240801_225033](https://github.com/user-attachments/assets/b3aa8f2b-0d2c-48fa-aed1-d51f0c5a2db5)

**Comment by hawkwind3** [comment]
Finally fixed. Took me ages .....
