### ISSUE TITLE
steam spawner issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1447]
Steam Spawners don't seem to work correctly.

They are supposed to be constant, but seem to be bursts.
As an experiment, I changed these to bursts but got nothing.

Work great in boa 3.1.

![steam spawner](https://github.com/user-attachments/assets/34b64396-5b78-49c3-a28c-002fd74c7dc9)

Update ... This is a screenshot of a saved game. When I loaded this saved game, the steam spawner worked great .... for a few seconds, then went back to puffs ...

Update 2 ... Seems the issue applies to the Dark Smoke Spawners as well. Note and compare the dark smoke from the high chimney stacks at sectors 3767 and 3776, with BOA 3.1. Could this be a bigger issue with spawners in general ?

Update 3 ... Interestingly, the Zyklon B steam spawners ( and steam spawners) work correctly in C3M1_A ... I noticed that these in C3M1_A were tagged and scripted. I tried the same for C2M6_B without success.

Update 4 ... Screenshot from C2M6_B. Same with T3215. Is there something about this particular level ?

**Comment by hawkwind3** [comment]
Cause found ...

It is the latest steam.zs.

https://github.com/Realm667/WolfenDoom/commit/23c489a1052e3cc3522e8a489e7f5c97a24627a9#diff-1d20597a546c93333d8c021d70509afe2a40f91a719d2f7bc082587de283ccd6R168

This new code has caused the fault. When I deleted all the additions and restored that was deleted, the steam spawner again worked correctly.

Calling @Talon1024

**Comment by Talon1024** [comment]
So if I understand correctly, the particle spawners appear to work well right after loading a saved game, but break after a few seconds.

What if you increase the number of particles (Options -> Display Options -> Number of particles) to max? GZDoom may have hit the limit on the number of steam particles spawned, since they are actual particles now, instead of inert actors.

**Comment by hawkwind3** [comment]
>What if you increase the number of particles (Options -> Display Options -> Number of particles) to max? GZDoom may have >hit the limit on the number of steam particles spawned, since they are actual particles now, instead of inert actors.

That's it. Thank You. GZDoom default is 4000, which is not enough for BoA 3.2. This should be documented or a BoA setting for this.
