### ISSUE TITLE
strange animation in c3m1_b

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1448]
Strange animation going on in c3m1_b with WATR_G98...

Compare with boa 3.1.

Screenshot taken from sector 2688.

![strange animation1](https://github.com/user-attachments/assets/2e5fd710-8845-4da8-87a9-6060811b90e5)
![strange animation2](https://github.com/user-attachments/assets/b0cbeffb-b236-468d-82bb-fd971eac0360)

**Comment by x3003** [comment]
It looks ok with the 'true color sw renderer', but not w/ hardware acc.

**Comment by hawkwind3** [comment]
True color sw renderer has its own issues. Models not rendered and cannot see through the window.

**Comment by x3003** [comment]
Yeah, but it looks as if the anim is updated/rendered very slowly on hw acc, which seems ok w/ true color.

**Comment by hawkwind3** [comment]
Did a rework for this area. Looks ok to me.

**Comment by x3003** [comment]
Look like its fixed.
