### ISSUE TITLE
Switch in Operation: Exodus' Kommandozentrale returning to off-state

### ISSUE THREAD

**Issue by Alexander-Wilms** [Realm667/WolfenDoom#145]
After flipping the switch, it immediately resets. Not sure if this was done intentionally, I found this a bit confusing.

This also happens with the switch opening the interrogation room that agent Ryan is in.

**Comment by Ozymandias81** [comment]
Please provide screenshots with needed coords to know where this happen. In order to do that just type "idmypos true" from console and post here a screenshot of the exact place where you've noticed this.

**Comment by Alexander-Wilms** [comment]
![screenshot_doom_20180122_225011](https://user-images.githubusercontent.com/3226457/35246344-adadd146-ffc6-11e7-9b5f-2eae2ba876fe.png)

**Comment by Ozymandias81** [comment]
Those are intended to work this way since we mustn't be able anymore to interact with them, plus the texture code works like that too
