### ISSUE TITLE
Different size barrels

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1450]
In c3m1_a, these barrels have a diffent size:

![Screenshot_Doom_20240815_111133](https://github.com/user-attachments/assets/e2b01899-c07b-48a5-ab5d-9ada0422fe96)
![Screenshot_Doom_20240815_111145](https://github.com/user-attachments/assets/b69796a2-7063-490f-a209-b2b0ce719341)

**Comment by hawkwind3** [comment]
Not a bug. Scaled by the author to that size.
