### ISSUE TITLE
C3M5_C can be softlocked

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1453]
In C3M5_C, if the player does not pick up the green key, the game can be softlocked.

Imagine this scenario ...
1. Player does not pick up the Green Key but picks up the Yellow Key at sector 381 first instead. Then ...
2. Player uses Yellow Key at sector 1751. Then ...
3. Player gets Red key at sector 329. Then ...
4. Player opens Red Key door at sector 692. Then ...
5. Player teleports at linedef 1581 to linedef 1439. Then ...
6. Player crosses the bridge south and uses te lift to go up. Then ...
7.  Crosses bridge again north and makes way to linedef 6220 and telelports to linedef 6156.
8. Player is trapped here. Cannot climb back up the ducting and does not have a green key to open sector 2268.

I can think of a few fixes. Here they are in my order of preference.

a) Make the doors to the "bridge", sectors 311 and 324, be green key doors.
b) Change the green door sector 2268 only be a green key open from sector 2666's side only, so it can be opened from sector 2348's side.
c) Place an additional green key somewhere around sector 2359.
d) Ladders at the ducting from linedef 6230 to climb back up.

UPDATE ....

Just to add, currently this map already has 2 different red key doors, sectors 1301 and 692. So extra green doors should not matter. Hopefully I'll get a dev's response to this big issue. If not I will implement my first preference.

**Comment by hawkwind3** [comment]
That is an option. But would require the making of a new door texture, and a brightmap to go with it. Probably not worth the effort.

**Comment by x3003** [comment]
You could leave it as is. If someone gets softlocked they can always restart.

**Comment by hawkwind3** [comment]
I could. But I'd rather not. No game should ever softlock. Considered a bug.

**Comment by Talon1024** [comment]
I like the idea of having the doors to the bridge locked by the green key.

**Comment by hawkwind3** [comment]
Done.

**Comment by hawkwind3** [comment]
I previously upped this wad to the root directory. Now fixed.
