### ISSUE TITLE
C3M5_C render bug

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1454]
Please see attached.

![1](https://github.com/user-attachments/assets/765f4dff-6a3e-4488-b72e-751e16243435)

This shows that the outside of the texture midg_gat1 is not being rendered on the outside.

![2](https://github.com/user-attachments/assets/4476c5ba-349c-44d7-b130-b57b56ef85c5)

This one shows the render bug inside the bridge. I suspect it has something to do with the 1st pic.

All this is not an issue with BOA3.1/GZDoom 6.4.

I tried without success to fix this. Over to you guys ...

**Comment by x3003** [comment]
That's weird, from the other side you don't get that effect.

![Screenshot_Doom_20240821_122334](https://github.com/user-attachments/assets/3f89784e-4ecd-4d23-bffd-5452c59316dd)

**Comment by hawkwind3** [comment]
I think I've fixed it. Problem was in specials.zs. It did not like RenderStyle "Transluscent " Just another example of the latest gzdoom not being forgiving.

This is how it looks from line 661 to line 699.

class SlopeMe1 : Obstacle3d //Ozy81
{
	Default
	{
		//$Category Misc (BoA)
		//$Title Slopeable Glass (clear)
		//$Color 3
		DistanceCheck "boa_scenelod";
		Radius 16;
		Height 4;
		Renderstyle "Translucent";
		+NOGRAVITY
		+CullActorBase.DONTCULL //remove in 3.1 
	}
}

class SlopeMe2 : SlopeMe1 //Ozy81
{
	Default
	{
		//$Title Slopeable Glass (checker)
		+CullActorBase.DONTCULL //remove in 3.1 
	}
}

class SlopeMe3 : Obstacle3d //Ozy81
{
	Default
	{
		//$Category Misc (BoA)
		//$Title Slopeable Glass (clear)
		//$Color 3
		DistanceCheck "boa_scenelod";
		Radius 16;
		Height 4;
		+NOGRAVITY
		+CullActorBase.DONTCULL //remove in 3.1 
	}
}

Could you please test the attached before I commmit.

[special.zs.zip](https://github.com/user-attachments/files/16703106/special.zs.zip)

Please place in scripts>decorate>models.
