### ISSUE TITLE
C3M5_C Script - SKYBOX FADE AND COLOR TRANSITION

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1455]
In C3M5_C there is a script, which, if I understand correctly, is supposed to darken the sky.
Starts from line 315 ( well, technically, line 319 ).
Does this script work ? Or am I missing something.

**Comment by Tormentor667** [comment]
Well, it should work or at least worked in the past. It's supposed to be the day/night transition as preparation for C3M6

**Comment by Tormentor667** [comment]
Tested it, in general it works but found a different issue. Will post immediately.

**Comment by hawkwind3** [comment]
Exactly. I was going to get around to mention this very thing.
Good to see that it is being looked into.
________________________________
