### ISSUE TITLE
[C3M5_C] Skybox light/fade affects mountains but not sky

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1456]
The script that controls the fading of the skybox works for the mountains but not for the sky anymore. It seems as if the line that changes the 3d-actors alpha channel at line 340
``SetActorProperty(45, APROP_Alpha, (1.0 * (fadetime - i)) / fadetime);
doesn't affect the translucency anymore. I can remember that @AFADoomer created that 3d object and the effect. 

Beginning:
![beginning](https://github.com/user-attachments/assets/a6c05358-5bb2-4322-adec-0d0674b36ad8)

Later:
![middle](https://github.com/user-attachments/assets/76b4a930-5d68-4799-8f92-064b1b3630ef)

The clouds actually should slowly vanish and the night sky should appear by increasing the transparency of the 3d object. But this does somehow not work anymore.

**Comment by Tormentor667** [comment]
Update: This is obviously an engine bug. Adding alpha to the 3d object doesn't change its look ingame. It's always fully opaque.

**Comment by hawkwind3** [comment]
I've done some experiments and I nearly got it to work correctly.
I got it to work - sort of -  with this script ...

Sector_SetFade(53, red, green, blue);
		SetActorProperty(45, APROP_RenderStyle, STYLE_Translucent);
		SetActorProperty(45, APROP_Alpha, (1.0 * (fadetime - i)) / fadetime);
		delay(1);

Note the new code = SetActorProperty(45, APROP_RenderStyle, STYLE_Translucent);
This appears to bring back the attribute of the Thing in UDB.

Worked great for exactly 10 minutes, which reflects this code ...

int fadetime = 35 * 60 * 10; // length of time (350 is 10 seconds)

All that needs to be done is for the script not to revert back the sky to Alpha 1.0.

**Comment by hawkwind3** [comment]
Some screenies with the above code addition ...

before 10 minutes ...

![before 10 mins](https://github.com/user-attachments/assets/81124106-8594-436e-b8b9-deb47b2ae880)

after 10 minutes ...

![after 10 mins](https://github.com/user-attachments/assets/9046f9df-84c1-4b12-a30f-0c37f68a3ef3)

The fix just needs to continue after 10 minutes.

Worst case scenario, we could start the level with the night sky.

**Comment by hawkwind3** [comment]
I'm ging to hazard a guess here ...

This is in scripts > decorate > models > special.zs line 756 ...

class MountainsSun3D : PlainsSun3D
{
	Default
	{
		//$Title Mountain Day SkyBox (MountainDay, Special)
	}
}

Note that here there is no reference to renderstyle or alpha.

When I add this like so ...

class MountainsSun3D : PlainsSun3D
{
	Default
	{
		//$Title Mountain Day SkyBox (MountainDay, Special)
               class MountainsSun3D : PlainsSun3D
               Renderstyle "Translucent";
	       Alpha 1.0;
       }
{

.... Transparency and Alpha are restored. But only for 10 minutes.

So it seems that the setting in special.zs overrides the setting for the UDB setting now. Probably applies to other things too.

I hope this gives someone a clue of how to fully fix this.

**Comment by hawkwind3** [comment]
This is what I did ...

Added this to the script ...

SetActorProperty(45, APROP_RenderStyle, STYLE_Translucent);

and gave sectors 122 and 2513 tag numberr 53.

This is the result after 10 mins. Better than the bright sky in the previous screenshot.

![partial fix](https://github.com/user-attachments/assets/393d73a8-536d-4065-bfac-0dd5db7a97a0)

Here is the map which includes the latest fixes ...

[C3M5_C.zip](https://github.com/user-attachments/files/16957083/C3M5_C.zip)

**Comment by hawkwind3** [comment]
I also made mention of your zdoom bug report @Tormentor667 here ...
https://github.com/ZDoom/gzdoom/issues/2708

**Comment by hawkwind3** [comment]
I have an idea which may or may not work ....
Can the model Mountain Day Skybox - Type 12506 - be removed via script just before the 10 minutes times out ?
I think that would solve our problem.
Still involves the use of - SetActorProperty(45, APROP_RenderStyle, STYLE_Translucent); in the script.

**Comment by hawkwind3** [comment]
I've made a great workaround. Can be used if the BoA coders cannot come up with better and if the GZDoom devs cannot fix the issue. As such this has not yet been added to the commit.

Added this to the script ... line 342
SetActorProperty(45, APROP_RenderStyle, STYLE_Translucent);

And constructed a "timer" to remove T106 - Type 12506 - mountain skybox, just before the 10 minute cutoff.
See new sector 2807 and within.

[C3M5_C.zip](https://github.com/user-attachments/files/17039600/C3M5_C.zip)

**Comment by hawkwind3** [comment]
The actual cause for this is in BoA3.2, not gzdoom.
Do this
1. Copy boa.ipk3 from your 3.1 distro to the latest gzdoom.
2.  Overwrite skyboxview.zs from your boa 3.2 into boa 3.1 ( scripts>actors) .
3. Change [BoA.LocalServerInfo.Mod] // boa_culling=false to boa_culling=true
4. You might need to generate a new ini file.
5. Run the "new" boa>ipk3.

For me the original method for the sky model fade works, without the need for the above.
Also, the added bonus of getting back the full rain spawners and no loss in performance.
:)

**Comment by Tormentor667** [comment]
Brilliant, did you already fix it on the repo? I would like to test it :)

**Comment by hawkwind3** [comment]
No. There is more going on here. The above was just to prove that the issue is with BoA 3.2, not GZDoom.
Remember, the above test still holds all the other BoA 3.1 code. The coders/programmers need to get to the bottom of this.

**Comment by Tormentor667** [comment]
Summoning @Talon1024 @AFADoomer @Username-N00b-is-not-available here as well, maybe they can solve this issue somehow

**Comment by Tormentor667** [comment]
Thank you @hawkwind3
