### ISSUE TITLE
wrong texture

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1459]
In c2m0_a, this texture is wrong.

![Screenshot_Doom_20240913_160043](https://github.com/user-attachments/assets/ba193404-d999-480d-b0f0-914e16e926d2)

This one is correct.

![Screenshot_Doom_20240913_160035](https://github.com/user-attachments/assets/a1264704-bbfd-4b9d-b170-256d43f77add)

**Comment by hawkwind3** [comment]
Thanks for reporting. Was my mistake. Fixed.
