### ISSUE TITLE
different kills

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1460]
When doing a stealth mission, for example c2m6_b, the knife kills can still be different.

These are stealth

![Screenshot_Doom_20240915_004847](https://github.com/user-attachments/assets/45033a4e-6cf5-4ff1-905b-234fad471578)
![Screenshot_Doom_20240915_005537](https://github.com/user-attachments/assets/d0863949-bd8d-477f-93b9-3bf20d5ba2b8)
![Screenshot_Doom_20240915_005503](https://github.com/user-attachments/assets/c1aefbed-ee58-43e6-bafe-8a99be338d36)

But on the other toilet, these are critical hits...

![Screenshot_Doom_20240915_004917](https://github.com/user-attachments/assets/1b65de1c-d3fa-47d6-9a27-27504c8b929e)

So why are these different  ?

**Comment by hawkwind3** [comment]
I think I know why.

The 3 that are stealth kills are classified as sneak-friendly enemies, whereas the one that gives the critical hit is not.
I'll leave this for others to confirm.

**Comment by Tormentor667** [comment]
Yes that’s probably the reason
