### ISSUE TITLE
path blocker

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1462]
In c2m6_a, this object is a little too big and blocks your path a little.

![Screenshot_Doom_20240915_005130](https://github.com/user-attachments/assets/e3121547-ae35-4753-ad01-cc8cb66f6c1d)

![Screenshot_Doom_20240915_005138](https://github.com/user-attachments/assets/4e8cd59f-e036-4b10-897e-fe650953c340)

**Comment by hawkwind3** [comment]
Technically, not a bug. But you raise a good point. The trolleys have a radius of 16 ( 32 wide ) which IMO is too much for a trolley. I will reduce its radius.

**Comment by hawkwind3** [comment]
Addressed. Now radius is 10 ( 20 wide ).
