### ISSUE TITLE
switch doesn't always open door

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1463]
In c2m0_b this switch sometimes needs to be activated 2x before the door opens.

![Screenshot_Doom_20240914_133155](https://github.com/user-attachments/assets/9747742f-0cdd-405d-b301-ee3629f070d8)

**Comment by hawkwind3** [comment]
Not a bug per-se.

This is the script responsible ...

script 401 (int door_id)
{
	floor_lowerbyvalue(door_id, 12, 64);
	ceiling_raisebyvalue(door_id, 12, 64);
	delay(140);
	floor_raisebyvalue(door_id, 12, 64);
	ceiling_lowerbyvalue(door_id, 12, 64);
	delay(70);

Notice that one of them has a delay of 140. This equates to 4 seconds. So it is a timing thing. Don't switch them too quickly.
The devs may wish to change this. So I will leave this one open.

**Comment by x3003** [comment]
All other doors open correctly, this is the only one where you have to presss the switch twice most of the time.

**Comment by hawkwind3** [comment]
There is a similar door nearby. For me, both doors perform the same, even in BoA 3.1.  I'll leave this open for others to comment on.

**Comment by x3003** [comment]
Try running from the previous door to this one, maybe it needs a delaytime (from the prev to this one) to work.

**Comment by hawkwind3** [comment]
Fixed. Both doors were sharing the same script. And a slight change to the delay. After closed, should now only take one use to open.
