### ISSUE TITLE
lamps too low

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1464]
In c2m0_a, these lamps are a little low, could someone place them a little higher ?

![Screenshot_Doom_20240913_160202](https://github.com/user-attachments/assets/cb16714f-cfa2-42bb-8871-1ef2912faafd)

These look correct, although the ceiling is a bit higher.

![Screenshot_Doom_20240913_160537](https://github.com/user-attachments/assets/3244b51d-ce28-431c-88df-053619477a94)

**Comment by hawkwind3** [comment]
Fixed.
