### ISSUE TITLE
ufo rings gone

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1465]
In c2m5_b, when you launch the ufo, the green rings are almost completely gone

![Screenshot_Doom_20240920_162742](https://github.com/user-attachments/assets/a718d910-6e94-49ac-8747-650fcdebf948)

as it should looks something like this:

![boa_rings](https://github.com/user-attachments/assets/66e9bb9a-253b-47ba-ad68-a11d3ab9e833)

**Comment by hawkwind3** [comment]
Confirmed. Not a map issue since I compared the BoA3.1 map with the current BOA 3.2 GZDooM 4.13 pre.

**Comment by hawkwind3** [comment]
I've done some more testing on this. I can state that this issue/bug came with GZDoom 4.12.2. Not an issue with GZDoom 4.12.1
Interestingly, the rain in that ufo hanger works great with GZDoom 4.12.1 too but is non-existent in GZDoom 4.12.2. Issue #1423 .
I'm guessing the two are related.

**Comment by Tormentor667** [comment]
So what do we need to change here in general?

**Comment by hawkwind3** [comment]
That's the question. One for the coders/programmers ...

**Comment by Tormentor667** [comment]
Summoning @Talon1024 @AFADoomer @Username-N00b-is-not-available  , maybe they can solve this issue somehow

**Comment by hawkwind3** [comment]
Try this ...
set boa_culling=true 
and
boa_debugculling=true

for both Boa 3.1 and BoA 3.2.

Notice the difference with the displayed messages. Way more messages with BoA 3.2 ( and the performance hit ). Notice the mention of chunks in BoA 3.2 messages. Could this refer to chunkhandler.zs ? This file is not in BoA 3.1.

Should not  boa_culling=true improve performance ? Quite the opposite for me.

Hope this helps.

**Comment by hawkwind3** [comment]
Fixed due to recent changes. Tested TEST_LDR.wad to confirm.
