### ISSUE TITLE
area blocked

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1466]
In c2m5_b, you can't go into this little area, as it's blocked

![Screenshot_Doom_20240920_155847](https://github.com/user-attachments/assets/cab04e4a-0eb0-4dd1-b448-4714f7eb06ec)

But you can go here

![Screenshot_Doom_20240920_155854](https://github.com/user-attachments/assets/66af79a2-fb3e-476f-8242-d8d5dcba5d9b)

**Comment by hawkwind3** [comment]
Addressed.
