### ISSUE TITLE
hidden question mark

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1468]
In c2m5_a, this question mark is quite hidden.

![Screenshot_Doom_20240920_134240](https://github.com/user-attachments/assets/57f4baa5-6547-4e0a-901d-dfd8032db514)

**Comment by hawkwind3** [comment]
I don't think it is hidden at all. Quite visible I would say.

**Comment by x3003** [comment]
From the other side, it's also hidden inside the bush ;)

**Comment by hawkwind3** [comment]
My apologies. I completely misread the issue. I thought you were referring to the paper and not the question mark. I should have read more carefully. Anyway, fixed. I just changed to a smaller bush.
