### ISSUE TITLE
vulcano not rendered correctly

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1469]
In c2m6_c, this vulcano doesn't seems to look good on a lot of machines, usually [?] with better gpu''s than mine.

On my system it looks like:

![Screenshot_Doom_20240915_111413](https://github.com/user-attachments/assets/f0c71a36-37ad-4478-895e-6f2d824a3f91)

On other machines it looks like:

![vulcano](https://github.com/user-attachments/assets/6d49136f-5b52-4ef9-858b-cacaa0fde914)

Could this be fixed somehow ?

**Comment by hawkwind3** [comment]
I get the same as your first pic, so no idea as to why another system would get different.

**Comment by hawkwind3** [comment]
I seem to recall that this was an issue some time ago, that got fixed. The machine that gives you the problem, are you running the latest BoA dev build with the latest gzdoom ?

**Comment by x3003** [comment]
I don't have that problem, but a lot of tubers (running 3.1 have). If it got fixed (for sure) you can close this one.

**Comment by hawkwind3** [comment]
Finally tracked down the old issue - See closed issue #948

**Comment by Talon1024** [comment]
I think this is happening because the volcano was separated into its own sector, supposedly to fix a performance issue. I don't know if that actually helped with anything, but I think it would be better to re-unite the volcano sector with the others, and convert the volcano to a 3D model.

**Comment by Tormentor667** [comment]
> I think this is happening because the volcano was separated into its own sector, supposedly to fix a performance issue. I don't know if that actually helped with anything, but I think it would be better to re-unite the volcano sector with the others, and convert the volcano to a 3D model.

The performance issue is not because of the volcano but all the visible sectors at once behind the volcano. Merging the sectors will drop down the performance again massively
