### ISSUE TITLE
C2M5_B activated mecha issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1470]
C2M5_B - When the unoccupied mecha is activated, there are chevrons under it.
They do not appear in BoA 3.1 Pic attached.
![chevrons](https://github.com/user-attachments/assets/18fa169f-122c-45d0-a153-afc110ee537f)

UPDATE - Not just this mecha, but all the mechas have the red chevrons.
UPDATE 2 - This might be an issue with all the "bosses".  Mengele in C3M1_B has those chevrons as well. Again, not an issue with BoA 3.1.

**Comment by Tormentor667** [comment]
They should be excluded in general for that enemy.

**Comment by hawkwind3** [comment]
Fixed for all mechas.
