### ISSUE TITLE
kill prisoner

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1471]
In c3m1_a, you can actually kill this poor guy.

![Screenshot_Doom_20240929_112751](https://github.com/user-attachments/assets/405d42c5-1629-46ca-8f66-7ecec5ea072b)

**Comment by x3003** [comment]
It's still possible to kill him.

**Comment by hawkwind3** [comment]
Actually, many of the prisoners are "shootable". Using UBD, under Concentration Camp (BOA) > Static, you will see many shootable prisoners. For grins, kick the guy sitting on the outhouse toilet ...
