### ISSUE TITLE
Poison icon shown

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1472]
In c3m1_a, you can try the alternative route, but when shot you might get the death/poison icon shown. Not always, sometimes.

![Screenshot_Doom_20240929_112019](https://github.com/user-attachments/assets/fdeb995c-006a-4cb8-b64c-db0303eb203b)

![Screenshot_Doom_20240929_111857](https://github.com/user-attachments/assets/b4677b7c-f756-4428-9da0-b0083f7c06b6)

**Comment by hawkwind3** [comment]
I think that is correct. Dr.Scabbs Jr throws purple needles at you. Same with BoA 3.1. I haven't tested, but I'm guessing all Dr.Schabbs attacks would be the same.
