### ISSUE TITLE
flame goes out early

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1473]
When using the blade, the fire goes out because it's on a timer. But this timer is measured from when the fire gets activated.
Sometimes you use it in battle, you wait for a second and the fire goes out, very annoying when you have to start the fire again when you've just used it.
Why not make it so the the timer responds to 1) When it's activated and 2) When it's last been used.

**Comment by Tormentor667** [comment]
That's a good idea, seconded.

**Comment by hawkwind3** [comment]
thirded.

**Comment by hawkwind3** [comment]
@Talon1024 - The changed timer works great for me. Thanks. Just wondering ... Is there a chance that when you enable the flame, that it only affects health, and not armour ?

**Comment by Talon1024** [comment]
Fixed in e9beea72cf82f03048419afeb6b586d2b9fe5cf4, I think.
