### ISSUE TITLE
Barrels have different sizes ingame (which is wrong) but same sizes in map editor (which is correct)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1476]
![grafik](https://github.com/user-attachments/assets/37f095b8-168e-44f6-b801-47acda3eb991)

![grafik](https://github.com/user-attachments/assets/dac7c102-9f84-4b10-ba55-6ebaa63c827d)

**Comment by hawkwind3** [comment]
Found the cause ...

This has been added to obstacles.zs since BoA 3.1 ...

class FuelDrumSpawner : RandomSpawner
{
	Default
	{
		//$Category Models (BoA)/Obstacles
		//$Title Fuel Drum
		//$Color 3
	}

	override Name ChooseSpawn()
	{
		double sidePitch = pitch % 180;
		double sideRoll = roll % 180;
		bool onSidePitch = (
			(sidePitch >= 88 && sidePitch <= 92) ||
			(sidePitch >= -92 && sidePitch <= -88));
		bool onSideRoll = (
			(sideRoll >= 88 && sideRoll <= 92) ||
			(sideRoll >= -92 && sideRoll <= -88));
		// 90 degrees with 2 degrees for error
		if (boa_debugbarrelspawns && (onSidePitch || onSideRoll) && Pos.Z > floorz)
		{
			Console.Printf("Pitch: %.3f, Roll: %.3f, floorz difference: %.3f, Scale: %.3f %.3f, Position: %.3f %.3f %.3f", Pitch, Roll, Pos.Z - floorz, Scale, Pos);
		}
		if (onSidePitch || onSideRoll)
		{
			if (onSideRoll)
			{
				double angleToMoveBy = Normalize180(Roll) < 0 ? Angle + 90 : Angle - 90;
				SetXYZ(Vec3Angle(24, angleToMoveBy));
			}
			else if (onSidePitch)
			{
				SetXYZ(Vec3Angle(-12, Angle));
			}
			if (onSidePitch)
			{
				angle += 90;
			}
			pitch = 0;
			roll = 0;
			AddZ(-17);
			return 'FuelDrumSide';
		}
		return 'FuelDrum';
	}
}

class FuelDrumFixSpawner : FuelDrumSpawner
{
	Default
	{
		//$Title Fuel Drum, non-solid for players
	}

	override Name ChooseSpawn()
	{
		Name spawn = Super.ChooseSpawn();
		if (spawn == 'FuelDrum')
		{
			return 'FuelDrumFix';
		}
		return spawn;
	}
}
Interesting though, is that scaling is not affected.

**Comment by hawkwind3** [comment]
Neither do I. I'm not a coder/programmer.

https://github.com/Realm667/WolfenDoom/commits/master/scripts/decorate/models/obstacles.zs

Calling @Talon1024 and @Ozynandias81 for further comment.

**Comment by Talon1024** [comment]
What that code does is spawn a `FuelDrumSide` (barrel laying down) if either the pitch or roll is 90 degrees.

@Ozymandias81 wanted mappers to use that actor instead of changing the roll or pitch of a regular barrel to make it look like it is laying on its side, so I figured I could write code that does it automatically, instead of having to go through every map and fixing such barrels manually.
