### ISSUE TITLE
Rain not working when boa_culling=true, but working when false.

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1479]
Noticed in C3M1_A and C2M1. Interestingly, snow works no matter if it's true or false.

**Comment by hawkwind3** [comment]
Yes. I basically mentioned this in closed issue #1423

**Comment by x3003** [comment]
Good catch. The other code can't work if it's returned in the very first line.

**Comment by hawkwind3** [comment]
the addition at line 163 for Particlehandler.zs ( return 0; ) ?.  Might be a moot point now. Rain works great again.

**Comment by x3003** [comment]
Talon1024 also rewrote part of the rain code, now it should even work better.

**Comment by Tormentor667** [comment]
So I guess this can be closed, right?

**Comment by hawkwind3** [comment]
I think so.
