### ISSUE TITLE
Trees and similar actors invisible in cutscenes if boa_culling=true

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1480]
With boa_culling=true:
![grafik](https://github.com/user-attachments/assets/5c5f6d83-b037-4805-8863-822a7bbf3ea6)

With boa_culling=false (correct):
![grafik](https://github.com/user-attachments/assets/e229aeff-8798-4893-8eec-ebdcbdc64d3e)

**Comment by hawkwind3** [comment]
Yes. I should have mentioned this earlier. I suspect it has something to to with the constantly appearing/disappearing trees at the start of this level. Just look at the trees, look away and then look back at them again. I also noticed that this cutscene would have jerky playback when boa_culling+true.

**Comment by hawkwind3** [comment]
This  has been fixed in recent changes.
