### ISSUE TITLE
enemy soldiers won't animate anymore when boa_culling=true

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1481]
For example in c1m2

These 2 in the back are static:

![Screenshot_Doom_20241019_124510](https://github.com/user-attachments/assets/a4b6d6ac-15d0-4977-9723-c8d6a5f8edef)

Also these 4:

![Screenshot_Doom_20241019_124524](https://github.com/user-attachments/assets/f5f55fc9-9077-4896-9d5c-0d3bfb1aef18)

And these 3:

![Screenshot_Doom_20241019_123813](https://github.com/user-attachments/assets/b4025972-1754-4cd2-8b0f-ce1f528dfb40)

**Comment by x3003** [comment]
It seems that with recent changes of the rain, not only we have some rain, but the soldiers also work again.

**Comment by hawkwind3** [comment]
I could not reproduce, even before and since the rain changes.

**Comment by x3003** [comment]
Seems fixed.
