### ISSUE TITLE
Weird messages when starting c3m5_a & c3m6_b

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1484]
With the latest boa & gzdoom, going to c3m5_a or c3m6_b, 'you'll get some weird text. The game runs fine afterwards.

![Screenshot_Doom_20241022_232524](https://github.com/user-attachments/assets/09b132fa-6c05-4323-9cd7-d09bfca6f1f3)

![Screenshot_Doom_20241022_233603](https://github.com/user-attachments/assets/34ba51fd-1354-4896-944b-78a5bbaea7b4)

**Comment by hawkwind3** [comment]
Benign. Fixed. Just GZDoom mapping warnings. Compare the front tunnel of the moving train with BoA 3.1 ...  ;)
