### ISSUE TITLE
5 player 1's in INTERMAP

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1487]
As the title says. I'm guessing the extra 4 are superfluous but I thought to ask
here to make sure I can delete the extra ones - keeping T36 of course.

**Comment by Talon1024** [comment]
There are a bunch of starting points in INTERMAP. After the chapter 3 intro sequence, the player starts on the bed in BJ's bedroom. Also, the player can start in front of the NES in Gutenberg's lab after beating one of the Commander Keen secret levels, or in James Ryan's room after beating his "secret" mission (C3M0_B).

**Comment by Tormentor667** [comment]
Exactly, not a bug.

**Comment by hawkwind3** [comment]
Yeah. Sorry about that guys. I should have realised. I just forgot ...
