### ISSUE TITLE
seller not selling metal detector

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1490]
Just before going into c3m4, i've noticed an issue with this seller.
He's not selling the metal detector although you could use it in the next level. Maybe someone can add it ?

![Screenshot_Doom_20241026_142236](https://github.com/user-attachments/assets/e6efd76e-31cf-41ae-8b28-80bef1ee695f)

**Comment by hawkwind3** [comment]
Just realised yesterday that there is one in the level to find. Be careful though ...

**Comment by x3003** [comment]
You need it right at the start of the level, else you can't get through the 2 minefields, of which 1 holds the switch which opens the secret door.

**Comment by hawkwind3** [comment]
No. You actually can pick it up near the start. Just a bit tricky though. Do you know where it is ? Do you need a hint ?

**Comment by x3003** [comment]
1) There's a switch in the forrest, in the minefield. This opens the secret door.  Hard to get w/o detector.
2) There's some treasure near the start, in a trench. Impossible to get w/o a detector.

Dunno where it is. If i don't know, how would a normal player know ?

**Comment by hawkwind3** [comment]
> There's a switch in the forrest, in the minefield. This opens the secret door. Hard to get w/o detector.

Please post a screenshot with coordinates. For the life of me, I cannot see the switch. I will then amend the map accordingly.

>There's some treasure near the start, in a trench. Impossible to get w/o a detector

Yes. And in BoA 3.1 that is where the mine detector is ! Just very hard to see - "camouflaged". That is why I moved to to be easier to see.
