### ISSUE TITLE
low clouds

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1493]
In c3m6_b, these clouds are too low. Only when you finished the game.

![Screenshot_Doom_20241101_161304](https://github.com/user-attachments/assets/b63a7b7a-b986-4c71-9bdd-16fb4aad722b)

**Comment by hawkwind3** [comment]
That's a weird one. Actually not clouds, but what are called "snowpile large". Should be rendered on the floor. I have no idea why they are doing that.

**Comment by Tormentor667** [comment]
These are not clouds but snowpiles :D Are they offset already at the beginning of the map or is this happening during playing the map?

**Comment by hawkwind3** [comment]
Confirmed.

To reproduce ...

Try this ...

  1.  Fire up c3m6_b.
  2. Open up the console and type notarget.
  3. Using the console again, type warp -5151 2398.
  4.  Open the console and type kill monsters.
  5.  The snowpiles jump up higher.
    Why ? I have no idea.

If the cause is not found they could be deleted.

**Comment by hawkwind3** [comment]
Could someone tell me where Snowpile1 is in scripts ? I would like to reduce the radius.
Currently, on Hitlers death the snowpile jumps to the floor height of sectors 3233.

**Comment by Talon1024** [comment]
`Snowpile1` is in `scripts/decorate/props/walldecs.zs`, line 302.

https://github.com/Realm667/WolfenDoom/blob/129a051bf7655176b189895fcbf05d8a0e4de164/scripts/decorate/props/walldecs.zs#L302-L314

Do those snow piles have TIDs? I can't think of any other reason why this would happen, off the top of my head.
