### ISSUE TITLE
door still open

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1494]
In c3m6_b, when finished. If this door was kicked, it's still open instead of moved.

![Screenshot_Doom_20241101_161321](https://github.com/user-attachments/assets/5747afcd-bc3a-4fd5-8cb9-e083a88f1d99)

**Comment by hawkwind3** [comment]
Good catch ! 

Relates to this in the script 

//Block other lines
	SetLineBlocking(432, BLOCK_EVERYTHING);
	TranslucentLine(432, 255, 0);

You would get the same with the other nearby door if kicked open too.

Issue is, it that there are many lines tagged 432 ? I thought of making just those 2 doors sliding doors, but still worry about the other doors in this map.

Developer input please ...

**Comment by Tormentor667** [comment]
I think I know what's happening here. Even though the line befor these doors are blocking and visible through the script, the kicking seems to be able to reach the doors anyway.

The doors should simply not be able to be triggered anymore at all so adding a "SetLineSpecial" that removes the poly action in the same moment as the lines get blocking and visible should do the job.

**Comment by hawkwind3** [comment]
More on this ...

I previously stated ...

You would get the same with the other nearby door if kicked open too.

I was wrong. It seems to only affect poly sector 5619.

Try this ...

1. Fire up c3m6_b
2. Open up the console and type no
3. Using the console again, type warp -6537 3309.
4.  Kick open the 2 nearby brown doors.
5. Open the console and type kill monsters.
You should see polydoor sector 5625 disappear. Poly sector should disappear as well but doesn't.
Why ? I have no idea.

Here is the full script code for this ...

//Block other lines
	SetLineBlocking(432, BLOCK_EVERYTHING);
	TranslucentLine(432, 255, 0);

	// Move all of the polyobj doors to (0, 0) to get them out of the way
	// just in case they were kicked/stuck open and would stick through
	// the blocking lines and grey door textures
	Polyobj_OR_MoveTo(123, 16384, 0, 0);
	Polyobj_OR_MoveTo(13, 16384, 0, 0);
	Polyobj_OR_MoveTo(217, 16384, 0, 0);
	Polyobj_OR_MoveTo(222, 16384, 0, 0);
	Polyobj_OR_MoveTo(7, 16384, 0, 0);
	Polyobj_OR_MoveTo(87, 16384, 0, 0);
	Polyobj_OR_MoveTo(14, 16384, 0, 0);
	Polyobj_OR_MoveTo(82, 16384, 0, 0);

The one that mentions angle 87 is not moving. The nearby one with the angle 82 does move/disappear.

Are we missing something ?

This is the wh

**Comment by hawkwind3** [comment]
UPDATE ...

@Tormentor667  you gave me an idea that works.

What I did was
Script added ...
SetLineBlocking(589, BLOCK_NOTHING);
Map added ...
Linedefs 19195, 19206, 19192 and 19197 tagged 589.

Will need to do the same for the door attached to T533.

**Comment by Tormentor667** [comment]
Thanks for fixing! :)
