### ISSUE TITLE
some clipping

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1497]
Some clipping.

![Screenshot_Doom_20241027_235056](https://github.com/user-attachments/assets/13256cc1-6465-4c9d-b27e-9abd3c1e1d22)
![Screenshot_Doom_20241027_235046](https://github.com/user-attachments/assets/865f34ec-2cea-4122-886a-c2cb9acd76ee)
![Screenshot_Doom_20241027_234540](https://github.com/user-attachments/assets/bd32b38e-afdc-4b99-ac2f-70c9887b5c71)
![Screenshot_Doom_20241027_234516](https://github.com/user-attachments/assets/4b64d2c1-959e-4568-8d64-8db60294d4a0)

**Comment by Tormentor667** [comment]
As the rocks are generated randomly and GZDoom only makes cube boxes for collision, this won't be fixable at all. It's an engine limitation.
