### ISSUE TITLE
C2M6_B possible softlock

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1499]
I found myself at sector 4717, and jumped down into the water to get the gold at sector  366. I had not yet picked up the red key at sector 1035. I could not proceed - unless I'm missing something.

**Comment by x3003** [comment]
Yes, you're screwed.  When you use the switch that opens the shark doors, the first door opens, but not the second one.
Maybe connect that one too to that switch ?!

**Comment by hawkwind3** [comment]
Your suggestion will only work if door sector 4860 opens as well. I have an idea. Watch this space ...

**Comment by x3003** [comment]
These 2 doors remain closed, so you can't go back to pick up the red key.

![Screenshot_Doom_20241120_234411](https://github.com/user-attachments/assets/6b61fa4a-4d10-44d0-a24f-3cfdb0a5a89d)
![Screenshot_Doom_20241120_234431](https://github.com/user-attachments/assets/fd39ff81-fb35-4042-a9d9-1d0752d02021)

**Comment by hawkwind3** [comment]
Good catch ! Hopefully fixed now. I forgot to consider going into the tank from the first bridge.
