### ISSUE TITLE
Cannot pick up the Tyrfing - Firebrand - on killing the Angel of Death C2M6_C

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1501]
As above. Is the player supposed to pick up the sword on the death of the AoD ?
It does get delivered to HQ for Gutenberg to study.

**Comment by Tormentor667** [comment]
Yes the player is supposed to pick it up. Did you cheat weapons before?

**Comment by hawkwind3** [comment]
Yeah ! That's it. Sorry.

**Comment by Tormentor667** [comment]
Maybe we should add an +ALWAYSPICKUP flag to the sword instead of breaking the flow when people cheat?

**Comment by hawkwind3** [comment]
I'm happy either way. But if this is done, for consistency should be done for all weapons

**Comment by Tormentor667** [comment]
It already is because all the other weapons are considered as ammo in case you already have the weapon. It just doesn't work for the melee weapon.

**Comment by hawkwind3** [comment]
Yes. You are right. I forgot. The Tyrfing is both melee and fires "missiles".
