### ISSUE TITLE
flame thrower indicator

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1502]
Maybe an idea to make the red flame thrower indicator dark red instead of bright when its's empty, so there's no confusion if it's empty or not.

![Screenshot_Doom_20241119_222418](https://github.com/user-attachments/assets/333af217-1905-4b50-aa1f-339a950b3fc3)
![Screenshot_Doom_20241119_222428](https://github.com/user-attachments/assets/c10245d7-d56e-493a-aab1-3457ddc60c2b)

**Comment by hawkwind3** [comment]
Not sure what you mean. When the canister is empty and reloading, the red light is off.

**Comment by hawkwind3** [comment]
Good point. Yes. If a canister is not loaded - and the top pic should not show a canister loaded - the red light should be out. Maybe someone can address this.

**Comment by Tormentor667** [comment]
Good suggestion indeed.
