### ISSUE TITLE
Astrostein grenades render into the floor

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#1505]
Astrostein grenades render 7mu into the floor.

![grenade in floor](https://github.com/user-attachments/assets/ef214351-0c7d-44dc-a209-22a48187d3cd)
![grenade in floor bounding box](https://github.com/user-attachments/assets/bd9d6cf6-0812-40cf-9654-a2f33413102d)

Ignore the position of the grenade in UDB. Just me showing the grenade below the bounding box.

Update ... Display>Hardware Renderer>Adjust Sprite Clipping set to either Smart/Smarter/Always does work, but really should be fixed properly.

**Comment by Tormentor667** [comment]
It's an engine-issue, isn't it?

**Comment by hawkwind3** [comment]
No. A sprite offset issue. See Slade screenshots. One before and one after Y offset fix.

![7 pixels below floor_before](https://github.com/user-attachments/assets/779ad70b-c433-48dc-b9fc-d370dc0a553f)

![render on floor _after](https://github.com/user-attachments/assets/8ede5fad-492f-4700-8416-02e4094806c6)

I have committed the fix. Should be ok. If ok with others - seems ok for me - this can be closed.
