### ISSUE TITLE
some chimney issues

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1508]
In c3m1_a there are still some chimney issues.

- There are 3 instead of the 2 needed for the furnaces. Also mentioned somewhere else.
- 2 of 3 get smoke out of them, although the furnaces are off and open.
- They don't align well, as they are set lengthwise outside and inside they are widthwise.
- Inside the building, the chimneys don't have vent holes, so the smoke can't go anywhere.

![Screenshot_Doom_20241207_122732](https://github.com/user-attachments/assets/d62eb94a-60b9-4c05-87a4-42cf8b292f19)

![Screenshot_Doom_20241207_122719](https://github.com/user-attachments/assets/49b3b69f-9910-4273-acea-5880272e7ecd)

![Screenshot_Doom_20241207_122559](https://github.com/user-attachments/assets/64d91f3e-d7b1-437a-86e3-e6e721210477)

**Comment by hawkwind3** [comment]
Did some work on this. If happy, you can close. The roof issue is still present.

**Comment by x3003** [comment]
It looks a bit better. although normally the chimneys would go through the upstairs room.
Tried to locate your issue, but not sure what you mean, looks fine to me.

**Comment by hawkwind3** [comment]
>normally the chimneys would go through the upstairs room.

True.  Try the attached. If both you and @Tormentor667  are happy, I will commit. This one has not been fully playtested.
Regarding the roof, it is quite obvious. Even your 2nd pic with the 3 chimneys shows it. Look far left on the roof.

**Comment by x3003** [comment]
It's now functional, but not pretty.

**Comment by Tormentor667** [comment]
Can you share screenshots?

**Comment by x3003** [comment]
![Screenshot_Doom_20241213_162841](https://github.com/user-attachments/assets/0522525f-7021-4f8d-895f-ba739216c48a)
![Screenshot_Doom_20241213_163211](https://github.com/user-attachments/assets/46407f31-dfdc-44db-87f9-ecbe070c94d2)
![Screenshot_Doom_20241214_092232](https://github.com/user-attachments/assets/d9e176b0-1a37-4d30-ac24-d4abcf509178)

**Comment by hawkwind3** [comment]
@x3003 - Yes, not pretty I agree.

Check this one out ...
[C3M1_A2.zip](https://github.com/user-attachments/files/18139073/C3M1_A2.zip)

**Comment by x3003** [comment]
![Screenshot_Doom_20241215_090132](https://github.com/user-attachments/assets/2df0b315-f0d0-4445-b8c4-7a292987bf6a)

**Comment by x3003** [comment]
The problem now is that the Dr can't get through. Maybe move the table a little ?

![Screenshot_Doom_20241215_120720](https://github.com/user-attachments/assets/18d74f2a-4fc9-4e05-b0db-d7868119a91e)

**Comment by hawkwind3** [comment]
I think this is my best so far. I did not need to move the table. I had already done that and didn't want to move it again. Did  a reno and knocked out part of a wall ;) .And Dr. Schabbs can now move around.

Try this ...
[C3M1_A3.zip](https://github.com/user-attachments/files/18145264/C3M1_A3.zip)

**Comment by x3003** [comment]
That works pretty good. Only now there are a few msg showing with map.

![Screenshot_Doom_20241218_234713](https://github.com/user-attachments/assets/d1b52a34-9046-4b44-b50d-cce8814956e2)

**Comment by hawkwind3** [comment]
Just me forgetting to deleted "lines used for measuring". I really should check the console more often.
OK, if @Tormentor667 is also happy with the latest map, I will commit to master - with those lines deleted.

**Comment by Tormentor667** [comment]
I am :)

**Comment by hawkwind3** [comment]
Done. With some additional refinements to the room.

**Comment by x3003** [comment]
>I really should check the console more often

Only 1 msg left when going to map c3m1_b

**Comment by hawkwind3** [comment]
Tks for reporting. Fixed.
