### ISSUE TITLE
Optional Enemy Rolling

### ISSUE THREAD

**Issue by SadCack** [Realm667/WolfenDoom#1509]
Please make enemies rolling optional. The fact that they seem to be invincible during the roll is frustrating and goes against the player's instinct to track them while shooting. It just adds more time until you can hurt them. With it being optional the players who want it can use it and players who are frustrated by it can choose not to activate it.

**Comment by Talon1024** [comment]
Enemies will not roll on skill 1 or 2.

In addition, rolling enemies are not invincible, but they take half as much damage as they normally would during the roll.
