### ISSUE TITLE
Distribute standalone release and the PK3 on GitHub Releases or similar

### ISSUE THREAD

**Issue by Calinou** [Realm667/WolfenDoom#160]
I'm maintaining a [Scoop bucket for open source and freeware games](https://github.com/Calinou/scoop-games) and I'd like to add Blade of Agony to it. However, if I'm not mistaken, the current official downloads are hosted on ModDB, which doesn't provide permanent direct download links (which Scoop requires to function).

Uploading the release artifacts on GitHub Releases or similar would make adding Blade of Agony to Scoop possible (without having to re-upload the files somewhere else). For information, GitHub Releases allows to upload files of up to 1 GB each (there is no total limit over all releases).

**Comment by Ozymandias81** [comment]
The true official webpage to get downloads are hosted on https://boa.realm667.com/, alongside with ModDB page though.
For reference, you may also check https://forum.zdoom.org/viewtopic.php?f=19&t=47801, just saying :) .
This Scoop looks pretty interesting, and concerning your requests well you can find atm only [these .zip releases, which I am sure you are aware](https://github.com/Realm667/WolfenDoom/releases), but I can't exclude that when we'll release Chapter 3, everything will be packed up and archived on Github, with Standalone .pk3 bundle.
@Tormentor667 has the last word here, so let's see what he think about doing this.

**Comment by Tormentor667** [comment]
What's wrong with the ModDB download links?

**Comment by Calinou** [comment]
> What's wrong with the ModDB download links?

As I said in my first post, the non-permanent nature of ModDB download links is problematic for automated/unattended installation methods such as Scoop.

**Comment by Tormentor667** [comment]
I am currently uploading a static download to the Realm667 page of Blade of Agony (under the "Projects" section), just check that page tomorrow and you have your link :)

**Comment by Calinou** [comment]
[Done](https://github.com/Calinou/scoop-games/commit/2029d4303c64658043ab2d9d77333987feaed451) :smiley:

**Comment by Ozymandias81** [comment]
Thank you @Calinou !!!

**Comment by Ozymandias81** [comment]
@Calinou sorry to bump you, but did you do something regarding C3 release? Is it in? Now the game is a standalone ipk3, and requires GZDoom 4.6 pre195 to run (64bit).

**Comment by Calinou** [comment]
> @Calinou sorry to bump you, but did you do something regarding C3 release? Is it in? Now the game is a [standalone ipk3](https://www.moddb.com/mods/wolfendoom-blade-of-agony/downloads/blade-of-agony-full-release-v30-standalone), with custom executable (not strictly important) and requires GZDoom 4.6 pre195 to run (64bit).

I didn't notice C3 was out, congratulations on the release :slightly_smiling_face: 

I still need a direct link (not ModDB) so the download can be initiated automatically via Scoop, though.

**Comment by Ozymandias81** [comment]
Alright, then maybe let's wait for 3.1 patch and the @Tormentor667 will give you the direct link, I guess.

**Comment by Tormentor667** [comment]
@Calinou there you go, does that work for you?

Link C3 release on Realm667: 
https://www.realm667.com/index.php?option=com_docman&view=document&alias=1135-blade-of-agony-chapter-3&category_slug=doom-wads&Itemid=424
https://www.realm667.com/index.php/en/downloads/doom-wads/1135-blade-of-agony-chapter-3/file

**Comment by Calinou** [comment]
> @Calinou there you go, does that work for you?
> 
> Link C3 release on Realm667:
> [realm667.com/index.php?option=com_docman&view=document&alias=1135-blade-of-agony-chapter-3&category_slug=doom-wads&Itemid=424](https://www.realm667.com/index.php?option=com_docman&view=document&alias=1135-blade-of-agony-chapter-3&category_slug=doom-wads&Itemid=424)
> [realm667.com/index.php/en/downloads/doom-wads/1135-blade-of-agony-chapter-3/file](https://www.realm667.com/index.php/en/downloads/doom-wads/1135-blade-of-agony-chapter-3/file)

That should do it, thanks :slightly_smiling_face:

**Comment by Ozymandias81** [comment]
Awesome! Thank you very much again @Calinou :smiley:
