### ISSUE TITLE
Proposal: INTERMAP shop enhancement

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#166]
Currently, the shop on INTERMAP is a mess, and some of the item lists are a bit too long to access with just the number keys, so I think it might be a good idea to divide the shop items into categories. For example:

Weapons:
	Grenade
	Mine
	Sten Gun
	Karabiner 98K

Armor:
	Leather Jacket
	Flak Jacket
	Heavy Armor
	Tesla Shield

Tools:
	Mine Detector
	Compass
	Adrenaline Kit
	Totale Macht

Health items:
	Vitality Serum
	Bandages
	Field Kit

**Comment by Tormentor667** [comment]
I am okay with it if you can make sure that it doesn't get even messier :) There is a lot of stuff going on through C1-C3 which change what things are accessable.

**Comment by Ozymandias81** [comment]
This idea was definitely needed and then I have decided to give it a [start](https://github.com/Realm667/WolfenDoom/commit/31b73da8911bc9b2f242e81907eb5835b6d1da1a), just test it

**Comment by Tormentor667** [comment]
Will test as soon as I am back from vacation

**Comment by Tormentor667** [comment]
So, has this already been resolved?

**Comment by Ozymandias81** [comment]
Well there are still some additional convos to add and to consider also if we want "before C3M1" shop being closed due to the fact we may break map flow.

**Comment by Tormentor667** [comment]
Can you elaborate the latter?

**Comment by Ozymandias81** [comment]
N00b wrote this on issue #188 :

> The player should probably be disallowed to carry any items to C3M1 (and therefore buy them before the map). Laz Rojas should explain that to them once more. It is possible now to go to C3M1 in a flak vest and with a handgun, not sure if this fits the story well.

**Comment by Tormentor667** [comment]
Ah, I understand. Okay then, for that reason we need to give Laz a different conversation before C3M1. I will take care of that.

**Comment by Tormentor667** [comment]
Now that the conversation for Laz is implemented, the issue can be closed.
