### ISSUE TITLE
Add license headers to script files

### ISSUE THREAD

**Issue by Calinou** [Realm667/WolfenDoom#167]
As I was fixing the [Blade of Agony Flatpak](https://github.com/flathub/com.realm667.WolfenDoom_Blade_of_Agony) to work with GZDoom 3.7, I noticed I had to patch the game to work with that GZDoom version. However, neither the original scripts nor the patched script contain any licensing information (in the form of source code headers or similar). As the Flatpak is redistributed publicly on Flathub, we'd rather not include too many files with unclear licensing information.

Please consider adding licensing headers to source files to make the legal situation clearer. It could also make sense to add such headers to other code files such as shaders. If you're unsure on the license to choose, see [Choose a License](https://choosealicense.com/) :slightly_smiling_face:

**Comment by Talon1024** [comment]
WolfenDoom: Blade of Agony is not an open source project with code or assets that can be freely re-used in other projects. The repo header and the README clearly states that the assets cannot be used without permission from the respective authors.

> License
> This repository is for development and testing purposes. Contributions are welcome, but you are NOT ALLOWED to use any un-released material for your own projects without our permission!

**Comment by Talon1024** [comment]
I reopened this because @AFADoomer wrote much of the ZScript code, and I'd like to know if he will allow other GZDoom-based projects to use any of it.

**Comment by AFADoomer** [comment]
Fair enough...  Do we have a preferred license we're already using for the ZScript files?  MIT?

I honestly don't care what people do with it, as long as they aren't claiming it's their own work...

**Comment by Tormentor667** [comment]
I‘d leave this decision totally up to you.

**Comment by Talon1024** [comment]
GZDoom is licensed under the GNU GPL, so code copied and pasted from GZDoom would be a derivative of the code in GZDoom, thus it would be licensed the GNU GPL. I suppose we could write "portions copied from GZDoom licensed under the GNU GPL v3" in the license header for such source files.

> I honestly don't care what people do with it, as long as they aren't claiming it's their own work...

I guess I'd pick the MIT license or one of the BSD licenses in that case.

**Comment by Tormentor667** [comment]
Has this been addressed in the meantime?

**Comment by Talon1024** [comment]
I'm working on it. However, I've run into a few issues:

- Who wrote scripts/libraries/DrawToHUD.txt?
- What is mk_rotation.txt licensed under? LGPL3? If not, we should remove LGPL3.txt.

**Comment by Tormentor667** [comment]
> Who wrote scripts/libraries/DrawToHUD.txt?

@AFADoomer according to the last commit

> I don't know much about the stealth system, other than that the original stealth system before AFADoomer's ZScripted version was written by MaxEd, so I don't know if it's possible to license it under MIT.

I think that @AFADoomer also rewrote the complete script to ZScrpt so afaik there is nothing based on the old code.

**Comment by AFADoomer** [comment]
Yes, DrawToHUD was me.  

mk_rotation was basically copy/pasted from the forum thread that it references in the file, with some comments removed.

The LGPL file is residual from the code that was in place before libeye was added as a library, so I think can be removed.

The stealth system was a complete rewrite, but there are some small snippets of original code that survived (only the state function calls, probably), and the underlying concept is the same as the original code.

**Comment by Tormentor667** [comment]
Anything left that needs to be sorted here or can this issue be closed? (just to keep track)

**Comment by Talon1024** [comment]
Sorry, this sort of thing takes a long time, and I'm lazy.

**Comment by Tormentor667** [comment]
So most propably @Alexander-Wilms needs to give his opinion/licensensing information abou this part here, right?

**Comment by Tormentor667** [comment]
So most propably wildweasel needs to give his opinion/licensensing information abou this part here, right? I will just post this issue for him in a pm over at ZDoom.org.

**Comment by wildweasel486** [comment]
I would _otherwise_ be okay with my work getting MIT licensed, except that I generally prefer to be asked first before my work gets used anywhere else, especially for commercial reasons. I am otherwise unsure what else to do here.

**Comment by wildweasel486** [comment]
Alright, having thought about it, perhaps it's unreasonable of me to want my code to be a "special snowflake" here and have its own license. Let's go ahead and put it under MIT. That shouldn't interfere with anything, should it?

**Comment by Tormentor667** [comment]
Thanks kindly @wildweasel486 , I think @Talon1024 can check if it works this way

**Comment by Tormentor667** [comment]
So, @Talon1024 can this be closed as of now?
