### ISSUE TITLE
How do you join this effort?

### ISSUE THREAD

**Issue by chippo1** [Realm667/WolfenDoom#174]
I've made some fixes and want to commit them. Where do you signup?

I thought my github account would work, but no ...

chippo@chippo-Aspire-V3-731:~/Downloads/git_clones/WolfenDoom$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
chippo@chippo-Aspire-V3-731:~/Downloads/git_clones/WolfenDoom$ git push
Username for 'https://github.com': chiphog@gmail.com
Password for 'https://chiphog@gmail.com@github.com': 
remote: Permission to Realm667/WolfenDoom.git denied to chippo1.
fatal: unable to access 'https://github.com/Realm667/WolfenDoom.git/': The requested URL returned error: 403

**Comment by madame-rachelle** [comment]
You must push it to a fork. Type `git push https://github.com/chippo1/WolfenDoom HEAD:master` - then visit your fork and click the [Pull Request](https://github.com/chippo1/WolfenDoom/pull/new/master) button.

This allows the team to review your changes before merging them.

**Comment by chippo1** [comment]
That seemed to work perfectly. Thank you.
