### ISSUE TITLE
Chapter 3 feedback

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#188]
Please enclose the screenshots you post into spoilers, so the issue does not become a monstrosity like #178.
---

The resolved issues have moved to 3rd post here!
---

General
---

- [x] No Cyrillic Chalkboard font usable for the Mission Summary's 'Phase' string. _[assigned to @Talon1024]_
> Added font fallback in 22fad8a2a9cf59cae4274160c7a1d291cb8980fa so that a different font gets used if the original font doesn't have all of the characters.  Not a fix, but a workaround... Maybe good enough, unless @Talon1024 is going to be doing a lot more font work - AFA (16 Dec 20)

> The work with fonts is underway, and there is a separate issue, need not to have this checkbox anymore --N00b

C3INTRO
---

C3 INTERMAP
---

C3M1_A
---
- [x] SS guards just disappear after the explosion (which is also too small for the accompanying text), lowering the killcount. _[assigned to @Talon1024]_

C3M1_B
---

C3M0_A
---

C3M2
---

- [x] Due to nature of C3M2 (constantly spawning and de-spawning enemies) it may not be possible to achieve 100% during a normal playthrough. _[assigned to @AFADoomer @Talon1024]_

> I'm not sure how much of a problem this actually is...  I haven't done a full playthrough, just checked specific spots that I thought could be problematic.  But the enemies spawned by the never-ending spawners don't count against the total kill count, and the rest are relatively standard in their placement. - AFA (14 Jan 21)

> There is no such problem anymore. --N00b

- [x] In C3M2, sometimes the invasion script (with that "Kill X more Kraut(s)") stops at 1 remaining enemy (this is actually not a recent problem). I used iddt x2 but could not find the actor. But what's more entertaining is that the label kill count starts increasing later during the map  _[assigned to @AFADoomer @Talon1024]_

> The only time I've seen this is when there was one enemy tucked away somewhere that I had missed... Though the count script should probably be stopped if you do continue playing without killing them all.  - AFA (14 Jan 21)

<details><summary>Screenshot</summary>

![Screenshot_Doom_20200131_135827](https://user-images.githubusercontent.com/59409713/73535079-ce193200-4433-11ea-852d-ed8081b7d550.png)

</details>

> Likely irreproducible. --N00b

C3M3_A
---

More to come after next playthroughs!

C3M3_B
---

C3M0_B
---

- [x] The map does not end properly (see December videos). _[assigned to @Talon1024]_

> @Tormentor667 You said that you have fixed this problem (the player cannot return to INTERMAP, they have to reload a savegame), and also the ability to escape the vault before its door closes, but here are two videos from today's build in which they can be seen again: [c3m0_b.zip](https://github.com/Realm667/WolfenDoom/files/5782613/c3m0_b.zip). For the polyobject, I suggest using a Polyobj_OR_... special. --N00b, 7 Jan 2021

C3M4
---

???

C3M5_A
---

C3M5_B
---

C3M5_C
---

C3M6_A
---

C3M6_B
---
- [x] (Added by AFADoomer - 16 Jan) How is Ascher supposed to be handled in this map?  Right now, he gets deactivated via script 46 when you cross the line at -5540, 644 (entry to the lab with Schabbs Jrs and Zombie Butcher), but the dialogue gives no indication as to why, so he just stands there stupidly and he never goes active again.  I think he originally was deactivated via script 44 - the dialogue line there makes more sense - but I can't find anywhere in the map that calls that script.  Rather than fully deactivating him, I can set him to properly stay in place (but still respond if shot or if he sees an enemy), but it would make more sense to do this later in the map, after the player opens the big all-keys door (and that wouldn't require changing the LANGUAGE strings).

**Comment by Tormentor667** [comment]
Awesome work on the feedback. Currently I am focusing on writing the dialogues between C3M2 and C3M3 so maybe Virg can concentrate on the maps.

By the way, do you want to join the team and help fixing issues directly? That would make things easier in a lot of cases :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667: Thank you!
If by joining the team you mean membership of https://github.com/Realm667, I definitely won't refuse. So, then I'll be able to edit comments of other members and make direct contributions to master branch without any PR's? Yes, that'll definitely make things easier for me.

BTW about to make a PR on lifts.

**Comment by Tormentor667** [comment]
Exactly. I will add you in a few minutes :) What do you mean with PR?

**Comment by Username-N00b-is-not-available** [comment]
So, what's the team's opinion on the gold count in C3 (if you have not read my statistics post, here it is: https://github.com/Realm667/WolfenDoom/issues/178#issuecomment-600817460)?
Also, can we add more gold also to C1 and C2? I think that it will only benefit the maps if the new gold is thoroughly hidden or 'protected' by puzzles of some sorts. I'm thinking about:

- secret safes in cabinets, which can be uncovered by moving some bookcases;
- gold immured in bricks;
- more obscure ones, like a key combination for a deposit box in the lobby of the bank in C1M5, which is hidden somewhere in also-French C1M2 (do you remember that Stronghold had such a system for opening a secret level? You had to flip a switch on some later map and write down the key it generates).

This will be useful for players who experience a sudden difficulty increase, so they can spend more gold on HP and other items in the shop; they will just have to explore a bit more.

I'm asking this to know if I should think about it further and possibly implement it or just drop the idea.

It would also be more convenient for the player if the spies had some distinct greeting animations, for example, like [this](https://github.com/Realm667/WolfenDoom/blob/master/sprites/monsters/npcs/DARSP0.png) or [this](https://github.com/Realm667/WolfenDoom/blob/master/sprites/misc/soldiers/FIB1U0.png). It may be a bit silly, but it may help distinguishing them from actual enemies. This is a request, I will most probably drown in sprites if I try to do it by myself.

**Comment by Tormentor667** [comment]
I am okay with adding a lot more gold to C3 (currently it's simply not playtested yet) and I am also okay with adding _some more_ gold to C1 and C2 as I agree if you say these maps benefit from that.

I am also okay when it comes to the placement of secret safes in cabinets, moving bookcases, gold in bricks, but I'd really avoid secrets across several maps. The mod currently is already so packed with features and stuff you need to remember, so we need to avoid these things.

One good example for a secret is in C1M1 where you hit a switch on a desk, a image on the wall opens and reveals a secret. Such things are definitely appreciated. Feel free to implement 1-2 examples that I can test before you go over all maps :) 

Regarding the distinctive animation, I'd avoid that as it would mean a lot of planning and sprite work. Instead I like the way it is currently implemented but maybe AFA has another idea of making spies more obviously spies before you are too fast with shooting them @AFADoomer

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667:

> The mod currently is already so packed with features and stuff you need to remember

Do you mean here 'the players need to remember' or 'the developers need to remember'? If it is the first, then, to be honest, I cannot remember any at all (if we are not talking about the basic gameplay mechanics or story, of course). Also, the secrets will not be mandatory at all, I doubt that will lead to any frustration among players. Anyway, you have the last word on this.

I plan to add around 2000 gold to C3 so that the effective total becomes around 2800 (for comparison, maxing the health in C3 costs 1500, and there are some expensive items in the shop). Maybe adding 100 gold into C1 (spreading in some secrets across M3, for example) and 250 for C2 (mostly M2 and M5_A, but also a bit in M4) would be enough.

Yeah, the hidden key in the officer's room also was in my thoughts when I was writing the previous post.

**Comment by Tormentor667** [comment]
I actually mean 'the players need to remember'. Just check this page, it lists all the new features in Blade of Agony from a gameplay point of view. Now add the mission objectives as well and you are loaded with information to think about when playing the mod.

Link: https://boa.realm667.com/index.php/hints

**Comment by Username-N00b-is-not-available** [comment]
This message is reserved for new secrets. Please edit this message if you have comments.

- The first one is placed in C1M3 (in the zip archive) on (6064, 392, 128). It is a 25-coin chest half-submerged into dirt (made using a 3dfloor), you have to 'dig it out' with a shovel found on the map.

[C1M3.zip](https://github.com/Realm667/WolfenDoom/files/4381659/C1M3.zip)

More coming later.

**Comment by Tormentor667** [comment]
I like it, just improved it a bit and committed it.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667: are there any possible ways to increase the performance of the level editor (especially in visual mode)? I am using UDB. I had to decrease view distance to 1000mp, but even this way I get severe lags every couple of seconds in the visual mode. I'd rather not use it, but it makes offsetting the textures more difficult. Also, BoA's resources load for around 1.5 minutes. Could you suggest anything on this?

**Comment by Username-N00b-is-not-available** [comment]
I'll try to play through C3 once again on commit https://github.com/Realm667/WolfenDoom/commit/ec9f61001208ae91c83ab386e0e401450b1bb3fb, the post will be updated.

**Comment by Tormentor667** [comment]
Fixed a lot of issues and uploaded the coresponding maps with today's commit.

**Comment by Ozymandias81** [comment]
I am fixing c3m3_A windows, and later I guess buildings will be replaced with models as agreed on team chat.

**Comment by Tormentor667** [comment]
> SS guards just disappear after the explosion (which is also too small for the accompanying text), lowering the killcount.

@Username-N00b-is-not-available would it make sense to first freeze the enemies, then fade them out (scriptwise) and then kill them and a tic later remove them? Or what would be a good solution for that?

> Due to nature of C3M2 (constantly spawning and de-spawning enemies) it may not be possible to achieve 100% during a normal playthrough.

@Username-N00b-is-not-available what could be changed here? The spawning and despawning is important for the map to work as it works.

> It is possible to play the map using 'brute force' (this way Stierlitz's scripted messages make little sense).

@Username-N00b-is-not-available ideas on how to avoid the bruteforcing technique?

> Zyklonstein and Zombie Butcher have too much health, and killing them yields almost nothing. There is no reason to waste ammo on them, as in the complex layout the player can run away and hide easily.

@Ozymandias81 I'd suggest making them drop more souls (Zyklonstein 100 souls, Zombiebutcher 50 souls), these open secrets in the upcoming maps. Can you take care f that?

> Mengele and Morell fights (especially the latter) could be made more fun to play through by weakening their instakill attacks and giving them large area denial attacks which slowly chip through the player health (2–3hp/s, like on a damaging floor), so the player has to kill them ASAP instead of taking potshots at them from cover.

@Username-N00b-is-not-available do you think you can take care of that? I'd be happy to see this in action for the Mengele battle (the player could avoid the floor damage by jumping on tables). For Morell I am not sure if the same approach would work, we need something different here.

> C3M5_B has some secrets with missing moving-block polyobjects.

@Username-N00b-is-not-available can you elaborate this a bit where the missing polyobjects are?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 
1. Increase their speed (threefold?), add +FRIGHTENED and execute Thing_SetGoal on them so they run out of main gates over a predefined path and are killed out of player sight.
2. Just stopping the scripts from spawning enemies after the bombers' arrival would be enough IMO.
3. Make the alarms non-deactivatable and affecting the whole building?
5. The doctors have been rebalanced since the time I wrote this complaint, these fights are much more enjoyable now.
6. AFAIK some of them were also fixed after my mention, but one or two of them remain missing; I sadly don't have access to the editor now, you can try to search for sector effect 1024 and find out which ones do not have start spots, or have problems with setup, etc. There were 4 secrets total IIRC. Also you can get onto the conveyor belt in the airport and get instantly teleported to the other side of it (use a player-blocking line there).

**Comment by Talon1024** [comment]
Speaking of Chapter 3 feedback, how the HECK am I supposed to get the key in this area on C3M5_C?
![C3M5_C](https://user-images.githubusercontent.com/6550500/97119452-ad41ec80-16e6-11eb-96d1-c715af53f23c.png)
If I just pick up the red key, that will alert everyone there. If I take out a gun and shoot everyone, that will raise alarms in other places, and prevent me from making any further progress.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 AFAIK just the key pickup won't alert the enemies, it's the Gestapo officers who might (or might not) blow your cover and raise the alarm. At least it was such when I played this mission. With some luck it was possible for me to sneak up to the key and steal it without everyone noticing; maybe this was changed recently, IDK.

> If I take out a gun and shoot everyone, that will raise alarms in other places, and prevent me from making any further progress.

How so? You have lots of weapons, even a Nebelwerfer if you aren't 'knife-starting' the map, and plenty of health and resources.

**Comment by Ozymandias81** [comment]
The pickup alert a certain amount of enemies, only those tagged 237, thanks also to SeePlayer script. In order to survive you have to kill all of them and then break the alarmpanel (probaby best if done before the pickup) in the room as fast as you can, you'll probably have to deal with Gestapo and 2 more soldiers, but staying crouched after that will make you safe again

Selected enemies are tagged 237, the gestapo will roam inside the room and we also have two SSGuards on left/right wings to deal with. 
![image](https://user-images.githubusercontent.com/11136108/97188381-bcd33b00-17a3-11eb-9831-24eda8abb851.png)

**Comment by Tormentor667** [comment]
Fixed a few things and made a commit today.

**Comment by Talon1024** [comment]
I recently played through C3M0_A, and I have a few things to say about it:
1. Before you reach the temple in the caves, there are 3 cracked walls which you can bomb. One of them has two explosive charges behind it, one of them has 1 explosive charge behind it, and another one has none. If the player knows about this beforehand, they can decide to bomb the wall to the temple when they've acquired 3 explosive charges, and they will have one left over for bombing the entrance to the Nazis' fortified city hall.
2. On my first run of C3M0_A, I found the Tesla cannon at the very moment the mission ended and I was sent back to HQ. I think the Tesla cannon should be in a more accessible spot, like backstage in the concert hall, where the chemical bag and Erik are.
3. I also had a run of C3M0_A where the Death Hunter came back at the exact moment the mission ended, and as a result, I got hurt while the screen faded to black. Perhaps when you bomb the entrance to the Nazis' fortified hideout is when the Death Hunter should become killable for good? You can do this by giving the player the "NemesisDiesForGood" item.

**Comment by AFADoomer** [comment]
@Tormentor667 - A couple of things that something said in the Doomworld thread for the mod brought to mind...  ("...none of them actually dies")

I thought this had been addressed before, but are the prisoners in C3M1_A intended to be killable?  Right now they can be killed under sustained fire (and they don't ever duck).  Also, the mini-scene with the two "firing squad" SS when you climb under the fence still effectively has prisoners lined up to be shot, and being fired on...  Is that intended to change?

**Comment by Tormentor667** [comment]
@Talon1024 - I took care of point 1, but regarding point 2-4 you might want to read my comment here: https://github.com/Realm667/WolfenDoom/commit/96b358801af21bd2f99733c00fe0b1ccd4cbc668

**Comment by Tormentor667** [comment]
@AFADoomer - Yes, I totally missed that actually, the execution scene. I updated my comment there, though we might want to talk about this here again. The scene is somehow necessary for atmospheric reasons and to show how dangerous this place is.  Regarding making the prisoners killable under sustained fire, I am not sure about it. What do you suggest? I thought @Ozymandias81 made them non-killable but maybe I misunderstood that,

**Comment by Ozymandias81** [comment]
On a FB discussion we said it was okay to have them killable again under sustained fire (but we discarded the lose money thing and instead went for friendly crosshair indicator, since DoomJedi said they would have turned as bullets sponge which may also block line of fire, or something like that) but afaik they should be invulnerable. For the execution scenes (c2m1 and c3m1) one can trigger the Death state or just make killable variants for them though, or change flags scriptwise on map. Today I don't have time at all, maybe tomorrow will get better but please set this in stone and decide once for all.

**Comment by AFADoomer** [comment]
The firing squad scene has them firing at wall textures, and with already dead bodies on the ground, so I don't think it's an issue.  Plus apparently the Nazis are bad shots, so the people on the wall stay alive...

I made some changes to the A_WanderGoal function and prisoner behavior in 85c498276cf84f4dd41dcb31d75002f4c43303be to make them actually react to being shot at, even if they aren't hit (they become afraid and run away), and added a chance to crouch if they do get shot (with crouching no longer blocking bullets fired from behind them).

**Comment by Talon1024** [comment]
I'm having a hard time with C3M0_B. It seems like you can't be stealthy, and the enemies will spot you too quickly, even though the mission was meant to be played stealthy. The alarm was sometimes ringing when I entered the base, and I couldn't get past this part without being spotted:
![c3m0bfrustration](https://user-images.githubusercontent.com/6550500/102711400-6fe18180-4287-11eb-8250-cc13cd42f9e5.gif)
At this point, I just said "fuck it" to myself, and continued with the mission by blasting every Nazi that dared get in my way, until I ran out of ammo.

**Comment by Tormentor667** [comment]
This area is indeed a problem. You can avoid being seen by walking on the right wall behind the crates though. Did you try that? Maybe we have to change enemy placement or map structures here to avoid that.

**Comment by Tormentor667** [comment]
Fixed what I could, assigned the rest

**Comment by Tormentor667** [comment]
Fixed a few more things.

**Comment by ForeverExe** [comment]
C2M4, Operation Wustenfuchs: the sheet of paper is blank and the game shows me this error https://prnt.sc/xgr0en

**Comment by Username-N00b-is-not-available** [comment]
@ForeverExe, Italian line 2303 in the CSV had ```s!: dovrebbe essere da qualche parte in città, non sono sicuro dove|4709|5```. There should have been a vertical bar instead of an exclamation mark (I replaced it now).

**Comment by ForeverExe** [comment]
> @ForeverExe, Italian line 2303 in the CSV had ```s!: dovrebbe essere da qualche parte in città, non sono sicuro dove|4709|5```. There should have been a vertical bar instead of an exclamation mark (I replaced it now).

Thanks, my bad.

**Comment by ForeverExe** [comment]
New problem, it's the background box in the german industry "cutscene" [https://prnt.sc/xi4ky0]

**Comment by Ozymandias81** [comment]
Grazie @ForeverExe ! ... e tieni presente che la traduzione italiana deve essere ancora sistemata, ma continua così! Ti suggerisco di creare un nuovo "issue" dal titolo ForeverExe Playtesting e includi li dentro i problemi che trovi di tanto in tanto. Per gli screenshot ti consiglio di usare "idmypos true" da console (premi il tasto e digiti quanto detto insomma, senza le ") :muscle:
