### ISSUE TITLE
Proposal: New weapon sprites

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#196]
Here are some new and/or improved HUD sprites for the weapons that I found on ZDoom forums:

Trench Shotgun:  
https://forum.zdoom.org/viewtopic.php?f=37&t=65643&start=105#p1146354  
https://forum.zdoom.org/viewtopic.php?f=37&t=65643&start=105#p1148591

MP40:  
https://forum.zdoom.org/viewtopic.php?f=4&t=15080&p=1140206#p1140206

Kar98k:  
https://forum.zdoom.org/viewtopic.php?f=4&t=15080&p=1151693#p1151693

Should we add them or not?

**Comment by Tormentor667** [comment]
This is definitely good stuff, I recommend adding these. Just make sure to incorporate the improved muzzle flashes that I made (see the /hires/ folder for details about what I have done exactly). Very good fining @Talon1024 ! :)

**Comment by Talon1024** [comment]
One problem I see immediately is that the Kar98k there doesn't have a sniper scope, whereas the one we have already *does* have a scope.

**Comment by Tormentor667** [comment]
I wonder if @DoomJedi or @Ozymandias81 is able to transfer the scope?

**Comment by Talon1024** [comment]
I have the new MP40 sprites in [this branch](https://github.com/Realm667/WolfenDoom/tree/feature/ElectricPulseMP40). Only the muzzle flash needs to be adjusted for the new MP40 sprites.

**Comment by Ozymandias81** [comment]
I think you can merge them on the repo, adding the scope over the new kar98 shouldn't be difficult so I am okay with these changes. Oh and btw last frame of kar98k is not used anywhere (no scope reload frame)

**Comment by Tormentor667** [comment]
The Kar98k hasn't been added yet and the muzzle flashs are still low-res, is this correct?

**Comment by Talon1024** [comment]
Correct, but the Kar98k needs a scope on its first-person sprite.

**Comment by Ozymandias81** [comment]
As Talon said yes, kar98 needs the scope... I still didn't frankensprite it since we'll also need to animate the weapon differently, and sprites we have also show arms without any clothes on them

**Comment by Tormentor667** [comment]
I currently just wonder if it is worth the huge effort. I mean the sprites look better than our version, no doubt about that. Having it would be cool, but is it doable In a reasonable time?

**Comment by Ozymandias81** [comment]
I wonder me too, let's see what will happen after fixing C3 maps. I'll save this after that, which is more important now.
Talon additions are awesome so those for sure will remain imho

**Comment by Talon1024** [comment]
Some other new weapon sprites I found:

Kar98k: https://forum.zdoom.org/viewtopic.php?f=4&t=15080&p=1009123#p1009123
Luger and G43: https://forum.zdoom.org/viewtopic.php?f=4&t=15080&p=1006973#p1006973

**Comment by Tormentor667** [comment]
I checked these but they are very bad model rips in my opinion. I like our variants better in this certain case.

**Comment by Ozymandias81** [comment]
Yes same here tbh, I think improving kar98 is enough and then weapons will be set

**Comment by Tormentor667** [comment]
I agree. If we add the Kar98 that is posted first, the weapons are set and ready to go, no need to add anything else. @Ozymandias81 - do you think you can take care of that this weekend?

**Comment by Talon1024** [comment]
I made a request on the ZDoom forums [here](https://forum.zdoom.org/viewtopic.php?f=60&t=69334)

**Comment by Ozymandias81** [comment]
If no one will reply on Talon thread, I'll try something next week. Guess what's more important now is taking care of maps

**Comment by Tormentor667** [comment]
Let's hope we do get some little support on this! Thanks for posting Kev

**Comment by Ozymandias81** [comment]
Just implemented new Kar98k frames, here you are the spritesheet (anyway used only 6 frames because of weapon code, and works good) and an ingame screenshot. Gonna commit in a while.
![Complete](https://user-images.githubusercontent.com/11136108/88245753-a4312180-cc98-11ea-87ee-e4d07eefde91.png)
![Screenshot_Doom_20200723_035856](https://user-images.githubusercontent.com/11136108/88245986-5bc63380-cc99-11ea-9c3b-00e469904c2e.png)

**Comment by Tormentor667** [comment]
Well done Ozy 👍
