### ISSUE TITLE
Improvement suggestion: Epilogues

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#197]
This is mostly relevant for @AFADoomer - we talked about improving the epilogues after each episode (as well as after/befor secret missions or cutscenes, where text messages appear). AFA had some ideas on how to improve these lame text typers but ended up in doing a nice animation for changing the maps :) This issue here is to make sure we don't forget about that idea.

**Comment by AFADoomer** [comment]
I hit a creative block when working on these...  Any ideas or suggestions on how we want these screens to look would be welcome.

**Comment by Tormentor667** [comment]
I have an idea and will try to come up with a mockup later.

**Comment by Tormentor667** [comment]
This is something I can imagine:
![Unbenannt-1](https://user-images.githubusercontent.com/10298439/86640893-fdcbf780-bfda-11ea-9eda-3033be36413e.jpg)

The live background is what we already have in the maps. The dark-blue border/frame is similar styled as the SEQ_001 element from the TITLEMAP, that slowly fades in. Then the text gets typed in the usual font. On top of that, we can add one or more little screens at the left, with which we can tell the story and enhance the epilogue.

What do you think?

**Comment by AFADoomer** [comment]
Thoughts on this?  You can see it with the fade-in effects in-game with commit f597e36d662e83c2ddfd887261cbc6e2a3300eec (use 'openmenu finale' in the console).

![Finale](https://user-images.githubusercontent.com/16618820/86712438-a16cd600-bfe2-11ea-933a-44dd75cc1819.png)

**Comment by Tormentor667** [comment]
As this is implemented and only needs fine-tuning, we can consider this to be closed.
