### ISSUE TITLE
Making the introduction letter from Dirty Douglas translatable

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#198]
Currently the letter is only available in english. @Talon1024 planned to change the system for making the scrolling letter also available in all translatable languages that Blade of Agony supports. This issue is here to make sure we don't forget about it.

**Comment by AFADoomer** [comment]
The backing implementation is already done for graphic replacements via LANGUAGE definition...  The DDB_LTTR entry sets the path of the letter image to use.  What's still missing are the graphics with the translated text.

**Comment by Tormentor667** [comment]
Would it be possible to somehow turn this into a mix of a background letter graphic and a text string? I have the feeling that this would be a more comfortable solution.

**Comment by AFADoomer** [comment]
Yes, I already have code to do that...  The font isn't quite as pretty (it uses the typewriter font that the papertexts use), but it works.

Do you have a clean version of the background paper image with no typewriter text, just the 'CONFIDENTIAL' stamp and signature?  I'm not sure who created that originally.

**Comment by Tormentor667** [comment]
Very good, I just uploaded the blank version of the letter with the stamp and the signature (good thing that I tend to save files as PDF because you never know what you will need in the future).

**Comment by AFADoomer** [comment]
Just committed a ZScript implementation of this in 10f659beb3f303bddba6d056b9339dcec80462c7.  

Could probably be done with just ACS, but I already had most of the ZScript sitting around...
