### ISSUE TITLE
Making "Help & Info" translatable

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#199]
I currently used parts from the webpage and simply turned them into screenshots that are directly implemented into the "Hints & Info" area of the game. I wonder if there is a way to make these also translatable and work differently so that I can set them up in a good way after C3 is done and the webpage is updated with all the relevant information? What kind of approach could we go for here? @Talon1024 @AFADoomer

**Comment by AFADoomer** [comment]
Changing out the MENUDEF entry to use a custom menu is easy.

The harder part is that the key that is bound to menu_help (default F1) is hard-coded to automatically launch the ReadThisMenu menu, which is the normal help screen that cannot be replaced.  I can get around this by putting an event handler in place to intercept the key press to launch whatever custom menu we set up instead.  

In either case, we either need custom images for each locale or we need clean background images and LANGUAGE strings for all of the content.  I can code in support for either.

**Comment by Tormentor667** [comment]
What if we use a font that’s already there? I think the best choice is to use custom images and place the text next to it but I wonder how we could layout that. I mean I am aware of anything html and css related but I have no idea how to transfer this into the game

**Comment by AFADoomer** [comment]
The easiest way would be for me to hard-code everything layout related into the menu code.  I can set things up to look close to the current pages with a little work.

The only fonts that we have with all characters are BigFont, Small Font, typewriter, and some of the handwriting fonts.  I can certainly use the big and small fonts instead, and it'll match the rest of our GUI.  It just won't match the current info screens.

**Comment by Tormentor667** [comment]
That sounds like a good plan, I am okay with that. Generally having BIGFONT and SMALLFONT used is the right way to go. As it looks now it was just a choice of lazyness, as it's exactly what's used on the page - it's not a must have.

**Comment by Ozymandias81** [comment]
This is epic work guys! One thing to point you out btw: page indicators on bottom screen tends to cover paragraphs with 4:3 resolutions ( I use 1024*768 windowed or 1280*1024 fullscreen).

**Comment by AFADoomer** [comment]
Thanks @Ozymandias81!  Yeah, these page indicators were literally directly copied over from the finale screens; waiting for @Tormentor667 to tell me if he likes them as-is, or if I need to do a smaller and more minimalist page indicator so that he doesn't have to rework all of the screen layouts (or I could tweak the virtual width/height to scale down all of the content slightly).

**Comment by Tormentor667** [comment]
What can I say, it's mostly perfect now as is - brilliant work from @AFADoomer when it comes to the coding and preparation, it was so easy to feed the skeleton with some meat :)

**Comment by Ozymandias81** [comment]
I can confirm that with recent changes everything seems to fit well with my resolutions. Applying these to epilogues will also improve them as well for me, which with the old method I was always missing most of left or right sides of the screen.

**Comment by Username-N00b-is-not-available** [comment]
Nice work!
I translated the section into Russian, also fixed some typos.

**Comment by Tormentor667** [comment]
Thanks kindly!

**Comment by Ozymandias81** [comment]
Guys noticed one thing: Enemies text doesn't fit with my resolution, which is a 4:3 1024x768 windowed (same happens fullscreen 1280x1024)
![image](https://user-images.githubusercontent.com/11136108/87621718-af78d000-c721-11ea-8919-59201173db00.png)

**Comment by AFADoomer** [comment]
It doesn't fit on any resolution.  The strings are too long and need to be edited down.

**Comment by Ozymandias81** [comment]
Yes thought that... I re-opened this to not let forget those that needs to be edit. There is also one minor nitpick: the Story image shown the old setup on the map that had Sherman tanks on the Russian side, while a couple of days ago I have added T-34 instead with proper things and such (c3m6_b map).
![Screenshot_Doom_20200716_051335](https://user-images.githubusercontent.com/11136108/87622326-2e223d00-c723-11ea-962a-b8a6fa50e1d3.png)

**Comment by Tormentor667** [comment]
> It doesn't fit on any resolution. The strings are too long and need to be edited down.

Shouldn’t they automatically scroll?

**Comment by Ozymandias81** [comment]
It doesn't happen it seems

**Comment by AFADoomer** [comment]
They did, but that was unintended...  the auto-scrolling was only supposed to happen when I forced the text size larger because of low resolution, because, frankly, it looks bad to have most of the boxes on that screen scrolling all at different positions.  Tolerable if it's a compatibility hack, not as the default...

**Comment by Ozymandias81** [comment]
Yes I guess best solution is to reduce texts in a feasible way and not have them scrolling

**Comment by Tormentor667** [comment]
Better would be to scale the texts so we don’t lose content :)

**Comment by AFADoomer** [comment]
I just tweaked the minimum scale size on the info screens to be slightly lower, and scaled the Enemies strings down.  Many still are too long.  If we make them any smaller, they become illegible.

**Comment by Tormentor667** [comment]
Well that's indeed a problem. In this special case I'd suggest shortening the texts for the Tanks and the Bosses (making them 4 lines) and on top of that scaling the images a bit (about 80% of their original size). That way the text should be readable and large enough. I will try that.

**Comment by Tormentor667** [comment]
Committed, maybe then you can upscale the text again now.
https://github.com/Realm667/WolfenDoom/commit/08659ff9b59b0626f8ac166d9e0c6aeff7fe2374
