### ISSUE TITLE
Explanation of all the graphic predefinitions

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#200]
@Ozymandias81 - I am currently translating various portions of the language entries into german and I need some help when it comes to the predefined graphic settings aka
`3d trees, special effects, mirrors & reflections OFF; particles at min values; rendering at half of min values; shaders OFF; advanced OpenGL options OFF`
Can you give me a detailed list of the various predefined settings you have prepared and what they are doing so I can turn them into a proper description and translation? Afaik, there are 5 of them reaching from "potato" to "maximum". Maybe a comparison table would work the best for me.

**Comment by Ozymandias81** [comment]
I'll try to write up something during the week, working on c3m6_b atm.

**Comment by Tormentor667** [comment]
Thanks kindly!

**Comment by Ozymandias81** [comment]
Wrote something on FB chat about it, keyconf has quite all info you can have. Sorry for being dispersive, doing too many things at the same time.
