### ISSUE TITLE
The uselessness of the "Totale Macht"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#201]
As of now, the Totale Macht is nothing more than a Berserk Pack, a pretty lame and non-fitting powerup in Blade of Agony. What can we do about it? @Talon1024 @Ozymandias81 @AFADoomer

**Comment by AFADoomer** [comment]
I think the only other thing that it does right now is to make your knife have 4x damage.

Maybe have it increase max health and/or give a regen effect?

**Comment by Tormentor667** [comment]
The 4x damage is generally the same as the fist from Doom being stronger, but Blade of Agony is not made for such kind of gameplay because of all the hitscans we have. 

A regneration effect sounds reasonable to me, maybe additional some kind of reflection effect, that reflects about 50% of projectile attacks from nazis? Just tossin' ideas.

**Comment by Ozymandias81** [comment]
Totale Macht increase damage of a couple of melee weapons, such as Knife, kicks, Shovel, Firebrand melee attack and it could be implemented to AstrosteinMelee as well too. The regen thing would be nice to add too probably yes, but also even health to 100 first like Doom berserk.

**Comment by Ozymandias81** [comment]
On the other side we must find a way to fix player being cured while entering/exiting tank, and also then prevent Totale Macht from being used in that case too, and also check armor too. Some of the issues are list on #188

**Comment by Talon1024** [comment]
Maybe the Totale Macht can make enemies randomly drop health and/or armor bonuses, or other useful things?

**Comment by Tormentor667** [comment]
Maybe make enemies drop coins for 5 minutes and we call it “Totale Gier” instead of “Totale Macht”?

**Comment by Ozymandias81** [comment]
I don't think it makes sense with drops or coins, I think the best way is: cure of 100hp, health regen and reflective invulnerability for 10 seconds. Or health and ammo regen 🤔

**Comment by Tormentor667** [comment]
Right - let's make it like Virg suggested:
- 100 hp of instand health
- health regeneration up to the player's max heath
- reflective invulnverability
(both the latter for 10 seconds, but no powerstrength)

On top of that @AFADoomer how hard woult it be to code my "Totale Gier" (total greed) powerup that makes nazis drop coinitems (let's say 3-6 per Nazi) for a total of 1 minute when the inventory item is used?

**Comment by AFADoomer** [comment]
The gold dropping would be easy enough to code (I'd make any Nazi within a certain distance who is targeting the player drop random coin amounts on a semi-random time interval).  I'm assuming this would be an easter-egg type item of some sort?  It's a little too Arcade-like for normal play...

**Comment by Username-N00b-is-not-available** [comment]
What about also dropping coins on getting hit with same conditions? :-)

**Comment by Ozymandias81** [comment]
Unless used as a little easteregg on some particular moments, I don't see how the treasure thing should fit on BoA.. Sounds too much like a jrpg or Golden Souls reference

**Comment by Talon1024** [comment]
I didn't mean having enemies drop coins at random intervals, I meant having enemies drop a random amount of coins or health/armor bonuses when you kill them, sort of like in Colorful Hell, but obviously to a much lesser extent.

Admittedly, I've been watching someone's playthrough of the Kingdom Hearts series games on YouTube from time to time.

**Comment by Tormentor667** [comment]
The power up is some kind of a secret that can be found once in each chapter. As long as it lasts, Nazis drop coins when being killed (or only a few if being hurt, could be connected to the amount of damage dealt.

**Comment by AFADoomer** [comment]
OK, just committed both of these b0bacf3ba1e44fde5bd27ecc6b1b53ae962a06a5.

One thing we missed about the Totale Macht is that it lets you sprint without using stamina for 30 seconds.  I left that piece in place.

**Comment by AFADoomer** [comment]
Another thought on this...  Would it be worthwhile to make the Totale Macht auto-activate when the player is killed?  So they would hit 1 health, then get all of the effects and be able to recover...

Though now that I write it out, it sounds like the Totem of Undying in Minecraft...  So maybe not.

**Comment by Tormentor667** [comment]
I am not sure about it. It sounds cool but also unintuitive to a certain extent but maybe I am not used to such an automatism

**Comment by Username-N00b-is-not-available** [comment]
Heretic and Hexen had a similar system; on skill 1, the game would activate a healing item if the player's health is low. I think it would be great to implement this, at least for skills 1 through 3, the item is really rare anyway. Though its Armory cost should probably be rebalanced.
As for being unintuitive... We can write about this behaviour in the pickup message, showing the current one (just 'Totale Macht!') on higher skills and something along the lines of 'Totale Macht! Auto-activates when you are close to death.' on the first three skills.

**Comment by Tormentor667** [comment]
Yes, that’s a good point then. I wasn’t aware of this feature in Heretic

**Comment by Tormentor667** [comment]
After @AFADoomer ‘s recent changes, this can be considered as solved. Well done :)
