### ISSUE TITLE
Different/new color scheme for the webpage

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#202]
In the game itself, we started to use a certain color sheme in the TITLEMAP as well as the ending sequences and cutscene overlays which has this blue teint. I thought about changing the look of the page to something similar. Here is a small preview, what do you guys think?

Link: https://boa.realm667.com/?template=bladeofagony_2020&is_preview=on

**Comment by Tormentor667** [comment]
![2020-07-14_200459](https://user-images.githubusercontent.com/10298439/87460615-6cc5d380-c60d-11ea-8027-d8976528d977.jpg)
![2020-07-14_200524](https://user-images.githubusercontent.com/10298439/87460619-6d5e6a00-c60d-11ea-8f0b-9f4ed67a15c7.jpg)
![2020-07-14_200538](https://user-images.githubusercontent.com/10298439/87460625-6df70080-c60d-11ea-9435-497ec9ac2e9e.jpg)

**Comment by Ozymandias81** [comment]
I like it, stands better ime. Maybe we should mimic same color scheme over options on the mod (not website), since the gray color sometimes is not clearly visible on top of the Wolfendoom symbol.

**Comment by Tormentor667** [comment]
> I like it, stands better ime. Maybe we should mimic same color scheme over options on the mod (not website), since the gray color sometimes is not clearly visible on top of the Wolfendoom symbol.

In case the new design is being used I’d adjust the options colors in game. I’d like to wait for @AFADoomer  and @Talon1024 and @DoomJedi opinions as well though

**Comment by AFADoomer** [comment]
I like it.

**Comment by Tormentor667** [comment]
Any Suggestions? :)

**Comment by Ozymandias81** [comment]
Maybe use some rusty paper for "Did you know that" like entries on the page? And I wonder if you could hide something over the webpage, inside only one page... Something that if you click takes you to a random secret screenshot

**Comment by Tormentor667** [comment]
![2020-07-15_161239](https://user-images.githubusercontent.com/10298439/87555652-08128380-c6b6-11ea-91d7-b973dbdbe903.jpg)

Did some more work, I think it's pretty much finished this way and can be released to the public :)

**Comment by Tormentor667** [comment]
New page design is online: https://boa.realm667.com/
