### ISSUE TITLE
Suggestions for the custom menu

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#203]
- Advanced GL Portals Off/On are currently unique single menue entries under "Rendering Settings". Can these be combined into a "Toggle" menue just like "2D Trees"?
- Under "Post Process Options" there are the "Tonemaps". As we haven't tested any of these with Blade of Agony, I'd suggest removing this options that involve Tonemaps.
- Under "Customize Action Controls", I'd suggest putting the "Quick Kick" and "Throw Grenade" under the "Weapon Zoom", remove the "Show Scoreboard/Toggle Scorebard" (we have no deathmatch) and also remove the "Weapon State 1-4".
- Under "Customize Inventory Controls" I'd remove the "Query item" and "Activate all items"
- Under "Customize Controls", remove the "GZDoom Original Controls". This is accessable through the main GZDoom controls option link anyway from "Options", these goes for any other additional shortcut btw.
- Under "Gameplay Options" I'd remove everything below "Smart Autoaim" as these are all Doom-relevant settings and flags, that have no reason to be in BoA (they are still accessable through the GZDoom menue)

**Comment by Ozymandias81** [comment]
I have set Portals now as you said but there are a couple of notes regarding changing that option: now it gets saved, I can't include any warning messages and well I think it should be removed since it may cause serious glitches during gameplay for unaware players.

**Comment by Tormentor667** [comment]
I agree
