### ISSUE TITLE
Floppy instead of "Game saved" on-screen message?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#204]
I know, this is some nitpicky design stuff but I never like how the "Game saved..." (autosave)-message overlaps with the map title when moving between operations and maps. I wonder @AFADoomer would it be possible to remove the onscreen-message and instead show a small 3.5" nazi-floppy disk at the upper right corner indicating the autosave?

**Comment by Talon1024** [comment]
Doing that might require a font character that looks like a floppy disk. Unicode has a "private use area" which is perfect for this sort of thing.

Here's a floppy disk font character I came up with: ![floppy](https://user-images.githubusercontent.com/6550500/87591380-3abc7c00-c6b6-11ea-8bc1-ab9f75d1f0fb.png)

**Comment by Tormentor667** [comment]
Wouldn’t it be possible to use the original doom floppy disc graphic and display that one with a ZScript override?

**Comment by AFADoomer** [comment]
I can just intercept the print call in the status bar class, then draw an image...

**Comment by Tormentor667** [comment]
Sometimes I don’t know what’s more impressive - the programming skills you have or the knowledge about the GZDoom source code :)

**Comment by Ozymandias81** [comment]
Lovely floppy, reminds to me of Amiga ones

**Comment by Tormentor667** [comment]
It’s in, it works, we are happy :)
