### ISSUE TITLE
Gestapo recognize disguised BJ instantly

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#205]
The Gestapo guys recognize BJ instantly when he's wearing a disguise. This isn't how it was in Chapter 2, and it makes some missions, like C2M6_B and C3M5_C unplayable.

[Video 1](http://www.ciinet.org/kevin/myimages2/doom/wolf_boa/bugs/Gestapo1.mp4)
[Video 2](http://www.ciinet.org/kevin/myimages2/doom/wolf_boa/bugs/Gestapo2.mp4)
[Video 3](http://www.ciinet.org/kevin/myimages2/doom/wolf_boa/bugs/Gestapo3.mp4)

**Comment by Tormentor667** [comment]
I experienced that as well. It seems that the delay is zero before the player looses disguise.

**Comment by AFADoomer** [comment]
This should be fixed in 2e1860d15f3cfb82ae4cc82e30b6f86313054faf.
