### ISSUE TITLE
Player loses extra health after completing Commander Keen bonus level

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#206]
I was playtesting Chapter 1, and before I played the Commander Keen bonus level, I bought a bunch of vitality serums. I got Bones to top me up, and then I went and played the Commander Keen bonus level. Afterwards, I had 100 health, but I could still pick up medkits and use healing items when I played C1M5.

**Comment by Ozymandias81** [comment]
And not only that, when we get on the tank, our health becomes 100 and same happens to armor, even if we have more or less than 100. We should also add something that prevent players from leaving the tank in certain occasions too

**Comment by Tormentor667** [comment]
> We should also add something that prevent players from leaving the tank in certain occasions too

For example?

**Comment by AFADoomer** [comment]
Ugh.  ZDoom's morph handling quirks strike again...  I will have to code something in to manually track player health (already did so for armor when using the tank).  Is armor amount correct when you stop playing as Keen?

**Comment by Talon1024** [comment]
IIRC yes

**Comment by Ozymandias81** [comment]
> > We should also add something that prevent players from leaving the tank in certain occasions too
> 
> For example?

Something like a radio message that tells us that if we leave the tank we'll get killed, something to use on c3m4

**Comment by AFADoomer** [comment]
The health issue should be resolved as of fffccd7e6458aea2c25643a418a05ab3ebc68076.  

The morphs both have been set up to remember armor amounts for about a year now; the health was a little more complicated because the internal function for handling unmorphs blindly sets the player's health to SpawnHealth when you unmorph.
