### ISSUE TITLE
C2M6_A: P_StartScript: Unknown script 25

### ISSUE THREAD

**Issue by 2-4601** [Realm667/WolfenDoom#207]
This switch produces an error message:
![Screenshot_Doom_20200717_220450_compressed](https://user-images.githubusercontent.com/174176/87849813-40070a00-c8f4-11ea-8645-abca8718f538.jpg)
GZDoom version: g4.4.2-m
BOA version: 1e3523ae364d9e7c67949cadfb21677d77ca512f

**Comment by Ozymandias81** [comment]
It looks like that button was already broken even on C2 release, fiddling old commits now in the search of it.

**Comment by Ozymandias81** [comment]
Thanks for let us know of that @2-4601 , this was never been implemented yet and now is fixed.
