### ISSUE TITLE
C2M6_C: P_StartScript: Unknown script 308

### ISSUE THREAD

**Issue by 2-4601** [Realm667/WolfenDoom#208]
This linedef produces an error message:
![Screenshot_Doom_20200718_155714_compressed](https://user-images.githubusercontent.com/174176/87853152-941fe780-c910-11ea-843c-d376c68edf68.jpg)
GZDoom version: g4.4.2-m
BOA version: 1e3523ae364d9e7c67949cadfb21677d77ca512f

**Comment by 2-4601** [comment]
Thanks for the quick fixes. I also experienced that the drones were "stuck" and assumed that the error was related that. But I guess it's a different issue.

---

I noticed something strange after building and testing all these C2M6 related fixes (93706b3acabd7f7f42446623090b3efc6369a585). All the three maps (C2M6_A, C2M6_B and C2M6_C) hang on me now after a few minutes (or less) of playing. I have to `kill -9` GZDooM. I tested the version before these fixes and it doesn't hang.

For example run:
1. map c2m6_a
2. iddqd
3. noclip
4. run straight to the switch that was fixed in 08aac73b0c21c758a5fbb90c9a18e5376fdd5be6

When I get to the first Übersoldat GZDooM hangs completely.

**Comment by Ozymandias81** [comment]
Which operative system are you under? We need more info to understand your issue, keep in mind that if you are using old saves that may be the cause. Also which exact version of GZDoom are you playing with too?

**Comment by AFADoomer** [comment]
I am unable to replicate this...  Definitely need more info.

**Comment by Tormentor667** [comment]
Same here, I can’t reproduce the problem.

**Comment by 2-4601** [comment]
Thanks all, it turns out @Ozymandias81 's fixes had nothing to do with the issue I described above. I bisected the bug and will open a new issue.
