### ISSUE TITLE
Blade of Agony weapon sprite (hud) is not widescreen friendly

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#213]
Some parts of the sprite get cut off when it is swinged.

**Comment by Ozymandias81** [comment]
This will be extremely hard to fix without some sprites to work with or through some help from the community... We even used improved sprites for the weapon though.

**Comment by Tormentor667** [comment]
We need to ask for help then, maybe neoworm could be asked. But everything else is widescreen friendly so it would be a shame if that fails

**Comment by Ozymandias81** [comment]
Btw forgot to tell you that I [already requested](https://forum.zdoom.org/viewtopic.php?f=3&t=57032&sid=20be0f9c526e620673099432f69d8a45) it in the past, and if I am not wrong we are using ZikShadow sprites actually

**Comment by Tormentor667** [comment]
I have taken a look at ZikShadow's submission. I'd be okay in using his version in total instead of our version if it is widescreen compatible. It looks good at least. :)

**Comment by Ozymandias81** [comment]
I'll try mixing both and see how the final result will work

**Comment by Tormentor667** [comment]
Awesome, I am looking forward to this!

**Comment by Tormentor667** [comment]
Did you already have the chance to Frankensprite a bit? :)

**Comment by Tormentor667** [comment]
As far as I can tell @Ozymandias81 you have solved this, right?

**Comment by Ozymandias81** [comment]
Will close when bmaps are done, going to work on them right now :)
