### ISSUE TITLE
Concentration Camp controversity and general game sensitivity discussion

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#215]
I had a discussion lately with Scub Steve on Doomworld about the sensitivy when it comes to the concentration camp (C3M1) in chapter 3 of Blade of Agony.

He made a lot of good points that I started to incorporate into the first of the third chapter but also some things I would like to discuss with you before making any changes. The sole reason for this is to avoid any possible shitstorm when it comes to this map and the release that we are working on.

Scuba said that even though historical influences are important, it's questionable to use real places and real persons in the mod itself. For example "Dachau" should be replaced with a fictional concentration camp location and so should "Mengele" not be called Mengele at all, considering that he was one of the henchmen who was never imprisoned for his crimes but lived happily in Brazil until his death.

So the question is: Do we change Dachau in a fictional place and do we change the names of real henchmen of Hitler's staff into something fictionl thast resembles their real counterparts? (for example instead of Dr. Mengele we can call him Dr. Scherge or Dr. Mangel). 

For Dachau it's not a big deal. I think the place doesn't get worse or better just if it is Dachau or a fictional place. For the henchmen it's different. People will most propably still recognize the original persons they resemble (their look is obvious), on the other hand it would be shame if they do not. It's a hard decision and I really want to know your thoughts about it.

**Comment by AFADoomer** [comment]
I think it's the right thing to do.  The whole setting of C3M1 has always bothered me, but I never really said anything.  It needs to be handled delicately, I think.

**Comment by Tormentor667** [comment]
I am currently already replacing "Dachau" with "Schattenau" (fictional). I think it's okay to do the same for the Nazi Bosses. I'd suggest going for something that's not totally off but maybe similar to the original name so people do get the reference and we don't wake up sleeping dogs.

Some suggestions from me (which sound phonetically similar without being too obvious if you are non-german)
- Dr. Mengele -> Dr. Mängels
- Gen. Himmler -> Gen. Hirnler
- Gen. Goering -> Gen. Görging
- Gen. Goebbels -> Gen. Gorpels
- Dr. Morell -> Dr. Muränle

**Comment by Talon1024** [comment]
If you're going to do that, I suggest coming up with new names that aren't references to real people involved in Nazi Germany. For example, one of the main antagonists of Wolfenstein is "Deathshead".

**Comment by Tormentor667** [comment]
I‘d tend to keep them phonetically German. I really don’t like localizations of names in general. #ironforge #stormwind

**Comment by Ozymandias81** [comment]
I think it would be better to keep historical names since we have Hitler and lots of references here and there to historical facts and persons. Instead I am okay with Dachau, but we shouldn't fall to censor too many arts and such imho

**Comment by PixelScuba** [comment]
I'm not saying you need to change _all_ the names, but Mengle in particular I feel is a really touchy subject since the real Josef Mengle was performing experiments on prisoners in concentration camps--his presence in the first level makes it especially offensive. My suggestions are, in preferred order... A.) completely change his name to a fictional German, or B.) If you're intent on keeping him in, remove him from the Concentration Camp level and have him only appear later in the game.

**Comment by Tormentor667** [comment]
B) is not an option as it conflicts with the complete storyline of C3. A) is something we can do with little effort.

**Comment by 2-4601** [comment]
As a player I would like to see more historical references, not less. A game with a theme like this should also represent the darkest parts of the era. If it doesn't, it would undermine their existence. As BOA is a tongue in a cheek game I see that it is not an easy task to handle the subject delicately. There's the danger of showing the Nazis as just another silly enemy. Fortunately BOA has handled this well so far - much better than many of the games it nods to. The historical photographs, posters on the walls, letters etc. do their part in showing the dark history. Especially the Jew Exhibition in the Paris mission was a great way to show this. I did not even know an exhibition like that actually existed: https://en.wikipedia.org/wiki/The_Eternal_Jew_(art_exhibition)
Thanks to BOA I learned something new.

The first two episodes had a theme of the Nazis running experiments on people. As the Schabbs family is not based on a real person I guess you could also change Mengele to a fictional character in the same manner. However as a counterargument one could say that removing him would mean that Mengele manages to escape to South America also on this BOA timeline and never has to face the consequences of his actions. Would it offend someone to see Mengele get killed and prevented from continuing his experiments? If he does not get caught in the Dachau mission, does it mean that he was able to finish his job there? Also if you start removing historical figures from the game why not remove Hitler? Or was Mengele worse than Hitler?

I think you have handled things well so far. Has there been a "shitstorm" of the first two episodes? At least I cannot find anything. Just articles from a couple of large game media sites praising the "mod". Will the third episode be that different? I say continue the same way and stick to your vision.

**Comment by PixelScuba** [comment]
I told Torm this earlier, but the concentration camp level is treading a _very_ fine line between homage and offensive, and in this case your best decisions should _always_ err on the side of caution. When it comes to this map, just stay away from anything referencing Judaism, real people, or actual places and events... it simply isn't worth it no matter how accurate you want to be. The other levels are less concerning.

**Comment by Tormentor667** [comment]
I think one of the really important things that we did now is removing the direct references to Jewish people from the concentration camp map. This is something that was quite dangerous to handle.

For the names of the enemies, especially Mengele, I think that @2-4601 made a very good point actually. It’s a thin line, we know that already since the beginning of the development of Chapter 3 and some decisions are still not easy to make.

**Comment by Tormentor667** [comment]
After thinking and considering this issue for another while, I came for a decision when it comes to the concentration camp, the art and the names involved.

All the points made here are good, from every point of view they make sense and are reasonable. My solution with this is similar to Peter Jackson's approach now, when he thought about which parts are needed for the "Lord of the Rings" movies to work: "What is important to carry the story, to prepare the atmosphere - and what is not?"

When it comes to the jewish references in the concentration camp (C3M1), it doesn't add anything to the story. It doesn't make a difference if the prisoner is a jew, an american or simply a prisoner without specific origins. We remove these remarks. There is also no need to tell if the place is real (Dachau) or if it is a fictional place (Schattenau) somewhere in the south of Germany. The level speaks for itself.

But when it comes to the names of the henchmen, specifically Mengele, we need to look at this from a different point of view. What if the main villain in this game is a guy with a strange mustache, called Huddler? Would it change the final bad guy's value? Of course it would! Knowing that Hitler, Himmler and Mengele are the villains we will face is what also sets the historical position of the mod, and it's what the player expects: To kill Hitler, to kill his henchmen - and maybe even to make those who escaped pay their debts in this alternate history.
