### ISSUE TITLE
Fix jittering movement for models while moving

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#217]
While I am not sure if this is doable, I wonder if it would be possible to fix railshooter moments when we are on truck in c2m4 (which is very noticeable) and on tanks when going backwards.
I know that there are some limits, and that some solutions may turn things into a slideshow, but would this be possible to fix to improve consistency and feeling for those maps?

**Comment by AFADoomer** [comment]
I don't know if this is something that we can fix...  It seems to be hardware/resource dependent.  My old computer jittered a lot during the rail sequences; my current machine does not.

**Comment by Ozymandias81** [comment]
Mmh yes thought so, but for some reason I remember something that could be related to a somewhat kind of improvement, sort of SPF_INTERPOLATE and extratics but atm can't check the map since I am not on pc. Later I'll try to get my mind on it

**Comment by Tormentor667** [comment]
I tried it on C1M6 just now and do not get any jitter issues.

**Comment by Ozymandias81** [comment]
C1M6 is different from C2m4, try there in case :+1:

**Comment by Tormentor667** [comment]
I will test C2M4 later this evening

**Comment by Tormentor667** [comment]
Update: Tried it and I don't notice any jittering, just a small "shaking" of the screen which is mostly because of the QuakeRadius that has been applied to the truck, but I guess that it's supposed to work like that.

**Comment by Tormentor667** [comment]
Another update: After playing the truck right from the beginning to the end, I indeed noticed some jittering, mostly random "jumps" of the truck during the ride, mostly at the end when reaching the city. It doesn't happen always, just sometimes but then for a few seconds where the movement of the truck is not seamless anymore @AFADoomer

**Comment by AFADoomer** [comment]
The small amount of screen shake is intentionally...  That's the shaking effect being applied via the ShakeShaderControl actor.

For me, I normally get no jumps.  Rarely, I'll get a small jitter, but it's not reliably in any one spot.  

I used to get a lot of jitter all the time on my old machine, so I'm pretty sure this is tied to system performance, and not something that we can fix.

**Comment by Tormentor667** [comment]
Right then, it’s something we can live with I think
