### ISSUE TITLE
Sandstorm shader/overlay effect

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#218]
I wonder, could we create a sandstorm overlay effect similar to this YouTube video to C1M6?

Link: https://youtu.be/OVCJ3sOrXeA (8:47)

**Comment by Ozymandias81** [comment]
I think it is possible but probably redundant if you use the method seen on C1M6, and I fear a bit of a problem for low-end rigs.

**Comment by Tormentor667** [comment]
I think it would look pretty cool ingame in the outside areas of C1M6 - it’s just an overlay with sand particles if I have seen this correctly in the videos. 

Unfortunately I can’t check your link on my Smartphone

**Comment by AFADoomer** [comment]
See commit f4f5a733c788cf602312b5ae93763f69282a476e.

**Comment by Ozymandias81** [comment]
Later I'll test it and tell you how it performs for me

**Comment by Tormentor667** [comment]
Feedback about it on my latest commit. It's a solid start and with some fine-tuning it'll be perfect 👍 
https://github.com/Realm667/WolfenDoom/commit/7ac2565e9429fbe57c91d03835d1dc4c1570fdbc

**Comment by Ozymandias81** [comment]
Did finally a proper playtest today of the effect, and sadly unless I turn maxparticleactors to 32 or lower, it really become an issue on my rig. Here you are some [shots](https://imgur.com/a/owDfple).

**Comment by Tormentor667** [comment]
@AFADoomer implemented the possibility to deactivate the shaders, it just needs the menu option added.

**Comment by Ozymandias81** [comment]
I didn't noticed it, my bad.
