### ISSUE TITLE
Tanks disappear when destroyed

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#219]
Title says it all...

Try entering `summon SSTank1`, quickly closing and opening the console so that the tank can spawn properly, and then entering `mdk` in the console. For me, the tank becomes completely invisible.

**Comment by AFADoomer** [comment]
Should be fixed now (c17a9d8c6ceb82e69041daa754a86b29ae1efadf).

**Comment by Tormentor667** [comment]
Something I noticed as well a few days ago: The smoke spawned by the destroyed tanks (actors that are already placed) moves downwards, and not upwards. This issue was present for ages. Has this been fixed with this commit as well?

**Comment by AFADoomer** [comment]
No, but I fixed it yesterday in 7379bcfebc0a157fbc73ea0c5f80fcefc78cf4e8...  Looks like pitch was inverted, probably from whenever it was converted from A_CustomMissile to A_SpawnProjectile.
