### ISSUE TITLE
Intermission screen appears after intro

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#221]
Playing as a WAD with Doom2 IWAD, the intermission screen appears after the intro map. Seems to be from https://github.com/Realm667/WolfenDoom/commit/8f419d07a4e4fae8eb6c7eb34674c2a8263756a5 where nointermission was commented out, possibly by accident?

**Comment by Tormentor667** [comment]
This was most propably due to testing by @AFADoomer - thanks for the fix.
