### ISSUE TITLE
C1M1 No-entry symbol over Douglas

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#224]
Looks like this is intended to indicate you can't leave yet, but all mission objectives were completed (and E on him did move me back to Allied headquarters!

![Screenshot_Doom_20200728_145904](https://user-images.githubusercontent.com/2124623/88714433-d1dbf780-d0ea-11ea-8427-b19496bc2820.png)

**Comment by davidxn** [comment]
I see what this is, in BoAStatusBar.txt - it's meant to indicate a friendly NPC you're not supposed to fire at, I just confused it for a "you can't leave yet" indicator because of the context I first saw it. Will leave this up for others to decide if confusion is likely for others as well!

**Comment by Tormentor667** [comment]
I never had such a problem appearing. The "forbidden" crosshair display is always for friendlies not being able to shot, nothing else. What do others think?

**Comment by Tormentor667** [comment]
@AFADoomer - What do you think about this? Can this be considered as an issue or not worth taking care? 

For me it was clear that the symbol is for “not shooting” but we are developers with a different subjective POV. Might others think that the Douglas actor can’t be used if the symbol is displayed on the crosshairs?

**Comment by Ozymandias81** [comment]
I thought it was good as is... But well seems that AFA solved it, so guess I'll close this.

**Comment by davidxn** [comment]
Thanks, I think that the new symbol makes it clearer!
