### ISSUE TITLE
C1M2 Easy route to get the chest key

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#228]
You can jump up here on the barrels to get the chest key, which is a much easier route than doing it the intended way of getting on top of one of the crates on the conveyor and jumping across to the vent. Wanted to open this one for discussion before fixing it, as I actually found the crates way very awkward

![Screenshot_Doom_20200728_173903](https://user-images.githubusercontent.com/2124623/88751887-95c68800-d126-11ea-9291-3ae29260ee70.png)

**Comment by Tormentor667** [comment]
I agree this must be fixed. What idea do you have to do this?

**Comment by Ozymandias81** [comment]
We can remove the barrels and set them right down those grates.

**Comment by Tormentor667** [comment]
Just fixed it.
