### ISSUE TITLE
PYRO English string rephrase

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#229]
I saw the languages CSV can't be edited through Git:

"You got the Flammenwerfer! The alternative attack mode allows to shoot a fireball."
Sounds a little awkward - can I suggest something like:
"You got the Flammenwerfer! The alternative attack mode shoots a fireball."

(Other languages for this string remain the same)

**Comment by Username-N00b-is-not-available** [comment]
@davidxn I wrote some of these messages, thank you for pointing the problem out! I'd change it, but now I also do not have access to the English lines. @Tormentor667 Could you please add me to the editors list?

**Comment by Tormentor667** [comment]
Can you tell me your Google name?
