### ISSUE TITLE
C1M1 Schabbs note thoughts

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#231]
Just a thought regarding the note in the lab at the end of C1M1, after you fight Dr Schabbs Jr... in the Chapter 2 release, I really liked the lab and the floating corpse as environmental storytelling, just seeing these bodies being stored and experimented on, making the player wonder and fear what was being done to them - and the payoff when I was suddenly having to fight mutants in the next map! Having the note naming them as 'mutants' so directly takes away from that mystery and just tells you what the bodies are for, spoiling the mystery throughout the second level.

Original:

"To:
Dr. Josef Schabbs

My honored father,
The results of the Operation: Eisenmann experiments are more than satisfactory. The mutants' enhancements were successful, and they will definitely prove useful on the front lines. With armies of our mutants deployed to the front, victory will be ours.

In humble worship
Your proud son,
Dr. Schabbs Jr.
"

Maybe something like this?

"To:
Dr. Josef Schabbs

My honored father,
The results of the Operation: Eisenmann experiments are more than satisfactory. Our enhancements were successful, and you will see the results for yourself soon enough. With our new forces deployed to the front, victory will be ours.

In humble worship
Your proud son,
Dr. Schabbs Jr.
"

**Comment by Tormentor667** [comment]
Changed, thanks for that
