### ISSUE TITLE
C1M1: Introduction camera flight doesn't have the black movie borders on top/bottom anymore

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#233]
The introduction camera flight of C1M1 misses the black movie borders on the top and bottom of the screen. Maybe this interfers with the "autosave sequence" @AFADoomer ?

**Comment by AFADoomer** [comment]
Has this ever worked properly?  The enter script for the map never adds the MOVIEHUD image overlay...  And the hudmessage calls that are there are nonsensical (duplicate id numbers, plus set to fade in over 0.1 seconds, hold for zero, then fade out for 0.1)?
