### ISSUE TITLE
INTERMAP ChestKey can be used to open C1M1 chest

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#235]
Presumably the same applies to any mission! However, I'm not sure what the intended way to open the C1M1 chest is otherwise because I don't see a ChestKey in the map... and using the INTERMAP chest key on a mission renders the INTERMAP chest unopenable.

If this isn't intended, I can think of three ways to fix it but I'm not sure what the most satisfactory one is:
- Treat ChestKey like the Training grenades, bank them into another inventory object when you leave the INTERMAP and restore them afterwards
- Spawn a new key in the current location of the chest key in an INTERMAP OPEN function, if the chest key doesn't exist and the chest is unopened
- Make Douglas stop you if you're about to go on a mission carrying a chest key (some hint about "before we go, check the chest behind you, you might find something useful")

**Comment by Username-N00b-is-not-available** [comment]
As for the key location in C1M1, search the officer's room where you find the Eisenmann files more carefully. The problem you mention needs to be addressed.

**Comment by Tormentor667** [comment]
Well, the whole point of the chest key/chest system is to have these options: If you can’t find the chest somewhere, simply take the key with you and open another one :) I see no reason for this to be fixed as long as it is intended and not game breaking.

**Comment by Tormentor667** [comment]
> Presumably the same applies to any mission! However, I'm not sure what the intended way to open the C1M1 chest is otherwise because I don't see a ChestKey in the map... and using the INTERMAP chest key on a mission renders the INTERMAP chest unopenable.

There is one, check for a secret switch on the side of the table in one of the office rooms.

**Comment by davidxn** [comment]
Sounds good - if it’s intentional to carry keys between maps, no problem!
