### ISSUE TITLE
Text spills over box in CUTSCEN1

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#236]
![image](https://user-images.githubusercontent.com/2124623/88877616-ed7ef500-d1f3-11ea-9366-82cadd4b67af.png)

Admittedly, here I was using a weird stretched window to test something else that I can't remember. But it might be hard to ensure that this text block stays nailed to where the box is meant to be across all resolutions

**Comment by AFADoomer** [comment]
Don't do that (tm).  

I'm not going to fix this.
