### ISSUE TITLE
Text lines on some textures

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#237]
When I was searching through BoA's textures to find ones which could be subject to translation, I found some inconsistencies:
SIGN_126 says something about Dachau;
SIGN_025 has 'Zuttrit' instead of 'Zutritt' (we should also check the textures for other typos);
SIGN_ST4 and possibly some others from SIGN_ST* series were also missed during implementation of #215;
NPAPER01, NPAPER02 are photos of WWI newspapers (dated 1914). Though it might be difficult to find appropriate ones?

**Comment by Tormentor667** [comment]
All fixed.
