### ISSUE TITLE
Remove critters (Rats, Spiders, Bats) from the Killcount

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#238]
Now that the critters behave differently, do you think it makes sense to remove them from the killcount? I missed 3 rats in C1M2 now because they simply got by unnoticed. @AFADoomer

**Comment by AFADoomer** [comment]
The only critter (rats/bats/spiders) that wasn't set with -COUNTKILL was the bats...  I fixed that, plus some other things in commit ba0438f0db114512632f470180c178b477236f85.

**Comment by Tormentor667** [comment]
Thanks man
