### ISSUE TITLE
Secret areas are not visually marked on "AutoMap"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#240]
If I use "iddt" to check the map for remaining enemies, secrets and items, the secret areas have no special color given to them as far as I can see currently. It's hard to find every single secret then. Can this be improved with a special color? (maybe orange) @AFADoomer

**Comment by AFADoomer** [comment]
Should be done as of da53eee5864740c039c0f1ac44ac3ccd64e19e41.
