### ISSUE TITLE
Only 2 "Eisenmann Files" in the "Mission Summary"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#241]
After beating C1M3 and returning to the INTERMAP, I gave another Eisenmann file to Gutenberg. Afterwards I checked the Mission Summary in the briefing room and noticed that only two are displayed there even though I already gave three of them to Gutenberg. 

For a complete report he needs five of them. If I give him another two, the Eisenmann operation is available but the mission summary only displays 4 files. I guess something is wrong with the count display @AFADoomer

**Comment by davidxn** [comment]
I see the same - I wondered if I was just interpreting the display wrong, but I feel I definitely had two on the mission summary after c1m2 and then just one later on.

Is there any other indication of files in the lab, like there is for the Mayan artifacts?

**Comment by Talon1024** [comment]
> Is there any other indication of files in the lab, like there is for the Mayan artifacts?

In the lab, there is a vat with purple liquid. Each time you hand in an Eisenmann document, the purple liquid rises.

**Comment by AFADoomer** [comment]
I don't know how this can happen.  The item is added to the stats board in literally the same script (INTERMAP script 2) as where the script to raise the purple liquid gets called.

I just did two runthroughs (noclipping to the folder, then back to Douglas) from C1M1 to C1M3, and each of the three folders shows up on the board as soon as I present it to Gutenberg, each time with no issues.  Same if I just 'give AktenEisenmann' in the console, then give it to him.

**Comment by Tormentor667** [comment]
What I just noticed - no idea if that helps though - when I came back from the Keen mission (actually after beating C1M4, I went to the lab and used the cartridge), the mission summary only displayed one Eisenmann file where there should be 4. I can't really tell what is happening here but something's odd.

**Comment by Tormentor667** [comment]
Update: After playing C1M5 and before giving the file to Gutenberg, none of the Eisenmann files are displayed now. After giving the file to Gutenberg, one is displayed.

**Comment by AFADoomer** [comment]
I think I may know what is going on...  Did you save, exit the engine, and restore from save during any if these tests?

**Comment by Tormentor667** [comment]
Yes, I did that numerous times indeed, mostly after switching maps for a little coffee break or meal.

**Comment by AFADoomer** [comment]
Ok, yeah, just checked, and the version of the map data that persists across saves doesn't currently include the special item pickup data.  I'll fix it when I get back home tonight.

**Comment by Tormentor667** [comment]
By the way @AFADoomer, thanks a lot and kudos for your commitment. I was talking to @Talon1024 , @Ozymandias81 and @DoomJedi in our Facebook chat today and we are all making so much progress in the past weeks - we are close to the release, we are all doing an amazing job and I am sure that the final release of BoA will have an unique impact to the community and the modding scene in general, not only Doom! And that’s because all of us, also you and the impressive work you did and still do :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 That's good news to hear! Do you have an estimate for the time of release, by the way (e. g. is there a possibility to finish the modification before the 75-year anniversary of the ending of WWII), or it is too early to speculate about this?
I'd also like to suggest a short 'open beta testing' development stage before the release (using a small advertisement campaign across the Doom community to search the mod for the remaining problems). What do you think about this idea?

**Comment by Ozymandias81** [comment]
Yes better come with a release candidate and in case do some more until we are near Cacowards, to be more. And damn yes, without @AFADoomer contribute we couldn't have all these super features in BoA! Happy to be part of a so proficient team guys 🚀

**Comment by davidxn** [comment]
Looks like that worked - seeing the correct count of files now!
