### ISSUE TITLE
Killcount on C1M4 is 165 of 163

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#242]
No idea where the additional 2 kills are coming from but I can confirm the issue that has already been mentioned by @Username-N00b-is-not-available on a different topic.

**Comment by Ozymandias81** [comment]
It should be 2 things: Douglas or an issue with toilet soldiers. Will look.

**Comment by AFADoomer** [comment]
It's probably the two Ryan NPCs (the one at the start, and the other inside the complex)...  If they are tagged as friendly in the map while they are also already set as +FRIENDLY, the engine is probably double subtracting them from the kill count.

**Comment by davidxn** [comment]
That seemed to be it - four Ryan NPCs were on the map, and two of them were tagged as Friendly MBF. Removing that fixes the monster count... will see if I can isolate this and post it as a GZDoom issue

**Comment by AFADoomer** [comment]
Probably something like the logic [here](https://github.com/coelckers/gzdoom/blob/e47f016b23a3146c9bc810ff21c2a3434dc0a716/src/playsim/p_mobj.cpp#L4639) not taking the MF_FRIENDLY flag into account, so it subtracts from the kill count even though the enemy was never added to the kill count in the first place [here](https://github.com/coelckers/gzdoom/blob/e47f016b23a3146c9bc810ff21c2a3434dc0a716/src/playsim/p_mobj.cpp#L4546).
