### ISSUE TITLE
Mission board doesn't reset on starting new game

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#246]
![Screenshot_Doom_20200730_234106](https://user-images.githubusercontent.com/2124623/88997709-47e48800-d2be-11ea-81dd-73e9d699ba11.png)

(Note 0 gold etc on the status bar)

Steps to reproduce:
1. Start BOA and load a game that has some completed missions
2. Go back to menu, New Game, go through intro etc
3. Go straight to the mission board
4. The mission board will show all completed missions from the saved game. If you selected New Game while in a mission, your time for that mission will display as the current map time when you switched to the new game.

**Comment by AFADoomer** [comment]
This should be good to close, just needs review/testing...  I re-opened it after I accidentally closed it, because apparently using the word 'resolve' and referencing an issue number in a commit message auto-closes issues.  Who knew?

**Comment by davidxn** [comment]
Hah, good to know :) I'll give it a try!

**Comment by davidxn** [comment]
Almost there :) Only the Eisenmann files in the PersistentMapData are now a bit too persistent:

![image](https://user-images.githubusercontent.com/2124623/89092252-13d09c00-d37e-11ea-97bb-02e7365a8a7a.png)

**Comment by AFADoomer** [comment]
Thanks.  Try with commit 620c42150f61ddc362aa2eaa70f9161999917b70.

**Comment by davidxn** [comment]
Looks good :) Thanks for getting to these so quickly.
