### ISSUE TITLE
Deactivate compass if you are in a Keen secret map

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#247]
I noticed that the inventory isn't cleaned when you enter the Keen maps. That's just fine I guess but we need a check that deactivates the hud compass if it is active, so it doesn't stay on the screen if you had it activated on the INTERMAP before using the cartridges @AFADoomer

**Comment by Ozymandias81** [comment]
Just had a test with this, I have "give boacompass" on Intermap (testing from folder structure via UDBUilder) and then "give Cartridge51"; after that I have activated the compass and once on Keen map (red cart), the compass indicator and the possibility to select it from the inventory was already possible. The sextant with all data instead doesn't appear in game.

![Screenshot_Doom_20200802_191959](https://user-images.githubusercontent.com/11136108/89128317-32a56e80-d4f5-11ea-9084-fe9dcc790743.png)

**Comment by AFADoomer** [comment]
Should be fixed in 019e99a536e9fd2a1685d377dc2a77537bbdd9b5.

**Comment by Ozymandias81** [comment]
Yes it works, only gripe is that it is still selectable with the tag appearing on screen, but I think it is a minor thing anyway. Thanks!

**Comment by AFADoomer** [comment]
Where does its tag appear for you?

**Comment by Ozymandias81** [comment]
Hey man sorry not on pc anymore, but I had "Compass" appearing in the middle hud weapon sprites, the tag itself. I see you did more tweaks to fix this problem, later tonight I'll test it again if I can

**Comment by AFADoomer** [comment]
Ooh...  I need to account for people who have item name tags turned on.

**Comment by AFADoomer** [comment]
OK, so the nametag behavior is hard-coded and I can't modify it.  I did fix some other bugs, so hopefully this won't be too noticeable to anyone in the end...  'displaynametags' defaults to zero (off), anyway.
