### ISSUE TITLE
Double press to use inventory

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#249]
Not sure if it's possible to code around this, but: When you've been cycling through inventory, you have to double-press Use to use the item you've scrolled to. I think this comes from the original Heretic-style inventory interface, where you would have the display of all the items in a row - the first press closed the display and selected the item, the second press actually used the item.

**Comment by AFADoomer** [comment]
This is already in, I just need to uncomment one line of code.  Didn't change it originally because I was worried that it would throw off experienced ZDoom players...

**Comment by Tormentor667** [comment]
So what is wanted? Double press or single press?

**Comment by AFADoomer** [comment]
The double press always annoys me...  

But, really the only time I can see accidental 'early' activations causing problems would be with people who are using grenades from the inventory bar...  Instead of 'selecting' grenades as the current powerup while behind cover, you just threw a grenade at the wall and died.  Oops!

**Comment by Ozymandias81** [comment]
Same for me, annoys me sometimes, I think probably it is better choose for single press, I vote for that :smile:

**Comment by AFADoomer** [comment]
OK, just committed the change in 175c56fee58258fa68e55833c7a8e50126b9d806.

**Comment by Ozymandias81** [comment]
That's awesome, so it's just that line which controls such behavior... Ah damn zscript :smile:

**Comment by AFADoomer** [comment]
Yeah, it's just the one timeout value that gets changed.  The Alt HUD and the non-fullscreen Strife HUD already works as single-press out of the box...

**Comment by davidxn** [comment]
You're an absolute machine, @AFADoomer :) I'm amazed at the speed that you knock these out!

**Comment by Ozymandias81** [comment]
> Yeah, it's just the one timeout value that gets changed. The Alt HUD and the non-fullscreen Strife HUD already work as single-press out of the box...

Ugh didn't know that, I am always stitch to classic... good to know then, thanks!
