### ISSUE TITLE
Aggressive nazis!

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#252]
Just thought this was worth mentioning, as I played the Chapter 2 release and then the Github copy back to back - the nazis are now much, MUCH more trigger-happy than they were, and often get a shot off into your face if you so much as poke your nose around a corner - this leads to extremely cautious gameplay even on non-stealth maps, having to take each step carefully and make sure that you're in reach of cover at all times. In the earlier version, they gave a bit more leeway and didn't fire so quickly on first seeing you.

If this is intentional and the way that the game is meant to be played, that's fine :) I was just surprised at the difference when I first started.

**Comment by Ozymandias81** [comment]
Well yes, SS guards and Elite ones specially are pretty aggressive and in several situations they are meant to be as they are. Some actors yet needs to be nerfed a bit, like tanks and mechs, but also don't forget that I have included FastSpeed properties if you have FastMonsters enabled though.
