### ISSUE TITLE
C1M0 Douglas can get into and walk on mutant fluid

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#255]
![Screenshot_Doom_20200801_145642](https://user-images.githubusercontent.com/2124623/89114588-3204cd80-d44c-11ea-8ff6-535d06a3e023.png)

Not sure how this happened - there are definitely monster-blocking lines around the pool.

**Comment by AFADoomer** [comment]
Monster blocking lines don't affect PlayerFollowers unless you explicitly un-set the NOBLOCKMONST flag on the actor via ACS.

**Comment by davidxn** [comment]
Aha... is there some sort of PlayerFollower blocker object to use here?

**Comment by AFADoomer** [comment]
No, he just needed to be set to not cross monster blocking lines.

I added this to the map's OPEN script:
`	SetActorFlag(223, "NOBLOCKMONST", 0); // Set Douglas to respect monster blocking lines`

**Comment by davidxn** [comment]
Thanks - closing this!
