### ISSUE TITLE
C1M6 Jumping columns room

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#258]
(Noting these down as it's past midnight - will drop a note if I work on fixing them myself soon!)

![Screenshot_Doom_20200801_234116](https://user-images.githubusercontent.com/2124623/89115348-6761e900-d455-11ea-9767-c7b69a0aa81d.png)

Couple of things here:

- By shooting at the bats here it prematurely wakes a boss character (probably the one with the flamethrower on the pyramid that emerges once you're past here?), making it appear that the bats speak German
- You can jump across to the sand bank about halfway through the jumps, bypassing the rest of the pillars (but I don't consider this a drawback)

**Comment by Ozymandias81** [comment]
The jump is intentional I guess and good for players. Set walls around the room perimeter with blocksound flag, so it should fix the boss issue as well :+1:
