### ISSUE TITLE
C1M6 Boulders disappear into slot

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#261]
(Noting these down as it's past midnight - will drop a note if I work on fixing them myself soon!)

![Screenshot_Doom_20200801_235153](https://user-images.githubusercontent.com/2124623/89115397-f53dd400-d455-11ea-94e5-fd2076a3660b.png)

Near the blue key switch, the boulders that drop down when you approach disappear when they reach the slot in what looks like a temporary animation

**Comment by Ozymandias81** [comment]
Well they simply drop down the slot, so I think it is fine as they are... What do you think @Tormentor667 ?

**Comment by davidxn** [comment]
I was seeing them vanish instantly, rather than drop - I'll try again and get a video

**Comment by Ozymandias81** [comment]
They drop but since they doesn't have a complete behavior, they just drop down quite immediately and fall down in an istant. I might replace these with 3d models and a nice behavior

**Comment by Tormentor667** [comment]
> They drop but since they doesn't have a complete behavior, they just drop down quite immediately and fall down in an istant. I might replace these with 3d models and a nice behavior

Either that or maybe (for an easier implementation) this “instant drop” can be removed with the help of ZScript.

Currently the boulders are floorhuggers, that’s why they appear that way.

**Comment by AFADoomer** [comment]
I have ZScript boulders...  Need to tweak the behavior to be similar to the ones already in BoA, but shouldn't be too hard.

**Comment by Ozymandias81** [comment]
I added the 3d model, it still needs to roll properly and I guess we'll be done with it :smile:

**Comment by Tormentor667** [comment]
It looks good and works well in C1M6 but is it just me or are the boulders no perfect round spheres?

**Comment by Ozymandias81** [comment]
Boulders are not meant to be perfect sphere since made of rock, do they really represent a problem now XD
That boulder model comes form Duke3d Plus btw

**Comment by Tormentor667** [comment]
I understand this but it doesn't make sense that they are flawlessly rolling but are not round spheres. What about using the models for the moon/earth instead? I mean, these are no natural boulders but created by those who created the tomb. It's quite possible that they are perfectly round so the enemy gets crushed the best way possible ;)

**Comment by AFADoomer** [comment]
It's an easy change, whatever is decided.  Just replace boulder.md3 in MODELDEF with planet.md3 and change scale to 1.2 1.2 1.44.

We could even make it frame B and give an option that some can be round and some can be rough.  I already was thinking to do something similar with different textures so that the boulders aren't all identical.

**Comment by Ozymandias81** [comment]
Well no worries, just applying planet.md3, did also a tweak for Ubermutant.

**Comment by Tormentor667** [comment]
Varying the texture sounds reasonable. The new boulders look much better by the way!
