### ISSUE TITLE
C1M6 Skip on lava bridges

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#262]
(Noting these down as it's past midnight - will drop a note if I work on fixing them myself soon!)

![Screenshot_Doom_20200802_000449](https://user-images.githubusercontent.com/2124623/89115414-17375680-d456-11ea-80fd-08a9a96f0744.png)

It's fairly easy to jump from the platform at the near side of the higher bridge to the lower one, skipping the need for the purple key (although how useful it is is debatable, I'm not sure if there's a way back)

**Comment by Ozymandias81** [comment]
Added blockplayers flags to avoid this to happen.

![C1M6 at 2020 08 02 19-11-54 528  R3530](https://user-images.githubusercontent.com/11136108/89128233-7d72b680-d4f4-11ea-9ae1-b08cf47b89de.jpg)
