### ISSUE TITLE
C1M5: Invincible Nazi at the end

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#263]
There's a Nazi that appears near the end of C1M5, and for some reason, he's invincible and cannot be targeted by Allied troops.
![Screenshot_Doom_20200802_130851](https://user-images.githubusercontent.com/6550500/89128660-3de0a600-d4c5-11ea-9194-6a9f3b50a06a.png)

**Comment by Ozymandias81** [comment]
Still the famous issues noticed ages ago with dodge feature and later by N00b again... Wonder if it is still related to that.

**Comment by Ozymandias81** [comment]
Mmh maybe that actor is triggered multiple times because of this, when alone...
![image](https://user-images.githubusercontent.com/11136108/89129259-3ab4dc80-d4fc-11ea-970d-d5218a097b8b.png)

**Comment by AFADoomer** [comment]
All of the wave attack enemies are tagged as 801, though.

It looks like somehow he's never getting to the 'Dodge.End' state, and the code to recover from the roll never gets run (hence why he is tagged with NOPAIN flag, still).  He shouldn't be invulnerable, though; the dodging code only sets them to half damage now.

**Comment by AFADoomer** [comment]
Attempted to fix this in 7f6f992ebacc5880206c89ff4ec4e60275550198.  

I've yet to be able to reproduce the problem on my end, through no lack of trying, but this fix addresses the only logical way that I can think of this to be happening (enemies detecting and trying to escape from grenades while rolling, so being set to See state and skipping the end of the roll).

**Comment by Ozymandias81** [comment]
I remember that in fact actors weren't exactly invulnerable, but with no hitbox at all, at least that's how it was the old behavior issue. Will figure a way to test this as well

**Comment by Tormentor667** [comment]
I played a few maps now of C2 and didn’t encounter this anymore. I guess it is fixed but can be reopened if needed.
