### ISSUE TITLE
C2M1 is enormous

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#265]
Mentioning this as I remember seeing in the blog that you wanted to keep mission size down - C2M1 stands out as intimidatingly large. When you reach the tank hangar you think you're nearly at the end. Then you make your escape and there's another section dodging searchlights, and you think you're almost at Douglas when he contacts you... then there's an entire second base to fight through!

If I were designing it from scratch I would probably have ended it after the outdoor searchlight dodging section, but I don't want to suggest chopping off that entire second part... perhaps find a way to give more of a sense of progress to the player? Instead of Douglas just saying he's to the east, have him warn the player of what's coming up... I'm not sure.

**Comment by Tormentor667** [comment]
Well, I am not sure about this as well. I played the map a few days ago and it indeed felt lengthy. For various reasons the second building is needed but maybe we can decrease it's sheer size or make parts of it optional? (for example you can completely skip if if you don't want to gather the Astrostein files?)

**Comment by Tormentor667** [comment]
@AFADoomer @Ozymandias81 @Username-N00b-is-not-available @DoomJedi @doomjuan  -Sorry for user-name-spamming here but I think this is an important discussion before a decision is made. Let me know what you think about the size and length of the map in general and also what could be done about the flow.

**Comment by AFADoomer** [comment]
I agree that the second half is too long.  

Maybe there can be an "early-out" option at like 1300, -7500, where Douglas is behind a fence with a cut opening and tells you something like, "I know you have more objectives to meet, but we can get you out now." so the player can choose to be done or not.

**Comment by davidxn** [comment]
I think that's a great idea :)

**Comment by Tormentor667** [comment]
I added this option now, let me know if it works

**Comment by Tormentor667** [comment]
> I think that's a great idea :)

Have you tried the latest version of the map and can you confirm that this is a good solution?

**Comment by Tormentor667** [comment]
I think that this can be considered as solved after recent changes.
