### ISSUE TITLE
C2M1 stealth mechanics

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#267]
![Screenshot_BoA_20200802_195646](https://user-images.githubusercontent.com/2124623/89193726-6c698a00-d574-11ea-815a-735db3442f2c.png)

For the most part the sneaking in C2M1 works pretty well, but there are a couple of weird moments... in the area of the second base in the screenshot, the enemies in the room beyond the wall (which I hadn't yet opened) got stuck continuously noticing me and sounding the MGS alert noise. In the office rooms where you're knifing officers one by one, it's often unclear what you did to trigger an alert (are some officers just standing more closely together than others, and so notice a stealth kill happening?)

I also wasn't sure what the icon in the lower right of the status bar was telling me - is that the number of enemies who currently have you in their line of sight?

**Comment by Ozymandias81** [comment]
That number with the eye icon tells you how many ppl have seen you and that are searching for you

**Comment by AFADoomer** [comment]
There's an alarm panel in that room.  If you woke them up once (running out in the open area below is enough - the two scientists  can see you through the windows), then one of them probably hit the alarm.  The alarm will stay active until you destroy it or turn it off, so the enemies in that room will continuously re-alert if they go idle after not seeing you for a while.

Might be best to add another alarm panel outside the room somewhere.

And yes, the eye and number tell you how many enemies are active and looking for you right now.  The number was originally a debug tool, and the eye was going to be the only indicator, but the extra info helps make the stealth sections more enjoyable.

**Comment by Tormentor667** [comment]
How large is the radius by the way?

**Comment by AFADoomer** [comment]
Current alert radius for a stealth kill with the knife is 192 units (probably actually a square "radius" of 192 - haven't looked at the internal code to check).

**Comment by Tormentor667** [comment]
While talking about C2M1, what do you think about shortening the map or rearranging it a bit to make the last building obsolete @AFADoomer ?

**Comment by Tormentor667** [comment]
We will talk about this in the other issue, therefore closed.
https://github.com/Realm667/WolfenDoom/issues/265
