### ISSUE TITLE
C1M6 Boss very easy

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#268]
In contrast to the nightmare of a time I had with the evil spirit ??? boss in the Chapter 2 release, I had absolutely no trouble at all with it this time around - it floated slowly around and I was able to just smash it with the shotgun over and over until it eventually exploded.

Would anyone mind if I had a try at making its attacks a bit more elaborate?

**Comment by Ozymandias81** [comment]
Well depends, since there is also the Zyklon monster which is its hard counterpart. So many ppl had issues with it in the past, so idk if it is good to change its behavior again.

**Comment by Tormentor667** [comment]
Well, I am okay if you want to try something out - just make sure that the Zyklon counterpart that @Ozymandias81 has mentioned gets a similar treatment.

**Comment by davidxn** [comment]
Thanks, I'll give it a try with the understanding that these changes may ultimately not be used :) I'll play through C3 first to see how the Zyklon enemy behaves

**Comment by Ozymandias81** [comment]
The Zyklon enemy is present only on the last map with the same arena per space, in case you wonder

**Comment by davidxn** [comment]
I've just accidentally discovered what neutered the boss compared to previous versions - it's the HeatEffectGivers. The boss uses SkullAttack to lunge forward (which was a devastating attack in the Chapters 1+2 release) - I imagine now that the HeatEffectGivers are there it's running into the oddity with Lost Souls' movement that stops their charge if there is any object in their path, even non-collidable ones: https://doomwiki.org/wiki/Lost_soul_colliding_with_items

**Comment by davidxn** [comment]
https://www.youtube.com/watch?v=T7faRN6Ri3o Here's a demo of the idea I had, with log messages intact to show its state - it goes in and out of hiding, spawning a couple of homing blood skulls either when it's been damaged enough or when it's been out for too long (increasing based on how low its health is).

**Comment by Ozymandias81** [comment]
I like the changes! While the creature has been nerfed after C2 release, it seems obvious that something is disturbing the monsters behavior yes, didn't had any free time to playtest the consequence of adding new shaders... I wonder then if we give a certain class to HeatEffect and make then Bloodskulls THRUSPECIES to avoid the issue. What do you think @AFADoomer ?

**Comment by Tormentor667** [comment]
> https://www.youtube.com/watch?v=T7faRN6Ri3o Here's a demo of the idea I had, with log messages intact to show its state - it goes in and out of hiding, spawning a couple of homing blood skulls either when it's been damaged enough or when it's been out for too long (increasing based on how low its health is).

Well, considering that you lost 8 hp during the whole fight (Not taking the grenade damage into account), how much of a better challenge was that now? :(

**Comment by Ozymandias81** [comment]
We need to wait AFA fixes for the heateffect and then see how it behave, it seemed a good addition. What we need also is that the smoke attempt to reach the player and "ripper" it more oftenly to make more damage, but we must be careful due to past feedbacks about this creature.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 @Ozymandias81 What are your thoughts on the current situation with C1M6?
I've played through the map on Mein Leben just now, and to me it seems that the fight is now balanced pretty well.

**Comment by Tormentor667** [comment]
Do you mean the Boss battle? I just tried it and it works perfectly fine in my eyes, so this can be closed.
