### ISSUE TITLE
C1M6 rock hitbox problem

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#269]
There's some odd hitbox stuff going on around the place where you could jump up near the skybox near the turret previously.

![Screenshot_BoA_20200802_162934](https://user-images.githubusercontent.com/2124623/89194398-4c869600-d575-11ea-811b-268e72e6e012.png)

**Comment by Ozymandias81** [comment]
Well I added blocking invisible bridges to mimic proper collision, but probably the rock setup is wrong... Gonna check.
