### ISSUE TITLE
Verify Keen actors since now enemies have all rotations

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#271]
I am dropping this here as a reminder, and I noticed that probably Dopefish and Schoolfish first may need some changes.

**Comment by Tormentor667** [comment]
I played SM01 a few days ago and didn’t notice any problems so far. Will test SM02 and SM03 during my play tests in the next 2 weeks

**Comment by AFADoomer** [comment]
The only actors that might need any adjustment (assuming the sprite rotations are all correct) would be Dopefish - right now he faces the viewing player when he burps, so the rotation sprites for that frame are hardly visible, and the Wormouth - during his 'looking around' state, he's supposed to blink, and the original frames were missing rotations for that blinking frame (I haven't checked to see if they're there or not, now).

I also noticed Lindsey not disappearing after her message is displayed.

**Comment by Ozymandias81** [comment]
I am not an expert at all with Keen games and also about the easteregg we have on BoA, so I'll fully trust your changes and playtest all 3 maps when I can, since SM02 is also heavy on my machine.

**Comment by Tormentor667** [comment]
I have played Keen in my youth a hundred times, especially Goodbye Galaxy. I think I will be able to check these properly :)

**Comment by Tormentor667** [comment]
@AFADoomer - One problem that I noticed while trying the secret maps for Keen is, that we get the usual "The End" music and screen if Keen dies. Instrad I'd suggest doing what the original Keen games do: Stop music and fade out the screen to black until the player hits "space" to restart as usual (just the normal GZDoom behaviour).

**Comment by Tormentor667** [comment]
After playtesting all the 3 maps, I can clearly say that everything else seems to work fine and perfect in terms of authenticity. I approve the enemy behaviour so this can be closed as soon as the "The End" issue is solved.

**Comment by AFADoomer** [comment]
"The End" issue should be fixed as of 95d3e3b032f2b95170838f0b551fb6a9a2ec934f.
