### ISSUE TITLE
Add compass markers and objectives to all C3 maps

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#272]
As the title says, we need to verify which ones still miss these, surely C3M5 maps and C3M0.

- [x] C1 - These have been set and fixed long time ago, should be done.

- [x] C2 - After recent changes to maps, I'll need to check again maps to avoid missing markers. Objectives shouldn't be a problem.

- [x] C3 - There is a lot of work to be done from C3M3 I think till the end, many of these maps doesn't have markers and the last map needs proper 1st objective yet.

**Comment by Tormentor667** [comment]
How far did you get with that? :)

**Comment by Ozymandias81** [comment]
Be patient, this will require some time and don't have much yet. I still need to work for this issue, first need to fix lights and generic scripts then time for this 👍

**Comment by Ozymandias81** [comment]
Okay getting started again with this from today, let's see

**Comment by Tormentor667** [comment]
Very good :)

**Comment by Ozymandias81** [comment]
C2 seems okay, still going through C3 and now it should come the hardest part, already checked C3M2-3-4

**Comment by Tormentor667** [comment]
Keep it comin' - we are almost done :)

**Comment by Ozymandias81** [comment]
Very sorry for the slow work, but you know why... I need to check better c3m5_c then go through C3m6 and c3m0 and it should be done.

**Comment by Tormentor667** [comment]
All fine, I was just checking, I hope we get this soon solved and can start with the real beta tests :)

**Comment by Tormentor667** [comment]
@Ozymandias81 - I think this is the last remaining issue that prevents us from starting some private beta tests with modders from the Doom communities (at least the english version). Do you think you can take care of this soon? (just asking)

**Comment by Ozymandias81** [comment]
Working on it atm :)

**Comment by Tormentor667** [comment]
Wohoo! What is left?

**Comment by Ozymandias81** [comment]
C3M0_B, C3M6 maps and probably C3M1. C3M0 and C3M6 maps still also needs fixes from me as well too

**Comment by Tormentor667** [comment]
Lets go for it, the beta test is nearing :)
