### ISSUE TITLE
Add switchable lights to all maps for consistency reasons

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#273]
Reminder for things that needs to be updated throughout maps (C3 mostly, C1 is completely done, C2 needs to be verified)

- [x] C1 - Added a few places that still miss lights, maybe the bank zone may benefit from 3d floors light switches as well like on c2m1/c3m1, but overall everything is set.

- [x] C2 - Needs to be investigated, C2M1 will be checked last to be sure that everything works properly.

- [ ] C3 - Several maps may still require lights and C3M1 maps will need same treatment as of C2M1 (so last one to be checked)

**Comment by Tormentor667** [comment]
Great job Ozy!

**Comment by Tormentor667** [comment]
How far are we with that?

**Comment by Ozymandias81** [comment]
Not much left, I just need time to investigate final c3 maps, which I am working already for c3m5_b

**Comment by Ozymandias81** [comment]
Beside c3m0 maps, everything else should have been fixed and properly implemented, so gonna close this.

**Comment by Tormentor667** [comment]
Awesome 💯
