### ISSUE TITLE
Finishing C3M0_A

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#274]
I think it is time to talk about what we do with C3M0_A - how to finish it, what to change with it. There is still a big portion that’s left to be done and I don’t know how to organize finishing it now.

@AFADoomer - What plans do you have with it currently and what can I do/help with?

**Comment by AFADoomer** [comment]
I've got nothing.  Last version that I uploaded can be worked on by whoever...  The movie theater and opera house need a lot of cleanup and detailing, and there's a green gem item (on the pushable/breakable statue) that I added that has no purpose right now - was thinking to make it activate something in the 'hunting cabin' basement area that would give the player the green vial (ZyklonResistance) powerup (decreased Zyklon/UndeadPoison damage).

I'm not sure how much time I'll have to work on the map...  Got a promotion at work, so I'm moving to a new position this week.

**Comment by Ozymandias81** [comment]
I might also suggest to include Erik the phantom of the Opera, maybe a secret alcove hidden that reveals using the gem, remember DoomJuan idea to hunt him behind the theatre in a 1920's like fashion horror movie. Probably AFA suggestion and this idea could be linked together to prepare something.

**Comment by Tormentor667** [comment]
Congratulations for your promotion @AFADoomer :) 

Regarding the map, I will continue my playtesting and cleanup for C2 this weekend and then, when I am done, proceed with C3M0_A. Let’s stay in contact here maybe, so as soon as your time window looks better, we can collaborate

**Comment by Tormentor667** [comment]
I started playtesting and working on C3 yesterday and today. I will continue with that but ignore C3M0_A for now, checking if everything else is working out well in Chapter 3. As soon as I am done with that, I will concentrate on C3M0_A and try to finish it up.

I am pretty sure that it is close to being finished but I have to be honest - I am lacking motivation for mapping atm. I can't tell why, but I guess it's the typical mappers block that I am suffering. 

If anyone is willed to continue instead until I am done with the C3 playtests, feel free to do so (@AFADoomer @doomjuan @Username-N00b-is-not-available )

**Comment by Tormentor667** [comment]
Now that I am done with playtesting and dev comments, I will concentrate on this one again next weekend. FINALLYY

**Comment by Username-N00b-is-not-available** [comment]
Can't wait to playtest the full map, finishing it will mean that we are mostly done with the project.

**Comment by Tormentor667** [comment]
Finally done with everything else that was relevant to be done. I am now fully concentrating on C3M0_A and will finish that beast as soon as possible.

**Comment by Tormentor667** [comment]
Doing it on my own now, I think I will make it :-)
