### ISSUE TITLE
Testing dialogues with TEST_DLG map

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#275]
Just got a message from one of the translators:

> Hello again!
> Sorry to bother you again.
> 
> I am attempting to test in-game the messages such as BARKEEPERCONV02 with Juliette.
> In the test_dlg map, I can only see the messages BARKEEPERMESSAGE01 from 1 to 6 and that's it. But that's in the dialogue section. Now there is a 2nd Juliette in the Convo section, but she does not say anything.
> Also, the two Douglas seem to say the same stuff. Even in English. Am I missing something?
> 
> Many thanks!

@Talon1024 can you investigate this?

**Comment by Username-N00b-is-not-available** [comment]
The two types of dialogues (in-game messages and Strife dialogues) are also 'messed up' in the CSV, see Stierlitz for obvious example. This affects only TEST_DLG though; during normal play everything works AFAIK correctly.

**Comment by Tormentor667** [comment]
Has this been taken care of already? I guess it’s something that @Talon1024 is responsible of, as the system is his work - isn’t it?

**Comment by Tormentor667** [comment]
Push - any news about it?

**Comment by Tormentor667** [comment]
Low priority, therefore closed
