### ISSUE TITLE
Cutscene in Chapter 2 (after C2M4) needs work

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#276]
I noticed that the messages in the lower right corner are wrong (copy from the cutscene in Chapter 3) and it also needs the music fading that is already used in the other two cutscenes.

**Comment by Username-N00b-is-not-available** [comment]
I know about these problems and will try to resolve them soon. Thank you for opening this issue as a reminder.

**Comment by Ozymandias81** [comment]
I'll try get some frames for you then, videos where usually got by DoomJuan which is almost inactive now. Will ask to him first.

**Comment by Tormentor667** [comment]
> I'll try get some frames for you then, videos where usually got by DoomJuan which is almost inactive now. Will ask to him first.
No need to, Ozy, simply decide yourself.

**Comment by Ozymandias81** [comment]
Okay, in case you need some fitting props @Username-N00b-is-not-available [I added](https://github.com/Realm667/WolfenDoom/commit/a03cf6893afe5e3152e393fea290aa000f24178b) Panzer parts (just two) as suggested by DoomJuan on FB chat, and also these are [the](https://youtu.be/sEMSredB6nU) [videos](https://youtu.be/4-y_oz06_cQ?t=625) that could work for the map.

**Comment by Tormentor667** [comment]
Just posted my update on the cutscene, there are problems with the quality of the video frames. The JPG compression is so strong that it generates a lot of artifacts and you can only assume what's happening in the video.

Other than the texts, it should work well so far though.

**Comment by Ozymandias81** [comment]
Found a solution that will require some time, but I can do it. This is a jpeg format
![PANZ_008](https://user-images.githubusercontent.com/11136108/91246613-8ef45a80-e750-11ea-9c71-602dc2da5d42.jpg)

**Comment by Tormentor667** [comment]
That's so much better!

**Comment by Ozymandias81** [comment]
Will continue between today and tomorrow with PANZ tx, should end around these days :)

**Comment by Tormentor667** [comment]
So are you done with your fixes? :)

**Comment by Ozymandias81** [comment]
Still need to upload some PANZ tx ans verify the map, so I am still at it yet

**Comment by Tormentor667** [comment]
I am fine with it now, well done!
