### ISSUE TITLE
Cannot edit language.csv

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#279]
@Tormentor667, about two months ago I have lost access to editing English cells in the language.csv. I have written about this problem in different places (here on github and in the comments section of the spreadsheet), but it has still not been resolved.
Could you please allow me (c0nc37n3dc1t123n) to edit the protected cells?

**Comment by Tormentor667** [comment]
Can you just send me your Google E-Mail? I will instantly add you :)

**Comment by Tormentor667** [comment]
You should be able to edit it again
