### ISSUE TITLE
General suggestions

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#280]
While being on vacation I have compiled some lists of bugs to fix and ideas to discuss. I'll add the information about bugs to the respective issues later (**edit**: done), and here is the idea list. Please edit this post and add your thoughts or comments on these:

<details> <summary>Closed suggestions</summary>

- [x] Remove the secret C3 chest until returning from C3M1? The SS would have found and taken the gold from BJ.
- [x] Add backpack to C3 shop?
- [x] Make STEN unavailable for buying before C1M4 (it is given in the map)?
- [x] Make use of the SECRETS lump? (AFAIK it has not been externalized yet, we can ask about it)

> Made some use of it, waiting GZDoom code change to include all secrets properly --N00b

- [x] Add a shotgun Wehrmacht soldier for trenches (he will shoot 4~5 pellets at once)?
>Spriting it would be a little nightmare, trust me. But if you want to make it, it is welcome. --Ozy81

>Yeah, another 77 frames (+5 for rolling animations), this is at least four or five hours of work; though since we have a rifle soldier we can just replace the rifle with the shotgun (which can be rescaled from its hires pickup sprite). I am more concerned with the balance: will such a hard hitter be appropriate in the fights, maybe fights with him could frustrate the players? --N00b

> Are the Wehrmacht rifle troops not hard enough? They shoot twice, and each shot deals about 20-40 damage. There's also the Wehrmacht and SS grenadiers. - Talon1024

> I want to add a variation specially for short ranges in some maps. --N00b

- [x] Invert shootability on some grate 3d floors?
>An engine limitation prevents projectiles from going through solid 3Dfloors --N00b

- [x] Draw and add a (regular, as opposed to elite) SS flamer? They can be used in maps like C1M5, C3M1_B, C3M3_C... I'd have drawn one myself but even the easier Afrika Korps one took me several hours.
>If you consider that Elite one are already black, and that adding SS ones may be redundant, since we see them more on C3 maps than C1-C2, I think it is better to keep things as they are and not add such variant (which was planned in the past, you can notice it on how did I name bmaps on boadefs before, but then it has been scrapped due to this fact). --Ozy81

>There are many buildings in the maps which are filled with SS enemies and have only flame soldiers from Wehrmacht (for example, the exposition in C1M5). Well, maybe it's okay since there are also enemies like scientists and mechanics, and it is not needed to dress everybody in similar uniforms. --N00b

- [x] Add instakill damage in c1m6 boss lava pit?
>Afaik one can't leave the pit in the end, so I think we can feel the players how painful that lava is slowly :tongue: --Ozy81
>I think now I agree with you on this. --N00b
- [x] Put a sniper rifle somewhere in C2M1, as there is a chance not to get one from the snipers?
>This can be added before we reach the courtyard outside on the purple key zone with tanks, I think it should work yes. --Ozy81
>This solves the problem only on first three skills, but okay. --N00b
- [x] Use the Nazi salute sprites for SS MP40 'guards on duty' in C3M5_C?
- [x] What's the team's current opinion on the possibility of recording voiceovers?
>Afaik it is planned to have voiceovers when all translations, or at least dialogues will be 100% complete. Probably an external file like on Strife. --Ozy81

>More like 'if' instead of 'when' :-) Got it, thank you. --N00b

:x:  Breakable windows in more maps, not in C3M0_A only?
> Mmmh well if you consider how hard would be distinct visually which should be the one "good for break" and "not good", this may confuse players, and only a couple of maps may benefit from this. It is something I suggested during C2 release figures, but we thought that it is better to avoid these kind of things. But I am open to adding it, what do you think @Tormentor667 ? --Ozy81
> I guess no reply means no need to implement these changes, since I already told to Torm 2 years ago this kind of thing but he wasn't okay with it. So won't happen. --Ozy81

:x:  What about adding some secret minigames to the maps? For example, <strike>Automap Asteroids</strike> a Windows Minesweeper game. The algorithm is the least concerning problem, I've tried to incorporate the special handling into the minesweeper handler's code but failed miserably, couldn't even get a working example...
> While this would be a cool add, it will require too much effort codewise to get implemented so I don't think that this will happen with official release. --Ozy81

:x:  May I change the generic 'Mecha'/'Nazi Mecha'/... in the texts to 'Panzerklein' in reference to this game? https://en.wikipedia.org/wiki/Silent_Storm
> Mecha sounds more Wolfenstein related, if you think about Mecha Hitler, so guess we'll stitch to its original name, which was given by me too :) --Ozy81

:x:  Add a random chance (1/32?) that weak enemies (scientists and mechanics) surrender and drop their weapons after seeing the player? After that they should be marked as friendly, so the enemy soldiers will shoot them.
> This may cause more issue than we have already with dodging/crouch features, so better not make things more complicate than they are already. --Ozy81

- [x] Add a flag for 3dmodel objects that does not allow them to disappear at a long distance from the camera? My CUTSCEN2 has a moving train, and if the player has the clipping distance set to very low, they will be able to see 3dfloor platforms, soldiers, etc. moving on thin air.
> We can simply add cutscene actors variants as I did for some in several occasions and for skybox related things, so while adding the flag may be a good solution but also not exactly clear for mappers (and probably not good for thinkers), we can include cutscene variants on purpose once CUTSCEN2 map will be ready. --Ozy81

>Yes, the cutscene variants would be great. --N00b

- [x] Add 'zombie reinforcements' to C3M2 as spoken by Miller?

- [x] We have Templar cultists in some maps; what about Thule cultists for C3M1–M4? We have SS officers with occult attacks, but what about the high ranks of the cult?

>Added, what do you think of this enemy? --N00b

> Not yet... --N00b

- [x] Move the chaingun to other weapon slot, as slot 5 is too overloaded? I suggest slot 8.
> Well too many ppl are used with Doom set of weapons, and we have rifle related ones on that slot, so moving it on a different slot I think it would turn it not exactly intuitive. What do you think @Tormentor667 ? --Ozymandias81

>The UMG43 is a very rare superweapon, and the rifles are regular weapons which also have a completely different purpose. It is very inconvenient to press the button 3 times to change to Kar98k. Also the chaingun shoots pistol bullets, not rifle ones (but moving it to slot 4 would be equally bad). As for the Doom controls, why do we have a rocket launcher in slot 6 then? :P --N00b

- [x] Clip the troops' long alert sounds on death?
> Where does this happen?  Their death scream cuts off their alert sound.  Both play on CHAN_VOICE. - AFA

- ❌  Print the total coins collected in stats screen? _[assigned to @AFADoomer]_

> Maybe it was not a good idea, now it seems redundant to me... --N00b

> During the regular death, yes, but not in the gibbing animation: [xdeath.zip](https://github.com/Realm667/WolfenDoom/files/5140490/xdeath.zip). Maybe other special deaths also have this problem, I did not check. --N00b

- [x] Add Ryan pain/death sounds to C3M0_B?

> Kind of done this, but death sounds do not work, needs fixing --N00b

- [x] Add switches on all floors for the main lift in the Eisenmann facility?

- [x] Add some caches of grenades (around 12 pieces?) in the player's path to the exit of C3M0_A? It is now mandatory to destroy the Tiger before exiting, but there are too few grenades to do this, so the player needs to get the Panzerschreck, which lies in an optional area.

</details>

- [x] Organize some sort of a hidden speedrunning contest after the release?

> I have some ideas on special categories. <strike>Nazifist</strike> Pacifist would be really hard to accomplish even on C1M1 (the corridors are too cramped), but a fast melee-only playthrough would be nice to watch (and not be very hard for a skilled player to do either). What we probably need to ensure for this is the presence of shovel on all or most of the maps :-) --N00b

> Just finished playing C1 melee-only on Bund Deutscher Madel, and overall it's quite manageable, except from the PzKpfw. IV you have to destroy in the last wave of C1M5 to progress. C1M0 experience would really benefit from a shovel though (I can think of adding a small pit which is about to be used for burying a dead dog by one of the German soldiers in the area just before the complex entrance). --N00b

> I will schedule this to some point after the release. The question is: What is the prize? --Tormentor667

> Fame! We can encourage high-skilled players to play our mod this way. BTW here the demo playback feature could be very useful (we'll pick the 'standard' version of GZDoom after the release anyway, so desync won't be a problem).
BTW it doesn't have to be only speedrunning, I'm planning to finally implement the cipher images (for PAPERTEXT57 and 58) into the game, and also thinking about other categories. --N00b

- [x] Instakill the flamer soldiers if they take significant (~20) flame/explosion damage? _[assigned to @Ozymandias81]_

> As for explosive enemies, we also have grenadiers and kamikaze zombies. --N00b

- [x] Add a small cutscene with the crate just before the end of C3M5_B? _[assigned to @Username-N00b-is-not-available]_

> ATM don't have much ideas for enhancing it further, so any help is welcome... --N00b

- :x: Add alternative attacks, other animations and combos to regular melee weapons? They are slow and very boring now, both that of a knife and a shovel (the sounds are good). Kick randomly with either your left boot or right one? 
> For this we'd need artists who are capable of drawing sprites for that, we simply do not have a person or the resources to do these and it is not top-priority --Tormentor667
- [x]  "give all" cheat does not give "Totale Gier" and "Totale Macht" powerups, this should be added. _[assigned to @Ozymandias81]_

> AFADoomer fixed it here: https://github.com/Realm667/WolfenDoom/commit/6e5744d9ef8936fddf51da3f394111a86040e934 --N00b

- [x]  "give all" gives 25 skull keys, this should not happen. _[assigned to @Ozymandias81 and @Talon1024 ]_
> Cheats are not important imho, so there is no need to go crazy with codes to adjust cheats accordingly. --Ozy81
> Well, yes, but I doubt it is too complicated to add "Gier" and "Macht". I will try to take care of both issues. --T667

- [x] What about adding an ability to drive Pz. Kpfw. IV and using it either on C3M2 or C3M5_A instead of M4 Sherman? Both maps are good choices, since there is little explanation why 1) the crew got off the non-damaged tank in C3M2 and 2) how the hell did the M4 get to the place we can see it in C3M5_A.
It probably should not be too difficult to add Pz. IV, since we already have all the code and the models.

> Added it, thanks to AFADoomer's code it was even easier than I thought, now what's left is to decide if we should add it to one of the maps or not. I'd like to place it in M5_A instead of the Sherman, this will require some text editing, but the German tank choice would be more reasonable for a fully barricaded street. --N00b

**Comment by DoomJedi** [comment]
It's not only copy-paste of rescaled shotgun (pickup is one direction only btw, rotating weapon is hard work) - part of weapon is hidden by enemy/enemy hands from quite some rotations, it's still hard work.

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi Nice to see you here again!
This set of frames was done based on the rifleman sprite in ~30 min IIRC, for the majority of the weapon frames (except 3 and 7) I used non-interpolated rescaling:

<details><summary>Shotgunner sprites</summary>

![RGR2A1](https://user-images.githubusercontent.com/59409713/91277064-034bef80-e78b-11ea-9427-36bb015f8d23.png)![RGR2A2](https://user-images.githubusercontent.com/59409713/91277072-047d1c80-e78b-11ea-9316-08ca11f99a70.png)![RGR2A3](https://user-images.githubusercontent.com/59409713/91277073-0515b300-e78b-11ea-8b98-b7b3aa434856.png)![RGR2A4](https://user-images.githubusercontent.com/59409713/91277076-05ae4980-e78b-11ea-87bd-73c92229c2e6.png)![RGR2A5](https://user-images.githubusercontent.com/59409713/91277077-0646e000-e78b-11ea-8e47-6236cea793d4.png)![RGR2A6](https://user-images.githubusercontent.com/59409713/91277079-06df7680-e78b-11ea-91b5-af28505d7991.png)![RGR2A7](https://user-images.githubusercontent.com/59409713/91277081-07780d00-e78b-11ea-9dc7-a2f3e5a0e3aa.png)![RGR2A8](https://user-images.githubusercontent.com/59409713/91277085-0810a380-e78b-11ea-909f-716191632d91.png)
</details>

Then I realized that it was the wrong shotgun :-)

I know this ought to be long, but want to draw the sprites myself. I am just asking this question to ask if this work will be useful or not. As for the hidden parts, the process is really quite lengthy but not too bad (I had to do this with the AK flamethrower soldier recently, but with his clothes instead of weapon).

**Comment by DoomJedi** [comment]
About usefulness - it's a question to Virg/Torm.
I can only refer artwise - send me 1-2 first frames to check the work, then I'll say if those are good enough by quality standards.

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi Are these OK? I made the shotgun a bit shorter than the Kar98k, but since the rifle is already not to scale I did not pay any extra attention to this :-)
Note that when these 8 are done, 40 or even 48 other frames can be just copy-pasted upon, and there will only be aiming/firing and death sprites left (or also the rolling ones).
<details><summary>Shotgunner sprites</summary>

![RGR2A1](https://user-images.githubusercontent.com/59409713/91290612-7d38a480-e79c-11ea-878c-7251214b1aaf.png)![RGR2A2](https://user-images.githubusercontent.com/59409713/91290614-7e69d180-e79c-11ea-940e-f327ff27ef6c.png)![RGR2A3](https://user-images.githubusercontent.com/59409713/91290617-7f026800-e79c-11ea-8c50-b3eece1d723c.png)![RGR2A4](https://user-images.githubusercontent.com/59409713/91290620-7f9afe80-e79c-11ea-9071-9d5e259df333.png)![RGR2A5](https://user-images.githubusercontent.com/59409713/91290623-80339500-e79c-11ea-8279-9b69d8993005.png)![RGR2A6](https://user-images.githubusercontent.com/59409713/91290626-80cc2b80-e79c-11ea-92af-d16eedb9b866.png)![RGR2A7](https://user-images.githubusercontent.com/59409713/91290629-8164c200-e79c-11ea-8081-06af1fdee914.png)![RGR2A8](https://user-images.githubusercontent.com/59409713/91290631-81fd5880-e79c-11ea-9e1c-7d13fbbc2388.png)
</details>

**Comment by DoomJedi** [comment]
Not to my level of perfectionism (have my perspective nitpicks to some rotations), but quality-wise dose the job.
If I'll fix your one set of frames, can you paste them over the resrt?

**Comment by DoomJedi** [comment]
![91290626-80cc2b80-e79c-11ea-92af-d16eedb9b866x1`](https://user-images.githubusercontent.com/18686908/91302735-9c8cfd00-e7af-11ea-8dbd-95480ed1a86c.png)
![91290620-7f9afe80-e79c-11ea-9071-9d5e259df333x1](https://user-images.githubusercontent.com/18686908/91302736-9d259380-e7af-11ea-9bc7-acc335f09f81.png)
![91290614-7e69d180-e79c-11ea-940e-f327ff27ef6cx1](https://user-images.githubusercontent.com/18686908/91302737-9dbe2a00-e7af-11ea-8687-6d0dd96520fb.png)
![91290631-81fd5880-e79c-11ea-9e1c-7d13fbbc2388x1](https://user-images.githubusercontent.com/18686908/91302741-9e56c080-e7af-11ea-99f4-b78582438108.png)

**Comment by Username-N00b-is-not-available** [comment]
These are four, and what about four other ones? Are they okay?
BTW I've already done all sprites...

**Comment by DoomJedi** [comment]
Maybe some small nitpicks, but don't think worth editing. They look fine enouph as they are, good work!

"Nice to see you here again!"
Thanks, never left, I take part on facebook group discussions, these days work on fixing BJ story pics. I do follow what is going here, but take interest mostly in art-related discussions/tasks, and things that refer to C3M1 which is a more personal map for me.

You are doing amazing work here, pal, your feedbacks and fixes are very valuable.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 @Ozymandias81 Do you have any opinions on the remaining checkboxes?

**Comment by Tormentor667** [comment]
Here are my comments :-)

Suggestion | Tormentor667's opinion on that
------------ | -------------
Clip the troops' long alert sounds on death? | :white_check_mark: Yes, please, can you take care of that? 
Organize some sort of a hidden speedrunning contest after the release? | :ballot_box_with_check: That surely can be done, but currently it's low priority.
Add Ryan pain/death sounds to C3M0_B? | :white_check_mark: Very good idea, can you take care of that?
Add switches on all floors for the main lift in the Eisenmann facility? | :eight_pointed_black_star: Can you elaborate this in detail?
Instakill the flamer soldiers if they take significant (~20) flame/explosion damage? | :ballot_box_with_check: I am okay with it but I it is not high priority for me
Print the total coins collected in stats screen? | :eight_pointed_black_star: Which stats screen do you mean?
Add 'zombie reinforcements' to C3M2 as spoken by Miller? | :o2: The dialogues regarding this have been changed as I don't want to make Zombies appear before C3M4 in a huge number.
Add a small cutscene with the crate just before the end of C3M5_B? | :eight_pointed_black_star: I like the idea, but I have no idea what to do here. As you did a great job on the CUTSCEN2, would you volunteer for that?
Add some caches of grenades (around 12 pieces?) in the player's path to the exit of C3M0_A? | :o2: Are you sure that you mean C3M0_A? It is still not finished and there is no exit anyway.
We have Templar cultists in some maps; what about Thule cultists for C3M1–M4? | :o2: This has already been adressed.

**Comment by Username-N00b-is-not-available** [comment]
Thank you, and what about the last two checkboxes after 'Edit (13 Sep 2020 and later):'?

---
Long alert sounds are not clipped only in special death states which do not play any sounds, e. g. XDeath from a grenade explosion (canonical example is C1M4's lift with four MP40 guards). I think fixing this is best left to @AFADoomer, because he knows the internal structure of base classes much better than me and is less likely to introduce sneaky bugs which will arise in some totally unrelated context.

On the Eisenmann facility lift: you can drop from one floor to another and not die, but you will prevent yourself from finishing the map, as you will not be able to call the lift from below. Hence the proposal.

The INTERMAP stats screen.

Ehhh, I probably don't have time for map editing now. The idea I got is to explain how the crate with Blazkowicz gets to the airship: we can show the final platform rise from the ground, and then the crates on it are are transferred with a crane or something else to the cargo section of the airship (for this you can use e. g. 3dmodel crates).

Damn! Not C3M0_A, it was C3M1_A.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Thank you, and what about the last two checkboxes after 'Edit (13 Sep 2020 and later):'?

---
Long alert sounds are not clipped only in special death states which do not play any sounds, e. g. XDeath from a grenade explosion (canonical example is C1M4's lift with four MP40 guards). I think fixing this is best left to @AFADoomer, because he knows the internal structure of base classes much better than me and is less likely to introduce sneaky bugs which will arise in some totally unrelated context.

On the Eisenmann facility lift: you can drop from one floor to another and not die, but you will prevent yourself from finishing the map, as you will not be able to call the lift from below. Hence the proposal.

The INTERMAP stats screen.

Ehhh, I probably don't have time for map editing now. The idea I got is to explain how the crate with Blazkowicz gets to the airship: we can show the final platform rise from the ground, and then the crates on it are are transferred with a crane or something else to the cargo section of the airship (for this you can use e. g. 3dmodel crates).

Damn! Not C3M0_A, it was C3M1_A.

**Comment by Tormentor667** [comment]
Fixed two more issues and updated my table.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 @Tormentor667 @Talon1024 I have thought about the possibility of adding some references to World War II cryptography. My idea is adding encrypted texts to a level or two, and a note which can help to decipher them (not fully: the player will still have to solve a small part of the riddle on their own). As for now, I have almost prepared both the message and the note. I would like it to be placed into the camp's Gestapo department in C3M1_A or _B.
What do you think of this idea? If you like it, what room in C3M1 would you suggest to use?

**Comment by Tormentor667** [comment]
I need to see it in action to make a decision :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 I've updated the CSV. PAPERTEXT57 has the complete explanation the cipher, and 58 is the encrypted message itself.
The following is the page I used for the 'gamma' (obfuscation) part, this should be put as a hi-res texture on a sector book in the supposed Gestapo room (or on a film projector — may I use the zombie slideshow one for this? :-D )
![PPN514401303_1935___800___0___00000355](https://user-images.githubusercontent.com/59409713/97356849-f0988880-18a9-11eb-9c57-34d141b8db8e.jpg)
The player only needs to find out what the agent's codeword is, and then they will be able to manually decipher the text with all this knowledge if they want (or better write a program, since living in XXI century allows it). When you're done (if you want to decipher it yourself), please tell me the plain text via email, please do not post it here.
I really hope I did not make any typos in these :-)
P. S. The cipher might seem quite complicated (and obviously it is), but it does not relate to gameplay in any way, so I thought such a thing would be appropriate.

**Comment by Tormentor667** [comment]
Just read the explanation and you are indeed write: It is complicated :-) To be honest, I am lacking the time currently to decipher the text and even though it is a nice addition, I have two questions atm before adding any kind of that:

- What is the reward for the player if he deciphers this?
- How high are the chances that even a single player wants to decipher that and spend so much time?

I kinda like it, but I simply think it doesn't fit into the mod. It's not a puzzle game, it's a 3d action shooter with a story, and I doubt that people expect something like that or even want to solve it. But that's just my thoughts :) What do the others think?

**Comment by Ozymandias81** [comment]
I find it too much complicate and out of bounds as BoA addition, I highly doubt that players will try decypher it and well there are enough things to investigate and take care already during gameplay.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Two days ago you've edited my post but placed the new checkboxes into 'Closed suggestions', where nobody would have seen them :-) I moved them to the post body.

**Comment by Tormentor667** [comment]
...ugh good spot, thank you :)

**Comment by Tormentor667** [comment]
Adding a different kind of cutscene between C3M5_B and _C

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 That one can work too, very nice!

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024, if it could be done automatically with your tools, could you please make the typewriter font monospace or add a monospace variation of it?
Most typewriters (especially at the time of our events) wrote monospace text, and this property will also be useful for certain messages which should be displayed with preserved structure such as this (mine):
![image](https://user-images.githubusercontent.com/59409713/99819221-3faba380-2b60-11eb-9b7c-4ce630fa1a11.png)

**Comment by Tormentor667** [comment]
The only thing left in this issue is the instakill for flamers, but is that really so important? I think it's nice to have, if @Ozymandias81 is willed to do it in time, I am okay but it is not a "must-have"

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 That's aside from your two checkboxes and my last post.
As for the instakill, I've tried to add Pain.Fire/Death.Fire states, but the painstate one hangs my game for some reason, I tried to use
```
    Pain.Fire:
    Pain.Rocket:
    Pain.Electric:
        "####" D 0 A_Die("Extreme")
        Stop
```
for the pain animation and added Death.Fire and Death.Rocket to the death states.

If we manage to do this correctly, we should also add the effect to grenadiers, Panzerschreck soldiers and zombies.

**Comment by Tormentor667** [comment]
The problem is that I am not the right person to ask. @Ozymandias81 @Talon1024 @AFADoomer are more skilled when it comes to the coding, I simply can't tell how to do this. :)

**Comment by Talon1024** [comment]
Try making the state last longer than 0 tics. I had to do that to get [a state in my Nemesis code](https://github.com/Realm667/WolfenDoom/blob/977cf1eb/scripts/actors/enemies/nemesis.txt#L269) working properly.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 Tried it before, to no effect. Also added a several-tic state just before it, also no effect...
Maybe A_NaziPain's behaviour has something to do here?
BTW, while you are here: :-) what do you think about 'monospacing' the typewriter font https://github.com/Realm667/WolfenDoom/issues/280#issuecomment-731246204?
