### ISSUE TITLE
Bug with Keen enemy standing in the air

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#283]
![2020-09-03_202650](https://user-images.githubusercontent.com/10298439/92153005-e5822880-ee23-11ea-8f11-41aeb0612c19.jpg)
This tends to happen in CM03 various times. The red enemy keeps standing in mid air, jumps but doesn't drop to the ground @AFADoomer , can you tale a look at this?

**Comment by Ozymandias81** [comment]
The A_Stop action function seems to block the actor in air, [commenting out](https://github.com/Realm667/WolfenDoom/commit/1850aaa5d57f2778ed6a2ee1a60be63decceeab2) it fixes the behavior apparently.
