### ISSUE TITLE
Fill maps with block monster lines to prevent actors blocking over small heights/ledges

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#284]
I noticed that if we manage to set block monster lines in a proper way (see C3M4 uploaded a while ago), enemies will rarely or never get stuck when rolling/dodge. So this needs to be applied all over maps here and there, painful task but certainly needed to avoid some issues. Please add maps that have been "fixed" below "done" checks, and once the list of a chapter is complete, check the task.

- [x] Chapter 1: M0, M1, M2, M3, M4, M5, M6 done.
- [x] Chapter 2: M0A, M0B, M1, M2, M3, M4, M5A, M5B, M6A, M6B, M6C done.
- [x] Chapter 3: M0A, M0B, M1A, M1B, M2, M3A, M3B, M4, M5, M6A, M6B done.

**Comment by Tormentor667** [comment]
I am already doing this while playing the maps. I hope I find most of them :)

**Comment by Ozymandias81** [comment]
Cool, we must keep an eye over 3d floors though, and sometimes maybe limit walkable space for enemies... I also think we should set breakable chairs in a way that enemies can walk through them, on narrow places it vanify the AI.

**Comment by Ozymandias81** [comment]
Hope this has been done manually, since there are several situations where blocking lines must not be used over 3d floors... We'll see playtesting everything I guess. Thanks a lot for these @Tormentor667 , as I said on FB some days ago I'll doublecheck updates one more time just to be 100% sure.

**Comment by Tormentor667** [comment]
I made everything manually and tried to check if 3d floors are in the way. Hopefully I spotted all of them :)
