### ISSUE TITLE
Adding a SECRETS lump to BoA

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#286]
As suggested by @Username-N00b-is-not-available , adding a SECRETS lump could be interesting. What do you think?

https://zdoom.org/wiki/SECRETS

**Comment by Ozymandias81** [comment]
It could be a nice add, maybe not the most important thing and indeed it should require some time for being complete but doable.

**Comment by Username-N00b-is-not-available** [comment]
It is an old feature, and apparently it has not been externalized to language, though I'm not sure...

**Comment by Tormentor667** [comment]
Would you mind posting a feature suggestion to the ZDoom forums?

**Comment by Username-N00b-is-not-available** [comment]
Sorry, I don't have a validated user account there...
Also on the design, I don't think we should write full walkthroughs like in the wiki article, just possibly a list of goodies which can be obtained (with '???' for very secret ones).

**Comment by Tormentor667** [comment]
https://forum.zdoom.org/viewtopic.php?f=15&t=69827

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 @AFADoomer Thank you for the request and the [addition](https://github.com/coelckers/gzdoom/pull/1179)! Time for me to start writing these messages...

**Comment by Username-N00b-is-not-available** [comment]
More than three weeks have passed since https://github.com/coelckers/gzdoom/pull/1180, apparently the GZDoom team has more immediate things to do and/or does not like my addition, so probably we either have to change all the secrets to sector ones, or remove this feature at all, as now it can only work half of the time. As our release has not been scheduled yet, we can still wait for the developers' final decision, but to me it looks like they have forgotten it long ago.

**Comment by Talon1024** [comment]
Don't expect your pull request to be added that quickly. I've made a few pull requests to GZDoom in the past, and I've had to wait for over a month to get them added. There are indeed other things that take priority for the GZDoom maintainers, such as the work that needs to be done for the 4.5.0 release. If you'd like to check the timeline for getting your pull request merged, [here are the pull requests](https://github.com/coelckers/gzdoom/pulls?q=is%3Apr+author%3ATalon1024) I've made in the past.

**Comment by Tormentor667** [comment]
I'd also say let's wait for it :)

**Comment by Username-N00b-is-not-available** [comment]
From what I see, although large times definitely exist in your examples @Talon1024, but these mostly correspond to 'serious' things like adding .obj models which are related to 'complex' parts of the engine, e. g. renderer. Easier ones get merged almost instantly, in range of three days. Even Doom64 lighting took a week.
Graf Zahl has responded to me in that thread, but I honestly do not know how to address his complaints, and I'm not sure if this could even be possible without serious crutches (how would I assign a static number — static as I will have to write it in the SECRETS lump — to a dynamically spawned actor?)
I doubt that this 'secrets' command's behaviour is of much importance, as it won't break multiplayer or demos (and I made the new format fully compatible to the former one). By the way, have you ever seen a single (released) modification that uses this 'secrets' feature? If yes, please point me to one, as I know nothing about these.

**Comment by Tormentor667** [comment]
I think it could be useful and interesting if the player can show it outside the console with a hotkey.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 There will be a problem, by default only up to three console lines are shown on screen.

**Comment by Tormentor667** [comment]
Can't these be displayed any other way?

**Comment by Username-N00b-is-not-available** [comment]
We can disregard the standard lump completely and try to make something like the objectives screen with ACS.

**Comment by Tormentor667** [comment]
That sounds like a reasonable idea indeed!

**Comment by Username-N00b-is-not-available** [comment]
Another idea: add a small 'interactive' note to each level with secrets. You would be able to pick them up and hold in inventory, like the Keen safe code hints, and the texts would automatically update when you find a secret, making the corresponding text line strike-through. This will need some special ZScript handling, but overall I see this approach as more believable and realistic than just a keyconf key.
After finishing the level the notes should self-destruct so as not to litter the inventory.

**Comment by Tormentor667** [comment]
Well, I don’t think there is a point in finding a secret item to display where secrets are. This should be solved differently.

**Comment by Username-N00b-is-not-available** [comment]
Not a secret item, it could lie in plain sight (e. g. on a random table) in every level.

**Comment by Tormentor667** [comment]
I could live with that 💯

**Comment by Username-N00b-is-not-available** [comment]
I'm working on this, maybe will commit something tomorrow. I changed the format for text entries in the language lump (and in process of refilling them), so please do not update language.csv in the repository before my commits on this.

**Comment by Tormentor667** [comment]
Vers Good, looking forward to this 💯

**Comment by Username-N00b-is-not-available** [comment]
Waiting for feedback on https://github.com/Realm667/WolfenDoom/commit/f8c48b7584999013c824f28dc3765d1bd6a1f79f (you can test it in C1M1, as it is written in the commit's description).

**Comment by Tormentor667** [comment]
I kinda already like it :) As it is now, the "greying out" is so subtle that I do not see any difference on the paper. On top of that I wonder: 

- How do you plan to make the explanation more useful for finding secrets? As it is now, the texts are not very helpful to be honest.
- Is this sheet per map or per chapter?

**Comment by Username-N00b-is-not-available** [comment]
I have not added greying out yet, this was just a planned feature :-)
They are not helpful to find the secrets, but are good to verify what's left (e. g. is it worth looking for). Maybe subtle hints (phrases like 'have not checked the roof') on a per-secret basis are worth adding.
The sheet is per one section of a map (i. e. C2M5_A and _B would have different ones), as this is a hint, not a tally, and you cannot revisit previous maps.

**Comment by Tormentor667** [comment]
The *per-map* solution is fine. I just added a new exclamation hint icon with a "question mark" which should also be placed on these hint papers but only in Skill 1+2.

Regarding the *explanations* for the secrets, these must definitely be enhanced, otherweise it's not a real help in my opinion.

**Comment by Username-N00b-is-not-available** [comment]
Done with this in a series of commits https://github.com/Realm667/WolfenDoom/commit/98ac6604c62c777af420320d3729b589b6aaa3fd, https://github.com/Realm667/WolfenDoom/commit/aca88304988ab8207dbc91ce4a43ee249ddc8f71, https://github.com/Realm667/WolfenDoom/commit/5e37b0e312800b30c1f9caaf06117381f7d6ce65, now waiting for opinions from @Tormentor667, @Ozymandias81, and @Talon1024.
You can find the coordinates of the paper hints in the commit descriptions.

**Comment by Tormentor667** [comment]
It's quite good so far, but the problem that I have is still that a reference is missing. You do get a text like _"check other side of the vent"_ but no coordinates ingame, you have absolutely no idea where to start searching. I mean, how is this supposed to help if you read the note about _"check other side of the vent"_ in a map where 10 vents are?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 C1M3 has exactly one playable vent area!
I understand you, I should probably have left at least a general positional reference (for example, in which building or part of a large structure the secret cache is), so I'll expand on some of them.

**Comment by Tormentor667** [comment]
That’s reasonable. Always remember: No player knows the maps as good as we do. The secret hint sheet should help the players to find the secrets 👍

**Comment by Username-N00b-is-not-available** [comment]
Hmmmm, there is a seventh secret on C2M5_B which I did not have information about. Looks like somebody has added it while I was messing around with the descriptions, so I'll probably have to check the secrets (at least their counts) yet another time...

**Comment by Username-N00b-is-not-available** [comment]
Checked everything once more and fixed the remaining problems. Also made an image with all the secret hint positions (can't put an 12MB file directly, so here is a zip archive):
[hints.zip](https://github.com/Realm667/WolfenDoom/files/5579746/hints.zip)
I think the issue can be closed for now, and the hints are ready for translation. @Tormentor667, @Ozymandias81, @Talon1024, what's your opinion on this?

**Comment by Ozymandias81** [comment]
As soon I have time and my personal problems will be solved, I will surely check your stuff @Username-N00b-is-not-available

**Comment by Tormentor667** [comment]
I am okay with it as it is now, thanks a lot for your efforts.

One thing though: Do you think you can give the secret papers a different sprite style when they are laying around? So they are obviously different from the rest of the papers? So you can actually see them and tell "Ah, thats a secret paper" :)

**Comment by Ozymandias81** [comment]
Maybe like on Day of the Tentacle, we can use typical "blueprint" color for secret papers

![DOTTHD](https://user-images.githubusercontent.com/11136108/100116136-ad631280-2e73-11eb-8614-e533c50c3317.jpg)

**Comment by Tormentor667** [comment]
Yes, that might work, the Cyanotopie was already available in 1939.
