### ISSUE TITLE
Music Help?

### ISSUE THREAD

**Issue by Psychonator17** [Realm667/WolfenDoom#288]
It's nothing wrong with the game, I just don't know how else to ask this particular question. I know that some of the music used in Wolfendoom is from Medal of Honor, but is there a listing of the actual names and what specific game they came from? (The one I'm looking for particularly is Chapter 2 Mission 5, where you're planting C4 in the weapons facility.)

**Comment by Ozymandias81** [comment]
Well quite all songs have metadata embedded, which you can easily read if you unzip the pk3 and check inside Music folder. While I am not sure if you are refer about Chapter 2 release or the actual dev build of BoA, since maps from the old release are pretty different now. Anyway here you are C2M5 music infos:

![image](https://user-images.githubusercontent.com/11136108/92674891-9013b300-f31e-11ea-8240-aba388c2bfe7.png)

**Comment by Psychonator17** [comment]
> Well quite all songs have metadata embedded, which you can easily read if you unzip the pk3 and check inside Music folder. While I am not sure if you are refer about Chapter 2 release or the actual dev build of BoA, since maps from the old release are pretty different now. Anyway here you are C2M5 music infos:
> 
> ![image](https://user-images.githubusercontent.com/11136108/92674891-9013b300-f31e-11ea-8240-aba388c2bfe7.png)

Thanks for this. I took your advice and installed audacity, then tried viewing the OGG files through it: they all came up blank.

**Comment by Ozymandias81** [comment]
How so?
![image](https://user-images.githubusercontent.com/11136108/106770155-f7b7fb00-663d-11eb-8c5a-c0eeac3906a9.png)
![image](https://user-images.githubusercontent.com/11136108/106770241-0f8f7f00-663e-11eb-9586-4c13a3430382.png)
![image](https://user-images.githubusercontent.com/11136108/106770296-1fa75e80-663e-11eb-90af-5711007b1cd8.png)
![image](https://user-images.githubusercontent.com/11136108/106770357-2fbf3e00-663e-11eb-915b-b4320f447e48.png)

From audacity, you need to go on Modify (or Edit, I have it set in italian) ==> Metadata

**Comment by Psychonator17** [comment]
Your advice worked, thanks! Just one more thing: the identification for
C2M2_ESC is completely blank. I searched through its metadata and found
nothing: no track name, no artist name, no anything.
