### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#289]
The game's interface looks very nice, but there are some minor problems with its usability:

<details><summary>Resolved issues</summary>

- [x] If a transmitted message is active, you cannot see kills/secrets count (and you have to wait several seconds until it fades out, sometimes just to be replaced by another one...) As for the solution, we can, for example, move all the map information from the top left corner, where it rests now, to the bottom left corner.

![Screenshot_Doom_20200911_204448](https://user-images.githubusercontent.com/59409713/92990023-37d8de80-f4e1-11ea-9693-7b68c1822574.png)

- [x] Unskippable cutscenes, especially at the start of a map, frustrate many players and become even more infuriating when testing. You have to wait several seconds watching a red curve propagate over a map you've already seen hundreds of times, and there is nothing you can do about it.

- [x] Then there was the problem of cutscenes which are not skippable beyond a certain point, but now it looks like it was mostly fixed, I can't find an instance of this. Needs to be checked later.

- [x] Ah, yes, there is also a problem with developer commentary in Russian:

![Screenshot_Doom_20200912_103842](https://user-images.githubusercontent.com/59409713/92990320-25ac6f80-f4e4-11ea-8e2a-35caa442b4e7.png)

>Oops, I have not noticed the second line break added to English texts... --N00b

</details>

- [x] Boss healthbars are covered by radio transmissions (see that silver swastika piece?) Not sure what to do with this, temporarily moving the healthbar down can interfere with player's view too much...

![Screenshot_Doom_20200924_213129](https://user-images.githubusercontent.com/59409713/94185146-9cb31200-fead-11ea-90e2-d477db1256c3.png)

- [x] The message of Douglas is fully covering the bomb timer. It keeps ticking and ticking, and when the message finally fades out, you have two seconds remaining (in other words, 'you are screwed :)') Also on C1M5: the same problem, but with Douglas message about the reinforcements and the 'Kraut killer' tally.

![Screenshot_Doom_20200924_214858](https://user-images.githubusercontent.com/59409713/94194475-692ab480-feba-11ea-9b77-45b2e949da1b.png)

**Comment by Tormentor667** [comment]
The unskippable cutscenes are only the "map travel" screns before C2M_A, C2M6_B, C2M6_C and C3M6_A as far as I know. I am okay with adding the same "Skip Sequence" script as for the other maps.

Regarding the position of the map stats, this is something @AFADoomer can help with, he wrote the scripts for that view.

**Comment by Ozymandias81** [comment]
Added skippability for Travel_Sequence scripts present on mentioned maps by @Tormentor667 , still didn't commit yet but should happen in a couple of hours, doing some work over final C3 maps. Also AFADoomer fixed mapstats coords when readiomessages appear too.

**Comment by Username-N00b-is-not-available** [comment]
Forgot a problem that has bothered me for some time.

**Comment by Tormentor667** [comment]
I am not sure what to do, it didn't bother me until you mentioned it. I actually would move it a bit more upwards so it is fully covered by the radio bar.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Do we need it at all then?
By the way, I have added yet another problem which I stumbled upon my today's E1 playthrough.

**Comment by Tormentor667** [comment]
The health bar is needed, yes. But we can move it upwards a bit so it is fully hidden (design choice).

What did you find in c1?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 It is in the first post, just below the healthbar issue. If I find a new problem, I always add it to the original post.

**Comment by Tormentor667** [comment]
Thanks, that must be fixed!

**Comment by Tormentor667** [comment]
Maybe @Ozymandias81 @Talon1024 or @AFADoomer can improve the scripts here.

**Comment by AFADoomer** [comment]
Boss health bars should be fixed in 76a41f28d69f9824a14d7feeea88369c73c5bb8c.  I just moved them up on the screen some so that the conversation bar covers them fully when active.
