### ISSUE TITLE
INTROMAP dialog sequences broken

### ISSUE THREAD

**Issue by yqco** [Realm667/WolfenDoom#29]
[This change](https://github.com/Realm667/WolfenDoom/commit/929fcbef0b35e16d11da7c200cc70719fc70d332#diff-a84a4be22538446e59008b0034918b5d) to MAPINFO has caused the mission briefing and level exit (Dirty Douglas) dialogs to break.

![wolfendoom_dialog_issue](https://cloud.githubusercontent.com/assets/20593027/17280077/583e9e6a-5744-11e6-895b-4f6a6ea049f5.jpg)

**Comment by Ozymandias81** [comment]
Yes, I noticed that right now...
Why it works good via GZDBuilder and not from the game itself?
Do I need to "import" it somewhere?
If you can find a solution for that, yqco, I'll merge it in an instant. I think I am dumb sometimes :facepunch: 
For now I'll revert those changes from the library, thanks a lot

**Comment by Ozymandias81** [comment]
Nevermind, [fixed](https://github.com/Realm667/WolfenDoom/commit/ea8abee30314a6d20c3264074254b72e7a3918a1).
