### ISSUE TITLE
Chapter 1 final boss doesn't display healthbar

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#290]
Normally, the health bar is being displayed when aiming at an enemy. This doesn't happen for the Smoke Monster in C1M6.

**Comment by Username-N00b-is-not-available** [comment]
Also you can see in the room before INTERMAP training that the health bar is sometimes displayed even if there is a solid obstacle between you and the boss (there are tanks you later need to kill with Panzerschreck).

**Comment by Ozymandias81** [comment]
The healthbar problem with SmokeMonster should be related to HeatEffect actor messing things, and afaik the Intermap issue was fixed long time ago

**Comment by AFADoomer** [comment]
Fixed the Smoke Monster health bar display problem in fc103d464cd24f87cea64c81c1dd06483c200113.
