### ISSUE TITLE
Turrets discussion

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#291]
The unmanned machinegun turrets on maps like C1M0 (Eisenmann) and C2M0_B (Astrostein Part 2) are annoying as hell! They're really hard to hit, and take several hits from the sniper rifle to bring down. Plus, they can cause you quite a lot of pain.

I'd say reduce their health, but what are your thoughts on this?

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 I agree on them being very annoying, even though they are used rather sparingly on maps. I support reducing their health, possibly even by half. It makes little sense for such a tiny actor to have so much health (I get that it is armoured, but there should be some room for the large mechanism of a six-barrel machinegun, or shouldn't it?)
This also applies to Astrostein ones. I know high health on turrets may be a Doom engine tradition, but this is not Strife, this is BoA :-)

**Comment by Tormentor667** [comment]
I agree on halfing the health

**Comment by Username-N00b-is-not-available** [comment]
What's the verdict on this?

**Comment by Tormentor667** [comment]
Halfing the health of the turrets.

**Comment by Username-N00b-is-not-available** [comment]
It has already been halved by @Talon1024: https://github.com/Realm667/WolfenDoom/commit/70e5aa4608a172d6affc793582a6245e8450dbab
