### ISSUE TITLE
Shader for Waterfall textures

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#293]
@AFADoomer I just replayed C1M4 for testing purposes and I had the feeling that the waterfall textures seem to be a bit too flat. Do you have a shader idea that makes them look more interesting and more like a waterfall? (maybe some overlapping that flows faster or slower or in waves so it looks like more streaming, more flowing, more like a waterfall.

**Comment by Talon1024** [comment]
How is the current waterfall shader?

BTW, you can tweak it in boashaders.txt

**Comment by Tormentor667** [comment]
Is it possible to also tweak the overlay scaling?

**Comment by Tormentor667** [comment]
It's perfect now, well done @Talon1024
