### ISSUE TITLE
Make objects fade in and out when nearing them

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#295]
Question towards @Ozymandias81 , @Talon1024 , @AFADoomer : Instead of making objects far away instantly appear as soon as you are close enough to them (or disappear, if you get farther away), would it be possible to make them slowly appear and disappear via fade? I find it kinda annoying that out of nowhere, trees pop out when getting close to them (depending on the rendering distance I set)

**Comment by Ozymandias81** [comment]
Adding that kind of effect was already suggested ages ago, problem is that it would require an additional special on top of DistanceCheck, which would drastically vanify the performance

**Comment by AFADoomer** [comment]
Just pushed an implementation of this in ec8d8abc87d763b189bf0db577b2fbb9cc4adf99 that leverages the existing culling code (so the distance check is already being performed).  Needs to be tested, and probably isn't 100% multiplayer safe visually, since it doesn't check distance for all players, just the first one it finds that's in range.

**Comment by Ozymandias81** [comment]
Cool work with this fade effect, I must be frank that I can set distance to 4096 for everything at C3M1_B and I get a slightly better performance than my old setup (everything at 2048), so these tweaks are pretty good! One thing have noticed though: light cones seems to spam "more" once we leave their distancecheck value, and probably we must see how objects behave during the train sequence on c2m5_A, rocks and trees are very sensible... Will do more tests tomorrow for this reason.

**Comment by Ozymandias81** [comment]
Conelights and such seems okay so I am gonna close this.
