### ISSUE TITLE
New Launcher - it might need modification

### ISSUE THREAD

**Issue by madame-rachelle** [Realm667/WolfenDoom#297]
https://github.com/Realm667/WolfenDoom/blob/master/tools/launcher-new/Blade%20of%20Agony%20Launcher/Blade%20of%20Agony%20Launcher.h

All the settings are here, in the linked file. Basically, it constructs a command line based on the options selected in the dialog box.

Features:
* It can save whether or not displacement textures should be enabled.
* It can be told not to show, and saves that setting, also.
* It should be very easy to change how it constructs the command line just by modifying the above-linked .h file

So yeah - how should the command line be constructed? That is the reason I am creating this ticket.

**Comment by madame-rachelle** [comment]
Changed link above, this link might not match what you got in your email. Sorry!

**Comment by Tormentor667** [comment]
That already works very good, thanks alot for that 👍 

Could you be so kind and also add a "language choice" dropdown? I also uploaded a new image and a custom new icon that can be used for the launcher.

**Comment by madame-rachelle** [comment]
Alright. What languages are you supporting?

**Comment by madame-rachelle** [comment]
Actually - I should probably figure this out myself since I'll need to know the exact values it has to use.

**Comment by Tormentor667** [comment]
The spreadsheet will help you here most propably:
https://docs.google.com/spreadsheets/d/1Nok0lZ7fX9mKLRf7TItqsllhdIVSC8jt_L9otCBP0bs/edit#gid=699002033

By the way, would it also be possible to set the developer comments to on and off from the launcher?

**Comment by madame-rachelle** [comment]
Yeah - I'll need the console commands for those, too.

**Comment by Tormentor667** [comment]
Maybe @Ozymandias81 or @Talon1024 can help here, he created the cvars for these settings.

**Comment by madame-rachelle** [comment]
I found it, I am good to go, just have to do a project first.

**Comment by madame-rachelle** [comment]
Did some updates, should be pretty up to snuff now.

> Regarding the final PK3 name, it will (most propably) be "boa.pk3"
* First - not .ipk3? .ipk3 allows it to be autodetected by GZDoom as an IWAD.
* Second - What is the -file for the displacement textures?

**Comment by madame-rachelle** [comment]
> 
> 
> Did some updates, should be pretty up to snuff now.
> 
> > Regarding the final PK3 name, it will (most propably) be "boa.pk3"
> 
>     * First - not .ipk3? .ipk3 allows it to be autodetected by GZDoom as an IWAD.
> 
>     * Second - What is the -file for the displacement textures?

@Tormentor667 Highlighting for this question - it's really important (sorry)

**Comment by Tormentor667** [comment]
I agree, .ipk3 is better, let's do that :) Regarding the displacement textures, we will call that boa_dt.pk3

**Comment by madame-rachelle** [comment]
Thank you! I will push the update for that ASAP. ☺

**Comment by Tormentor667** [comment]
@madame-rachelle, could you be so kind and add "czech" to the available languages? We have a translator who is working like crazy on the translation :)

**Comment by DoomJedi** [comment]
Can you add "texture filtering" option to the launcher? To easy set pixellated look for the mod, for retro fans? There is very big visual difference/implications between default setting and pixellated look, something player better choose from the start.

**Comment by madame-rachelle** [comment]
> @madame-rachelle, could you be so kind and add "czech" to the available languages? We have a translator who is working like crazy on the translation :)



> Can you add "texture filtering" option to the launcher? To easy set pixellated look for the mod, for retro fans? There is very big visual difference/implications between default setting and pixellated look, something player better choose from the start.


This is just to let you guys know I have received these messages and will do this when I am able to.

**Comment by Tormentor667** [comment]
Thanks for reporting back @madame-rachelle :)

**Comment by madame-rachelle** [comment]
Check commit https://github.com/Realm667/WolfenDoom/commit/a0ae8b317d17b36a4ef33aa04f87f00b4d7b96fe

**Comment by Ozymandias81** [comment]
Just testing it right now, with my 1280x1024 resolution (I have an old pc with Belinea monitor that's 4:3) the star menu doesn't fully fit, but I guess we can live with it anyway.

My actual folder, only with boa IPK3 (no separate displacement file yet)...
![image](https://user-images.githubusercontent.com/11136108/97016177-b72fe800-154c-11eb-8c2f-63b93ba64199.png)
...so as you can see doesn't fit perfectly, but nothing dramatic I think, not many ppl nowadays have 4:3 monitors...
![image](https://user-images.githubusercontent.com/11136108/97016197-be56f600-154c-11eb-9dd2-fe040174a493.png)

[more to come, testing]

**Comment by madame-rachelle** [comment]
Change the name from wolf_boa.ipk3 to boa.ipk3. This was the name chosen by Tormentor667.

**Comment by Ozymandias81** [comment]
Should these use +set instead of just +?
![image](https://user-images.githubusercontent.com/11136108/97019000-15aa9580-1550-11eb-9d12-7b4d21fc8049.png)

**Comment by madame-rachelle** [comment]
No, they invoke aliases. If the aliases don't work then they should be replaced with the contents of those in-game aliases. They are defined here: https://github.com/Realm667/WolfenDoom/blob/master/keyconf.txt

**Comment by Ozymandias81** [comment]
Yes I am aware of where they are defined, but thought adding set and 1-0 was good... Not very fond with these kind of things, and sadly can't compile/code myself what you did (I mean I can modify the .h file but not compile it). Thanks for the hint :)

**Comment by madame-rachelle** [comment]
Do a pull request then (and make sure to @ me in it)  - and I can fix it up if there's any problems.

**Comment by Tormentor667** [comment]
Just a little push: Has this been solved now for the release of the latest GZDoom?

**Comment by madame-rachelle** [comment]
AFAIK no, but I am planning on other options that will increase flexibility for the team as a whole and require less recompiling. i.e. basically not having anything hardcoded

I have a week off this week from most of my stuff, so I may have time to do this.

**Comment by Tormentor667** [comment]
Very good, I am looking forward :)

**Comment by Ozymandias81** [comment]
As a side note, do not forget to [check the branch](https://github.com/Realm667/WolfenDoom/tree/launcherfix) I opened for my attempts to fix stuff for the launcher @madame-rachelle

**Comment by madame-rachelle** [comment]
Thank you @Ozymandias81 - but wow that is a massive amount of options that need to be changed. Unfortunately that's going to have to go into some .cfg files, in my opinion, but I can handle that.

**Comment by Tormentor667** [comment]
Thanks for trying to solve this :)

**Comment by Tormentor667** [comment]
I noticed a problem that I do not understand why it is happening @madame-rachelle, but here is what I did:

- created a new directory
- added the complete package "boa.ikp3" to this directory 
- added the latest gzdoom files to this directory
- added the Blade of Agony Launcher.exe (your launcher) to this directory.
- started the launcher
- left everything on default and started
- and there is the bug: 

All the additional language entries (for example the episode choice) is not used by the engine. "New Game" is displayed correctly. "The Staff of Kings" is not, instead, $EPNAME1 is shown, even though the default language in the launcher is set to "English". If I simply launch "gzdoom.exe" and let it decide to automatically use boa.ipk3, everything works fine.

-------------------------------------

Next problem, this is what I did:

- created a new directory
- added the complete package "boa.ikp3" to this directory 
- added the latest gzdoom files to this directory
- added the Blade of Agony Launcher.exe (your launcher) to this directory.
- started the launcher
- set "Detail preset" to max, "Using displacement" to yes, "Texture filtering" to no filtering, "Language" to german, "Commentaries" on and started
- and there is the bug: 

Nothing happens. The launcher quits and no GZDoom is executed. I hope you can check these issues, I'd like to send a few copies of BoA to my friends in the next few days so they can do an independent beta-test :)

**Comment by madame-rachelle** [comment]
Okay I suspect there are some GZDoom bugs here. At any rate, it looks like the CVARs are going to have to be pushed to the engine *after* startup, not during. And that will definitely have to be done with .cfg files.

What if we created a GZDoom fork specifically for this project, that would be set to read two different autoexec.cfg files, one specifically for the launcher?

**Comment by Tormentor667** [comment]
> What if we created a GZDoom fork specifically for this project, that would be set to read two different autoexec.cfg files, one specifically for the launcher?

One of the most important things to me is "backwards compatibility". I really want Blade of Agony to be run in any future GZDoom versions instead of creating a specific port for it.

**Comment by madame-rachelle** [comment]
@tormentor667 please check your zdoom PM's as soon as you can please, I've decided to scrap this incarnation of the launcher and have decided to remake it using more modern tools/concepts (and hopefully make it cross-platform) but need some important information from you.

**Comment by Tormentor667** [comment]
Just answered your pm on Zdoom, sorry for the delay, just had to prepare the webpage :)

**Comment by Ozymandias81** [comment]
We'll need to provide some sort of "definitive" list of cvars to be included on such configs if they will be used on the new launcher, guess that can be updated before day prior release, am I right @madame-rachelle  @Tormentor667  ? There are still some to include yet

**Comment by madame-rachelle** [comment]
Okay, the only way that is going to work is if they are done in config files. I'll still try and get the new launcher done, but in the mean time I'm going to split that PR off into config files, that will at least make it somewhat less hard-coded.

**Comment by Tormentor667** [comment]
I am okaa with that change.

**Comment by madame-rachelle** [comment]
Updated launcher in https://github.com/Realm667/WolfenDoom/commit/f04f58e5d7612553a40f00830bd5e760adc60ec0 - @Ozymandias81 can you please test when you are able? Thanks.

**Comment by Ozymandias81** [comment]
So I am at it, let's see: I guess I need to update these in our menudefs, I am using actually GZDoom 4.5 r305 since I had this version set during my previous tests.

![image](https://user-images.githubusercontent.com/11136108/100520346-a30b8600-319d-11eb-95b2-9a67d1a27dfd.png)
![image](https://user-images.githubusercontent.com/11136108/100520163-a94d3280-319c-11eb-8dc4-938c407031f2.png)
![image](https://user-images.githubusercontent.com/11136108/100520185-c550d400-319c-11eb-8c17-8fa3baa43074.png)
![image](https://user-images.githubusercontent.com/11136108/100520195-d568b380-319c-11eb-83ce-457a3156b2bd.png)
![image](https://user-images.githubusercontent.com/11136108/100520218-f6310900-319c-11eb-9d78-a06f5067cbfe.png)
![image](https://user-images.githubusercontent.com/11136108/100520240-11037d80-319d-11eb-8b2a-aaf0df783141.png)
![image](https://user-images.githubusercontent.com/11136108/100520303-663f8f00-319d-11eb-9e45-85caaf88c1e9.png)
![image](https://user-images.githubusercontent.com/11136108/100520570-b408c700-319e-11eb-88ba-b69ce66402e8.png)

**Comment by Ozymandias81** [comment]
So my conclusions are:

1. language needs to be updated, English should be split into English US (ens) and UK (enu)
2. texture filtering works if we change it only under most recent build of GZDoom, but as soon as we try to change Detail Preset, pressing play produces a crash
3. Some entries needs to be up to date menudef wise
4. Sprites must have clipping set to Always
5. Show ENDOOM must be set On
6. We must get rid of the option to not have mouse in menues, since this will break interactive events in game (dialogues, skipping, safe combinations etc)

**Comment by AFADoomer** [comment]
>     6. We must get rid of the option to not have mouse in menues, since this will break interactive events in game (dialogues, skipping, safe combinations etc) ***
> 

I never use mouse for any of these things...  what does disabling mouse in menus break?

**Comment by Tormentor667** [comment]
Tried the latest version of the launcher as it currently is. It is not working. It simply doesn't launch the mod. It works if I do not choose any setting from the dropdowns but as soon as I choose a setting, the game simply doesn't start. Maybe the command line is still too long?

**Comment by madame-rachelle** [comment]
oops I forgot to update this issue. Please check commit https://github.com/Realm667/WolfenDoom/commit/58549a54ec33e097ee5e7ba0ae857ddb8bdb5d9d

**Comment by Tormentor667** [comment]
What did you actually change?

**Comment by madame-rachelle** [comment]
Mostly I just tried to address the problem here, so not really much. The texture filtering is now specified using the .cfg files, that's about it.

**Comment by Tormentor667** [comment]
The latest version seems to work fine for me. Did anyone else test it so far?

**Comment by DoomJedi** [comment]
We need to have objectives key pre set in the launcher (if it's not st already), "O" is most logical.
Without objectives - it's hard to know what to do in the map.
Do we have grenade button pre set? We need it too...."G"?

**Comment by DoomJedi** [comment]
> 
> 
> The latest version seems to work fine for me. Did anyone else test it so far?

Where is this launcher so I can test it?

**Comment by Tormentor667** [comment]
It’s under tools/launcher-new/distribution afaik

**Comment by DoomJedi** [comment]
How to use it? It just loads Doom II....

**Comment by Tormentor667** [comment]
You need to build a ipk3 from the complete mod, then put it into a folder with GZDoom and the ipk3, from there you can launch the launcher

**Comment by madame-rachelle** [comment]
You need everything that comes in that "distribution" folder too, or else the included options will not work.

**Comment by Tormentor667** [comment]
@Ozymandias81 - Did you try the launcher yet? I think you are into this the most when it comes to predefined settings, would be cool if you can check the launcher so we can close that issue as well!

@madame-rachelle thanks kindly for helpig us with this :)

**Comment by Ozymandias81** [comment]
Testing now, I see there are some options that should be on per default but aren't, gonna update.

**Comment by madame-rachelle** [comment]
>     * Bloom which is set 1 on default doesn't get set in game properly if we run the game for the very first time without touching any options (in this case Use Last Setting under Detail preset), and trilinear filtering is enabled too which should never be active on BoA due that it would break some shaders alignment and lighthouse conelight translucency at its end. For instance "Use Last Setting" acts like if you are running GZDoom for the first time when you run the game for the first time, so mmh maybe I am overracting

Some of these options can (and should) be fixed using [DefCVARs](https://github.com/Realm667/WolfenDoom/blob/d5a11f31a3c8463081b29cf16abddf0b27862ea1/defcvars.txt)

**Comment by Ozymandias81** [comment]
Thanks, just setting them and works properly now :smile:

**Comment by Tormentor667** [comment]
So are we done here? :)

**Comment by Ozymandias81** [comment]
Need to test properly when displacement separate file will be ready and also to see which changes we must do to menudef accordingly to simple menu options too (so maybe something will be removed or added idk). Also must test all possible config combos, this is at least from me.

**Comment by Tormentor667** [comment]
Remember, it needs to be called "boa_dt.pk3" :)

**Comment by Username-N00b-is-not-available** [comment]
@madame-rachelle Will it be possible to incorporate loading language-specific files? Quite a long time ago I had an idea of localizing the signs in the HQ and other English graphics and textures, and I think I have done all or most of them (in Russian).
Would've appreciated the original fonts TBH, but it was faster to Frankenstein all the letters by myself :-) I can share the pk3 here, it's around 2MB.

**Comment by Tormentor667** [comment]
It surely is but I'd like to keep it as is for authenticity reasons. I mean - why should german signs be in russian?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 I'm not talking about any _German_ signs, I mean the ones with _English_ lines, such as 'Armory' or 'Briefing Room' in the HQ and so on, and graphics such as https://github.com/Realm667/WolfenDoom/blob/master/graphics/general/m_epis.png or the help screen backgrounds (I won't change M_DOOM, just in case). I doubt we lose much 'authenticity' if we translate these ones, and it would surely help players who don't know even basic English (as there are quite a lot of rooms in the HQ).
German ones should of course stay in German. It would also make little sense to translate well-known English posters, since you either can read the sign and get the reference, or cannot, in which case a translation would be of little help.

**Comment by Tormentor667** [comment]
Even the english lines in the hq should stay as they are for authenticity reasons. Regarding the "m_epis.png" ones, that would make indeed sense but I wonder how much effort it is worth to translate these as well.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 OK, there's just like fifteen of these signs, maybe they really won't confuse anyone.
As for the interface graphics, I found 18, and I did spend a few hours on them, but that was because I had to manually draw missing Cyrillic characters (and I did not have the full font to make the process faster). It won't be that much of a problem for languages which use Latin alphabet. Here you can see the graphics: [boa_ru.zip](https://github.com/Realm667/WolfenDoom/files/5868633/boa_ru.zip)

**Comment by Tormentor667** [comment]
What I can imagine is adding an „addon“ section to the webpage for things like that but I wouldn’t add these to the official release - it’s very minor and cosmetic, and more a personal preference. 

As an addon, I‘d be even okay with adding more textures and graphics localized to russian so you have more freedom then.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Well, I wanted these ones to essentially be a part of the translation (and to have similar ones for every language). Though maybe it's really better not to add these at all.
By the way, I am wondering how people would use addons if there is no way to load them in the launcher. Players will have to use CLI, but wasn't avoiding the command line the exact reason the launcher was added? Do we plan to add support for addons there?

**Comment by Tormentor667** [comment]
That's a good point indeed - how to load addons through the launcher ... well, you could easily drag and drop the addon on gzdoom.exe and it instantly works. But I wonder if @madame-rachelle has an idea.

**Comment by Username-N00b-is-not-available** [comment]
We should not forget about multiple addons which need to be launched in a specific order. ;-)

**Comment by madame-rachelle** [comment]
> We should not forget about multiple addons which need to be launched in a specific order. ;-)

You can use GZDoom's own systems to handle this. Stick a GAMEINFO lump inside of a zip file which, when properly defined, declares the exact order of loading the files along with telling it to load BOA.

https://zdoom.org/wiki/GAMEINFO

The zip file does not need a `.zip` extension or `.pk3` - for the purposes of loading it with a launcher we can just choose `.boa`. Then the launcher can load all `.boa` files in the directory and let you choose one to load.

**Comment by Tormentor667** [comment]
Very good, thanks @madame-rachelle , then we have a proper solution for addons :)

**Comment by Username-N00b-is-not-available** [comment]
@madame-rachelle This is a very good idea, though possibly not very familiar to modders. Do you think you can implement the addon system this way? Then I'll sketch a small example of using this technique for people to follow.

**Comment by madame-rachelle** [comment]
I could try and do it but I have a lot on my plate at the moment including a paid gig that is taking up quite a lot of my time.

**Comment by Tormentor667** [comment]
> I could try and do it but I have a lot on my plate at the moment including a paid gig that is taking up quite a lot of my time.

That would be definitely nice to have. We have still time, the release is planned on April 30th, so if you can pick it up until then, it's all fine :) Good look with your gig!

**Comment by Tormentor667** [comment]
@madame-rachelle I don't want to bother you, just asking if your time schedule got a bit better and if there are any estimatd dates when you can pick this up again :) Other than that, I suppose the launcher is finished as is, right? (@Ozymandias81)

**Comment by Username-N00b-is-not-available** [comment]
Bumping @Tormentor667's question. Any news on the https://github.com/Realm667/WolfenDoom/issues/297#issuecomment-768784412 addon system, @madame-rachelle? Maybe @Ozymandias81 could code it in?

**Comment by madame-rachelle** [comment]
I already described the format that should be used for addons - this is native to GZDoom itself. The launcher would merely list all files with extension (*.boa) in its folder and simply -file them with GZDoom. 

I haven't had any time to pick this up. The documentation for the addon system should be written ASAP though - the sooner the standard is set on this the more addons that will pick up the standard so that they comply with the launcher's requirements.

To reiterate the proposed standard:

All addons will have a "header" file that uses the extension .boa instead of .pk3. Inside the file is merely a `GAMEINFO.TXT` file with the following contents:

```
IWAD="boa.ipk3"
LOAD="myaddon1.pk3", "myaddon2.pk3", "etc.pk3"
STARTUPTITLE="My sweet addon"
STARTUPCOLORS="FF FF FF", "00 00 00"
STARTUPTYPE="Hexen"
STARTUPSONG="my-cool-addon-music.ogg"
```

The file should not contain anything else. If it's a standalone addon (i.e. requires only one file) then the author can simply rename their .pk3 to .boa and include the requested `GAMEINFO.TXT` file and it will work just fine.

**Comment by Username-N00b-is-not-available** [comment]
@madame-rachelle I got the standard you posted and was asking more about the implementation. Thank you for expanding on it anyway!
I'll add the detailed explanation to the Editing Docs on the website, but the addon standard is something so important that it could not be thrown into the middle of >30 subsections mess and simply left there, it would literally be the starting point of modding BoA. @Tormentor667, do you by chance have ideas where the description could be posted to actually attract the attention of **every** potential modder? Maybe a subsection under 'Help' submenu will do (with multiple references to it from the download page, editing docs, news, ...) would be a good idea (I'll create it then)?

**Comment by madame-rachelle** [comment]
As I said, this implementation is native to GZDoom. Simply provide a few example mods in this format, and the community will follow.

**Comment by Username-N00b-is-not-available** [comment]
Being too lazy to install VS, then set up and compile all of this, I meant the launcher implementation :-)

**Comment by madame-rachelle** [comment]
If/when the documentation is written for this it should be noted that only the loader files should be .boa - the actual mods and contents should be packed in a file with a regular .pk3 extension. If you don't emphasize this point I think it will cause confusion and lead to exactly the problem we're trying to fix with this - and people will start trying to tell you to use "a series of .boa files in 'this exact order'" which would defeat the purpose of creating something like this in the first place.

**Comment by Username-N00b-is-not-available** [comment]
Yeah, I'm writing it just now, I'll explicitly state this one more time. Thanks!

**Comment by Username-N00b-is-not-available** [comment]
@madame-rachelle Here's what I wrote on the site (https://boa.realm667.com/index.php/help/docs, section "Addons"):

<details><summary>Addons</summary>

An addon for Blade of Agony is a collection of GZDoom game data archives, loaded after the main game files in a specific order.

The Blade of Agony launcher allows the player to optionally load a single addon when launching the game. At first this may seem a severe limitation, but in fact it is not. Multiple mods in separate files can be easily combined into one addon in the following manner.

An addon definition consists of a "header" zip file that links the mod files together and makes sure they are loaded in proper order. It uses the extension .boa instead of .zip or .pk3. Inside the file should merely be a standard ZDoom GAMEINFO.TXT file, with contents similar to this:

```
IWAD="boa.ipk3" //main game archive, do not change this line
LOAD="autoautoautosave-v1.0.0.pk3", "Call_of_DOOty_IV_maps.wad", "hitler_gore_xbrz_x32.pk3", "ChexWeaponsForBoA.pk3" //additional archives which constitute the addon, listed and loaded in proper order after the main archive
STARTUPTITLE="My mod collection" //name of this addon which will be shown on startup
STARTUPCOLORS="FF FF FF", "00 00 00" //colors of the starting menu banner
STARTUPTYPE="Hexen" //BoA default, change this only if you know what you are doing
```

The .boa addon definition file should not contain anything else. Its purpose is similar to that of a batch script. All the game resources (maps, actor code, sprites, music, etc.) that need to be loaded with the addon belong to the external files listed in the LOAD=... line of GAMEINFO.

If you want to combine two or more addons, just merge their GAMEINFO definitions into one (do not forget to test and check the proper load order in game).

</details>

***

I decided to remove the startup song line, because BoA uses a blank entry for it, and it will probably have to be packed into the .boa file to get played; and also removed the sentence about standalone addons, because it contradicts the principle you stated in your last post.

**Comment by madame-rachelle** [comment]
Looks good to me. :)

**Comment by Tormentor667** [comment]
I'd suggest shipping some kind of an addons already with the final release of BoA, just as an example for modders.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 I've had an idea about the archives with various unused resources I had sent you some weeks ago. We can bundle them into an 'addon' and put it as a separate download onto the same webpage.

**Comment by Tormentor667** [comment]
It somehow needs to be incorporated into the game. I thought about some kind of a gameplay addon

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 What about something very simple like this? [new_skill.zip](https://github.com/Realm667/WolfenDoom/files/6243308/new_skill.zip)
The two files in the archive need to be placed into the distribution folder with the executables (or maybe we can add a special ```/addons``` subdirectory there). Until the launcher addon system is implemented, to test it you can just drag the .boa file onto GZDoom.
***
This particular archive just adds a new skill which is harder than Mein Leben but also has the new [InstantReaction keyword](https://zdoom.org/wiki/MAPINFO/Skill_definition#InstantReaction), so the enemies shoot you on sight rather than walk around (like ```user_static```'ed enemies in BoA or Nightmare! monsters in Doom). It also brings enemy health down 3x.

**Comment by Tormentor667** [comment]
I am okay with something simple but I think we could do better :) By the way, your description says "enemies take triple damage", does that mean they are even harder to kill or easier because of their instant reaction?

I'd suggest going a different route for a pre-implemented addon though. Any ideas?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Fine, but there is a dichotomy. We either 1) add a few maps or 2) make the addon a 'gameplay mod', not adding any maps at all. 1) is clearly superior to 2), but given the time left before release it would probably not be possible to fulfill the task. There are also not too many options for a gameplay mod anyway.
***
<details><summary>Oh, we can make a pack of all 60 original Wolf3D levels!</summary>

![image](https://user-images.githubusercontent.com/59409713/113479997-c5d6df80-949a-11eb-83c8-69c0f85ac269.png)
Just like Brutal Wolfenstein did. Sorry, I think this suggestion is two days late...
</details>

***

>By the way, your description says "enemies take triple damage", does that mean they are even harder to kill or easier because of their instant reaction?

The enemies are easier to kill (you'll need 3x less ammo to kill one on average), but with their instant reaction you'll now have to rely on your reflexes and luck to avoid bullets, which also deal x3 damage to you now. I think a substantial portion of Blood/other Build engine game fans would like this mode :-)
I just thought that in the base game enemy soldiers often wander aimlessly when they see the player, this is not what you would expect from a human soldier; hence this new skill level.

**Comment by Tormentor667** [comment]
Adding a few maps is, as you have already stated, not an option :) So I am totally okay with a gameplay addon - but something that is more interesting, something, that changes the game a bit more obvious. I think of mutators like in Unreal (Tournament) that fundamentally change the gameplay and add a huge replay value to the game.

Or we implement "unused material" (like enemies or weapons). 

Your new skill setting is a good start, but it's not enough for my taste :)

**Comment by Ozymandias81** [comment]
Regarding the boa_dt.pk3, how does we go for it, through an automated process or build it manually before release?

**Comment by Tormentor667** [comment]
I'd leave the question to @madame-rachelle

**Comment by madame-rachelle** [comment]
.boa should only be for mods, even if they are official ones.

boa_dt.pk3 is not a "mod" per se, but a feature.

As for splitting boa_dt.pk3 - you'll have to talk to the person who maintains your archive builder script. You may have to split that on your own. I'm not touching the version that's in the archive right now - I would make one that is much more simplified and less dependent on third-party tools.

**Comment by Tormentor667** [comment]
Thanks for the explanation. We'd be pkay if you'd like to change the archive builder so it creates a boa_dt.pk3 and a boa.ipk3 if you have some time left.

Without bothering you too much, did you have time to implement the mod feature in general?

**Comment by Tormentor667** [comment]
I sent a message to **hobomaster**, the programmer of _Doom Launcher_. With a bit of luck, he might be able to help us!

**Comment by Tormentor667** [comment]
Thanks for not giving up on this @madame-rachelle , I can imagine how frustrating this might be but I am very glad that you continue on getting it done somehow. Still one week to go ;)

Regarding hobo, he is currently on vacation so I am not sure if he can even help at all.

**Comment by Tormentor667** [comment]
I just share this for the discussion: In case of not getting the launcher finished, I'd simply release this without it, making the _dt part of he man ipk3, renaming the gzdoom.exe to boa.exe and replacing the icon of the .exe itself.

**Comment by madame-rachelle** [comment]
The existing launcher (the precompiled version anyway) should work just fine, just it doesn't have mod support. I don't imagine a project like this can go without a v1.1 release anyway, so would that be okay to finish the launcher for that?

**Comment by Tormentor667** [comment]
Sure thing, we can go for that solution. I still did a little change though, can you adjust the launcher to use boa.exe instead of gzdoom.exe?

**Comment by madame-rachelle** [comment]
I am only able to do that because of hex editing tools, as of now the old launcher is effectively closed source for me. Please keep this in mind if you are in need of creating any further adjustments.

**Comment by madame-rachelle** [comment]
Oh by the way - it has been done.

**Comment by Tormentor667** [comment]
Thanks kindly for taking care. Is the launcher also taking care of the boa_dt.pk3 functionality?

**Comment by madame-rachelle** [comment]
Yes that version of the launcher had it built in.

**Comment by madame-rachelle** [comment]
However boa_dt.pk3 still needs to be compiled separately by the archive maintainer. I still have not had a chance to write a tool to create the release archive, and I also would need to know where you have your shader at anyway (and anything else you need have separated in that archive).

**Comment by Tormentor667** [comment]
Well that's a good question actually. Wouldn't it be enough to seperate the gldefs responsible for the dt as well as the apropriate material folder? I currently wonder if that's even necessary/worth the effort in general, and if we just stick dt to the main release...

**Comment by madame-rachelle** [comment]
If that's all it needs then yes, really worth the effort. It's a feature on the launcher, anyhow.

**Comment by Tormentor667** [comment]
Can you deactivate that feature somehow through hex editing if we make the boa_dt part of the boa.ipk3?

**Comment by madame-rachelle** [comment]
No, not very easily. Why do you want to make boa_dt part of the main archive so badly? That is literally one of the most laggy parts of the mod! There *should* be an option to turn that off!

**Comment by Tormentor667** [comment]
Because currently I find it more complicated (and dangerous) to split it from the main package

**Comment by madame-rachelle** [comment]
That is not a very good reason. https://github.com/Realm667/WolfenDoom/commit/f3989a6b6f72496c71f62ef5384c25fda10d4595

This may need a bit of testing but it should work just fine. I split `boa_dt.pk3` for you, it's now inside the launcher folder.

**Comment by Tormentor667** [comment]
Wow, thanks a lot that was very quick. So the files are moved now and packed up separately? Or do I need to delete something else in the final ipk3?

**Comment by Tormentor667** [comment]
Update: Nevermind, I understand now what you did, that’s clever :)

**Comment by Ozymandias81** [comment]
Since mgrinz is working on a new launcher, with some help from Afadoomer, I am gonna close this.
