### ISSUE TITLE
Make "running" more suspicious for the Gestapo

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#298]
@AFADoomer there are a lot of occasions where the player can simply run by the Gestapo and avoid various other routes that are meant to be taken in C2M6_B for example. Can some alteration to the machanic be added that makes a "running player" more suspicious to the Gestapo?

**Comment by AFADoomer** [comment]
Should be good as of 8d111bcf05c5c6fe528743f4a97de97fbfd2cbc8.  There's a modifier value on line 93 there that can be tweaked if we want to speed up/slow down how quickly the suspicion level increases.
