### ISSUE TITLE
Replace "low-res" skybox textures with "hi-res" variants

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#299]
One of the big let-downs in Blade of Agony are the low-res skybox textures. I have already started to replace some of them with hires variants (1024x1024 pixels, no jpg artifacts) in the past, but I didn't find adequate replacements (remember: It is important to have a totally similar look regarding colors and depending fog in the maps themselves). Currently those which are missing a hi-res replacement are (in the "/textures/skybox" folder):

- [x] dawnsea (256x256 pixels, jpg artifacts, desperately needs a replacement)
- [x] ely_sunset (512x512, jpg artifacts, terrible quality, needs a replacement)
- [x] plaindawn (256x256 pixels, low quality, could benefit from a replacement)
- [x] plainday (256x256 pixels, low quality, could benefit from a replacement)

The latter two are no "must-haves" but the first two are really of terrible quality and I think finding good replacements would be nice. I have found this place for good skyboxes if someone wants to investigate: https://gamebanana.com/textures/cats/28

If you have to convert VTF files to PNG for example, this can be used: http://nemstools.github.io/files/vtfedit133.zip

**Comment by Ozymandias81** [comment]
Some fitting skyboxes may be found here as well

https://www.cleanpng.com/free/skybox.html

**Comment by Tormentor667** [comment]
These are unfortunately low-res either

**Comment by Ozymandias81** [comment]
I will invest some time on checking through my infinite resource from games and see if there are some skyboxes useful as replacements, some can be smart recolored changing hue/saturation/temperature color to fit with desired ambience.
Meanwhile [found these](https://imgur.com/a/WSGJ5), if we find some fitting sea that can be copy-pasted, one of these should work for dawnsea probably (4096x3072 jpeg format, doesn't have seams)

**Comment by Tormentor667** [comment]
I am at it, was able to improve them with the programm GigaPixel AI, but the problem now is that the border transitions are not perfectly. More information here: https://github.com/Realm667/WolfenDoom/commit/10b436c0e20e598fd2f6161a14a7622e4d17a6fb

**Comment by Tormentor667** [comment]
Done with today’s commits

**Comment by Ozymandias81** [comment]
I noticed some seams yet with this sky, just had to say it

![Screenshot_Doom_20201118_173130](https://user-images.githubusercontent.com/11136108/99690924-efaddd80-2a88-11eb-8837-302a92e862ce.png)

**Comment by Tormentor667** [comment]
Fixed in my commit.
