### ISSUE TITLE
Prisoners invincibility discussion reopening

### ISSUE THREAD

**Issue by DoomJedi** [Realm667/WolfenDoom#301]
...and you thought this mod could end without me opening my first "issue", heh.

I want to discuss prisoners invincibility.
First - I want to say (as Sonder maker) I fully understand both Torm's considerations/fears, and his weight of responsibility. Sonder was never publicly released, and was sent to dozens of trusted people, and their plays of it - do not indicate all the possible plays and feedbacks the mod can get. And media spotlight will be on Torm. So it's fully his decision, and I respect that.
There is always that fear that some neonazis will use it to upload videos where they just intentionally shoot prisoners (though now, they are not even clearly jews anymore even).
I understand all that, I really do.

Now, having said that - having Sonder gameplay/feedbacks experience, I think I have some important points to bring to this discussion.

1. Actual use of people of Sonder - they cared for the prisoners with alot of empathy and did everything to avoid that (though we even had special level built around this mechanics - "Morals"). They did that even in public Sonder remake where human prisoners were replaced by half-mutants (visually - mutants, most hated Wolf3D enemy usually).
This brought into the game very important gameplay mechanics and tactics...just as playing in an area with exploding barrels. You need to mind your position, shooting direction and aim, even weapon being used. Added to that is empathy to the game actors/setting/scenario/plot. Also more realistic - warfare in civilian location.
You can watch Origins videos for that.
So removing all of that - just for the safety...not too high price to pay?

2. Fear of neonazis uploading killing videos - you have to understand - if game does enough to show it's not the intended way to play the mod - it's not your fault, guilt, problem - in how others prefer to play it. Just as player cheating etc....
In Sonder we had clear mechanics to indicate this is not the intended way to play - if you hit prisoner - he knees/huddling in fear, with a chance to move out of the line of fire (you can add message "don't shoot the prisoners!"), once area is left - he stands up again. If hit again - he moves out of line of fire to a safer place. And if hit again - he dies with score/gold punishment and appropriate message.
This is more than enough to cover yourself media-wise and legally, to show this is not the intended way to play, and prisoners are not the enemy. You cannot blame yourself for any game action someone might take and self-proof yourself against any possible cheat or way of play, game gives player a choice - being a game. What people do - is not your fault, it's theirs.
So removing all of that - just for the safety...not too high price to pay?

3. Dumbing down the gameplay and mistrusting the player - treating him like a madman you need to hide scissors and sharp things from. Players hate that. Treating each player like potential prisoner-killer and jew-hater. Players love choice, game interactivity.
Maybe we should remove the cake girl or the Female Boss, just for the fear of players uploading videos masturbating on it?
Remove dogs out of fear of "dog killing" edited video montage - not to offend animal protection groups?

4. Hurting realism (I know, helpful NPCs...yes...it's there too)

**Comment by Tormentor667** [comment]
Well, first of all, thanks for the constructive criticism, that’s definitely useful and I do care about it.

The main reason for avoiding any offensive mechanic was as I said the public impact it might have. We have strict rules in Germany and having Dachau, Jews and a Concentration Camp as mission was too dangerous for me and my reputation.

The situation didn’t change. But the mechanics somehow did. Instead of jews only, we have Prisoners. Instead of Dachau we have a fictive Schattenau. And the camp is more a laboratory than a Holocaust location. These things make it much easier now for reconsidering the invincible prisoners.

I think a different approach might work: If the prisoners get hurt, they get invincible for a few seconds and the first time they knee and take cover. The second time they run away. The third time they die and you lose treasure. 

If @Ozymandias81 , @AFADoomer or @Talon1024 are willed to code that, I am ok with it.

**Comment by DoomJedi** [comment]
Regardless of the final decision on this, I want to express sincere appreciation for you listening to my suggestions and reasonings behind those and being open for constructive...suggestions.

I know this is sensitive issue regarding sensitive level, with possible fearful implications, I woudn't want the mod to cause negative effect on your personal life and reputation.
So do what you find most appropriate in this case.

**Comment by DoomJedi** [comment]
So, guys, any intent and ability to code it in? All art is already there.

**Comment by DoomJedi** [comment]
Thanks :) better than nothing I think. 

But I still think it doesnt do what it need to do - warn the player and reflect to the player that is not the intended way to play. So you make it bulletsponge Boss type...doesnt say not to shoot them, just adds to the challenge.
Huddling + flee is way better, can post links to Origins videos. How hard are those to add? Wasnt it coded before? Any flee code in boa? Huddling state is not hard either, like half-dead state.
Not a coder, feel free to correct me if im wrong.

**Comment by Tormentor667** [comment]
I agree with @DoomJedi , that approach would be a bit better indeed.

**Comment by DoomJedi** [comment]
To add to that - making weakest, starving and barely dead anyway prisoners into Boss-type bullet-sponge - is not only unrealistic, but anti-realistic.

I don't ask for too many features in this mod, as you know (if at all). This one I prefer to have no shortcuts on. This level and thematic is very important to me.

**Comment by Ozymandias81** [comment]
You should check how it works in game first, specially on the map where you have not many chances to shoot at prisoners unless you want to get killed by nazis surrounding you. Anyway the player warning is already in, it just needs to be coded, and flee and head cover is there for bald prisoners/shirtless ones. Standing ones doesn't move for obvious reason, they are usually decorative, and it is not about making them bullet sponge, but instead make feel players stupid to throw away bullets (or a couple of rockets) just to kill prisoners and see money removed of 50 coins. What's this huddle you talk about? Remember that I just propose a way to code it, sure a zscript approach is better, but idk how to do that and anyway adding new features is always a problem, specially until we stitch continuosly to non stable builds of GZDoom.

**Comment by Tormentor667** [comment]
I do agree with @Ozymandias81 on this one. On another note, maybe even adding the "crosshair warning" (like npcs and spies) to the prisoners might already be enough of a hint for the player to make it clear that shooting prisoners is not intended.

We can avoid removing money or other mechanics in this case which saves Ozy a lot of work. What do you think guys?

**Comment by DoomJedi** [comment]
Well, what I called huddle (term used by Sonder devs) is what you call "cover" I guess. "Crossfire prisoner" folder. There is even possible "rolling out of line of fire" frames there.
_ADDED\#Concentration Camp\Prisoner\Crossfire prisoner

Unless standing prisoner as used as "map blocking path" element, to block path to some doors/areas - there is nothing in "standing" concept that prevents standing prisoner to start moving once shot.
Or do you mean the lack of the hat? I can sure add additional skin needed for hat-prisoner to walk. Can do those tomorrow.

**Comment by DoomJedi** [comment]
They can even sometimes roll away if hit, and sometimes walk...

**Comment by Ozymandias81** [comment]
Updating comment here saying that now prisoners can be killed if we spend some time shooting at them, but we'll lose 50 coins and maybe a message will appear too for players doing it. Bald/shirtless can wander around, flee frightened and "cover/huddle", plus on top of these "features", now all prisoners have the X crosshairs blinking once we aim at them with a weapon. On my end I think this should work well, make them "roll" being starving and barely dead shouldn't work as well, plus never seen a camp prisoner doing that anywhere XD
So unless @AFADoomer will have a better way to code these, I'll think myself how to implement the message popup properly for players and all should be good as is.

**Comment by Tormentor667** [comment]
I’d avoid removing coins after thinking about it. All the other functions are clear enough to show the player that prisoners are not supposed to be killed.

**Comment by Ozymandias81** [comment]
Reverted coins removal from prisoners, I think if everybody are satisfied with this, we can close the issue.

**Comment by Tormentor667** [comment]
I agree, well done Ozy!

**Comment by Username-N00b-is-not-available** [comment]
Just noticed that regular prisoners (e. g. Camp_PrisonerBald) say German soldier phrases when running after being hit (you can test it on C3M1_B).

**Comment by Username-N00b-is-not-available** [comment]
Looks like this fixed the issue, thanks @Ozymandias81!
