### ISSUE TITLE
Unsolicited praise

### ISSUE THREAD

**Issue by mcphail** [Realm667/WolfenDoom#304]
Just wanted to let you guys know you're doing an awesome job. I've been tweaking the snap build in the background, all the time watching your progress. I can't wait to have the opportunity to show this to people!

**Comment by Ozymandias81** [comment]
Thank you @mcphail we are not far from a first complete release! :muscle:

**Comment by Tormentor667** [comment]
Thanks so much for your kind words :) this is what motivates us the most!

**Comment by Brian-McElroy** [comment]
Hi I would also just like to say this mod is awesome!! Its really fun action + I love the crazy amount of references to other 90's games a pop culture.. 
Ive been checking your website regularly waiting for episode 3.. I actually tried to run this version. I was able to build a pk3 file using the batch file, but it didnt work with my gzdoom (or by substituting pk3 file in a download of episode 2 release)
Would you mind telling me how to run this version? I defo dont want to wait for voice acting or translations (im not a fan of voice acting in games anyway)

**Comment by Tormentor667** [comment]
Thanks for your kind words as well :) the final compiled pk3 should work well with the latest GZDoom version available at zdoom.org

**Comment by Username-N00b-is-not-available** [comment]
@Brian-McElroy Hello and thank you for your attention to Blade of Agony!
Please keep in mind that even the core of modification (i.e. not counting translations or voice acting) **is still in development**: not all the maps and sequences are finished. This is just for your information, the most part of BoA is playable now.
No wonder you could not get it to work with C2 version: it's been more than three years, and during this time GZDoom has changed a lot, adding lots of cool features which we tend to use in BoA.
As he stated in his message, what @Tormentor667 said will apply to the final version of the mod. As for today, we test the git version on the latest development builds of gzdoom, which can be obtained here: https://devbuilds.drdteam.org/gzdoom/ You can just download a suitable archive, unpack it, then move the .pk3 file to the directory. To launch the game you can just drag-and-drop the .pk3 over gzdoom.exe, or use the command line or a launcher of your choice. AFAIK no IWAD is needed now.

**Comment by Ozymandias81** [comment]
Just a minor correction: you do need an IWAD if you play the game as .pk3 file, instead if you want a proper BoA experience, rename the .pk3 built file as .ipk3, then run gzdoom and it will automatically recognize it as a distinct game, you'll just need to select it once gzdoom is run

C2 was intended to be played with gzdoom 3.2.1/3.2.5 max, so in case you still want to play it check for that versions

**Comment by DoomJedi** [comment]
Thank you for the kind words, this is very rewarding. 

...Freedoom iwad works fine
