### ISSUE TITLE
MuadDib90 #1 translation debuging playtesting

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#305]
I am primarily testing Czech translation, but if I think it concerns also English, I'll let you know.

This concerns everything until the very first mission starts.

- [ ] **The first letter**
"Dear William..." have broken czech diacritics. Charakters as (áéíýóú) seem fine, but charakters (ůěščřžďť) don't appear at all. Instead there are regular charakters (uescrdt). _[assigned to @Talon1024]_
.
EDIT: The same issue is with 'text papers' in-game.

- [x] **Speaking more of the letter:**
I had problems with reading it in time. And I even know, what it is about, and I read it in my native language. It just scrolls too fast. If you want to indulge players the comfort of knowing the story behind (if they want of course), I'd suggest to slow down the automatic scroll to let's say 0,7x of the original speed. That should do the trick.

- [ ] **Last thing about the letter:** 
I did (unintentionally) something that appear to cause the letter to scroll when you are already in the intromap at HQ. _[assigned to @AFADoomer and @Talon1024]_

<details>
      <summary>Screenshot</summary>

![letter](https://user-images.githubusercontent.com/73436978/98465831-fa848a80-21cb-11eb-909a-24adc5d771a8.PNG)

</details>

I did this:

1. Started a new game. There is first intro with Douglas typing a letter. After a couple seconds the sound of typewriter appears and also the mouse kursor is visible now.
2. Then I pressed ESC key and the GZDoom menu appeared. - The sequence goes on at the background. Sound of typewriter and a song continue. After a while it changes into 2nd intro with newspapers.
3. After that music from HQ starts and you are in. Now I pressed ESC again and the letter started appearing.
(My point of view: When you hit that ESC key the first time as I described, the script for scrolling the letter has already started and it has been "paused" by the ESC key, then simply continues where it was before, after you jump into game again.

Fun fact: When I got to windows using WIN key to get a screenshot, and then head back to the game, the letter immediately after my return disappeared (no matter how much it was scrolled up).

- [x] **Color of the texts**
There is not seem to be color difference between 'white' (\cJ) and 'gray' (\cC) as pictures show:

<details>
      <summary>Screenshots</summary>

![color diff 01](https://user-images.githubusercontent.com/73436978/98465906-7a125980-21cc-11eb-9b2b-e72b70cac46d.PNG)
![color diff 02](https://user-images.githubusercontent.com/73436978/98465909-7da5e080-21cc-11eb-97e7-8608df0c4db4.PNG)

</details>

- [ ] **Overlap (for the time being only) of toilet text:**
But I think it's just because the border frame for the text is longer than it should be. Nothing more scary... Human would expect it end by the end of dark grey zone under (which I know is very different "object"). _[assigned to @Talon1024 ]_

<details>
      <summary>Screenshots</summary>

![zachod 01](https://user-images.githubusercontent.com/73436978/98465365-f0ad5800-21c8-11eb-9a7e-689bf1dcce5a.PNG)
![zachod 02](https://user-images.githubusercontent.com/73436978/98465373-f60aa280-21c8-11eb-916a-26bffbedb8e2.PNG)

</details>

- [x] **Different weapon (skin?):**
At the beginnig of a training course, you get a Walther. But on the shelf was Luger.

<details>
      <summary>Screenshot</summary>

![walther](https://user-images.githubusercontent.com/73436978/98465558-0a9b6a80-21ca-11eb-9b91-c0f864307332.PNG)

</details>

- [ ] **And one suggestion in the end:**
A percentage indicator in the inventory icon of mine detector would be very convenient. If it isn't ON, you don't know how much is left. So knowing it without a need of turning it on would be great. _[assigned to @AFADoomer and @Talon1024]_

EDIT:

- [x] **CSY language support**
Please add a Czech language possibility in the options menu.

**Comment by Tormentor667** [comment]
Fixed the text colors on this commit: https://github.com/Realm667/WolfenDoom/commit/d211ddf8f8349fffdc3bf5ea9cbb2d40ef54f258

**Comment by Tormentor667** [comment]
The Luger has already been fixed by someone else, just checked it ingame.

**Comment by Tormentor667** [comment]
Fixed the letter-scrolling speed in the INTROMAP

**Comment by Tormentor667** [comment]
Added czech language to the supported languages, thanks again for doing this :)
