### ISSUE TITLE
MuadDib90  #2  translation debuging c1m2

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#306]
Today I have two things.
First a "cosmetic one":

- [ ] **Dev_coms overlap**
This particular dev_com, even in english, is overlaping the box. There are several others with same problem, judging by the length in language.csv.
Do you want to deal with it at all, or is it much work for so little outcome? _[assigned to @Talon1024]_

<details>
      <summary>Screenshot</summary>

![01](https://user-images.githubusercontent.com/73436978/98719399-ff923700-238f-11eb-80ca-0ab6ad0ca6e7.PNG)

</details>

Second one, although not critical, but is very important indeed:

- [ ] **Mission c1m2**
The point of the mission is to safe Ryan. To get him to safety with you, to the point, where Douglas is waiting with the truck.
So if you can open Ryan cell, then use a 'hold position' command on him (then maybe just forgot it!), and then complete the rest of the mission, going to Douglas, press 'use' key on him to end the mission and actually end the mission with Ryan still being in his cell... 

But in my opinion it 'only needs' one condition in script, that Ryan must be in some defined radius around Douglas to be possible to end the mission. Maybe some warning from Douglas, if Ryan isn't there with you in that radius. _[assigned to @AFADoomer and @Talon1024]_

**Comment by Tormentor667** [comment]
The first problem can be solved by shortening the text @Talon1024 

The latter is something @AFADoomer might be able to solve.
