### ISSUE TITLE
Milestone achieved | time to celebrate

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#307]
Dear developers, dear comrades, dear friends,

today marks a special day in the development timeline of Blade of Agony. With today's commit from me (https://github.com/Realm667/WolfenDoom/commit/f546256febc8dc3a3fd7accd5cfce71a79ad7457), the complete mod is fully playable, all maps are set and the only thing left to do from now is balancing, improving and bugfixing.

@Ozymandias81, @Talon1024, @MuadDib90, @DoomJedi and I took the opportunity in our Facebook Chatgroup for a drink (a few beer, a few soda, things that make you happy - maybe we all will be able to meet for a Zoom or other Videochat as soon as the mod is released, to celebrate our time together).

On 10th of February 2015, I opened the development thread over ZDoom.org which started it all. Look how far we came now! Time to stand together now, focus on the largest and most complex Doom project that has ever been made and bringt it to an end - I am so motivated and I can't wait to see the release.

There is not much left to be done, the list of issues is short, but it is essential that all of us concentrate on the remaining bugs one final time before we can launch the beta tests. **Let's do it!**

![Unbenannt-1](https://user-images.githubusercontent.com/10298439/98727257-f1e0af80-2397-11eb-9f73-965ff809e8c1.jpg)

**Comment by Ozymandias81** [comment]
Damn, in 3 months or less we'll reach 6 years of development! Can't wait to see what people will think of our awesome team effort friends. 😄

**Comment by nashmuhandes** [comment]
Congratulations! It's inspiring to see large projects like this reach the end.

**Comment by DoomJedi** [comment]
This could be a good time for site and zdoom forum update.

**Comment by Tormentor667** [comment]
Give me a few days, I will prepare something :)

**Comment by Tormentor667** [comment]
Made updates to the forums, the webpage and the Realm667.
