### ISSUE TITLE
Introduction sequences in C1M1/C2M1/C3M1_A use wrong overlay graphic

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#308]
Currently all three use MOVIEHD5 whereas they should use MOVIEHUD instead.

**Comment by Ozymandias81** [comment]
Fixed in my incoming commit.

**Comment by Tormentor667** [comment]
Thank you

**Comment by Talon1024** [comment]
> Fixed in my incoming commit.

You can write "Fixes #308" in the commit message
