### ISSUE TITLE
Control bars in options/menues shouldn't use WHITE as translation color

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#309]
Instead, they should use GREY or DARK GREY. I am not sure where this can be controlled but somewhere it should be possible. I am sure @Talon1024 or @AFADoomer know a solution here. Currently they are too bright and look out of place after I changed the color sheme of the WHITE color setting in the TextColo lump a few days ago https://github.com/Realm667/WolfenDoom/blob/master/TextColors.txt

**Comment by MuadDib90** [comment]
Where I could, I dealed with it in Czech translation by adding "\cC" in BoA language.csv, but as for the GZDoom menu, it must be changed in GZDoom language.csv, I suppose.

**Comment by Tormentor667** [comment]
I actually have no idea where this is located, so I will ask in the ZDoom forums.

**Comment by Tormentor667** [comment]
https://forum.zdoom.org/viewtopic.php?f=122&t=70606

**Comment by AFADoomer** [comment]
It's hard-coded to white in the engine ZScript.

**Comment by Tormentor667** [comment]
Can this be changed with ZScript somehow for the mod? Otherwise I need to change the color range again in the TextColo lump to something that works better.

**Comment by Tormentor667** [comment]
Fixed it.
