### ISSUE TITLE
MuadDib90 #3 translation debuging

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#310]
Some issues with counters:

- [ ] **C1M4**
Counter doesn't show up at all...

<details>
      <summary>Screenshots</summary>

![01](https://user-images.githubusercontent.com/73436978/99196593-b0804380-278d-11eb-8313-052074f20d97.PNG)
![01a](https://user-images.githubusercontent.com/73436978/99196600-b70ebb00-278d-11eb-9c60-46e46474120e.PNG)

</details>

- [ ] **C1M3 and C2M5_B**
Prefix doesn't show up (even in other languages - I checked it). Yes, in the sheet there is written, that in C1M3 there is no prefix; and I ask why is that? I could make a good use of it. -- However, in C1M5_B, there should be, but it isn't too...

<details>
      <summary>Screenshots</summary>

![02](https://user-images.githubusercontent.com/73436978/99196757-b32f6880-278e-11eb-9697-53c76b3b9211.PNG)
![01a](https://user-images.githubusercontent.com/73436978/99196765-bb87a380-278e-11eb-9e7a-68099cea3e18.PNG)
![03](https://user-images.githubusercontent.com/73436978/99196767-be829400-278e-11eb-89ff-2ed7c9274547.PNG)
![03a](https://user-images.githubusercontent.com/73436978/99196771-c2aeb180-278e-11eb-8d23-a9a043b9146c.PNG)

</details>

- [x] **Missing line = identifier placed (solved)**
If the line is 'empty', nothing is written in it, the identifier is placed insted. I work around it by "writing a 'space' in the line", so nothing will be visible in actual game.

<details>
      <summary>Screenshots</summary>

![04](https://user-images.githubusercontent.com/73436978/99196987-cee73e80-278f-11eb-8fcd-1402cf3c553f.PNG)
![05](https://user-images.githubusercontent.com/73436978/99196995-d1e22f00-278f-11eb-9ba8-da788b24674b.PNG)

</details>

**Comment by Tormentor667** [comment]
Could you be so kind and combine all your testing issues into one issue? :) (making 1 out of 4 issues)
