### ISSUE TITLE
Time to decide a proper setup for our Post Process options

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#311]
So as the title says, we must decide which PP option should be enabled or not per default.
As many of you may have noticed, setting also Trilinear/Bilinear filtering on with BoA breaks many things visually, and that's why in our custom launcher "no filters" is set as "recommended", so this issue is for the same reason: something that keeps us anchored to old retro style but also with an enhanced feeling which doesn't alter too much our art in movement.

Vignette, Lens Flares, Film Grain, Heat & Sandstorm plus Motion Blur imho should be off, maybe just Blur on
Sandstorm is pretty intensive on my GPU, which is a bland 1gb Nvidia GT610, turning it off increase playability a lot in several situations.
Bloom on per default and no resize filters enabled are also my other 2 important changes that I usually do.

Now let's discuss about your suggestions, obviuously with a final word from @Tormentor667

**Comment by DoomJedi** [comment]
As I told before: 
I think Bloom should be a must (though it looks weird on zombies and such). Care less about the rest listed.
Also clipping should be set to ALWAYS, or sprites dig in half way into the floors.
Texture filtering should be set to OFF by default, 
Film Grain should be OFF as well.

This is as much as my opinion goes.

**Comment by Tormentor667** [comment]
In my opinion, a game should always be delivered in the way it is meant to be - meaning with the options activated that the developers see as „This is how we imagine the visuals in the best case“.

Therefore, everything should be activated (including heat shaders, sandstorm, bloom, etc). Why? Because it’s the best case.

If players notice that they suffer heavy fps drops, they can adjust their settings until they end up having a reasonable performance (that’s what the predefined settings are for, that’s what the launcher is for).

Regarding the texture/sprite filters, I‘d set them to „no filter“ as standard though, the pixelated charme of our mod is priceless :)

**Comment by Ozymandias81** [comment]
Okay so settings mentioned by Torm have been already set per default, anyone have something to add to this? Otherwise will close it next week.

**Comment by Tormentor667** [comment]
I agree with the suggestions @Username-N00b-is-not-available made, they are reasonable.

**Comment by DoomJedi** [comment]
I disagree, I always use turn left/right as i never use strafing.
Hate games that hide or disable that option.

I also love chasecam. Especially on multi-player-skin mod like ours.

**Comment by madame-rachelle** [comment]
I think the movement and strafe keys should be bound to WASD, and have the classic Doom controls on the arrows. Some of the controls I think are safe to throw off and leave in the old GZDoom keybinds menu, but some should definitely be kept for the mod itself.

Throw:
Weapon Zoom,  mouse look/keyboard look ones (what about these?), Toggle Run, Strafe; Drop item, Drop weapon; Toggle zoom, Toggle grid (automap key); the entire chat submenu; Coop spy.

Keep:
Turn left/Turn right; Chasecam

Maybe?:
flying ones,

About the flying keys - those need to be kept if there is any swimming at all in the mod. Some people prefer using classic flight controls and in order for that to work you need Z-axis control.

**Comment by madame-rachelle** [comment]
As for shaders I don't have much of an opinion. When I play tested the mod I found I was scrambling to turn them off right away, they really didn't enhance anything for me and I preferred them off - but that's just me.

**Comment by AFADoomer** [comment]
The fly controls can also be used for ladders...  between the climbavle zones and the number of underwater areas, it doesn't make sense to remove them (though I'm pretty sure I bound an alias of crouch and movedown together for my install).  I agree with Rachael's recommendations.  And her assessment of (and reaction to) the screen shaders.

**Comment by Tormentor667** [comment]
I also agree with Rachael on the control question.

**Comment by DoomJedi** [comment]
As long as texture filtering is off, other shaders...don't mind. Still, there are some "old movie look" shaders that I don't see as " but it'd be nice to let them know what it could look like.", those are artistic/stylish degrading of the look, not upgrading. Some might like, most - won't.

**Comment by Ozymandias81** [comment]
I think [these changes](https://github.com/Realm667/WolfenDoom/commit/f7c8d555b5abb75afb6c56fae38a5296fb293f78) will satisfy all tastes, regarding controls. About shaders I am with DoomJedi, but well not a major problem... Maybe an option to be included on launcher?
