### ISSUE TITLE
Chapter 2 Issues - Alando1

### ISSUE THREAD

**Issue by Alando1-doom** [Realm667/WolfenDoom#312]
Hello all, for those who may or may not know me, I'm Alando1. I'm usually on the Zdoom Forums and sometimes on Doomworld. I, too, am the creator of the Temple of the Lizard Men series. I offered to help Tormentor667 with the testing of BoA. I finished the playthrough and I here is my critique for Chapter 2:

C2M1:

For the most part, this level was pretty good. 
- [x] In one area, though, around one of the spotlight areas, the middle spotlight can still sense the player even when it's not touching them. The area of concern is around these coordinates: x=-2995 y=-4260 z=0
I felt this particular area might need further tweaking. Other than that, the rest of the level was fine. _[assigned to @AFADoomer]_
> I have reduced sight radius for spotlights placed on those zone and also moved a bit their angles to give some space to BJ. In order to sneak properly there, you must have a karabiner and always crouch, then aim at proper distance to shoot to spotlights and destroy them, so later you are free to sneak silenlty without killing anyone in the zone, so also not spawn dobermann which turns the hide impossible if alarms are set. --Ozy81

C2M2:

The level was fine, however, 
- [x] I spotted a minor bug with a chaingun turret tripod. Two seem to have appeared. This likely was caused when another enemy took control of the turret after I killed the initial gunman. The area of concern are around these coordinates: x=1473 y=1990 z=-576

C2M3:

This level was a bit laggy but it's not your fault - my CPU is not the best in the world... Anyway, the level was fine, however,

- [x] in a secret cave area, the 3D model of a rock was not solid. The coordinates for this are: x=5961 y=-3043 z=-128

C2M4:

The most fun level of the chapter :) No major complaints.

C2M5_A:

Love the UFO & train bit - No major complaints.

C2M5_B:

- [x] The catwalk over the purple pool with fans blowing you around is a bit annoying. To be honest, I felt it would've been better to have projectile based enemies firing at the player instead of fans blowing you around. Other than that, the rest of the level was fine.

> I heard issues now for numerous times regarding the area. Instead of having the wind blow you around like a gumball, I simply reduced the strength of the winds to make the area less frustrating.

C2M6_A:

Level is fine - No major complaints.

C2M6_B:

Level is fine - No major complaints.

C2M6_C:

- [x] Found a floating door texture at these coordinates: x=9975 y=13880 z=306
I took a screenshot of it, too (not sure if I'm able to upload it). It appears this floating texture coincides with the main entrance door to the building the player gains access to.

- [x] Within the mining/caverns area, in the lava section, I wasn't sure if you wanted to scroll the lava falls or leave them the way they are. The area of concern are at these coordinates: x=6039 y=-27999 z=-318

Other than those bits, the level was fine - especially the temple area.

That is my critique for Chapter 2. There are some issues, but it doesn't take away the fun factor. I still enjoyed it :)

-Alando1

**Comment by Tormentor667** [comment]
Dear @Alando1-doom thanks kindly for your feedback in Chapter 2-3, I will work on the issues as soon as I can.

Did you spot anything major in Chapter 1? I also noticed you didn’t give feedback on the secret missions in C2 and C3 or the super secret maps. Didn’t you find them?

**Comment by Alando1-doom** [comment]
In Chapter 1, there were minor things. I noticed the Chapter 1 Issues section was closed so I was unsure where I could mention them. In any case this is what I've found:

Tutorial Section of the HUB Level:

I had some trouble with the ladders within the obstacle course. I couldn't climb up them for some reason. As a note: I would double check the ladders that appear in the other levels just to be sure they are working. I didn't have these issues with Chapter 2 or 3.


C1M1:

The switch to open the exit gates isn't easily noticeable. The player may walk past it by accident. Perhaps putting a green light beacon around it might make it more noticeable. Other than that, the level was fine.


C1M2:

Had trouble with Agent Ryan but I eventually figured out you can press 'use' to tell him to hold position. Other than that, the level was fine.


C1M3:

Level is fine - No major complaints.


C1M4:

Level is fine - No major complaints.


C1M5:

Level is fine - No major complaints.


C1M6:

Best level of the entire Chapter. There was one tiny texture misalignment in the mining cart bit. If the player walks back the way they came via the train rails, there's one sarcophagus with a misaligned texture. Other than that, this was the most fun level. The overall architecture and Indiana Jones inspired vibe really makes this level epic.


C1M0:

The level was fine, however, I would strongly advise to indicate the exit path when the player leaves the facility. The area that branches off to where the player has to go is not noticeable especially if the player had not discovered it prior. Maybe put the exclamation point there to remind/notify player to go that way. Once I exited the facility, I ran straight back to the very beginning of the level since I thought that was the exit. All in all, that is the only complaint I have with this level.


In regards to the secret levels for Chapter 2 & 3, I had not come across them. I think I might've found the entrance to the one in Chapter 3 but I didn't have enough green souls to get through (I think this might've been the secret exit?) In any case, I will go back and play them. From there I'll let you know how it goes. :)


-Alando1

**Comment by Username-N00b-is-not-available** [comment]
@Alando1-doom To access the secret level C2M0_A (+ _B) in Chapter 2 without cheats you should collect all five Mayan artifacts (each one lies in a separate map, in C2M1, C2M2, C2M3, C2M4, and C2M5_B) and report to Gutenberg, just like with the Eisenmann files in Chapter 1.
Chapter 3 has two secret maps, C3M0_A can be accessed if you manage to collect all 6 clues on C3M1_A and _B and afterwards report to Lt. Anthony F. Arlow in the HQ (communications room on the upper floor of the building). The second level C3M0_B is accessed from a certain closed room in the HQ which opens (IIRC) after C3M4.

BTW you don't have to replay all the levels if you just want to test these specific maps, you can use something like 'warp C2M0_A'.

**Comment by Alando1-doom** [comment]
@Username-N00b-is-not-available  For Chapter 2, I knew I was missing 1 more Mayan artifact - I found 4, though.

I played through the Chapter 2 secret levels and I loved them! I only found minor issues.

C2M0_A:

First, let me just say how awesome this level was. I noticed a lot of Temple of the Lizard Men and Unreal references :) This level was beautifully well done. The level design, the music, the atmosphere - EPIC! The only area that needed fixing was a waterfall with the textures scrolling in reverse (in screenshot). Other than that, this level was fine as well as incredibly fun :)
![Screenshot_BoA_20201202_191022](https://user-images.githubusercontent.com/75344456/101214744-7e565900-364a-11eb-941c-c1837523c262.png)

C2M0_B:

This level, too, was very well done. Got a bit of a Blade Runner vibe in certain areas :) The only things I would recommend is:
1. Add a health bar to Cyber Hitler
2. Modify the stronger photon gun (the one that lobs an energy ball). I feel it would be better if it just fires the projectile straight instead of lobbing it like a grenade. Just a suggestion.

Other than that, this level was fine.

I will post the Chapter 3 secret level critique in the Chapter 3 Issues section.


-Alando1

**Comment by Ozymandias81** [comment]
Cyber Hitler has been fixed [already](https://github.com/Realm667/WolfenDoom/commit/05c2df0a65f1a7ec8546413155ca962c2ca841a6) by me, you must turn off laser barriers and then it will pop up.

**Comment by Tormentor667** [comment]
Check the alt-fire of the weapon and you get what you want :)

**Comment by Alando1-doom** [comment]
Okay, cool :)
