### ISSUE TITLE
Chapter 3 Issues - Alando1

### ISSUE THREAD

**Issue by Alando1-doom** [Realm667/WolfenDoom#313]
Hello. This is my critique for Chapter 3. I did find a handful of bugs but I will address them below.

Chapter 3 intro level:

Love the horror element. To be honest, it has been a while since a Doom level made me feel genuinely spooked. No major complaints though.

C3M1:

Level was fine - No major complaints.

C3M2:

My CPU was struggling but I enjoyed the tank bit very much. Had a nice UT2K4 vibe :)

C3M3:

>C3M3_A or C3M3_B? --N00b

- [x] The level was nice for the most part but I did find a glitch in the floor around these coordinates: x=7377 y=6028 z=-120
Not sure if it's on my end or not but I recommend checking it out to be sure. It doesn't effect the gameplay in any way.

C3M4:

I certainly got a Resident Evil vibe with this level. The music and skybox really added to the atmosphere. I enjoyed the ending portion with fighting a horde of zombies in a little town. This level, overall, I found to be the most enjoyable of the chapter. I did, however, find a couple of issues. 
- [x] 1. Three guard dogs seem to be frozen and inactive at these coordinates: x=3170 y=-3949 z=-80
- [x] 2. There's a tank that is not solid. It can be found around these coordinates: x=5567 y=-2136 z=184

C3M5_A - B:

The onslaught is quite difficult. This certainly will challenge players in a good way.
- [x] When the player reaches the airport to board the zeppelin, I noticed enemies wearing a blue-green uniform have death animations of enemies wearing brown uniforms. _[assigned to @Ozymandias81 and @Talon1024]_

C3M5_C:

This level was very well done.
- :x: I would recommend giving the player just a little extra time to evacuate the zeppelin. Since the ship is tilting, it is much more difficult for the player to maneuver in certain areas. A little extra time would be advised.

> I'd actually keep it as is. It is solvable and it is a reasonable amount of time, but it should be challenging and I think there is no need to make it at first try. --T667

- [x] The other issue: I found a texture glitch on the lift behind the Red Door. I took some screenshots of it, although I'm not sure if I'm able to post it here. I do have the coordinates, though: x=9587 y=-12664 z=-96
When the player flips the switch, the checkered "missing texture" graphic appears.

C3M6_A:

- [x] At the beginning of the level, the player is vulnerable to being attacked by zombies during the cut scene. Other than that, the rest of the level was fine.

C3M6_B:

- [x] In the Skull Key tomb room, the player can easily escape the trap with enemies if they're quick enough.
- [x] I would advise going easy on the tricks and traps around these coordinates: x=2129 y=-2512 z=-48
The spike traps are placed in an area where it can be a bit annoying/unfair for the player since they already have a lot being thrown at them all at once. I would recommend reworking this trap area. Other than that, this was my biggest complaint throughout the level.

C3M6_C:

- [x] The mini-boss battles were alright but zombie James Ryan was a bit of a pain to deal with. He's way more erratic than the other two bosses and since the sword is the only weapon that can do any real damage to him, hitting him with the sword projectiles is extremely difficult. I would recommend he be a little less erratic or even have moments where the player has a brief window of opportunity to strike him with an effective attack. Just a suggestion. _[assigned to @Ozymandias81 and @Talon1024]_
> Decreased health a bit, now rounded to 4000 and also made attacks less frequent, this way also with fastchase called only one time per See state it should be more feasible fight with Ryan, because there are several spaces to hide, hit and run the enemy around the flak tower. --Ozy81

Other than that, the rest of the level is a good final level. It certainly challenges the player to use every bit of skill they have. In a way, the final battle felt similar to the ending of Doom 3 (killing enemies to recharge the player's strongest weapon so they can use it on the main boss). All in all, not bad.

After my playthrough of Chapter 3, I found it to be enjoyable for the most part. Still, I have to say, C3M4 was _the_ best level of the chapter. What I liked most about BoA is that it was a very inviting game. I felt I wanted to go back and play some more. I wasn't turned off by it (even with some minor bugs). It has a good fun factor to it and it feels good to play. Even though it is a long campaign - especially Chapter 2 & 3 - I enjoyed it from start to finish. :)

-Alando1

**Comment by Username-N00b-is-not-available** [comment]
Hello, @Alando1-doom, and welcome to Blade of Agony repository! Thank you for testing the game, it is very pleasing to hear that you enjoyed it. One question though: have you tested Chapter 1, or the secret levels in C2 and C3?
Regarding the C3M6_A map, as for now the player spawns near the end of the map, skipping a very large portion of it (I left the player start near the area I am still currently working on with other developers, and it looks like this has gone unnoticed by @Tormentor667 who invited you to test the maps).
Do you mind if I edit your post and add checkboxes to the problems you mentioned, so later we can keep track of what has been resolved?

**Comment by Tormentor667** [comment]
@Alando1-doom thanks kindly for your report, @Username-N00b-is-not-available is right, C3M6_A is left with a map spot on the wrong place, I should have thought about it before sending the beta, as you are missing the complete map now :) 

@Username-N00b-is-not-available please add the checkboxes :)

**Comment by Username-N00b-is-not-available** [comment]
Updated the original post, will also do that with C2 issue.
@Alando1-doom, to post a screenshot you can drag-and-drop the image file over the message box, it works well for images smaller than 10MB.

**Comment by Alando1-doom** [comment]
@Tormentor667 It's quite alright :) Still a pretty good level nevertheless.

@Username-N00b-is-not-available  Okay, cool. I wasn't sure before - still getting used to GitHub. Anyway, I'll post the screen shots where I found some of the issues.

The first one is from Chapter 2 - C2M6_C:
![Screenshot_BoA_20201201_180905](https://user-images.githubusercontent.com/75344456/100945366-13ccde00-34cf-11eb-9590-a0ea75e3bb50.png)

The second one is from Chapter 3 in the zeppelin level:
![Screenshot_BoA_20201201_185727](https://user-images.githubusercontent.com/75344456/100945444-3b23ab00-34cf-11eb-819a-6b537b274319.png)

-Alando1

**Comment by Alando1-doom** [comment]
For the Chapter 3 secret levels, there were some things of concern, particularly in the first secret level, C3M0_A. Only one issue with C3M0_B.

First, I'll start with C3M0_B:

The only issue I found was right after the player enters the Amber room to collect the treasure. When the player tries to escape through the vent grate, after smashing it open, the area is impassable (refer to screenshot). Other than that, this level was fine. Love the stormy weather effects, by the way :)
![Screenshot_BoA_20201203_205636](https://user-images.githubusercontent.com/75344456/101215608-228ccf80-364c-11eb-8d62-96c0d4bddc70.png)


Now for C3M0_A:

This level, I did have a bunch of problems with. Before I get into it, I first want to say I loved the Resident Evil inspired vibe. The references to RE1 with the Spencer Mansion was wonderful and RE2's Racoon City - not to mention the save rooms. 

The issues I found were:

1. I came across a couple of notes with some typos/grammar errors in them. One in the cabin in the first portion of the level (around the mansion area) and one in a shed within the mining area. I couldn't screenshot those for some reason. 
2. My computer was lagging terribly due to the constant spawning of enemies. I had to modify some graphic settings and I used some console commands like "freeze," "fly," and "give infrared."
3. The areas that had ropes were not climbable. I had to use fly mode to get to where I needed to go.
4. I couldn't find a lantern to use in the dark areas.  I came across lantern fuel but no lantern.
5. When I entered the city section of the level, every time there was a sound of sparks, the game briefly froze. This occurred until I finished the level.
6. I found some misaligned textures (refer to screenshot)
![Screenshot_BoA_20201203_200807](https://user-images.githubusercontent.com/75344456/101216709-fc682f00-364d-11eb-973d-b00fec366934.png)

I would like to suggest an idea with this map. I feel instead of spawning in enemies every so often, perhaps let the player fight a wave of enemies and, after they kill all the enemies in that wave, they can proceed to the next section of the level. I think this will prevent extreme lagging. Another idea would be when the player completes an objective. For example, when the player repairs one of the generators near the mansion, spawn in some enemies.  I feel this might help with the pacing of the level, minimize lagging, and still make it fun - like in the end of C3M4.

Even though this level has its issues, it certainly has great potential. I like the direction of the level. The Resident Evil idea is awesome and I feel it can be better.


-Alando1

**Comment by AFADoomer** [comment]
@Alando1-doom - Can you post coordinates for the ropes that you were unable to climb in C3M0_A?  Also, would you mind checking to see if you have any compatibility options enabled, just in case that's somehow related?  

@Tormentor667 - Almost every wave component in C3M0_A is set up with a 4th parameter of zero - meaning that the spawners infinitely spawn a new enemy every time you kill one that came from that set of spawners, forever, until the wave is ended.  Especially in Zone 4, I think this causes problems, because after 20 minutes (wave 3) you will have a minimum of 210 zombies alive and active at once.  This *destroys* game performance, and killing them doesn't help, because more always spawn.  A better approach might be to make the 3rd parameter (number to keep alive at once) smaller - less than 10 - and to set the 4th parameter (max spawn amount) to the original 3rd parameter's larger number, so the end result of fighting through 210 enemies is the same, but you don't have huge swarms of zombies destroying your gameplay, and they eventually *will* stop spawning if you somehow survive.

**Comment by Tormentor667** [comment]
@Alando1-doom - Thanks kindly for all the feedback, I made various improvements and I hope the rest of the team can take care of what's left.

@AFADoomer - Good point, I didn't know that these are so resource hungry. I just found it kinda interesting to have this certain feeling of danger in the city, just as in Resident Evil 2. For something else, I just tried to change the spawners but something is going wrong. Arg1 and Arg2 of the Thing Spawners are "unused" and I can't work with them anymore. I have the latest version of UDB, maybe it's a BoA code issue. Can you take a look at this?

![2020-12-05_191447](https://user-images.githubusercontent.com/10298439/101260162-2bee6880-372e-11eb-8a89-66b36b161583.jpg)

**Comment by AFADoomer** [comment]
@Tormentor667 - It's not the spawner things themselves that you need to alter, it's the ACS script that sets up the wave components (around line 1055) that needs to be adjusted.

**Comment by Tormentor667** [comment]
@AFADoomer now I remember, these have been different spawners. Thanks for clearing up.

**Comment by Alando1-doom** [comment]
@AFADoomer  Thank you - I found the lantern :) In regards to the ropes, when I played through the level a second time, they worked. But I do have the coordinates for you:
![Rope1](https://user-images.githubusercontent.com/75344456/101267545-d020e100-3727-11eb-96b8-119e4897c8c6.png)
![Rope2](https://user-images.githubusercontent.com/75344456/101267547-d4e59500-3727-11eb-80fb-2b5e60e2903b.png)
![Rope3+4](https://user-images.githubusercontent.com/75344456/101267548-d8791c00-3727-11eb-9a41-5beb3dc863be.png)
![Rope5](https://user-images.githubusercontent.com/75344456/101267550-dca53980-3727-11eb-9190-d84e56515779.png)

@Tormentor667  I was able to get exact coordinates of those notes. Still couldn't screenshot the actual notes but I will provide what needs correcting. The coordinates are in the screenshots provided.
![Note1](https://user-images.githubusercontent.com/75344456/101267813-1d528200-372b-11eb-8723-155747f23e04.png)
![Note2](https://user-images.githubusercontent.com/75344456/101267803-0dd33900-372b-11eb-8f1c-f2bb6dc6fb9b.png)


- For the first note, AKA: PAPERTEXT04: "I investigated the house, but no sign of **live**, except for one of the undead..."
**"live"** should be **"life"**

- For the second note, AKA: PAPERTEXT05: "This excavation is haunted, Cpt. - I am not sure what has happened here, but all the tools, the machinery, the chaos - the Krauts seem to have **leaved** this place in a hurry,..."
**"leaved"** should be **"left"**

While I was playing through the second time, I did notice other issues (minor, though).

- The first issue is a texture out in the open within the farming area. Screenshot below:
![Screenshot_BoA_20201205_170741](https://user-images.githubusercontent.com/75344456/101267846-728e9380-372b-11eb-823e-4dda17a77733.png)

- The second issue is in regards to the plane that flies overhead. It can be seen in the distance just sitting there frozen. This is long after it had passed in the beginning of the map. I noticed it when I was near the mansion. Screenshots below:

![FrozenPlaneSkybox](https://user-images.githubusercontent.com/75344456/101267929-3445a400-372c-11eb-8a72-ed993bb5dab4.jpg)
![PlaneSkybox2](https://user-images.githubusercontent.com/75344456/101267933-39a2ee80-372c-11eb-8fe5-30282c168983.jpg)


- The last issue I found was one of the 3D snow-covered boulders. It wasn't solid and I was able to walk through it. Screenshot below:
![Screenshot_BoA_20201205_172053](https://user-images.githubusercontent.com/75344456/101267976-7cfd5d00-372c-11eb-901e-a61e3aa18b90.png)


Other than that, those are the only other issues I found. Still love the Resident Evil theme :)

-Alando1

**Comment by Tormentor667** [comment]
I guess we have fixed everything now that was found in Chapter 3 so far except the two points that I assigned in the first post.

**Comment by Tormentor667** [comment]
Perfect, so thanks to @Alando1-doom for all these valueable suggestions and I am glad that you did the beta testing for us. This has been very very useful! You have been already added to the list of beta testers as credit btw! Thank you so much!

**Comment by Alando1-doom** [comment]
Thank you, @Tormentor667 ! :) It has been my pleasure to help you and your team out. I enjoyed playing through the beta and I wish you guys the best of luck. If there is anything else you need me to look at or play test, by all means let me know. :)

Best Regards,

-Alando1
