### ISSUE TITLE
E2M2 Ladder

### ISSUE THREAD

**Issue by mzoeller** [Realm667/WolfenDoom#316]
Is the ladder supposed to be hard to find? I found it a bit strange that I could climb from the bottom but there was no climbing texture. 

![Screenshot_Doom_20201205_092131](https://user-images.githubusercontent.com/1606177/101240593-810b8980-36f0-11eb-9003-4b97b0556088.png)

Btw: Should I file these individual tickets or collect everything in one big post?

**Comment by Tormentor667** [comment]
Well, you don't necessarily have to use the ladder to climb up there, you can reach this area from a different access as well, it's just there or the lazy people :)

If you mean that the texture is "too short", simply imagine how you would do it: Get your hands on the lowest ladder part, pull yourself up and move on :)
