### ISSUE TITLE
C1M5 - restaurant enemy spawn bug

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#318]
On C1M5, when you first enter Hotel de la Mort, there is a restaurant to the left, and a living room to the right. If you enter the restaurant, and go to the back to grab some shotgun shells and bandages, enemies will spawn near the entrance.

![c1m5enemybug](https://user-images.githubusercontent.com/6550500/101867851-1fad4580-3b4a-11eb-8497-22383a622119.gif)

However, I don't remember that many spawning. Furthermore, even more enemies will spawn if you go to the back again and try to pick up something else from there, like a meal.

**Comment by Ozymandias81** [comment]
Ah that's indeed weird, maybe duplicate spawspots? I remember reducing some of them, but it seems map has been edit after and something has been changed... Later I will look onto that, maybe it is better if enemies are spawn in front of reception entrance though
