### ISSUE TITLE
'Make colormap' shows in Titlemap at start

### ISSUE THREAD

**Issue by madame-rachelle** [Realm667/WolfenDoom#320]
I'm guessing this is a debug message that was meant to remind someone to make a colormap. Which I doubt is even useful at this point since the entire project seems to depend on true-color rendering.

**Comment by Tormentor667** [comment]
Absolutely right, but were is it produced?

**Comment by Ozymandias81** [comment]
Afaik it is something generated by GZDoom per default with IWADs which doesn't have colormaps, am I right?

**Comment by madame-rachelle** [comment]
Right you are @Ozymandias81 - the line is being generated here: https://github.com/coelckers/gzdoom/blob/b2289528c6fb90d54fcb386347adbd4b6567fbad/src/rendering/swrenderer/r_swcolormaps.cpp#L357 - I didn't realize it before I made this post, sorry about that.

So I fixed it here: https://github.com/Realm667/WolfenDoom/commit/826ddb430a75004dd17460a17a50d2c11dfa792f
