### ISSUE TITLE
Crosshair becomes inaccurate after resetting tilt

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#321]
Before:
![tiltbefore](https://user-images.githubusercontent.com/6550500/102743016-7245e900-4324-11eb-8c84-f398352cd4cd.gif)
[Video (mp4)](http://www.ciinet.org/kevin/myimages2/doom/wolf_boa/tiltbefore.mp4)
After:
![tiltafter](https://user-images.githubusercontent.com/6550500/102743025-770a9d00-4324-11eb-94a6-681704be3fd8.gif)
[Video (mp4)](http://www.ciinet.org/kevin/myimages2/doom/wolf_boa/tiltafter.mp4)

**Comment by Talon1024** [comment]
I just noticed it only seems to be an issue with negative angles, or angles above 180.

**Comment by Ozymandias81** [comment]
Guess there is something we should change from playertracer

https://github.com/Realm667/WolfenDoom/blob/eaa4eabc95518c505c11242ba0680e17daca1dac/scripts/actors/tracers.txt#L526

**Comment by Talon1024** [comment]
That happens regardless of the roll and pitch settings. BTW, [here's the map](http://www.ciinet.org/kevin/myimages2/doom/wolf_boa/test_tlt.wad) I made for testing this.

**Comment by Talon1024** [comment]
I just found that this bug also affects projectiles "summoned" with the summon CCMD, including rockets, so this bug may be a GZDoom bug.

**Comment by Talon1024** [comment]
I just found out that "pukename settilt 15 1" will cause this bug.

**Comment by Talon1024** [comment]
UPDATE: I just found out that disabling the A_SetSize calls [here](https://github.com/Realm667/WolfenDoom/blob/e112c177a0b0a857708dd00e33eb67946cc313d1/scripts/actors/player.txt#L890) and [here](https://github.com/Realm667/WolfenDoom/blob/e112c177a0b0a857708dd00e33eb67946cc313d1/scripts/actors/player.txt#L898) fixes this bug. It seems like the height and radius are not being reset for some reason, although I don't know why @AFADoomer (IIRC) decided to do that in the first place...
