### ISSUE TITLE
Skybox in First mission

### ISSUE THREAD

**Issue by staredcraft-prime** [Realm667/WolfenDoom#323]
Hey guys first of all I'm new to Beta Testing this game, so if anyone else has pointed this out before I apologize for bringing this up. However the skybox during the first mission of the first episode is kinda wonky. I can see the edges of the box as black lines and it kinda takes away from the illusion. I don't know if this is intentional, or if this is a limitation of GZDoom, but I thought I'd point it out. I don't recall seeing this during the release build of Episode 2 (but it's been a while since I played that)

![image](https://user-images.githubusercontent.com/76535538/103032331-c839ad00-452d-11eb-969f-0319387a28cc.png)

**Comment by AFADoomer** [comment]
We probably should make gl_ssao defaul to one in DEFCVARS...  Unless someone can figure out a way for the ambient occlusion to not affect skyboxes.

**Comment by Tormentor667** [comment]
I adressed this already over a year ago, no idea what's the current status on this, so I agree with your suggestion, @AFADoomer 
Link: https://forum.zdoom.org/viewtopic.php?f=57&t=65561&p=1129280&hilit=skybox+ambient+occlusion#p1114236

**Comment by staredcraft-prime** [comment]
> 
> 
> I adressed this already over a year ago, no idea what's the current status on this, so I agree with your suggestion, @AFADoomer
> Link: https://forum.zdoom.org/viewtopic.php?f=57&t=65561&p=1129280&hilit=skybox+ambient+occlusion#p1114236

Ah okay, I should look through that thread first next time

**Comment by DoomJedi** [comment]
Yes, old issue, even I mentioned it before myself. Thought it was long taken care of.

**Comment by Tormentor667** [comment]
Well, it is not so I think @AFADoomer 's suggestion is the right way to go. I will comment on the ZDoom thread anyway.

**Comment by Tormentor667** [comment]
> We probably should make gl_ssao default to zero in DEFCVARS... Unless someone can figure out a way for the ambient occlusion to not affect skybox sectors.

After discussing it in the thread over at ZDo now for a while, there must likely won’t be a solution from the developers in a short time.

I’d suggest setting it to 1 that it affects at least the regular areas. Portals won’t be perfectly seamless but I mostly didn’t notice the “change” so I think it’s okay. 

Can someone adjust the cvar?

**Comment by Talon1024** [comment]
This GZDoom commit may be relevant: https://github.com/coelckers/gzdoom/commit/df4f41f4e8d9b1d0372b6e814bb1a0c091a59f23

**Comment by Tormentor667** [comment]
Oh yes, finally!
