### ISSUE TITLE
Missing "Dialogue" sounds when using boa.ikp3 as IWAD

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#324]
I noticed, that when using BOA.IPK3 as IWAD (and not based on DOOM2.WAD), the sounds are missing when talking to an npc. This refers to the sound, when you choose your option (up and down) and when you select it (enter). What sounds are used here? Which ones do we need to copy from DOOM2.WAD? I guess they are simply missing in BOA.IKP3.

*EDIT*
After checking it, I guess the sounds are there but some definitions, that are present in the DOOM2 SNDINFO aren't in the BOA SNDINFO covered, just an idea, maybe @AFADoomer you can check the dialogue code for something that is using the DOOM2 SNDINFO definitions from this: https://github.com/rheit/zdoom/blob/master/wadsrc/static/filter/game-doomchex/sndinfo.txt

**Comment by Talon1024** [comment]
Speaking of which, Nemesis uses the Revenant's melee sounds from Doom 2. We should replace those before we release.

**Comment by Tormentor667** [comment]
Just took care of the Nemesis punch sound in 5faf7576b345966cc9a5a5fb5ed31747db002547

**Comment by AFADoomer** [comment]
I don't know what's going on.  All of the menu/* sounds are redefined in the BoA SNDINFO.  Will have to dig through the code.

**Comment by Tormentor667** [comment]
Just checked it, you are right and all the sounds are there, though not working in the dialogie menue.

**Comment by MuadDib90** [comment]
Found one issue regarding running the game as ".ipk3" instead as standard mod ".pk3".
when trying to end the game using "exit game" in main menu, the "randomized dialogs" are not appearing, instead there is (as I suppose) standard GZDoom line:
<details>
      <summary>.ipk3</summary>

![ipk3](https://user-images.githubusercontent.com/73436978/103172103-4f9a5f80-4851-11eb-9b55-a681581a7ca8.PNG)

</details>
<details>
      <summary>.pk3</summary>

![pk3](https://user-images.githubusercontent.com/73436978/103172106-5cb74e80-4851-11eb-95df-c28a7db43d4b.PNG)

</details>

**Comment by Blue-Shadow** [comment]
From what I can see, BoA relies on the presence of Doom's quit messages and replaces them via LANGUAGE, as opposed to defining its own via [MAPINFO](https://zdoom.org/wiki/MAPINFO/GameInfo_definition#QuitMessages).

**Comment by Tormentor667** [comment]
@Blue-Shadow how can that be fixed if we don't want to use DOOM as IWAD? Are there other dependencies btw?

**Comment by Talon1024** [comment]
Regarding Strife conversations, you have to define a "ChatSound" under the gameinfo section in mapinfo.txt.
IIRC, quit messages are also defined under the gameinfo section in mapinfo.txt.

**Comment by Tormentor667** [comment]
The sound when starting a conversation is working again, but there is no sound when switching through the possibilities of answers. I am not sure if there was one before but it feels like a little "movement" sound is missing here.

**Comment by Ozymandias81** [comment]
And testing via UDBuilder doesn't show custom exit messages, but just QUITMSG lines sadly.

**Comment by Tormentor667** [comment]
> And testing via UDBuilder doesn't show custom exit messages, but just QUITMSG lines sadly.

That’s because of a UDBuilder isn’t turning this into a ipk3. All fine, if it works standalone we can leave it as is.

The only thing left is the cursor movement sound that is missing when clicking through the options in the dialogue answers. I am almost certain there was a sound before :) @Talon1024 or am I missing something?

**Comment by MuadDib90** [comment]
> 
> 
> From what I can see, BoA relies on the presence of Doom's quit messages and replaces them via LANGUAGE, as opposed to defining its own via [MAPINFO](https://zdoom.org/wiki/MAPINFO/GameInfo_definition#QuitMessages).

Now it is showing this:
<details>
      <summary>Screenshot</summary>

![Výstřižek](https://user-images.githubusercontent.com/73436978/103208104-21278d80-4900-11eb-83f3-1729668e9716.PNG)

</details>

**Comment by AFADoomer** [comment]
Back to the original issue stated here:

There were never any sounds played when moving the cursor inside of conversations.  Just checked in Strife, even, and there are no sounds.  I've added one in be2c17fa0d66085a221a3d47d743025507237bed, but the normal menu cursor movement sound (bullet fire) doesn't seem appropriate, so I added a more subdued placeholder.

**Comment by Tormentor667** [comment]
My memory fooled me here obviously. Anyway, it's an improvement and it sounds and feels right now. Thanks for sorting this @AFADoomer.

> > From what I can see, BoA relies on the presence of Doom's quit messages and replaces them via LANGUAGE, as opposed to defining its own via [MAPINFO](https://zdoom.org/wiki/MAPINFO/GameInfo_definition#QuitMessages).

This has been fixed by @Talon1024 today, so the whole issue can be closed now.
