### ISSUE TITLE
Operation Paris issue

### ISSUE THREAD

**Issue by armymen12002003** [Realm667/WolfenDoom#326]
![Screenshot_BoA_20201229_230231](https://user-images.githubusercontent.com/76763736/103329837-aa3be300-4a2c-11eb-949f-d3069c0a5cdb.png)

There is a door that seems to be stuck only way of getting through is no clipping.

**Comment by Tormentor667** [comment]
Can you share coordinates?

**Comment by DoomJedi** [comment]
I am testing by chance Paris map as well, and didn't met any stuck door so far. Maps looks solid.
And I'm already at the bank.

**Comment by Ozymandias81** [comment]
Sadly I think I know what happened, an half-dead soldier is behind that door and it stopped the polyobj... Idk how to fix it, surely it is a GZDoom limit but I may be wrong. On the other hand, please do not play BoA with external mods, that "new active enemies" shouldn't belong to BoA (unless there are some developer things that I am not aware). Which gzdoom build did you use @armymen12002003 ?

**Comment by armymen12002003** [comment]
> Sadly I think I know what happened, an half-dead soldier is behind that door and it stopped the polyobj... Idk how to fix it, surely it is a GZDoom limit but I may be wrong. On the other hand, please do not play BoA with external mods, that "new active enemies" shouldn't belong to BoA (unless there are some developer things that I am not aware). Which gzdoom build did you use @armymen12002003 ?

The one that tormentor supplied. and i was using the auto auto save external mod with it,

**Comment by Tormentor667** [comment]
That’s from yesterday - all fine actually

**Comment by Talon1024** [comment]
Judging by the textures, I'm guessing it's the door near 224, -632, -256. A half-dead guard may be blocking the door, but half-dead guards should be "pushable" now, and the issues with that door getting stuck on things beneath should have been fixed a long time ago.

**Comment by Talon1024** [comment]
I just played through C1M5 recently, and I can confirm this issue. I have no idea what's causing it, but maybe it has something to do with the blocking flags set on the door?

**Comment by Tormentor667** [comment]
Most propably something is blocking it - wether it is a structural part or an actor. Do you have the coordinates?
