### ISSUE TITLE
Key binding for "Objectives" missing

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#328]
I noticed there is no more option to bind a key to the Blade of Agony objectives display ingame. Or am I simply missing something? I couldn't fint it in the key customization menue.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 For me it's in the very first line of it (though I am still playing with doom2.wad, standalone behaviour could be different).
![image](https://user-images.githubusercontent.com/59409713/103440323-8ad3ce80-4c55-11eb-9d27-d46476f17c41.png)

**Comment by Ozymandias81** [comment]
It works with PWAD and IWAD, tested on 1st january 2021 build

PWAD...
![image](https://user-images.githubusercontent.com/11136108/103441487-a8ea0080-4c4e-11eb-9f56-a57175646d18.png)
... and IWAD
![image](https://user-images.githubusercontent.com/11136108/103441524-ec446f00-4c4e-11eb-88e5-24180b948bb7.png)

**Comment by AFADoomer** [comment]
The option is there for me as well.

That said...  Some of the changes to the menu are kind of redundant now that the engine's built-in simplified menu is available.  Should the menu changes be re-examined in light of that addition?

**Comment by Tormentor667** [comment]
Sorry guys, I was completely blind, my fault! 

> The option is there for me as well.
> 
> That said... Some of the changes to the menu are kind of redundant now that the engine's built-in simplified menu is available. Should the menu changes be re-examined in light of that addition?

And yes I do agree here.

**Comment by Tormentor667** [comment]
Closer the issue, a new one should be opened regarding the menu revamp.
 @AFADoomer
