### ISSUE TITLE
VM abort at the end of C3M0_B

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#331]
I just did a quick test of C3M0_B, and at the end of the level, I got a VM abort.

    INTERMAP - Allied Headquarters

    VM execution aborted: tried to read from address zero.
    Called from InventoryHolder.RestoreInventory at /home/kevinc/misc/WolfenDoom/:scripts/actors/items/powerups.txt
    Called from RyanToken.OnDestroy at /home/kevinc/misc/WolfenDoom/:scripts/actors/items/powerups.txt, line 798
    Called from DisguiseToken.Tick at /home/kevinc/misc/WolfenDoom/:scripts/actors/items/powerups.txt, line 623
    Called from Object.Destroy [Native]

This is confusing, since RyanToken is supposed to be removed at the end of C3M0_B in the ENDING_SEQUENCE script. It shouldn't transfer over to INTERMAP at all.

**Comment by Talon1024** [comment]
It looks like the culprit was Z_ShadeMe, since it destroys itself every second.

**Comment by Tormentor667** [comment]
I didn't get a VM abort, tried it two times in a row, one time with a regular playthrough, the other time by cheating the scripts (pukename PREPARE_END and pukename ENDING..)

**Comment by Talon1024** [comment]
Apparently, some people are still experiencing this issue.

**Comment by Talon1024** [comment]
If you experienced this issue on C3M0_B, please try to play C3M0_B from the start again, and enter "developer 1" into the console. That should tell you which item cannot be restored.

**Comment by Username-N00b-is-not-available** [comment]
Just for the record, I haven't experienced the problem in the past month. Also checked it now, everything works correctly.

**Comment by Tormentor667** [comment]
Same here, I could completely play it, so I consider this fixed.
