### ISSUE TITLE
Color grading shader problem on certain hardware

### ISSUE THREAD

**Issue by AFADoomer** [Realm667/WolfenDoom#332]
In OpenGL renderer (but not in Vulkan), the color grading shader leaves weird red artifacts around some pixel boundaries when I play with my GeForce GTX 1050 Ti card (with most recent drivers).  Disabling the shader or switching to onboard graphics restores normal rendering.  

![Screenshot_BoA_20210101_123145](https://user-images.githubusercontent.com/16618820/103444380-711e9100-4c2d-11eb-997c-85f75db62620.png)

I've tested this with Verdant Citadel, which I think is the origin of the shader, and the same problem happens there; Not sure if this is something that can be fixed (I've certainly had no luck), but wanted to at least post this here for tracking.

**Comment by Tormentor667** [comment]
That’s strange... as far as I know, the TITLEMAP isn’t using the shader at all.

**Comment by Talon1024** [comment]
Unfortunately, I cannot reproduce this issue with OpenGL or Vulkan. I'm using an NVidia GeForce GTX 970, with the 450.80.02 drivers for Linux (from the Ubuntu graphics-drivers PPA).

**Comment by AFADoomer** [comment]
I've tried all variations of texture options.  The red lines are less prevalent on Linear/Bilinear/Trilinear than on the None variants.  And the red lines disappear under full brightness (i.e., 'give powerlightamp').

I thought this might be a sampling error with the lut texture, and clamping the cell_l value to above 1.0 makes the lines pretty much disappear, but I can't figure out what the real problem is (or why Vulkan works fine).

**Comment by Talon1024** [comment]
Vulkan works fine because GZDoom integrates glslangValidator, which, despite the name, compiles GLSL code to SPIR-V. Vulkan uses SPIR-V as the format for shaders.

**Comment by AFADoomer** [comment]
On:
![Screenshot_Doom_20210105_103355](https://user-images.githubusercontent.com/16618820/103678825-ac7cd080-4f49-11eb-95af-a66b64b06d91.png)
Off:
![Screenshot_Doom_20210105_103602](https://user-images.githubusercontent.com/16618820/103678821-ab4ba380-4f49-11eb-973c-0b1e1185449c.png)

The artifacts are evident in every part of every map...

**Comment by Tormentor667** [comment]
I noticed there are even green artifacts in the lantern light.

**Comment by Tormentor667** [comment]
I tried it today as well, OpenGL with a Radeon RX 580 with the latest drivers doesn't get me these artefacts, just for the record.

**Comment by Ozymandias81** [comment]
Later I would try to test myself too since I have a 1030 after my recent improvements to my pc, with latest Nvidia drivers as well. How to test it properly @AFADoomer ?

**Comment by AFADoomer** [comment]
Yeah, this looks like it may be hardware specific.

**Comment by Ozymandias81** [comment]
So any news regarding this issue? I would like to know how to exactly reproduce this, since I have also updated my drivers some days ago and we share Nvidia ones.

**Comment by Tormentor667** [comment]
It depends on @AFADoomer, did you have the chance to update your graphics drivers lately?

**Comment by AFADoomer** [comment]
They were the latest when I last tested.  Will check when I get home tonight.

There's really nothing to be done to reproduce this, just load the game.  Same results with a fresh config and minimal .pk3 file that is nothing but the shader-specific files.

I'm mostly worried about pushing the mod out without any way of knowing who will be affected.  Worst case, maybe color shading can be disabled if not on Vulkan renderer?  Seems almost too much for something that may only affect a few players.

**Comment by Ozymandias81** [comment]
I guess we should see if the problem gets better in future releases of GZDoom, really don't know what could be the cause, probably something related to how shader treats colors but I am prety dumb when it comes shaders.

**Comment by Tormentor667** [comment]
> I'm mostly worried about pushing the mod out without any way of knowing who will be affected. Worst case, maybe color shading can be disabled if not on Vulkan renderer? Seems almost too much for something that may only affect a few players.

Same here, but it is still extremely strange. I gave the beta to about 10 friends of mine with the color grading being active by default and none of them suffered this. I'd at least suggest you post the issue to the ZDoom forums and ask for feedback there.

**Comment by Tormentor667** [comment]
Getting back to this: I tried the latest mod on 6 different PCs at my office and never got any of the artficacts. This doesn’t help either I know - did you post the issue yet to the ZDooms?

**Comment by Tormentor667** [comment]
So after all the current beta testers didn't encounter that problem, I'd simply leave this issue as a very special case. When the final beta testing will start, we can reopen that issue if there are serious complaints but for now, it seems to only occure in a very very special case.

**Comment by AFADoomer** [comment]
For posterity:  This seems to have been fixed for me with one of the last few Nvidia driver updates.
