### ISSUE TITLE
Surrendering sprites for Medics

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#334]
When they are standing, they take a lot of attention. I'd suggest making the surrendering medics crouch instead of standing. What do others think regarding this?

**Comment by MuadDib90** [comment]
For me, what actualy takes the attention, is the constant waving with his hands. (Through I understand, why it was implemented.)
How about him crouchinng with hands behind his head? With no movement.

**Comment by Tormentor667** [comment]
Yes, I think that might work better indeed.

**Comment by DoomJedi** [comment]
I think both ideas are very unrealistic, those are not surrender poses - but arrested poses. While player does nothing to cause any of it.
We can just make hand wave frequency much rarer. And maybe make them disappear by faster conditions.

**Comment by Ozymandias81** [comment]
I think I am with DJ, less frequent arms waves and make "surrendering" soldiers disappear faster. You know I have already told you that if it was for me, surrender feature should have not been included but well

**Comment by AFADoomer** [comment]
I'll adjust the timing for the surrender animation.  They were originally just stopping on a single frame, but I changed them to to match the standard surrender animation. 

I would have liked to have a couple of crouched/scared sprites, similar to the frightened prisoner crouching, so that they would look different from standard surrendering enemies.

**Comment by Tormentor667** [comment]
I support that crouching variant as well @DoomJedi @AFADoomer

**Comment by DoomJedi** [comment]
I"ll try to help you out.
At least prisoner-type crouching is more logical than arrested poses :)

**Comment by DoomJedi** [comment]
Virg will probably commit the new frames soon.
Do we need those more advanced "shootout/kneeing animations for more enemies, like doctors?

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi If you mean the PlagueDocs, as well as scientists and mechanics, I'd say 'no', as these are just workers who have not undergone extensive military training, and if they want to show that they are harmless to the player, they will do that in a way that's obvious to them.

**Comment by AFADoomer** [comment]
I just updated the code for the medic surrender in commit 98e1c164612765933e1b89183ba2347ac6f81db8.

**Comment by Ozymandias81** [comment]
Guess this is done then.
