### ISSUE TITLE
Some actors inheriting CullActorBase fades out immediately

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#335]
As the title says, actors which have CullActorBase as inherit class fade out immediately. This has been noticed mostly over flora related actors by DoomJuan, beside Grass ones. You can check it immediately from Intermap, flowers aren't there anymore. I tried comment out CullActorBase from Flower1 and they do show up, but idk what I should do then to fix CullActor class (which also seems to make disappear some models too). Any clues @AFADoomer ?

**Comment by AFADoomer** [comment]
This should be fixed as of bd4c57f226f8e0a44581a827fa7b60480380dd06.

**Comment by Ozymandias81** [comment]
Looks like they are yes, thanks a bumch AFA. Btw noticed another different issue, well this is present since some months ago: set your rendering distance for models and such at mmh let's say 2048, load C3M6_A and then see trees falling down through mountains as soon they gets visible on screen. Since those are randomspawners I guess that's also why we have those issues, but is there by any chance some way to fix that? This seems to happen rarely and only if the variable is set below default value at the very start

**Comment by AFADoomer** [comment]
OK, that should be fixed now as of 39fe9cd7e3a8ae4978bcdf97065afbd5141d2089.  Plus some other fixes for actors not fading in cleanly.
