### ISSUE TITLE
Talking sharks? (LOL)

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#336]
Just listen to this:

https://user-images.githubusercontent.com/6550500/104402603-a88e1700-5524-11eb-99cf-b0f9aa4b744c.mp4

**Comment by AFADoomer** [comment]
I think this will be fixed once @Ozymandias81 gets a chance to sort out the new boss sounds...  Sharks' "shark/active" sound is mapped to ROAMING, which happens to be a file name that was used in the 'as-is' sound file names that @Tormentor667 uploaded in ac87848e9a8f657c75ab1571f9353c1175554464.

**Comment by Ozymandias81** [comment]
Yes I am at it ahaha

**Comment by Tormentor667** [comment]
Awesome, I like it, can we keep it? [/nonsense]
