### ISSUE TITLE
Endless scrolling in help screens

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#338]
Noticed in the help screen, that if I wait for a while, the text scroller begins because of texts which are too long, but they scroll upwards forever and display the same text over and over again. Texted with latest version, german language:

![2021-01-23_174348](https://user-images.githubusercontent.com/10298439/105608171-aa689d80-5da2-11eb-965a-95e325ae02c2.jpg)

Noticed also that these texts aren't scrolling at all if they are too long:

![2021-01-23_175617](https://user-images.githubusercontent.com/10298439/105608630-58c11280-5da4-11eb-821e-49ec85ffc05d.jpg)

**Comment by AFADoomer** [comment]
So don't make the texts too long?  👼

**Comment by Tormentor667** [comment]
I thought, they were automatically scrolling if they are too long? Maybe I am missing something :)

**Comment by AFADoomer** [comment]
They are, but I don't think I ever finished fully implemented that, because I didn't like the way it looked.  The "scroll once and stop" logic is commented out, and I'll need to check the other boxes to see why they aren't scrolling at all.

**Comment by AFADoomer** [comment]
OK what is the desired behavior here?  Scroll just to the bottom, then stop?  Right now it's set up for scrolling in an endless loop.

**Comment by Tormentor667** [comment]
What do you think of scrolling to the bottom, wait, fade away, display again from top and scroll to the bottom (loop)? Just an idea

**Comment by AFADoomer** [comment]
The problem is that in most cases there are only a few words that run over and make the text scroll up a single line, which looks bad.

**Comment by Tormentor667** [comment]
That’s true. Well, you could still add that feature and the translators could shorten the text of it which are only 1-2 words too long, what do you think? 

Or maybe you have a different solution?

**Comment by AFADoomer** [comment]
My preference for this would be for the strings to be made shorter, and the automatic scrolling to be removed. The user experience should be the same in all languages.

**Comment by Tormentor667** [comment]
Well, I can take care of that for the english and german strings - with some dirty work I should be able to shorten that. For the other languages we need to point the translators towards that. 

@MuadDib90 - Would you be so kind and add some kind of explanation towards the max length of the Info texts to the Google Spreadsheet?

**Comment by Tormentor667** [comment]
Fixed german texts, made them all shorter, should work without scrollin now.

**Comment by Tormentor667** [comment]
Added a small hint for the translations, I think this is done for now.

![2021-02-07_092608](https://user-images.githubusercontent.com/10298439/107141049-8ec6d080-6926-11eb-9b2d-5f60683b18d4.jpg)
