### ISSUE TITLE
Forever.exe's Playtest

### ISSUE THREAD

**Issue by ForeverExe** [Realm667/WolfenDoom#340]
- C3M1: Killing Mengele does not update the objectives box

**Comment by Tormentor667** [comment]
Which version did you use to play?

**Comment by MuadDib90** [comment]
>     * C3M1: Killing Mengele does not update the objectives box

Yes, it does not. The first and second time you encounter him in C3M1. Because he "run away". But the third (also the last) time you encounter him and kill him, the box is checked.

(I am not sure, but I would say that message box at the top - from Ascher - says, Mengele "run away" the first time you kill him, suggesting though he is not dead yet.)

**Comment by Tormentor667** [comment]
Exactly @MuadDib90, thanks for the explanation. I think we can close that issue here.

**Comment by ForeverExe** [comment]
1- Operation: Geheimnistrager, if you kill the guard in the tower before picking up the radio at the other side of the camp, it's not possible to continue and the level needs to be played again.
2- After finishing Ryan's level, it sends me to the main menu instead of the HQ. I don't know if it is intentional, but I didn't knew about it so I'm playing chapter 3 all over again.

Sorry to re-open the issue but I don't know if there are other proper places to report this.

**Comment by Talon1024** [comment]
> 2- After finishing Ryan's level, it sends me to the main menu instead of the HQ. I don't know if it is intentional, but I didn't knew about it so I'm playing chapter 3 all over again.

I assume by "main menu" you mean the title screen, and not the menu that pops up when you hit "Esc". I have absolutely no idea what could cause that, other than a modified MAPINFO.

**Comment by ForeverExe** [comment]
> I assume by "main menu" you mean the title screen, and not the menu that pops up when you hit "Esc". I have absolutely no idea what could cause that, other than a modified MAPINFO.

I remember when I've played the map that I've used the "idfa" cheat and godmode for the whole level, then at the end the console showed up displaying what I think are some kind of errors, I'll replay the level in the same conditions and then I'll post some screenshots.

Is there a way that i can use to change levels? "idclev" works?

**Comment by Username-N00b-is-not-available** [comment]
@ForeverExe Screenshots will definitely help here, we need to see the exact error messages. By the way, screenshots from the main menu do not get saved automatically, you'll have to e. g. paste the image into Paint.
>Is there a way that i can use to change levels? "idclev" works?

'map CxMx_x' in the console works, but please do not use it now, since AFAIK C3M0_B ended normally when warped into by a cheat, and now you are experiencing this issue. If you have savegames from before C3M0_B, please load them instead.

**Comment by ForeverExe** [comment]
Sorry for the wait but I'm having heavy issues with the game:
About 2 days ago i thought to update my local folder with the BoA repo, but:
- Most of the models are broken
- The shader on the screen in the briefing room is absent
- Even with the lowest preset, the game is stuck at 6/7 fps
I've attached some screenshots https://drive.google.com/drive/folders/11j9gJdH2D9OgGWsR3MYtwqrU7zlVs6I3?usp=sharing

**Comment by Username-N00b-is-not-available** [comment]
@ForeverExe That's some serious sh...tuff going on with your models, the tank especially. I have no such problems even with potato mode. Maybe some data in the folder got corrupted?
Did you use a git client like GitHub Desktop to clone the BoA repository, or just downloaded it from the website? If the former, you can try repairing your BoA folder by reverting the changes that were supposedly done on your machine recently.

**Comment by ForeverExe** [comment]
> @ForeverExe That's some serious sh...tuff going on with your models, the tank especially. I have no such problems even with potato mode. Maybe some data in the folder got corrupted?
> Did you use a git client like GitHub Desktop to clone the BoA repository, or just downloaded it from the website? If the former, you can try repairing your BoA folder by reverting the changes that were supposedly done on your machine recently.

I use Git Bash to clone the repository, maybe i just need to re-download it.

**Comment by Username-N00b-is-not-available** [comment]
@ForeverExe Rather than redownload the full 7.5GB, you can try ```checkout```ing the most recent commit.
Have you tried launching other mods with lots of shaders/3D models on your GZDoom, by the way?

**Comment by Talon1024** [comment]
You should open Git Bash, "cd" to your WolfenDoom repo directory, and type in "git status" - that will tell you if the data is intact or not.
If it tells you a whole bunch of files have been modified, and you know you didn't make those changes yourself, you can type "git reset --hard" to get rid of those changes.

**Comment by ForeverExe** [comment]
@Talon1024 @Username-N00b-is-not-available thanks for your time, I've discovered the problem:

By probably a missclick of mine, GZDoom was running using the **SoftPoly engine**. 

I'm feeling very stupid 😞

**Comment by ForeverExe** [comment]
Ok, back to the original issue: I get this when i end Ryan's mission https://imgur.com/a/rg7GEml

**Comment by Talon1024** [comment]
Can you please enter "developer 1" into the console and do that again? That should show you which items are being "restored"

**Comment by ForeverExe** [comment]
> Can you please enter "developer 1" into the console and do that again? That should show you which items are being "restored", if your BoA ipk3 is sufficiently up to date.

That will require some days, give me some time to replay the chapter until that point... because with the "map CxMy" command gives me problems (yes, I made a save before the mission but it ended being overwritten).

**Comment by Talon1024** [comment]
Before you do, please update your BoA ipk3. You can use build.bat, or click on the green "Code" button, and click on "Download ZIP".

**Comment by ForeverExe** [comment]
I've played Ryan's mission again with the updated repo, with the "map" command. After being captured and the final text shows up, It starts the chapter 1's introductive cutscene and then it seems to load again the mission, but it stays with a black screen like it's freezed, and I can't do nothing but go through the main menu.

I played it adding "developer 1" in the console, but it showed nothing.

**Comment by Talon1024** [comment]
That's actually to be expected. After finishing Ryan's mission (C3M0_B), the player enters INTERMAP (Allied HQ) in Ryan's room.

If you aren't playing Chapter 3 on a normal playthrough, the cutscene with the newspapers will play, and you will start on mission 1, since the game doesn't have information on any previous visit to INTERMAP, and the `map` CCMD starts a new game with a "pistol start".

And if you press "use", you'll play Ryan's mission again, since you're standing right in front of a line which will start that mission if you press "use" on it.

**Comment by ForeverExe** [comment]
> 
> 
> That's actually to be expected. After finishing Ryan's mission (C3M0_B), the player enters INTERMAP (Allied HQ) in Ryan's room.
> 
> If you aren't playing Chapter 3 on a normal playthrough, the cutscene with the newspapers will play, and you will start on mission 1, since the game doesn't have information on any previous visit to INTERMAP, and the `map` CCMD starts a new game with a "pistol start".
> 
> And if you press "use", you'll play Ryan's mission again, since you're standing right in front of a line which will start that mission if you press "use" on it. However, this shouldn't happen on a normal playthrough, since that line special isn't repeatable.

Now I understand better, thanks. 
By the way, knowing the behaviour of the level with 'map' and everything, since I've updated my ipk3 I haven't seen any console errors at the end of the mission, so we can consider this issue solved for now?

**Comment by Talon1024** [comment]
Hopefully.

On the other hand, I remember a while back that `Z_ShadeMe` and cursed souls caused VM abort errors.
