### ISSUE TITLE
Camera textures only working after changing texture filtering

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#341]
I noticed that when I play Blade of Agony, the camera textures on small screens are not working...
![Screenshot_BoA_20210125_190550](https://user-images.githubusercontent.com/10298439/105747036-83e06900-5f40-11eb-8d4b-6782eea52c0a.png)
...until I simply change the texture filtering in the options menue - doesn't depend on which setting, just changing it and even changing it back makes it work.
![Screenshot_BoA_20210125_190618](https://user-images.githubusercontent.com/10298439/105747070-9490df00-5f40-11eb-9ddb-d237e3e8313c.png)
No idea if that's a GZDoom bug or a BoA-specific issue.

**Comment by MuadDib90** [comment]
Huh?
I do not occur to me.
But I am not playing with "texture filtering" though. All set from the GZDoom download and first starting.
When did it happen to you? Lately? When you changed something?

**Comment by Tormentor667** [comment]
Already for a while actually, but I didn’t try that on a clean installation but on my GZDoom standard installation and playing boa as ipk3

**Comment by Ozymandias81** [comment]
This actually happened on past builds of GZDoom, so I suggest to test it with recent builds

https://forum.zdoom.org/viewtopic.php?f=7&t=69106

**Comment by Tormentor667** [comment]
Tried it after updating, actually it's a different bug. I tried it with our standalone build and it works, so I guess something is wrong with my development folder - all fine :)
