### ISSUE TITLE
Timeperiod tractor

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#342]
The tractor used in the game looks like an International Harvest 1486 (could be wrong here), which was made 1976 - 1981, but definitely not in the 1940's. Maybe someone could replace this one for a timeperiod correct one ?

**Comment by Ozymandias81** [comment]
Can you be so kind to post a screenshot of the actor itself?

**Comment by x3003** [comment]
![Screenshot_Doom_20210126_000645](https://user-images.githubusercontent.com/77861029/105777524-d0d93500-5f6a-11eb-9a22-97c90f3e7884.png)
![Screenshot_Doom_20210126_000655](https://user-images.githubusercontent.com/77861029/105777581-ecdcd680-5f6a-11eb-8215-310e8dea5597.png)

**Comment by Talon1024** [comment]
Well, the game also features [GE M134 miniguns](https://forum.zdoom.org/viewtopic.php?f=19&t=47801&start=2565#p1092411) as the usable machinegun turrets. AFAIK we generally don't care so much about being historically accurate, as long as it's not too out of place.

**Comment by Ozymandias81** [comment]
Yes we can live with it perfectly, that truck is too cool to now with us too :smile:
