### ISSUE TITLE
Some text wrong ?

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#343]
Think some text on walls in C3 maps said 'nicht rauchen' or so. I don't think they (N***s) would ever put that so. More like 'rauchen verboten' or 'rauchvorbot', like in some other maps.

**Comment by Ozymandias81** [comment]
Please be more specific, we need screenshots or at least consistent clues.

**Comment by x3003** [comment]
Can't remember where exactly. Need some more playing.

**Comment by x3003** [comment]
One of them is sign_w53. It says 'kein rauchen', which just sounds odd.
'Rauchverbot' should be better here, I think.

![SIGN_W53](https://user-images.githubusercontent.com/77861029/105780240-501d3780-5f70-11eb-85c9-b0447dbbad20.png)

**Comment by Username-N00b-is-not-available** [comment]
For reference: SIGN_035 is 'Rauchen verboten', and there is also SIGN_W52 with 'Benzinspeicher // kein Rauchen!'
What do you think @Tormentor667?

**Comment by Tormentor667** [comment]
Fixed in 1c10b7844138f7c5f6ce3ac3e82b5feef5e11000
