### ISSUE TITLE
Crash in C3M2 when activate map under vulkan.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#344]
On 1 spot (or maybe 2) in C3M2 there's a crash when activate the map. This only happens w/ Vulkan and works fine w/ opengl or softpoly.

![Screenshot_Doom_20210126_122205](https://user-images.githubusercontent.com/77861029/105839898-6a87fd00-5fd2-11eb-83e7-9581f767a841.png)

**Comment by Ozymandias81** [comment]
Do you have an Nvidia gpu or Amd? We need more info about, does gzdoom exit asking for a crash dump or just quits? Which are your pc specs too and under which resolution you was playing though? Most important too, which version of gzdoom exactly? Did you use a savegame? @x3003

**Comment by x3003** [comment]
I have an nividia & amd, running under win10. All updated.
It's on gzdoom 4.5.0 and the latest dev version. Resolution is 1920*1080.
When pressing the tab, gzdoom just crashes, saying "Execution could not continue.
Could not allocate memory for vulkan buffer: out of device memory"

Crashdump attached.
[CrashReport.zip](https://github.com/Realm667/WolfenDoom/files/5875353/CrashReport.zip)

**Comment by Tormentor667** [comment]
@x3003 - This seems to be a problem with GZDoom, would you be so kind and can you share the CrashReport to the ZDoom.org bug forums?

**Comment by alexey-lysiuk** [comment]
It’s the same thing as reported in https://github.com/coelckers/gzdoom/issues/1285, and in some older forum’s posts as well.
In short, if your graphics hardware doesn’t have enough VRAM, Vulkan renderer isn’t your friend at the moment.

**Comment by x3003** [comment]
The weird thing is, as soon as I get off the tank (on the same spot), there's no crash anymore when accessing the map.

**Comment by Tormentor667** [comment]
> In short, if your graphics hardware doesn’t have enough VRAM, Vulkan renderer isn’t your friend at the moment.

Well, as long as this is an engine bug and the developers of GZDoom are aware of it, we need to simply wait and/or live with it. We will package the standalone release of Blade of Agony with the latest stable version available until then.
