### ISSUE TITLE
Guts and Blood parts instantly translucent after kill

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#345]
When you kill Wehrmacht soldiers or Scientists, the guts/blood parts they spawn are instantly translucent, but they shouldn't. It works well with Mechanics interestingly, no idea what's going on here though.

![144106574_711624546190139_6691072809790418106_n](https://user-images.githubusercontent.com/10298439/106043318-7d87f380-60de-11eb-913d-50e2d4d6d13e.png)

![143414078_3814255005301311_904011332728166409_n](https://user-images.githubusercontent.com/10298439/106043309-7bbe3000-60de-11eb-8e26-6372900c65e4.png)

**Comment by Wolfenburger** [comment]
Pretty crazy, hope to hear back from you soon so I can beta test and help spot bugs.

**Comment by AFADoomer** [comment]
Depending on how many other blood actors are around, this may be the culling kicking in...

**Comment by Wolfenburger** [comment]
So when am I going to test? I got the weekend off and will have a chance to inspect bugs and issues. I apologize to ask. Just hype and excited.

**Comment by Tormentor667** [comment]
I will answer your email as soon as I can :)

**Comment by Wolfenburger** [comment]
Rodger that

**Comment by Wolfenburger** [comment]
Figured you'd of had time to since you've been around updating. I am just super ready to beta test. Really hope I am not forgot. I am legit hype to do this and help in any way I can.

**Comment by Tormentor667** [comment]
@AFADoomer - Played around with it in the TEST_ACT map by using the shovel and killing all the nazis there. The problem with the transparent guts exists on all actors actually. Considering that nothing else was active at the time, I doubt that's the culling.

@Wolfenburger - I will just send you the mail with the latest beta in about half an hour. :)

**Comment by Wolfenburger** [comment]
> @AFADoomer - Played around with it in the TEST_ACT map by using the shovel and killing all the nazis there. The problem with the transparent guts exists on all actors actually. Considering that nothing else was active at the time, I doubt that's the culling.
> 
> @Wolfenburger - I will just send you the mail with the latest beta in about half an hour. :)

Rodger that. I'm hype. Love you guys for your hard work. I'll have my radar up. I'm at work atm but I'll be excited to play once my shift is over.

**Comment by x3003** [comment]
It's not only blood und guts, but one time someone I shot disappeard instantly and another one got half translucent.

![Screenshot_Doom_20210129_221235](https://user-images.githubusercontent.com/77861029/106356071-fd8ba480-62fc-11eb-8047-8e83a1f4980d.png)

**Comment by Tormentor667** [comment]
> It's not only blood und guts, but one time someone I shot disappeard instantly and another one got half translucent.

That's a rendering issue of GZDoom and something we unfortunately can't do anything about except posting it on ZDoom.org. The flatsprite gets drawm in front of the actor sprite. The engine is doing wrong something here.

**Comment by AFADoomer** [comment]
As I suspected, this is the culling.  

The culling for the various blood and gore actors uses the internal 'sv_corpsequeuesize' cvar to determine the max number of actors that can be present (because Droplets uses the native corpse queue handling to limit actor spam, since it pre-dated ZScript and event handlers).  

We need to increase the default value of that variable to something more than 64.

**Comment by AFADoomer** [comment]
Fixed in 1898a348c26fff4097097039df488300e98ee8c5.  Defaults for the preset aliases still need to be tweaked.
