### ISSUE TITLE
First mission, lag

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#346]
Upon looking up at the sky or down at the ground it lags. Or entering a hole in the barracks. I set my settings to the usual maximum. I suppose this is just because of the new maps being unoptimized a little bit?

**Comment by Tormentor667** [comment]
Well, if your settings are at max and it lags, then you simply need a better computer :) Well, regarding the performance, we pushed the engine to its limits and in some occasions, you might get slowdowns on lower hardware specs. If that is too heavy, simply don't use maxed-out settings.

**Comment by Wolfenburger** [comment]
I have a 3 thousand dollar computer with a dual 2080 set up.

**Comment by Tormentor667** [comment]
This wasn't meant cheeky or rude either, it was an assumption as I didn't know your specs before. Actually I'd really suggest to lower the performance settings and see if it gets any better. I actually only have a computer worth around 1000 euros and it is running Blade of Agony with all settings at max.
