### ISSUE TITLE
Sound related question.

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#348]
Amazing beta so far. Had not glitch issues in mission 1. Everything handled nicely. I have a bone to pick with the sound effect that emits when you pick food up. Its the obnoxious rtcw food sound. Is it possible I could maybe for myself client side, edit that? I'm unsure where in the dll that may be. I kinda wanted to add the old MoH bread eating sound :x if possible. Sorry to bug. Final thread for now. Again I'm newer than a greenhorn private to this.

**Comment by Talon1024** [comment]
The food sound for eating/picking up food is "pickup/mealfood", which is sounds/items/DSFDPCK.ogg

**Comment by Wolfenburger** [comment]
> The food sound for eating/picking up food is "pickup/mealfood", which is sounds/items/DSFDPCK.ogg

Not to sure where to find it. Its in a dll right? Sorry to be nooby. I'm on the right track. And I appreciate the kind quick reply.

**Comment by Talon1024** [comment]
https://github.com/Realm667/WolfenDoom/blob/master/sounds/items/DSFDPCK.ogg

**Comment by Wolfenburger** [comment]
> https://github.com/Realm667/WolfenDoom/blob/master/sounds/items/DSFDPCK.ogg

I mean like in my actual beta file where do I find the sound? I only have a file titled "Soundfonts" I don't see a "sounds" folder. If you want i can provide a screen cap.

**Comment by Talon1024** [comment]
Is there a wolf_boa.ipk3 in there? wolf_boa.ipk3 is just a ZIP file, and the ipk3 extension is so that GZDoom and other apps like qZDL recognize it.

Inside wolf_boa.ipk3, you'll find a "sounds" folder.

**Comment by Wolfenburger** [comment]
Just "boa.ipk3" but it is huge, how do I open a ipk3?
