### ISSUE TITLE
Tree blocking pathway

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#349]
On C3M1, there's tree in the way (of the 2nd camp), so you can't walk all the way around it. Is this done on purpose ?

![Screenshot_Doom_20210130_132700](https://user-images.githubusercontent.com/77861029/106356342-3cbaf500-62ff-11eb-9ac4-42910045a8d2.png)

**Comment by Tormentor667** [comment]
Yes, you are not meant to walk around it :)
