### ISSUE TITLE
Gameplay question

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#351]
Didn't get all 6 clue's in the first mission, should I repeat or can I still go on to get more clues to unlock special operation? Just curious. Also first mission runs flawlessly. It is very well designed.

**Comment by Tormentor667** [comment]
Without the clues, you can't run the secret operation, so try to find all of them.

**Comment by Ozymandias81** [comment]
4 clues on c3m1_A, 2 on c3m1_b :)
