### ISSUE TITLE
Observation.

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#352]
![Screenshot_BoA_20210130_215910](https://user-images.githubusercontent.com/77998291/106376309-19756180-6362-11eb-8fb4-11b0481275fc.png)
I know it sounds extra, which it probably is. But when you finally get help from the soviet's when your in that zombie town. I noticed the soviet soldiers and soviet commander have no gas masks on. I would imagine they would wear gas masks to prevent infection. Unless vodka has it's own natural immunity. Which keeps them from being infected. X3

**Comment by Tormentor667** [comment]
That's a pretty good spot indeed - I wasn't thinking about it myself... well, not sure if it is worth being added (gas masks to the russians) or if we can go for a different approach. I mean, it isn't insta-kill anyway, so maybe the russians also just survive the gas.

**Comment by DoomJedi** [comment]
Too much hassle artwise, hope for...simpler solution

**Comment by Wolfenburger** [comment]
Vodka probably gives them some kind of immunity lol. But its up to you guys. I'm sure you guys will think of something. My thoughts could be how the commisar mentions a air strike. Maybe when the Russians bomb the area, the fire disperses some of the gas. And they are sorta in a safe spot.

**Comment by DoomJedi** [comment]
Maybe they have pills against the gas, like they had for case of nuclear event.

**Comment by Wolfenburger** [comment]
> Maybe they have pills against the gas, like they had for case of nuclear event.

Iodine pills? Well they were invented in the 1800s. They have many purposes for human organs, but the nervous system isn't one. Iodine also stops radiation a bit. Unless these slavs got a their own kind of new pill.

**Comment by Username-N00b-is-not-available** [comment]
The air strike happens after the player and the Soviet troopers have left the town.
Inasmuch the Soviet soldiers from there are said to be NKVD/NKGB troopers, and not just regular army, we can indeed hand-wave that they were ![image to replace words](https://user-images.githubusercontent.com/59409713/106393685-a9bab180-6409-11eb-9b0a-048cd41dd9fb.png) given some experimental 'secret alcohol solution' before the battle (not a solution **of** alcohol, but of _something_ **in** alcohol). We can mention that in Volkoff's dialogue later on in the INTERMAP.

**Comment by Wolfenburger** [comment]
> The air strike happens after the player and the Soviet troopers have left the town.
> Inasmuch the Soviet soldiers from there are said to be NKVD/NKGB troopers, and not just regular army, we can indeed hand-wave that they were ![image to replace words](https://user-images.githubusercontent.com/59409713/106393685-a9bab180-6409-11eb-9b0a-048cd41dd9fb.png) given some experimental 'secret alcohol solution' before the battle (not a solution **of** alcohol, but of _something_ **in** alcohol). We can mention that in Volkoff's dialogue later on in the INTERMAP.

The pills the took were Breekium 420s. I legit support a joke idea like this. Like they had a pill. That cured it or held it off. And it was given a slav nick name. "Cheeki 9000" or something stupid. Shit could even do a nod to lifeofboris "Boris' Super Pills" just anything to be light hearted. Since we all seem to be fellows with good humor.

**Comment by Tormentor667** [comment]
> We can mention that in Volkoff's dialogue later on in the INTERMAP.

That's a good suggestion!

**Comment by Username-N00b-is-not-available** [comment]
I made the changes in the dialogue (VOLKOFFCONV01), decided instead to expand on it a bit rather than to specify a nickname.
@Wolfenburger Thank you for the observation!
