### ISSUE TITLE
Fight with Hitler

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#355]
Gonna be upfront there is like zero ammo in the final chapter, needs way more ammo. Tons, was bone dry by the half way point in the final mission. Also would be cool if some kind of epic music played after beating him on your walk out of the castle. Really would be interesting to also have banter from Hitler as he's fighting you. You'd think a blow hard like him would have something to say. Just suggestions and ideas.

**Comment by Username-N00b-is-not-available** [comment]
@Wolfenburger Congratulations on completing the game!

> would be cool if some kind of epic music played after beating him on your walk out of the castle

The silence is likely a design choice, summoning @Tormentor667 and @Ozymandias81 to comment on this.

> would be interesting to also have banter from Hitler as he's fighting you

He does say some phrases, but a player can not really hear them distinctly because of their volume, the distance from him and the overload of SFX during the battle. @Ozymandias81, do you think if it would be appropriate to play at least Hitler's sounds at full volume (```$attenuation 0```)? Also when I was recording a video of the new voice acting yesterday, Hitler seemed to say only two roaming phrases instead of three, _Mein Blondi beisst besser als du_ and _Du bist nichts im Vergleich zu mir_. (and there were no sounds at all played by Schwabbelhals, but I guess we can live with that).

As for the ammo amount, which skill did you play on? Is that a problem for all weapons, or there are some abundant ammo types and some deficit ones? Important to know (for me, at least), since I did not have such problems, likely because of that old Doom tradition of hoarding ammo for large weapons and using common ammo types in almost all situations.

**Comment by Wolfenburger** [comment]
> @Wolfenburger Congratulations on completing the game!
> 
> > would be cool if some kind of epic music played after beating him on your walk out of the castle
> 
> The silence is likely a design choice, summoning @Tormentor667 and @Ozymandias81 to comment on this.
> 
> > would be interesting to also have banter from Hitler as he's fighting you
> 
> He does say some phrases, but a player can not really hear them distinctly because of their volume, the distance from him and the overload of SFX during the battle. @Ozymandias81, do you think if it would be appropriate to play at least Hitler's sounds at full volume (`$attenuation 0`)? Also when I was recording a video of the new voice acting yesterday, Hitler seemed to say only two roaming phrases instead of three, _Mein Blondi beisst besser als du_ and _Du bist nichts im Vergleich zu mir_. (and there were no sounds at all played by Schwabbelhals, but I guess we can live with that).
> 
> As for the ammo amount, which skill did you play on? Is that a problem for all weapons, or there are some abundant ammo types and some deficit ones? Important to know (for me, at least), since I did not have such problems, likely because of that old Doom tradition of hoarding ammo for large weapons and using common ammo types in almost all situations.

I legit played on regular. I tried to desperately conserve ammo. And what little I had I ended up losing all of it with the 3 final bosses before Hitler. I had the blade and was launching fire bombs at him. But still if ammo is a problem on regular I can only imagine higher.

**Comment by Username-N00b-is-not-available** [comment]
>I tried to desperately conserve ammo. And what little I had I ended up losing all of it with the 3 final bosses before Hitler.

@Ozymandias81 And here is some evidence to my today's words on the players' perception of the fights.

---

@Wolfenburger Launching the 'fire bombs' with the Blade's altfire is really the intended way to kill three minibosses and Hitler, it does a lot more damage to all of them than even the stronger normal weapons. The minibosses go down in ten or twenty swings.
You say you also had problems with ammo before the final fight? Have you found the Nazi merchant in C3M6_A (he sells some useful items, including ammo)? Did you have a backpack (it doubles your ammo carrying capacity; there are two in C3M6_A secrets)? What about earlier maps, which ammo types would you suggest to add to them?

**Comment by Wolfenburger** [comment]
> > I tried to desperately conserve ammo. And what little I had I ended up losing all of it with the 3 final bosses before Hitler.
> 
> @Ozymandias81 And here is some evidence to my today's words on the players' perception of the fights.
> 
> @Wolfenburger Launching the 'fire bombs' with the Blade's altfire is really the intended way to kill three minibosses and Hitler, it does a lot more damage to all of them than even the stronger normal weapons. The minibosses go down in ten or twenty swings.
> You say you also had problems with ammo before the final fight? Have you found the Nazi merchant in C3M6_A (he sells some useful items, including ammo)? Did you have a backpack (it doubles your ammo carrying capacity; there are two in C3M6_A secrets)? What about earlier maps, which ammo types would you suggest to add to them?

Had found the merchant and had the upgrades. Ammo was scarce in the last 3 levels. The final one ultimately was the worst. Need like a weapons locker or some massive amounts of ammo in one or two of the missions. Also the 3rd mission before the final, the one where you're outside the castle when the blimp crashes chugs to unplayability in some areas. On OpenGL and Vulkan. On any setting. I noticed I'm like one of very few testers tackling these things. I feel special lol. Not really. But I'm happy to be helping extensively help.

**Comment by Tormentor667** [comment]
I agree with the hint on the alt-fire. @Username-N00b-is-not-available do you think you can add some lines to the final Gutenberg messages before the long Wolfenstein mission?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 I've done that, but we should keep in mind that the players are not obligated to read Gutenberg's messages or even interact with him _at all_ during the game. I think we should also add a hint e. g. to the beginning of C3M5_A about the altfire.

**Comment by Wolfenburger** [comment]
> @Tormentor667 I've done that, but we should keep in mind that the players are not obligated to read Gutenberg's messages or even interact with him _at all_ during the game. I think we should also add a hint e. g. to the beginning of C3M5_A about the altfire.

Easy, have the British Sergent say "That's a cool sword. Try and see if it can't do more stuff." Might make the player curious to swing the sword and do more stuff.

**Comment by Username-N00b-is-not-available** [comment]
@Wolfenburger This is also a good idea, but this dialogue of Ascher has a more 'pathetic' (poignant) role, and he can also be skipped. I'd like to use HINTTEXTC3M5_A for this. @Talon1024, could you please make the line be shown at the very beginning of the map (when the player takes out the sword)?

**Comment by MuadDib90** [comment]
> 
> 
> > @Tormentor667 I've done that, but we should keep in mind that the players are not obligated to read Gutenberg's messages or even interact with him _at all_ during the game. I think we should also add a hint e. g. to the beginning of C3M5_A about the altfire.
> 
> Easy, have the British Sergent say "That's a cool sword. Try and see if it can't do more stuff." Might make the player curious to swing the sword and do more stuff.

Ascher's line? And what about his message to a player:
"Hey, captain, does this sword do something special? It's a "mythical weapon", after all. As Gutenberg didn't forget to mention in every report of his."

**Comment by Wolfenburger** [comment]
> > > @Tormentor667 I've done that, but we should keep in mind that the players are not obligated to read Gutenberg's messages or even interact with him _at all_ during the game. I think we should also add a hint e. g. to the beginning of C3M5_A about the altfire.
> > 
> > 
> > Easy, have the British Sergent say "That's a cool sword. Try and see if it can't do more stuff." Might make the player curious to swing the sword and do more stuff.
> 
> Ascher's line? And what about his message to a player:
> "Hey, captain, does this sword do something special? It's a "mythical weapon", after all. As Gutenberg didn't forget to mention in every report of his."

Not sure what the question was for. But having Ascher make a question about the sword may help the player test the weapon more.

**Comment by Talon1024** [comment]
I was personally thinking of having Sgt. Ascher say something like: "Hey, Captain, remember how Gutenberg wanted field reports about the blade? Now would be a great time to try it out!" during the fight with Mengele in C3M5_A.

**Comment by Tormentor667** [comment]
That’s a good idea

**Comment by Username-N00b-is-not-available** [comment]
Your suggestions are nicely written, but none of them mention the altattack explicitly. I feel that we won't be able to tell the player about it in Ascher dialogues without breaking the immersion one way or another, so I insist on adding a direct reference hint in form of an Astrostein Repetierlaser-style comment, as I wrote earlier: https://github.com/Realm667/WolfenDoom/issues/355#issuecomment-772813244

**Comment by MuadDib90** [comment]
> 
> 
> Your suggestions are nicely written, but none of them mention the altattack explicitly. I feel that we won't be able to tell the player about it in Ascher dialogues without breaking the immersion one way or another, so I insist on adding a direct reference hint in form of an Astrostein Repetierlaser-style comment, as I wrote earlier: [#355 (comment)](https://github.com/Realm667/WolfenDoom/issues/355#issuecomment-772813244)

From my point of view, I think the altattack don't have to be explicitly mentioned. The first thing I did, when I could wield that mighty sword, was try an alternate attack. I see it as a a basic instinct. So a hint in form of a message from Ascher - as mine or @Talon1024's, which is maybe even better considering story consistency - is (for me) sufficient enough.

Although I understand your point, I think the message fits the story pretty well and at the same time gives the hint. @Talon1024's line about Gutenberg and his field report is kind of clever way of how to deliver it.

(And there is also that third option to have both possibilities: a direct reference hint with Ascher's message. - Or divide them: direct hint for lower skills, message for higher skills.)

**Comment by DoomJedi** [comment]
If people are not aware of weapon alt attacks - it can be a problem, but once they are aware of alt attacks for prior weapons - it's natural they will try it for each new weapon.
It can be a rewarding puzzle. Slight hint can help, but let's not overthink it.

One guy from russian Doom forum already finished Chapter 3 today and had only best words to say (and did not mention issues finding alt attacks)
""Well, third episode is now passed. I want to express my gratitude for the work, you have done a fantastic job! I especially want to highlight the detail of the maps, it is great! As well as the soundtrack. With all my heart, success to you! I was enjoying myself immensely".

So...

**Comment by Tormentor667** [comment]
I am open to both, Talons’ sand Noob’s suggestion, both points are valid and I can live with both of them.

**Comment by Wolfenburger** [comment]
> If people are not aware of weapon alt attacks - it can be a problem, but once they are aware of alt attacks for prior weapons - it's natural they will try it for each new weapon.
> It can be a rewarding puzzle. Slight hint can help, but let's not overthink it.
> 
> One guy from russian Doom forum already finished Chapter 3 today and had only best words to say (and did not mention issues finding alt attacks)
> ""Well, third episode is now passed. I want to express my gratitude for the work, you have done a fantastic job! I especially want to highlight the detail of the maps, it is great! As well as the soundtrack. With all my heart, success to you! I was enjoying myself immensely".
> 
> So...

So...? I don't know if you're trying to be snarky or not but not everyone has the same experience. And I genuinely am glad he had a fine standard of going through. He may of used cheats here and there and lumped through. Just because one person makes a post thats borderline shilling doesn't dismiss the other people's experiences. Yes there is a GIGA ammo problem in the last 2 missions. Yes there are some feats that need to be covered still. I don't even see the point of your post at this rate. Was it just to dismiss me and other people's thoughts or what?

**Comment by DoomJedi** [comment]
First, I apologize if I sounded snarky, and I didn't want to offend anyone or dismiss his experience with the mod (in general - and especially as I myself didn't play/see any of the Chapter 3 maps yet, beside part of mission 1).

I admit that I am a bit impatient about mod's release, and it sometimes can be felt on my comments, and if it offends anyone - I apologize, it's not a good way to act on my part. What I say - is not related to anyone specifically, just overall impatience to see the mod released, as sometimes reports and bugs look like....endless process that seem to have no end, with different preferences by different testers and of different level of importance to delay mod's release and sometimes attention to details anyone is barely notice.

Many potential players are impatient and already play the mod in its current form, and it's not a fact they will replay it later...so if release it too late - less people will experience its final form anyway. Such a ....almost ready mod - there is an issue to keep it on "open access" shelve for too long.
Spoilers are all around the forum already, many already played the mod and spoiled parts of it.

**Comment by MuadDib90** [comment]
>Spoilers are all around the forum already, many already played the mod and spoiled parts of it.

That's sad to hear. :(
(I don't understand why people have to spoil the fun to others...)

**Comment by DoomJedi** [comment]
I asked one guy on russian doom forum to hide his spoilers at least under spoiler tag.
But it's...unavoidable I guess.

**Comment by Tormentor667** [comment]
Well, we can live with that if people want to spoil their experience, they can do it. If other people read their comments, it's their problem as well. That's the downside of a public development - but the pro is that we gained people like @Talon1024 , @MuadDib90 and @Username-N00b-is-not-available - which is more more valueable :)

**Comment by Wolfenburger** [comment]
> First, I apologize if I sounded snarky, and I didn't want to offend anyone or dismiss his experience with the mod (in general - and especially as I myself didn't play/see any of the Chapter 3 maps yet, beside part of mission 1).
> 
> I admit that I am a bit impatient about mod's release, and it sometimes can be felt on my comments, and if it offends anyone - I apologize, it's not a good way to act on my part. What I say - is not related to anyone specifically, just overall impatience to see the mod released, as sometimes reports and bugs look like....endless process that seem to have no end, with different preferences by different testers and of different level of importance to delay mod's release and sometimes attention to details anyone is barely notice.
> 
> Many potential players are impatient and already play the mod in its current form, and it's not a fact they will replay it later...so if release it too late - less people will experience its final form anyway. Such a ....almost ready mod - there is an issue to keep it on "open access" shelve for too long.
> Spoilers are all around the forum already, many already played the mod and spoiled parts of it.

I just want this project to be earned in heart and soul and for it to be a perfect experience to everyone on launch brother. This is years of compassionate work. This must be fine tuned.

**Comment by Tormentor667** [comment]
Absolutely true, and thanks for the words :)

**Comment by Username-N00b-is-not-available** [comment]
Do we have a decision on the altattacks and the ammo balance yet?

**Comment by Tormentor667** [comment]
Well, I need to play it again, will do this after moving into my new home this week. What about other opinions? What do you think @Username-N00b-is-not-available ?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Part of https://github.com/Realm667/WolfenDoom/commit/88a2ed2a897cd697bdf69e306d390a7b85f1e5ad is what I'd do for the altfire, and for the ammo balance I suggest adding a few 'unofficial secrets' as seen in Doom IWADs, that is, small ammo caches in obscure places. I'll likely implement them now (and will mostly try to place rare ammo types).
BTW using the Firebrand altattack when having no souls costs the player absolutely nothing (I mean the actual projectile attack, not the powering-up which takes 25hp), is that intended?
