### ISSUE TITLE
Changes in the way, enemies were alerted?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#356]
After playing through C1 and C2, I noticed a number of times now, that enemies were alerted in places, were they were not in previous playthroughs from me. One prominent example is C2M3 or C2M5_A. A lot of soliders are already searching for you and looking after you, even though they are placed on spots with blocking sound lines. It worked actually before and doesn't as of now.

No idea if that's a bug of GZDoom or a bug of Blade of Agony, or maybe it's just me. That's why I am startign this discussion. Simply play C2M5_A, it's mostly notable when fighting through the train. A lot of enemies are active even though they shouldn't yet.

**Comment by Tormentor667** [comment]
Additional occasion: It happens in C2M5_B as well. The enemies in the room at 6460|6252 get alerted through the door and attack you before you even get near that place. That didn't happen in the past, and the line 14216 is blocking sounds, so the enemies shouldn't get alerted at all.

**Comment by x3003** [comment]
This also happens with C3M5_C, when you first open the door to the Rezeption, some ss-guys come in and start shooting. Even when you're quite before.

**Comment by Talon1024** [comment]
I think [this is the commit](https://github.com/Realm667/WolfenDoom/commit/1c9994fca107db689a9aeb2ddc454bbf960fe9bf) that caused this particular issue.

**Comment by Tormentor667** [comment]
That’s possible, maybe the problem is that they alert enemies despite having 1-sided lines or sound blocking lines between them.
I will just point @AFADoomer towards this.

**Comment by AFADoomer** [comment]
This should be fixed in 41cd873dad263198600c2a42c2d7b224fc3c304e.

**Comment by x3003** [comment]
Was playing a bit with the latest version, but when crawling through the fence in C1M2, I was spotted immediately.
What is the use of the hole in the fence if guards can see you coming ?

**Comment by AFADoomer** [comment]
To crawl through?

Stealth doesn't always work...
