### ISSUE TITLE
Can't hurt enemy sometimes

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#357]
On C3M0_A, you can't hurt the 'death hunter' for the first 20-30 secs when being inside of a building. By the time you can, you're already a corpse yourself. Outside I have no problem.

![Screenshot_Doom_20210204_164218](https://user-images.githubusercontent.com/77861029/106939399-80a76300-6720-11eb-8742-31f77cc8551f.png)

**Comment by MuadDib90** [comment]
I think it happend/happens to me too, the first time you encounter Death Hunter, you need to shoot at him a while, until he starts taking any damage. But only the first time on a map.
But dunno, if it is a wanted function, or not.
@Tormentor667 @Username-N00b-is-not-available @Ozymandias81 @Talon1024 What was the foremost intention back then?

**Comment by Talon1024** [comment]
As far as I know, you should be able to hurt the Death Hunter when you first encounter him.

**Comment by MuadDib90** [comment]
One side note (as it pierce my eye):
Shouldn't be better to have that Death Hunter's life status bar under that "undeath kill count bar" (not over)?

**Comment by x3003** [comment]
The picture taken was from inside when using a blue key.
Before that I encountered one when coming out the hotel (after getting the blue key). No problem hurting him then.

**Comment by Tormentor667** [comment]
I noticed this also on the C1-boss as well during my play through. The damage is being taken but the boss bar isn’t updating. Played it on skill 0 btw.

**Comment by Tormentor667** [comment]
@Talon1024 is it working now after this commit https://github.com/Realm667/WolfenDoom/issues/357#issuecomment-773537775 ?

**Comment by Talon1024** [comment]
Well, apparently @AFADoomer decided to add code that modifies an enemy's health separately from the MonsterHealth property within a MAPINFO skill definition. I don't know exactly why, but the only reason I see for doing this is to prevent sharks and other "critters" from having their health lowered by lower skill settings.

**Comment by AFADoomer** [comment]
Yeah, it's been that way for 4 years now...  You can probably change it to the MAPINFO skill setting if you want.  Don't know why it wasn't done that way in the first place.

**Comment by Tormentor667** [comment]
So, do we need to change this - or does it make to change this?
