### ISSUE TITLE
No parachute instructions

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#358]
Before the parachutejump (C3M5_C), the other officer doesn't mention what to do next, where to go and how to extract the parachute.

**Comment by Talon1024** [comment]
The parachute opens automatically, when you jump out of the airship entrance/exit with Sgt. Ascher.

**Comment by MuadDib90** [comment]
What do you mean by "what to do next"? The whole mission is on the wave "to get out of there", isn't it? So for me "to jump out" was quite logical.
On the other hand, well I wasn't thinking much about "how to open my parachute"... I don't know how much that is related to my "thinking" about Doom itself, its possibilities and functions. Maybe I just don't expect such a "function" as >open a parachute<.
But that's how I am seeing it.

**Comment by x3003** [comment]
>The parachute opens automatically, when you jump out of the airship entrance/exit with Sgt. Ascher.

Well, I think what I should do, is to get Arscher and get back to the section where the plate from the zeppelin has fallen out.
When I jump in there, I die.
So where to go next ?!

**Comment by Tormentor667** [comment]
Back to Asher :)

**Comment by x3003** [comment]
He just follows :(

**Comment by AFADoomer** [comment]
You don't jump out of where the plate fell, you have to go back to the beginning of the map where the entry ramp is now able to be opened.

**Comment by x3003** [comment]
I now see that the switch in the beginning got activated. With all of this shaking and so, it wasn't so obvious this got activated.

**Comment by Tormentor667** [comment]
So do we need a hint at the end where the player needs to go actually?

**Comment by x3003** [comment]
Maybe a hint and/or make the red light from the switch blink on/off ?!

**Comment by Username-N00b-is-not-available** [comment]
What about adding a series of animated blinking lights on some walls. which would indicate the direction to the emergency exit on being activated with the alarm? Something like these (the white part should flicker):
![notausgang](https://user-images.githubusercontent.com/59409713/107112873-ec4a1700-686b-11eb-8edb-76ba4aa0ab9d.png)

**Comment by Tormentor667** [comment]
Currently adding emergency exit signs - thanks @Username-N00b-is-not-available for the textures.
