### ISSUE TITLE
Can't jump over tables

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#359]
In C3M5_C you can't jump over this table go grab the ammo.

![Screenshot_Doom_20210205_131251](https://user-images.githubusercontent.com/77861029/107032715-89497900-67b4-11eb-9d2e-bf2c7d7d7892.png)

and can't also jump over the general's table in the screeningroom. Why ? Because it's faster to exit...
In the previous release the table was smaller, so it was easier to get around it.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 This was likely done so the player can not crouch and one-hit kill the officer without him raising the alarm. Eisenhimmel's table is probably blocked for a similar reason (there is a red key nearby which should alert Gestapo officers in the surrounding room).

**Comment by x3003** [comment]
The gestapo officers come anyway, sooner or later. But, I kill everyone on this level, so that's not a problem.
And I was talking about general John H. Miller's table, not eisenhimmel's.

**Comment by MuadDib90** [comment]
> 
> 
> The gestapo officers come anyway, sooner or later. But, I kill everyone on this level, so that's not a problem.
> And I was talking about general John H. Miller's table, not eisenhimmel's.

Yes, the Briefing room's table is blocking your way in purpose, so you stay inside the briefing room until the very end of briefing. Because many people (including me) just starter the briefing, and waited it outside next to Douglas.

(I must say I personally agree with this decision.)

**Comment by Tormentor667** [comment]
Exactly. You wouldn't want to jump over the General's table anyway. I mean, disrespectful can one be? :-D
