### ISSUE TITLE
Letter is boxed in

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#360]
You can't see / read this letter because there are boxes in front of it (and it's too close to the edge).

![Screenshot_Doom_20210205_110448](https://user-images.githubusercontent.com/77861029/107036601-2f4bb200-67ba-11eb-8039-1b4c1f7d6844.png)

**Comment by Username-N00b-is-not-available** [comment]
>You can't see / read this letter

@x3003 Why not? You can :-) It is just a bit risky, but really doable with Doom engine physics, where the player can have their center of mass over a chasm and still not fall. From this screenshot, you can go around the rightmost crate and reach the paper, balancing on the edge of the cliff.

**Comment by x3003** [comment]
I'm just an average player, not superman.

**Comment by MuadDib90** [comment]
Well yes, you can. If - as N00b said - you know the Doom logic. In Doom you can walk in fact on any edge of the cliff, if it has some wide. (but shorter the wide, the more danger to fall) Am I right, @Username-N00b-is-not-available ? :)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 You don't have to be a superman or a speedrunner god-among-players, you can e. g. just take careful steps.

https://user-images.githubusercontent.com/59409713/107051242-46e86200-67dd-11eb-8365-d2331b6cb1e1.mp4
