### ISSUE TITLE
letter colors

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#361]
When you're close to a letter it (the yellow box) becomes grey. It would be nice if it becomes grey -after- you've read it, not before.

**Comment by Tormentor667** [comment]
We had this discussion already at the development phase of chapter 2. I know that @AFADoomer has prepared something for the letters or the dialogues as well, but changing this now is something that is very difficult, as a lot of mechanics have been scripted and adjusted the way it works now. Changing this for over 300 occasions must be done manually and therefore is not fail-safe enough to consider it. So sorry, but we need to no this.
