### ISSUE TITLE
AI players annoying.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#362]
I think THE most annoying thing about the game are the computer players, who should help you, but are always in the way. Either blocking you in front or behind. You can also see it in some YT vids. that players getting annoyed by it.
Hope someone can finally fix this before the final release.

![Screenshot_Doom_20210205_105801](https://user-images.githubusercontent.com/77861029/107037794-e3017180-67bb-11eb-96bb-7540c093d94d.png)

**Comment by Tormentor667** [comment]
By "using" the NPCs, you can stop them following you. I think there is no explanation of that feature yet so I will just add a solution hint to C2M2.
