### ISSUE TITLE
Reinforments not wearing masks

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#363]
In C3M4, in the end part you have to wear a mask. But when the reinforments come, they don't wear one.
Which is odd, coz when I take mine off, I will die...
If the air is so good for them, why destroy the city otherwise ?!

![Screenshot_Doom_20210205_142222](https://user-images.githubusercontent.com/77861029/107039374-1fce6800-67be-11eb-816b-af16c1c53548.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 This is a valid point, the issue has been recently discussed in #352 and it is (somewhat) dealt with in new versions.
Adding gas masks to soldiers is too much sprite work, so we agreed on explaining this in Volkoff's dialogue by the soldiers' usage of an experimental antidote.
Please reopen this issue if you have any better suggestions on how to deal with the problem.
