### ISSUE TITLE
Ventilator shaft moved

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#364]
In this version playing C1M2, the ventilatorshaft move a bit upwards, so it's quite hard to get in and get the key and gold.

In the C2 release it was here:

![Screenshot_Doom_20210205_234336](https://user-images.githubusercontent.com/77861029/107097128-8e3a1700-680c-11eb-9ef5-81c65a4eed5e.png)

and with the C3 version it is here:

![Screenshot_Doom_20210205_162759](https://user-images.githubusercontent.com/77861029/107097171-a1e57d80-680c-11eb-987a-2f41315c9c6d.png)

**Comment by Username-N00b-is-not-available** [comment]
I also noticed that, but didn't report, because you can get the treasures by jumping over the <strike>lazy dog</strike> barrels which stand near the other end of the shaft.

**Comment by MuadDib90** [comment]
I think I was not able to get it from the other side, than it is shown in the picture above. I could only acquire it by jumping on those moving crates, than try to jump in to that shaft... and that was quite frustrating, because it lasted me like 20 attempts.
So, are you sure N00b, it can be obtained from the other side?

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 100% sure. Though I was incorrect about barrels, looks like either they were removed or I confused this place with some other one:
![Screenshot_BoA_20210206_121939](https://user-images.githubusercontent.com/59409713/107114349-3c2ddb80-6876-11eb-9385-dbe25b686668.png)
The bombs' height is just enough to hop on, so you can use them to get into the shaft, if you are careful enough to not detonate them beforehand. If you mess this up, well, you still can jump there from the top right ramp, but it will be much more difficult.
You can also use a grenade jump if you desperately want that key :-)

**Comment by x3003** [comment]
I know it now because i'm reading it here, but I (and others) would normally just blow them up and have a hard time getting the key. Where's the fun in not blowing them upt ;)

**Comment by Tormentor667** [comment]
Well, that's the point of a secret :) By the way you can reach it with some good jump skills from the other side as well. I consider this closed.
