### ISSUE TITLE
Declension system for Czech is not working

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#367]
as mentioned by @MaudDib90, putting that in an addition issue now to make sure to not loose track.

**Comment by Talon1024** [comment]
We need to add a few new entries to language.csv, with "A" and "B" suffixes.

**Comment by Tormentor667** [comment]
Right then, so I will keep this open.

**Comment by MuadDib90** [comment]
> 
> 
> We need to add a few new entries to language.csv, and then @MuadDib90 and @Username-N00b-is-not-available need to fill them in for Russian and Czech. I will prepare the entries for them to fill in.
> 
> They will be named like the other entries for the counters, suffixed with "P", except the suffix will be "A" and "B" respectively.

OK. Will wait.

**Comment by MuadDib90** [comment]
I tested @Talon1024's declension system for Czech, and it works fine now. (Wow, never thought I'd see this in action. - For all the Czech players, thank you.)
Other than those 3 issues in #371 (which are kind of problems of general perspective) it seems to be OK. 👍 

So from my point, this can be closed. Not know the @Username-N00b-is-not-available's part though...
