### ISSUE TITLE
C3M0_B does not end properly

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#368]
@Username-N00b-is-not-available mentioned this issue in the long issues post:

> @Tormentor667 You said that you have fixed this problem (the player cannot return to INTERMAP, they have to reload a savegame), and also the ability to escape the vault before its door closes, but here are two videos from today's build in which they can be seen again: c3m0_b.zip. For the polyobject, I suggest using a Polyobj_OR_... special. --N00b, 7 Jan 2021

I wonder, is this still buggy or is it working in the meantime?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Tested it quickly (just used ```pukename ending_sequence```), seems OK. It needs thorough testing, though, and I sadly have no more time left for testing now.

**Comment by Tormentor667** [comment]
Tried it with a complete test and it works.
