### ISSUE TITLE
SS Guards in C3M1_A disappearing after the explosion

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#369]
> SS guards just disappear after the explosion (which is also too small for the accompanying text), lowering the killcount. -- @Username-N00b-is-not-available 

The problem here is that I wanted to get rid of the soldiers - just if there were moving to the explosion and the entrance is empty for the player. Instead of making them disappear, what can we do instead?

**Comment by MuadDib90** [comment]
So coding the "moving" is not possible?
When the explosion starts, all soldiers start to move (for example 1,5x or 2x of their normal walk speed - as they were running) toward the explosion (and they will just gather there).

**Comment by Tormentor667** [comment]
Well, one solution would be to make all enemies tagged 91 move towards the explosion. But from there, they would still stuck and not be removed from the kill count. On the other side, making all enemies tagged 91 move towards othe explosion side would lead to problems. The player would cross them and some of them wouldnt be able to move directly there without any path nodes. I am not sure if this is really worth it.

Instead I'd remove all tagged 91 (as it is now). What do you think @Username-N00b-is-not-available ?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 You can use an approach similar to what I have recently done in C1M6. ```TeleportGroup``` the 91-tagged monsters into a large technical sector and massacre them. This will fix at least the killcount, but not the visual inconsistency.

**Comment by Tormentor667** [comment]
What about using the new flag instead that is available in GZDoom, not making them count at all?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Or that, if it works :-)

**Comment by Tormentor667** [comment]
![2021-02-08_174808](https://user-images.githubusercontent.com/10298439/107252655-da1bd480-6a35-11eb-9567-672d13d0660a.jpg)
It should I guess :)
