### ISSUE TITLE
Documenting new Blade of Agony features (temporary GitHub wiki, will be transferred to the site later)

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#370]
It is possible to open a wiki section in a GitHub repository: https://github.com/Realm667/WolfenDoom/wiki

---
I think it would be useful to create one and fill it with some general technical information for modders. Not proper documentation, just a roadmap which can at least highlight the main new features, already way too numerous in BoA. This might not only include code details from @AFADoomer and @Talon1024: I would have been also pleased to read e. g. a guide on extracting and modifying 3D models by @Ozymandias81, tips on using automated UDB features by @Tormentor667, and about @DoomJedi's sprite editing tricks. You guys have put so much work into Blade of Agony, it would be a great pity if potential modders won't be able to follow us, drowning in the game's complexity.
As for the workload, we can postpone writing the wiki and start after the release so as to spend time on more 'useful' things now. It'd be better to agree upon it now though.
What does the team think of my suggestion?
@Tormentor667 We should also remove or transform https://boa.realm667.com/index.php/help/docs (it is outdated as hell and may be misleading).

**Comment by DoomJedi** [comment]
Not a bad idea at all (and thank you for the compliments), just a bit intimidated about the scale...

**Comment by Username-N00b-is-not-available** [comment]
Added a start page for the wiki and a general outline of topics (as always, any suggestions are welcome): https://github.com/Realm667/WolfenDoom/wiki

**Comment by Username-N00b-is-not-available** [comment]
Wrote some short samples of articles for the wiki, so you can see for yourselves what I was talking about in the first post.

I know it was my initiative, and I can't expect anybody to like it, but only @DoomJedi has commented on the issue so far. Do other developers have any opinions on this?
I won't be able to write all the articles myself, that's for sure; if even I had time, I am properly acquainted with only a small subset of BoA features. Though I can possibly help even with something unknown to me, to do some research — if someone tells me what features I forgot. That's why I would like to hear arguments and come to a decision on whether we should ever start working on the wiki (closer to the release or after it, when all problems are fixed) or just abandon the idea and close the issue. Do other team members really not see any future in having a wiki?

**Comment by Tormentor667** [comment]
To be honest, I'd suggest updating the editing docs on boa.realm667.com instead of creating a new place for information and content - but not all that you have currently planned.

**Useful tools for creating GZDoom modifications** for example is too generic and more info on GZDoom which belongs to the ZDoom wiki instead, this goes for anything that is engine specific. For Blade of Agony special stuff, I am okay and I like the idea but as I said, it should be here: https://boa.realm667.com/index.php/help/docs

If you are interested, I can give you access to the backend of that system. I think it would be useful for modders and mappers.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Sent a response to your today's email, thank you for writing it!
I agree with your suggestion and am definitely interested in the system (for my part, do I need to just register a Realm667 forum account for this?), but I think for the beginning it'd be better to write the information here, since it is easier for a group to collaborate on GitHub. If this effort is fully transferred to the site, it will only be myself who writes anything there :-) Once we have finished the pages, I will then proofread the information, carefully prepare it and post to the webpage. What do you think?

**Comment by Tormentor667** [comment]
I totally agree here, that’s a good plan actually.

**Comment by Username-N00b-is-not-available** [comment]
I've added small explanations to some of the important code features to the [webpage](https://boa.realm667.com/index.php/help/docs), please add your corrections and suggestions to the page (or just write them here). @Tormentor667 The widget on the page shows only the first 20 category elements for some reason, but there are already 31 :-)
I would also like to have some info about the following code features there, but I decided to not do these ones myself (these classes are either too specific or too complex, I fear that my text about them could mislead modders):

<details><summary>List of features</summary>

- RevolvingDoor

- DialogueIcon.Animate

- GateKeeper

- SlidingDoor

- StatueBreakable

- CKPlatform

- LightningBeam

- MinecartEMoving

- SoulFountain

- BoAPlayer: SpawnEffect, dodragging, DoKick

- StealthBase, DisguiseFailToken, DisguiseToken

- BoASupplyChest

- spies
</details>

Also, this will only mean that we are finished with features that are somehow related to ZScript; there are some purely ACS ones, not to mention non-code advancements...

**Comment by Tormentor667** [comment]
>  @Tormentor667 The widget on the page shows only the first 20 category elements for some reason, but there are already 31 :-)

Fixed :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Thank you very much!

**Comment by Tormentor667** [comment]
By the way, what happened to all the old entries? I noticed that some of them are missing, for example these which explain custom flags like "user_static"

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 All the old entries are still there, if shortened _a bit_. ```user_static``` and lots of other features are [documented](https://github.com/Realm667/WolfenDoom/search?q=user_static) in the [code](https://github.com/Realm667/WolfenDoom/blob/8ab2940804360296bc59a903bcb69e9fb90dca7d/scripts/actors/enemies/base.txt#L128). I had removed easily accessible information from there, such as these flags' explanations which are already written in the same words in the code comments, DoomEdNums which can be found by just searching the MAPINFO for the class name, and so on. Such a reference list would anyway be helpful for modders to find the starting point in several megabytes of code that we currently have, and duplicating information easily leads to discrepancies and misapprehension.
Some of the feature use cases can be copied verbatim from our maps, but if a modder wants to use our code features in a somewhat different way, they will anyway have to consult the code for details on the implementation.

**Comment by Tormentor667** [comment]
Well, the problem with documenting features in the code requires the knowledge about a specific feature to actually exist. I'd suggest adding the documentation and the feature explanation both in our editing docs, to make these also accessable to modders that only want to create maps and not fiddle around with the code. E.g. "user_static" as it was in some of the old docs.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 OK. Could these explanations for ```user_static``` and similar things just be copy-pasted from the code comments? I'll start doing this now.
I would only like to warn you that the page will become way longer than it is now (and likely messier).

***

Would anyone like to contribute articles on topics which are not covered..?

**Comment by Tormentor667** [comment]
Yes that’s just fine :)

**Comment by Tormentor667** [comment]
> Would anyone like to contribute articles on topics which are not covered..?

As of now I am mostly busy with fixing bugs and discussing remaining stuff in the Facebook teamchat, so I'd at least leave this to the technical more educated people in the team :)

**Comment by Username-N00b-is-not-available** [comment]
I've mostly covered the topics I was able to, and transferred @DoomJedi's contributions from the wiki.
I'll likely add the scrapped code features there and stop after that, since now I simply don't have time to perfect everything myself.
I think the list is already enough of use to modders now, and dissecting the pk3 has always been the option to study Doom mods anyway.

**Comment by Tormentor667** [comment]
We can still continue on this after the release. Thanks alot for your effort here!

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 The "Screen shaders" section is incomplete, and you probably know the best how to use them in maps, so could you please write some more details about them, either here on GitHub or directly on the site? There are missing descriptions and unknown activation methods for some of them.

**Comment by Tormentor667** [comment]
Do you mean the LUT shader or the other ones? (heat, underwater, old video) For the other ones, @Talon1024 and @AFADoomer are the ones to talk to.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 The LUT/color grading and the heat shaders need explanations of what they do and how to control them, and the old video shader needs just a description of what it is.
