### ISSUE TITLE
Counters' problems

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#371]
- [x] **C1M4 - Ryan's response**
This is probably a minor thing, but I will present it anyway.

A hypothetical situation:
What if someone doesn't destroy all 5 upper flak cannons first? (Very low chance, I know, but this is my line "it can be done" :D )
Then the Ryan's response about the "last one down there" is kind out of the place.

Don't know if you want to deal with it at all given the very low chance of the situation happening, but I see it as kind of an error, that's why it is here.

> How could it happen though? The door to the ladder into the dam's lower part is opened right when you bomb the last upper flak cannon, and I think you cannot jump down to that area from the dam without cheats if you have not opened the door (you'll crash into the water). --N00b
>> My bad. Yes, you're right here. I forgot that. I do seem to "overthought" it. Sorry. --MuadDib

- [x] **C1M5 - kill counter (at the end)**
There is this line: "you killed XX soldiers in wave YY"
In Czech lang the wave counter is counting waves YY, but not killed soldiers XX in each wave.

In other words, there is still maximum XX soldiers number of the present wave, and if you kill all in the wave, the YY will switch +1. XX is always the maximum amount of the wave no matter how many you kill in the wave.

> I don't get the message, sorry. Could you please say what is wrong here and what should it be changed to? The numbers' behaviour here should be indifferent of the language you play in. --N00b
>> Now that I am reading it, this is really strange. I'll go through it later home. --MuadDib
EDIT:
The line is actually "kill XX more krauts in wave YY".
So, the bar was behaving like this:
1st wave (10 is an example)
kill 10 more krauts in wave 1 (number of all soldiers XX in a wave 1)
kill 10 more krauts in wave 1 (after killing the first soldier in wave 1 - but should be 9)
kill 10 more krauts in wave 1 (after killing the second soldier in wave 1 - but should be 8)
...
kill 10 more krauts in wave 1 (after killing the ninth soldier in wave 1 - but should be 1)
kill 10 more krauts in wave 1 (no more left (0), maybe even not displayed, don't remember)
2nd wave
kill 10 more krauts in wave 2 (number of all soldiers XX in a wave 2)
kill 10 more krauts in wave 2 (after killing the first soldier in wave 2 - but should be 9)
kill 10 more krauts in wave 2 (after killing the second soldier in wave 2 - but should be 8)
...
kill 10 more krauts in wave 2 (after killing the ninth soldier in wave 2 - but should be 1)
kill 10 more krauts in wave 2 (no more left (0), maybe even not displayed, don't remember)
.
So number of waves was changing, but not the remaining soldier count.
This should be more clearer of what happend, I thing.

- [x] **C2M5_B, C3M4, C3M5_C - counters' zeros**
In these maps the counter shows also the "zero count". Similar to the C1M4 map, which was already repaired by @Tormentor667. The bar with zero in it doesn't necessarily have to be shown, and also it looks kind of odd.

- C2M5_B - fan counter
- C3M4 - reinforcement counter
- C3M5_C - ship crash counter

**Comment by Talon1024** [comment]
The second sub-issue should be fixed in 1e8c67a44aedb1550bd9c1411ac30bbe305b8228

**Comment by MuadDib90** [comment]
> 
> 
> The second sub-issue should be fixed in [1e8c67a](https://github.com/Realm667/WolfenDoom/commit/1e8c67a44aedb1550bd9c1411ac30bbe305b8228)

Nice. Works.

**Comment by MuadDib90** [comment]
@Talon1024 
Tested it and there is one remaining thing.


- C2M5_B - fan counter **-- there appear zeros and there seem to be slight desynchronisation between tics and actual number change (in those other two, there is tic and number change at the same time)**

- C3M4 - reinforcement counter **-- OK now**

- C3M5_C - ship crash counter **-- OK now**

**Comment by MuadDib90** [comment]
@Talon1024
@Username-N00b-is-not-available 
Is this easy to repair? So we can close this already?
