### ISSUE TITLE
C3M5_A issues

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#376]
- [x] Ascher is shooting Russians (aren't they allies here?)

https://user-images.githubusercontent.com/73436978/107850536-672ea700-6e03-11eb-94a4-ba06199c78bd.mp4

- [x] And I don't even know, how to describe this "issue":

https://user-images.githubusercontent.com/73436978/107850552-7ca3d100-6e03-11eb-833b-f6345874716b.mp4

**Comment by AFADoomer** [comment]
First issue should/might be resolved after 7fd6d0b1b7974052044da8de51afcec38d2541e2.

Second issue is annoying and keeps cropping up occasionally.

**Comment by MuadDib90** [comment]
Yes, first issue seems to be solved. Thanks @AFADoomer 

So the second thing keeps popping up randomly on random actors, and noone knows, what to do with it?

**Comment by AFADoomer** [comment]
Just the debris piles.  The debris actors intentionally don't process much code after they initially spawn and fall to the ground in order to reduce think time.  In some cases, for some reason, they do this infinite loop of falling, and I don't know why.

**Comment by MuadDib90** [comment]
OK. In this case, if anyone hasn't any idea, I think we can close this...
