### ISSUE TITLE
A question on special missions

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#378]
So for Eisenmann, Astrostein and the Zombie level. Do we have any negative penalty for them not being completed? Like I kinda sorta think that if a player fails to ever truly kill Schabbs the Eisenmenn would be around later even in chapter 3. And more heavily. If astrostein isn't done you obviously won't get the armor. What about the zombie level though? I also like the end game easter egg.

**Comment by Talon1024** [comment]
For Operation: Eisenmann, AFAIK there are no penalties for not completing it. Supposedly, you would have to face more mutants on your missions, but that was a feature that was planned from before Blade of Agony was broken into chapters.
As for Operation: Regenschirm, the "Zombie level", if you don't finish it, you won't have enough cursed souls to enter certain secret areas, like the one on C3M3_B which gives you a Nebelwerfer.

**Comment by Wolfenburger** [comment]
> For Operation: Eisenmann, AFAIK there are no penalties for not completing it. Supposedly, you would have to face more mutants on your missions, but that was a feature that was planned from before Blade of Agony was broken into chapters.
> As for Operation: Regenschirm, the "Zombie level", if you don't finish it, you won't have enough cursed souls to enter certain secret areas, like the one on C3M3_B which gives you a Nebelwerfer.

I just find it odd that the Eisemmenn are completely gone by the turn of chapter 3. I honestly feel like there should still be some of them. I mean we got lopers. Its hard to imagine Schabbs remaining sons automatically switched focus to another program last minute. There should be at least a few dozen of them at the castle and maybe during it out with the undead. It would kinda be cool to see the nazis creations fighting one another.

**Comment by AFADoomer** [comment]
The ACS handling for removing Mutants at spawn is all still in place from MaxEd's original implementation...  There are three ACS variables that can be toggled that do exactly what their names indicate: disable_mutants, disable_big_mutants, and disable_supermutants.

The variables even get set in C1M0, you just never see them have any effect because there aren't any mutants in the last map of Chapter 1 (try beating C1M0 - or even just setting the C4 on the crate - then spawning a mutant - it will immediately disappear).

I could probably set up something to carry the variable values over between chapters...  Probably a CVAR or something would be easiest.  But then we'd have to place mutants in C2 and C3, and deal with confusion from people playing that don't go back to play C1 again before playing C3.

**Comment by Username-N00b-is-not-available** [comment]
@Wolfenburger 
> Its hard to imagine Schabbs remaining sons automatically switched focus to another program last minute.

We have PAPERTEXT29 where Hitler orders them (at least one of them) to stop and return to Berlin for new instructions.

@AFADoomer CVARs can easily be modified, and this will not even be considered a cheat, so many players who don't want to replay C1 would just change the CVARs 'by hand' from the console, essentially circumventing the measure.

***

I'd rather not change anything with mutants, we have several explanations and hints for their disappearance, see e. g. entries MARINE1CONV14, PAPERTEXT29, PAPERTEXT31, PAPERTEXT32. We cannot calculate the outcome and write a separate storyline for every possible gameplay alternative. Canonically the player is expected to visit all the secret levels, and if they do not... well, it's just their choice.

**Comment by Tormentor667** [comment]
To clear things up: The plan at the beginning was actually to make the whole Chapters being played after each other without a break. That's what the system was there for. I scrapped the idea though and even though the functionality is still there, we won't change this. It's not worth it and we would have to fiddle around too much with the consequences.
