### ISSUE TITLE
Small-delay active sound spamming by actors

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#379]
@AFADoomer @Talon1024 This old issue can finally be reproduced quite consistenly on commit https://github.com/Realm667/WolfenDoom/commit/47c039d09fdde76303e72d055ff0404de1d220b9. Steps:
- ```map c3m3_b```, ```iddqd``` and ```idkfa```;
- go past the spy and the dogs' room, open the door and stand in the corner right to the door; kill some of the guards but leave e. g. two of them. The nearby spy will spam active sounds (this depends somehow on him seeing the enemies) until the remaining enemies die.

**Comment by AFADoomer** [comment]
Should be fixed in 62460fc29c13810ffe5ecc16a875ffee763e3796.  

This should have been fixed for other enemies already...  This specific fix adds the same check for spies that was already in place for sneakable and frightened enemies.
