### ISSUE TITLE
Can't open door

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#380]
This door can't be opened by the player, but only by an enemy doctor. But most of the time the doctor comes out very early, when you open the main door to this room. After this no one gets out anymore  (some others might be dead inside) and you can't get the key.

![Screenshot_Doom_20210214_172854](https://user-images.githubusercontent.com/77861029/108265712-69796400-7169-11eb-820c-a55a815e2094.png)

**Comment by AFADoomer** [comment]
Please provide the map name and coordinates (set 'idmypos' to true in the console) when you post bugs like this.

**Comment by Talon1024** [comment]
Judging by the screenshot alone, the map is C3M1_A, at -22752, 1024.

-------------

I think it was intentional that you can't open that door from that side, but the enemies probably shouldn't be able to open it if it breaks the level progression.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 You can get the key anyway, the intended progression is to break a ventilation grate on (-22896, 1344) and fall through, you can get to the grate by going upstairs in the door area. As @Talon1024 says, it was intentional that the door is opened from the other side.
