### ISSUE TITLE
blade causes damage

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#382]
When activating the blade, it causes damage for the player. I hope this could be fixed, why else would someone activate the blade, if you lose health all the time ?!

![Screenshot_Doom_20210216_001202](https://user-images.githubusercontent.com/77861029/108266657-a5f98f80-716a-11eb-9be1-ff6e582f6598.png)

![Screenshot_Doom_20210216_001208](https://user-images.githubusercontent.com/77861029/108266467-6af75c00-716a-11eb-90fd-9a3d5b714608.png)

**Comment by Talon1024** [comment]
This is intentional. However, if you have some cursed souls, you can use the blade's alternate attack without getting hurt.
