### ISSUE TITLE
Important questions for discussion

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#383]
Duplicating the unresolved questions & suggestions which need **discussion** (not plain old bugs) in a separate post, so it would be possible to read them through. Please share your thoughts on them, some are quite important:

- [x] C3M0_A: killcount is totally off, it may be better to disable showing it at all. Pre-placed zombies count towards kills, spawned ones not, and it is impossible for a player to distinguish them.

> https://github.com/Realm667/WolfenDoom/commit/3e1b331ddba3dce9f7759589d3d062b3ae0fc4b9. Thanks, @AFADoomer! --N00b, 21 Apr 2021

- [x] C3M0_A: absolutely nothing indicates that to start assaulting the SS HQ you have to gather all three weapons (Browning, G43, Nebelwerfer) from their specific spots. Else the player can only wonder what to do after grabbing two keys and, for example, missing the butcher's with the rifle. I think the corresponding primary objective should be re-added.

> Well done, @Talon1024, thank you very much! --N00b, 22 Apr 2021

- [x] C3M0_A: Is it really necessary for the player to wait several minutes until the Nemesis wakes up again after destroying the SS HQ? Could you please force Nemesis to revive himself when the player leaves the area, or at least give another message the player to wait a bit 'until the reinforcements arrive'?

> As far as I know the behaviour has been changed by @Talon1024 , maybe he can just confirm and check this issue --T667 (14th April)

- [x] C3M0_A: I have severe lag in the city part of the level, I have to pause the game every few seconds to avoid stuttering. Could anyone please think of some measures to reduce the workload on the CPU, maybe adding more one-sided linedefs which block the view, or replacing lots of small decorations with bigger ones?

> This really needs a map-side fix.  Run the level with 'stat rendertimes' and check out the S: stat...  Even with more aggressive culling (if I enable it for all models, lights, and other decor) this area renders a ton of sprites/actors at a time. There are *3500+* things in the city portion of the map, compared to just over 3000 in the mansion and start area, and not quite 1900 in the underground area.  - AFA (21 Apr 2021)

> @AFADoomer By 'more aggressive culling', what values do you mean? The area works generally quite okay for me now with Vulkan and 4096 on everything, the S: is around 2.0, but when exploring the map there are lots of lag spikes, S: temporarily becomes around 300 and more (is it measured in milliseconds?). I suspect it is because of new models having to be loaded from the HDD, and wonder if something like [PrecacheClasses](https://zdoom.org/wiki/MAPINFO/Map_definition#PrecacheClasses) could help with this. --N00b, 22 Apr 2021

> I set up my local build to also cull all model-based decorations and lights.  Probably going to hide the capability behind a CVar and commit tonight.  I get some improvement in render time from that, but it's still bad.  For lag spikes, make sure you don't have something like Github running in the background.  I'll experiment with Precache, but I think that would only help on first load of the model, not each successive spawn. - AFA (22 Apr 2021) 

> No, this happens every time, even when only GZDoom is opened. For me it's always some large model (I set all distances to 512 for testing the matter) that pops up in the view after a lag spike, e. g. the one which stands near the entrance to the opera house. As for precache, the lag spikes do not seem to appear in previously visited areas, I think the bottleneck here is either loading from HDD or unpacking the pk3 on the fly (I am running the game from an .ipk3, not from a directory). When a model respawns, the game would fetch its data directly from RAM instead of extracting the archive, and there should be no lag anymore (at least, this is my theory, it seems to hold on my machine).
Also, have you noticed that on C3M5_C there is a lag spike near the beginning when the SS MP40 guard near the red door gives the player a Nazi salute? After you reload the map, it disappears (the sprites/"Herr Hauptmann!" sound would have been loaded into RAM). --N00b, 23 Apr 2021

> I get zero change in performance even with every actor precached...  But I also (usually) don't get lag when I re-visit areas, either. Anyone else seeing this? - AFA (23 Apr 2021)

- [x] It is possible to postpone going to C3M0_A at least after finishing C3M2. Not sure if it is desirable, some INTERMAP scripts could break (have not tested it yet), and you can also freely get a minesweeper and a repair kit which allow to circumvent some areas in C3M0_A.
> Repair kits have been fixed and we can live with the minesweeper thing, but idk if INTERMAP gets broken somehow. --Ozy81
> I suspected that you could have visited C3M2 two times this way, checked it right now, this is not the case. Everything seems to work correctly. --N00b, 22 Apr 2021

**Comment by Username-N00b-is-not-available** [comment]
<details><summary>Resolved issues</summary>

- [x] C2M4 suggestion: add a reward for destroying all planes?
- [x] One of the textures used in C2M6_C has 'Projekt Seeteufel' on it, maybe it is better to either rename the enemy or change the project name to https://de.wikipedia.org/wiki/Schwertwal_(U-Boot) so as not to confuse the players?
- [x] Is it really necessary to have a damage penalty for unscoped Kar98K fire?
> Yes, thats an intended behaviour. The Kar98k shouldn't be used as assault rifle but as sniper rifle, so use the scope and you have full damage. - T667 (18 Feb)

> TBH, to me there's something so stereotypically "baby's first ZDoom mod" about this behaviour, it is non-realistic, arcadey and quite overused, even [a ten-year old WildWeasel's tutorial](http://gunlabs.blogspot.com/2011/02/tutorial-inventory-variables-and-making.html) mentions it. Though it may really be no big deal, there is an explanation that the bullets deal more damage because the player can take aim at and hit more vulnerable spots when looking down the scope. --N00b, 19 Feb 2021

- [x] If the player has no souls, he is able to power up the Firebrand with his own HP. That's fine, but this way they are still able to use the altfire attack, and it would cost them nothing until the effect runs off and the player has to use up their HP again. Is this tolerable or not?
> That's okay and has also been issued by Gutenberg ("The sword can damage the bearer"). On top of that, the attack through health is not as powerful as through souls. - T667 (18 Feb)

> I was hinting at that health spending only occurs when you power up the sword, not when you use altfire after that. After spending 25 souls the no-souls altattack itself is basically for free. Also didn't pay attention to the no-souls attack being 5x weaker, thank you for the info! That makes it a fine balance. --N00b, 19 Feb 2021

- [x] We probably have to make a final decision for the sprinting and flinch amount in Cheats Options menu if we want to see BoA speedruns. These settings have a big impact on gameplay, and the player is free to change them as they are not considered cheating in-game.
> I kinda agree. I would suggest hiding these options (uncomment them). - T667 (18 Feb)

> Hiding as in removing from menu, or removing the CVARs completely? If we just remove the options from menu, the knowing players will adjust the CVARs manually from console. I'd remove them completely (and add their default values in places where they are used), but just before the release, since these two cheat options are quite useful for testing/debugging. --N00b, 19 Feb 2021

> Ah, nope, please disregard that n00bishness of mine. There is an option to count them as cheats, a commit is upcoming. --N00b
</details>

**Comment by Talon1024** [comment]
> Lt. Heit shows a message about the player completing Schwarzwald before C2M3.

This is what I see:
![Screenshot_Doom_20210220_150758](https://user-images.githubusercontent.com/6550500/108607337-bf2e5600-738d-11eb-8518-9262850c4ad7.png)

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 Doesn't "I've been hearing about your recent efforts" imply that the player had already made the efforts? This message would fit after C2M3, not before it.

**Comment by Talon1024** [comment]
C2M2 takes place near the Black Forest. Look at the briefing, or some of the papers on C2M5_A and B

**Comment by Username-N00b-is-not-available** [comment]
*facepalm*
Now I see that M2 and M3 are both connected with the Black Forest... You are completely right, sorry. Withdrawn.

**Comment by Talon1024** [comment]
> C3M0_A: absolutely nothing indicates that to start assaulting the SS HQ you have to gather all three weapons (Browning, G43, Nebelwerfer) from their specific spots. Else the player can only wonder what to do after grabbing two keys and, for example, missing the butcher's with the rifle. I think the corresponding primary objective should be re-added.

I agree. I think the primary objectives should be:
- Meet up with Lt. Arlow
- Prepare to raid the SS HQ
- Get chemicals from Opera house backstage (replaces second Primary objective)
- Raid the SS HQ and find a radio

>  C3M0_A: Is it really necessary for the player to wait several minutes until the Nemesis wakes up again after destroying the SS HQ? Could you please force Nemesis to revive himself when the player leaves the area, or at least give another message the player to wait a bit 'until the reinforcements arrive'?

I would rather give the player a bit of time to reload and/or stock up on ammo. Maybe ammo for all weapons should be rewarded for clearing out the SS HQ?

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024
Maybe it's better to just plainly write 'Gather weapons to raid the SS HQ' in the second primary objective? Arlow says about 'weapons, ammo and medical supplies', but only weapons qualify for the objectives.

I would add a large ammo cache in the SS HQ (for example, behind Hitler's portrait in the Totengraeber's room: just like the chest key in C1M1, but with lots of ammo and already half-open) and have Arlow say about it via radio (I have already adjusted the CSV texts for it).
If we just give the players time, players would have to wander around aimlessly for several minutes, as there is no indication of what to do next while waiting for the 'rescue team'. It is also very easy to get overrun by zombies during this time.

**Comment by Tormentor667** [comment]
I agree with your suggestions here. Adding some more ammo to the SS HQ in a secret stash would work for me but it should be very easy to find it.

**Comment by Talon1024** [comment]
> I would add a large ammo cache in the SS HQ (for example, behind Hitler's portrait in the Totengraeber's room: just like the chest key in C1M1, but with lots of ammo and already half-open) and have Arlow say about it via radio (I have already adjusted the CSV texts for it).

How about doing something with that elevator? For example, the ammo cache can be in the basement, and the player will be able to access it via the elevator in the building.

**Comment by Talon1024** [comment]
> C3M2: the map is lagging as hell, including during the machinegun hill defending scene and the tank ambush (where it is especially frustrating), both on default and low settings. On default my FPS does not raise over 15 and frequently drops to 5. Any measures here as well?

I think the bottleneck here is sprite rendering... Enter `stat rendertimes` in the console and see what you get. I think the "S:" stands for "sprites", and I think the 3D models may also fall into that category...

**Comment by Tormentor667** [comment]
> 
> 
> > I would add a large ammo cache in the SS HQ (for example, behind Hitler's portrait in the Totengraeber's room: just like the chest key in C1M1, but with lots of ammo and already half-open) and have Arlow say about it via radio (I have already adjusted the CSV texts for it).
> 
> How about doing something with that elevator? For example, the ammo cache can be in the basement, and the player will be able to access it via the elevator in the building.

I currently want to avoid any more mapping work actually. I feel pretty much exhausted with that and I think added a stash somewhere is enough effort instead of creating something that complex.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 That's fine, but I hope we won't axe my today's work? It's just I have already added a mix of my own and @Talon1024's suggestion...

**Comment by Tormentor667** [comment]
Most propably not :) If you already did it (and this is what I currently see), I am okay with it.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024
> I think the bottleneck here is sprite rendering... Enter `stat rendertimes` in the console and see what you get. I think the "S:" stands for "sprites", and I think the 3D models may also fall into that category...

Yes, the main problem seems to be 'S:', the 'Render=' is always the largest entry there on C3M2, around 10ms, but in open areas it jumps to 30ms and sometimes even more.

**Comment by AFADoomer** [comment]
I just added handling to the culling code to let RandomRye be culled (same lod range as grass actors)...  Should improve C3M2 performance.

**Comment by Tormentor667** [comment]
Fixed various issues, things that I was capable of.

**Comment by Username-N00b-is-not-available** [comment]
There are 11 questions left in this issue, would anyone like to speak out on any of them?
If not, it may be time for me to close this issue.

**Comment by Talon1024** [comment]
> C3M0_A: absolutely nothing indicates that to start assaulting the SS HQ you have to gather all three weapons (Browning, G43, Nebelwerfer) from their specific spots. Else the player can only wonder what to do after grabbing two keys and, for example, missing the butcher's with the rifle. I think the corresponding primary objective should be re-added.

I think we should change the primary objectives to:
- Meet up with Lt. Arlow
- Prepare to raid the town hall
- Get chemicals for making explosives
- Raid the town hall and get a radio

We can put the fourth primary objective on the list by "scrolling" the list down: The first primary objective is replaced with the second, the second is replaced with the third, and the third is replaced with the fourth.

**Comment by Tormentor667** [comment]
Agreed with everything @Talon1024 said, I am okay with these changes if someone can take care of them.

**Comment by Tormentor667** [comment]
Updated the first post with some comments.

**Comment by Username-N00b-is-not-available** [comment]
Only questions regarding C3M0_A are left, and after discussing that the issue could be closed.

**Comment by AFADoomer** [comment]
The 'user_nocountkill' UDMF property can be set to true for all of the map-placed zombies in C3M0_A...  That would fix the first issue here, at least, I think.

**Comment by Tormentor667** [comment]
How good is the performance in C3M0_A after AFA's recent improvements?

**Comment by Ozymandias81** [comment]
I'll test it on sunday most probably.

**Comment by Tormentor667** [comment]
I don't notice any slowdowns on my pc, so I can't really spot a difference.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 Have you tested C3M0_A today? If you did not notice severe slowdowns, this issue can be closed (finally, another one!)

**Comment by Tormentor667** [comment]
Reminder @Ozymandias81 :)

**Comment by Ozymandias81** [comment]
I need some proper free time to test it, but these are troubled days for me and I am still writing down the interview for safarigames.it ... Maybe tomorrow I can check it out, under gzdom 4.6 r915.

**Comment by Tormentor667** [comment]
I think the interview is currently less important than the fixes

**Comment by DoomJedi** [comment]
I agree, my thoughs exactly

**Comment by Username-N00b-is-not-available** [comment]
https://github.com/Realm667/WolfenDoom/issues/521#issuecomment-828637817
