### ISSUE TITLE
Weapons can't be seen by enemies

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#385]
In C3M1 when you suppost to be disguised, you can hold a weapon and the enemy doesn't see it.
Only when you switch weapons, they get into action.

![Screenshot_Doom_20210219_154621](https://user-images.githubusercontent.com/77861029/108520421-f38d0e00-72ca-11eb-8bf2-3bb5d8dcc95d.png)

![Screenshot_Doom_20210219_155458](https://user-images.githubusercontent.com/77861029/108520430-f687fe80-72ca-11eb-86cf-f1ad9d4ab751.png)

**Comment by Username-N00b-is-not-available** [comment]
Can't confirm this, likely something with disguises (could you please remember the path you went through the building? It would likely help a lot)...
BTW found one more problem in the map: killing the officer to obtain the field radio does not alert the guards even if the door to the house is open.

**Comment by x3003** [comment]
I just exited the red doors (on the right, first pic) with the weapon, after cleaning that building first. Then I thought, why aren't they shooting at me ?!

**Comment by Talon1024** [comment]
I just tried playing C2M6_B on "Mein Leben!" (SS disguise), and if I pull out a gun whilst standing still, the enemies won't recognize me. However, if I have a gun out while I'm moving, the enemies recognize me right away.

**Comment by x3003** [comment]
Thats's a little different. Still odd though. It doesn't matter if i'm moving or not. Or which level, i've also tried the middle one.
Only when i'm changing weapens inside the building w/ the red doors and walk outside, they don't see it.

**Comment by AFADoomer** [comment]
Please test with e3a7417504f819e78b1bc4c3242585ca6e3eb76b.

**Comment by x3003** [comment]
That works, but now there's another problem. When i'm -not- having a weapon and disguised, I can't get over the point [seen below] w/o being spotted.

![Screenshot_Doom_20210221_103413](https://user-images.githubusercontent.com/77861029/108621059-ab87fb80-7430-11eb-901c-a004d566b5b6.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 I don't think you are supposed to be able to cross that line for the second time after walking into the camp. The guards shoot at you because they think you try to escape (but actually you are crossing it from another side).
I think the problem is the double red door at the main building, the guards should be alerted when you try escaping from there.

**Comment by x3003** [comment]
Seems to work fine now. Maybe close this one ?
