### ISSUE TITLE
Tank won't react

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#386]
In C3M1, when you don't grab the panzerschreck from the basement, the tank won't do anything, so you can get past that one easily.

![Screenshot_Doom_20210219_222627](https://user-images.githubusercontent.com/77861029/108563771-4fbf5480-7302-11eb-9de1-1950fc6ba6de.png)

![Screenshot_Doom_20210219_222714](https://user-images.githubusercontent.com/77861029/108563783-564dcc00-7302-11eb-9449-e85f9b9abaf4.png)

**Comment by Talon1024** [comment]
What skill are you playing on @x3003?

**Comment by x3003** [comment]
just lousy level ;)

**Comment by x3003** [comment]
On the middle level the tank does react. But you can get past w/o being hurt ;)

**Comment by Username-N00b-is-not-available** [comment]
Due to multiple alternative paths, there have always been serious issues with the stealth system on the level. Does not visiting the Mengele fight still leave the ```notarget``` flag on the player now?

**Comment by Tormentor667** [comment]
It actually doesn't matter if you grab the Panzerschreck or not, the tank gets activated when leaving the trainstation heading north. I don't understand why it wasn't activated in your case but what @Username-N00b-is-not-available says could be an issue maybe. Pointing @AFADoomer and @Talon1024 towards this.

**Comment by Talon1024** [comment]
It's activated by a sector action thing, which is not a good idea because it is unreliable. Remember when I couldn't get the C2M6_C ending sequence to work, or when I was still taking greatly reduced damage on C2M4 after the truck ride? You really shouldn't count on sector action things.

**Comment by Tormentor667** [comment]
I wasn't aware of this actually, but thanks for the hint and fixing it.
