### ISSUE TITLE
Text icon gone

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#387]
On C3M1 on -this- letter, the icon text isn't here anymore.

![Screenshot_Doom_20210220_150957](https://user-images.githubusercontent.com/77861029/108598628-f4877380-738e-11eb-874a-809daea4db0d.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 There are no question marks shown above these papers on non-'lousy', as you say, skill levels. This is intended.
Only Bund Deutscher Maedel and Morgenspaziergang skills have the question marks.

**Comment by x3003** [comment]
Ah, I played it on normal level...
Lousy is me, I'm not a pro player like many of these youtubers....
