### ISSUE TITLE
Making the Gestapo more dangerous

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#388]
I am currently playtesting the game, especially C2M6_B and I think the Gestapo needs to be more dangerous. I can easily run by them without getting uncovered on the middle skill setting. Maybe we can make the curve on this setting a bit tougher @AFADoomer (about twice as dangerous as they are currently).

**Comment by MuadDib90** [comment]
I had the same issue on highest skill.

**Comment by Talon1024** [comment]
I just did this: 9a2e626e4f56947f7aea4e1252d25030fca6c56c

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 What do you think about also making them unload 4 bullets at the player in a rapid succession, like the Wehrmacht officers do, instead of only one? This way they could become a more serious opponent in battle, not just bags with health like they are now.

**Comment by Tormentor667** [comment]
Well, the danger about the Gestapo is not their attack but simply that they are able to uncover you. I see no need to make them stronger and start checking for rebalancing issues again.
