### ISSUE TITLE
C3M5_C music

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#389]
I saw a player request to add this Wolfenstein 2009 music track into BoA: https://www.youtube.com/watch?v=6Fb4HgucsiQ&feature=emb_logo. What do you think about changing the track which plays on C3M5_C after destroying the engine from D_HURRY2 (also from Wolf2009) to this one?

**Comment by Tormentor667** [comment]
I like it, I am okay with the change if you want to take care of it :)
