### ISSUE TITLE
CVAR abuse

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#390]
A tricky player can intentionally set e. g. ```boa_treeslod``` to 1 from console and essentially have all the trees almost disappear by courtesy of ```EffectManager```; we can't even consider this a cheat. To see what it gives gameplay-wise, you can e. g. warp to C1M3 or to the first Wehrmacht fight area of C3M3_A across the bridge.
The problem with CVARs of similar type can be fixed quite easily by clamping the distance with its menudef minimum (1024) before using it, but I think more analysis is needed on the effect of other CVARs.

**Comment by DoomJedi** [comment]
I really think we care too much about speedrunning...and BoA doesn't fit speedrunning IMHO - as there are just too many ways to cheat.

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi That's not only about speedrunning, IIRC there are places in the game where trees block some pathways and the player can go out of bounds if trees are not present; then they can sometimes get advantage in long-distance shooting from unexpected angles, where the map designer thought 'this enemy unit will be blocked by trees anyway', etc. What bothers me is that you can get such behaviour without 'cheating', though declaring ```boa_treeslod``` as a cheat CVAR would make even less sense, hence my suggestion.
Too many ways to cheat or other quirks does not mean our team should accept and happily live with all of them. Nobody else is going to fix them for us :-)

**Comment by Tormentor667** [comment]
Well, if someone is really digging so deep into the code and changes the CVARs for such an advantage (that totally destroys the look of the game by the way), he can go even further and remove or modify resources himself. This is really not worth the effort considering that the whole IPK3 is just a ZIP archive with most of it's coding content being open source.

**Comment by Username-N00b-is-not-available** [comment]
>🎵Deep Into the Code🎵

I think anybody who's been using ZDoom for more than a month knows what a CVAR is. Though maybe it's really not worth the effort since this 'hack' has an obvious visual outcome, but I wonder what other subtle and non-obvious gameplay changes can be achieved by this method. I agree this is not the highest priority.

**Comment by Tormentor667** [comment]
Yes, but ask yourself who wants to do that and what purpose this would have :)
