### ISSUE TITLE
Spriters Resource

### ISSUE THREAD

**Issue by DoomJedi** [Realm667/WolfenDoom#391]
"Blade of Agony" sprites have been uploaded to that site (was notified by a good pal today), obviously without our permission and against BoA resource policy.

[https://www.spriters-resource.com/pc_computer/wolfendoombladeofagony/?fbclid=IwAR1hFZJzd6daZlmi8NMfnhe8Lk0MV0W1gVoKIWIBjq528jz_YAz74LUXPuQ](url)

What should we do about it?

**Comment by madame-rachelle** [comment]
Up to you guys if you want to go this route, but there is a way to request a take-down. 
https://www.spriters-resource.com/page/faq/
* **I'm the copyright holder for some of the content you have on your site and would like it removed. Who should I get in touch with?**
While we would love to see all of the content we host remain online and accessible, we fully respect the rights and wishes of the content creators and owners. If you are the owner of a piece of content on any of our sites and would like it taken down for any reason, please just email us using the contact form. You'll be asked to verify you are who you say you are and then the content will be removed, no further questions asked. Formal DMCA takedown notices are not necessary - a quick email is all that's required.

https://www.spriters-resource.com/contact/

They have a Discord, too, which makes this very accessible.

**Comment by Tormentor667** [comment]
![2021-02-22_190851](https://user-images.githubusercontent.com/10298439/108750532-6d2e3180-7541-11eb-81ec-e551c9aca315.jpg)

Issue resolved.

**Comment by madame-rachelle** [comment]
Perfect, @Tormentor667 . 😄👍
