### ISSUE TITLE
crosshair changes

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#394]
The crosshair changes now on -every- weapon -all the time- when pointing at an enemy, which is annoying.
Can someone change it or turn it off ?

![Screenshot_Doom_20210226_141238](https://user-images.githubusercontent.com/77861029/109305921-bc74aa80-783e-11eb-9424-7c377bdddc2b.png)

**Comment by AFADoomer** [comment]
Is this every enemy in every map, or just certain ones?

**Comment by MuadDib90** [comment]
AFAIK this is only happennig when pointing on enemies, that can "snipe" you ("in some way") - to deal you a considerable damage with one shot.
Typically enemies with Karabiner, Gewehr, or some Bosses like this one.
(It ~~should be~~ is controlled - the crosshair change - by the type of enemy you're pointing at, not the type of weapon you're holding.)

I am experiencing no such a behavior you described.

Could you please make sure it appears on every enemy (including dogs for example) as you described, or just in cases I mentioned above?

**Comment by x3003** [comment]
Yes, it's on every enemy incl. dogs. The closer they are, the bigger it gets.
Pointing at an enemy to snipe is a good thing, when you're having a sniper rifle. Now it also works with the luger, mp40 and gewehr 43 and so.

**Comment by AFADoomer** [comment]
This mechanic is intended to make hard-to-see enemies more visible to the player, regardless of what weapon they are holding.  The map author manually flags enemies that they want the cross hair to show up on.  In the map from your screenshot, you have disabled fog, so the crosshair is unnecessary, but for people playing the map as designed, those enemies are very hard to see.
