### ISSUE TITLE
Scrapped content

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#396]
We have had many feature ideas that did not make it into the final release for various reasons (style, design decisions, and simply lack of time because of more important tasks). I would like to compile a list of them here to post them in small news articles on the website closer to the release. They would be of great help to the community modders out there: just think of Tom Hall's Doom Bible.

Please post such ideas here (they can be anything: complicated scripted features, clever map tricks, bizarre gameplay mechanics, ...) The explanations do not have to be too detailed, the only requirement is that I should understand them :-) to write something about them and possibly add an outline of how they could possibly be implemented if we were at it.

**Comment by DoomJedi** [comment]
I wanted mutants to have leap melee attack with screen scratch, like in my "Eisenfaust Edition" series. It could just use a variant of rolling code.
Art was made, but Virg said it's too complicate to code in and would make mutant too dangerous.

**Comment by AFADoomer** [comment]
The player class contains inactive code that would allow the player to crouch and hold '+use' on dead bodies and pushable objects in order to drag/push/pull them around.  

The code actually works (search for "bool dodragging = false;" and set it to true), just doesn't take the objects mass or pushfactor into account when adjusting player movement, so everything moves around at full speed.

**Comment by AFADoomer** [comment]
The C3 secret map originally had a constant day/night cycle that would allow the player to have a daylight break from zombie spawning, with all of the zombies burning up in the sunlight.  

The status bar code to override the actual map time and display the "in-game" time is still in place; global ACS integer 60 (named 'time' in the BOALIB library) controls the time value set here - 0 or 1.0 is midnight, 0.25 is early morning, 0.5 is mid-day, etc.

**Comment by Talon1024** [comment]
> The C3 secret map originally had a constant day/night cycle that would allow the player to have a daylight break from zombie spawning, with all of the zombies burning up in the sunlight.
> 
> The status bar code to override the actual map time and display the "in-game" time is still in place; global ACS integer 60 (named 'time' in the BOALIB library) controls the time value set here - 0 or 1.0 is midnight, 0.25 is early morning, 0.5 is mid-day, etc.

There's a developer comment about that in the mission now.

**Comment by Username-N00b-is-not-available** [comment]
Very useful input, I need more of it :-)

@DoomJedi
> Art was made

Is the art currently in the repository? Could you please post it here, if not?

@AFADoomer

Why was the dragging commented out?

@Talon1024 
>There's a developer comment about that in the mission now

I would like to write myself detailed explanations for the features, and the devcomment margin is too narrow to contain them ;-)

Would the minigame have used the dragging mechanic AFADoomer mentioned, or there would have been a different implementation?

>but that was years ago

Well, that is exactly what I am hunting for, I've only been following the repository for around a year and know almost nothing about previous ideas.

**Comment by DoomJedi** [comment]
We actually planned to release scrapped art pack separately after BoA release.
But I now think Virg can add those into BoA, unused, just as we did with Rommel art (which is even coded but unused in maps?)

...Which reminds me of next note - Dean offered to add Rommel in, art was made, but Torm said Rommel is dead, historically, by the time of BoA events. Art was added and coded for future modders, but left unused.

**Comment by DoomJedi** [comment]
At one point we wanted to have a monk carrying the Bible...probably for some magic attack. Art was made, but never used.

At one point we wanted to add Castle Guardian, monster to protect castles, most enemy frames were made, but never used.

...already had scrapped art folder on DropBox, but now started adding more art to it. Those include Bible carrying monk, more variants of russian soldiers and other stuff.

**Comment by AFADoomer** [comment]
> @AFADoomer
> 
> Why was the dragging commented out?
> 

It's leftover code from an experiment that I never really intended to be in BoA.  

When I added the hold-to-use/repair script code to the mod, I pulled in my existing dragging code because I had already implemented custom crosshair graphic overlays as part of this dragging experiment, and needed similar code for the repair scripts.  

I just left the dragging code in there with the thought of - "Maybe we'll use this..."

**Comment by Ozymandias81** [comment]
During Chapter 2 development, I had this mutual idea with DoomJuan to build up a map locate on Venice, with a mission in a similar fashion-like of Indiana Jones and James Bond: fight through Canal Grande with boats and reach Piazza San Marco then head up to the church, something related to the plot should have been hidden there... There are commits present around which are about this idea, there are also some scrapped stuff and images present on out private dropbox folder.

I remember the problem with dragging bodies should have been to include HUD graphics, also to add another playism feature where people may get confused again (in fact if I am not wrong Dan said it was going to be "too much Thief" and I can't blame him there, even if I crazily love the game). Maybe with these leftovers modders will do something, if they'll notice it...

Concerning again scrapped content, there is the boss Erik which I am not sure i it has been used on C3M0 maps, DoomJuan idea to add the Phantom of the Opera playing in front of a organ (anims are there), until he should have disappeared in a smoke cloud and a fight should have started. More scrapped content can also be found on ZDoom Forums, where [I had a thread](https://forum.zdoom.org/viewtopic.php?f=37&t=51374&p=896036) about it but where at certain point decided to not update it due too much work ongoing.

**Comment by Ozymandias81** [comment]
Added link to "Venice"

**Comment by Username-N00b-is-not-available** [comment]
> Venice

Parts of that map are present in C1 release AFAIK, don't remember the number. This is interesting, what other locations were planned during development? @Tormentor667, do you remember anything?

> https://forum.zdoom.org/viewtopic.php?f=37&t=51374&p=896036

That should be really useful, thank you very much!

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Checked out the dragging feature, it is very cool! Great potential for stealth-related and puzzle missions.
Do you mind if I move the ```dodragging``` variable from the method to the ```BoAPlayer``` class itself, so it can be set to 'on' easily (otherwise a modder would have to subclass BoAPlayer and copy-paste the entire 250-line ```DoInteractions``` just to change one variable)?

**Comment by AFADoomer** [comment]
I don't mind at all.  

And yes, there are some issues since I never did anything to finish the feature 😁 .

**Comment by DoomJedi** [comment]
" DoomJuan idea to add the Phantom of the Opera playing in front of a organ"
I was sure it's coded in, this is a sad shock for me if it isn't. So much work was done on it.

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi
https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-787094641
> Erik is used on C3M0_A, though he does not play the organ.

**Comment by AFADoomer** [comment]
There is Duke3D-style "auto-stomp" code coded into the base class that is commented out.  This would make the player automatically look down and kick/stomp any +Base.CANSQUISH-flagged enemies, like rats and spiders, when the player runs into them.

**Comment by Tormentor667** [comment]
> There is Duke3D-style "auto-stomp" code coded into the base class that is commented out. This would make the player automatically look down and kick/stomp any +Base.CANSQUISH-flagged enemies, like rats and spiders, when the player runs into them.

I smell an addon here for the launcher...

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Sorry, I do not have time for new mutators anymore... I think the presence of this issue as a storage of information would already be of great use to modders. We can put a direct link to here on the website.
Closer to 30 April I will also post here archives with scrapped graphical content compiled from the Dropbox folder (sprites and sprite sheets), the ones that I had emailed you a month ago.

**Comment by Tormentor667** [comment]
No need to finish it until April 30th, we still can compile addons after the release

**Comment by Tormentor667** [comment]
From what has been mentioned here, what is worth an addon or a planned feature for 3.1?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Here is a summary of what has been done:

<details><summary>Current state of things</summary>

- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-786862874: done, implemented in behaviour.pk3 addon.
- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-786983636: mentioned on Editing Docs, "Dragging objects"; used in melee.pk3 addon.
- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-786985681: mentioned on Editing Docs, "Day-night cycle".
- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-787012251: nothing yet (about Transmission Received).
- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-787036771: the scrapped art pack is done, nothing done about Rommel.
- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-787059254: the scrapped art pack is done.
- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-787093719: nothing yet, neither for Venice (except the old map version by Ozymandias81, of course), nor for adding exisitng organ playing animation to Erik in C3M0_A.
- https://github.com/Realm667/WolfenDoom/issues/396#issuecomment-813108142: mentioned on Editing Docs, "Auto-Stomp".

</details>

I'd personally add auto-stomp to 3.1 and release Venice as a bonus map (though I am not sure who would do the additional map design), but this is just my opinion, all of these suggestions are valid and worthy and could be used for addons.

**Comment by AFADoomer** [comment]
One more unused item:
![](https://memegenerator.net/img/instances/31221579/sharks-with-frickin-laser-beams.jpg)

The LaserShark actor isn't used anywhere that I know of.

**Comment by Tormentor667** [comment]
> One more unused item:
> ![](https://camo.githubusercontent.com/8d1e25c3adc859b3effb012908cd52645c3769128cb931a97026cf5857f86ffb/68747470733a2f2f6d656d6567656e657261746f722e6e65742f696d672f696e7374616e6365732f33313232313537392f736861726b732d776974682d667269636b696e2d6c617365722d6265616d732e6a7067)
> 
> The LaserShark actor isn't used anywhere that I know of.

Correct

**Comment by Ozymandias81** [comment]
I had an idea to use them somewhere, maybe a new area on Feuerdrone with swimming frickin' laser sharks? Or some sort of pool to add on New Berlin city?

**Comment by Tormentor667** [comment]
No additional content for the primary release. This could be an addon as well - additional monsters for example

**Comment by AFADoomer** [comment]
There's a Scuba tank pickup that was minimally functional in the 3.0 release. I recently fleshed it out to be more useful - it's now toggleable, has a hud overlay, and increases your speed while swimming (at cost of decreasing speed while you are out of the water).

**Comment by Tormentor667** [comment]
I will add the new scuba gear to a few maps where appropriate.

**Comment by Username-N00b-is-not-available** [comment]
Is ```ZyklonResistance``` used in any of the maps? @AFADoomer, could you please add it to an 'unofficial' secret place in C3M0_A (not mark it is as secret), possibly behind a puzzle as you originally intended?

**Comment by Tormentor667** [comment]
Various "scrapped" material has been added now as addons or part of the main game:

- Leaping Mutants
- Pulling dead bodies out of the way
- Scuba Tank (has been added to use for C1)

Some of it is still there as resource (ingame or dropbox) or code but not usable:

- Day/Night Cycle in C3M0_A
- Monk carrying a bible (dropbox)
- Russian Soldier variants (Winter, dropbox)
- Castle Guardian monster (dropbox)
- Autostomp feature (duke3d-like) for critters
- LaserShark monster

I think it's good to have the info here, but for now I'd simply close this, as I don't see additional potential for addons right now. We can stll add the additional monsters to the game resources for other modders. For the "autostomp feature", I'd open a new issue.

**Comment by DoomJedi** [comment]
AFAIR we also had scrapped Rommel Boss.

**Comment by Tormentor667** [comment]
Are the sprites done?

**Comment by DoomJedi** [comment]
Afaik yes. You know why he went unused.

**Comment by Tormentor667** [comment]
I do, but I don’t know anymore if he was only sprited or also coded

**Comment by DoomJedi** [comment]
I remember it being coded. But should be an easy check for people.

**Comment by Ozymandias81** [comment]
It has been coded and I thought it was been used... but doesn't seem so. We can keep it anyway, some effort has been put for his sounds afaik, am I right too?
