### ISSUE TITLE
Can't get on the sub in C2M6_B

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#397]
When I'm handing over the papers to the guard, next to the sub everything seems ok. But when you wanna get on, the disguise falls away and they shoot you.

![Screenshot_Doom_20210227_021521](https://user-images.githubusercontent.com/77861029/109371011-2757cd00-78a3-11eb-9f48-c4879a31e628.png)

**Comment by AFADoomer** [comment]
I can't reproduce this.

**Comment by Talon1024** [comment]
It's possible he killed some enemies in a completely different area of the map, and someone else was alerted by the corpses, forcing everyone to recognize and shoot at BJ.

**Comment by x3003** [comment]
Ofcourse I killed some enemies. Where's the fun not killing them ?!
 But I make sure no one else gets alerted, and destroy the alert buttons. If you see the grey bar, it means it's ok I can walk around freely and no one is shooting at me.
But the moment I step over the grey area on the left of the pic (or the water), the disguise falls away.
So I have some more killing to do, also in the sub, before joining Douglas....

**Comment by x3003** [comment]
A test file. When I step forward, the disguise is gone. When I step back the disguise is back.

[save6.zip](https://github.com/Realm667/WolfenDoom/files/6054430/save6.zip)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Please tell us the BoA commit and the GZDoom version you have been using. If there were any additional mods loaded. please list them as well. We won't be able to load your savegame otherwise...

**Comment by x3003** [comment]
The git version was from 25/02 and gzdoom-x64-g4.6pre-114-g387abf81a with freedoom and widescreen / fullscreen.
No other mods used.
