### ISSUE TITLE
Mission objective shown too fast

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#398]
When you do get on the sub in C2M6_B....
There's 1 spot on the deck that makes you get 'Objective accomplished' -before- you get in the sub and find douglas.
Seems the game doesn't sees the right height here.

![Screenshot_Doom_20210227_004328](https://user-images.githubusercontent.com/77861029/109371248-5cb0ea80-78a4-11eb-8b14-8c16db637939.png)

**Comment by Tormentor667** [comment]
@Talon1024 can you apply the same fix here as in fe6ead9bdf5ee0939d36ea42c1679a4b8744479f ?
