### ISSUE TITLE
Sign is wrong

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#399]
On C2M6_C this sign is wrong.
It says: 'eingang verboten', but I think it should say "eintritt verboten'.

![Screenshot_Doom_20210227_151629](https://user-images.githubusercontent.com/77861029/109390064-b995ba80-790f-11eb-8a02-1255d55dd597.png)

**Comment by Username-N00b-is-not-available** [comment]
Well, I don't know German, but to me it seems that Eingang and Eintritt are synonyms. @Tormentor667, what do you think?
I can found a lot of signs with 'Eingang verboten' sold on auctions, e. g. this one: https://www.proxibid.com/Firearms-Military-Artifacts/Military-Artifacts/German-Sign-Eingang-Verboten-Entrance-Forbidden-Metal-13-quot-x-29-quot-High/lotInformation/29848837

**Comment by x3003** [comment]
Well, to me, 'eingang' is the entrance itself. So you forbid the entrance to be itself.
With 'eintritt' you forbid going someone through it.

https://www.linguee.de/deutsch-englisch/uebersetzung/eintritt+verboten.html

Look at a)

**Comment by Tormentor667** [comment]
@x3003 is perfectly right, I fixed it.
