### ISSUE TITLE
Kill surrendering scientists

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#400]
I think the player should still be able to kill surrendering scientists and mechanics (it's okay to not kill medics thoug). It's quite unintuitive not to do this, especially in C3M1_A or other stealth missions. I mean, you leave them alive for what? So they can flee as soon as you are gone and tell the SS that you are here? Well, they actually don't do that but in this mission it feels like "How dumb is it to leave this scientist alive here?"

![2021-02-27_171831](https://user-images.githubusercontent.com/10298439/109393044-e0f48380-791f-11eb-9003-362c4a40f9e2.jpg)

**Comment by Username-N00b-is-not-available** [comment]
...or somehow make them not surrender on these maps...

**Comment by Tormentor667** [comment]
Thanks for taking care
