### ISSUE TITLE
Boulder issue in C3M0_A

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#401]
The boulders somehow get up to these sectors and continue playing their rolling sound infinitely.

![Screenshot_BoA_20210228_152638](https://user-images.githubusercontent.com/10298439/109421870-6b4cee00-79d9-11eb-9ab2-40fcc95a1b41.png)

**UPDATE**
The same issue happens in the supersecret area in C3M6_B where the boulders should fall into the pit in the Realms of Arkania dungeon. In the same area, the boulders that are stopped by a wall, still play their active sound.

**UPDATE2**
Also happens in C3M6_C

![2021-03-07_164903](https://user-images.githubusercontent.com/10298439/110245807-0b1ff400-7f65-11eb-9512-0814c10122be.jpg)

**Comment by Username-N00b-is-not-available** [comment]
Also noticed this some commits ago.

**Comment by AFADoomer** [comment]
Need to change them back to bouncing boulders, I think.  The floorhugger boulders do this, and ignore maxstepheight.

**Comment by Username-N00b-is-not-available** [comment]
Any updates on the state of this @Tormentor667? Do the boulders work properly now in C3M0_A, M6_B and _C?

**Comment by Tormentor667** [comment]
Just tried C3M0_A and the issue still exists, I guess @AFADoomer didn't have time yet so I am summing him as by request :)

**Comment by Username-N00b-is-not-available** [comment]
Closing the issue after @AFADoomer's commit.
