### ISSUE TITLE
C3M5_C - game mechanics that noone thought about

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#402]
I admit I found it by accident...

You can hand over the papers to the already alerted guard and the path will open.
You can even hand over the papers to his corpse, and the path will still open.
Other thing confuses me: Until you hand over the papers, you should have them in stock on the right of your HUD, haven't you?

![Clipboard01](https://user-images.githubusercontent.com/73436978/109422955-ef08d980-79dd-11eb-99fe-702e1d712a95.png)

**Comment by Username-N00b-is-not-available** [comment]
Oops, it seems this problem has popped up again after almost half a year... @Ozymandias81 had already fixed it once in https://github.com/Realm667/WolfenDoom/commit/3a2eb728c62ad1e8641d23d99cc4784a1e5150dc, yet here we are...
As for the stock, it would of course make sense, but then you won't be able to play the level from 'pistol start'... Presence of the papers in the inventory should be ensured at the beginning of the map (i. e. if there is none, add them via scripts), like I've done with C1M6 ArtifactEgyptian. Also we need the player to have 10 C4's in C2M5_B to blow up things, ...

**Comment by MuadDib90** [comment]
Well, I don't think I am able to help you here anyhow at this point.

**Comment by Username-N00b-is-not-available** [comment]
The information is already a huge help, thank you @MuadDib90!
I have a suspicion that Ozymandias just disallowed showing the Kennkarte when the player has no SS uniform on.
