### ISSUE TITLE
Nemesis fight in C3M0_A

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#403]
I am not sure if it is meant that way but Nemesis appeared when I finished of the final remaining nazis in the basement where the armory with all the weapons is. It's quite impossible to survive this battle there. 

Can we change it that Nemesis appears not after killing the last remaining Nazi but instead as soon as you try to leave the ss headquarer, so you can fight him outside @Talon1024

**Comment by Username-N00b-is-not-available** [comment]
How's the basement BTW @Tormentor667?

**Comment by Tormentor667** [comment]
Very good, I like it :)

**Comment by Talon1024** [comment]
Perhaps we should add a new sector property "user_blocknemesis" to prevent Nemesis from reappearing in a particular sector

**Comment by Tormentor667** [comment]
Yes that would be a good idea as well.

**Comment by Tormentor667** [comment]
Have you already added that sector property to the corresponding sectors in C3M0_A?

**Comment by Tormentor667** [comment]
Just a reminder @Talon1024

**Comment by Username-N00b-is-not-available** [comment]
Now that Talon1024 added the property to the sectors, can we close this @Tormentor667?

**Comment by Tormentor667** [comment]
I think so :)
