### ISSUE TITLE
Objective wrong ?

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#404]
In C2M6_B, one of the secondary items you have to grab is the 'totale macht'. Nice, but you can buy it from the shop -before- this mission. So why is this ?

**Comment by Username-N00b-is-not-available** [comment]
@x3003 You can also find it in the mission. Same with the adrenaline on C2M6_C. I think it just serves a demonstrative purpose for players who spent their gold on other items and have not used the item yet.
Also if you had bought a Totale Macht from the shop, you can afford to use one in C2M6_A or _B and still bring one to the boss fight. A Totale Macht would come in handy in C2M5_B, for example, so I don't think it would be good to remove it from the shop.

**Comment by x3003** [comment]
Well, the first time that i've played it I was surprised that I couldn't get the objective. When playing the level again, I noticed I already bought the item (but didn't use it).
And yes, it comes in handy later on in C2M6_C, but that's why you have the objective. Esp. new players won't buy it, coz it costs a lot and they don't know what it does.
