### ISSUE TITLE
Low-Health effect in C3 not working

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#405]
After finishing C3M1, I noticed that the "low health screen effect" isn't working if you continue playing Chapter 3. I guess that a token from C3M1 isn't removed at the right moment or at all, so it stops the effect from happening in other maps after C3M1.

**Comment by Talon1024** [comment]
I just loaded up a saved game I had from my Chapter 3 playthrough (at Allied HQ), stood in front of a wall, and summoned a bunch of rockets, and the low health effect was working for me.

**Comment by Tormentor667** [comment]
I guess you need to play chapter 3 including the intro.

**Comment by Tormentor667** [comment]
Still playing, in the meantime at C3M3_B and the low-health effect is still not working. I am pretty sure it gets taken in the C3INTRO or C3M1_A map and never given back again.

**Comment by Talon1024** [comment]
Can you please enter "printinv" and "screenshot" in the console, and upload the screenshot here?

**Comment by Tormentor667** [comment]
![Screenshot_BoA_20210304_174943](https://user-images.githubusercontent.com/10298439/109998993-1202f880-7d12-11eb-97b3-05559ae440e0.png)
![Screenshot_BoA_20210304_174950](https://user-images.githubusercontent.com/10298439/109999003-14fde900-7d12-11eb-9acc-7010e11baae3.png)
![Screenshot_BoA_20210304_174952](https://user-images.githubusercontent.com/10298439/109999010-17604300-7d12-11eb-8506-e77aa085a980.png)
![Screenshot_BoA_20210304_174957](https://user-images.githubusercontent.com/10298439/109999025-19c29d00-7d12-11eb-9432-33d471b2f77d.png)

In case it is still needed.
