### ISSUE TITLE
Returning from C3M0_A reactivates exclamation marks above all actors

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#406]
After returning from C3M0_A, all exclamation marks above the npcs get reactivated again even if you read (deactivated) them before joining the C3M0_A mission. The only active exclamation mark should be above AFA, because he has a new dialogue. The others shouldn't be reactivated.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Has https://github.com/Realm667/WolfenDoom/commit/9acace797d976101c5c146896167902dccdee803 fixed the issue?

**Comment by Tormentor667** [comment]
@Username-N00b-is-not-available I will try that this evening

**Comment by AFADoomer** [comment]
Is this resolved or not?  I though that @Talon1024's fixes took care of this problem?

**Comment by Tormentor667** [comment]
@AFADoomer @Talon1024 I just tested it by playing Chapter 3 from the beginning including C3M1 and C3M0_A. Unfortunately, all the exclamation marks that I already read after C3M1 are active again after playing C3M0_A.

**Comment by Talon1024** [comment]
*All of them*, including Juliette, Randi Heit, and Prof. Gutenberg? I just did a quick test with the debug mode and `changemap`, and it seems to be working properly for me. Some of them are supposed to be lit up, including Gen. Miller, the mission stats board, Lt. Halderman (if you're not at max health), and the SNES (if you have a cartridge).

**Comment by DoomJedi** [comment]
It's NES if im not mistaken....

**Comment by Tormentor667** [comment]
All of them in my current testing with today’s build. I played C3M1, got to the intermap, met all NPCs, played C3M0_A, returned to the intermap and all of them that are lit up after C3M1 are back on after C3M0_A

**Comment by Talon1024** [comment]
Ugh, I have no idea what's happening on your end, but [this is what I get](http://www.ciinet.org/kevin/myimages2/doom/wolf_boa/regenschirm.mp4) with the latest build (video).

I assume your BoA build is up to date with the latest GitHub changes? On the other hand, I just load BoA as a PWAD directly from the development folder.

**Comment by Tormentor667** [comment]
I am up to date - same with GZDoom - and I am using it as a PWAD as well. This is extremely strange.

**Comment by Tormentor667** [comment]
Update, my fault, I was playing it as IPK3, not as PWAD

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Related to @Talon1024's video: please remove the INTERMAP greetings sounds on Stierlitz. They are only meant for Volkoff. Stierlitz should stay silent.

**Comment by Tormentor667** [comment]
@Username-N00b-is-not-available just took care of that issue.

**Comment by Talon1024** [comment]
Well, here are some obligatory before/after screenshots...

Before:
![Screenshot_Doom_20210328_041059](https://user-images.githubusercontent.com/6550500/112748255-9995fd00-8f88-11eb-9db1-5220adff3de6.png)
After:
![Screenshot_Doom_20210328_053226](https://user-images.githubusercontent.com/6550500/112748257-9ef34780-8f88-11eb-9478-a285c966757b.png)

**Comment by Tormentor667** [comment]
This is certainly strange. I just hope that your test is simply the way it actually works - and not my test :D

**Comment by Talon1024** [comment]
The only thing I can think of (now) which could cause your issues is your BoA IPK3 being outdated.

**Comment by Tormentor667** [comment]
Well, I did build a new file after updating from the repo - that’s what I usually do lately when playtesting. I can give it another try this weekend.

Just for the record: How is this controlled or programmed not to reappear?

**Comment by Talon1024** [comment]
There's a `special_dialogue` variable in the INTERMAP ACS scripts, and if it isn't 0, the "special" dialogues will be activated instead of the dialogues that usually get activated. `special_dialogue` is set to 0 again every time the player returns to HQ.

`special_dialogue` is set whenever the player goes on a secret mission, or when the player activates James Ryan's mission (Operation: Raubgold/C3M0_B).

**Comment by Tormentor667** [comment]
Is someone else able to reproduce this issue or does it work everyone else other than me?

**Comment by Tormentor667** [comment]
> `special_dialogue` is set whenever the player goes on a secret mission, or when the player activates James Ryan's mission (Operation: Raubgold/C3M0_B).

I had a suspicion of what I did wrong when testing, so I retried it without rudimentary cheating and guess what: it works.
