### ISSUE TITLE
C3M4 zombie invasion is by far too easy

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#408]
I am not sure what has been changed (if it is script- or map-wise) but the difficulty (played it on the middle skill) is by far too easy when it comes the zombie invasion city. There are too few zombies alive, and only normal zombies, no Braineaters or Nazi Officers get spawned, instead we only have the white naked ones and a few dogs. The map as it is now, is no real treat. Even the bosses at the end are an easy task if there is not enough cannon-fodder around.

I'm pointing @Talon1024 and @AFADoomer towards this, maybe something is bugged - or has been changed - or do I have to change the map somehow? It definitely needs to be harder, more of a challenge in the last 90 seconds where you feel overrun.

**Comment by Talon1024** [comment]
I just did [this](https://github.com/Realm667/WolfenDoom/commit/848860df0882aebffc9cf434a0aafc53ffcf335f). Hopefully, it's better than before.

**Comment by Talon1024** [comment]
The actor spawners treat the arg1 value as a global value for maximum total spawns for all spawners with their specific TID. I tried adding a more aggressive variant of the actor spawner, which ignores the spawns from spawners with the same TID, and I ended up with this:
![Screenshot_Doom_20210304_160532](https://user-images.githubusercontent.com/6550500/110030639-fc86d200-7d03-11eb-8437-2e15ed3094f9.png)
![Screenshot_Doom_20210304_160355](https://user-images.githubusercontent.com/6550500/110030630-fabd0e80-7d03-11eb-9061-fa7ccc6ca500.png)
![Screenshot_Doom_20210304_160416](https://user-images.githubusercontent.com/6550500/110030633-fb55a500-7d03-11eb-8e85-263f1613502a.png)
![Screenshot_Doom_20210304_160509](https://user-images.githubusercontent.com/6550500/110030636-fbee3b80-7d03-11eb-9671-1f2ad60f82a3.png)

**Comment by Talon1024** [comment]
And with [these changes](5dcf5ca9c304e836fcb6a2f2a175fc3014b961d9), I get:
![Screenshot_Doom_20210304_165253](https://user-images.githubusercontent.com/6550500/110035840-2a6f1500-7d0a-11eb-8954-ac9679682445.png)
![Screenshot_Doom_20210304_164916](https://user-images.githubusercontent.com/6550500/110035834-293de800-7d0a-11eb-9284-d8dc87ff59a6.png)
![Screenshot_Doom_20210304_165117](https://user-images.githubusercontent.com/6550500/110035838-29d67e80-7d0a-11eb-8900-04e6ac1a2d88.png)

**Comment by Tormentor667** [comment]
I will do another test as soon as I am done with my current playthrough, but it looks much better according to the screenshots, so thanks for that for now. Details later after my testing.

**Comment by Tormentor667** [comment]
Did two more testings today and everythng is good after @Talon1024 's changes except the Kamikaze Zombies, they make the battle too "random" - if you are unlucky, one appears next to you and you are dead. Can you remove the Kamikaze spawners completely? Other than that it's well balanced.
