### ISSUE TITLE
First cvar type with cheat defined isn't recognized by UDBuilder

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#409]
As the title says, if you open anything with UDBuilder you'll notice that a warning will pop up regarding an uknown cvar, because it is defined in this case as a multiple type (server, cheat and float), but if you get rid of the cheat one, the one that doesn't get recognized is line 56. This makes me think that testing via UDBuilder is compromised this way, because I fear that all other subequent cvars are not loaded or applied properly at all... Maybe. Something to point out to UDBuilder repository?

![C3M1_A at 2021 03 04 18-15-10 711  R3714](https://user-images.githubusercontent.com/11136108/110002814-19c49c00-7d16-11eb-978e-559a388422eb.jpg)

**Comment by Username-N00b-is-not-available** [comment]
>I fear that all other subequent cvars are not loaded or applied properly at all

@Ozymandias81 How so? The only thing UDB does is launch the executable with a parameter string, and the player's .ini is loaded from the GZDoom folder as by default.
That said, it would be good to let the UDB team know about this GZDoom feature they have unimplemented.

**Comment by Ozymandias81** [comment]
Right, I thought it was like that because I have been a long time far from these things, and also becuase sometimes I noticed issues happening only when testing from UDB rather than on GZDoom directly. Gonna close this and point that to Jewalky.

**Comment by Ozymandias81** [comment]
[Here](https://github.com/jewalky/UltimateDoomBuilder/issues/535) we go.
