### ISSUE TITLE
Secret area too obvious

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#414]
In C1M1, this secret area should be a bit more covered up else, why it's a secret area if anyone can see it so easily ?!

![Screenshot_Doom_20210306_151643](https://user-images.githubusercontent.com/77861029/110211852-c595f500-7e98-11eb-9347-86e54f1cc6d1.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 This particular one does not stand out too much IMO, especially considering the C1M2 shovel secret and countless gold in vents. This one's just free gold labeled as a secret.
It's literally the first level in the game, we'll have more complicated secrets later on :-)

**Comment by Ozymandias81** [comment]
Yes as n00b said that's why, it is the first level so this won't change. Needs to be easy and too many people familiarized with it too.
