### ISSUE TITLE
Objective goals too long in translations

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#415]
The title is self-explaining. I added an additional graphic though a few weeks ago called "objectgy" that can be used instead. It hasn't been coded though. I think this might be a job for @Talon1024 or @AFADoomer 

![2021-03-06_163624](https://user-images.githubusercontent.com/10298439/110212123-3093fb80-7e9a-11eb-8b0d-769edc273a27.jpg)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Do you want to code it in separately, based on the text length? This would overcomplicate things IMO, I suggest to just replace the objectgx with it, it probably won't look too bad.
Word wrap with ```SetHudSize``` on these messages would also be nice to have, just in case some message cannot be reduced to a short one...

**Comment by MuadDib90** [comment]
Didn't you add a wider version of this frame for objectives, so, iirc expecially German and Italian, languages can fit in?
It should be in the repository, maybe noone code it in yet?

**Comment by Tormentor667** [comment]
I'd suggest using the wider version in all languages other than enu

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Why not for ```enu``` itself, too, could you please explain it?

**Comment by Talon1024** [comment]
Fixed in 5463a782f66920a129344d2c52d7d37a53e04cdf

**Comment by Tormentor667** [comment]
> 
> 
> @Tormentor667 Why not for `enu` itself, too, could you please explain it?

Because it already fits perfect well. With the new gfx we simply have too much empty space on the right.
