### ISSUE TITLE
C3M5_C - Escape sequence parachute is not moving with the player

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#418]
When escaping at the very end of the map, the opened parachute model stands in the air and is not moving downwards with the player.

**Comment by AFADoomer** [comment]
Again, I thought this was fixed a while ago...  

The parachute is intended to stay where it is.  The map script also sets the player to FLY (See line 408 of the map's ACS script), so the player stays with the parachute.

**Comment by Talon1024** [comment]
In that case, you'll also need to set the player's Z velocity to 0.

**Comment by Tormentor667** [comment]
Then something is not working. The player moves downwards and is far away from the parachute, the parachute stays where it is though.

**Comment by AFADoomer** [comment]
Do you get the same problem with a53abe377fcecf5af860d800f979f9bfbef205d1?

No changes other than that I added a debug script to set up the exit and open the door - 'pukename TestEscape' in the console, then jump out of the door.  If that works properly, then there's some interaction being triggered elsewhere in the map that is causing the problem.

**Comment by Tormentor667** [comment]
That way it works perfectly fine. I will do a test-run later from the beginning to the end of the map and see if it still works. Could it be that it has something to do with the tilting?

**Comment by Tormentor667** [comment]
Update: Played it from the beginning to the end and after jumping out of the door, it still moves the player downwards away from the parachute. Pretty sure it has something to do with the tilting.

**Comment by Talon1024** [comment]
It does seem to be the tilting which is causing this bug, since I was able to reproduce it by entering this in the console:
    pukename settilt 15 0
    pukename TestEscape
and then running out of the door
