### ISSUE TITLE
C3M6_B: Final battle arena skybox not centered

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#424]
I noticed that the final battle arena's sky effect (this "zyklon tornado skybox") is not centered at the middle of the arena but pretty much off. I am not sure what's going on here as the skybox is set up right and it should perfectly fit. Maybe someone can take a closer look.

![2021-03-07_165850](https://user-images.githubusercontent.com/10298439/110246139-a6659900-7f66-11eb-8912-400d05ed11c6.jpg)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Has @AFADoomer's commit fixed the issue?

**Comment by Tormentor667** [comment]
Works perfectly now!
