### ISSUE TITLE
C3M6_B: Boss battle adjustments

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#425]
I have a few suggestions after playing the boss battles in the final arena.

**Zyklon Ryan**
- Make him use his flame attack more often (+50% of what it has now)
- Make him spawn 150% as many dogs as of now

**Zyklon Smoke**
- Double its health
- Reduce the damage of his projectiles to about 50% of what it is now

**Zyklon Gargoyle**
- Give him about 150% of health of what he has now

**Comment by Talon1024** [comment]
> **Zyklon ~~Gargoyle~~ Angel of Death**
> 
> * Give him about 150% of health of what he has now

Why? I think the Angel of Death fight on C3M6_B is good enough as is.

**Comment by Tormentor667** [comment]
With 1800 souls in my inventory, I beat him pretty fast. Maybe it's just me though. It's not a "must have", it was just my personal experience. What do others think about the difficulty?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 +150% is too much IMO, but 50% could work. Same for the Zyklon Smoke Monster.
I agree with other suggestions.

**Comment by Tormentor667** [comment]
That’s what I meant with 150% - not add but make 150% out of 100% :)

**Comment by x3003** [comment]
What if you don't have 1800 souls ? Is he still so easy to beat then ?

**Comment by Tormentor667** [comment]
The question is: What is the average number of souls until you get to the final battle arena?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667, what do you think on the current state of things here, after https://github.com/Realm667/WolfenDoom/commit/f48e2db548804a9f495f6ba343d3c2fcfe48b820?

**Comment by Tormentor667** [comment]
I will do a test play this evening, after that I can say more.

**Comment by Tormentor667** [comment]
Did a new playthrough just now and this is what I noticed.

**Zyklon Gargoyle**

- His primary attack (the zaps) is almost insta-kill (playing on default skill 2), I had 150 health, 100 armor and 3-4 hits from his attack killed me. The damage of these should be reduced by about 50%
- The enemy drops 1200 souls when being killed (runes), this is definitely too much, as I only needed about 150-200 souls to kill him. I'd suggest reducing this to 100-200 souls when being killed

**Zombie Ryan**

- I'd suggest spawning zombie shephards during the battle (2 of them each 30 seconds until Ryan is dead) to spice things a bit more up and make the player have to move quickly, otherwise he's no treat. Other than that perfect.

**Zyklon Smoke Monster**

- I'd suggest some more health, maybe +25%, and make him drop 100 souls upon death. Other than that, perfect.

**Hitler** 

- He's a challenge bit in my eyes the fight is perfect, nothing to change here.
----------------------

So the main thing that needs to be taken care of is the Zyklon Gargoyle, everything else is ready to go. What do the others think?

**Comment by Ozymandias81** [comment]
Improved Zyklon gargoyle and Zombie Ryan battle with dogs

**Comment by Tormentor667** [comment]
I don't get it why but the Zyklon Gargoyle still drops 4 Runes instead of 1 even though the code only drops one:
`[..]
DamageFactor "Fire", 0
DamageFactor "OccultFire", 2.0
Species "Zombie"
DropItem "Rune_Gibor" 255
States[..]`
Maybe something different is wrong here? @AFADoomer @Talon1024 @Ozymandias81

**Comment by Blue-Shadow** [comment]
> I don't get it why but the Zyklon Gargoyle still drops 4 Runes instead of 1 even though the code only drops one

At the end of its Death state sequence, [A_Fall](https://zdoom.org/wiki/A_NoBlocking) is repeatedly called until it hits the floor, whereupon it enters the Crash state sequence. A_Fall is responsible for spawning the drop items.

**Comment by Tormentor667** [comment]
Thanks for the explanation :)
