### ISSUE TITLE
Die after level complete

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#427]
In C1M5, when you for example didn't go in the restaurant area of the hotel previously, you can still die when the mission is complete when going there afterwards. The text says '....ze Nazis are retreating.....' Eh, no, they're not.
 Why go there ? Maybe.... to get some wine to celebrate with Juliette ;)

![Screenshot_Doom_20210309_222108](https://user-images.githubusercontent.com/77861029/110540315-a3b1a200-8126-11eb-86d5-844a6c16d786.png)

**Comment by Talon1024** [comment]
Perhaps enemies in those areas should be moved outside when the final battle begins?

**Comment by x3003** [comment]
Perhaps they could be added in another batch ?

**Comment by Tormentor667** [comment]
Fixed
