### ISSUE TITLE
No direction shown after objectives complete

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#428]
In C1M3 when you complete every objectives, there's no direction shown on the compass were to find Douglas, unless you're almost on top of him. So it's pretty useless.

![Screenshot_Doom_20210307_163340](https://user-images.githubusercontent.com/77861029/110542030-d8bef400-8128-11eb-829a-085a2541b167.png)

**Comment by Talon1024** [comment]
Good point... C1M1 has a red exclamation mark at Douglas' position, which appears when you open the gates.

**Comment by Tormentor667** [comment]
@Ozymandias81 @Talon1024 can you take
