### ISSUE TITLE
Sniper distance too short

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#430]
In C1M0, the sniper [in the distance] on the other side of the bridge can hit you from were i'm standing in the pic, but you can't hit him. The shot always goes too low. Checked it against the release version [c2], but there it works as expected.
You can only hit him -after- the bridge.

![Screenshot_Doom_20210311_233239](https://user-images.githubusercontent.com/77861029/110865702-4d7a6580-82c4-11eb-862c-ecb75439bc62.png)

**Comment by Talon1024** [comment]
@AFADoomer and @Username-N00b-is-not-available added bullet drop for Chapter 3, which is why your shots are hitting too low.

I was able to hit him from closer to the bridge, if I aim above his head.

**Comment by x3003** [comment]
>I was able to hit him from closer to the bridge from that side, if I aim above his head.

Then the sniper on the other side should have the same problem and not always deliver a perfect shot.

**Comment by x3003** [comment]
Thx
