### ISSUE TITLE
Volkoff dialogue sounds

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#432]
@DoomJedi has recently added some dialogue phrases for Volkoff into the folder. I do not currently have proper access to the GitHub repository from my machine, @Tormentor667 @Ozymandias81 @Talon1024 could you please convert the following files and add them to the game?
```Greetings (exact - Wish you health, common russian army phrasing), Captain Blazkowitz (alternative version).wav```
```O, Captain.wav```
```Greetings (exact - Wish you health, common russian army phrasing).wav```
```Greetings (exact - Wish you health, common russian army phrasing), Captain (formal phrasing).wav```
Please make sure that these are only used **in the beginning** of the dialogues, as they are greetings phrases (this should also apply to all other NPCs on the maps, but oh well...)

**Comment by DoomJedi** [comment]
First one was more accurately renamed to
Greetings (exact - Wish you health, common russian army phrasing) (alternative version)

**Comment by Ozymandias81** [comment]
These have been already implemented codewise by me some commits ago, one now needs to add them mapwise on INTERMAP.

**Comment by Tormentor667** [comment]
Can you tell me the 'sndinfo.txt' lumps? I will add them to the INTERMAP dialogues, the C3M0_B dialogues and the C3M5_A dialogues.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 It's ```urss/greet```, it will play a random sound out of three ones (they are interchangeable). Please remember that these phrases will make no sense in between dialogue responses, they should be played before the first line :-)

**Comment by Tormentor667** [comment]
Just did it :)
