### ISSUE TITLE
No distance icon on undead

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#433]
When using the knife, there's a [right] distance icon for nazis shown, but not for the undead. Intentional ?

![Screenshot_Doom_20210313_232443](https://user-images.githubusercontent.com/77861029/111052129-ab3fb680-8458-11eb-9920-34bfa1ccd292.png)

**Comment by Talon1024** [comment]
That one was alerted, so you won't see a "distance icon" when you get close to him, and you also won't get a one-hit kill.
