### ISSUE TITLE
c4 pack missing

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#434]
In C3M0_A,  there are 3 cracks where you can put c4 to blow it open, but there are only 2 c4 packs found (in 2 of the cracks).
The 3rd pack is nowhere to be found, so maybe someone can put a clue in the compass where to find that c4 pack.

**Comment by Talon1024** [comment]
If you use the gem in the wall of the torture chambers, you'll find 3 C4 packages somewhere in the cave that opened up

**Comment by x3003** [comment]
Then you first have to get the gem (from the statue I guess). And that's not easy....

**Comment by Talon1024** [comment]
You have to push the statue off the ledge to retrieve the gem.

**Comment by x3003** [comment]
How do I (or anyone else) suppost to know that ? You didn't leave a clue.

**Comment by Tormentor667** [comment]
Well, this mission is some kind of a "puzzle mission" and you will encounter a lot of things that you need to find out. Actually there have been quite a few situations where you had to "push" objects (like crates) before reaching C3M0_A so it's not like the player has no idea he can actually to this.

You get the info about the statue and the gem, and if you find it, you have various options to try: Shoot it, search for a switch, or see the ledge and push it over :)
