### ISSUE TITLE
Time too short

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#435]
In C1M0, when you have to clean out the main building, you only get 25 mins to do it in.
For me that's just a bit too short. I know the level a bit, not playing blind or anything like it, but still come up too short.
The first floor I do in about 10 mins, the second in about 8, which leaves me with only 7 mins for the last one, which is a hard one.
Would be nice to get a few mins more. So maybe 30 mins total time would be nice.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 This interval had already been raised <strike>four score and seven years ago</strike> during the development of Chapter 3: https://github.com/Realm667/WolfenDoom/commit/7a17cfebc401aeadd4fcb700ef0731c27a36767e. BTW, the player does not die instantly after the time passes, you are damaged every few seconds instead, and still can escape during that time.
Were you able to deal with the area successfully?

**Comment by DoomJedi** [comment]
Based on latest youtube video, at least time of original release was way too short, especially for blind play.

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi Which video?

**Comment by DoomJedi** [comment]
https://www.youtube.com/watch?v=1FDdPDOyJdI

**Comment by Username-N00b-is-not-available** [comment]
Well, I wouldn't call the original time '**way** too short', and it had already been raised by 5 minutes since the version on the video.
At one point he says "I just think I screwed myself, I may have to restart this mission", and he's correct. For some reason he went out of the facility when clearly hinted not to do that, and also ruined his savegames multiple times. Though I bet he won't have such substantial problems with the level next time.
It looks like E3 will come just in time for BMD to play (or a bit earlier :-) )

**Comment by x3003** [comment]
I **didn't** based my request on a video, I played it myself and always come up short.... help....

>Were you able to deal with the area successfully?

If I go into god mode (because of the flying debris), yes else no.

**Comment by Tormentor667** [comment]
When playing it myself, I had about 8 minutes left and I went straight through the map on the middle skill setting. What skill setting did you play this and how much additional time would you have needed? Just for getting a feeling.

**Comment by x3003** [comment]
I play at the lowest level (ofcourse). I'm also not a youtuber nor hardcore wolfenstein player. I would need some 5 mins more. 
The first floor w/ all the damn zombies takes about 10 mins already, so that doesn't leave me a lot for the next 2 floors.  
And that boss in the end is pretty hard you know, wasting minutes there too.

**Comment by Tormentor667** [comment]
We had various playtests on this skill, including other skills with the current timer and we absolutely had no issues (including youtube Let's Plays). Could you record a playthrough of that specific map for us?

**Comment by x3003** [comment]
Well, you guyz know everyting, so it shouldn't be that hard for you anymore.
Dunno how to record, so not gonna. Not a youtuber, you know. Then I also had to cut out all the times I saved/reloaded.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Neither am I, yet I recorded some playthroughs and shared with the team, and the videos seemed to help with quite a lot of issues. You don't have to be a 'youtuber' to do that. @Ozymandias81 [hinted me](https://github.com/Realm667/WolfenDoom/issues/178#issuecomment-659118836) at installing and using OBS, and it worked out pretty well for me. There is absolutely no need for 'professional video editing' or voice acting, just the game footage.
As for the editing, I only had to cut out breaks after going AFK during long multiple-hour walkthroughs (I used avidemux for this, but you can choose any software you want). Also, why cut out the saves? Including these will help us understand which parts of the level may be frustrating.
You can even attach small .mp4 videos directly here in GitHub comments, but there is a file size limit, and a 20min video is going to be around 100MB even under the very low 600kbps bitrate I used, so it would probably be better to upload to a random file sharing service if you want to avoid Youtube.

**Comment by Tormentor667** [comment]
The point is: We watched a lot of videos in the past and no-one had issues with the time limit in C1M0. To understand why this has happened for you, we need to watch you playing.

**Comment by Tormentor667** [comment]
I made a playthrough today and really slowed down my pace. I had 1:29 left when leaving so I simply can’t imagine what took so long. 

Can someone else do a quick test run instead of me?

**Comment by Talon1024** [comment]
I just did a test run myself. Found all secrets, killed almost everyone, and had about 11 minutes to spare.

**Comment by x3003** [comment]
I have some trouble fighting the zombies w/ the rockets and the first floor, after that losing some time on the zombies upstairs.
And ofcourse the endboss on the last floor. That's quite hard.
But I'm not a speedrunner like you guyz. Sometimes taking a little time so see where i am and where i need to go to next.
Hacks are off, so I don't see the enemies on the map, like some ppl have who are making vids.
And ofcourse bj's stamina isn't so great, so he can only run a short distance b4 he runs out of air.
You all should know the map by heart now, so there should be no problem playing it, but I think I'm playing this map only 4 or 5 times.

**Comment by Tormentor667** [comment]
@x3003 I do get your point but the problem is "balancing" in this special case. We had hundreds and thousands of players and none of them reported "not enough time to beat C1M0" so it seems to be balanced right. Adding more time because of one single report (even though we consider your report valuable) doesn't feel right here - so I hope you understand that we need to keep things as they are atm.

**Comment by x3003** [comment]
Maybe the hundreds of thousands of ppl didn't reached that level, of they just didn't wanna bother you and played with god mode...

**Comment by Tormentor667** [comment]
Possibly, but the question is a question of statistics: What do we listen to more? One voice or a thousand? :) I am sure you get the point. What I can suggest is to watch one of another of the Let's Play videos on Youtube about C1M0, maybe you get the hang of it that way.
