### ISSUE TITLE
Opening too high

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#436]
In C3M0_A, it would be nice to get a little ladder here (when you open the main room), because you simply can't jump that high.

![Screenshot_Doom_20210314_162812](https://user-images.githubusercontent.com/77861029/111080415-ac2b2380-84fe-11eb-8f23-91db230f814c.png)

**Comment by Talon1024** [comment]
You're not supposed to reach that area right away.

**Comment by x3003** [comment]
I know, i've already cleared the rest of the field and pressed the button, but still can't reach it.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 You should get to that area from the other direction, over the chasm. There is a way to make the chasm path available by 

<details><summary>(spoiler)</summary>

flooding it with water.

</details>

Judging by the screenshot, you can already do it.

**Comment by x3003** [comment]
>(spoiler) fl......

I would never have guessed you could do that. Maybe make it a bit more obvious.

**Comment by Username-N00b-is-not-available** [comment]
Yeah, good point! What about adding some water pools in small randomly scattered cavities at the bottom of the chasm with the stakes, @Tormentor667 @doomjuan?

**Comment by Tormentor667** [comment]
Yes, that's a good idea.
