### ISSUE TITLE
logo copyright

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#437]
Is this logo not copyrighted ? If yes, you can't use it unless you have permission.

![Screenshot_Doom_20210317_010925](https://user-images.githubusercontent.com/77861029/111398099-1c82a200-86c3-11eb-8461-bd89cb3a8d4f.png)

**Comment by Talon1024** [comment]
1. It's a parody. Note the subtle alterations that make it look more like a swastika.
2. Logos are trademarked, not copyrighted.

**Comment by x3003** [comment]
>It's a parody. Note the subtle alterations that make it look more like a swastika.

I hope microsoft also sees it like that, else you have a problem.

>Why is your HUD face James Ryan's face?

Don't ask, just a little friendly game, not a bug ;)

**Comment by DoomJedi** [comment]
I can try to modify a texture a bit more, to be recognizable and yet more swastika-like

**Comment by x3003** [comment]
Would be nice. And no, I don't work for m$.

**Comment by x3003** [comment]
Well, I didn't saw the parody (the swastika ?) in the logo. All I see is that the Win 10 logo is a bit warped.

**Comment by Ozymandias81** [comment]
I think it is good as is, gonna close this.
