### ISSUE TITLE
New dialog (suggestion)

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#438]
While I am in overhaul of language.csv, I've come up with another dialog with Lt. Big Dave.
I've talk to @Tormentor667 and he approves this addition. 

<details>
  <summary>Spoiler dialog:</summary>

\cCSir...? Ahm... so now you know too. Pretty fucked up story, huh? - Oh, pardon me! It's just... I can't get it out of my head. Just can't. At first, I was angry at Ryan as hell, since he betrayed us. But when I've heard of it... Now I completely understand that look he had, when he was telling me about his family that evening in the mess hall. By that time, he was already a broken man. This is what war is doing to us. My knees are trembling with the thought, that I could get into the same position as he was. My palms are sweating, do you see it, \cPCpt.\cC? Make it stop. Please, end it. End it now. I want nothing more than just to see my children and wife again...\n\n\cCSs-sorry for my mood. Good luck on your next mission, sir.

</details>

It should be available if you do (and after you finish) Ryan's secret mission C3M0_B.

@Talon1024 could you please "prepare the grounds for that"? It needs some coding... and I will add it to language.csv as MARINE2CONV18 (which is next in order) after you agree for this identifier. (Also please feel free to correct my english... :)

**Comment by Tormentor667** [comment]
Approved :) (just for the record)
