### ISSUE TITLE
Sign wrong

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#439]
In C1M3, you see this sign saying 'kein parken', it looks a direct translation from google or so.
A better one would be 'nicht parken' or 'parkverbot'

![Screenshot_Doom_20210307_161633](https://user-images.githubusercontent.com/77861029/111855305-76ce6d80-8924-11eb-834d-25d0090152e4.png)

**Comment by Tormentor667** [comment]
Fixed.
