### ISSUE TITLE
Letter wrong signed

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#440]
In C1M5 you can find the letter from Juliette. But, as a close friend (of BJ), she would never sign her name that way. It would be more like "J.", "Juliette", "Jules' or even "Shotglass", but not "J. Bertrand".
Just when you phone someone you know well, you might say "it's me", but never your fullname.

![Screenshot_Doom_20210307_233353](https://user-images.githubusercontent.com/77861029/111855437-43d8a980-8925-11eb-8138-641eb6f9ac45.png)

**Comment by MuadDib90** [comment]
Yep, good spot.
Should I take care of it @Tormentor667 ?

**Comment by Tormentor667** [comment]
Yes please

**Comment by Talon1024** [comment]
I already replaced with signature with "Juliette" on the Google Docs spreadsheet
