### ISSUE TITLE
dangerous wall

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#441]
In C3M1, when you touch this piece of wall, you die. You don't even have to touch the beams.....

![Screenshot_Doom_20210320_162747](https://user-images.githubusercontent.com/77861029/111883577-86999080-89bc-11eb-8a20-9a9f41e017fe.png)

**Comment by MuadDib90** [comment]
AFAIK that's on purpose. You have to either:
A) shut down the beams, or
B) find an alternative route

**Comment by x3003** [comment]
I know about the beams, but it shouldn't apply to that piece of **wal**l i'm -pointing- at.

**Comment by Ozymandias81** [comment]
This happened to me already in the past, when there were too many beams crossing all together... let's see what's going on

**Comment by Ozymandias81** [comment]
Meanhwile spot this, the default radius seems the culprit here
![image](https://user-images.githubusercontent.com/11136108/111902586-7d510800-8a3e-11eb-87bf-d337448f0343.png)

**Comment by Ozymandias81** [comment]
I did something, enlarged the space to fit the barrier... let's see if it works as intended.
![image](https://user-images.githubusercontent.com/11136108/111903123-f18cab00-8a40-11eb-80db-27af55943a7f.png)

**Comment by Ozymandias81** [comment]
Fixed.
