### ISSUE TITLE
Lever not working.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#442]
In C3M1, lever nr 1 isn't working. Think the nazis would never allow something like that being broken/not working.

![Screenshot_Doom_20210320_144648](https://user-images.githubusercontent.com/77861029/111883661-0c1d4080-89bd-11eb-9e8a-df35b0e82d2c.png)

**Comment by Username-N00b-is-not-available** [comment]
A bit related: I remember that some kind of a semi-secret map action was also suggested for levers (there is also a set of them in the C3M0_A opera house BTW), and it never got implemented to my knowledge. @Tormentor667, @doomjuan, do you still have any plans on them by chance?

**Comment by Tormentor667** [comment]
Short answer: no

**Comment by Ozymandias81** [comment]
There was a plan for that and the lever was stuck for a reason, before that was made sector based but then they simply got replaced with models. We'll keep that one stuck, let's see if anyone has got an idea to use this setting then.

**Comment by x3003** [comment]
> We'll keep that one stuck, 

Why not put a sign on it, to mark it's not working (außer Betrieb) ?!
Something like this.

![außer Betrieb](https://user-images.githubusercontent.com/77861029/111916826-1ef74a00-8a7d-11eb-96d0-b8785f2d6f63.jpg)

**Comment by Tormentor667** [comment]
Will just take care :)

**Comment by x3003** [comment]
You could also replace the double S with the SS "logo", which makes it a bit sinister.
