### ISSUE TITLE
Part invisible tanks

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#443]
In C3M2, you can see through the tanks. Git version is from 21/03.

![Screenshot_Doom_20210322_232427](https://user-images.githubusercontent.com/77861029/112070657-68739200-8b6e-11eb-9b6e-19232647bcad.png)

![Screenshot_Doom_20210322_232439](https://user-images.githubusercontent.com/77861029/112070667-6d384600-8b6e-11eb-86f0-eb4b9960102b.png)

**Comment by Talon1024** [comment]
I think this issue was caused by https://github.com/coelckers/gzdoom/pull/1320. I tried to put together a simple example of the bug, but I haven't been able to reproduce the issue with my simple example.

**Comment by Tormentor667** [comment]
So is it an engine bug or a game bug?

**Comment by Talon1024** [comment]
> So is it an engine bug or a game bug?

I think it's an engine bug. Builds before March 6 don't have this bug.

**Comment by Tormentor667** [comment]
Did you have any success recreating this and/or posting it to the Zdoom forums as bug report?

**Comment by Talon1024** [comment]
Well, I posted a [bug report here](https://forum.zdoom.org/viewtopic.php?f=2&t=71850) on ZDoom forums.

**Comment by x3003** [comment]
Seems fixed.
