### ISSUE TITLE
Walls don't align

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#444]
Some of these walls don't match up.

![Screenshot_Doom_20210321_220709](https://user-images.githubusercontent.com/77861029/112071009-3ca4dc00-8b6f-11eb-99a1-602d3ee66699.png)

**Comment by Tormentor667** [comment]
Can you please share coordinates? ('idmypos 1' at the console)

**Comment by x3003** [comment]
It's in C3M2

X 2414
Y -8523
Z 0

**Comment by Tormentor667** [comment]
Thank you!
