### ISSUE TITLE
Tank fast turn hint

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#445]
I recently discovered that I can make my tank turn a lot faster if I'm holding shift. Shouldn't there be a hint about this ingame?

**Comment by MuadDib90** [comment]
I agree, it should.
And you have "shift" key assigned to "crouch" or "run"?

**Comment by Talon1024** [comment]
I have shift bound to sprint.

**Comment by x3003** [comment]
Here, pressing shift doesn't do anything faster. Also set to 'run'.

**Comment by Talon1024** [comment]
You have to be holding the `sprint` and `move forward` key

**Comment by AFADoomer** [comment]
Holding shift makes the tank "auto-steer" in the direction of your crosshair while moving.  Mostly because that's how I originally coded the movement before I was asked to change it to the current separate controls for base turning and turret spin.

**Comment by Username-N00b-is-not-available** [comment]
So, what's the verdict on this? Is the new hint message necessary? It could be shown somewhere in later parts of C3M2, near one of the three objectives, for example.
By the way, on my older commit I too can't tell the if there is a difference in angular velocity. @Talon1024, could you please make a small video of what is going on?

**Comment by AFADoomer** [comment]
If you turn while stopped, the tank rotates at the same rate as it does if you hold shift; the auto-steer just automatically stops the tank's forward motion, pivots everything to align with the aim direction, then resumes forward motion.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024, please reopen this issue if the behaviour you described still occurs.
