### ISSUE TITLE
Possible sandbox mode?

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#447]
I know that sounds odd. But like if you could spawn more jerry yourself to shoot it would be fun as heck. I wouldn't mind if there was a console code spawner for enemies. Also not a issue but a question, what is the song that plays on the Paris level?

**Comment by Talon1024** [comment]
GZDoom has a built-in `summon` console command, which you can use to spawn any kind of actor in the game. These are some of the enemies you can spawn:

    Guard
    MP40Guard
    RifleGuard
    Officer
    SSGuard
    SSMP40Guard
    SSOfficer
    WGuard
    WMP40Guard
    WOfficer
    WRifleGuard
    Sniper
    WSniper

**Comment by Username-N00b-is-not-available** [comment]
Talon1024 beat me to it :-)
@Wolfenburger You can do it with stock GZDoom commands, try ```summon wguard``` or ```summon sstank3```. This is of course considered as cheat. There is no comprehensive list of classes, but you can use ```logfile actors.txt; dumpactors; logfile``` (I don't remember exactly, maybe you'll have to add ```+``` signs before the ```logfile```s), and GZDoom will fill the file with information on actors (it will be created in the GZDoom directory). There are lots of technical actors, but usually you'll be able to find out which ones correspond to enemies by their names.

As for the music, the main one?
![image](https://user-images.githubusercontent.com/59409713/112744910-bc3a0d00-8fac-11eb-86a2-6fb772da9eb6.png)
https://www.youtube.com/watch?v=c9GtTT-tmh4

**Comment by Wolfenburger** [comment]
> Talon1024 beat me to it :-)
> @Wolfenburger You can do it with stock GZDoom commands, try `summon wguard` or `summon sstank3`. This is of course considered as cheat. There is no comprehensive list of classes, but you can use `logfile actors.txt; dumpactors; logfile` (I don't remember exactly, maybe you'll have to add `+` signs before the `logfile`s), and GZDoom will fill the file with information on actors (it will be created in the GZDoom directory). There are lots of technical actors, but usually you'll be able to find out which ones correspond to enemies by their names.
> 
> As for the music, the main one?
> ![image](https://user-images.githubusercontent.com/59409713/112744910-bc3a0d00-8fac-11eb-86a2-6fb772da9eb6.png)
> https://www.youtube.com/watch?v=c9GtTT-tmh4

The music for the Paris level sounds like a MoH soundtrack but idk where or which. 



> GZDoom has a built-in `summon` console command, which you can use to spawn any kind of actor in the game. These are some of the enemies you can spawn:
> 
> ```
> Guard
> MP40Guard
> RifleGuard
> Officer
> SSGuard
> SSMP40Guard
> SSOfficer
> WGuard
> WMP40Guard
> WOfficer
> WRifleGuard
> Sniper
> WSniper
> ```

So what to I type into the console? Summon?

**Comment by Talon1024** [comment]
> So what to I type into the console? Summon?

Type in `summon`, and then one of the enemies' names, and then press enter to "summon" the enemy. For example: `summon guard`, `summon officer`, `summon ssmp40guard`, `summon ssguard`, `summon wsniper`, etc.

On a related note, this is one of the reasons I consider GZDoom to be like Garry's Mod for the Id Tech 1 engine. Another reason is that it's so easy to mod once you learn DECORATE and ZScript.

**Comment by Wolfenburger** [comment]
> > So what to I type into the console? Summon?
> 
> Type in `summon`, and then one of the enemies' names, and then press enter to "summon" the enemy. For example: `summon guard`, `summon officer`, `summon ssmp40guard`, `summon ssguard`, `summon wsniper`, etc.
> 
> On a related note, this is one of the reasons I consider GZDoom to be like Garry's Mod for the Id Tech 1 engine. Another reason is that it's so easy to mod once you learn DECORATE and ZScript.

Excellent help! Thank you! One question? I'm going to assume I'll have to hunt for specific enemies to spawn in the list

**Comment by Talon1024** [comment]
Well, that list was just a meager sample of what's available. We also have a naming convention for actor classes: Wehrmacht soldiers have the "W" prefix, SS soldiers have the "SS" prefix, and Afrika Korps soldiers (generally) don't have a prefix. If you *really* want, you can look in [the DECORATE files](https://github.com/Realm667/WolfenDoom/tree/master/actors/monsters) for what actors you'd like to spawn.
