### ISSUE TITLE
Enemy can see through trees.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#449]
In C3M2, the enemy sniper can somehow see me through some trees and then shoot me.
And it's not the problem I pointed out in #448, coz I now have the tank in my back, blocking the enemy shots from that side.

![Screenshot_Doom_20210328_132419](https://user-images.githubusercontent.com/77861029/112758079-cc71dc80-8fec-11eb-82e2-78248089c675.png)

**Comment by Tormentor667** [comment]
Well, trees don't have a hitbox that covers the leaves, so I guess we can#t do anything about it. Simply consider enemy snipers having a sharp eye ;)
