### ISSUE TITLE
So mutants are allies?  (Eisenmann level bug)

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#450]
![Screenshot_BoA_20210328_165553](https://user-images.githubusercontent.com/77998291/112768840-f1198480-8feb-11eb-809d-d85bf5c92fa1.png)
![Screenshot_BoA_20210328_165557](https://user-images.githubusercontent.com/77998291/112768843-f1198480-8feb-11eb-8b4a-481f29993697.png)
![Screenshot_BoA_20210328_171823](https://user-images.githubusercontent.com/77998291/112768844-f1b21b00-8feb-11eb-8123-c5eec9fd60af.png)
![Screenshot_BoA_20210328_171827](https://user-images.githubusercontent.com/77998291/112768845-f1b21b00-8feb-11eb-9465-1c5b41937d7c.png)

I can get help from them in the eisenmann level lmao

**Comment by Ozymandias81** [comment]
The indicator appears once an actor is set as FRIENDLY on its properties or which comes with that flag hard-coded, that's why it happens. It's not exactly a bug but indeed something which needs to be addressed, probably mapwise.

**Comment by Wolfenburger** [comment]
> The indicator appears once an actor is set as FRIENDLY on its properties or which comes with that flag hard-coded, that's why it happens. It's not exactly a bug but indeed something which needs to be addressed, probably mapwise.

I kinda ain't complaining because they gave me bandaides. And a few magazines. However it does break immersion. Which is OK though. Not the end of the world though. Just wanted to spot this little bug. We maybe could keep a friendly mutant in as a cute joke.

**Comment by Tormentor667** [comment]
Fixed the issue.
