### ISSUE TITLE
Text doesn't fit screen

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#453]
The text 'schlangenkopf' doesn't fit the screen, so either the screen is too small or the text too width.

![Screenshot_Doom_20210402_013519](https://user-images.githubusercontent.com/77861029/113409963-9fd61000-93b2-11eb-9930-636118e51786.png)

**Comment by Username-N00b-is-not-available** [comment]
It does fit the screen, it's the translucent curtains that hide parts of the name:
![image](https://user-images.githubusercontent.com/59409713/113417159-81304300-93cb-11eb-8a79-886a3af017b0.png)

**Comment by Tormentor667** [comment]
I just took care of it.
