### ISSUE TITLE
Ufo hard to see

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#454]
In C2M5, when douglas finished his sentense, the ufo is already gone.
It's hard to spot anyway w/ this grey on grey.

![Screenshot_Doom_20210402_165512](https://user-images.githubusercontent.com/77861029/113455447-e8b9b300-940a-11eb-9bec-01afa252ec1d.png)

![Screenshot_Doom_20210402_165414](https://user-images.githubusercontent.com/77861029/113454659-07b74580-9409-11eb-9b22-da5d0cf7d106.png)

**Comment by Wolfenburger** [comment]
> In C2M5, when douglas finished his sentense, the ufo is already gone.
> It's hard to spot anyway w/ this grey on grey.
> 
> ![Screenshot_Doom_20210402_165512](https://user-images.githubusercontent.com/77861029/113455447-e8b9b300-940a-11eb-9bec-01afa252ec1d.png)
> 
> ![Screenshot_Doom_20210402_165414](https://user-images.githubusercontent.com/77861029/113454659-07b74580-9409-11eb-9b22-da5d0cf7d106.png)

I see it clear as day :x

**Comment by Tormentor667** [comment]
Same here. Yes, you could have bad luck and look into a direction where the ufo isn't visible but hey - bad luck. But it enlarges the replay value ;)
