### ISSUE TITLE
Door color

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#456]
In C2M5, this door has another color on the inside (green). On purpose ?

![Screenshot_Doom_20210402_211000](https://user-images.githubusercontent.com/77861029/113455278-82349500-940a-11eb-8179-e0557de41556.png)

**Comment by MuadDib90** [comment]
Yes, this is intended. So you can't go back, until you have a turquoise key. This should prevent a level wandering, to be more narrow in sense of level directioning. (to prevent gamers' frustration...)
