### ISSUE TITLE
Text not clear

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#457]
In C2M5, when you wanna walk the path douglas says something like 'walk all the way through the forest'. As if the destination is far away.

![Screenshot_Doom_20210402_165320](https://user-images.githubusercontent.com/77861029/113456798-895da200-940e-11eb-9e1e-d4490466c02e.png)

However, when you jump on the (slow moving) truck, it's only few minutes away.

![Screenshot_Doom_20210402_165333](https://user-images.githubusercontent.com/77861029/113456740-5fa47b00-940e-11eb-9496-154596694aa8.png)

Why not remove the line saying [The entrance is .....] ???

**Comment by MuadDib90** [comment]
Yes, I know what you are aiming for...
But you have to consider more things. Storytelling and game playability.

It is a question of story that there should be (idk 1 hour - in real time - travelling through the forest for example?), but you - and I am certain of it - wouldn't want to spend an hour behind your PC just sitting and looking on your display...

Thus this "convenient shortcut".
Consider it as a "long journey through the forest" in your head, but in real time you don't have to sit through all that. That would be boring. :)

(Remember: it is the same sense of shortcut as in C1M4, where you are far away from the dam, but using a portal, you appear right before it.)

**Comment by x3003** [comment]
Well, if douglas would say something like, 'get on the truck bj, else i'm leaving you behind', to me it would make more sense.

**Comment by Tormentor667** [comment]
@MuadDib90 already explained that very well but I could also live with improving this if others agree on the report. Both possibilities are fine to me.

**Comment by AFADoomer** [comment]
"You don't want to walk the whole way through the forest, do you?" is far less awkward English.

**Comment by Tormentor667** [comment]
Well, at least I changed that ;)

**Comment by MuadDib90** [comment]
Sure, can be done. We will at least make more variety. There is similar line in C2M4, when you want to walk through the desert alone. This way we'll have two different states. So @AFADoomer or @Talon1024 can you please check a proper english there too, but leave the line as is?

**Comment by MuadDib90** [comment]
Both comments - going through the forest and desert - has been taken care of. This can be closed now.
