### ISSUE TITLE
General notes

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#458]
I did (quick) play E3 on first difficulty.

- [x] This happend to me in the shop:

https://user-images.githubusercontent.com/73436978/113480474-ae94f380-9494-11eb-93d6-e70946e619ac.mp4

- [x] The "pointer" (hold-to-activate script, when planting a bomb for example) isn't showing anymore. Is it only on my side, or some particular commit "is to blame"?

- [x] When you open automap, the title of the map in the upper left corner used to be "operation: 'something' ", now it is just "someting". Is it a bug or intended?

> Intended, it was my suggestion, recently implemented by @Tormentor667. This way the lines are shorter and do not escape their boxes in the Mission Summary. --N00b, 03 Apr 2021

- [x] Last suggestion for an easteregg:
This is a shot from Wolfsschanze. Could be nice, to have just one ammo storage like this one, filled with original DOOM 1 textures of machine gun ammo packages and rocket ammo packs. What do you think? :)

![01](https://user-images.githubusercontent.com/73436978/113480657-cae56000-9495-11eb-92ae-73c57d3e0de9.PNG)

> Preparing something :-) --N00b, 03 Apr 2021

**Comment by Tormentor667** [comment]
> Preparing something :-) --N00b, 03 Apr 2021

No need to, I already committed something ;)

**Comment by Tormentor667** [comment]
Regarding the rest of the report, I was not able to reproduce the video and the cursor crosshairs are still working for me.

![2021-04-03_194328](https://user-images.githubusercontent.com/10298439/113486852-08a5b100-94b5-11eb-953f-5ee4888b8690.jpg)
![2021-04-03_194359](https://user-images.githubusercontent.com/10298439/113486854-093e4780-94b5-11eb-8a6e-af74e2dad705.jpg)

**Comment by AFADoomer** [comment]
Can you give specific instances where the crosshairs aren't showing up for you?  I made a small change to the crosshair scaling code recently (because I was playing on a lower resolution and the crosshair graphic was gigantic), but that's the only thing that has changed in probably a year.

**Comment by MuadDib90** [comment]
> 
> 
> > Preparing something :-) --N00b, 03 Apr 2021
> 
> No need to, I already committed something ;)

Maan, this is hilarious! :D

**Comment by MuadDib90** [comment]
> 
> 
> Can you give specific instances where the crosshairs aren't showing up for you? I made a small change to the crosshair scaling code recently (because I was playing on a lower resolution and the crosshair graphic was gigantic), but that's the only thing that has changed in probably a year.
> 
> EDIT: Also, I don't understand what I'm seeing in the shop video... What's the problem?

Sure.
It is suddenly not showing anymore. The arc that is loading (as Dan showed above), I can't see it. The functionality is there, but no icon. What bothers me, I did nothing unusual then each time I download the latest git repository. Anyway I'l try start evething from scratch and let you know.

About the video. When I go close to Laz, it starts to lag (not much, but there was a visible loss of fluency) and that black screen under that is blinking... was not problem with that before. - But it happens from certain angles and closeness I guess.

**Comment by Ozymandias81** [comment]
Does it happen fullscreen while recording or windowed while recording? Seems there is a focus problem with apps, something between Bandicam (please use OBS) and your gzdoom mouse config maybe... I guess you have a modern mouse, am I right? Just trying to help qith questions regarding the issue.

**Comment by AFADoomer** [comment]
Out of curiosity, what is your 'crosshairscale' CVAR set to?

**Comment by MuadDib90** [comment]
> 
> 
> Does it happen fullscreen while recording or windowed while recording? Seems there is a focus problem with apps, something between Bandicam (please use OBS) and your gzdoom mouse config maybe... I guess you have a modern mouse, am I right? Just trying to help with questions regarding the issue. Also, gzdoom version?

It happend ingame (on lowest dificulty if that makes any change), that is why I recorded. So I guess it has nothing to do with Bandicam.
Mouse config? What could possibly cause any problem in mouse settings? Here I really don't know what to say... it's not like I don't want to, I just don't know what...
GZD ver.: GZDoom g4.6pre-86-gd71b03f75

>Out of curiosity, what is your 'crosshairscale' CVAR set to?
>
>EDIT: Try with latest commit (d2589a6), please.

My "crosshairscale" CVAR is set to 0.
OK, will try the commit. Then Let you know.

**Comment by AFADoomer** [comment]
> My "crosshairscale" CVAR is set to 0.

OK, should be fixed, then, if that was the case.

**Comment by Tormentor667** [comment]
Regarding the slowdown, the only reason why this might happen is that the npc or an object near the npc checks the distance from the player and we get some kind of a loop here.

**Comment by MuadDib90** [comment]
The pointer is solved.
New dev_built of GZDoom... now works. But I can't really tell if "this" in particular solved it.

Regarding the video; I kind of suspect my NTB causing this. It is not a gaming machine... unfortunatelly. So I guess we can assume it as solved.

**Comment by AFADoomer** [comment]
> The pointer is solved.
> New dev_built of GZDoom... now works. But I can't really tell if "this" in particular solved it.

If your crosshairscale was set to zero, then, yes, this last commit was definitely the fix.  I was blindly multiplying by the value of that variable in order to calculate the desired drawing size, and didn't account for 0 actually meaning 0.5 (the default value).  So a crosshairscale of zero was causing no cursor overlay to be drawn before I fixed it.
