### ISSUE TITLE
Balancing the Gestapo agents

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#461]
In C2M6_B on the lowest level, these gestapo agents must be blind. They don't see you, even when you are in front of them (even when the alarm goes off).

![Screenshot_Doom_20210404_134304](https://user-images.githubusercontent.com/77861029/113507775-c9c33a00-954c-11eb-8558-6504ab10e52e.png)

**Comment by Tormentor667** [comment]
Assigned to @AFADoomer , maybe it has something to do with the latest changes you did regarding the "speed" the Gestapo can unveil your cover. I'd suggest making them see you a bit faster, uncovering you faster anyway, as you still can run through a large of portions in C2M6_B without being noticed by them.

**Comment by Talon1024** [comment]
I tried to make the suggested tweaks. The thing is, I don't want levels like C2M6_B to become impossible on higher skill settings, especially since there are non-optional parts of the level like this:
![Screenshot_Doom_20210404_094550](https://user-images.githubusercontent.com/6550500/113511326-50681f00-952d-11eb-9b09-5522ae158772.png)
As well as the office where the red key is.

**Comment by AFADoomer** [comment]
Thanks, @Talon1024.  The different weights are a smart addition.

This seems to be a good balance in the limited playthrough I just did, but I'm worried that we are making the Gestapo too difficult on higher skill levels...  

We've all played this thing many times and are familiar with the mechanics; we don't want people who are playing through for the first time to be frustrated.

**Comment by Wolfenburger** [comment]
> In C2M6_B on the lowest level, these gestapo agents must be blind. They don't see you, even when you are in front of them (even when the alarm goes off).
> 
> ![Screenshot_Doom_20210404_134304](https://user-images.githubusercontent.com/77861029/113507775-c9c33a00-954c-11eb-8558-6504ab10e52e.png)

He has "deal with it" shades on. He thinks he's to cool to see you. Ok ik this isn't really adding anything. Sorry thought it would be funny

**Comment by DoomJedi** [comment]
Or he is like a cat - he sees you but doesn't show he cares :)

**Comment by Wolfenburger** [comment]
> Or he is like a cat - he sees you but doesn't show he cares :)

Lmao. He also has the careless blank face to macth.

**Comment by x3003** [comment]
Look ok now.

**Comment by Tormentor667** [comment]
Thanks for bringing this up @x3003
