### ISSUE TITLE
Can't disable alarm anymore

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#462]
In previous git versions of boa, it was possible to disable the alarm by kicking the alarmswitch. If you do this now, you alarm the guards and they fire at you. Disabling the alarm was suggested somewhere in the game, which is now made impossible. 

![Screenshot_Doom_20210404_134401](https://user-images.githubusercontent.com/77861029/113507860-35a5a280-954d-11eb-866c-496372ccf26a.png)

![Screenshot_Doom_20210404_134406](https://user-images.githubusercontent.com/77861029/113507940-ad73cd00-954d-11eb-9f89-f401e5a5bc0f.png)

**Comment by Tormentor667** [comment]
Well, kicking an alarm off directly standing near some guards - how unrealistic would it be if they ignore you? :-D

**Comment by Username-N00b-is-not-available** [comment]
This issue reminds me of a manner I played C2M6_B one day. It was possible to fling grenades from safe spaces into the centre or near such soldier groups. If the grenade did not hit any of the soldiers before the explosion, but the explosion killed everyone from the group, no alert was raised. I had managed to clear pretty much the entire map with similar tricks. Does this still work in new BoA versions?

**Comment by x3003** [comment]
Well, it also happens in the hangar, were there are guards, but they dont stand next to you.

**Comment by AFADoomer** [comment]
The kick is treated just like any other weapon here...  If you are in disguise and raise a weapon (or kick), your disguise fails.

If a random scientist starts kicking the alarm panel, of course the guards will respond.

@Username-N00b-is-not-available - There's a specific check for sneakable enemies to not look for grenades unless they are alerted.  I don't know/remember why it is there.

**Comment by Wolfenburger** [comment]
> In previous git versions of boa, it was possible to disable the alarm by kicking the alarmswitch. If you do this now, you alarm the guards and they fire at you. Disabling the alarm was suggested somewhere in the game, which is now made impossible.
> 
> ![Screenshot_Doom_20210404_134401](https://user-images.githubusercontent.com/77861029/113507860-35a5a280-954d-11eb-866c-496372ccf26a.png)
> 
> ![Screenshot_Doom_20210404_134406](https://user-images.githubusercontent.com/77861029/113507940-ad73cd00-954d-11eb-9f89-f401e5a5bc0f.png)

Personally don't believe those Wehrmacht boys would let you kick their alarm. In reality if anyone saw some dude kicking things they'd probably ask him if he was ok or if he was nuts. But those germans aren't programmed to have social skills in the game. So they socially accept you by firing 9mm at you.
