### ISSUE TITLE
Faction reference. 

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#463]
In feuerdrone they reference Japan and there is a discussion on a note. I'm not sure if I've missed anything yet. But has there or is there any comments on Italy or places like Romania on notes? I just wonder how their fairing in this altered ww2 scenario.

Obviously this ww2 is different from our ww2. Hitler escapes Berlin to raise a army of the dead and the Afrika Korps is still in North Africa in 44. Plus the map in the wolfenstein level with flags and units on the board show Germany still has a large chunk of territory even for 1945 after berlin. So I wonder. What happened to Italy or Romania? Possibly same fate?

**Comment by Tormentor667** [comment]
We actually didn't care too much of complete historical correctnes. Italy and Romania simply do not serve any purpose story-wise.

**Comment by Wolfenburger** [comment]
> We actually didn't care too much of complete historical correctnes. Italy and Romania simply do not serve any purpose story-wise.

All good. At least Japan got a reference. That was cool. Would of been cool to get little peeps outside the world we were in and wonder how things were going in the other parts of the world. Cool to get little looky loo's. You know?
