### ISSUE TITLE
C3M0_A - rope issue

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#464]
This happend to me when I used the rope where appropriate in this mission.
The rope wasn't there, where it should be. (Where it should appeared.)
Instead it was somewhere "midair", barely visible. And the worst part **(game-breaker)** I couldn't climb on it.
I was standing as close to the wall as possible, holding "use" until the pointer was full. Could it be caused by it? In any case it should be checked.

![001](https://user-images.githubusercontent.com/73436978/113574427-6274bb00-961c-11eb-8342-2e40b3479dd7.PNG)
![002](https://user-images.githubusercontent.com/73436978/113574442-67d20580-961c-11eb-84b7-1194288decb3.PNG)

**Comment by Talon1024** [comment]
I just played through C3M0_A, and I didn't have this particular issue.

**Comment by AFADoomer** [comment]
I have no idea how this could happen...  I've never seen behavior like this through many hours of testing the ropes.

**Comment by Ozymandias81** [comment]
GZDoom build? Please alway tell us which build did you used and from where (mapeditor or in game)

**Comment by MuadDib90** [comment]
Sorry...
![003](https://user-images.githubusercontent.com/73436978/113741765-42b7c280-9702-11eb-98dc-c42d2dcdacea.PNG)

But I don't use mapeditor - not only as you do, but I don't have it at all - (only game created from github repository on my HDD), so I guess, the question "from where" is not understandable for me... :)

I just had like 30 attempts for testing purposes, from which 2 ended up like this:
![001](https://user-images.githubusercontent.com/73436978/113742175-9fb37880-9702-11eb-98fe-de1896787e75.PNG)
![002](https://user-images.githubusercontent.com/73436978/113742192-a641f000-9702-11eb-826f-03c6a49e5c60.PNG)

Sometimes the rope is where it should be, but with different thickness... thick and slim. But if it appears where it should, you can climb on it with no problem. If it appears everywhere else, you can't.

Now for the testing:
I tried what came to my mind; crouch, jump, changing weapon, fire, move with mouse slowly, faster, hold move forward, backward, to the left and right. Yet any connection to that 'where exactly this bug happens' I couldn't unfortunatelly track down.
What is certain (as it seems) is that it might, in some occasions - we don't know which - pop up, making a soft lock. 

I really want to provide more helpful info, but now I don't know what to do...

**Comment by Ozymandias81** [comment]
Try with most recent build then, means r195 and see if it happens again

**Comment by Talon1024** [comment]
BTW, by "r195", he means the number in between the version number and commit hash.

**Comment by MuadDib90** [comment]
Now used R195 built.
Another 20 attempts.
One misplaced rope position. (I could climb up to the half of the hight using this misplaced one, but also a zombie followed me there :D - or he could, almost as there were stairs...)

Seems very, very random to appear (to me).

**Comment by Ozymandias81** [comment]
Btw what are these on C3M0_A, what was thing 9605? I can't see any reference too regarding maybe Hexen actors for shards or something similar... @Tormentor667 ? @AFADoomer ?
![image](https://user-images.githubusercontent.com/11136108/114412461-68831280-9bad-11eb-81cc-3551dfa9f97e.png)

**Comment by Talon1024** [comment]
From [GZDoom's built-in MAPINFO](https://github.com/coelckers/gzdoom/blob/master/wadsrc/static/mapinfo/common.txt#L97): `9605 = SecActDeath3D`

**Comment by Tormentor667** [comment]
No idea where it came from or what it does...

**Comment by Ozymandias81** [comment]
Mmmh destroyable geometry? They are linked to windows on the cottage at the center of the map

**Comment by MuadDib90** [comment]
> 
> 
> Now used R195 built.
> Another 20 attempts.
> One misplaced rope position. (I could climb up to the half of the hight using this misplaced one, but also a zombie followed me there :D - or he could, almost as there were stairs...)
> 
> Seems very, very random to appear (to me).

So... be it a random to appear (and it has to be adressed - in rare occasions as tested), we don't have pretty much nothing in hands to solve it. Am I right?

Do you (with your experience) still consider it a game-breaker, or can we leave it be; and eventual come back to it in future, IF this will be a more of a threat? (closing this issue)

**Comment by AFADoomer** [comment]
Can you still recreate this issue with the current code?

**Comment by MuadDib90** [comment]
Latest GZDoom - R195
Latest github repository

Tried 30+ attempts... "no luck" in recreation. (Doesn't necessarily mean it isn't there... if it is rare...) But again it is so rare, we may don't have to bother/worry at all. - I can't estimate this.

**Comment by AFADoomer** [comment]
I think this is resolved, then...  I think there's some kind of auto-aim behavior on the Railgun function that I was using to spawn the rope segments.
