### ISSUE TITLE
C3M0_A - displaying (video?) problems...

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#465]
I once have this problem, but I don't remember, if it was resolved anymore. 

In this mission this strange behavior was happening. When pointing in some certain directions (I couldn't figure out when exactly this was happening) display starts to brighten with someting I can't even name...
When not moving, it will cover all your display (as seen in second picture), leaving the game impossible to play. The worst place, where this was happening (nearly) wherever you pointed, was Erik's room. I though I won't be able to go through that room. (Was, with the help of automap...)

![004](https://user-images.githubusercontent.com/73436978/113575439-25a9c380-961e-11eb-9616-8fb201bb2b64.PNG)
![005](https://user-images.githubusercontent.com/73436978/113575453-2a6e7780-961e-11eb-91c5-a193c89352c0.PNG)

**Comment by AFADoomer** [comment]
Can you recreate this and then try to disable the post-processing shaders one at a time to narrow down which one is the problem?

**Comment by Tormentor667** [comment]
It seems as if the crosshair and the bloom effect somehow are interfering, or the lense flares... but that would be my first guess.

**Comment by MuadDib90** [comment]
From what I have just found out, when I disable all three shaders (motion blur, vignette, lens flares) the effect disappears. Also the crosshair moves smoothly through places, where it was appearing.

On the other hand, I guess it is not doing only one of them, because if I turn each one of them on (individually ), it is doing something.
Vignette will blacken your screen, lens flares are doing something similar as above but not in that scale, and motion blur is stopping the screen on that spot (when you move the screen freezes for some time, then unfreeze again, when you are "out of that focus point").
And together they are unbearable nuisance...

**Comment by AFADoomer** [comment]
Thanks for the testing and confirmation...  I imagine that this is going to be similar to my own bug with the color temperature shader in OpenGL, where it is hardware dependent. Are you using the Vulkan renderer or OpenGL?

You've captured my thoughts on all of these "always on" overlay effects in general as well 😉 .

**Comment by MuadDib90** [comment]
No problem.
Using OpenGL.
I've heard that Vulkan is in the state of development, so I do not want to put myself into more trouble than necessary. :D

**Comment by AFADoomer** [comment]
I think it is past the "in development" phase at this point.  

The reason that I ask is that my bug only happens with the OpenGL renderer, and not with Vulkan.  Can you test that with your machine?

**Comment by MuadDib90** [comment]
Ah, didn't know that.

Tested. With Vulkan it is about 95 % better. It is still doing something, but only when I look into lights, as it seems (it is small and not developing into the whole screen)

**Comment by Username-N00b-is-not-available** [comment]
Possibly connected with my dated report in https://github.com/Realm667/WolfenDoom/issues/384#issue-811375079 (search for 'nuclear explosion'). That one occured to me in SM03.

**Comment by Tormentor667** [comment]
I wonder, should we make Vulkan the default for the standalone or OpenGL?

**Comment by AFADoomer** [comment]
If we set vid_preferbackend to 1, it will use Vulkan if available, and fall back to OpenGL if not.  

I doubt BoA will running on SoftPoly (vid_preferbackend = 2).

**Comment by Tormentor667** [comment]
Then let’s go for that :)

**Comment by Ozymandias81** [comment]
The fact is that setting if for Vulkan might cause several slowdowns for players, specially if they have an Intel based rig with nVidia gpu. I get worse performance with my AMD based pc (Fx 6300 6core 3.5ghz), where my gpu is an Nvidia GeForce GT 1030 2gb. Seen instead on some people who had RX 560 a good step up in terms of performance under Vulkan, while instead have crazy slowdowns with OpenGL.

Gonna do a pair of tests with latest devbuild... BTW we SHOULDN'T base our April release over a devbuild, we already got issues during C2 release. Anyway time for tests.

**Comment by Ozymandias81** [comment]
Well, the Pixelated Film Grain seems to slowdown performance greatly on screen, with both Vulkan/OpenGL solutions. I do get a better framerate on TITLEMAP under Vulkan running the game from official "setup" (so custom executable, everything default): 143fps Vulkan, 115 OpenGL. On C3M0_A, using the map command, I do see a critical slowdown simply when starting the map: spikes of continuos slowdownw from 4fps to 12fps, with all PP shaders on, but I get 25-35 as intended quite stable with all PP shaders on beside Pixelated Film Grain (this under Vulkan). I bet it gets worse with OpenGL (testing)

**Comment by Tormentor667** [comment]
Tried it on my pc with C3M6_A and wow: The Vulkan renderer is indeed much faster. I got an FPS gain of 200% on that map, from 20FPS to 60FPS. I guess we definitely must set Vulkan to default :)

**Comment by Ozymandias81** [comment]
It's mildly true yes, even I gained 30 on Opengl to 50 on Vulkan, but always on Vulkan I got these terrible spikes again, and they are very random it seems. It was running good until started to rotate around myself for a while to see if performance was stable... and then I got this.
![Screenshot_BoA_20210406_183232](https://user-images.githubusercontent.com/11136108/113746487-ad6afd00-9706-11eb-97d1-dcb093215779.png)

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90, does the issue from your original post still happen? I had experienced something similar on a Commander Keen level, but that was quite a long time ago. It does not occur for me now.

**Comment by MuadDib90** [comment]
@Username-N00b-is-not-available yes, I saw your video.

Newest version of gzdoom, up to date repository. Tried to turn everything on. Tried it again on C3M0_A.
Short answer: yes.

OpenGL causes it still more than Vulkan. But it is **noticeably** lower than before. So I would consider it "tweaked down" as much as you could at this point. Thank you.

We can consider it done by now, from my point. :)

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 Could you post a video from your machine, please? In what locations does it occur now? Is it still the Erik room, as in your first post? I also tried to reproduce this problem there, but, once again, it does not occur to me anymore for some reason...

**Comment by MuadDib90** [comment]
@Username-N00b-is-not-available
Man, this is so frustrating...

I recorded a video about OpenGL, where I could not shown it properly (to my surprise), there are only those parts, where screen "stops" and "blur" as when you went through walls using NOCLIP in vanilla Doom. But I swear I do not making it up, those "things" from the first post at the top were there, but not so much anymore, and also with no such strength to make the game impossible to play. 

[OpenGL.zip](https://github.com/Realm667/WolfenDoom/files/6353007/OpenGL.zip) (too long to upload directly)

Then the OBS studio software gave out and I was not able to record a video with it; only sound. So I tried with Bandicam, but that caused jerky video (tried to cover the same place with Vulkan this time). Despite that it shows lesser problems with this issue.

https://user-images.githubusercontent.com/73436978/115601356-fb265e80-a2dd-11eb-8bd2-8c79b98473e0.mp4

**Comment by AFADoomer** [comment]
Can this be considered a hardware-specific issue and closed?

Some player may just need to disable the post-processing options if their machines do not handle them well.

**Comment by Tormentor667** [comment]
Yes, I agree. We could prepare an explanation in the FAQ on the website for this. I will take care later.

**Comment by Tormentor667** [comment]
![2021-04-29_084802](https://user-images.githubusercontent.com/10298439/116512011-a4191e80-a8c7-11eb-8306-f0ef1aa87f8e.png)

Did it. @Talon1024 if there is anything I can improve language-wise, let me know.
