### ISSUE TITLE
Some images too small

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#467]
Some images, the knife and the cross are now way too small, you can barely see them.

![Screenshot_Doom_20210405_135953](https://user-images.githubusercontent.com/77861029/113603047-b9da5180-9643-11eb-917d-2ba503127902.png)

![Screenshot_Doom_20210405_154231](https://user-images.githubusercontent.com/77861029/113603060-bcd54200-9643-11eb-941c-fe2e9af71b7b.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Which commit are you playing? Is it the latest one?
AFAIK @AFADoomer has recently fixed a similar problem in https://github.com/Realm667/WolfenDoom/commit/d2589a6957ee07f0c34d8f87c6d3f8a4b2727a0f.

**Comment by x3003** [comment]
It's the commit from today.

**Comment by AFADoomer** [comment]
Yeah, it's almost certainly because of the scaling change commit.  I'll have to change how I'm calculating the draw size for the crosshair overlays; scaling is too unpredictable at different resolutions as-is.

**Comment by AFADoomer** [comment]
Should be good after 5e3bb306441433d079b4720ccb7dc636a8ccea5e.

**Comment by Tormentor667** [comment]
@MuadDib90 can you confirm?

**Comment by MuadDib90** [comment]
> 
> 
> @MuadDib90 can you confirm?

Sure.
I confirm this:
After this 5e3bb30 commit the cursor behaves like this:
With zero set, the cursor is at (what I think is) a default size.
Slightly to the right to the value 0,1 the cursor gets barely visible.
And moving slider to the right, it gets bigger, until max. values, where it is nearly over half of the display.

**Comment by AFADoomer** [comment]
That matches the scaled size of the actual green crosshair, also, right?

**Comment by MuadDib90** [comment]
> 
> 
> That matches the scaled size of the actual green crosshair, also, right?

Yes, exactly.

**Comment by x3003** [comment]
Seems ok now.
