### ISSUE TITLE
Streetnames not complete

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#468]
I think someone should put a period after the numbers of the streetnames.
That way, the streetnames will be something like, erste, zweite, dritte [...] straße and so on, which makes more sense.

![sn1](https://user-images.githubusercontent.com/77861029/113938241-99082c80-97fa-11eb-907a-d9265c4b9ac2.png)

**Comment by Username-N00b-is-not-available** [comment]
I may be wrong here, but to me it seems that these numbers are supposed to mean the building numbers, not the street numbers.
This raises another question, since in German addresses (and in Dutch ones) the building number should go after the street name, not before it...

**Comment by Tormentor667** [comment]
Well, I didn't go for accuracy here but for the "easter egg" effect actually. That's why there are various numbers with various names there which represent famous/infamous names. This won't be changed as the reason for adding them the way I did outweighs the correctness ;)
