### ISSUE TITLE
Various issues after recent changes

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#471]
- [x] There are some problems with recent changes: we can't run anymore while in disguise, this means also that we aren't able anymore to reach some secrets, such [this one](https://ibb.co/R3WTstw) on C3M1_A. 

- [x] Also the new coordinates for idmypos [takes top-right](https://ibb.co/bBt1w3g) corner with my setting, makes nearly impossible to see which keys and stuff I have with me.

- [X] There is also an issue with targets indicators, they doesn't seem to work anymore on certain occasions, such [this one](https://ibb.co/zQC2dYS) which is fundamental.

- [x] In the end, it also seems that special [skyboxes doesn't work as intended anymore](https://ibb.co/GWCXP18), or something has been moved on the map (if maps have been edit using external editors beside UDBuilder this could be related maybe).

- [x] MGTurretSoldiers and enemies which shoot tracers with Bullet damagetypes damage tanks.

- [x] In any case, I have to say that I get terrible slowdowns spikes with Vulkan (more frequent) and OpenGL, while performance is initially better under Vulkan. This also happens under GZDoom 4.5.0 stable via IPK3 and lots of details off.

> Is this still the case? - AFA (17 Apr 21)
>> Sadly yes, but now happens in different ways... Sometimes it may start fluently even with PPShaders on, but if open the console and play with it for a while, or switch app and then return to BoA, spikes happens again. It happened to me with console open then close on C3INTRO, with default settings via ipk3... I noticed that frame weren't going down drastically, but think time used to jump from 30ms to 200ms intermittently. Then I decided to remove PPShaders and leave the game. Loaded boa again (default settings, so Vulkan), and I had spikes already on Titlemap. I am gonna see if it's my ssd, but it doesn't happen anywhere, only with BoA (and not plain GZDoom or any other project) --Ozy81
>>> Happens as well on my other plain hdd, it seems that if I don't do anything for a long while, neither move, and then continue to play, things get worse. Didn't touch boa_cullrange and rendering distance, on both occasions (ssd and hdd). --Ozy81

Running under gzdoom4.6 r195 64bit, while testing from UDBuilder 3751 64bit.

**Comment by MuadDib90** [comment]
About those targets indicators, could it be related to the scale crosshair issue we had couple days earlier @AFADoomer ?

![obrazek](https://user-images.githubusercontent.com/73436978/114269637-819e8e80-9a08-11eb-9cd8-8513e66e7a4a.png)

**Comment by Talon1024** [comment]
IIRC the target indicators shouldn't show up on skill 3 (HMP/Ordinary) or higher.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 It was my decision https://github.com/Realm667/WolfenDoom/commit/feb6eb903cc428e8799dc765591a9aba4dc78476, maybe it was stupid, but nobody commented on my stupidity neither when I posted it on the issue nor when committed the change. Fixed right now.

**Comment by AFADoomer** [comment]
Sprinting was always supposed to be disabled while in disguise, but the check broke as the disguises evolved. I can get rid of that check.

Does idmypos actually cover anything when you have items? It should float to the left of the key block and inventory area.  I do need to adjust the position downward when fps is shown.

The skybox might be misbehaving after I made a change to fixe the C3M6 finale swirl skybox.  I will take a look.

**Comment by AFADoomer** [comment]
@Ozymandias81 - But it _doesn't_ cover the keys or the inventory area...  Look at your [later screenshot](https://imgbb.com/GWCXP18).  The red key is off to the right of the lock icon.

**Comment by AFADoomer** [comment]
It already accounts for incoming messages...  I just need to add an offset if vid_fps is toggled.

**Comment by Ozymandias81** [comment]
Works good now... On the other side, this model has some tearing that can't be noticed under any model editor, only on GZDoom... Why?
![Screenshot_Doom_20210412_165923](https://user-images.githubusercontent.com/11136108/114423297-55754000-9bb7-11eb-9fe0-1e99c217039d.png)

**Comment by Tormentor667** [comment]
Is this in C3M0_A's Resident Evil easter egg? If yes, @AFADoomer made these models, maybe he can help.

**Comment by AFADoomer** [comment]
The original model that I converted from was a mess.  This is residual from that, I think.

It's possible that 2 models are overlapping in this case, though.  I'll take a look.

**Comment by Ozymandias81** [comment]
Yes I was aware that AFA did them, I thought it was the midtex, then models clipping together... But no, it comes from the model itself. Didn't test if setting scaling to 1.0 on modeldef helps though (which is 1.333 xyz atm)

**Comment by Tormentor667** [comment]
> The skybox might be misbehaving after I made a change to fixe the C3M6 finale swirl skybox. I will take a look.

After investigating, I am pretty sure that's the reason. It worked before that commit but the relative position seems to be broken now.

![2021-04-13_223043](https://user-images.githubusercontent.com/10298439/114617065-ecb9c080-9ca7-11eb-8739-d5472af6e262.jpg)

**Comment by AFADoomer** [comment]
Yes.  And if I revert my change, this one is right again, and the finale one is broken.

**Comment by Ozymandias81** [comment]
Then now what's left is the window model and the optimization... Surely when there are around actor spawners and zombies things get worse than expected. I'll see if I can do more tests while checking issue #384

**Comment by AFADoomer** [comment]
I've been experimenting with short-circuiting enemy logic/Tick calls if they are outside of a certain range from the player...  with some good initial success.  I have to track down @Talon1024's issue with the new culling code and do some more testing and tweaking, but this gave me huge improvement.

I'm also working on adding fog/fade handling so that enemies that shouldn't be able to see you through fog from a distance won't shoot at you, also with great success (because fast projectile bullet tracers are expensive due to ridiculous portal check overhead) .  C3M2 plays very differently with this change.

Will work to commit these tonight (so like 8 hrs from now).

**Comment by Ozymandias81** [comment]
Added new issue that I noticed while playing C3M2, MGTurretSoldiers and enemies which shoot tracers with Bullet damagetype turns out that they damage tanks... Not sure if it is a smart move to add a different damagetype for EnemyTracers inheriting BulletTracer

**Comment by MuadDib90** [comment]
> 
> 
> Added new issue that I noticed while playing C3M2...

If you transfered it here (sort of) as another issue, does it mean this #465 can be closed?

**Comment by Ozymandias81** [comment]
Sadly it seems that recent improvements to cull and actors code made things worse, noticed it in a triple run (vulkan-opengl-vulkan) of C3M1_A from UDBuilder and I always get crazy spikes until I reach a zone without many actors... and when I return to the prisoner's courtyard after the first load, things gets a bit better, but indeed worse than how it felt previously @AFADoomer 
Gonna playtest again to be 100% sure, now from ipk3.

**Comment by AFADoomer** [comment]
What about if you lower the boa_cullrange value?

**Comment by Ozymandias81** [comment]
It seems that if I change cullrange, things slowdown for a while, let's say 30 secs, then gets better... but then if I leave a zone that I have already visited, let's say surrounded with trees, if I leave it far enough then get back there again, slowdown happens again and it takes 30-35 secs to get acceptable framerate again. Mind you, this is under ipk3, vulkan and rendering distance for everything at 2048, while playing with cullrange between 8192 and 2048, no PPShaders enabled (I even did a run with them but wasn't bearable for me). Some shots with also some profilethinkers, I also forgot to show you a screenshot where I got 29.0 for ColorGrade under Titlemap (and it got some spikes there too, until I removed PPShaders).

![Screenshot_BoA_20210416_175334](https://user-images.githubusercontent.com/11136108/115052252-06444d80-9ede-11eb-8e46-e8a1bfd49f00.png)
![Screenshot_BoA_20210416_175350](https://user-images.githubusercontent.com/11136108/115052276-0d6b5b80-9ede-11eb-86c0-48296b43d973.png)
![Screenshot_BoA_20210416_175423](https://user-images.githubusercontent.com/11136108/115052287-11977900-9ede-11eb-9cc4-725fffb1717b.png)
![Screenshot_BoA_20210416_175745](https://user-images.githubusercontent.com/11136108/115052296-13f9d300-9ede-11eb-8cb8-453ed7666b56.png)
![Screenshot_BoA_20210416_175832](https://user-images.githubusercontent.com/11136108/115052297-14926980-9ede-11eb-9126-fe986e5af36f.png)
![Screenshot_BoA_20210416_175839](https://user-images.githubusercontent.com/11136108/115052300-15c39680-9ede-11eb-9d61-8b1951bbde32.png)

**Comment by Ozymandias81** [comment]
Now with properly updated drivers runs better, even with PPShaders on, but I noticed an issue between rendering distance and cull values: if I start the game with cullrange at 2048 and have rendering distance at 2048, it seem to work faulty with conelights, until I increase cullrange to something more than 2048 (tested with 8192). So I bet that if one starts with cullrange at 8192 can't be notice this problem. Seems to run fine, always 4.6 r195 ipk3.
![Screenshot_BoA_20210416_183026](https://user-images.githubusercontent.com/11136108/115056020-997f8200-9ee2-11eb-90e0-f7757fb0d006.png)
![Screenshot_BoA_20210416_183036](https://user-images.githubusercontent.com/11136108/115056047-a00df980-9ee2-11eb-9493-a9414cf064be.png)

**Comment by Tormentor667** [comment]
Good framerates :)

**Comment by Ozymandias81** [comment]
I have found the source of my issues with slowdowns, going to confirm and drop a line in a while... it doesn't belong to GZDoom or BoA btw, but something between my version of Github or DFX.

**Comment by AFADoomer** [comment]
That's ok.  This drove a lot of optimization that otherwise probably wouldn't have been in the release.

Thanks for tracking it down!

**Comment by Ozymandias81** [comment]
You are welcome! btw I noticed something: heat and sandstorm effects doesn't get deactivated from menues, I am redo cloning of several repositories so it will take a long time... 
Reminder for me: never use anymore old 3.3.6.1 because of just the presence of "synch" button, we can live without it!

**Comment by Tormentor667** [comment]
Are all issues here fixed so far?

**Comment by AFADoomer** [comment]
Effect givers should be good after 3bc70d6b510f8977aa8de4c466d42391048d25c1.
