### ISSUE TITLE
Lonely soldier

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#472]
Except for the very first mission, this guy doesn't get to say much to BJ, even after a mission. So give this lonely guy something to do !!!

![Screenshot_Doom_20210409_160937](https://user-images.githubusercontent.com/77861029/114273579-e9f66b80-9a1a-11eb-9fd2-3b8cc9ab3146.png)

**Comment by Ozymandias81** [comment]
He just gives clues, the map is already complicate and there is no need to overcomplicate thing near release date.

**Comment by x3003** [comment]
He could say 'Hello' to BJ after a mission, now he sits there doing nothing.

**Comment by Tormentor667** [comment]
That's actually fine. This guy is usually introducing BJ to the current situation at the beginning of each chapter.
