### ISSUE TITLE
Passage very hard

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#473]
I've done this level a few time (lowest level ofcourse), but this passage is somehow made very very hard, with lotsa dogs/soldiers and some mechs coming from the front and a lot more from down below. For me, pretty undoable w/o help. So a bit less would be appreciated.

![Screenshot_Doom_20210410_125708](https://user-images.githubusercontent.com/77861029/114273643-32158e00-9a1b-11eb-9054-98d3f09f6f1a.png)

**Comment by x3003** [comment]
Git version from 06/04 and gzdoom x64-g4.6pre-195-g55ce0510c

[save8.zip](https://github.com/Realm667/WolfenDoom/files/6290057/save8.zip)

**Comment by Tormentor667** [comment]
The right strategy is letting the door open and then move backwards and look for cover while attacking the ambush with your Nebelwerfer.

**Comment by x3003** [comment]
I've played it a few times now (w/o having to hide and take cover) and I never failed upon this time, so something has changed for the worse....

**Comment by Tormentor667** [comment]
You mean you played that area before already?
