### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#474]
As you might have already seen, some of our translations are incomplete and I am pretty sure that they won't be finished for our release date on April 30th.

Link: https://docs.google.com/spreadsheets/d/1Nok0lZ7fX9mKLRf7TItqsllhdIVSC8jt_L9otCBP0bs/edit#gid=699002033

So, I wonder what we should do here? Not including unfinished translations doesn't seem right to those who spent so much time in writing them, but people should know that they play an "unfinished localization" somehow.  So could we add an identifier that displays a message next to the "Language" option that displays how much percentage is finished of this particular selected language?

@AFADoomer @Talon1024

**Comment by AFADoomer** [comment]
Added some custom handling for the language selection menu item in 1b59e891ec27cdf6e1d0d1655c59fa4fbff96633.  Just need to make sure that we keep the completion percentage line in LANGUAGE for the final release.

I can add a line underneath the entry to explain the number also, just need the LANGUAGE entries added.

Related:  Our MENUDEF was last updated before the engine added the simplified menu system...  Should we re-work our base menu to be simplified as well?

**Comment by Tormentor667** [comment]
Thanks for adding this. I am not sure if we even need an explanation or if it is self-explanatory. 

Regarding the simplification: I agree, we should incorporate that.

**Comment by MuadDib90** [comment]
> 
> 
> Added some custom handling for the language selection menu item in [1b59e89](https://github.com/Realm667/WolfenDoom/commit/1b59e891ec27cdf6e1d0d1655c59fa4fbff96633). Just need to make sure that we keep the completion percentage line in LANGUAGE for the final release.


Looks good. I don't think it needs any extra explanation. :)
