### ISSUE TITLE
Switch shouldn't open door

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#476]
In c2m6_b you come across this switch (last room, where the 2 gestapo agents walk). This makes the underwater switch useless, as it also opens the door.
In the previous release you had to go underwater to open the door, but with this switch activated, you don't have to do that anymore, you just go from one door to the other and continue.
As a suggestion maybe this switch could be removed or else activated by the underwater switch.

![Screenshot_Doom_20210411_132720](https://user-images.githubusercontent.com/77861029/114442517-ea366880-9bcc-11eb-8051-4c5ad932a29e.png)

**Comment by Talon1024** [comment]
Going underwater is optional; you only get a couple of grenades and stimpacks out of it.

**Comment by Tormentor667** [comment]
Going underwater is optional; you only get a couple of grenades and stimpacks out of it.

**Comment by x3003** [comment]
Were is the fun not going under water and mess w/ the sharks ?

**Comment by Tormentor667** [comment]
You can if you want to :)
