### ISSUE TITLE
Glitch I discovered (late post sorry))

### ISSUE THREAD

**Issue by Wolfenburger** [Realm667/WolfenDoom#477]
After talking to the local town drunk in the bar after the Stahlhimmel level, I was able to pull my guns out while in HQ, they re-conceal themselves though. I tried to recreate this on other chapter inter maps and couldn't for some odd reason. This seems like a very miniscule glitch, that doesn't truly effect anything. But I did find it funny to hold the store keep at gun point.

"GIVE ME ALL YOUR VITALITY SERUMS NOW!"

![Screenshot_BoA_20210405_155936](https://user-images.githubusercontent.com/77998291/114563402-6072b380-9c3d-11eb-9211-3b1f7bf48c73.png)
![Screenshot_BoA_20210405_155946](https://user-images.githubusercontent.com/77998291/114563406-610b4a00-9c3d-11eb-9ca4-2e3be9c584b2.png)
![Screenshot_BoA_20210405_160017_01](https://user-images.githubusercontent.com/77998291/114563409-61a3e080-9c3d-11eb-8690-49fbde7a47c3.png)

**Comment by Ozymandias81** [comment]
Which branch of BoA did you encounter this issue? And GZDoom version? So you didn't went to Training zone at the very start but after?

**Comment by Tormentor667** [comment]
Can you also please explain a way to recreate that issue?

**Comment by Talon1024** [comment]
> Can you also please explain a way to recreate that issue?

Buy a weapon from the shop, and select it using its slot number or pressing the next weapon/previous weapon key(s).

**Comment by AFADoomer** [comment]
Weapons are coded to automatically lower when in HQ.  I think the bigger issue is why his inventory wasn't stripped leaving Stahlhimmel...

**Comment by Tormentor667** [comment]
> Buy a weapon from the shop, and select it using its slot number or pressing the next weapon/previous weapon key(s).

The weapon gets shown but I can't fire it and it gets instantly lowered again.

**Comment by Wolfenburger** [comment]
> > Buy a weapon from the shop, and select it using its slot number or pressing the next weapon/previous weapon key(s).
> 
> The weapon gets shown but I can't fire it and it gets instantly lowered again.

This. I didn't feel it to be a huge broken issue, because you can't fire. Nor is there really any downside to it. It may break immersion for some. But we can't make everyone happy.

**Comment by AFADoomer** [comment]
This is literally intended behavior.

You're just never supposed to still have most of your weapons in the intermission map.

**Comment by Ozymandias81** [comment]
In fact if you try to throw grenades, it says to you if you are mad or not.
