### ISSUE TITLE
Enemies notice you after they died

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#479]
Playing 'mein leben', enemies that are killed notice the player (getting the exclamation mark) after they get shot. Is there still life after death after all ?

![Screenshot_Doom_20210413_232359](https://user-images.githubusercontent.com/77861029/114628087-9d2ec100-9cb6-11eb-839d-1ed8a53df0ac.png)

**Comment by AFADoomer** [comment]
Fixed in eebf6c9d0149fd47c2affc1d67580129dfb4df15.
