### ISSUE TITLE
Visual indicator for actor spawners using 3d models

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#480]
I thought suggesting this should be a good thing, specially in terms of "consistency", but I am still brainstorming about what could be the best solution... maybe set an additional Arg over ActorSpawner which allows us to "drop in place" necessary object to distinct among kind of spawners (zombies, soldiers, astrostein) so we don't see enemies pop-up all of a sudden but instead from a distinct thing itself? And if yes how should it look? I thought it would be cool to have sort of "colored rings" that have a bullseye on their center and which their color represent chosen kind (human=red, zombies=zyklon, astrostein=yellow, mutants=purple). It came to my mind while fixing zombiefied Ryan battle on c3m6_B, where ZGermanShepherd actors spawner are over SoulFountains

**Comment by Tormentor667** [comment]
Good suggestion for future modders.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 Maybe we can simply add a decorative actor which could be placed over the ActorSpawner. Colored rings with a bullseye seem a good way, I remember that Stronghold has similar sprites for its goal actors. The actor can have a fixed colour (grey), and the necessary colours could be added via UDMF properties...

**Comment by AFADoomer** [comment]
This feels like it would be kind of arcade-ish in comparison to the rest of the mod...  The actor spawners shouldn't spawn when a player can see them - though maybe I need to update the light level/visibility code.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer If you make this change, it would mean a rework of the wave areas on C1M5 and C3M2; though maybe that's for good. Also a player who knows where the spawner is would be able to circumvent spawning by going to its visibility range, if its spot could be reached.

**Comment by AFADoomer** [comment]
The behavior is already in place...  I would just be tweaking the visibility thresholds.

**Comment by Ozymandias81** [comment]
My idea was to "hide" enemies being spawned all of a sudden, so AFADoomer suggestion is indeed a great solution

**Comment by AFADoomer** [comment]
The light level detection of the spawners should be better as of 76ba9e128e8802053e96f07557b886107f459684.

I had to balance this so that I didn't break existing setups, so it's a little generous in defining what the "can't be seen" threshold is, unfortunately.
