### ISSUE TITLE
Glitches when moving

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#482]
When moving on some positions, the game flashes shortly.
To reproduce load the file w/ yesterday's git version, then walk over the opening, fast turn 180 degrees and walk back. You should see a yellow flash. But it can also flash when walking over a body who has been shot.
It's w/ vulkan and opengl.
Dunno what has changed, but it wasn't there a few weeks ago.

[flash.zip](https://github.com/Realm667/WolfenDoom/files/6321385/flash.zip)

**Comment by AFADoomer** [comment]
I cannot recreate this.  There are multiple portals in the area, including a skybox outside of the windows, so this may be hardware dependent.

For anyone who cannot load the save, it's the upstairs part of the main building at the start of C3M1_A (with the miniature camp skybox visible out the windows).

**Comment by x3003** [comment]
It's not only there, but also on other places.
When you go down the stairs (on the savegame), you see the 2 bodies, when walking/running over them, the first time it also glitches.
And there are some other places as well
Quite annoying.

**Comment by AFADoomer** [comment]
It sounds like your computer is having problems with rendering portals when you cross portal lines...

**Comment by x3003** [comment]
Well, it shouldn't. It's running at 60 fps and the driver is updated.

**Comment by AFADoomer** [comment]
Yeah, especially if it wasn't doing this before.

**Comment by x3003** [comment]
I think someone over here has a 1030 (instead of a 1060). Maybe he can check w/ updated drivers if it's the game or else the driver could have a bug.

**Comment by Ozymandias81** [comment]
It's me with 1030, and I have indeed updated drivers... Will check when I can, meanwhile: gzdoom version?

**Comment by Ozymandias81** [comment]
I don't get any issues with my configuration, so idk what's going on.

**Comment by x3003** [comment]
It's the latest dev of gzdoom, but also with v4.5.0.

**Comment by AFADoomer** [comment]
Interesting...  Is there any way that you could record a video so that we can see what you are experiencing?

I assume there's no change for you with current dev build of BoA?

**Comment by x3003** [comment]
No change w/ the latest build.

Small recording:

[SAM_3698.zip](https://github.com/Realm667/WolfenDoom/files/6326322/SAM_3698.zip)

**Comment by AFADoomer** [comment]
What happens when you disable post processing screen shaders (the film grain, vignetting,etc.)?

**Comment by Ozymandias81** [comment]
Pardon I see there are video drivers from 14/04 and I have instead 465.89. Gonna test again.

**Comment by Tormentor667** [comment]
I had similar issues with other portals that aren't reproducable. I have the feeling that sometimes the portal code from GZDoom as problems. You sometimes can see the own player sprite for a milisecond of time.

**Comment by x3003** [comment]
>What happens when you disable post processing screen shaders (the film grain, vignetting,etc.)?

Still the same.

**Comment by AFADoomer** [comment]
I do not know if these can be resolved...  There are too many hardware-dependent variables in play.

**Comment by Username-N00b-is-not-available** [comment]
https://github.com/Realm667/WolfenDoom/issues/465#issuecomment-828982607
