### ISSUE TITLE
Pick up clue freeze

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#484]
When picking up a clue, the game freezes for a second or so. Is this by design ?

![Screenshot_Doom_20210416_014521](https://user-images.githubusercontent.com/77861029/115069289-a8bafb80-9ef3-11eb-86ec-05e22d11c121.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Could it be because of the autosave?

**Comment by AFADoomer** [comment]
This is almost certainly because the clue items force an autosave on pickup.

**Comment by x3003** [comment]
Autosave is always off here. Or is the game forcing the autosave ?

**Comment by AFADoomer** [comment]
The game forces it.

**Comment by Tormentor667** [comment]
Not a bug then.

**Comment by x3003** [comment]
Not a bug, but forcing an unwanted autosave isn't good either.

**Comment by Tormentor667** [comment]
Well, the whole purpose of an autosave is, that it is unwanted :-D
