### ISSUE TITLE
Entry is blocked

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#488]
The secret passage is somehow blocked. No way to get in, except clipping.

![Screenshot_Doom_20210417_090629](https://user-images.githubusercontent.com/77861029/115106623-2ae40800-9f66-11eb-88c0-0523196a74ee.png)

**Comment by Tormentor667** [comment]
You can find two switches in the rooms where the dogs are in. As soon as you hit both of them, a secret switch appears behind the Realms of Arkania image. Use that and the entry opens.

**Comment by x3003** [comment]
I found the 2 switches already, but wasn't aware of the 3rd.

**Comment by Tormentor667** [comment]
I made it a bit more obvious in my new commit.
