### ISSUE TITLE
Fontchars issue

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#489]
@Talon1024 I just got that notice after updating the language file:
<img width="797" alt="2021-04-17_125413" src="https://user-images.githubusercontent.com/10298439/115110509-1448ab80-9f7c-11eb-9bac-862126f1f724.png">

**Comment by Talon1024** [comment]
The problem seems to be the `git commit` line, which is returning a non-zero exit code because there are no changes to fontchars.csv.
