### ISSUE TITLE
Scary "Horst Wessel" song in C3INTRO not being played

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#490]
No idea why but the "scary Horst Wessel song" in C3INTRO is still not being played for me @AFADoomer

**Comment by AFADoomer** [comment]
It's set up as an ambient sound, is relatively quiet, and the volume is scripted to fade in and out at random levels...  I intended this to be a "am I really hearing music" situation for the player, not a soundtrack.  I can begin to hear it after standing at the spawn location for a few seconds.

**Comment by Tormentor667** [comment]
Do you think it makes sense to make the effect less subtle? I really like it now that I have tested it by waiting for the right moment, but I fear that many players will miss it.

**Comment by AFADoomer** [comment]
Up to you.  I can increase the audio file's volume and cap the minimum volume above zero.

**Comment by Tormentor667** [comment]
Yes, I‘d go for that

**Comment by AFADoomer** [comment]
This should be good now.
