### ISSUE TITLE
Actors still behave a bit dumb

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#491]
With this house the actors, inside and out 'think' they can shoot each other through the walls. Ehhh ?!

![Screenshot_Doom_20210417_141425](https://user-images.githubusercontent.com/77861029/115117618-d198ca80-9f9f-11eb-8805-a6962abbc498.png)

**Comment by Ozymandias81** [comment]
Please always use imdypos true as console command and indicate the map

**Comment by x3003** [comment]
Oh, I'm already past it in the savefile, but it's on c3m6_a
