### ISSUE TITLE
AI is clueless what to do

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#492]
In c3m6_a, when I want to go into this building, the ai player usually (9/10 times) jumps over the railing and gonna run until I pick him up again. 
Same when you go down the ladder into the zyklon c ruins a bit later on, he just won't come up again.
Maybe he needs a 'come here' command.

![Screenshot_Doom_20210417_073647](https://user-images.githubusercontent.com/77861029/115117725-5552b700-9fa0-11eb-8ae0-109f6f30e855.png)

**Comment by AFADoomer** [comment]
I have no idea where this is.

**Comment by AFADoomer** [comment]
He just followed me into that room just fine...  

Even if he doesn't immediately follow you, this isn't game-breaking.  He will always catch up if/when you get far enough ahead of him (he follows path nodes that trace the player's steps; if he falls more than 150 nodes behind the player, he will teleport halfway ahead to the 75th node and continue catching up from there).

**Comment by x3003** [comment]
Well, with me, he doesn't listen very well. I have to go backwards in the room, 1 step at a time to make sure he follows.
