### ISSUE TITLE
C2M1 (but maybe not only this one)

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#493]
When you start the Prison Break map (C2M1) and make a noise at the beginig of the map, guards don't shoot you through the doors with bars... they did like month ago and even earlier.

Is this intentional or not?

[2021-04-17_19-33-20.zip](https://github.com/Realm667/WolfenDoom/files/6329713/2021-04-17_19-33-20.zip)

GZDoom R195
Latest github repository

**Comment by AFADoomer** [comment]
This is possibly related to the recent work to add blocking flags to polyobject door lines.

**Comment by MuadDib90** [comment]
OK.
So, the question is, are we want to keep it that way, or change this behavior (to the previous state)?

**Comment by Tormentor667** [comment]
Damn I didn’t think about grate doors when I did the search-and-replace method for poly doors. 

This should at least be changed back for doors with bars indeed. I will look through the maps tomorrow.

**Comment by Ozymandias81** [comment]
You already working on it @Tormentor667 ? Because I can give it a go over C1 atm.

**Comment by Tormentor667** [comment]
You can begin with C1 if you want to, I can start with C2 then and continue with C3 after my webpage fixes.

**Comment by Ozymandias81** [comment]
Working on it

**Comment by Tormentor667** [comment]
Well done
