### ISSUE TITLE
exit of the tunnel is moved

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#494]
In c3m6_a the exit of the tunnel has moved somehow.

The start is here:

![Screenshot_Doom_20210417_211836](https://user-images.githubusercontent.com/77861029/115124523-f94d5a00-9fc2-11eb-8da0-1e4d68440fc1.png)

But instead of moving to the exit here (oops, almost shot myself)...

![Screenshot_Doom_20210417_211642](https://user-images.githubusercontent.com/77861029/115124534-1124de00-9fc3-11eb-9a98-c34b601af0bc.png)
 
You're taken over here, surrounded by the enemy:

![Screenshot_Doom_20210417_211857](https://user-images.githubusercontent.com/77861029/115124619-6234d200-9fc3-11eb-8021-7675e5848da5.png)

I have the built from yesterday, so it could be fixed already.

**Comment by MuadDib90** [comment]
Yes, it should be fixed now as the commit suggest:

![obrazek](https://user-images.githubusercontent.com/73436978/115124818-90ff7800-9fc4-11eb-840e-4d2d09bf1125.png)

**Comment by x3003** [comment]
Ok, I don't read every commit or understand them.

**Comment by Tormentor667** [comment]
Was my fault but fixed it.

**Comment by MuadDib90** [comment]
> 
> 
> Ok, I don't read every commit or understand them.

Yeah, sure, I didn't mean to be rude. Just wanted to present an evidence.
