### ISSUE TITLE
Slowdown on a certain spot

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#495]
In c3m6_a when i'm on a certain spot the fps drops by half. When i'm walking down a bit, it's back to 60 fps.
Dunno what's so special about this spot, coz nothing is happening over there.

![Screenshot_Doom_20210418_001217](https://user-images.githubusercontent.com/77861029/115128148-01fe5a00-9fdc-11eb-97ab-b1c84cdd9358.png)

![Screenshot_Doom_20210418_001240](https://user-images.githubusercontent.com/77861029/115128152-062a7780-9fdc-11eb-8fb7-963db907c12b.png)

**Comment by AFADoomer** [comment]
You are crossing a portal boundary when you walk down the stairs.

**Comment by x3003** [comment]
Could be, but why the big drop in fps upstairs ? There's nothing, read: no enemy left upstairs.

**Comment by Tormentor667** [comment]
It’s the level geometry that’s responsible here.

**Comment by AFADoomer** [comment]
It has nothing to do with the enemies.  It's the rendering of the huge outdoor area in that map combined with rendering the other side of the line portal there that is causing your machine to lag.
