### ISSUE TITLE
Webpage overhaul

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#496]
We have lots of useful information on the website, but some of it had been there for a long time and became quite outdated:
- [x] The F.A.Q. refers to Chapter II distribution, it needs to be rewritten.
- [x] Most Chapter I and Chapter II screenshots on the Media page are outdated (the locations have changed, and they contain old sprite enemies). I would like to go through the process of shooting new ones in the same locations, but for that please tell me which rendering/postprocessing settings I should use for them. The ones that are present use an xBRZ-type scaling and apparently also filtering, must these settings be preserved? May I take 1920x1080 pictures, rather than 1280x720 (if yes, then I'll also handle Chapter III ones)? Should we put old screenshots onto a separate page?
- [x] The Downloads section should obviously have only one link, since Blade of Agony is now standalone.

More nitpicks coming soon...

**Comment by Tormentor667** [comment]
Fun fact: I noticed that yesterday as well and thought about updating that stuff.

- I will take care of the F.A.Q. today.
- For the Chapter 1-3 screenshots, feel free to create a complete new set, simply use the "standalone" settings for these and make sure to max out the performance options.
- Same here, will take care of today.

**Comment by Tormentor667** [comment]
Fixed the download and faq page just now.

**Comment by Username-N00b-is-not-available** [comment]
Good, when I have a little bit more time (today/tomorrow) I'll try to deal with the screenshots.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 [Here](https://mega.nz/file/vnxRhSzI#roqhz13HcZajlUshqtDDWEaaC1CbCZzm901hnJWvQtY) you are, 54 1920x1080 pictures for 100MB total. For them, I switched off vignette and pixelated film grain, but everything else was IIRC left as default on maximum settings. @Ozymandias81, I would like to ask you for help with this: could you please run PNGCrush on screenshots from this archive and reupload the result if the size reduction turns out to be significant?
***
I think some more trivia in addition to 9 C1/C2 items we have now would also be nice. @Tormentor667, which references from C3 would you like to add there?

**Comment by Tormentor667** [comment]
No need to crush the screenshots, I will take care of the web optimization for the page. 

Regarding trivia: Feel free to collect what you want and consider worth :) I will add it for you.

**Comment by Tormentor667** [comment]
Just uploading the screenshots, fantastic workd @Username-N00b-is-not-available !

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667, the C2 section on the site contains 17 pictures ATM. It seems you forgot the C3M6_A image with a dog near the frozen sea (timestamp 220213).

**Comment by Tormentor667** [comment]
Updated :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 As for the trivia, I would personally like to add information on the following references/homages:
- C3M0_A: the Resident Evil series
- C3M0_B: books and movies about Stierlitz
- C3M6_B: RTCW inspiration in the castle interiors
- SMxx: well, this one is obvious.

Messages:
- C3M0_B: 
Under Müller's thumb
Max Otto von Stierlitz is the main character in the most famous Soviet book and TV spy fiction series? His incredible luck did not follow him to Blade of Agony's world...
- C3M6_B:
Castle Wolfenstein
interiors of the last map were strongly inspired by the beginning of a popular early-2000s Wolfenstein game?

I'm not sure what to write about RE and CK... (But I'll make images for all 4 messages tomorrow.)
Maybe I have also missed something important.

**Comment by DoomJedi** [comment]
I can help with anything Keen-related

**Comment by Tormentor667** [comment]
I am okay with this Trivia. Do you want to add it yourself?

**Comment by DoomJedi** [comment]
Did you know? Billy Blaze, aka Commander Keen is BJ grandson.

Did you know? Commander Keen series still has active modding community, which also helped us with additional Keen art for the mod.

Did you know? All Keen art used in BoA came from a single Keen game "Secret of the Oracle" (first part of "Goodbye Galaxy" trilogy), which was distributed for free as shareware.

Did you know? Enemy rotations didn't exist in the original Keen game and were made specifically for this mod

Did you know? The big green Dopefish appeared since the release of the original game as an easter egg on many other media, including recent "Doom Eternal".

...can make more.

**Comment by Username-N00b-is-not-available** [comment]
Thanks, @DoomJedi! I think I'll choose the one about rotations.
That leaves us with Resident Evil... @AFADoomer, would you like to suggest anything?
***
@Tormentor667: yes, I think I am able to do it myself. I'll make and add the three trivia pieces now.

**Comment by Tormentor667** [comment]
Well done, I think we can close this :)

**Comment by DoomJedi** [comment]
"there were no enemy rotations in the original Keen game? They were made specifically for Blade of Agony."
Should we add ... "...by pixel masters of Keen modding community"?

**Comment by DoomJedi** [comment]
Should we also reference Cook identity in Trivia?

**Comment by Username-N00b-is-not-available** [comment]
![Screenshot_BoA_20210421_214456](https://user-images.githubusercontent.com/59409713/115605165-dbe1fe00-a2ea-11eb-93c8-5ca6411e0f44.png)

@DoomJedi What would be your suggestion on the accompanying text for the Chef Team?

**Comment by DoomJedi** [comment]
Be merciful with the Chefs, they cooked a great mod for you :)

**Comment by Tormentor667** [comment]
Very nice :)

**Comment by DoomJedi** [comment]
You even improved upon my phrasing :)

...we hint at many secret maps there, maybe Amber mission deserves a hint too?

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi There is one about Stierlitz, and it hints right at the C3M0_B ending which leads to Stierlitz imprisonment in BoA.

**Comment by Username-N00b-is-not-available** [comment]
Bumping this issue with some more questions/suggestions:
- Should we return the Totengraeber description to https://boa.realm667.com/index.php/info/characters ?
- @Talon1024 should probably update the Linux subsection in https://boa.realm667.com/index.php/help/f-a-q when flatpak and snap are done.
- Still need more info on screen shaders in https://boa.realm667.com/index.php/help/docs (on activation and effect of the items).
- The 'Bringing the experience to perfection' news article on the main page has a broken image link.

**Comment by Tormentor667** [comment]
>     * Should we return the Totengraeber description to https://boa.realm667.com/index.php/info/characters ?

No, he is not of that importance.

>     * Still need more info on screen shaders in https://boa.realm667.com/index.php/help/docs (on activation and effect of the items).

I'd point @AFADoomer and @Talon1024 towards this (even though it's lower priority atm)

>     * The 'Bringing the experience to perfection' news article on the main page has a broken image link.

Fixed :)

**Comment by MuadDib90** [comment]
> 
> 
> ![Screenshot_BoA_20210421_214456](https://user-images.githubusercontent.com/59409713/115605165-dbe1fe00-a2ea-11eb-93c8-5ca6411e0f44.png)
> 
> @DoomJedi What would be your suggestion on the accompanying text for the Chef Team?

Although late, but... so F*** cool!  Awesome guys! :)       
 (BTW where is it from? Shawarma? :D )

**Comment by Username-N00b-is-not-available** [comment]
The screenshot is taken in C1M2 (the kitchen under the Arbeit und Brot sign is the workplace of Dean Dosenwurst).

**Comment by Username-N00b-is-not-available** [comment]
Since there is no mod package for 3.0 (and both links on the download page lead to ModDB anyway), the mod package block should probably be deleted. Nitpicks on the Standalone paragraph: the file size is shown as 755 MB on ModDB (but 765 on the site), and the executable is named `Blade of Agony Launcher.exe`.

**Comment by Ozymandias81** [comment]
It is 754 if we wanna be extremely nitpicky :tongue: 
![image](https://user-images.githubusercontent.com/11136108/116778569-edf23800-aa72-11eb-950d-7b0d97cce8da.png)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Not website-related, but:
![image](https://user-images.githubusercontent.com/59409713/116815923-83bbbf00-ab68-11eb-98dd-0dc9d4f8a903.png)
Does this still hold?

**Comment by Ozymandias81** [comment]
From this repository yes, from released material no but modders always need to ask for permission first, in both cases.

**Comment by DoomJedi** [comment]
I did post on wolf3d that after release resources are free for credited modding use.
This at least refers to my art and was pre-agreed during boa development, not to say promised to me.
Also same was told by torm to spriter's resource site where boa art was posted, after 30 of April all is legit.

**Comment by Tormentor667** [comment]
Exactly
