### ISSUE TITLE
Ship the game with what GZDoom version?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#499]
The title says it all I guess.

**Comment by alexey-lysiuk** [comment]
Convince Graf to make a new release 😉

**Comment by Tormentor667** [comment]
Well, I dropped him a line ;)

**Comment by Ozymandias81** [comment]
We also must ask if it is good to have Vulkan as preferred backend or it is better to keep OpenGL (atm vulkan is preferred)

**Comment by Tormentor667** [comment]
I will open a thread at ZDoom

**Comment by Ozymandias81** [comment]
I see, cool then no need of preferred backend it seems.

**Comment by Tormentor667** [comment]
Well, the renderer issue has been discussed but I still wonder which version to use. I asked Graf Zahl but there is no stable version planned, so sould we just stick to the latest dev version instead?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Will 4.5.0 or the latest bugfix release version run Blade of Agony?

**Comment by AFADoomer** [comment]
The mapinfo keyword to disable ambient occlusion in skyboxes was not introduced until after 4.5.0, which is (I think) the only real hurdle to releasing with that version.  Otherwise, I think everything functionally works just fine.

**Comment by Tormentor667** [comment]
Could we compile our own 4.5.0 and include that single additional feature or what would youveuggest?

**Comment by Ozymandias81** [comment]
Chapter 2 release was shipped with a somewhat broken release of GZDoom which was published as stable, so I suggest to do this: release BoA on 30th april with the last available devbuild version from that day (but let's test first), and then we'll release 3.1 once a new stable version of GZDoom is out.
In the future we should also get rid of nashshadows when they'll be merged on GZDoom itself too.

**Comment by Tormentor667** [comment]
Yeah, we can go for that.

**Comment by Username-N00b-is-not-available** [comment]
We should be careful with the _latest_ devbuilds, there is at least one [quite critical bug](https://forum.zdoom.org/viewtopic.php?f=2&t=72085) related to save overwriting currently present in GZDoom, and there is no guarantee that it will be fixed until Apr 30.

**Comment by Tormentor667** [comment]
Then we use the version before?

**Comment by DoomJedi** [comment]
Yes, as we cannot allow such critical bug in. One version before that bug appeared.

**Comment by alexey-lysiuk** [comment]
> We should be careful with the _latest_ devbuilds, there is at least one [quite critical bug](https://forum.zdoom.org/viewtopic.php?f=2&t=72085) related to save overwriting currently present in GZDoom, and there is no guarantee that it will be fixed until Apr 30.

The fix is pretty obvious. I explained why I didn't do it myself in the linked topic.

**Comment by x3003** [comment]
The commit that broke the saving was 6 days ago, so an older build from at least 7 days ago should be fine.
So gzdoom-x64-g4.6pre-195-g55ce0510c should work.

**Comment by Tormentor667** [comment]
Then let's set it to this version for any further testing: https://devbuilds.drdteam.org/gzdoom/gzdoom-x64-g4.6pre-195-g55ce0510c.7z

**Comment by x3003** [comment]
I tested it with boa/doom2/freedoom and it works as expected.

**Comment by x3003** [comment]
The latest gzdoom version has a temp fix for this. [https://github.com/coelckers/gzdoom/commit/869532538325c27b4226644ff0991c4feee466ad](url)
Seems to work fine over here.

**Comment by Tormentor667** [comment]
So, how much sense does it make to use that version that might introduce new bugs?

**Comment by Ozymandias81** [comment]
In fact using it may cause more [it seems](https://github.com/Realm667/WolfenDoom/issues/524#issuecomment-827843930), I don't get such issue under r195 for example.

**Comment by Tormentor667** [comment]
Then we stick to r195.

**Comment by Tormentor667** [comment]
For v3.1 we can stick to the latest stable official release.
