### ISSUE TITLE
Dogs damaged by tanks will infight them.

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#500]
Dogs at the end of C1M2 got damaged by a tank blast, they ran to the tank and started biting it... Funny. Intended? XD

**Comment by Ozymandias81** [comment]
I guess it is related with recent updates for bullets and tanks.

**Comment by AFADoomer** [comment]
It has always been this way.  The dogs (and all other Nazi actors) attack the last thing that harmed them if it is a monster/living enemy.

**Comment by AFADoomer** [comment]
Should be good after 14a2770b377587d7f5d38373f1617aced0e76b8d.  If not, I'm not worried about it.
