### ISSUE TITLE
C3M1_A: Missing/blank window textures

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#503]
Missing window textures near the end, in the room with Dr. Schabbs jr. and the last clue of the level.
![Screenshot_BoA_20210422_201424](https://user-images.githubusercontent.com/20642121/115765942-a64f1a80-a3a7-11eb-9415-8d98c89c2710.png)

**Comment by Tormentor667** [comment]
The portal seems broken here. I thought I fixed that already. Which version did you play?

**Comment by pagb666** [comment]
I rebuilt my ipk3 like a couple hours ago.
