### ISSUE TITLE
C1M4: Dissappearing ground texture

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#504]
The floor texture in the clipping sector for this jeep pops in and out as you walk around it
![Screenshot_BoA_20210422_201503](https://user-images.githubusercontent.com/20642121/115766177-f332f100-a3a7-11eb-8bef-a0a7969fb003.jpg)

**Comment by Tormentor667** [comment]
Could be self-referencing sectors.

**Comment by Ozymandias81** [comment]
Looks like it is related to self-referencing indeed, but sadly doesn't happen on the other side of the jeep... Gonna remove there since there aren't also on the other side of the dam
