### ISSUE TITLE
Slowdown at a certain spot

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#505]
In the intermap there's a certain spot which causes a little slowdown, either when selecting the first level c1m1 or when you come back from a mission.
To reproduce select c1m1 and walk from douglas towards the headquarters. Some older builds also have it, but a bit less.

![Screenshot_Doom_20210423_012937](https://user-images.githubusercontent.com/77861029/115797535-75390f00-a3d4-11eb-9e64-e55336d9ef92.png)

**Comment by Ozymandias81** [comment]
It is always related to portals, the roof up there with the radar is a portal, which passes by all around the HQ external perimeter, also windows you see there with soldiers are portals too.

**Comment by x3003** [comment]
Could be, but it wasn't so obvious in previous builds.
