### ISSUE TITLE
Tutorial doesn't progress if grenade throwing misses

### ISSUE THREAD

**Issue by mcphail** [Realm667/WolfenDoom#506]
Hello everybody. I have been working on an updated snap for the release day, and made a build from git last night to have a quick playthrough. Apologies in advance if this issue is related to my build rather than the mod itself.

Problem:
If the player in doing the tutorial, if they miss the targets with the grenades they cannot progress or return easily.

Steps to reproduce:
- Start a new game.
- Head to DD in the tutorial area and follow his directions
- Complete the pistol and rifle rooms
- Pick up grenades in third room. Fail to hit all 3 targets when throwing and exhaust the grenades
- Note that gate ahead is closed, and that supply of grenades does not replenish

A new player is quite likely to miss with a few grenades until they learn the trajectory of a throw. I think the gate should open even if the room has been "failed". It is a bit early to punish a new player for a mistake, particularly as they are just learning the mechanics.

**Comment by Talon1024** [comment]
There should be a shelf full of grenades behind you. If you use that, you can pick up up to 3 grenades, and try again until you've destroyed all 3 targets.

**Comment by mcphail** [comment]
Apologies - it wasn't apparent the shelf would respond to the "use" key. It has been a long time since I played the mod and this wasn't obvious to me, as the grenades on the shelf behave differently to the other grenades (and the other weapons and ammunition experienced so far) which are picked up by moving towards them.

**Comment by Username-N00b-is-not-available** [comment]
I thought that in some earlier versions Douglas hinted at that you can take ammo/grenades from the shelves, but it is not true for now. Maybe it would be a good idea to add a hint to the third lesson (right into the text hint). Does anybody remember why it was removed @Tormentor667 @Ozymandias81, or it is just my false memory?
@mcphail While you are still here ;-) , I would like to ask you to tell us what you plan to change in the installation instructions for the snap package; could you please make a small general list of changes, so we could replace the outdated explanations in e. g. https://boa.realm667.com/index.php/help/f-a-q and similar places?

**Comment by mcphail** [comment]
> @mcphail While you are still here ;-) , I would like to ask you to tell us what you plan to change in the installation instructions for the snap package; could you please make a small general list of changes, so we could replace the outdated explanations in e. g. https://boa.realm667.com/index.php/help/f-a-q and similar places?

I think a simple link to https://snapcraft.io/boa would be enough, as that page would then give further instructions on installation. Whilst on the subject, I'll be updating that page for release but would also be happy for any changes to branding/presentation required as well. Furthermore, if anyone from the team wants to collaborate or take ownership of the snap or the snap store page, I'd be happy to oblige.

Best wishes to you all for the release!

**Comment by Ozymandias81** [comment]
Chapter 2 release had ExclamationMarks over stashes, gonna re-check again if C3 has the same thing, should be enough. And no there weren't informative messages, at least that's what I have noticed during the brief C2 gameplay I did for this shot.
![Screenshot_Doom_20210423_180328](https://user-images.githubusercontent.com/11136108/115899132-ae1dc600-a45e-11eb-98eb-017fc3f9ac91.png)

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 I just added the message about the shelf to the CSV, going to commit right now.

**Comment by Ozymandias81** [comment]
Meanwhile exclamations are not present on C3
![Screenshot_Doom_20210423_180913](https://user-images.githubusercontent.com/11136108/115899563-2b493b00-a45f-11eb-8ece-919e670763dd.png)
