### ISSUE TITLE
Cross appears too slow

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#507]
When you point the pointer to a friend, the red cross appears. But the very first time it's quite slow showing (needs loading in memory ?). It's not a problem for actors you can't shoot, but with the ones you can it is,  because the player sees these as enemies and shoot them before the cross appears.

![Screenshot_Doom_20210423_153120](https://user-images.githubusercontent.com/77861029/115888774-968d1000-a453-11eb-821c-1fb6b6d26f3a.png)

**Comment by AFADoomer** [comment]
That's intentional.  You can't immediately recognize a spy, etc.

**Comment by x3003** [comment]
Well, then they get shot....

**Comment by AFADoomer** [comment]
Then then don't be so quick to shoot...

Yes, the behavior is the same for all friendly actors.
