### ISSUE TITLE
Room should be darker

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#508]
In a room in c1m2, when you turn off all the little lights, the room becomes brighter, not darker...

![Screenshot_Doom_20210423_165109](https://user-images.githubusercontent.com/77861029/115889532-511d1280-a454-11eb-8a99-4b27bca3fa43.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 The table lamps are turned off when you first visit the area, so you turned them on ;-) It seems that your screenshot has an increased gamma, which could have tricked you into thinking that the lights are already on.
With gamma 1, the room is almost pitch-black (but it becomes quite okay when you switch on all the table lights).

**Comment by x3003** [comment]
In here I can light the room w/ this monitor, so I dimmed it to 50 %, so I needed to add some gamma while playing else I won't see a damn thing ;)

**Comment by Username-N00b-is-not-available** [comment]
Yeah, BoA has quite a lot of really dark areas. I also have brightness reduced (but on a laptop screen, not a monitor), though thankfully even with 20% brightness (which I am using right now) gamma 1.3 or 1.4 usually seems to help.

**Comment by Ozymandias81** [comment]
I tested it a day ago and everything was fine. Since I worked on those personally, I am sure that the place work as intended. Check this. (wait)

**Comment by Ozymandias81** [comment]
Lights there have been always with big radius I have to say, what I did during the common scripts porting (mirrors, lights etc) was this: applied tag to target external lights and applied then script call to tablelights, and this is present (without those bigger lights btw) quite everywhere on maps. It has been necessary to fix external pointlights that were applied over switchable actors, were before my changes they were just not changing during on/off. Now the thing is inversed, as dormant the TableLight is on with target pointlight off, and as soon as you turn one of them on, the object turns off and then pointlight is set on

![image](https://user-images.githubusercontent.com/11136108/115911355-440d1d00-a46e-11eb-8bf1-e7a503d7fdab.png)
![Screenshot_Doom_20210423_195852](https://user-images.githubusercontent.com/11136108/115911446-63a44580-a46e-11eb-8a83-052559f6b96f.png)
![Screenshot_Doom_20210423_195859](https://user-images.githubusercontent.com/11136108/115911450-656e0900-a46e-11eb-9365-121d3e0640d2.png)

**Comment by AFADoomer** [comment]
Should be working properly now.

You were correct, this was related to the culling addition...  The DORMANT flag is already toggled when the various culling base actors are activated/deactivated, so the toggling of the flag in the light actors that used to be necessary is now redundant.  It was effectively setting the DORMANT flag's value back, causing the lights to enter the opposite to correct state.

**Comment by Ozymandias81** [comment]
Thank you very much @AFADoomer :)
