### ISSUE TITLE
Training course glitch

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#510]
It happend to me by accident, and no one probably won't try this, and it is at the very begining of the game so starting again is not of a drama - on the other hand it can be solved prety easily I think, by adding an invisible wall into the door instantly after you enter the first room, until the grill rises up. So player can not be stucked on it and glitch won't happen. See video please.

https://user-images.githubusercontent.com/73436978/115952510-a275e200-a4e6-11eb-8c06-a8d65e7e4e4a.mp4

**Comment by Ozymandias81** [comment]
Will fix it
