### ISSUE TITLE
Bulletholes

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#511]
When you do the training course, when you shoot the gun, the targets looks like if they're shot with a shotgun.

![Screenshot_Doom_20210424_151723](https://user-images.githubusercontent.com/77861029/115960318-fe556080-a510-11eb-9689-1acc4b182d09.png)

**Comment by Username-N00b-is-not-available** [comment]
Intended by @Ozymandias81, he added this effect. The targets (and ones at C1M2) can easily be switched to 3dfloors (and aesthetically I would like that more), but such changes need a quorum from the core team.

**Comment by Tormentor667** [comment]
That's because of a "switch" texture that works like that. It's intended as it is now. If @Username-N00b-is-not-available is willed to take care of that, I am okay but it's low priority atm considering the release date in less than a week.

**Comment by Talon1024** [comment]
I'm not sure if realistic bullet holes in that texture would be even doable. Sure, GZDoom has decals, but AFAIK GZDoom's decals can't force parts of textures to be transparent, unlike in other more advanced game engines. On that topic, I don't think decals will appear on midtextures which block hitscans and/or projectiles.

I guess the closest we could do is split those lines into several 4px pieces, and make variants of that texture with bullet holes in them at each height. But that would be a lot of work for such a small detail.

**Comment by DoomJedi** [comment]
I will say more directly - this is not a kind of nitpick to deal with a week before release. Period.

**Comment by Tormentor667** [comment]
@DoomJedi is absolutely right here.
