### ISSUE TITLE
no cross shown

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#513]
At the end of c1m4, there's a cross for douglas, but not for ryan. Technical they are still in the same team, so.

![Screenshot_Doom_20210424_220007](https://user-images.githubusercontent.com/77861029/115971497-0e893200-a549-11eb-9deb-47084ff03ae0.png)

![Screenshot_Doom_20210424_220012](https://user-images.githubusercontent.com/77861029/115971502-11842280-a549-11eb-9ad6-43fe01e1d22f.png)

**Comment by AFADoomer** [comment]
Should be showing up after f43e95c44bdcca0c38bf153eff7fc2a0f7458c90.
