### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#514]
The first picture it is shown correctly, but not in the second one. The umlaut should be on the u from fur, not nur.
But in the second one, the word autorisiertes is correct, coz it's not not authorisiertes, like in the first pic.
[https://www.linguee.com/german-english/translation/autorisiertes+personal.html](url)

![Screenshot_Doom_20210424_213833](https://user-images.githubusercontent.com/77861029/115971561-66c03400-a549-11eb-9417-77f04b5f8bdd.png)

![Screenshot_Doom_20210424_213901](https://user-images.githubusercontent.com/77861029/115971591-9111f180-a549-11eb-8fd0-6cd01e3d89f0.png)

**Comment by Tormentor667** [comment]
Fixed

**Comment by x3003** [comment]
You fixed 1 sign partially.
Sign025 now says: 'authorisiertes Personal'. This is wrong,  both signs should read ' autorisiertes Personal'. So no **TH** for german words.

**Comment by Tormentor667** [comment]
Me = Idiot, fixed it and thanks for the hint :)
