### ISSUE TITLE
No cross on medic

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#516]
In c1m4, there's no 'red' [don't shoot] cross on this medic.

![Screenshot_Doom_20210425_165803](https://user-images.githubusercontent.com/77861029/115998517-e4d31800-a5e7-11eb-8151-39064eabd637.png)

**Comment by AFADoomer** [comment]
There's not supposed to be.

**Comment by Username-N00b-is-not-available** [comment]
I think @x3003 means the medic's initial state, when he has not already surrendered. I can confirm, this does happen with this medic on C1M4, for some reason the "don't shoot" crosshair is not displayed on him.

**Comment by AFADoomer** [comment]
But they don't ever have don't shoot markers on them...

**Comment by Username-N00b-is-not-available** [comment]
Oops, sorry, you are right...
