### ISSUE TITLE
Healthpack in the wrong place

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#517]
In c1m2, I think this healthpack is in the wrong place. It should be moved to the right side, coz when you open this door you might accidentally touch it when you really don't need it and save it for later.

![Screenshot_Doom_20210424_211727](https://user-images.githubusercontent.com/77861029/115998653-970adf80-a5e8-11eb-9a0b-707e0d35cf82.png)

**Comment by Username-N00b-is-not-available** [comment]
It is also quite easy to avoid it completely when pressing the switch, so I don't think this should be considered an issue. Same goes for a similar switch in C1M0.
***
If you are not reporting this for the sake of completeness, but are frustrated by such things yourself, you should try one of my addons, namely efficiency.pk3 ;-)

**Comment by x3003** [comment]
Not frustrated, but I tought it would be better on the other side, coz over there the player normally stand to avoid been hit (moving right & left).
