### ISSUE TITLE
Endstat

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#518]
In in endstats, could there be a stat of how many ppl the player spared ? Currently there's one how many were killed, but not how many were saved.

![Screenshot_Doom_20210424_212102](https://user-images.githubusercontent.com/77861029/115998789-34feaa00-a5e9-11eb-9f6c-f91835ff86a7.png)

**Comment by Tormentor667** [comment]
The addition might be interesting but I'd keep that for a 3.1 release or even an addon (we are planning addons anyway)
