### ISSUE TITLE
Red lights in the sky on C3M3_A

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#522]
![Screenshot_Doom_20210426_201936](https://user-images.githubusercontent.com/6550500/116187589-ce19e780-a6f3-11eb-99c2-4263ff8296d7.png)

**Comment by Tormentor667** [comment]
Portal overlapping?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 You are right, this _is_ related to portals.
The sewers secret under these lamps was added by me, and initially it was done with an interactive portal. Then in https://github.com/Realm667/WolfenDoom/commit/089f8de74dc1e9d7581f45fcb9cb51de3e83b998 it was changed to 3dfloors, and the lights which were placed on ceiling got attached to the sky.

**Comment by Tormentor667** [comment]
Ah, that explains everything. I changed that area into a 3d floor for better performance. I can remember that Graf Zahl suggested this change.
