### ISSUE TITLE
AI doesn't recognise some enemies

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#523]
In c3m5_a, these enemies (dressed up docs) won't get recognised by Ascher, so he won't shoot them.

![Screenshot_Doom_20210427_114135](https://user-images.githubusercontent.com/77861029/116221918-5d53e900-a74e-11eb-845e-5ded9994a201.png)

**Comment by Username-N00b-is-not-available** [comment]
For me, he does:
![Screenshot_BoA_20210427_192924](https://user-images.githubusercontent.com/59409713/116278180-edb21e00-a78e-11eb-9d9a-202de48070b9.png)
@x3003, could you please provide more details on this? What were your actions? Did you order him to stop and guard the area instead of following you?

**Comment by x3003** [comment]
> What were your actions? Did you order him to stop and guard the area instead of following you?

Yes, that's right. I know there are enemies coming, so I let him also shoot some for me. Then I can focus on the boss.

**Comment by Username-N00b-is-not-available** [comment]
Then you probably should have written this in the original post...
I can confirm that this happens, not only with `PlagueDoc`s, but with all enemies. Ascher just stands and watches the battle between the player and enemies.

**Comment by AFADoomer** [comment]
Interesting...  will troubleshoot tonight.  I've noticed some odd targeting when in god mode... Does this happen during normal (non-cheating) play?

**Comment by x3003** [comment]
I'm in non god mode. The latest game i'm with 2 other soldiers. They seems to attack alright, but not Ascher. He does nothing.

**Comment by AFADoomer** [comment]
Should be fixed in 5c3d79d1019c0fd14bcfb22bb1b43cb9670d7489.
