### ISSUE TITLE
Text color issues still exist

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#525]
Tried it with one of the disguised spies - I think it's not the same issue but a different one, tested with today's build and on C3M3_A
<img width="954" alt="2021-04-27_210747" src="https://user-images.githubusercontent.com/10298439/116298628-f6a9ec00-a79c-11eb-9b19-9e4c242a34de.png">

**Comment by AFADoomer** [comment]
Looks like I missed setting the default font color for the string.  Will fix tonight.

**Comment by Tormentor667** [comment]
Thank you Afa

**Comment by AFADoomer** [comment]
Should be fixed in 1ed125598b89a54f33860a35e1338c98250290fe.

**Comment by Tormentor667** [comment]
It works
