### ISSUE TITLE
Monsters can't see you (not a bug?)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#526]
In C3M3_A in the basement of the first building I noticed that the zombies can't see you - or it actually takes less distance to make them notice you. Is this because of the new code that is used in the battlefield map C3M4 so enemies don't shoot you if the fog is too strong?

<img width="953" alt="2021-04-27_212257" src="https://user-images.githubusercontent.com/10298439/116301029-ddef0580-a79f-11eb-8d4b-bf1068f93d54.png">

If yes, I'd suggest deactivating this for zombies of all kind or at least enemies should be able to "see" you (wake up) but not attack you if they are too far. Instead they try to reduce the distance.

**Comment by AFADoomer** [comment]
Are those enemies all supposed to be tagged as STANDSTILL?

Fixed some lighting/visibility issues in 7c3e599043da81ca24878e28aafd625ee86b5cd4 and 9a21a9b0faca3c48ad2a48fa1ce0581c18b06ced.

**Comment by Tormentor667** [comment]
Are they? I am pretty sure they shouldn’t at least

**Comment by AFADoomer** [comment]
They are.
