### ISSUE TITLE
Make the "Video Menu" available again

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#527]
Currently the "Video Menu" isn't available from our BoA simplified menu but it should, so people can choose a resolution and their renderer.

<img width="1002" alt="2021-04-27_213537" src="https://user-images.githubusercontent.com/10298439/116301727-a3d23380-a7a0-11eb-857f-14eb045b77f3.png">
<img width="1006" alt="2021-04-27_213547" src="https://user-images.githubusercontent.com/10298439/116301735-a59bf700-a7a0-11eb-90f2-c4d110aab031.png">

**Comment by AFADoomer** [comment]
It matches the built-in menus.  

I should be able to change that as well, though. 

As a possible 3.1 to-do...  would a single-page initial configuration screen that launches on first run to set basics like resolution and key binds be worthwhile?

**Comment by AFADoomer** [comment]
09fa1aa45a7ce390fc3ee1da404187a53ccf9af0 - Added the Video menu as the first option on the Display Options page (or it can be accessed from the full menu directly).

**Comment by Tormentor667** [comment]
> As a possible 3.1 to-do... would a single-page initial configuration screen that launches on first run to set basics like resolution and key binds be worthwhile?

Not sure if that’s really needed. I think people will always adjust their options first before playing, don’t they?

**Comment by AFADoomer** [comment]
It was just a thought.  Would give an opportunity to let newbies do setup without wading in the menus.  But not necessary.
