### ISSUE TITLE
Snap/Flatpak releases

### ISSUE THREAD

**Issue by mcphail** [Realm667/WolfenDoom#529]
Hi everyone. The end is in sight, and what a blast it has been to follow this project! Thanks to everyone involved in bringing this game from conception to reality.

I want to get the snap version, for Linux, ready for release day, and for it to be as close to your vision for the game as possible. I have a few questions, if that's OK?:
- Are we settled that the branding has changed from "WolfenDoom: Blade of Agony" to "Wolfenstein | Blade of Agony"? or is simple "Blade of Agony" alone preferred?
- Can I have formal permission to make the release on release day? As per chapter 2 release, can you give me permission for a specific commit or tag from the git repository, if possible?
- (As an aside, a temporary permission to release a pre-release version of the mod to the snap's "edge" channel would allow me to ask a few more people to playtest the snap before release, but this isn't essential in any way.)
- ~~For technical reasons which are too dull to bore you with, it will not be possible to bundle the exact gzdoom revision you are bundling with the main release on release day. I've made a build of gzdoom based on g4.5.0 with a couple of extra cherry-picked commits referencing the skybox AO feature which appears to run well enough on my playthrough. Hopefully I can bring the chosen version of gzdoom in a post-release update. Would this be acceptable to you?~~
- ~~Do you have favourite screenshots and gameplay videos I can link to on the Snap Store page?~~

There's currently about 6000 users of the Chapter 2 snap version. I'm hoping we can get "featured" status in the Snap Store to push this closer to 5 figures on release. Good luck with everything, and thanks for having me along for the ride :)

**Comment by Talon1024** [comment]
> * For technical reasons which are too dull to bore you with, it will not be possible to bundle the exact gzdoom revision you are bundling with the main release on release day. I've made a build of gzdoom based on g4.5.0 with a couple of extra cherry-picked commits referencing the skybox AO feature which appears to run well enough on my playthrough. Hopefully I can bring the chosen version of gzdoom in a post-release update. Would this be acceptable to you?

[This is the GZDoom revision](https://github.com/coelckers/gzdoom/commit/55ce0510c) we are bundling with the Blade of Agony Chapter 3 release.

**Comment by mcphail** [comment]
> [This is the GZDoom revision](https://github.com/coelckers/gzdoom/commit/55ce0510c) we are bundling with the Blade of Agony Chapter 3 release.

Yes - I'd love to use that if I could. But with the refactoring (and cmake requirements) of the gzdoom project post-4.5.0, this version doesn't build on the current stable version of the snap build system. At a push, I could build it separately and add it as a binary blob to the snap package, but I think Linux users are more likely to trust something with an audited traceable source build. I hope to rectify that whenever Canonical fix the build process for snaps built on their `core20` base, but these are currently segfaulting.

**Comment by Talon1024** [comment]
Well, a lot of other Linux users are saying that Snap is a proprietary system.

As for an "audited traceable source build", all of the GZDoom executables I built contain revision information. It's the first line printed to `stdout` and the in-game console.

On the other hand, I hope the Flatpak release of Blade of Agony goes more smoothly than the Snap release.

**Comment by mcphail** [comment]
@Talon1024 if you'd rather focus on Flatpak than Snap, I'm happy to step back. I have no preferences in the snap/flatpak debate, beyond that my experience is with snaps and they are easier to use on my distribution of choice. If they don't suit your project, focusing on flatpak is fine.

**Comment by Talon1024** [comment]
No, I would like the Snap and Flatpak releases to get equal consideration.

**Comment by Alexander-Wilms** [comment]
@Talon1024 I'm currently preparing the Flatpak, using the new ID com.realm667.Wolfenstein_Blade_of_Agony. Would you or another developer like to (co-)maintain the package?

**Comment by mcphail** [comment]
> As for an "audited traceable source build", all of the GZDoom executables I built contain revision information. It's the first line printed to `stdout` and the in-game console.

OK, I've added a blob of the chosen version of gzdoom. I'll try to get a proper build working when snapcraft irons out the kinks.

**Comment by Talon1024** [comment]
> @Talon1024 I'm currently preparing the Flatpak, using the new ID com.realm667.Wolfenstein_Blade_of_Agony. Would you or another developer like to (co-)maintain the package?

Yes, I'd like to co-maintain the Blade of Agony Flatpak package. We're planning to release a "3.1" update after the final Chapter 3 release on April 30.

> Also, I noticed that currently, the screenshot links in https://github.com/Realm667/WolfenDoom/blob/master/dist/com.realm667.Wolfenstein_Blade_of_Agony.appdata.xml are broken

Check out [the media page](https://boa.realm667.com/index.php/media-screenshots) on the Blade of Agony website. @Username-N00b-is-not-available took a whole bunch of new screenshots of Chapter 1, 2, and 3 for us. I hope @Tormentor667 and @Username-N00b-is-not-available won't mind if we use them.

**Comment by Tormentor667** [comment]
Feel free to use them :)

**Comment by mcphail** [comment]
![photo_2021-04-28_23-29-52](https://user-images.githubusercontent.com/1226842/116480693-b66c6b80-a879-11eb-8a64-57541d46ef03.jpg)
Just for a bit of light relief, here's the Linux snap running on Windows via WSL. Not playable, due to software rendering, but fun to see :)

**Comment by mcphail** [comment]
@Tormentor667 if you happen to get a chance, when you're building the final release can you let me know which git commit is "final" so I can set the snap to build? And can I have permission to release the snap when ready? Thanks.

**Comment by Tormentor667** [comment]
You have the permission to release the snap in exactly 3 hours and 15 minutes from now (22:00 / 10:00 PM CEST), just when we release the game officially on the webpage :)

Regarding the exact build I will let you know around 20:00 / 8:00 PM CEST, is that okay?

**Comment by Talon1024** [comment]
I'll tag the commit from which the release was built, to make it easy for @mcphail and @Alexander-Wilms to maintain their respective Snap/Flatpak packages.

**Comment by Alexander-Wilms** [comment]
Thanks

**Comment by mcphail** [comment]
That's brilliant. Thanks

**Comment by Alexander-Wilms** [comment]
Thanks for the support! And best wishes to you as well, @mcphail. The Flatpak will be published in 2 hours here: https://flathub.org/apps/details/com.realm667.Wolfenstein_Blade_of_Agony

**Comment by mcphail** [comment]
> Thanks for the support! And best wishes to you as well, @mcphail. The Flatpak will be published in 2 hours here: https://flathub.org/apps/details/com.realm667.Wolfenstein_Blade_of_Agony

You may want to ping Liam at gamingonlinux.com. I think he's still linking to the old flatpak address (wolfendoom rather than wolfenstein) in his article. I don't know whether flathub will automatically redirect?

**Comment by Alexander-Wilms** [comment]
Thanks for the info, I sent him a mail. The old page will become unavailable, but when one tries to install it, there'll be a prompt asking if one wants to switch to the new version.

**Comment by mcphail** [comment]
![Screenshot_20210508-101215](https://user-images.githubusercontent.com/1226842/117534693-78deaf80-afea-11eb-93fd-8989b9aa9e32.png)
We've made my target :)

**Comment by Tormentor667** [comment]
Whoa :)

**Comment by DoomJedi** [comment]
Can you explain me the numbers and what it means?

**Comment by mcphail** [comment]
It means the active installs of Blade of Agony have increased from around 6 to 10 thousand since release of chapter 3 last week, and most existing users of chapter 2 have been upgraded. And there are users in most countries on earth :)

**Comment by DoomJedi** [comment]
Wow, fantastic :)
Thanks for explanation.
