### ISSUE TITLE
Small issue with tank

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#530]
In c3m5_a, Ascher tells the player to get on the tank, but there's no 'use' key shown on the tank like in c3m2.

![Screenshot_Doom_20210428_173111](https://user-images.githubusercontent.com/77861029/116431113-bfdce000-a847-11eb-9c77-10d81661754f.png)
just like in

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Which 'use' key do you mean? A yellow/orange exclamation mark? It is not needed here, since the tank is right in front of the player's path. C3M2 instead has nonlinear trenches and some destroyed Sherman tanks.

**Comment by x3003** [comment]
I think when you come near the tank in c3m2, the 'says' press use to enter or so.
