### ISSUE TITLE
C2M5_A truck ride broken

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#531]
https://user-images.githubusercontent.com/6550500/116439274-5fd14400-a81d-11eb-9123-d9c4fee382e4.mp4

I have no idea how or why this happened... The mine cart ride on C1M6 and the truck ride on C2M4 aren't broken like this.

**Comment by Talon1024** [comment]
Well, the truck is visible when you get on it at the start of the mission, but if you ride the truck, the truck model gets culled(?) during the ride.

**Comment by AFADoomer** [comment]
I will take a look at it tonight.  

It shouldn't even be getting added to the culling array...  Anything with a TID is automatically skipped in the culling code.

Most likely it is somehow getting added to the culling queue and its chunk info isn't getting updated when it moves, so when the camera moves outside of culling range from the original location, it gets culled.

**Comment by Ozymandias81** [comment]
Please also check [this](https://github.com/Realm667/WolfenDoom/commit/929c9efc89855b8c1b9f55a35de503f0f88eef6e#commitcomment-50133892)

**Comment by Tormentor667** [comment]
I just tried the truck ride after recent commits, it works again.

**Comment by Talon1024** [comment]
So many critical issues right before launch day... This shouldn't be happening!

**Comment by Tormentor667** [comment]
Definitely not, it makes me kinda nervous...
