### ISSUE TITLE
Exploded mine floor decals have strange pitch

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#532]
@Talon1024 I don't know what could be done here though. I think the hiddem mines leave a floor decal when exploding and the decal actor checks the floors pitch it is at. Because of the sector cones, this is random but looks very strange, what could be done here? Maybe deactivating these decals that are created by invisible mines?
![2021-04-28_215106](https://user-images.githubusercontent.com/10298439/116464340-25db5e80-a86c-11eb-96f4-d080a8baaa89.jpg)

**Comment by AFADoomer** [comment]
This should be resolved now.
