### ISSUE TITLE
Name default "Player" by "B.J. Blazkowicz"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#533]
I noticed that the default player's name is "Player", can this be changed to "B.J. Blazkowicz" instead?

**Comment by x3003** [comment]
I set it to a name, but the name isn't mentioned anywere in the game itself. It only shows in the left top corner when you're dead.

**Comment by Tormentor667** [comment]
Exactly

**Comment by x3003** [comment]
Well, if you would change it within the game itself, it might not fit in the text boxes. And if you only see 'player' when you're dead, well make sure you won't die ;)

**Comment by DoomJedi** [comment]
This can sure wait to 3.1, lets focus on critical issues only

**Comment by AFADoomer** [comment]
This is literally just a cvar that needs to be added to DEFCVARS.  Done.
