### ISSUE TITLE
Minor issues caused by recent changes to the culling code

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#536]
Missing guillotine model here (C2M1, during the intro cutscene):
![Screenshot_Doom_20210428_195517](https://user-images.githubusercontent.com/6550500/116486521-d856f580-a85b-11eb-807a-062be1e5be2a.png)

Sherman tank at Allied HQ is missing its top half:
![Screenshot_Doom_20210428_192309](https://user-images.githubusercontent.com/6550500/116486511-d12fe780-a85b-11eb-9146-b5d657d21186.png)

But these are very minor issues. I think we should leave them alone for now, so that we don't cause any super-critical issues before the release. Hopefully, we can have them fixed for the 3.1 release.

**Comment by AFADoomer** [comment]
The first one is an easy fix; the culling is only running if the player mo position moves, not the camera.

Second one, no idea.

**Comment by Ozymandias81** [comment]
It seems that also flames on C3M0_A stove are not spawned in place, verifying the map placement now
![Screenshot_Doom_20210429_105656](https://user-images.githubusercontent.com/11136108/116526612-12ff7300-a8da-11eb-99bf-2e0515a717f3.png)

**Comment by Ozymandias81** [comment]
I can confirm, FireSpawner works only if I "summon " it

**Comment by Ozymandias81** [comment]
The Sherman at the start was set as DORMANT, these flags must be used properly in game... Gonna fix them over maps, I did a scenery variant for those actors to save performance, so now with the cull system if it is set DORMANT, the warped object doesn't get spawn.

**Comment by Ozymandias81** [comment]
Guillotine works on c1m2, so I think these issues have been solved.
