### ISSUE TITLE
C3INTRO zombie is dead and drops an MP40

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#538]
The zombie at the beginning of the intro sequence of Chapter 3 is dead when you reach him. I was further investigating and noticed that he instantly starts to burn and dies at the very beginning of the map. Maybe this has something to do with the sector light and the automated burning. Didn't happen before but maybe @AFADoomer knows how this can be fixed.
<img width="956" alt="2021-04-29_224912" src="https://user-images.githubusercontent.com/10298439/116616909-87b7c900-a93d-11eb-86ff-72874d5debf4.png">

**Comment by AFADoomer** [comment]
Should be resolved after 7060179758ffbf08973a73a44a1d9baae5d615eb.
