### ISSUE TITLE
Ascher attack actors that can't play yet

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#540]
In c3m5_a, Ascher tries to attack a few soldiers through the gate that can't play w/ us yet. Not good, but funny though.

![Screenshot_Doom_20210430_005921](https://user-images.githubusercontent.com/77861029/116630053-da4fb000-a952-11eb-8c00-59127f35000b.png)

**Comment by AFADoomer** [comment]
[Won't Fix]
