### ISSUE TITLE
Release Day | Time Schedule

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#542]
I am currently planning and preparing things for today. My plan is to compile the final version 3.0 in about 12 hours which is 9:30 PM CEST (Central European Summer Time). I will upload the archive on 9:45 PM to ModDB and make the announcement on 10:00 PM then on each channel.

Let me know if that works for us :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667
**!!! important !!!**: it is 9:30 AM now according to https://www.timeanddate.com/time/zones/cest, https://time.is/en/CEST , and 11 hours from that will be 8:30 PM, **not** 9:30. What is the intended time?

**Comment by Ozymandias81** [comment]
We share the same time so it is perfect on my end, and I will have time to do some tests still, even if I am not at home today until 6-7pm (just committed my work) :)

**Comment by Tormentor667** [comment]
9:30 PM CEST :) It was an hour ago when I wrote that issue :)

**Comment by Tormentor667** [comment]
Fixed initial post.

**Comment by DoomJedi** [comment]
As moddb comments prove - BoA site is misleading, as I reported a few days ago.
It's a pity my report was dismissed.

**Comment by Username-N00b-is-not-available** [comment]
We can add a flashing banner to the downloads page when the archive is uploaded...

**Comment by Tormentor667** [comment]
> 
> 
> As moddb comments prove - BoA site is misleading, as I reported a few days ago.
> It's a pity my report was dismissed.

Misleading?

**Comment by DoomJedi** [comment]
"Wolfenstein: Blade of Agony
Version 3.0 (release on 2021-04-30), 765 MB, standalone
including all three chapters

This version is ready to use and includes all you need to play Blade of Agony. Unzip it to a directory that you have permission to write to, and run "Blade of Agony.exe"."

**Comment by Tormentor667** [comment]
> Version 3.0 (release on 2021-04-30), 765 MB, standalone

What is misleading here?

**Comment by DoomJedi** [comment]
Let me quote moddb comment (I seem to be the only one replying daily on moddb and youtube comments)

" I was just surprised to see no download link yet because the download page on the official website was/is already talking about

"Version 3.0 (release on 2021-04-30), 765 MB, standalone
including all three chapters"

Because of this I thought the full thing was already available for download. "

**Comment by Tormentor667** [comment]
I will take care ;)

**Comment by pagb666** [comment]
Congrats on reaching the finish line guys!

**Comment by Tormentor667** [comment]
Thanks man, let's hope nothing too critical pops out now :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 When you compile the archive(s) at 9:30 CEST, could you please post its (their) approximate size in megabytes here? I'd like to have this information for posting news on the Russian Doom Community forum.

**Comment by Tormentor667** [comment]
I will share that information directly on the webpage download area if that's okay

**Comment by Ozymandias81** [comment]
@Tormentor667 Please also do not forget to point these issues on Doomworld credits readme: countkills may not be perfect on some maps; defbinds doesn't work with shipped version of gzdoom; RE mansion big windows upstairs on C3M0_A suffer of some tearing; trees doesn't have any basement and are "empty"; maps have not been "cleaned" visual wise most probably on certain occasions; soldiers may crouch during cutscenes (seen on c2m1 start)

**Comment by Tormentor667** [comment]
Well, I am not going to mention every single issue, I think I won't even talk about these things yet. Maybe people do not even notice them :)

**Comment by Wolfenburger** [comment]
I am glad I got to work on this project with you all. I had fun. Helped me get by in these seriously dark times.

**Comment by Tormentor667** [comment]
> I am glad I got to work on this project with you all. I had fun. Helped me get by in these seriously dark times.

Glad that we could help you somehow - you are an amazing help by testing all that stuff! By the way, one hour left until I compile the final version.

**Comment by DoomJedi** [comment]
> 
> 
> @Tormentor667 When you compile the archive(s) at 9:30 CEST, could you please post its (their) approximate size in megabytes here? I'd like to have this information for posting news on the Russian Doom Community forum.

You are gonna take care of russian Doom forum post?
I'm fine, don't get me wrong :) If you need any help just ask :)

**Comment by DoomJedi** [comment]
Hope the russian youtuber will post video tomorrow, as pre-agreed :)
Tomorrow will be videos day :)

**Comment by Tormentor667** [comment]
> You are gonna take care of russian Doom forum post?
> I'm fine, don't get me wrong :) If you need any help just ask :)

I'd appreciate if you can do it, russian is not my preferred language - I can't speak that :)

**Comment by DoomJedi** [comment]
Will take care of Keen forum and Wolf3D forums

**Comment by Tormentor667** [comment]
Thank you!

**Comment by Talon1024** [comment]
Just sent an e-mail to gamingonlinux.com about the release time

**Comment by Tormentor667** [comment]
Here we go!
https://www.moddb.com/mods/wolfendoom-blade-of-agony/downloads/blade-of-agony-full-release-v30-standalone

**Comment by DoomJedi** [comment]
Hooray!!!!

Did you prepare news post too, with 3+ pics?

**Comment by Tormentor667** [comment]
Newspost prepared!
https://www.moddb.com/mods/wolfendoom-blade-of-agony/news/wolfenstein-blade-of-agony-final-release
(unauthorized yet)

**Comment by DoomJedi** [comment]
Posted on Wolf3D discords.
Will see where more to post.

**Comment by Tormentor667** [comment]
112 downloads in 6 minutes

**Comment by Tormentor667** [comment]
250 downloads in 19 minutes

**Comment by Tormentor667** [comment]
550 downloads and still going :)

**Comment by DoomJedi** [comment]
Why my downloads refuse to update???

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi Probably it's like on popular youtube channels, only first 301 or so views are shown in first few minutes.

**Comment by mcphail** [comment]
That's the snap release, too. Thanks everyone!

**Comment by DoomJedi** [comment]
Russian review is in :)

https://www.youtube.com/watch?v=7UvrIOKyi_M

**Comment by Tormentor667** [comment]
Just sent out 20 emails to big german gaming magazines and sites - let's see what's going to happen.

**Comment by Tormentor667** [comment]
> 
> 
> @Tormentor667 Please also do not forget to point these issues on Doomworld credits readme: countkills may not be perfect on some maps; defbinds doesn't work with shipped version of gzdoom; RE mansion big windows upstairs on C3M0_A suffer of some tearing; trees doesn't have any basement and are "empty"; maps have not been "cleaned" visual wise most probably on certain occasions; soldiers may crouch during cutscenes (seen on c2m1 start)

@Ozymandias81 can you open single issues for the things you mentioned, that still remain?
