### ISSUE TITLE
Sloped model glass windows in C3M5_C opaque

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#543]
No idea what has been changed here but it worked before. Checked in the map editor, it's the 31722 (SlopeMe2) window with a 0.5 translucency. Maybe the culling doesn't keep the translucency at all @AFADoomer 
![2021-04-30_121435](https://user-images.githubusercontent.com/10298439/116681853-cb4a1b80-a9ad-11eb-9fa6-1b0c42964edf.png)

**Comment by Talon1024** [comment]
I think this is related to #536

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Which graphics settings do you play on here?

**Comment by Tormentor667** [comment]
Tried both Vulkan and OpenGL, both the same.

**Comment by AFADoomer** [comment]
I think the alpha is getting overridden by the culling code.

Can someone please add the +CullActorBase.DONTCULL flag to that actor and test again?  That should work as an immediate fix until I can fix it properly for 3.1.

I will be at work through the release time, so can't make changes myself.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer OK, I'll do it.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 Could you please give coordinates of the crates with this problem? I can't find them, for me the crates in C2M1 look like this:
![Screenshot_BoA_20210430_151727](https://user-images.githubusercontent.com/59409713/116693895-3227fe80-a9c7-11eb-866d-4598d27ca810.png)

**Comment by Username-N00b-is-not-available** [comment]
In https://github.com/Realm667/WolfenDoom/commit/2714f221221327c0d3befa506017b3091ca7bdca:
![Screenshot_BoA_20210430_154355](https://user-images.githubusercontent.com/59409713/116696981-453ccd80-a9cb-11eb-9811-9460561eea55.png)

**Comment by Tormentor667** [comment]
Perfect, thanks for the last-minute fixes to both of you @AFADoomer @Username-N00b-is-not-available
