### ISSUE TITLE
C3M3_A: Door handle animation borked

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#544]
I'll let the video speak for itself. I rebuilt my ipk3 yesterday night for reference.
https://www.youtube.com/watch?v=FqTPhCLa2j8

**Comment by Username-N00b-is-not-available** [comment]
Going to fix in upcoming commit.
I wonder how many doors of this type are present on maps...

**Comment by Tormentor667** [comment]
I think there are only few of them. We would have notived more of them already as it's not a new bug being introduced lately.
