### ISSUE TITLE
Ascher doesn't react anymore

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#545]
In c3m5_b, when on this spot, Ascher says something about splitting up and seeing each other later. But when this enemy comes out, he doesn't react anymore to enemy fire.

![Screenshot_Doom_20210430_141150](https://user-images.githubusercontent.com/77861029/116710575-33125d80-a9d2-11eb-8463-72cb013d1d73.png)

**Comment by x3003** [comment]
Ah, but at least he could fire when enemies come ?

**Comment by Username-N00b-is-not-available** [comment]
Yeah, I'll try to address the issue @x3003.

**Comment by Tormentor667** [comment]
Thank you

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer I have already fetched them from C3M6_B ;-)

![Screenshot_BoA_20210430_181341](https://user-images.githubusercontent.com/59409713/116716037-f2b9dc00-a9df-11eb-90ca-34c4c695699f.png)

**Comment by x3003** [comment]
That works pretty well. :)

**Comment by Username-N00b-is-not-available** [comment]
Good to know!
