### ISSUE TITLE
Grabbing key undisguises player

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#547]
In c3m5_c, when grabbing this key, the enemy reacts and shoots me. Up until this point I didn't kill anyone, so no alarms were set off before. All I did was walk from the beginning to the kabinen, enter the room and grab the key.

![Screenshot_Doom_20210430_144143](https://user-images.githubusercontent.com/77861029/116711348-0ca0f200-a9d3-11eb-98d5-24f0b3de4ae7.png)

**Comment by Username-N00b-is-not-available** [comment]
This is not a bug. It is intended.

**Comment by Tormentor667** [comment]
> I think that is not wrong. You literally grabbing a key in front of him. So he starts to shoot at you. That's all.

Exactly.

**Comment by Ozymandias81** [comment]
You need to kill him fastly and lean down weapons once he is dead, and wait when suspicion bar is green or grayed at least

**Comment by x3003** [comment]
Well. for 1 time (only) I wanted to play the map without killing anyone, but it seems it's not possible ;)
