### ISSUE TITLE
Portuguese INFO PAGE translation

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#548]
@Tormentor667 
Can I please ask you to decide, if we should at least "blindly" translate (using automated tools) the last one language - that is Portuguese? -- Only the info pages, so players at least know something. 

I thought it will be better than nothing (empty cells, or english ones), but N00b stoped me in CSV and put a bee in my bonnet.

So, what do you think would be better? To have some (maybe "broken") lines, but in their language, or leave them for 3.1 and a proper native translator?

**Comment by Username-N00b-is-not-available** [comment]
Nitpick: there are two unfinished languages (also Turkish), but the _info pages_ have already been translated by human translators quite a long time ago.

**Comment by Tormentor667** [comment]
When choosing an "unfinished" language, the user gets a percentage at the language choice anyway so they will understand why some strings are missing. I want to avoid blind translations as I am sure translators won't read over them ...

**Comment by MuadDib90** [comment]
OK, I'll revert my recent changes then.
Thanks.
