### ISSUE TITLE
no movie operator

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#549]
In the intermap at the very start of c3m1, somehow there's no movie operator. Can this be added ?
How else could the movie start ?

![Screenshot_BoA_20210501_005450](https://user-images.githubusercontent.com/77861029/116761772-d1c1ad00-aa18-11eb-8e53-658c572f2eb2.png)

**Comment by Ozymandias81** [comment]
It is a minor detail that's not really necessary, also it would make the space to reach the Mission Summary chalkboard very narrow.

**Comment by x3003** [comment]
Thats's not true, normally there is one, except here.
This one is from before c1m1:

![Screenshot_BoA_20210501_134642](https://user-images.githubusercontent.com/77861029/116781536-c9eb2280-aa83-11eb-8d33-e8c17e51a402.png)

**Comment by Tormentor667** [comment]
I’d also say „not worth the gain“.

**Comment by x3003** [comment]
Well after all of these years making a game, putting 1 extra actor shouldn't be a problem.

**Comment by Tormentor667** [comment]
Good point :)

**Comment by Ozymandias81** [comment]
Ah alright I see now, well yes we can add a smoking allied soldier there maybe.
