### ISSUE TITLE
Graphics cutoff at 16:9 making 21:9 look odd

### ISSUE THREAD

**Issue by madame-rachelle** [Realm667/WolfenDoom#552]
Easiest way to test - `vid_aspect 6` in the console.

Sorry that I hadn't noticed this sooner, I normally do play in 16:9. I actually noticed it because I was playing with a maximized window at 16:9 which made the game view just a smidge wider.

**Comment by madame-rachelle** [comment]
The thing that this affects the most is the fade quad that is used in some of the cutscenes. i.e. starting episode 1.

**Comment by madame-rachelle** [comment]
![image](https://user-images.githubusercontent.com/18584402/116779857-d1d8a180-aa46-11eb-87e7-33bfd50098a3.png)

**Comment by Tormentor667** [comment]
Am I right if widening the graphics to 21:9 will solve the problem?

**Comment by madame-rachelle** [comment]
It'll solve the issue up to 21:9. A cvar will allow this issue to be fixed with little to no effort, however it is limited to 16:9 screen assets (as classic ZDoom was), and will cause massive stretching if used at any higher aspect.

Setting `vid_allowtrueultrawide` to `0` should fix this. Can be done in the CVARINFO.

**Comment by madame-rachelle** [comment]
> 
> 
> Am I right if widening the graphics to 21:9 will solve the problem?

So when you asked this I realized that the way I changed the engine to handle it is a bit insane, so I made this commit: https://github.com/coelckers/gzdoom/commit/153968dc7c0edea2b6ceb0c25b8a1ae07d3b076b

So for now, if you make graphics up to 21:9 it will indeed solve the problem, but you still should put an entry in cvarinfo for it so that it knows.

**Comment by Tormentor667** [comment]
So we need the CVAR but also wider graphics?

**Comment by madame-rachelle** [comment]
Either-or. The wider graphics might overall be a better idea to avoid stretching. The CVAR can save you a lot of work though.

**Comment by Tormentor667** [comment]
Considering that most of the graphics are already 16:9, stretching them to 21:9 isn't a huge step. If it would only be for these graphics, I don't see a problem:

![blackbg](https://user-images.githubusercontent.com/10298439/116811629-9c1ce100-ab4a-11eb-8b45-06aedb78e54b.png)
![Pain](https://user-images.githubusercontent.com/10298439/116811630-9cb57780-ab4a-11eb-88fc-cc89cc9809c7.png)
![MOVIEHUD](https://user-images.githubusercontent.com/10298439/116811631-9cb57780-ab4a-11eb-84f0-6564566ac3fd.png)

But I wonder, does it also stretch the graphics when it's HUDMessage overlays like these?

![endc1](https://user-images.githubusercontent.com/10298439/116811663-b0f97480-ab4a-11eb-80e7-2a089be511f3.jpg)
![endc2](https://user-images.githubusercontent.com/10298439/116811664-b1920b00-ab4a-11eb-9324-250cc2b99ff0.jpg)

**Comment by Tormentor667** [comment]
Oh and what happens if we add the CVAR and also make some of the graphics widescreen-friendly for 21:9?

**Comment by madame-rachelle** [comment]
If you do that set the CVAR to "1" - and then any screen that is wider than 21:9 will have their graphics stretched. However, if a screen is narrower (i.e. 16:9, 16:10, or 4:3) then the graphics will be cropped at the sides.

**Comment by Tormentor667** [comment]
That sounds good. Though adding this line to CVARINFO doesn't work somehow 

`user int vid_allowtrueultrawide = 0;`

**Comment by madame-rachelle** [comment]
Oh, my bad. It's DEFCVARS - and it only works on a clean .ini file.

**Comment by madame-rachelle** [comment]
Oh - 1 is for 21:9

It goes like this for `vid_allowtrueultrawide`:
* -1 : Unrestricted
* 0 : 16:9
* 1 : 21:9

**Comment by madame-rachelle** [comment]
My bad I said wrong again >.<

**Comment by madame-rachelle** [comment]
Took care of it with https://github.com/Realm667/WolfenDoom/commit/896e1220b1e3ded795784ec4763968e8aa8ee46d
