### ISSUE TITLE
Strange behaviour on help texts when low resolutions

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#553]
I noticed a strange behaviour when low resolutions are applied - actually if you resize the window frame manually to very small and then back to high resolution again. No idea if this can be fixed
<img width="998" alt="2021-05-01_114502" src="https://user-images.githubusercontent.com/10298439/116789419-fc5e4500-aaae-11eb-88ca-812d40f8923d.png">

**Comment by Ozymandias81** [comment]
To adjust it in game again, you need literally to turn fullscreen (alt+return usually should work) or enlarge the window with at decent size, press esc and then f1 again. But I wonder if there are some other possible ways to fix it

**Comment by AFADoomer** [comment]
Ugh.  I never should have added the scrolling fallback.

**Comment by AFADoomer** [comment]
This should be 'fixed' now...  The smaller text will be illegible on low resolutions, but will no longer to weird scrolling things.
