### ISSUE TITLE
Snap pack links are missing on the webpage

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#554]
@Talon1024 @Username-N00b-is-not-available 
![2021-05-01_195340](https://user-images.githubusercontent.com/10298439/116790862-fb311600-aab6-11eb-82ad-7d2f7305f347.jpg)

**Comment by Ozymandias81** [comment]
For flatpak I see [this](https://flathub.org/apps/details/com.realm667.Wolfenstein_Blade_of_Agony), it says that's updated,
[Here](https://snapcraft.io/boa) instead you can find the snap file.

**Comment by Talon1024** [comment]
I just updated that particular FAQ section with links and instructions for setting up the Snap and Flatpak releases of Blade of Agony, as well as setting it up with plain GZDoom.

**Comment by Tormentor667** [comment]
Thank you @Talon1024
