### ISSUE TITLE
A new strange glitch with lens flares on HQs briefing room, always with an nVidia 20+ gpu

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#556]
Today Doomjedi told us to watch some streamers after the release of C3, and he noticed that a couple of users had an issue you can notice [here](https://youtu.be/drpyHhabo48?t=1565) (after C1m1) and [here](https://youtu.be/drpyHhabo48?t=4141), and the dude has nvidia 2080ti with most recent drivers installed (brief discussion [here](https://www.youtube.com/watch?v=drpyHhabo48&lc=UgxtFgJLyHU8FrxqBlt4AaABAg)). Turning off lens flares removes the issue apparently.

**Comment by Tormentor667** [comment]
With this

https://github.com/Realm667/WolfenDoom/pull/555

is the issue gone now?

**Comment by AFADoomer** [comment]
No, this issue is related to the lens flare post-processing shader, and is hardware-specific.

**Comment by mrmatteastwood** [comment]
I have this issue on a 1080 Ti on Linux Mint, driver 460.80. Another way to fix it is to set tone mapping to Reinhard.

**Comment by Tormentor667** [comment]
> No, this issue is related to the lens flare post-processing shader, and is hardware-specific.

Do you have an idea why it happens and what could be done about it, if it's the lens-flare post-processor?

**Comment by Tormentor667** [comment]
![grafik](https://user-images.githubusercontent.com/10298439/120920466-38dd1c00-c6bf-11eb-955d-5fb247561a92.png)

Added this to the webpage, will close as long as it is a hardware issue.

**Comment by mrmatteastwood** [comment]
Would it make sense to add that changing the colour palette is a workaround that allows one to still play with lens flares?

When setting the colour palette to "Reinhard", the glitch disappears, only a small bit of black residue is left if you look closely. At the same time, I could barely discern any difference in the look and feel of the game (though I did turn down the saturation one notch).
