### ISSUE TITLE
[General] Proof-Reading translations

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#558]
After we got a few 'not-so-good' comments about the quality of some of our translations, I think we definitely need to find a way to proof-read them before v3.1. As of now, we have these languages (checked, which are fine):

- [x] English (proof-read by all of us, base language)
- [x] German (proof-read by @Tormentor667 )
- [x] Italian
- [ ] French
- [ ] Spanish
- [ ] Turkish
- [x] Czech (proof-read by @MuadDib90 )
- [ ] Polish
- [ ] Portuguese
- [x] Russian (proof-read by @Username-N00b-is-not-available )

**Comment by Ozymandias81** [comment]
Just as a reminder: Portuguese and Turkish have several entries which have been added with automated tools, I say this because I added myself several lines, special for Turkish, so for anyone which will proof-read these languages you'll need to consider also this aspect. It also seems that Polish has the same issue.

**Comment by MuadDib90** [comment]
> 
> 
> Just as a reminder: Portuguese and Turkish have several entries which have been added with automated tools, I say this because I added myself several lines, special for Turkish, so for anyone which will proof-read these languages you'll need to consider also this aspect. It also seems that Polish has the same issue.

Yes, good point here.

**Comment by Username-N00b-is-not-available** [comment]
We forgot to move `default` to `en` column for 3.0. Also I spotted that the PAPERTEXT24 entry (the C1M4 safe hint) in Italian has unrelated contents and **does not contain the safe combination** (+in some other languages Fettgesicht is said to be born in 2009 🤦‍♂️).

**Comment by Tormentor667** [comment]
Added `default` to `en` just now.

**Comment by Ozymandias81** [comment]
What about the FAILURE message on C1M5 then? Has that been fixed?

**Comment by Tormentor667** [comment]
> What about the FAILURE message on C1M5 then? Has that been fixed?

What was wrong with it anyway?

**Comment by Ozymandias81** [comment]
It was [hardcoded](https://github.com/Realm667/WolfenDoom/commit/01cdedd84490a336129d89423f669e0837a5f6ef), not sure if it got changed or not

**Comment by AFADoomer** [comment]
That commit was me un-hardcoding it...  it should be working as expected now, and failing back to English if the localized translation isn't available.

**Comment by Tormentor667** [comment]
So back to the translations, anyone an idea who we could ask for proofreading the other languages?

**Comment by MuadDib90** [comment]
Unfortunatelly no clue from my side... sorry

**Comment by Ozymandias81** [comment]
I might have an idea for spanish and french, will look

**Comment by Tormentor667** [comment]
@Ozymandias81 do you think you can take of italian or find someone of your friends and people around you who can do that?

**Comment by Ozymandias81** [comment]
I need some free time in my hands first, but I'l also see if someone can help.

**Comment by Tormentor667** [comment]
Does anyone have some ideas where we could recruit people supporting us with the translations?

**Comment by MuadDib90** [comment]
So sorry again, I have no such contacts I know about.

**Comment by Ozymandias81** [comment]
Working on italian proof-reading recently, for time being when done maybe I might scout for some, we need better use of social networks for this though.

**Comment by Tormentor667** [comment]
What about the other languages? As I said, I can do german but nothing else.
