### ISSUE TITLE
Commentary box too high

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#561]
I think it would be better if this box was placed a bit lower. Now it's directly over the top of the weapon.

![Screenshot_BoA_20210502_135207](https://user-images.githubusercontent.com/77861029/116816942-6edd2c80-ab64-11eb-9f68-2c0e0328ba97.png)

Even if you make the play window smaller there's enough space to place it a little lower.

![Screenshot_BoA_20210502_134208](https://user-images.githubusercontent.com/77861029/116816945-73094a00-ab64-11eb-8e96-0eea4a920504.png)

**Comment by Tormentor667** [comment]
A dynamic approach would be perfect (making the box only as high as needed) but I wonder how much hazzle it is to implement this.

**Comment by AFADoomer** [comment]
The intent of this issue should be improved as of dc3620ce781dc7d79253016478c86d3633c5b0fc.

The comments are lower to the bottom of the screen and dynamically sized based on content length.

**Comment by Tormentor667** [comment]
Very well done @AFADoomer , works like a charm!
