### ISSUE TITLE
C3M5_A & C3M5_B: Don't have autosave checkpoints

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#567]
Title is self-explanatory. Also C3M0_B only has one when you enter the bunker. Another one after the golden room would be nice.

**Comment by Tormentor667** [comment]
Took care of the autosaves just now.

**Comment by pagb666** [comment]
C3M5_C doesn't have either. Check C3M6_X just in case

**Comment by Tormentor667** [comment]
@pagb666 will take care. Did you check C3M6_A/B yet?

**Comment by pagb666** [comment]
Played them yesterday late at night, they don't

**Comment by Tormentor667** [comment]
Added them.
