### ISSUE TITLE
C3M5_B: Softlock spot

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#568]
I was able to open the door from the outside, the sound of the door opening would play, but not the animation. After getting in, there's no way to get out without cheating.
![Screenshot_BoA_20210503_191702](https://user-images.githubusercontent.com/20642121/116909411-783dc600-ac44-11eb-87bd-0069ddfa8d62.png)

**Comment by Ozymandias81** [comment]
I am sure that [my fixes](https://github.com/Realm667/WolfenDoom/commit/3260ad637ac7d40882d5698e1135d0ee4e4e9d83#diff-80684fc4ec4d97752e3d4f6423d51ad34e0f0329e91e75dae98d1baaa2c2e04f) where working there, idk what has been changed then.

**Comment by Ozymandias81** [comment]
Okay I see, if one provoke the issue by running immediately upstairs, you can enter the room before it closes (that's the sound you can hear). Fixed on next commit.
