### ISSUE TITLE
C3M5_A & C3M5_B: Make Sgt. Ascher not impassable

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#569]
I can't even begin to count the times that I've been hit or that I couldn't hide behind a corner in time because this moron was in the way. Mengele killed me TWICE because of him. It's extremely irritating.

**Comment by x3003** [comment]
You do know when you press the use key when you're close to him, it stops him (and others) from following you ?! When you then need him press the use key again to let him follow again. I played c3m5 last week like that. No problem that way.

**Comment by Tormentor667** [comment]
> 
> 
> You do know when you press the use key when you're close to him, it stops him (and others) from following you ?! When you then need him press the use key again to let him follow again. I played c3m5 last week like that. No problem that way.

Exactly. Maybe we should add a hint to the game when you have your first mission with a NPC that this actually works that way. I think the first occasion would be C1M2, the second one C1M0. As I don't know how the new "Hint-System" is working, I'd leave this to @Talon1024 @AFADoomer

**Comment by AFADoomer** [comment]
Most of the hint system problems stem from people not actually reading the hints (like with the safes).

**Comment by Tormentor667** [comment]
So is there already a hint about this?

**Comment by x3003** [comment]
Maybe make a **seperate** readme file, with stuff ppl **should** know about the game ?!

**Comment by AFADoomer** [comment]
> So is there already a hint about this?

I think it's when you rescue Ascher...  I don't think there is actually on in C3.

**Comment by pagb666** [comment]
I don't recall reading any any in C3

**Comment by Talon1024** [comment]
There is a hint on C2M2 (Operation: Feuerdrone) which tells you that you can make NPCs stop following you by pointing at them and pressing the `use` key.

**Comment by Tormentor667** [comment]
Then it’s enough in my opinion

**Comment by x3003** [comment]
>There is a hint on C2M2 (Operation: Feuerdrone) which tells you that you can make NPCs stop following you by pointing at them and pressing the use key.

This hint has been added to the **reworked** version, right ?! It wasn't in the previous c2 release. If someone already played c2 (like pagb666 did) and doesn't replay it, how would he or someone else know ?

**Comment by Tormentor667** [comment]
That’s true indeed but we consider the final release as a whole, not only Chapter 3

**Comment by pagb666** [comment]
Tbh, I started at C3, as I had already played the other Chapters twice in the past.

**Comment by Tormentor667** [comment]
Well, you are a special case :)

**Comment by pagb666** [comment]
I'm on it, those playthroughs aren't going to update themselves

**Comment by x3003** [comment]
>There is a hint on C2M2 (Operation: Feuerdrone) which tells you that you can make NPCs stop following you by pointing at them and pressing the use key.

Could be, but there isn't one on c1m2 (saving ryan's privates). That's when you **first** (not c2m2) gonna be together with an AI player.

**Comment by Tormentor667** [comment]
> Could be, but there isn't one on c1m2 (saving ryan's privates). That's when you **first** (not c2m2) gonna be together with an AI player.

I don't know how much sense it makes to deactivate the person you have to rescue...

**Comment by Tormentor667** [comment]
> I'm on it, those playthroughs aren't going to update themselves

I didn't want to sound impatient :) You are doing a damn good job and we are happy for these videos. They are helping a lot of people out there.

**Comment by pagb666** [comment]
> 
> 
> > I'm on it, those playthroughs aren't going to update themselves
> 
> I didn't want to sound impatient :) You are doing a damn good job and we are happy for these videos. They are helping a lot of people out there.

If you want to help me out... Just don't add more secrets in future updates, it triggers my OCD having misleading vids uploaded xD

**Comment by Tormentor667** [comment]
Promised :)
