### ISSUE TITLE
C1M6 - VM Abort on Level Exit

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#570]
When exiting C1M6 to finish the episode, a VM Abort occurs before the final cutscene can occur.
See also: attached screenshot.

I think this may have something to so with the SuperTicks at the latter two lines.

GZDoom version: v4.6pre
![Screenshot_2021-05-03-09-39-26-688_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/116928006-140a0a80-ac22-11eb-9095-b9f9ad5b234b.jpg)

**Comment by AFADoomer** [comment]
This should be fixed as of 46e64b22cb91bbed30754c1c1d73628f1ff075a0.

**Comment by Ozymandias81** [comment]
@Shockwave508 I assume you was playing on Delta Touch here, am I right?

**Comment by Ozymandias81** [comment]
Even [this one](https://github.com/Realm667/WolfenDoom/issues/575#issue-875954524) was looking like normal GZDoom, but it wasn't the case
