### ISSUE TITLE
crouch / run doesn't work correctly anymore

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#571]
With the new git version you can't run while crouching anymore. This is handy when you wanna make a fast kill for example in c2m1. It was still good in the build from 01/05.

**Comment by AFADoomer** [comment]
More accurately, the current code fixes an issue that was not able to be detected in the old ACS code.  

You were never supposed to be able to sprint while crouched, and couldn't if you used a key bound to "+crouch" that had to be held down to crouch.  

Toggling crouch via "crouch", where the key isn't held down, was undetectable in ACS, so sprinting was allowed.

This is an easy change to make, so if the team thinks I should revert the behavior, I can.

**Comment by Tormentor667** [comment]
I think it really shouldn’t be possible to sprint if you are crouching. Doesn’t make sense physically :)

**Comment by x3003** [comment]
>I think it really shouldn’t be possible to sprint if you are crouching. Doesn’t make sense physically :)

It's still a game you know, so not everything needs to be accurate. Not being able to do that makes it a bit harder to kill the enemy.

**Comment by Tormentor667** [comment]
But more tense in C2M1 for example :)

**Comment by x3003** [comment]
Too slow to attack you mean ?! If you don't crouch they see you. If you do, you can't attack properly...

**Comment by Tormentor667** [comment]
It works for me actually from behind
