### ISSUE TITLE
[3.1] [C3M2] Too few enemies spawned

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#572]
When you reach the first usable machinegun turret at the Allied camp, Sgt. Ascher tells you to man it quickly, and then you would face a whole lot of Nazi troops. Now, on that part of the mission, there aren't as many Nazis being spawned as there used to be.

**Comment by AFADoomer** [comment]
I think this changed when I fixed the spawners to not endlessly spam enemies...  The spawn spots do what they are supposed to - keep a certain number of their designated enemy alive at once.  

What I can't figure out is why the supersoldier sometimes spawns, but most times does not.

**Comment by Tormentor667** [comment]
Is the "Maximum Number alive" taking the class in consideration, the tid or both? I changed the count now in 523bc0dbc8cf3ae41833eef6c9ec35c4db235425 but I also noticed thath enemies do not spawn at all when the spawner is in my sight - not sure if it was different before.

**Comment by AFADoomer** [comment]
Yes.  I think the fog visibility threshold needs to be adjusted.

**Comment by Tormentor667** [comment]
Anything I can do or do you take care of it?

**Comment by Tormentor667** [comment]
Is this still active @Talon1024 @AFADoomer ?

**Comment by Username-N00b-is-not-available** [comment]
During my playthrough the spawn amounts seemed normal, so because of lack of activity on this issue I am closing it.

**Comment by Tormentor667** [comment]
I just made a clean new installation with the latest version and GZDoom 4.6 stable - works now so I guess it was something buggy remaining. Can be closed safely.
