### ISSUE TITLE
C2M2: Secrets list note is floating mid air

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#573]
Self explanatory

**Comment by Ozymandias81** [comment]
Where? It doesn't float from C3 release and neither actual repository state... You can use idmypos true and drop a screenshot here, do you mean exactly the secret hint sheet?

From C3 release, using warp cheat to check immediately the zone (map c2m2 then warp x-y)
![Screenshot_BoA_20210505_181909](https://user-images.githubusercontent.com/11136108/117175183-d991a080-adce-11eb-8e61-e2435890f68f.png)

..and from map editor on GZDoom 4.6 r211
![Screenshot_Doom_20210505_182504](https://user-images.githubusercontent.com/11136108/117175654-5de42380-adcf-11eb-964a-d2ae51a087cd.png)

**Comment by pagb666** [comment]
Warping/Noclipping there causes the note to appear correctly on the ground. However, during my 4 playthroughs of the level, during normal gameplay, it's floating mid-air. (I'm using GZD r1999). Here are some shots of both situations:
![Wolfendoom Blade of Agony - C2M2 - All Secrets No Commentary mp4_snapshot_18 30_ 2021 05 05_18 33 08](https://user-images.githubusercontent.com/20642121/117176791-8e788d00-add0-11eb-9d7b-24906fed078f.jpg)
![Screenshot_BoA_20210505_183228](https://user-images.githubusercontent.com/20642121/117176849-9fc19980-add0-11eb-864b-eceb2c157924.png)

**Comment by Ozymandias81** [comment]
Well you should use r195 or most recent

**Comment by Tormentor667** [comment]
I have an idea what's happening here. @Ozymandias81 can you make the train sequence start and recheck that area? I guess it has something to do with the polyobject and it can be solved by moving the note to a different spot in the map.

**Comment by Ozymandias81** [comment]
Fixing now
![Screenshot_Doom_20210506_191644](https://user-images.githubusercontent.com/11136108/117339100-a4a14e80-ae9f-11eb-8646-4011e415c499.png)

**Comment by Tormentor667** [comment]
Thank you
