### ISSUE TITLE
[Delta Touch] Episode 1 - Mutant Goo storage tanks' glass cut off at the bottom edge.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#575]
Throughout the entirety of Episode 1, any and all storage tanks that house the purple Mutant Goo have their glass shielding cut off at the bottom-edge. This can be observed as early as INTERMAP.
![Screenshot_2021-05-04-09-53-07-517_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/117086350-ef8d5b80-ad11-11eb-8a46-a9be4e87f454.jpg)

**Comment by AFADoomer** [comment]
This does not match other people's experience.  What are your system specs?  Which renderer are you using?

**Comment by Shockwave508** [comment]
I will concede, that I am running it via Delta Touch, with an older GZDoom v4.6pre. Same with issue #576 .

**Comment by Tormentor667** [comment]
The question is: Do we need to change something here or is it a Delta Touch port/engine issue?

**Comment by Tormentor667** [comment]
After investigating the map, I can safely say that this is a Delta Touch bug. The texture is properly scaled and aligned. Can you report thos to the DT-developers?
