### ISSUE TITLE
[Delta Touch] All liquid surfaces: Textures don't animate at all, giving the appearance of solidity.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#576]
Liquids such as Mutant Goo, instakill acid, and C1M6's lava don't animate at all, instead appearing static at all times. Perhaps have such surfaces swirling their textures around to enhance realism?

**Comment by AFADoomer** [comment]
What are your system specs?  All of the liquid surfaces are animated with shaders; this sounds like a hardware issue.

**Comment by Talon1024** [comment]
Does the OpenGL ES renderer not support user shaders on textures? That's how all the liquid surfaces in BoA are animated.

**Comment by Ozymandias81** [comment]
Well there are specifics for OpenGL ES 3.2, which I think are present on Delta Touch, but for what I have understand it requires dedicated code for custom shaders, so the ones present on BoA shouldn't work (check page [555](https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf))

**Comment by emileb** [comment]
@Shockwave508 Do you have user shaders enabled?

@Ozymandias81 Yes actually for the GELS 3.2 desktop shaders can work, it is just they sometimes need slight modifications to compile properly for GLES, usually small changes. I'll see if I can load them and let you know what changes might be needed (They will still work on desktop)

**Comment by Tormentor667** [comment]
As this is a Delta Touch specific issue, it needs to reported to the devs and can be safely closed here.
