### ISSUE TITLE
C2M3: Framerate plummets when looking at the ground

### ISSUE THREAD

**Issue by xSonicB00Mx** [Realm667/WolfenDoom#577]
The framerate in C2M3 is already pretty rough, but especially when looking at the ground. There my framerate halves. I've attached a save file. Look directly at the ground and watch your fps drop hard.
[C2M3_framerate_drop.zip](https://github.com/Realm667/WolfenDoom/files/6430511/C2M3_framerate_drop.zip)

**Comment by Tormentor667** [comment]
It will be the same when looking at the sky, right?

**Comment by xSonicB00Mx** [comment]
Bummer, but at least the level was absolutely great! The pacing was top notch.

**Comment by Tormentor667** [comment]
Thanks kindly :)
