### ISSUE TITLE
C1M5: Floor Candelabras in the Tomb can be toggled with use key

### ISSUE THREAD

**Issue by wjhollyart** [Realm667/WolfenDoom#578]
The floor candelabras in the ambush area in the tomb can be toggled with the use key. It's a tad funny, but does come across as a bug.

Amendment: So can the normal candles beside the sarcophagus.

**Comment by Ozymandias81** [comment]
What bug? Candelabras and candles (2d ones) are intentionally interactive, like 2d table lightsa

**Comment by wjhollyart** [comment]
> What bug? Candelabras and candles (2d ones) are intentionally interactive, like 2d table lights

Very bizarre feature that reads as an oversight, since the act of lighting a candle is a little more involved than most "use" actions (flipping a switch, pushing a door, turning a wheel) and the ability to flip them on and off repeatedly in fast succession almost reads as a joke.  But I guess that's more of personal game design theory and less of a bug in that case.
