### ISSUE TITLE
[GLESZDoom] BoA works on recent builds of mentioned port!

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#579]
While this isn't an issue but instead something we must thinker of, the official C3 release seems to work on this version of [GLESZDoom](https://drive.google.com/file/d/1qVciQf9FGIAQVdMmHPPsgIp-u2v50t6d/view), and probably even better if someone is capable to build it directly from [the repository](https://github.com/emileb/gzdoom).
Why GLESZDoom? While you still need 3.3+ gpu capable and a 64bit system, you may experience some good improvements in term of performance versus losing some of the features present on BoA, mainly shaders related (PPShaders doesn't work at all, I am still digging it), and lights effects sometimes also doesn't work, but game mechanics and stuff seems all there (skipping the letter at the start for example implies you have forcibly enabled mouse on menues).
Effects which uses shaders aren't animated but actors are shown at least (bushes, flowers, bubbles etc etc)
Here you are a screenshot from HQs.
![Screenshot_BoA_20210506_174631](https://user-images.githubusercontent.com/11136108/117328974-75391480-ae94-11eb-9707-6a9ec6e58bc3.png)

HQs running at 197fps in front of a portal
![Screenshot_BoA_20210506_181809](https://user-images.githubusercontent.com/11136108/117332492-3442ff00-ae98-11eb-87dc-ccd65d9561a0.png)

Another one after C3INTRO, conelights attempt to fade somehow with good effect, but if you walk straight below them you see this, not that's a big problem anyway
![Screenshot_BoA_20210506_182145](https://user-images.githubusercontent.com/11136108/117332442-20979880-ae98-11eb-9847-c83871a7c771.png)

C3INTRO running at 188fps, the health effect has the same issue seen on GZDoom with 4:3 resolution so all fine, no shaders on screen obviously
![Screenshot_BoA_20210506_181058](https://user-images.githubusercontent.com/11136108/117330946-83883000-ae96-11eb-9726-45b98f917d76.png)

Ahaha always on HQs after C3INTRO, you can see the dummy tx used for OldVideo shader in the briefing room
![Screenshot_BoA_20210506_182700](https://user-images.githubusercontent.com/11136108/117333072-d7941400-ae98-11eb-979d-758f7d7c4a9d.png)

Sadly not good framerate on C3M1_A... gets better with rain off
![Screenshot_BoA_20210506_183029](https://user-images.githubusercontent.com/11136108/117333438-38235100-ae99-11eb-87fd-4d6e4a5388af.png)

We can notice the limits in these occasions, like with portals tearing for a while
![Screenshot_BoA_20210506_184605](https://user-images.githubusercontent.com/11136108/117335426-6e61d000-ae9b-11eb-83df-6d3fcc9e6b17.png)

**Comment by Ozymandias81** [comment]
@emileb in case you are interested on this, just for fun.

**Comment by emileb** [comment]
Oh cool! Nice! Been meaning to give this popular mod a try. 
Yeah the post process shaders will not work, probably not going to enable them as there is too much removed.

However I will probably get the texture shaders to work again as an option, this should fix a few of the graphical bugs I think.

**Comment by Ozymandias81** [comment]
Looking forward with what you will come :eyeglasses:
