### ISSUE TITLE
Fullscreen opens on wrong Screen

### ISSUE THREAD

**Issue by T3ll1nG** [Realm667/WolfenDoom#580]
The game starts almost correct on the main screen but at 3/4 of the initial loading process it suddenly changes to the 2nd screen and then opens fullscreen mode there. I tried everything minimizing, moving ... but every time I initiate fullscreen mode (alt + enter)  the game moves to the 2nd screen. The 2nd screen is not marked as main monitor in windows and the is the only program where I encountered this problem. I also tried to unplug the 2nd screen to force fullscreen mode on monitor 1 in the hope it would stick, but after the next start fullscreen mode is back on the 2nd monitor. I did not find an option to change the monitor in game or in the .ini file.

**Comment by Ozymandias81** [comment]
https://forum.zdoom.org/viewtopic.php?f=50&t=66942

**Comment by T3ll1nG** [comment]
Thanks for the fast reply. It helped. Yes I guessed it is not from your mod but I couldn't find any quick help. Therefor I couldn't change it in the .ini. ZDoom was unknown to me. Anyway thanks again for the fast reply and even finding the correct post for me.

**Comment by Ozymandias81** [comment]
You are welcome! I had to specific it not belonging from our mod also for developers, just in case. Have fun and let us know if you find something else, we appreciate it. :smiley:
