### ISSUE TITLE
Freezes when launching the game

### ISSUE THREAD

**Issue by Jesusmann** [Realm667/WolfenDoom#581]
Hello, I have a 3950x AMD CPU, 2080S GPU, running off an m.2 seagate firecuda 520. Everytime I launch it just has the loading window, opens on my 2nd monitor(not default) and then turns the rest of the monitor black and sits freezes with gun sounds.

**Comment by Ozymandias81** [comment]
You must take a look [here](https://forum.zdoom.org/viewtopic.php?f=50&t=66942), hope it helps. It isn't a problem which comes from our mod btw.

**Comment by Ozymandias81** [comment]
You are welcome! If you notice some more issues, please let us know. Have fun :muscle:
