### ISSUE TITLE
Problem with sprinting at HQs

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#582]
As the title says, I have noticed an issue with most recent changes, atm at HQs. Once you start a new game, you can run normally around the base and that's okay. But as soon you'll start a Briefing, what happens next is that you won't be able to run anymore.
Also if you try to reload the game, when you will run again, you'll expire the stamina forever and BJ will breathe heavily for the rest of the game. Another thing, you can hear BJ breathing at the very start of the game during the Titlemap sequence, this happens even without mentioned issue.

**Comment by AFADoomer** [comment]
No, because I can't reproduce the problem.

I started a new game, and sprinting worked.  I started a briefing, and sprinting worked.  Once the briefing was done, sprinting still worked.  Played a map and came back to INTERMAP, and sprinting still worked.

**Comment by Ozymandias81** [comment]
I'll retry and see if I can reproduce this for you, again.

**Comment by Ozymandias81** [comment]
I have tested with a fresh GZDoom and didn't happen, so maybe it was .ini related.

**Comment by Talon1024** [comment]
Does watching the Chapter 1 intro cutscene (letter from Douglas) have any effect on whether sprinting works properly or not? I recently started another Chapter 1 playthrough, and noticed that the stamina didn't "recharge" until I started the training course.
