### ISSUE TITLE
All text has gone bad

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#583]
As the title says. With today's git version, all text seems lost. With the version I have from 01/05 everything works as expected. 

![bad1](https://user-images.githubusercontent.com/77861029/117449305-1d57e780-af40-11eb-9280-d93020f08b0e.jpg)

![bad2](https://user-images.githubusercontent.com/77861029/117449313-1fba4180-af40-11eb-914a-d50678b81e1e.jpg)

**Comment by Ozymandias81** [comment]
GZDoom version?

**Comment by AFADoomer** [comment]
This almost looks like the language lump is missing.

**Comment by Ozymandias81** [comment]
Yeah just checking.

**Comment by Ozymandias81** [comment]
Yes I can confirm, moving default has cause an issue with all languages.
![image](https://user-images.githubusercontent.com/11136108/117465676-37022a80-af52-11eb-8de0-81800d15c42a.png)

**Comment by AFADoomer** [comment]
Yeah, I don't know if we can just move default into the English column like that.  The GZDoom internal language lump leaves the English column blank and has all of the English translations in the default column.

**Comment by Ozymandias81** [comment]
So I guess it is better to keep an empty default column right?

**Comment by AFADoomer** [comment]
No, it's better to move the English translations to the default column, and leave the English column empty (basically, English will not be found, so will always use the default).

I may have to adjust the language menu code slightly, but not a big deal.

**Comment by Ozymandias81** [comment]
But is it worth the effort to merge english on default? Why that also? Because of new entries on gzdoom?

**Comment by AFADoomer** [comment]
Because otherwise any language that has not been fully translated will fall back to the entry name (like in this bug  post) and not English.

**Comment by x3003** [comment]
>GZDoom version? Probably related to the default column move.

r221.

**Comment by Ozymandias81** [comment]
So how it was before, default at column 0 right @MuadDib90 ?

**Comment by AFADoomer** [comment]
Yeah.  Compare the layout to the gzdoom.pk3 one to be sure.

**Comment by Ozymandias81** [comment]
Okay so it works, but obviously as you said UK languages are shown with 0%
![image](https://user-images.githubusercontent.com/11136108/117473167-f4445080-af59-11eb-8b55-bec6d596e258.png)

**Comment by AFADoomer** [comment]
Yeah.  Easiest immediate fix is to just manually set the percentage for English to 100,00% in the spreadsheet instead of calculating the actual percentage.  That or update the English percentage calculation to use the default column for its comparisons instead of the en column.

**Comment by MuadDib90** [comment]
So the EN column now will be blank, because we need to make sure, there will be displayed english (default text) in case another language translation has not been found? It will be transfered to "default" column, if I understood corectly.

Can't there be also english? In both english and default column? Will this be a problem?

**Comment by Ozymandias81** [comment]
What I did is copying celles from D to A, removed then the content from D except formatted cells, and then changed the sum formula for D with A, and now it looks correctly in game. So basically, selecting English UK/US doesn't mean anything now.
![image](https://user-images.githubusercontent.com/11136108/117475834-cf051180-af5c-11eb-81e5-7cad35d1eb2a.png)

**Comment by AFADoomer** [comment]
> So the EN column now will be blank, because we need to make sure, there will be displayed english (default text) in case another language translation has not been found? It will be transfered to "default" column, if I understood corectly.
> 
> Can't there be also english? In both english and default column? Will this be a problem?

There could, but then you have to make sure the text gets copied over or entered twice.

This matches how GZDoom handles English and default fallback...

**Comment by Tormentor667** [comment]
@Ozymandias81 please move it back and simply rename the default column heads ("default" to "en enu..." and "en enu" to "default"), so the positions of the entries are still the same and it's easier to reference them.

**Comment by MuadDib90** [comment]
> 
> 
> @Ozymandias81 please move it back and simply rename the default column heads ("default" to "en enu..." and "en enu" to "default"), so the positions of the entries are still the same and it's easier to reference them.

Won't this cause another problem? From the point the default column needs to be the first probably (like the code "is scanning" the columns from left to right?)...

**Comment by Ozymandias81** [comment]
Yeah thought so, also gzdoom.pk3 format as default at the start for reasons I guess... let me check, maybe it's not the case.

**Comment by Tormentor667** [comment]
> > @Ozymandias81 please move it back and simply rename the default column heads ("default" to "en enu..." and "en enu" to "default"), so the positions of the entries are still the same and it's easier to reference them.
> 
> Won't this cause another problem? From the point the default column needs to be the first probably (like the code "is scanning" the columns from left to right?)...

No, it doesn’t scan from left to right. It’s scanned by the identifier.
