### ISSUE TITLE
Request for ultra-widescreen monitors (SBARINFO)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#586]
From TulDuru at the Realm667 forums:

> Would like to add something. Not sure if its worth to open a new post for this:
> Is it possible to change the position of the HUD elements. So e.g. you could push them more to the middle of the screen? This would be really cool for ppl with ultra-wide screen. 

https://www.realm667.com/index.php/en/forum-board/wolfendoom-blade-of-agony/1597-damage-effect-ultra-wide-monitor

**Comment by AFADoomer** [comment]
There is no SBARINFO in BoA. 😝 

But, this should be doable...  a "force 4:3 arrangement" setting or similar.

**Comment by Shockwave508** [comment]
I seem to recall Marisa Kirisame (the creator of SWWM GZ) implementing a pair of "HUD Margins" CVARs for that mod's HUD, one for horizontal offsets, and one for vertical. Perhaps consult them for such advice?

**Comment by Shockwave508** [comment]
The Armor icons don't respect whatever HUD scaling you select.
![Screenshot_2021-05-08-20-16-57-092_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/117557623-8b80d500-b03a-11eb-9630-23142efd66ca.jpg)

**Comment by AFADoomer** [comment]
Thanks.  Should good now.
