### ISSUE TITLE
kill counter sometimes wrong.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#588]
The counter for killed enemies at the start of 2 levels seems wrong.
When starting c2m1, you've already killed 1 (the one with the gun), but the counter says 0.

![Screenshot_Doom_20210507_212208](https://user-images.githubusercontent.com/77861029/117499148-1a2e1d00-af7b-11eb-9b60-6d2445694b3e.png)

But when starting c3m1, you've killed 0, but the counter says 1.

![Screenshot_Doom_20210507_212305](https://user-images.githubusercontent.com/77861029/117499241-3cc03600-af7b-11eb-90bf-fb6ae0f4bce4.png)

**Comment by Ozymandias81** [comment]
This is a known issue with sneakable variant enemies, does these come from C3 release or BoA devbuilds for the record? Since AFA did some fixes regarding it, so it may be map dependent the issue (I think).

**Comment by AFADoomer** [comment]
The first one is because the dead guard isn't actually a counted enemy, but a static actor.

The second is probably an enemy dieing from other causes at map load.  We can investigate that one.

This probably has nothing to do with sneakable actors...

**Comment by x3003** [comment]
>The first one is because the dead guard isn't actually a counted enemy, but a static actor.

Yes, but you **could** count him as 1.

I've checked the version from 01/21 with gzdoom 4.5.0 and it's already set to 1 in c3m1_a.

**Comment by AFADoomer** [comment]
I'm not changing c2m1.  The kill counts are already fussy enough without us screwing with them intentionally.

**Comment by x3003** [comment]
The counter on c3m1 looks fixed.
