### ISSUE TITLE
Stuck door blocking progress through C1M3

### ISSUE THREAD

**Issue by Betalord** [Realm667/WolfenDoom#589]
Hi,
I had a strange bug that is blocking me from progressing through the C1M3 mission (I can't complete it because of it). It's about a door not opening completely (no idea why - maybe some enemy was behind it when I tried opening it?). I made a video so the thing would be more clear:

[Video](https://youtu.be/7Oejg5q69Z4)

**Comment by Ozymandias81** [comment]
It is a very rare thing but it might happen... Until we'll fix it, you can use the old "idclip" cheat or "noclip" from console and check what's behind there. Hope this will be fixed for 3.1 patch, a sliding door there might help though.

**Comment by Betalord** [comment]
I used noclip command and guess what I found behind the door... a living soldier :) He wouldn't do anything upon seeing me, I did shot him down and the door opened. However without "noclip" cheat there is no way I can progress through that door. I don't have any grenades to take him out.

**Comment by Ozymandias81** [comment]
It is a very very rare occasion but well there are ways to prevent it probably, gonna check the map and a line which prevents enemies from hide behind that door.

**Comment by Betalord** [comment]
If I may suggest another solution: add a timer like 10 second or so, and if the enemy is still behind the door blocking the door from fully opening itself, kill the enemy (he gets squeezed by the doors). This resolves the problem very elegantly in my opinion.
