### ISSUE TITLE
Problems with ambient sounds on Linux on C1M2 and C1M3

### ISSUE THREAD

**Issue by MvKord** [Realm667/WolfenDoom#590]
Hi!

I've tried your excellent mod on Linux and I've found an issue with the "ambient" (I don't know if that is the best description) sounds

In C1M2 (Exodus) the sounds of rain are played all along the level at a very high volume. This also happens with the sound of the alarms when they are activated by the enemy soldiers or at the end of the level when you're escaping with Ryan

In C1M3 (Overlord) it happens with the "radio"? transmissions heard at beggining, I can hear it all along the level (at least up until the last place I've progressed too)and also at a very high volume.

This has happened both with the official Gzdoom 4.5 Linux release, with a version compiled from the latest commit in their repo (commit bb58dedff2ea22d4c357d347de6c3844541220ec) and with a version compiled from the latest commit from GLESZdoom (06cef65752e4c13f67698f83090703ff5710d10f), all of this running natively in Linux. However, it hasn't happened when using with Wine the gzdoom bundled with Blade of Agony nor with the windows version provided by the GLESZdoom author.  

Has anyone experienced something similar? Maybe it's a bug in GZdoom itself? I've tried to find some related bug reports here and in GZdoom repo but I haven't been able to find anything related.

Also, as a workaround, do you know if there's some console command that can be run to at least silence those sounds? :sweat_smile: 

Thanks in advance and keep up the good work!

**Comment by alexey-lysiuk** [comment]
May I ask you to post output of `snd_status` console command from native Linux version?

**Comment by jrugia** [comment]
Can confirm this too, I thought it was just something on my end.

@alexey-lysiuk  I don't have access to my pc atm bit will give that a try as soon as I'm able.

**Comment by MvKord** [comment]
Sure, there you go:

```
]snd_status
Output device: OpenAL Soft
Device sample rate: 44100hz
ALC Version: 1.1
ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE 
ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context 
ALC_SOFTX_device_clock ALC_SOFTX_HRTF ALC_SOFT_loopback ALC_SOFTX_midi_interface 
ALC_SOFT_pause_device
Available sources: 256 (255 mono, 1 stereo)
EFX Version: 1.0
Auxiliary sends: 4
Vendor: OpenAL Community
Renderer: OpenAL Soft
Version: 1.1 ALSOFT 1.16.0
Extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 
AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW 
AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic 
AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates 
AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency 
AL_SOFT_source_length
```
This was on the gzdoom compiled from source. 

Also, although I think that the information is mostly redundant, here's the output of openal-info:
```
$ openal-info 
Available playback devices:
    Built-in Audio Analog Stereo
Available capture devices:
    Built-in Audio Analog Stereo
    Monitor of Built-in Audio Analog Stereo
Default playback device: Built-in Audio Analog Stereo
Default capture device: Built-in Audio Analog Stereo
ALC version: 1.1

** Info for device "Built-in Audio Analog Stereo" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE,
    ALC_EXT_DEDICATED, ALC_EXT_disconnect, ALC_EXT_EFX,
    ALC_EXT_thread_local_context, ALC_SOFTX_device_clock, ALC_SOFTX_HRTF,
    ALC_SOFT_loopback, ALC_SOFTX_midi_interface, ALC_SOFT_pause_device
OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.16.0
OpenAL extensions:
    AL_EXT_ALAW, AL_EXT_DOUBLE, AL_EXT_EXPONENT_DISTANCE, AL_EXT_FLOAT32,
    AL_EXT_IMA4, AL_EXT_LINEAR_DISTANCE, AL_EXT_MCFORMATS, AL_EXT_MULAW,
    AL_EXT_MULAW_MCFORMATS, AL_EXT_OFFSET, AL_EXT_source_distance_model,
    AL_LOKI_quadriphonic, AL_SOFT_block_alignment, AL_SOFT_buffer_samples,
    AL_SOFT_buffer_sub_data, AL_SOFT_deferred_updates, AL_SOFT_direct_channels,
    AL_SOFT_loop_points, AL_SOFT_MSADPCM, AL_SOFT_source_latency,
    AL_SOFT_source_length
EFX version: 1.0
Max auxiliary sends: 4
Supported filters:
    Low-pass, High-pass, Band-pass
Supported effects:
    EAX Reverb, Reverb, Chorus, Distortion, Echo, Flanger, Ring Modulator,
    Compressor, Equalizer, Dedicated Dialog, Dedicated LFE
```

**Comment by MvKord** [comment]
Looks like it's indeed related to the OpenAL soft version.  I've just compiled the 1.21.1 version from [their repo](https://github.com/kcat/openal-soft), linked to it with `LD_PRELOAD=/data/src/gzdoom_build/openal-soft-1.21.1/build/libopenal.so.1 ./gzdoom`  and the problem has gone away, at least in C1M2 in C1M3.

Do you think that I should report this to GZDoom, so at least they are aware of  it?

**Comment by alexey-lysiuk** [comment]
We (GZDoom developers) do not support such old versions of OpenAL Soft at all. E.g., standalone version of BoA was released with 1.20.1. Sorry, it's not our problems if someone still uses ~7 years old libraries.
I would recommend to use the latest OpenAL Soft which is 1.21.1 at the moment. Switching to older versions makes sense only in case of issues.

**Comment by MvKord** [comment]
Yeah, I totally agree. This is a Linux box which I haven't came around to update from Ubuntu 16.04, and that was the version of OpenAL soft that shipped with it. That's why I asked about reporting it, just to make sure that you guys were informed if someone came up with a similar problem, but if you're already aware all the better :smiley: Maybe some version constraint for openal can be added to the cmake script?

Anyway, thanks for your work!

**Comment by MvKord** [comment]
Well, the thing is: as you said, to play natively BoA in Linux we use the ipk3 with a gzdoom that we obtain separately, be it from our distribution packages, from someone that has compiled and packaged it or by compiling it from source. In any case, the Linux gzdoom executable uses the libraries installed in the machine, they don't come bundled in the gzdoom package (think something similar to how games use the video card driver installed in the machine).

In my case, I'm running Ubuntu 16.04, which installs the 1.16 version of OpenAL . Hence, gzdoom uses by default that version, which apparently leads to the problems that prompted by post.  I've compiled the newest available release (1.21.1) of OpenAL and told Gzdoom to use it (with the LD_PRELOAD line), and the problem has gone away. I guess that this would be like overwriting a dll file in gzdoom's folder for the windows version.

My Ubuntu is fairly outdated (2016), so I think that most linux users wouldn't suffer this problem, since they would be using more modern distributions which would install more up to date OpenAL versions.

**Comment by Ozymandias81** [comment]
I see then, thanks for clarify this, maybe it is something we may add for linux users @Talon1024 ?

**Comment by Ozymandias81** [comment]
Alright so it is better for @MvKord to download the [flatpak](https://flathub.org/apps/details/com.realm667.Wolfenstein_Blade_of_Agony) or [snap](https://snapcraft.io/boa) , even the [scoop](https://github.com/Calinou/scoop-games) version once it will be included (afaik it should be possible to download from there)

**Comment by Tormentor667** [comment]
> We (GZDoom developers) do not support such old versions of OpenAL Soft at all. E.g., standalone version of BoA was released with 1.20.1. Sorry, it's not our problems if someone still uses ~7 years old libraries.
> I would recommend to use the latest OpenAL Soft which is 1.21.1 at the moment. Switching to older versions makes sense only in case of issues.

I wonder what is the problem here then? We used GZDoom 4.6 r195, and on Windows it seems to work right. Should we update the Windows build somehow? And if yes, how? And what do we need to do for the flatpak release @Talon1024 ?

**Comment by Ozymandias81** [comment]
No it is how Linux users download the mod, they have the ipk3 and then download target GZDoom version, plus dlls. But as McPhail said, Ubuntu 16.04 is outdate so MvKord had an old version of OpenAL. Suffice to download from flatpak/snap/scoop (scoop when updated).

**Comment by MvKord** [comment]
Oh my, I wasn't aware that there was a flatpak or a snap, sorry :sweat: ! In my defense I have to say that those possibilities are not mentioned in the download page :sweat_smile: (now I see it's in the FAQ , maybe a link can be added to that question in the download page?)

**Comment by jrugia** [comment]
Just like @MvKord, my OpenAL is a bit outdated (1.17.2 - Debian 9). Running the game with OpenAL 1.21.1 fixed the issue for me as well.

**Comment by MvKord** [comment]
Nice! I don't know the exact protocol that you guys follow. Shall I close this issue?

**Comment by Ozymandias81** [comment]
Since it has been solved, yes. But I am gonna close this by myself then, thanks a lot MvKord, let us know if you encounter some other issues 🙂
