### ISSUE TITLE
Bosses death animation is too fast.

### ISSUE THREAD

**Issue by DoomJedi** [Realm667/WolfenDoom#591]
Bosses die too fast, they almost immediately go from standing to dead, and they don't have too many death frames anyway so it looks overly fast.
Please slow down Boss death animation speeds so killing them will feel rewarding and you can watch them die.

Also most Bosses have long German lines so they seem to talk much after they are dead, this is improve that matching as well.

Also slow falling Bosses look more heavy and intimidating.

**Comment by Ozymandias81** [comment]
Later will apply changes to undead bosses and close this.

**Comment by Tormentor667** [comment]
Well done!
