### ISSUE TITLE
C1M5 rotating door bug

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#593]
> The revolving door into the Paris hotel got rotated in such a way that I couldn't get in at the end. The edge of the door was in the way of the door way. I had to idclip inside to finish the level.

**Comment by x3003** [comment]
With the latest git version I have no problem entering the hotel. The door rotates left or right w/o a problem.

**Comment by Ozymandias81** [comment]
This requires proper playtesting, but afaik @Talon1024 did a great job with the revolving polydoor.
I'll keep this open until many of us will manage to test it in game to see the result.

**Comment by Tormentor667** [comment]
I can only imagine that the door stops sometimes at the exact middle.

**Comment by Tormentor667** [comment]
@Talon1024 can you take a look at this just to be sure?

**Comment by Talon1024** [comment]
That happened to me once, but I was able to get in through brute force. I just fixed this, but I'm not sure my solution is the best one.
