### ISSUE TITLE
Problem with blood effects (culling?)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#594]
Read this py Captain J from ZDoom:

> - The First thing i would like to point out is the feedback of the enemy after getting hit by bullets. In Trailer, i can see vanilla doom's blood effect spawning after getting shot but in Standalone version for some reason, It does not appear. I mean sure, it plays sound effect, blood trail spawns sometimes and with NOBLOOD flag, it's visible. But along with the fact that enemies roll quite often, It's still hard to tell if my bullets actually hit the enemy or not. Feels like i'm wasting too much ammo.

This sounds like a culling issue with the blood effect. I think blood shouldn't be culled at all, because it doesn't seem to get spawned if too many actors are around. Afaik it fades after a certain while anyway, so it shouldn't impact the performance too much, is it? @AFADoomer

**Comment by AFADoomer** [comment]
The blood is murder on performance if it's not culled.  Play with the sv_corpsequeue cvar to test.

**Comment by Tormentor667** [comment]
Wow, I wouldn’t have thought that. But as it is not that reduced as ipk3, it’s fine. Just feared that blood isn’t even visible as ipk3
