### ISSUE TITLE
exit misused

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#596]
I saw this in someone's vid. He takes this exit (in c2m3) and uses it as entrance.
This way, he skipped a part of the map, didn't get the green key and doesn't had to kill holzbein to enter this cave.
Maybe an idea to block this exit until holzbein is dead ?

![boa_exit](https://user-images.githubusercontent.com/77861029/117554142-f1c72100-b055-11eb-96f6-cc08f26fde48.jpg)

**Comment by Tormentor667** [comment]
Already fixed

**Comment by x3003** [comment]
ok, thx
