### ISSUE TITLE
Crash when firing

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#597]
In c1m5 with the latest git version, when I fire with the shotgun at the enemy, I get a crash.

VM execution aborted: tried to read from address zero,
called from BulletTracer.Tick at  scripts/actors/tracers.zs, line 157
To reproduce, open the savefile, run towards the front and kill the boss to start a new wave. Then kill some more enemies, all done with the shotgun. Crash....

[save24.zip](https://github.com/Realm667/WolfenDoom/files/6447740/save24.zip)

**Comment by AFADoomer** [comment]
This should be fixes now.

**Comment by x3003** [comment]
Yes, now it works as expected.
