### ISSUE TITLE
Keen enemies fall and die on SM02 map at map start

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#598]
A couple of hour ago I dropped a request regarding tracking back enemies which die on BoA, in all circumstances, and I have found out that, beside CKSpear actors (which needs to be placed 8mp more over 3d floors), the enemies you can see on the list dies once they hit 3d floor, guess because of the Instant Death special below them. 3d floors should avoid that but somehow it doesn't get applied properly for these kind of actors: I tried to add tags, lift them up 8-16mp... but with no avail. Any clues? Going to commit fixes and then after that you are free to fix these. Tested both from C3 official release and GDoom 4.6 pre224.
![Screenshot_BoA_20210509_191625](https://user-images.githubusercontent.com/11136108/117582962-fc8cbf00-b104-11eb-9f9c-987f211f2f1f.png)

**Comment by AFADoomer** [comment]
This should be fixed after d3ce682a769c8a3bb80ab4a16590f02269ee2c63.
