### ISSUE TITLE
TITLEMAP and Cutscenes: Letterboxing cut off on ultrawide resolutions.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#599]
On TITLEMAP and the cutscene leading up to C1M5: Paris, the letterboxing effect gets cut off at any aspect ratio wider than 16:9, possibly exposing certain elements that were likely intended to remain unseen. I'm sure this also applies to any cutscenes that precede the start of an Episode proper.
![Screenshot_2021-05-09-13-41-42-095_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/117583415-adc33300-b0cc-11eb-8d8c-2e4d238c394f.jpg)

**Comment by AFADoomer** [comment]
This is mostly fixed after 26bf3eeba1e30ee29668f74c4bd24233e0dcbabc.

The cutscene maps and the finale screens still need more work done.

**Comment by Tormentor667** [comment]
Are the cutscenes and finale screens improved as well? Is this mostly a code-question or do the camera movements also need some changes? Anything I can help with?

**Comment by AFADoomer** [comment]
The finale screens (meaning the message and tally part) are all code side. 

The cutscene maps can either be updated to widen the visible areas or I can add a black pillarbox overlay.  You can see the problem if you make your game window short and wide and play the cutscenes.  Some areas are OK, but others could use work.  Or we just pillarbox them to cover up the edges 😄.

**Comment by Tormentor667** [comment]
I just tried a few of them and I think it’s doable. One thing that makes me headaches is the video sequences though which we can’t widen. 

Instead of pullarboxing everything what about adding „movie film stripes“ or something g similar as borders to the left and right side?

**Comment by AFADoomer** [comment]
Yeah, that could work, too.  Just need the graphics.

**Comment by Tormentor667** [comment]
@AFADoomer if I saw it correctly, you fixed it by pillarboxing the screens, is that right? Is the issue fixed here then?

**Comment by AFADoomer** [comment]
Should be fixed now, yes.
