### ISSUE TITLE
painting / mirror wrong order

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#601]
In c1m5, you can find the switch when you move this painting. But, it should be better if you could only move the painting **after** you've broken the mirror. Why else have the message when ppl first move the painting and **then** break the mirror ?

![Screenshot_Doom_20210509_125713](https://user-images.githubusercontent.com/77861029/117584854-8b9ed480-b10f-11eb-9978-04afbd3b15f1.png)

**Comment by Ozymandias81** [comment]
It's just up to player's choice, the message behind the mirror was something fishy we wanted to include on thay room.

**Comment by x3003** [comment]
If they do it in the wrong order, were is the surprise ?
