### ISSUE TITLE
new STEN gun Sprite.

### ISSUE THREAD

**Issue by donnelenriquez** [Realm667/WolfenDoom#602]
![sten_handed2_strip2](https://user-images.githubusercontent.com/20440652/117586142-dab52b80-b148-11eb-8a36-202739d80b5d.png)

Here's the STEN sprite i made to replace the current one.

**Comment by Ozymandias81** [comment]
This should belong to mutators, as replied on zdforums thread

**Comment by donnelenriquez** [comment]
I was told by Tormentor667 on the same thread that he is planning to use this sprite for 3.1v and was told to post here.

**Comment by donnelenriquez** [comment]
> This should belong to mutators, as replied on zdforums thread

I was told by Tormentor667 on the same thread that he is planning to use this sprite for 3.1v and was told to post here.

**Comment by Ozymandias81** [comment]
It requires a proper pickup sprite then

**Comment by Talon1024** [comment]
I just added these sprites, and I don't see why we need a new pickup sprite now.

**Comment by Ozymandias81** [comment]
I thought it looks different... nevermind, since it is good as is for everyone, I'll close this. Later will do the brightmap.

**Comment by Tormentor667** [comment]
Thank you
