### ISSUE TITLE
CREDITSM graphics needs to be fixed

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#605]
As the title says, ddb_crd2 and ddb_crdt graphics needs to be updated because I noticed a couple of issues:

SidDoyle is credit sometime as SydDoyle, which is wrong; Muska666 has also the "Cha-Ching Register" line, which is not needed; the "Thanks for Playing" line doesn't practically show up while instead it should roll at least until the "no this isn't a Marvel end" line after that; we must add a couple of russian flags as suggested by DoomJedi (there are soldiers though).

**Comment by Tormentor667** [comment]
Just updated the graphics, for the rollers.
