### ISSUE TITLE
incorrect order of clues

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#609]
In c3m1, when you look at the clue to grab next (or nearest ?) in the compass, at some point you see an incorrect one shown.

![Screenshot_Doom_20210511_221119](https://user-images.githubusercontent.com/77861029/117891492-46b5a200-b2b7-11eb-897d-956e9c50305a.png)

If you move just a little forward, you see the correct one.

![Screenshot_Doom_20210511_221122](https://user-images.githubusercontent.com/77861029/117891554-5f25bc80-b2b7-11eb-9b62-d8b0bc3095d1.png)

**Comment by Tormentor667** [comment]
You are walking through a portal line here that connects two different parts of the map with each other. As Doom is not a real 3D game but a 2.5D game, we had to do this once in a while on various maps and occations to achieve "rooms over rooms". Unfortunately the compass doesn't take these teleports into account so we can't do anything about it.
