### ISSUE TITLE
stuck behind doors

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#610]
Some actors can get stuck behind doors and there's no way to unstuck them, as the door never closes.

![Screenshot_Doom_20210511_224130](https://user-images.githubusercontent.com/77861029/117891741-bb88dc00-b2b7-11eb-9bba-d7f55e9bc3d7.png)

**Comment by Tormentor667** [comment]
As this is no game-breaking bug and more an aesthetical thing, it's not that critical. Fixing it for BoA is a problem anyway, as this is how GZDoom (the engine) works. There is nothing we can do about it with little effort so I'd simply leave it as is.

**Comment by x3003** [comment]
Nah, it's nothing serious. Just some info that these thing can happen. But, it's funny as well ;)
