### ISSUE TITLE
Releasing "Addons" - When?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#611]
I wonder when is the perfect time to release the addons? I thought about doing it this weekend. Are you okay with it or do you have other suggestions?

**Comment by Ozymandias81** [comment]
I think it is better to have them shipped with 3.1 release, since we also need the launcher finished and addons tested too.

**Comment by Tormentor667** [comment]
I can live with that. What do others think?

**Comment by AFADoomer** [comment]
I think they should be the highlight of the 3.1 release.  Yes, we are doing bugfixes, but the new features - add-ons and updated launcher - should be the focus.

**Comment by Tormentor667** [comment]
Yes, that is absolutely reasonable.
