### ISSUE TITLE
C2M6_B Hades - nazi issue

### ISSUE THREAD

**Issue by Gadgetdan** [Realm667/WolfenDoom#612]
The nazi soldier that ask for your passport to enter the U-Boat is killable. I suggest to make it unkillable because after I kill him, his dead body still ask for a passport but I can over pass him with no issues, since he is dead. Also I think the passport is not available anymore at the map since I cannot find it, I may be wrong about the passport.

**Comment by Tormentor667** [comment]
For now I made him non-killable even though a different solution would be better. Killing all soldiers around him shouldn't make him give you access anyway. Maybe @AFADoomer @Talon1024 can come up with something better.
