### ISSUE TITLE
C2M2: Ryan can be made to follow you at the end if you "use" him

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#613]
Got a bug report from Captain J

> You actually can push Ryan into the acid pit if you command him to follow you.

![IkgN2Gfl](https://user-images.githubusercontent.com/10298439/118089964-38f04180-b3c9-11eb-87f7-53af7f50a6fb.jpg)

I think Ryan shouldn't be able to follow you at all, even if you 'use' him after he stops continuing.

**Comment by x3003** [comment]
Yes, strangely enough it's possible that he follows you.

![Screenshot_Doom_20210513_134043](https://user-images.githubusercontent.com/77861029/118121045-27229480-b3f1-11eb-885d-1d5f537a0517.png)

**Comment by Tormentor667** [comment]
He is deactivated through script but can be reactivated by the player. This should be prohibited somehow.
