### ISSUE TITLE
C2M5_B: Model icon appears

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#614]
Also from CaptainJ

> So i burned Nazis to crisps above and they show this weird cute thingie. What's this do?

![grafik](https://user-images.githubusercontent.com/10298439/118093328-94243300-b3cd-11eb-9690-5e0b00657210.png)

**Comment by Ozymandias81** [comment]
Looks like it comes from BodySmokeSpawner, disappear quite immediately
![Screenshot_Doom_20210516_192737](https://user-images.githubusercontent.com/11136108/118406623-d9ba5780-b67c-11eb-8e58-9dff33c28476.png)

![Screenshot_Doom_20210516_192620](https://user-images.githubusercontent.com/11136108/118406619-d626d080-b67c-11eb-8056-74618261d031.png)
