### ISSUE TITLE
C2M0_B: Mecha suits with mecha sounds

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#616]
![grafik](https://user-images.githubusercontent.com/10298439/118095484-668cb900-b3d0-11eb-9311-4c0c1983946e.png)

These guys shouldn't make normal footsteps but mecha walking sounds - not as "strong" as the large mechas but maybe a lighter variant of that walking sound.

**Comment by AFADoomer** [comment]
Addressed in fedd1e181026dd4d8f62389d27cd0956ec55b632.

They play a quiet version of the mech walk sound on top of the normal terrain footstep sound.
