### ISSUE TITLE
C2M6_B: Splashing sounds on solid floor

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#618]
Report from CaptainJ

> If you stay close to the gate and walk around it, the splash sound plays for some reason.

![grafik](https://user-images.githubusercontent.com/10298439/118096011-1eba6180-b3d1-11eb-842f-d86ad1fa7c83.png)

I am pretty sure it has something to do with the sewer below the area. I guess the footstep check doesn't check if you are standing on a 3d floor, but takes into account what the lowest sector floor's flat is. Is this right @AFADoomer @Talon1024 ?

**Comment by AFADoomer** [comment]
Is this in current dev or release?  I rewrote the footstep handling into ZScript instead of ACS.

**Comment by Tormentor667** [comment]
Tried it, works as expected.
