### ISSUE TITLE
C2M6_C: Skybox issue at the end of the map

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#619]
Something is wrong with the skybox at the very end of the map. I guess it has something to do with @AFADoomer 's changes.

![grafik](https://user-images.githubusercontent.com/10298439/118096541-c6379400-b3d1-11eb-87ee-a3241017cd7c.png)

**Comment by AFADoomer** [comment]
This should be fixed as of a7c617149a04c1057446b8096da2c29a498cdb05.
