### ISSUE TITLE
C2M0_A: Automap is blacked out

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#620]
In C2M0_A, the automap is not working. Instead, it is blacked out.

**Comment by Talon1024** [comment]
I think it's supposed to be like that during the map intro cutscene.

**Comment by x3003** [comment]
During cutscenes it's always like that. It was still working on the build from 01/05 and broken in the git version.

**Comment by Talon1024** [comment]
Hmm.. If I skip the cutscene, the automap is blacked out during gameplay, but the automap is fine if I watch the cutscene without skipping it.

**Comment by Tormentor667** [comment]
> Hmm.. If I skip the cutscene, the automap is blacked out during gameplay, but the automap is fine if I watch the cutscene without skipping it.

Exactly that's the problem. Maybe a token is not being removed.
