### ISSUE TITLE
Performance Settings requiring restart affect savegames

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#622]
From ModDB (no idea if something can be done here):

> I want to point this out but I am not sure it is a bug. Changes in performance settings require a restart of the game but when I load last saved files it loads also the settings with it was saved with, so I had to restart a whole new game to lower performance for my pc. This might be an issue, unless I did something wrong.

**Comment by x3003** [comment]
Which performance settings ? When I switch from vulkan <-> opengl and load a file saved with the other setting, it stays on the one set in the options menu. I don't think games (tested with boa/doom2/freedoom2) save these settings in the savefile anyway.
