### ISSUE TITLE
C3M0_B: v3.0 release

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#624]
First of all, it was here before the final release, the impossibility to get through the main hall with Tiger in it, from the entrance door. I tried like 20 minutes straigth to find a possible path, but they always saw me. It was just that if I stayed too long in "direct line of sight" (I could see the guard, so he could possible see me too), I got detected. And the time needed to get to the right pass the boxes is too long when crouching, so the bar at the bottom "has time to load", and you got detected no matter what. 

![01](https://user-images.githubusercontent.com/73436978/118141947-33671b80-b40a-11eb-912e-7dc8fa926de0.PNG)

(_I was only able to do it by - kind of dumb way - throwing a grenade to that group to the left, so they died (also it did not raised the alarm - what the hell? ), and then proceeded as supposed to in the first place /without that grenade/._)

Second, when using Stierlitz, conversating with him and then recieving the gold key with the new objective added logo, I could speak to him again and recieve a gold key with the logo new objective added; could do it as many times as I wanted to... also the exclamation mark on a map was there the whole time. (_My guess, problems with proper triggeres setting. So it allows the loop._)

Finaly, when I got back from C3M0_B to intermap, I could go through many actors such as people, tables ect. almost as "noclip" was ON, but it wasn't (but not through walls). Also I got incomprehensible boost in speed when "runing", and when normaly walking, but this only on stairs going up. No idea whatsoever happend there.

**Comment by Ozymandias81** [comment]
Was you playing with GZDoom version shipped with C3 or different one? Also did you import your .ini file from somewhere else and overwritten the one on c3 release? It sounds like you have missed some tokens and DoEffects in a row. Did you cheat in apoint of the game? NoClip has been tweaked for the mod afaik setting turbo to 255 if I remember correctly.

**Comment by AFADoomer** [comment]
I can crouch and walk back and forth across that area with no problem...  I can even walk without crouching as long as I don't move too quickly.  The only thing that alerts the guards is if I move too quickly or if I jump or walk onto a the mutant cell ledge and then step down (and make a sound when I hit the ground).

**Comment by MuadDib90** [comment]
@Ozymandias81 
> Was you playing with GZDoom version shipped with C3 or different one? 

Yes, the shipped one.

> Also did you import your .ini file from somewhere else and overwritten the one on c3 release?

No. Totaly standalone folder for testing purposes. Not messing with anything together, so to be sure the problem is "release-based".

> Did you cheat in apoint of the game?

Not in once.

> NoClip has been tweaked for the mod afaik setting turbo to 255 if I remember correctly.

Yes, it was. And it did come to my mind too. But as I did not used cheats... it is strange.


@AFADoomer 

Tbh I had no problems with this previously (and in pre-release era, using github repositories). I remember someone playtesting it (maybe @x3003 but not sure) and issued this exact problem. Told him the same as you do to me now. I am confused why this happend.

**Comment by Talon1024** [comment]
I tried to fix the issues with Stierlitz's conversation, but I have no idea how the clipping or speed issues happened to you. Do you have a saved game from after C3M0_B where you're having those issues? If so, I'd like you to show us what `myinfo` and `printinv` (console commands) tell you.

**Comment by MuadDib90** [comment]
I can't use <code>myinfo</code> because cheats are turned off by game, and can't be turned on (at least IDK how to do it -- in the current progress of the game >Mein Leben option<).

<code>printinv</code> show:
<details>
<summary>screens</summary>

![01](https://user-images.githubusercontent.com/73436978/118280839-dbddb400-b4cc-11eb-988a-405f7bdaf252.PNG)
![02](https://user-images.githubusercontent.com/73436978/118280842-dc764a80-b4cc-11eb-809a-313a74c7630f.PNG)
![03](https://user-images.githubusercontent.com/73436978/118280843-dd0ee100-b4cc-11eb-867a-ca0832ea047a.PNG)
![04](https://user-images.githubusercontent.com/73436978/118280846-dd0ee100-b4cc-11eb-9862-d93d37becd81.PNG)
</details>

Here are also both saves.
<code>save63</code> is right before ending C3M0_B (only reach the main door)
[save63.zip](https://github.com/Realm667/WolfenDoom/files/6479306/save63.zip)
<code>save64</code> is already in the mess hall after returning ("clipping" through actors)
[save64.zip](https://github.com/Realm667/WolfenDoom/files/6479312/save64.zip)


When preparing this for you @Talon1024, I remembered, what happend to me there, that "changed normal behavior".
When you reach the main door (in C3M0_B), you get "freeze", you can only turn around, BUT also fire and throw grenades. Now it gets tricky. With my first atempt before stating the issue, I (out of boredom) tried to shot some standing Nazis. The newly appeared (Afrika Korps ones) can't be killed, but those Wehrmacht ones (green) can be. And I shot one, and wounded one other, until I could not do anything (even shoot). He started moving (even turned on the alarm), and they shot me dead. This was AFTER the text with all that monolog had already appeared, so I died and death screen appeared _under-layer_ the text message. After hitting ESC, you go back to intermap with those glitches. This can be also achieved by throwing a grenade(s) under you, after you got freezed, so you die after the text appears.

**Comment by Ozymandias81** [comment]
To enable cheats on Mein Leben, type sv_cheats true and then replay the zone

**Comment by MuadDib90** [comment]
> 
> 
> To enable cheats on Mein Leben, type sv_cheats true and then replay the zone

What? Replaying do not work (if we mean the same thing). Because loading a save will load previous CVARs, am I right? So what exactly changes? You have to go through "map" command, or play it from the begining after the cheat is applied, if you do not want to "break the threads" (or what phrase english uses...).

**Comment by Talon1024** [comment]
Seems I was able to reproduce your clipping and stair climbing issues if I killed myself with the `kill` CCMD right before the mission ends. I'd recommend setting Buddha mode on when the ending sequence starts and Fettgesicht and his Afrika Korps goons appear, and then setting Buddha mode off right before the player is sent back to HQ.

**Comment by MuadDib90** [comment]
Well, I usually play on highest skill to test if some fight is (nearly) impossible, for example.
What that report tells us anyway?

With your suggestion of using Buddha mode, which occurred to me too, this can be solved, isn't it?

**Comment by Talon1024** [comment]
> What that report tells us anyway?
What flags are set on the player actor, what state the player is in, and other info which is useful for debugging.

> With your suggestion of using Buddha mode, which occurred to me too, this can be solved, isn't it?
I meant doing that in the map scripts using [SetPlayerProperty](https://zdoom.org/wiki/SetPlayerProperty).

**Comment by Tormentor667** [comment]
@Talon1024 @MuadDib90 is this still bugged?

**Comment by MuadDib90** [comment]
> 
> 
> @Talon1024 @MuadDib90 is this still bugged?

Yes, now it is good.

Just discovered you can clip through all these beds as shown bellow:
![01](https://user-images.githubusercontent.com/73436978/120894681-0af1cc00-c61a-11eb-9d61-554d4b093e69.PNG)

But we can close this.

**Comment by Tormentor667** [comment]
Will fix that
