### ISSUE TITLE
[Delta-Touch] C1M0: VM Abort when being killed by an auto-turret.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#625]
In Operation Eisenmann, I experienced a VM Abort when I died from an auto-turret's fire. [scripts/actors/tracers.zs] tries to read from address zero at line 131. Offending process is "BulletTracer.PostBeginPlay".
![Screenshot_2021-05-13-09-32-47-887_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/118180020-ae750580-b3fb-11eb-93ae-3e013714b36d.jpg)

**Comment by Ozymandias81** [comment]
Please consider that playing from Delta-Touch is not how we planned for BoA. It has been developed to run under Win/Linux/Os-X (maybe) for pc.

**Comment by AFADoomer** [comment]
I can "fix" this error with a null pointer check...  this can only happen if the shooter actor I removed in the same Tick that it fires a tracer.
