### ISSUE TITLE
[Delta-Touch] C1M0: Framerate sharply nosedives when escaping Eisenmann base.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#626]
Upon escaping the Eisenmann facility, the framerate takes a steep nosedive into single-digits, while on the way to the Allied train/level exit, leaving me susceptible to the remaining Nazis/attack dogs on the map. Had no choice but to turn on Inglorious Mode just to make it through. Even with all the culling options turned down to the absolute minimum allowed by the game, I was barely able to fight, let alone survive.

**Comment by Tormentor667** [comment]
Are you playing with the current git build or with 3.0?

**Comment by Shockwave508** [comment]
Playing with current Git build, and on Delta Touch thanks to a recent update on that particular app.

**Comment by Ozymandias81** [comment]
What are your handled specs?

**Comment by Shockwave508** [comment]
My device's specs can be found here: https://www.gsmarena.com/xiaomi_black_shark_2_pro-9779.php

**Comment by Ozymandias81** [comment]
I see it has OctaCore but with low speed, if you consider that GZDoom is singlethreaded and on BoA you need at least 3.5ghz to run it nicely (6core 3.5ghz is my cpu, which I am the one with), also videoram is still not good as it would be on a pc.

**Comment by Shockwave508** [comment]
At least there is an alternative solution on my end, which is to head to the trainyard first, killing all hostiles along the away, so I face zero opposition after I escape the facility.

**Comment by Shockwave508** [comment]
Come to think of it, it might be all the constant explosion effects still occuring across the facility portion of the map long after you've left. Would it be possible to vanish them all away once the player makes it to a safe distance, resulting in one last, larger explosion, and leaving damaging flames behind at the facility's entrance, as a way to "communicate" that there's no incentive to go back inside.

**Comment by Ozymandias81** [comment]
The effect has been already tweaked and culled scriptwise and it gets removed once enough far from them.

**Comment by AFADoomer** [comment]
Added a script to clean up the effect spawners inside of the facility once you leave in 3dfa21f0ad77b4bbedcca027707262b12283c960.
