### ISSUE TITLE
Crash at the end of C2M1

### ISSUE THREAD

**Issue by Darkcrow20** [Realm667/WolfenDoom#627]
Once I finish C2M1 it crashes and says...

VM execution aborted: tried to read from address zero
Called from z_shademe.setenableshadow at boa.ipk3:scripts/items/nashshadows.zs, line 234
Called from z_shademe.postbeginplay at boa.ipk3:scripts/items/nashshadows.zs, line 276

**Comment by Darkcrow20** [comment]
Found a workaround by lowering graphic settings. Maybe just a graphic card issue.

**Comment by Tormentor667** [comment]
On which system did you play the mod? Our standalone? Linux? Delta?

**Comment by AFADoomer** [comment]
This is not applicable on the current build, since the old shadows have been removed in favor of engine shadows.

**Comment by Darkcrow20** [comment]
I'm running the current build (3.0 I believe) on the stand-alone launcher. Didn't have any issues during Chapter 1

**Comment by AFADoomer** [comment]
> 
> 
> I'm running the current build (3.0 I believe) on the stand-alone launcher. Didn't have any issues during Chapter 1

No, you are running the release build, not the current development build.  This has been fixed.

**Comment by Darkcrow20** [comment]
Ok. My misunderstanding. Just trying to help.

**Comment by AFADoomer** [comment]
And we appreciate your help 😄 .
