### ISSUE TITLE
C3M2: Machinegun turret feedback from Captain J

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#628]
![grafik](https://user-images.githubusercontent.com/10298439/118257888-76c79580-b4af-11eb-860b-a60256c9edf8.png)

> Okay! Let's talk about Stationary Chaingun, again. It's not because of the model. It's about the overall existence. Maybe because of low framerate is delaying my key command, but despite i double clicked it i just can't use it immediately. Also the tripod of this chaingun is so low i don't even know what i'm shooting at. To make matters worse, you actually get shot from both the allies and enemy... Ouch. That's Totally ouch.

**Comment by x3003** [comment]
I never have had any problems with it.

**Comment by Talon1024** [comment]
Maybe the player should be locked on to the usable machinegun turret for 10 tics after successfully attaching to it?
