### ISSUE TITLE
C3M3_B: Ryan's Arena visual glitch

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#629]
![grafik](https://user-images.githubusercontent.com/10298439/118258488-3288c500-b4b0-11eb-8976-d972f18aec61.png)

> Agent Ryan's arena looks quite funny. If you step onto the specific area, this happens.

**Comment by AFADoomer** [comment]
This should be fixed as of 7647ca780e7ee835cbebfa8123cd5fd13205addb.
