### ISSUE TITLE
C3M5_B: Mengele is still alive 

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#631]
>  I see... Dr. Mengele and he's doing fine?? I saw him heavily injured in previous fight and thought he was dead for sure. But this time his wounds are all somewhat healed and acts differently. Sure, Zyklon C would've made him come back to life but making him zombified would've made more sense. But Spoilers, i guess?

**Comment by DoomJedi** [comment]
Im not sure zombified version would fit the setting he is used in
....Can't we simply add green glow to his eyes? As subtile hint?
I could add him (to green eyes glow) though Bane-like "venom" injection tubes that sustain him, sort of "keeping alive" device.
Will fit the setting mych more than streight-out zombie and add nazi story more depth in ways cyclon can be used for temporal life sustainer, reversable.

**Comment by Tormentor667** [comment]
Sounds good to me

**Comment by DoomJedi** [comment]
But making him also wounded, or just life sustained?
It might be too much details that might conflict or overdo, and cyclone can be used as explanation for his fast wounds heal.

...I think in any way on his table or whatever - note needs to be added to add explanation to his "sustained" origin, as intermediate way to fuller transformation he might have planned for himself...or not.

**Comment by Tormentor667** [comment]
Well done guys

**Comment by DoomJedi** [comment]
Thank you :) And thanks to Virg :)
