### ISSUE TITLE
C3M5_C: Propellor of airship model isn't rotating

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#632]
![grafik](https://user-images.githubusercontent.com/10298439/118259429-6d3f2d00-b4b1-11eb-8a39-182fbfed6e8c.png)

Maybe we can do something with an animated texture here that is applied to the model, what do you think?

**Comment by AFADoomer** [comment]
The model doesn't match our supposed airship at all in the first place...

**Comment by Tormentor667** [comment]
That’s something we must live without a proper model artist I guess.

**Comment by Ozymandias81** [comment]
It took me humongous time to rip it from from NecroVision using the internal map editor, before it was waaay even worse with LilMouse model. I also customize it a bit and fixed flaps and skin to set it right.

**Comment by AFADoomer** [comment]
Animated the props in 702ae4bd1514a498011b99b7b4cdc06296d4e10a.

Also fixed the skin on the middle gondola.

**Comment by Ozymandias81** [comment]
Thank you for improving the model @AFADoomer , will fix it now for the static variant we need on some situations (the model on the control room in c3m5_C for example). Just minor edit to the code and to c3m5_C cutscene.
