### ISSUE TITLE
C3M5_C: Speed issues after sabotage

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#633]
> After sabotaging the engine, the zep starts to lean itself. For some reason i get the speed boost from that. It's a situation you should be in hurry, i understand, but why this fast?

**Comment by MuadDib90** [comment]
Looks like a similar "bug", the speed boost I got in #624 at straircase.

**Comment by Talon1024** [comment]
The speed boost on C3M5_C comes from the level tilting. C3M0_B doesn't use that feature at all.

**Comment by AFADoomer** [comment]
Yeah, this is almost certainly the level tilt's fake directional gravity working as intended.

**Comment by Tormentor667** [comment]
So we can consider this a „not a bug, a Feature“?

**Comment by MuadDib90** [comment]
> 
> 
> Yeah, this is almost certainly the level tilt's fake directional gravity working as intended.

OK then, here it is a feature.
