### ISSUE TITLE
CREDITSMAP: No final stats

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#634]
>  In the Credit Section, after the last cutscene, i still can hear the Future Nazis strolling in the field. And i'm not saying this is bad or anything, but it's kinda frustrating that it takes me to the title screen immediately. Where's the final stats? Other 2 Episodes showed me just fine. Why not this? Where's THE END or should i say, DAS ENDE?

**Comment by x3003** [comment]
You mean this end ??? https://youtu.be/0SHnuXsCB54?t=2861
Seems working for him.

**Comment by Tormentor667** [comment]
No, I guess he means the overal stats

**Comment by AFADoomer** [comment]
Where do you want them?  After the full scroll?  They interrupt the flow anywhere else...

**Comment by Tormentor667** [comment]
Yes I think that’s the only possible place and a good reason for watching the credits till the end

**Comment by AFADoomer** [comment]
Added in f866311f451f2c1e9ba6fd0d44257d12a1ea538b.
