### ISSUE TITLE
Fullscreen-friendly dialogue boxes in Screensize 11 HUD?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#635]
Noting how the Screensize 10 HUD looks, and how the in-game dialogue boxes fit that particular theme, would it be possible to add a transparent-black version to go alongside the fullscreen, Screensize 11 HUD?

**Comment by Tormentor667** [comment]
That would be a nice feature indeed

**Comment by AFADoomer** [comment]
I was planning to rework the messages as part of the ultra-widescreen support anyway.  Should certainly be doable.

**Comment by AFADoomer** [comment]
This is done as of dc3620ce781dc7d79253016478c86d3633c5b0fc.
