### ISSUE TITLE
Fog in C3M2

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#636]
I've heard various reports, some of which come from very good and attentive players, that the C3M2 fog is frustrating. This was my impression too as you can remember, but I did not considered that a problem after the map has been optimized. Though we can't guarantee that it runs smoothly for _every_ player, hence the following question:
@Tormentor667, @Ozymandias81, **is it possible to reduce fog thickness in C3M2 for 3.1?**
The visibility distance might be just too low for players who do not know the enemy disposition yet, and the fights degrade into savescumming. I understand that presence of the fog is a design choice and one of the key features of the map, but maybe a slight reduction (around 10 to 20%) could help matters? Maybe in some areas it could be made thinner, and in some it would be left as is.

**Comment by Tormentor667** [comment]
I‘d be okay with a reduction of 10% but I really am not happy with that. It was meant to look and play like that. 

I noticed that these players complaining mostly run through the map like a maniac where they should proceed slowly instead.

**Comment by AFADoomer** [comment]
^ This.  People need to slow down and be cautious.  If you play this map like Doom, you will die.

**Comment by Tormentor667** [comment]
That’s exactly the point. We even covered this ingame and in the faq.

**Comment by Username-N00b-is-not-available** [comment]
OK, all fine, I'll close this issue then.

**Comment by DoomJedi** [comment]
Very good russian youtuber hated it as well

Sent from Yahoo Mail on Android 
 
  On Fri, May 14, 2021 at 20:04, ***@***.***> wrote:   


OK, all fine, I'll close this issue then.
