### ISSUE TITLE
C2M3: House 5's windows can be shot through from outside.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#637]
While at the area with three houses, the one marked with the number 5 has some improperly set tags in its windows: unlike the other houses, House 5's windows can be shot through from outside, and enemies can detect you through those same windows, yet cannot penetrate it from the inside with their weapons fire.

**Comment by Tormentor667** [comment]
Can you share the position or a screenshot of house 5?

**Comment by Tormentor667** [comment]
Fixed.
