### ISSUE TITLE
Meals falling through talbles

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#638]
Meals falling through tables 

![grafik](https://user-images.githubusercontent.com/10298439/118362598-63d8c200-b590-11eb-943c-1aaa3ba47bb6.png)

**Comment by Ozymandias81** [comment]
This was working fine before the zscript migration

**Comment by Ozymandias81** [comment]
Okay my bad, just checked an old version I had from December 4th 2020, but anyway I added tables with meals for a reason, the chosen variant doesn't have meals on it

this is the used one
![image](https://user-images.githubusercontent.com/11136108/118379579-b390ab00-b5db-11eb-8e79-194493e964f9.png)


instead one should have put these
![image](https://user-images.githubusercontent.com/11136108/118379566-9825a000-b5db-11eb-984c-25757af4ff89.png)

**Comment by Tormentor667** [comment]
Ah that was my fault then. Is it fixed by now?
