### ISSUE TITLE
Notes (C3M6_A; credits) -- v3.0 release

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#643]
- **C3M6_A**
I forgot to write that after jumping from airship (the beginning of C3M6_A) I did not lost any of my arsenal. But I should. Ascher tells you weapons are too heavy for jumping (actually I am even not sure now if this message appeared at all).
.
Can someone please check these two things out?

- **CREDITS graphics**
The blured one graphic wasn't updated. So the one in front is OK, but blured one at the back is older version.
.
Also @Tormentor667 did you include your friend who did voiceovers for bosses in credits? I don't remeber his nick so I couldn't check myself. (Just asking...)

> https://github.com/Realm667/WolfenDoom/blob/d8530b79068837439c2e63ae23bcefa02a059de5/wolf_boa_cr.txt#L291
Here it is, the credit line. --N00b, 24.05.21

Speaking of voices... they definitely should be more louder. I just couldn't hear them. Only when all that shooting stopped... that's a pitty. There was too much efford into it :-)

**Comment by Ozymandias81** [comment]
As I told on FB chat, the blurred graphic is barely noticeable and since many changes have been done by hand, the blurred version can't be edit by hand since too complex.

**Comment by Tormentor667** [comment]
> I forgot to write that after jumping from airship (the beginning of C3M6_A) I did not lost any of my arsenal. But I should. Ascher tells you weapons are too heavy for jumping (actually I am even not sure now if this message appeared at all). Can someone please check these two things out?

Checked it, there is no message like that, you keep your arsenal. With the other bug being fixed, we can easily close this.
