### ISSUE TITLE
passport pages

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#644]
When you find this passport in c2m0_a, it says you can turn the page with the arrow keys. But there are no more pages, so this text is useless. Or should it turn the page and doesn't that work as expected ?!

![Screenshot_Doom_20210516_135952](https://user-images.githubusercontent.com/77861029/118396318-44549e80-b64f-11eb-9333-f9cd455f73e7.png)

**Comment by x3003** [comment]
With yesterday's git version.

[save37.zip](https://github.com/Realm667/WolfenDoom/files/6489336/save37.zip)

**Comment by Tormentor667** [comment]
The passport doesn’t have a second page

**Comment by x3003** [comment]
Yes, but the game tells you, you can turn the page with the arrow keys. Which is incorrect.

**Comment by MuadDib90** [comment]
Maybe the problem is in settings of general behavior. If it uses the atribut of "paper notes", in those the message @x3003 is talking about is appearing even if there are no other pages; if I am not mistaken.

**Comment by AFADoomer** [comment]
At some point, someone added the arrow keys part to the generic message, so it shows up on all papers, regardless of how many pages they have.  A better solution would be to split these sentences into two separate entries, then display the first one as needed.

**Comment by MuadDib90** [comment]
But that would necessarily mean, someone has to go through each paper note of the game in each language to see, if the other line with arrows is needed, isn't it? ...

My suggestion is to adjust the general message to something like: "Use arrow keys to turn pages, if needed."

**Comment by AFADoomer** [comment]
No, they are all one class of actor.  Just some code.

**Comment by MuadDib90** [comment]
We didn't understand each other here, I guess.

I meant that if some paper note in EN is barelly on one page, some language, after translation, may need two pages, some other may still use only one. We can't possibly know, unless someone verifies this. 

So some paper message in different languages would need different hints.
But if you can easily code this, it's a win-win.

(But maybe you meant something else.)

**Comment by AFADoomer** [comment]
The page breaks are calculated at runtime, so displaying the correct message can be done in the code for the object.

**Comment by DoomJedi** [comment]
> My suggestion is to adjust the general message to something like: "Use arrow keys to turn pages, if needed."

I second that, why not to go with simple generic solution?

**Comment by Ozymandias81** [comment]
This is a very minor issue and tbh I don't see a significant problem keeping this as is, this happens also on games like Resident Evil almost so I think this can be closed. It shows the passport with a "better view", and pressing left/right does nothing so nothing is not "break" behavior wise, you do understand by yourself that it's just that.
