### ISSUE TITLE
16:9 still not automatically widened to 21:9

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#645]
@madame-rachelle I remember we talked about it and I added a specific addition to one of the lumps, but still the 16:9 graphics (hudmessage) aren't automatically widened to 21:9.

![grafik](https://user-images.githubusercontent.com/10298439/118396999-571ca280-b652-11eb-8c68-7571aab69d2b.png)

For some graphics, I can still do it graphic-wise manually, for others it would be rather complicated though. Did I something wrong with the appropriate lump?

**Comment by Tormentor667** [comment]
Just for the record: Uploaded graphical fixes c1cb0910a64c83d1c3c97b7140acf4ee85efcaae

**Comment by madame-rachelle** [comment]
You will need to update your personal config. Unfortunately it is a config variable and those will not change with a `defcvars` update.

You can enforce the change in the self-contained distribution via `autoexec.cfg` with the line `set vid_allowtrueultrawide 0`.

For your own personal settings, you'll have to manually set the CVAR yourself.

That should fix it.

(And it seems ... maybe I should probably make this a `gameinfo` thing)

**Comment by AFADoomer** [comment]
@Tormentor667 - Was this not already working as expected with the updated overlay code?

**Comment by Tormentor667** [comment]
Tried it and it didn’t work.

**Comment by AFADoomer** [comment]
😖 

The main screen overlay code has been committed for like two weeks now.  Why didn't anyone say that the updates made no difference?

**Comment by Tormentor667** [comment]
Well, I can’t tell you what’s wrong. I built a new ipk3 after having the latest commits, set up a 21:9 ratio, tried it as mod and as standalone and got the screenshotted result.

I can retry to tomorrow though, maybe someone else can try it as well just to make sure it is not just me :)

**Comment by AFADoomer** [comment]
Between this and the shader branch not working, I think something's broken in your build process.

**Comment by AFADoomer** [comment]
I would recommend reverting at least the pain and vignette images, so that the wider bars on the side don't get squished in at lower resolutions.

**Comment by Tormentor667** [comment]
Just done.
