### ISSUE TITLE
Fullscreen/Screensize 11 HUD: "Messageless" pickup widgets?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#648]
Given the general improvements being made under-the-hood, would it also be possible to add "pickup widgets", absconding with the traditional quartet of text messages that GZDoom provides? As-is, traditional notifications will obstruct certain elements of either HUD, any way you slice it.

For Health/Armor/Inventory widgets, you could show text-based widgets in the lower-left corner like "+20 Health", "Flak Jacket (100 Armor)", "Bandages x2" and so on. For the lower-right, you can display ammo pickups like this: "[Ammo Icon/Name] +32".

Naturally, these notifications could accumulate if appropriate items are picked up during a few seconds.

**Comment by Tormentor667** [comment]
Do you mean text messages if you collect something?

**Comment by Shockwave508** [comment]
Something like that, yes. Just so long as they don't obstruct mid-mission dialogue or the upper-left widgets.

**Comment by Tormentor667** [comment]
But we have these already:
![grafik](https://user-images.githubusercontent.com/10298439/119385047-e155ae00-bcc5-11eb-8e71-7abb847d9d54.png)

**Comment by Talon1024** [comment]
I think @Shockwave508 means something [like this](https://forum.zdoom.org/viewtopic.php?f=46&t=72283), wherein changes to the numbers are shown beside the numbers.

**Comment by AFADoomer** [comment]
I have some thoughts and initial work on this in a working branch where I'm experimenting with named "widget" classes that can be arbitrarily placed on the fullscreen hud.  

I was also debating changing the default message printing locqtion to screen center to keep the top left from being obstructed.

**Comment by Tormentor667** [comment]
> I was also debating changing the default message printing locqtion to screen center to keep the top left from being obstructed.

I second this. Regarding the widgets, now I understood. That's nice indeed.

**Comment by Username-N00b-is-not-available** [comment]
Is the current implementation good enough for you @Shockwave508, or some more features could be added? Can the issue be closed?

**Comment by Shockwave508** [comment]
Yes, I believe it can be safely closed now. :)
