### ISSUE TITLE
Fullscreen/Screensize 11 HUD: Briefing/level-transit dialogue still uses Screensize 10 assets.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#649]
While the mid-mission/NPC-interaction dialogue now appears in its new Fullscreen incarnation, briefings at Allied HQ, as well as level-transit dialogue with Cpt. Douglas, still retain their Screensize 10 appearance.

![Screenshot_2021-05-17-00-43-00-312_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/118437903-0e440880-b6a9-11eb-817e-88011d8dbbff.jpg)

**Comment by AFADoomer** [comment]
Yes, this is the last type of message that I need to re-work.

**Comment by Talon1024** [comment]
I'm working on that right now

**Comment by Shockwave508** [comment]
New screensize-11 message assets are good and working. Safe to close.
