### ISSUE TITLE
C1M4: Water tower near the final artillery cannon is non-solid; player can clip through its model.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#652]
The water tower depicted in this screenshot can be walked through, due to the lack of solidity in its model tags. I can only presume that other water towers in the game exhibit similar issues.

![Screenshot_2021-05-17-11-11-10-520_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/118548781-49355300-b720-11eb-97b1-dcc457c40d8c.jpg)

**Comment by Ozymandias81** [comment]
It should be the only one, since it needs to be enclosed over blocking sectors usually, and C1M4 has always been a problem with HOMs
