### ISSUE TITLE
Fullscreen/Screensize 11 HUD: Compass still self-hides during messages, despite the adjustments to dialogue boxes.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#653]
Despite the amount of screen-space freed-up by the new fullscreen dialogue boxes, the Compass still hides itself when mid-mission and briefing dialogues are being displayed.

**Comment by AFADoomer** [comment]
This should no longer happen unless you are using the old-style dialogues.

**Comment by Shockwave508** [comment]
Can confirm that the issue's resolved. Safe to close.
