### ISSUE TITLE
Secret zombie map instead of tank map

### ISSUE THREAD

**Issue by wesp5** [Realm667/WolfenDoom#654]
I played episode 3 and after finishing the first concentration camp map, I got the tank briefing at the hub, but the next map I got was the winter map that seems to have been the secret zombie map. After finishing that I was back at the hub and got the tank briefing again, this time following by the correct map. So how are you supposed to enter the secret zombie map the correct way?

**Comment by Talon1024** [comment]
You enter the "secret zombie map" by talking to AFADoomer at Allied HQ after collecting all of the clues from Schattenau, and then getting the briefing for that level from Gen. Miller. There are 6 clues to find at Schattenau.

**Comment by MuadDib90** [comment]
Yes, exactly as @Talon1024 said.

You are told in the C3M1 mission to bring all clues back to Lt. Arlow. That's where you are told what to do. (If you read messages and so...)

Also, if you complete missions and go directly to another briefing (not "browsing" through HQ intermap), you'll sure miss some hints, info, and as in this case - more importantly - secret mission. (And I don't mean it in a mean way... just saying)

**Comment by wesp5** [comment]
Okay, so I think I figured out the problem: I found all clues and talked to Lt. Arlow, but I went to the briefing room before talking to him so I got the tank mission briefing instead and the general will not give another one afterwards. So you need to disable the general giving a briefing until the playes has spoken with Arlow in case the player has found all clues!

**Comment by Tormentor667** [comment]
Yes, something like „please speak to Lt. F. Arlow before we proceed“ might work. @Talon1024 do you think you can realize that?

**Comment by Talon1024** [comment]
And FORCE the player to play the secret zombie map if they've collected all the clues? I don't think that's a good idea.

**Comment by wesp5** [comment]
You could add a choice to the dialogue with the general, like "Are you ready? 1. Yes, go ahead. 2. No, I have to talk to Lt. Arlow first." In case the player chooses 1. Lt Arlow should have a different text too, as if somebody else would do his mission and so the change to the secret map is not triggered.

**Comment by MuadDib90** [comment]
The easiest way of solving this, according to me, with as less intervention to the code itself as possible:

Remember that "one time dialog only" with Miller at the very beginning of the game, when he welcomes you? After that "are you prepared for another mission: 1.yes 2.no" dialog appears the first time. So how about adding such another "one time" dialog after returning from C3M1 with Miller?

He could go: "Welcome back, William. It was very hard for me to sent you over there, but you've made it. And saved countless lives. You may rest for a bit now and take this opportunity to talk to Lt. Arlow, if you haven't done already. About the clues, if you have found any. He may be up to somthing. - After you regain your strength again, report back to me. Dismissed."

And after this the common phrase "are you prepared for another mission..." can go as usual.
This way we can leave to a player an opportunity of choosing, with also gently remind him to bring the clues to Lt. Arlow first in case he want to play the secret mission, but forgot.

**Comment by Tormentor667** [comment]
That sounds reasonable indeed. We just need to make sure that this can't be broken as well by mixing up things (e.g. talk to the General, then to Farlow, then activate the secret mission)

**Comment by wesp5** [comment]
While you are contemplating text changes, can you please include somewhere that the alternative fire button of the blade fires projectiles? Maybe I overread it, but I always thought alternate fire ist just to ignite it and I never figured it out :)!
