### ISSUE TITLE
stamina runs out being on the truck

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#655]
Just a minor issue. When being on the truck, you can actually 'run' and the stamina meter goes down.

![Screenshot_Doom_20210513_031336](https://user-images.githubusercontent.com/77861029/118557162-1792ab00-b765-11eb-9ed6-130befa45f0d.png)

**Comment by Tormentor667** [comment]
Why would you run if you can't run anyway? :)

**Comment by x3003** [comment]
Why does the meter goes down when I can't run ?

**Comment by Tormentor667** [comment]
That should happen but it’s a minor issue I guess
