### ISSUE TITLE
bj's stamina

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#656]
Just an idea...
It would be nice if bj's stamina improves all the time. Idea is when you start to play a new chapter his stamina is a bit low and he can't run very far w/o being out of breath. Like it is now basically. But on every mission you do, he's getting fitter and fitter, so he can run just that bit more for longer.

**Comment by Shockwave508** [comment]
Or perhaps tie it to the Vitality Serums as a secondary effect, on top of the permanent +5% max health bonus.

**Comment by x3003** [comment]
Well, it was just an idea.

**Comment by Tormentor667** [comment]
And we appreciate that :)
