### ISSUE TITLE
Messages differ

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#657]
Maybe it's being worked on, but some of the messages differ, some are small, some are large.

![Screenshot_Doom_20210517_195006](https://user-images.githubusercontent.com/77861029/118558103-73116880-b766-11eb-81ab-448762df173b.png)

![Screenshot_Doom_20210517_194925](https://user-images.githubusercontent.com/77861029/118558219-9b996280-b766-11eb-8eca-f4a2787e0be0.png)

**Comment by Talon1024** [comment]
This should be fixed in 83f900f4a698423d5455e6c886f8b51de52cd509
