### ISSUE TITLE
Fullscreen/Screensize 11 HUD: Message boxes obstruct ally/structure/enemy health bars.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#658]
In Operation: Paris (C1M5), the Nebelwerfer's health bar (as well as those of Übersoldats and tanks) can be obstructed by Douglas' mid-mission dialogue. I can only guess that this also generally applies to any situation where both dialogue and health bars appear simultaneously.

**Comment by AFADoomer** [comment]
They always have...  You just couldn't see them through the old message bar.

I need to add something to track the bottom draw height for messages (and top draw height for items on the bottom)...  Not a high priority, though.

**Comment by AFADoomer** [comment]
This should be resolved now.

**Comment by Shockwave508** [comment]
Can confirm it's all working properly now. Safe to close.
