### ISSUE TITLE
text looks blurry

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#659]
When starting today's git version, pretty much all text, also from the info screen / dialog / etc looks blurry. Seems there's a bigger grey border around the text.

This one was from the 16/05 git, which is much sharper.

![Screenshot_Doom_20210517_195006](https://user-images.githubusercontent.com/77861029/118721593-5d19ab80-b82b-11eb-96a2-4ae483b20815.png)

This one from the 18/05 git.

![Screenshot_Doom_20210518_223358](https://user-images.githubusercontent.com/77861029/118721718-80dcf180-b82b-11eb-8132-838ca278add0.png)

**Comment by Shockwave508** [comment]
It's not just you; it's happening to me on Delta Touch as well...I'm guessing the font's borders were tweaked somehow. No texture filtering was used on my end.
![Screenshot_2021-05-18-17-13-08-321_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/118730081-a1da1e00-b7fc-11eb-9187-1e5b2056f92e.jpg)

**Comment by AFADoomer** [comment]
Are you sure that you didn't somehow turn on texture filtering (Options/Display Options/Texture Options/Texture Filter Mode)?

**Comment by Shockwave508** [comment]
In my case, I choose to use "None (Trilinear)", with 16x Anisotropic Filtering.

**Comment by AFADoomer** [comment]
And your screenshot looks normal...  Honestly, the conversation code hasn't been touched in ages.

**Comment by Talon1024** [comment]
This looks more like an issue with the Gamma or text colours to me...

**Comment by AFADoomer** [comment]
I don't see it on my end.

**Comment by Talon1024** [comment]
I think I know why: OBJ_YES and OBJ_NO were added to the smallfont, and those images don't have the same palette as the other characters.

**Comment by MuadDib90** [comment]
I experienced the same issue.

But when trying, I've found out that you can finish the C1M1 without killing Schabbs Jr., thus without checking the third objective. Just an observation...

**Comment by x3003** [comment]
For me, texture filter is always set to linear. But that was already w/ the older versions.

**Comment by Tormentor667** [comment]
I know whats the problem now. The 1-pixel-thick border around the font was darker im previous releases and therefore better to read. Not it's mich brighter, that's what it makes harder to read and blurry. What was changed here?

**Comment by AFADoomer** [comment]
It's what @Talon1024 said above - I added the box and check mark images used by the objectives as the corresponding unicode characters, but they use a different pallette, so the internally calculated font coloring scale is different now.  I'll have to revert that piece and do the check marks differently.

**Comment by x3003** [comment]
Seems fine now.
