### ISSUE TITLE
NPC Conversation Menu: No character portraits are animated except for Lt. Laz Rojas.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#660]
Not sure if it's from ZScript limitations or a lack of appropriate sprites, but Lt. Laz Rojas from the Allied HQ Armory seems to be the only NPC with a fully-animated character portrait in the conversation menus. When talking to any other NPC, their face remains static on those same menus.

**Comment by Tormentor667** [comment]
There are various inconsistencies here.

**Working** are Halderman, Laz Rojas, Big Dave
**Not Working** are Nash (even though using the same as Big Dave), Juliette, Gutenberg

As far as I can remember, @AFADoomer uses a system that checks the text and accordingly reacts with animation. Maybe something is broken here now.

**Comment by DoomJedi** [comment]
I always thought animations are WAY too fast. BTW.
