### ISSUE TITLE
INTERMAP/Chapter 1: During Douglas' tutorial, additional grenades cannot be taken from the shelf.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#661]
While playing the tutorial offered by Cpt. Douglas, you cannot grab additional grenades from the shelf once you run out of them, leaving you unable to finish if your throwing aim is off.

**Comment by mcphail** [comment]
I had similar issues in #506

**Comment by MuadDib90** [comment]
I can confirm, the shelf can no longer be used for adition grenades. (I got 1 maybe, nothing else afterwards...)

**Comment by Tormentor667** [comment]
It only works one time, then stops working.

**Comment by Ozymandias81** [comment]
Tested, it works.

**Comment by MuadDib90** [comment]
> 
> 
> Tested, it works.

I confirm.
