### ISSUE TITLE
Objective Notifications: Not scaled properly with Fullscreen HUD.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#662]
Objective notifications of any sort aren't scaled properly with the rest of the Fullscreen HUD.
![Screenshot_2021-05-19-02-48-37-027_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/118776234-63208400-b84d-11eb-8e9e-0418f049da21.jpg)

**Comment by Tormentor667** [comment]
Confirmed, it's not working yet.

**Comment by AFADoomer** [comment]
Yeah, my scaling is off.  Will fix tonight.

**Comment by Shockwave508** [comment]
Issue's been solved. Safe to close.
