### ISSUE TITLE
McDonalds and CocaCola in Germany

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#665]
![grafik](https://user-images.githubusercontent.com/10298439/119020434-827af680-b99e-11eb-87a3-b3e110a616b1.png)
![grafik](https://user-images.githubusercontent.com/10298439/119020441-8575e700-b99e-11eb-86fc-4ed50ac7a1a1.png)

Considering the situation, there shouldn't be "Coca Cola" or "McDonalds" in Germany, so these sprites need to abe altered. 

Instead of "Coca Cola", we can use "Fanta"
![grafik](https://user-images.githubusercontent.com/10298439/119020570-ac341d80-b99e-11eb-87f7-012ce81df983.png)

Any ideas for "McDonalds"?

**Comment by DoomJedi** [comment]
Why not?
https://www.historyanswers.co.uk/history-of-war/how-coca-cola-won-a-place-in-adolf-hitlers-heart/

Cola was in Germany way before Fanta. 
Google is full with German/Nazi posters, bottles of Coca Cola etc, commercials, that started long before the War and was endorsed by nazis.

I don't mind to change it to Fanta of whatever,.
But depending on how historically accurate we would want it to be - those will be ugly and unrecognizable, as they had no label on them, just transparent brown/reddish glass.
Those are just not sprite-friendly in any way, sure not in those resolutions.
We can use freedom to add "more later" label on them, and if so - it doesn't matter much to me if to write fanta of cola on the label.
Or you can give me freedom to tweak bottle design as I wish - from pure historical look.
I think if we add some related fanta/cola german posters to walls there it'll make good context to the sprites and make them more visually readable.

**Comment by Tormentor667** [comment]
Fast food was not existent during the 30s in Germany so it is hard to find an equivalent. 

I guess we need to generalize that somehow or replace the McDonals meal with sauerkraut and sausages

**Comment by DoomJedi** [comment]
I'll do some research on that and will try to come up with as much "fast food"-like variants from the era.
Those need to be visually recognizable though.

**Comment by DoomJedi** [comment]
So Fanta was made and added to replace "modern design" Cola.
For the rest - will need more ideas, fitting historically and visually recognizable by general public.

**Comment by Ozymandias81** [comment]
Maybe we can make a fictional/parody brand called HFC, where H stands for Hitler and use red/yellow/black colors for enemies food and then use a different brand as ally food, AFC , this time using red/blue/white ?

[KFC](https://cdn.slidesharecdn.com/ss_thumbnails/kfcgroup-6-190306100535-thumbnail-4.jpg?cb=1551866841) orginal brand has been found in Kentucky on 1952, and the idea comes from Harland Sanders, which has been a colonel too.

**Comment by Gaerzi** [comment]
I find it odd to worry about historical accuracy in a Wolfenstein game.

Especially one that puts Egyptian ruins in Tunisia, or asserts there's only one bridge in Paris. :p

**Comment by DoomJedi** [comment]
Regarding historical accuracy - I can see both sides here. And I don't care nearly as much for it in my mods.
Yes, I think we go too much into it, and yet when I made those sprites - I wondered to myself why noone mentioned those items looking totally modern-day in their designs and logos.

I like the KFC idea, used it before in my "Batman No Man's Land" mod where it was BFC (Batman Fried Chicken) logo.

**Comment by Tormentor667** [comment]
We could still turn these into HFH -> Hitler's Frittiertes Hühnchen - and make them look like KFC, just with Hitler's face.

**Comment by DoomJedi** [comment]
Ok, will add this to my tasklist.

**Comment by Tormentor667** [comment]
Now I am curious how this sick idea ends up :D

**Comment by DoomJedi** [comment]
Well, it's just left for Virg to upload...

**Comment by Ozymandias81** [comment]
All common fastfood related pickups have been replaced, and modders can still use old ones by placing them on maps with FastFood11-12-13-14. So gonna close this? :sunglasses:

**Comment by Tormentor667** [comment]
Yes, well done guys!
