### ISSUE TITLE
Model issue with trees

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#667]
If trees are tilted and laying at the side (as in C3M0_B for example) you can look "into them". Can this model be closed on the bottom somehow to prevent this?

![grafik](https://user-images.githubusercontent.com/10298439/119021151-5ca22180-b99f-11eb-9b73-f79fd0742460.png)

**Comment by AFADoomer** [comment]
This should be resolved; @Tormentor667, can you please test to see if this fix looks good to you?

**Comment by Tormentor667** [comment]
The usual @AFADoomer - quality, what can I say, it looks perfect :)
