### ISSUE TITLE
[C3M0_B] Stierlitz dialogue issue

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#668]
From CaptainJ

> Tho i talked to him already but once i end the conversation, the objective notification keeps showing plus the exclamation mark on the automap unless if it was not intentional.

![grafik](https://user-images.githubusercontent.com/10298439/119021257-82c7c180-b99f-11eb-9081-94d58c398a12.png)

**Comment by MuadDib90** [comment]
I adressed this issue couple days ago (can't find the exact issue), and it was repaired by @Talon1024 or @Ozymandias81, if I am not mistaken.
So why it is here again, that I have no idea; unless you play older version than the last commit...

**Comment by Tormentor667** [comment]
Very good then :)
