### ISSUE TITLE
[INTERMAP] C3M0_B can be played more than once

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#669]
> So i beat the super-duper super secret map that is Raubgold. However i still can start the map all over again and is this intentional?

I just checked the INTERMAP and the line is only "use-once", so how it is possible to replay the map?

**Comment by Talon1024** [comment]
Maybe there's more than one linedef that runs the script which lets you play through C3M0_B? Or said player warped to C3M0_B using the `map` CCMD?

**Comment by Tormentor667** [comment]
He didn't warp with the map command and I also checked the INTERMAP, there is no second line. I will just check it myself now.

**Comment by Tormentor667** [comment]
![grafik](https://user-images.githubusercontent.com/10298439/119025983-f4eed500-b9a4-11eb-92c0-fc210550babb.png)

I do get this now, so I can't test. Seems to be a font issue according to the error message. I get prompted to this after the end scene of C3M0_B

**Comment by Tormentor667** [comment]
> Ugh. Search for "Font Symbols" in the objective handler ZScript file (line 5 or 6) and put "transient" at the beginning of that line and that might fix it.

In Germany we have a common saying: "Ich verstehe nur Bahnhof". I think a proper translation for that is "It's all double Dutch to me." (?)

**Comment by MuadDib90** [comment]
Yeah, I know exactly what you mean, man.
We say: "It's a Spanish village." (But don't know why though...)
And Polish people say: "It's a Czech film." :D Lovely!

**Comment by Tormentor667** [comment]
Can't reproduce playing C3M0_B a second time so I will close this.
