### ISSUE TITLE
[INTERMAP] Friendly fire

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#670]
From CaptainJ's playthrough:

> Just about to click on the debug panel at the invisible wall i heard the gunfire. I loaded the map again, typed freeze at the console and then i found the reason why. It was this guy firing at the target... For some reason. I dunno what makes him angry.

![grafik](https://user-images.githubusercontent.com/10298439/119022304-c969eb80-b9a0-11eb-84bb-6d90feedd671.png)

**Comment by MuadDib90** [comment]
Maybe those tanks, that are marked as "enemies"? (Even are counted on automap.)

**Comment by Tormentor667** [comment]
Good guess, I will just make them friendly, this should solve the problem here.

**Comment by Tormentor667** [comment]
That's why I did something else, see my latest commit :)

**Comment by MuadDib90** [comment]
And that's what we call a "GZDoom magic". Good work, private Torm! :D:D
