### ISSUE TITLE
[SM01] Floating enemies

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#673]
From CaptainJ as well:

> This Guy floats for a while if there's a Mad Mushroom above him.

![grafik](https://user-images.githubusercontent.com/10298439/119023038-9aa04500-b9a1-11eb-9835-6dd9a5e76416.png)

**Comment by Tormentor667** [comment]
Is this minor enough to simply close it?

**Comment by Username-N00b-is-not-available** [comment]
How could he even get the Bounder there? Ride the platform upwards and just wait until it randomly jumps under the Mushroom?

**Comment by AFADoomer** [comment]
He had to have.  They won't bounce onto platforms by themselves.  

I'm not planning to put too much work into fixing this...

**Comment by Tormentor667** [comment]
Agreed :)
