### ISSUE TITLE
[SM02] Issue with blue fire ball

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#674]
From CaptainJ:

> Not sure if it was intentional but this fella's flame doesn't reach, making it barely harmless.

![grafik](https://user-images.githubusercontent.com/10298439/119023123-b6a3e680-b9a1-11eb-9ac7-81b43a6c0cb4.png)

**Comment by AFADoomer** [comment]
Keep standing there and see how well you do, then 😄.

When I summon one (cummon cklick), i t pushes itself toward me and does 10-15 damage every second or so.  I'm not sure what the bug is here?

**Comment by Tormentor667** [comment]
Same here, for me it works as intended.
