### ISSUE TITLE
[3.2] Commander Keen has no Pogostick spriteset 

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#675]
From CaptainJ:

> I can see Keen's death animation in third person but not the pogostick one.

![grafik](https://user-images.githubusercontent.com/10298439/119023434-2c0fb700-b9a2-11eb-8dbb-99af995fe3f9.png)

**Comment by AFADoomer** [comment]
The sprites are there (rear view only), and this used to work...  He also has dedicated jumping/falling sprites.  Not sure what has changed.

**Comment by AFADoomer** [comment]
The sprites are there (rear view only), and this used to work...  He also has dedicated jumping/falling sprites.  Not sure what has changed.

**Comment by Tormentor667** [comment]
![grafik](https://user-images.githubusercontent.com/10298439/119026727-c9b8b580-b9a5-11eb-84e0-754e5bb79f17.png)

Just tested it, it works indeed. I'd point @DoomJedi to this though for the other sprites considering the coop plan that we have for a possible 3.2 version.

**Comment by DoomJedi** [comment]
Most of BoA keen sprites were made by Nisaba and Keen community spriters, we better ask them for a bit more help.

**Comment by Tormentor667** [comment]
> Most of BoA keen sprites were made by Nisaba and Keen community spriters, we better ask them for a bit more help.

Can you get in touch with them once more?

> Regarding coop I still didnt hear solutions for 1dir Bosses and enemies like grenadeers, rpg guys etc.

This is a different topic but I am pretty sure we will find a solution that for that as well. I just thought about a way to modify the one-sided sprites to make the player understand where the enemy is facing, maybe with a sprite overlay on the ground, with a pointer for the actual direction.

**Comment by DoomJedi** [comment]
I have no problem asking Keen forum for more help, but can you sum up the sprites needed? Pogo rotations, anything else? Jumping, Falling....basically all Keen sprites fully rotated?

**Comment by Tormentor667** [comment]
We have most of it, afaik we only need the pogo sprites that we currently have in all directions. Maybe @Ozymandias81 can do the usual magic?

**Comment by DoomJedi** [comment]
I'll post on Keen forum.
If they won't help - as you know - I'm ready the be Plan B for stuff they won't supply for any reason.

**Comment by Tormentor667** [comment]
So has anything appeared on the Keen forums yet?

**Comment by DoomJedi** [comment]
Nope...

**Comment by Tormentor667** [comment]
Link for reference: https://pckf.com/viewtopic.php?f=6&t=10416&start=30

**Comment by Tormentor667** [comment]
Nisaba is working on it but it will take a while as she has other things to do atm.

**Comment by Ozymandias81** [comment]
Just [replied today](https://pckf.com/viewtopic.php?p=100019#p100019) with 3.1 link and tease for 3.2 :cool:

**Comment by Tormentor667** [comment]
Pushed: https://pckf.com/viewtopic.php?f=6&t=10416&p=101037#p101037

**Comment by Tormentor667** [comment]
Pushed again: https://pckf.com/viewtopic.php?p=102629#p102629

**Comment by Username-N00b-is-not-available** [comment]
Looks like we'll need DoomJedi's help here, if he has time.

**Comment by Tormentor667** [comment]
@DoomJedi summoning :)

**Comment by DoomJedi** [comment]
Where am I? What am I doing here? How summoned me?  :-O

...love you have you back N00b! How are you, pal? (have been following your recent return and burst of activity and contribution, keep it up!
You can always talk to me over russian Doom forum (I see you read my last PM eventually)

I'll need to see about that old pending task.
Will fetch origin now to see what's missing.

...CaptainJ might be an option as well, fantastic spriter and helped before (?) Or does he prefer Doom art?

**Comment by DoomJedi** [comment]
I see Keen front shooting frames are very inconsistent and even not evident and need total remake as well.

Well...let's see.
Tomorrow is a busy day (country's Independence Day, guests, barbecue)  not sure I'll get anything done, but after that I have some free days and can look at it.

**Comment by DoomJedi** [comment]
All Keen rotation frames need remake actually, now looking at it.

**Comment by Username-N00b-is-not-available** [comment]
Hello, @DoomJedi! Nice to meet you again, too! I'm (mostly..?) fine, just had too big of a workload in my institute, now I have time for a small break (and a larger one later in the summer). I hope my recent contributions made the re-release date closer, i. e. I introduced fewer bugs than fixed :-)
As for the sprites, they can wait, of course. If you don't want to fix them yourself (too much time), you can try to explain me what in your opinion is wrong with them, and I'll try to implement your guidelines. Concerning the old PM on RDC, I've translated most of the remaining strings up to date, only a few unimplemented menu options remain that refer to... well, I do not know what.
Congratulations on the holiday!

---
By the way, what do you think of #1300 point 2? I sure as hell am not inviting you to do another **7000** 'hitmap' sprites; this should be done via automated tools, or only for specific enemies. Asking you as a modder and a player, not a spriter :-)

**Comment by DoomJedi** [comment]
> ...... If you don't want to fix them yourself (too much time), you can try to explain me what in your opinion is wrong with them, and I'll try to implement your guidelines.

I appreciate the offer (already did now new standing rotations frames BTW).
I'll see what I can do (it's a big workload indeed), and I always give you guidelines about the rest.
About what's wrong - take into account that side shooting frames are the true ones from the game and the rest need to be pose consistent with those and generally readable visually.
Shooting rotations are a wrong pose (just as Pogo lower frame) and in front frames - those are not readable as shooting frames - the gun is not visible/visually readable as such, hand is too "centered to the body" which makes it less readable as well. First rotation in just not readable pose wise and direction/perspective-wise.

> Congratulations on the holiday!
Thanks! :)

> By the way, what do you think of #1300 point 2? I sure as hell am not inviting you to do another **7000** 'hitmap' sprites; this should be done via automated tools, or only for specific enemies. Asking you as a modder and a player, not a spriter :-)

Well, that's a cool feature, I think first we need to make it work with what we already have in the game - it means making actual headshots and not "random-loaded" ones.
One more idea - we can make gibbing trajectory direction (of skeleton bones for example) and general gib sprite inertia to refer to actual part body with hit in - if hit to the left side-gibs will fly mostly to the right etc.

**Comment by DoomJedi** [comment]
So far did:

standing rotations, 
2 walking rotations (rotation 2 and 5), 
1 shooting rotation (rotation 1), 
1 pogo rotation (rotation 1).

Time to sleep :)

**Comment by Tormentor667** [comment]
You are a spriting machine :)

**Comment by DoomJedi** [comment]
Thank you.
While not the same quality as the Blue Bird (rotation accuracy-wise, as I try to reuse existing Keen art "elements" where possible) - I do put attention to animation consistency, perspective consistency and readable poses.

**Comment by DoomJedi** [comment]
Finished shooting rotations.
Guests are arriving soon so not much more today probably.

**Comment by DoomJedi** [comment]
Here are standing, walking and shooting rotations for Keen player.
Those need proper renaming, transparency, offset.
https://www.dropbox.com/s/6asyrqvc9y55oqo/Keen%20frames.zip?dl=0

Still working on the pogo ones.

**Comment by DoomJedi** [comment]
Keen standing, walking, shooting and Pogo rotations:
https://www.dropbox.com/s/6a6mb21w2pysnxc/Keen%20frames.zip?dl=0

Those need proper renaming, transparency, offset.

I used latest github frames as a task, if there are additional actions/frames used that are beyond what is in 
GitHub\WolfenDoom\sprites\misc\easteregg\ckeen\player

You can try give me additional tasks related those, as I didn't find there frames used for jumping, climbing and such tasks.

**Comment by Tormentor667** [comment]
Brilliant!

**Comment by DoomJedi** [comment]
Thank you :) Work of love both for Keen and for this project.

**Comment by Ozymandias81** [comment]
Will put them on repository as soon as I can, thank you very much @DoomJedi

**Comment by Ozymandias81** [comment]
Alright just put most all of the new frames, we need shooting frames since we have only the first set on your dropbox zip, feel free to come with the second variant whenever you can @DoomJedi

**Comment by Ozymandias81** [comment]
Replied on FB chat

**Comment by DoomJedi** [comment]
Please be patient with me here, I'm just trying to understand Keen shooting frames.

Original Keen game had only 1 shoot frame, as zap itself was a separate sprite.

Doom shooting frames usually have aiming frame, shooting flash flame (sometimes 2 for bullet weapons) and sometimes alert/attack prepare frame.

Can you please will me how many shooting frames we should have and a description of each - which phase of shooting they depict.
I see only E and F shooting frames...so 2 frames?
The second one is just with shooting zap flash added?

**Comment by DoomJedi** [comment]
Here made "zap" shooting frame as second shooting frame:
https://www.dropbox.com/s/dz1z0uwcwv1g5ws/Keen%20Shooting%20Rotations.zip?dl=0
