### ISSUE TITLE
[Keen levels] Suggestion for "restarting" the map

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#676]
> And Commander Keen levels in general, if you die, it takes you to the reality, the Allied Headquaters. However you can prevent it to happen by pressing the button after Keen died as quickly as possible. You could enhance it by telling the players to press the buttons to try again, or don't if you want to leave the secret level.

**Comment by Username-N00b-is-not-available** [comment]
This will need replacement with a ZScript menu, the existing system is just a simple ACS "death script" crutch. Something should also be done with autosaves that are spammed with each return to another map and can quickly overwrite earlier ones.

**Comment by Tormentor667** [comment]
@Username-N00b-is-not-available you should make a new issue for the autosave spam. I guess this happens scriptwise through the library. I wonder, is this really a big deal? I kinda found that useful.

**Comment by Username-N00b-is-not-available** [comment]
Bringing this up for attention of @AFADoomer and @Talon1024.

**Comment by AFADoomer** [comment]
Already working a custom menu to match Keen 4 death prompt.

**Comment by AFADoomer** [comment]
Implemented in 8aad61b185a6ecef92bff27cf1079904f1017117.
