### ISSUE TITLE
Game fails to make saves of any sort; cites unhandled NativeStruct<Font> variable.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#677]
When attempting to save the game or leave a mission, the game fails any attempts to auto- and manual-save, citing something about the font as the problem. See also: Attached screenshot.

![Screenshot_2021-05-20-10-08-56-134_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119041246-01ab0300-b97c-11eb-976e-ec4e8e37b989.jpg)

**Comment by AFADoomer** [comment]
This was noted earlier.   It's a one-word fix (add "transient" before "Font Symbols" in the objective code.  Will commit tonight if no one else does before I get to it.

**Comment by AFADoomer** [comment]
Between @Talon1024's fix and my 61b4a2336f4f962c0f4ad1b447dca2cb7b49c4f8, this is resolved.
