### ISSUE TITLE
can't hit enemy at a certain spot

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#678]
In c1m6, you can't shoot between the tree and the rock, so you can't hit this enemy unit from this position.

![Screenshot_Doom_20210521_165849](https://user-images.githubusercontent.com/77861029/119157837-ddbbf000-ba55-11eb-8098-98910278bc78.png)

**Comment by MuadDib90** [comment]
I think that is a (unfortunate) legacy of id1tech...
Someone would just made the tree, where "it exactly is" in space. But the tree occupies a block in space.
![obrazek](https://user-images.githubusercontent.com/73436978/119173704-eae1da80-ba67-11eb-9b8c-764c9c74285f.png)
And I don't really know it that is even possible...
