### ISSUE TITLE
Allied HQ Conversations: Inconsistent "talking" pics for Allied troops and the Toilet of Wisdom.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#680]
When talking to Sgt. Nash or Lt. "Big" Dave, their talking picture will randomly shift their jacket color between brown and white.

The Toilet of Wisdom's talking picture is absent during conversations.

**Comment by AFADoomer** [comment]
Toilet is fixed in 2e890a4a690c0416736993bf39bfcab60f81845a.

The soldier mugshot images have a 0 frame with a different color jacket than the other frames for some reason.

**Comment by Tormentor667** [comment]
Fixed.

**Comment by Shockwave508** [comment]
I can confirm both issues have been resolved; should be safe to close now.
