### ISSUE TITLE
C1M0: Gas countdown timer obstructs Übermutant health bar.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#681]
When facing down the Übermutant boss in Operation Eisenmann, the gas countdown timer obstructs its health bar.
![Screenshot_2021-05-21-20-58-15-363_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119211529-5633a880-ba78-11eb-84d9-e0865381ab99.jpg)

**Comment by Tormentor667** [comment]
Besides the bug report, I want to thank you for all the testing you are doing :) this is very helpful!

**Comment by MuadDib90** [comment]
> Besides the bug report, I want to thank you for all the testing you are doing :) this is very helpful!

Same here. :)

**Comment by AFADoomer** [comment]
What they said 😄.

This is also fixed as of 8f06af759ff53518402245e4ca1a4dd36159d280.

**Comment by Ozymandias81** [comment]
Btw I see you are playing with some on screen damage indicators, please playtest the release as intended.
