### ISSUE TITLE
Certain assets still need ultrawide support.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#683]
1) The Kar98K scope's dimming effect on the sides doesn't reach all the way on wider aspect ratios.
2) The main menu's title/black bar doesn't span the entire width of 21:9.
3) The blue background in intermission/episode-end cutscenes doesn't reach far enough in ultrawide ratios.

Note: Do ignore the touch buttons on the screenshot; it's a side-effect of playing on Delta Touch, as they appear when using a "menu" interface, ZScript or otherwise.

![Screenshot_2021-05-21-19-31-07-190_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119228803-55cbf980-bada-11eb-9ed4-09dac360571e.jpg)

**Comment by Username-N00b-is-not-available** [comment]
It would not be desirable just to change these graphics to 21:9, since who knows if something like 35:9 would become popular ten years later. The existing graphics for 2. and 3. should be drawn fullscreen as in DTA_FullScreen (instead of DTA_FullScreenEx which is used in multiple DrawTexture calls now).
Not sure what we could do with the rifle...

**Comment by Tormentor667** [comment]
I fixed the menu graphics as in 2). but for some reason I can't fix 3) - they are already 21:9 actually. For the scope, I don't have a PSD for that, who created them?

**Comment by Shockwave508** [comment]
Quick question: Is the Space Suit's helmet not supposed to scale to screen width? In the second half of Astrostein (C2M0_B), i found that my field of vison was significantly narrowed while it's active.

**Comment by AFADoomer** [comment]
I think these are all addressed now...

The space suit does not scale, no - both it and the gas mask intentionally limit your FOV.
