### ISSUE TITLE
"Alternate" Objectives Widget: Also show Kills, Secrets, and Treasure?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#685]
Just tried out the alternative objectives widget, and enjoying how it blends in with the fullscreen HUD, whilst being unobstructive. Adding to that, would it be possible to show Kills, Secrets, and Treasures in the upper-left corner, as a trio of icons and numbers, so players can keep track without needing to open the Automap?

For kills, I imagine a red skull would fit nicely.
For secrets, how about a gold question-mark?
And for treasures...I'm not sure really!

**Comment by Tormentor667** [comment]
I think adding these would be a useful and reasonable addition but it fully depends on @AFADoomer if he easily can do that. I just wonder: What do you mean with "alternative objectives widget"? What have I missed? :)

**Comment by AFADoomer** [comment]
I added the 'boa_altobjectivestyle' CVar that, when set to 'true' adds a second display mode to the objective screen, so that when you toggle objectives view twice, a minimal objective display shows up in the top right of the screen.

**Comment by Tormentor667** [comment]
How could I miss that. Can we make that behaviour default? :)

**Comment by AFADoomer** [comment]
Sure, just need to set the default CVar value to true in DEFCVARS.

**Comment by Tormentor667** [comment]
Just did it. d8530b79068837439c2e63ae23bcefa02a059de5

**Comment by AFADoomer** [comment]
This is added now.  Use the 'boa_hudstats' CVar to toggle (it's true by default); the values displayed depend on what you've enabled to show on the automap, and what's actually present in the level.

**Comment by Shockwave508** [comment]
Would it be possible to add a CVAR that always shows the Alternative Objectives Widget, with or without stats, regardless of objectives-related inputs?

**Comment by AFADoomer** [comment]
Just committed this in f2723e63262dca1edaa4c7dad7ca3e5308c2d1a0.
The alt objective style CVar is now named 'boa_hudobjectives'.  Set it to 1 for the old toggling behavior, 2 to always show the objectives.
