### ISSUE TITLE
bj's clothes

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#686]
With todays git, in c2m1, it looks like the clothes bj is wearing is not correct. It looks more like he's going to hike in the mountains, then that he is in prison.

![Screenshot_Doom_20210523_164532](https://user-images.githubusercontent.com/77861029/119270870-2bc02780-bbff-11eb-885b-867c041539c4.png)

**Comment by Shockwave508** [comment]
That's because it's the default player sprites for BJ himself; not sure how much work (likely a lot) it would take for the team to make sprites and rotations for stuff you'd likely only see in mirrors and reflective surfaces. That would go for mission-specific outfits and disguises.

**Comment by x3003** [comment]
Well, in c3m1, he is wearing some kind of prison clothes, so it wouldn't be that hard to give him some of those.

**Comment by Ozymandias81** [comment]
That's just an issue on the code I guess with recent builds of gzdoom, there are frames for all uniforms. Next time @Shockwave508 check inside sprites folder on the ipk3 and you will get it :)

**Comment by Tormentor667** [comment]
The prisoner uniform in C3M1 is a special concentration camp cloth, we can't use that in C2M1 as well. There is currently no prisoner uniform for C2M1. I can imagine though to use the body from Ryan in C1M2 and place BJs head on that, and use this player sprite for C2M1. @DoomJedi

**Comment by DoomJedi** [comment]
(oh man, I really hoped I won't meet the need of yet ANOTHER BJ skin)

It's simple head pasting, Virg done such stuff before, it's better for him to do it.
Another alternative is just to recolor camp outfit, it's just 3 purple colors to recolor to greys. Will make him look more distinct from Ryan.

**Comment by Tormentor667** [comment]
Torm to the rescue. Here is a full set of sprites color adjusted. Only needs renaming and code.
[grey_uniform.zip](https://github.com/Realm667/WolfenDoom/files/6534046/grey_uniform.zip)

**Comment by Ozymandias81** [comment]
Ah that's true, totally forgot that... Gonna add sprites then.

**Comment by Tormentor667** [comment]
Thank you Ozy!

**Comment by Ozymandias81** [comment]
Still need to add bmaps, will do tomorrow :)

**Comment by Tormentor667** [comment]
Brightmaps aren't in yet, right?

**Comment by Ozymandias81** [comment]
Yes not yet, will do them today or sunday
