### ISSUE TITLE
C1M1: Loose collection of rock models levitates in midair.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#689]
After detonating the fire extinguisher to progress further in C1M1, there is a loose collection of rocks that levitates in midair, and I had some difficulty navigating past them.
![Screenshot_2021-05-23-19-04-59-876_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119281132-198fba80-bbfa-11eb-9423-6aafe57e12b7.jpg)

**Comment by Shockwave508** [comment]
Seems to have been fixed in the latest build. Safe to close.
![Screenshot_2021-05-23-20-12-41-131_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119283640-41cfe700-bc03-11eb-8e37-445181f5e6fb.jpg)

**Comment by Ozymandias81** [comment]
Now that there is gzdoom 4.7, always consider that things may get weird when updating the build, happens quite oftenly.
