### ISSUE TITLE
Possible bugs at the end of C2M1 Ausbruch

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#690]
C2M1 Ausbruck bugs ?
There are 5 Things Type 12788 ( T's 3051, 3052, 3053, 3219 and 3853 which are invisible, fire at the player and cannot be killed.
Also T4119 is stuck, and a nearby dog is stuck near line 12115

**Comment by Ozymandias81** [comment]
We need screenshots, gzdoom version and also from where, C3 release or the build from github repository?

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3 Do these things seem to count towards kills? If not, then everything seems to work correctly, as 12788 corresponds to "invisible machine gun turrets":
https://github.com/Realm667/WolfenDoom/blob/c2b1ce9d4d2bfc8b2e5edc3e315b341639d23f66/mapinfo.txt#L1252

**Comment by Ozymandias81** [comment]
I don't see any issues here, so gonna close it

**Comment by Tormentor667** [comment]
The soldier was stuck indeed, fixed it.
