### ISSUE TITLE
C1M5: "No numbers" and "numbers" display in gold text when dialogue, kill/wave status, and Nebelwerfer health are simultaneously displayed.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#692]
In C1M5, the words "no numbers" and "numbers" will display in gold text when dialogue, kill/wave status, and Nebelwerfer health are displayed simultaneously, for a brief moment before the first wave of Krauts spawns in.

**Comment by Talon1024** [comment]
It's probably debug code that @AFADoomer forgot to remove

**Comment by AFADoomer** [comment]
Yeah, it was.  Sorry!
