### ISSUE TITLE
C1M6: Alternate objectives and low-health effects can still be seen and heard during the ending intermission scene.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#694]
When "exiting" the level to finish the episode, the low-health heartbeat/visual effects and the alternative objectives display can still be seen and heard during the ending cutscene.

**Comment by Shockwave508** [comment]
After my latest Episode 1 run, I noticed that this also applies to key items, namely the Spear of Destiny and Red Keen Cartridge.

**Comment by AFADoomer** [comment]
This should be resolved after recent commits...  Can you confirm?

**Comment by Shockwave508** [comment]
Can confirm it's fixed. Should be safe to close now.
