### ISSUE TITLE
C2M1: Two blank lines in alternative objectives display, when it should show just one line at the start.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#696]
When you start Episode 2, there are two blank lines underneath your main objective if you turn on the alternative objectives display.

**Comment by AFADoomer** [comment]
I have fixed this in a working branch, but there are other changes that I need to finish before committing.

There was a flaw in the logic for printing the objectives if an objective was skipped...  It wouldn't stop printing at that point.

C2M1 actually starts with three objectives; one primary and 2 alternate.

**Comment by AFADoomer** [comment]
This should be resolved now.
