### ISSUE TITLE
[C2M0_B] Damaging lasers can be crouched under, without injury.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#697]
In the puzzle rooms leading up to the Cyber-Hitler fight, all of the blockable lasers can be safely crouched under, completely defeating the point of said puzzles.

**Comment by AFADoomer** [comment]
This will need to be a map object placement change for the laser spawners...  The laser beams themself have no height; they are a basically just a model that follows the path of a hitscan tracer and inflicts damage if that hitscan path is broken.

**Comment by Tormentor667** [comment]
@Shockwave508 can you share coordinates or screenshots?

**Comment by Tormentor667** [comment]
> This will need to be a map object placement change for the laser spawners... The laser beams themself have no height; they are a basically just a model that follows the path of a hitscan tracer and inflicts damage if that hitscan path is broken.

The problem here is: If I set the laser spawners lower, you can jump over them. If they are higher, you can crouch under them. Instead could you "emulate height" by adding 2 additional invisible tracers 2-3 units above and below the main tracer?

**Comment by Username-N00b-is-not-available** [comment]
More ideas from the resident ideas guy of the repository: if 2–3 units would be enough, what about making the tracers waggle (change their pitch in a sinusoidal wave: ```pitch(t) = pitch(0) + delta * sin(a * t + b)```, delta is the maximal pitch difference, a and b are constants, possibly slightly randomized for different actor instances)? It might not be enough for situations when the player is able to come close to the emitter.

**Comment by AFADoomer** [comment]
That might be an option.  The tracer is also used to calculate the position of the beam model, though, so I don't think it will work easily.  Best approach will probably be to add 4 additional tracers equidistant from top/bottom/left/right of the main tracer, distance based on model size/scale.

**Comment by Username-N00b-is-not-available** [comment]
> so I don't think it will work easily

Why not have the laser model waggle, too, maybe the effect could be made to look presentable? It will also not deceive the player visually. But I am not against adding 4 tracers, especially since those are hitscan checks and won't additionally hinder the performance.

**Comment by AFADoomer** [comment]
This should be resolved after 04be7f8aaa9436905e6d38847df0e9d6cd2d6576.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer The rotating ones still can be crossed under for some reason.

**Comment by AFADoomer** [comment]
Because they are 2 pixels higher relative to the floor that the player is standing on than the ones in the entry corridor are to the floor there.

**Comment by Tormentor667** [comment]
So should we just lower the rotating lasers by two map units and we are done?

**Comment by AFADoomer** [comment]
I think that would fix it.  Needs to be tested for each level.

**Comment by Tormentor667** [comment]
Fixed.
