### ISSUE TITLE
C2M0_A: Templar Cultists immune to lava damage.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#701]
When a stray grenade knocked some cultists around, they fell into the lava and continued shooting me, none the worse for wear.

![Screenshot_2021-05-26-14-35-55-879_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119753119-d20c6700-be63-11eb-8ebc-e398ed542d81.jpg)

**Comment by AFADoomer** [comment]
There probably need to be monster-blocking lines added here.

With minor exception where I've added special handling, enemies don't respond to sector damage - and the pathfinding AI isn't aware of it at all...  Just like in Doom, where imps and zombies can walk across nukage.

**Comment by Tormentor667** [comment]
Fixed it by adding monster-blocking lines.
