### ISSUE TITLE
C1M5: Flickering texture in diner cripples framerate when viewed from a certain angle.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#706]
When viewing a particular wall/light texture in the diner from a very specific angle, said texture rapidly flickers in and out of existence, dragging the framerate down with it.

![Screenshot_2021-05-27-10-27-17-544_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119890145-16981100-befd-11eb-8f1e-7263d708149c.jpg)
![Screenshot_2021-05-27-10-27-19-899_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119890164-1bf55b80-befd-11eb-9c77-6e8f30927725.jpg)

**Comment by Tormentor667** [comment]
Which engine are you using and which version? This seems like a rendering issue to me, maybe because of the brightmap, the light actor and the texture.

**Comment by Ozymandias81** [comment]
Yeah I can't reproduce it with gzd 4.7 pre4 from both Opengl and Vulkan api's.

**Comment by Shockwave508** [comment]
Delta Touch, with the official release of GZDoom v4.6.0.

**Comment by Tormentor667** [comment]
Seems to me like a Delta Touch rendering issue then, as I can't reproduce it myself as well. Do you think you can hint the developers to this issue? And please always make sure to share coordinates (idmypos = true) so it's easier for us to find specific spots :)
