### ISSUE TITLE
HUD - Reserve ammo widget: Scale vertically to amount of currently-usable ammo types?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#707]
Would it be feasible to scale the new "reserve ammo" widget to account for however many currently-usable ammo types the player has? Minimum height, for example, would constitute exactly one ammo type (for example, when you just have 9mm ammo/weapons and nothing else). This will also pave the way for any custom ammo that a mod for BOA may make use of, as its scaling nature can accomodate both vanilla and custom ammo.

**Comment by AFADoomer** [comment]
It already does, just with a minimum size cap.

By default, it matches the height of the bottom right hud blocks that are already on the screen.  If additional ammo is added that pushes the height larger, it will grow larger to fit them all (do 'give all', then 'give astrostein' to see all normal ammo, plus Astrostein-specific ammo drawn).

**Comment by Shockwave508** [comment]
A fair point. Feel free to close this if need be.
