### ISSUE TITLE
[3.2] Inventory widget for HUD: Show more than one item at a time when scrolling through usable items.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#708]
Currently, BOA can only display one inventory item at a time, regardless of however many the player is carrying. Is it possible to show at least three at a time as long as the player is scrolling through his usable items?

**Comment by Tormentor667** [comment]
It would be nice to have but it isn't high priority. If @AFADoomer is interested in coming up with something, we can implement it.

**Comment by AFADoomer** [comment]
Yeah, low priority for 3.1.  I have some mostly working code,  but it needs polish and I haven't had time to do it.

**Comment by Tormentor667** [comment]
@AFADoomer any news on that?

**Comment by AFADoomer** [comment]
Added in 6413899ca4b6a1d84c3fa0f4a410f0adb4e499df.

**Comment by x3003** [comment]
Maybe someone can put a box around the selected item ? Now it's unclear which one is selected.

![Screenshot_BoA_20220115_145553](https://user-images.githubusercontent.com/77861029/149624349-54accb95-94c1-415a-bf10-6bbd4aa94599.png)

**Comment by Tormentor667** [comment]
Yeah, that would be a nice addition indeed.

**Comment by AFADoomer** [comment]
Added a box and some effects to make the currently selected item more evident in 1176d7668318a123b4647414cdefcb4418cc41f6.
