### ISSUE TITLE
HUD - Weapon widget: Only show grenades when the player has at least one.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#709]
It seems a bit awkward to have a grenade icon lying around on the weapon widget if the player has none whatsoever. Is it possible to make a "third" version of this window without grenades, if the player has none whatsoever, be it standard or Astrostein?

**Comment by AFADoomer** [comment]
Just committed this change.

**Comment by Shockwave508** [comment]
Can confirm it's working; safe to close.
