### ISSUE TITLE
The Blade of Agony itself: Show Cursed Souls as ammo instead of "key item"?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#711]
Given how the game's titular weapon uses Cursed Souls as "ammo", perhaps display it as such on the weapons widget, instead of being a "key item" in the upper-right corner?

**Comment by Tormentor667** [comment]
Yes, that's certainly a good point.

**Comment by AFADoomer** [comment]
While this works fine on the ammo display widget, the regular "current weapon" ammo displays on the hud and status bar aren't designed to show 4-digits of capacity; everything runs together.

Souls are also used for soul gates, not just as ammo, which is why I left them as non-useable inventory.

**Comment by MuadDib90** [comment]
And how about to let it display as non-useable inventory and from C3M5_A to have it display as ammo, because you already have the Blade? (Or have it displayed either way from this point...)

**Comment by AFADoomer** [comment]
How about we have the best of both worlds, and it shows up in both places? That way it's only on the ammo widget if it's in your inventory, and they will always be seen in the puzzle item area even if you don't have the sword.

See 661cecfda40dc0d0737d804e1bb98a0f9b910562.

**Comment by MuadDib90** [comment]
>How about we have the best of both worlds, and it shows up in both places?

Yes, that is what I meant.

**Comment by AFADoomer** [comment]
This should be complete now.  I added both tesla ammo and souls to the main status bar ammo count area; that was the last thing missing, I think.
