### ISSUE TITLE
C2M5_A - Stahlhimmel - moving train

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#714]
C2M5_A ...

While on the moving train, and outside, Things scroll. This area has sector type 46 - Wind south weak.
The effect is not weak at all. I suggest removing this sector type from this area. The wind is gale force ! Not a gook look IMO.

Also, somehow, Dirty Douglas fell from the train. To "retrieve" him, I had to walk back to the rear carriage of the train.
UPDATE ... I reproduced this. He can fall at line 4903. This line has the block monster flag. Would also adding the "block players" flag help ?

There needs to be a door or something at sector 1335. Player can got back and forth between sectors 1359 and 1377 and the train starts/stops. This is not wanted. Once the player reaches sector 1359, he should not be able to go back. Train has stopped.

**Comment by Tormentor667** [comment]
> There needs to be a door or something at sector 1335. Player can got back and forth between sectors 1359 and 1377 and the train starts/stops. This is not wanted. Once the player reaches sector 1359, he should not be able to go back. Train has stopped.

This has already been fixed in the current dev version.
