### ISSUE TITLE
HUD: Show timer for active "powerup" items/status effects.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#715]
Is it possible to show duration timers on the hud for the Totale Macht, Totale Gier, Adrenaline Kit, Bandages, and whatever else the player can make use of that involves duration timers?

**Comment by Shockwave508** [comment]
Similarly, is it possible to add timers for statuses like "Frozen" (from Winter Ubersoldat's grenades) and "Poisoned" (from Schabbs syringes/mutant attacks)?

**Comment by AFADoomer** [comment]
Mostly done in c05b24079eeb0072d504e5ea55e2109fadc8a8cf.

Poison damage doesn't work via inventory items, so will require separate handling.

**Comment by Tormentor667** [comment]
> Poison damage doesn't work via inventory items, so will require separate handling.

Should be done with this, isn't it? 0e67d6ea2b67f4c80c947c6cef92b35aed1fdcaa

**Comment by AFADoomer** [comment]
Yes, this should be able to be closed now.
