### ISSUE TITLE
guards too aggressive

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#719]
In c2m1 when trying to play mein leben, you can't even get out of the cell because the guards on the right, who are the **furthest** away from you, see you when you only stick your head out of the door opening. No problem with the guards on the left though. I know mein leben should be very hard, but the player should also still be able to play the game. And here it already ends within 5 seconds.

**Comment by AFADoomer** [comment]
I can't reproduce this...  All I did was wait for the light to flicker off, then crouched and walk around to the next hallway.  Also did it without crouching, but that's a little harder.

**Comment by Tormentor667** [comment]
Same here, you have to be very careful (as usual in this map), but it works.

**Comment by mgrinzPlayer** [comment]
![2021-05-30 10-59-38 mkv 1](https://user-images.githubusercontent.com/9157726/120100463-24d66f00-c141-11eb-8ddd-e3fc77006e80.gif)

Maybe change HINTTEXTC2M1A about blinking lights 🤷

**Comment by x3003** [comment]
You can get through when the light goes off again, but the strange thing is that the guards on the left (who are closest) don't see you when the light goes on and the ones on the right do. So for me, these guards are too aggressively programmed.
