### ISSUE TITLE
Incorrect player-sprite in mirror for no-weapon / weapon-held

### ISSUE THREAD

**Issue by Kroc** [Realm667/WolfenDoom#72]
![screenshot_doom_20161005_174707](https://cloud.githubusercontent.com/assets/142650/19124004/31622f82-8b29-11e6-862b-12cc1cc91217.png)

I assume this is either a limitation in gzdoom or just the need for an artist to create a crap-tonne of sprites for it. Note that this also applies when the player is not holding any weapon, such as at HQ.

**Comment by Ozymandias81** [comment]
Exactly, it needs a crap-tonne of sprite edits for each weapon. Who knows, maybe it could happen in the future but I really doubt.
