### ISSUE TITLE
C2M4: Sgt. Ascher and his troops display the "stealth-kill" crosshair when targeted with the Combat Knife.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#720]
With the Combat Knife equipped, Sgt. Ascher and his two troops display the "stealth-kill" crosshair when aimed at.
![Screenshot_2021-05-28-09-49-35-260_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120035873-e6b44080-bfc4-11eb-819a-6cdfaad8aa37.jpg)

**Comment by x3003** [comment]
Yes, that's quite weird.
