### ISSUE TITLE
C2M5_B: Starting/central hallway; tank cannona, flatbed truck, and rocket tailfins can be clipped through.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#722]
1) In the starting hallway, the tanks' cannons can be clipped through if the player jumps from underneath them.

2) Further down that same hallway, the top-half of the flatbed truck is non-corporeal, and can be clipped/shot through by all combatants.
![Screenshot_2021-05-28-10-43-17-438_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120036446-c33dc580-bfc5-11eb-9971-78aec067c1a4.jpg)

3) The test-fire rockets' tailfins can still be clipped through, despite recent fixes.
![Screenshot_2021-05-28-10-49-50-189_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120036513-dea8d080-bfc5-11eb-8abe-ecc527f93d41.jpg)

**Comment by Tormentor667** [comment]
Fixed'em all
