### ISSUE TITLE
INTERMAP/End of Episode: Mission summary displays four Eisenmann Files/Mayan Artifacts after finishing C1M0 and C2M0_B.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#723]
After completing Operation Astrostein, viewing the mission summary in the briefing room erroneously displays four Mayan Artifacts, despite having acquired all five beforehand.
![Screenshot_2021-05-28-13-55-11-707_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120036804-48c17580-bfc6-11eb-9deb-8698d222ec62.jpg)

**Comment by AFADoomer** [comment]
I can't reproduce this.  

All that I can think of is that the stats update call didn't fire for some reason when you turned one of the artifacts in to Gutenberg.

**Comment by Shockwave508** [comment]
After finishing my most-recent Episode 1 run, the same issue happens with the Eisenmann files.
![Screenshot_2021-05-31-09-36-46-968_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120209184-fe254080-c1f3-11eb-9d6b-efe169a32ef1.jpg)

**Comment by Ozymandias81** [comment]
Maybe related to Delta Touch?

**Comment by Talon1024** [comment]
No, I had the exact same problem

**Comment by AFADoomer** [comment]
Yeah, I still need to look into this more...  

"Changemap"-ing through each level and warping directly to the artifact and then turning them in gives me the correct results, so figuring this out will require some more investigation.

**Comment by Talon1024** [comment]
Here's a screenshot from after handing in one of the Eisenmann files:
![Screenshot_Doom_20210531_155625](https://user-images.githubusercontent.com/6550500/120236057-68a4a380-c229-11eb-966b-36b1db1acf2b.png)

**Comment by Talon1024** [comment]
I just completed a playthrough of Chapter 1, and I can confirm my commit fixes this issue.
