### ISSUE TITLE
[Delta-Touch] C2M6_B: Totale Macht objective doesn't register as finished, despite picking it up.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#726]
Secondary Totale Macht objective in C2M6_B does not register as finished, despite picking it up.

**Comment by x3003** [comment]
I had this issue once. That was because I already bought it and it can't register another one if you already have one.

**Comment by Talon1024** [comment]
I have no idea why this could be happening, other than the Totale Macht objective completion script "completing" the wrong objective.

Anyway, I checked the map and the ACS code on C2M6_B, and the Totale Macht objective completion script is set up to be triggered once the player crosses one of the linedefs surrounding the Totale Macht on the small crate, and does not have any checks for whether the player has a Totale Macht already or not.

**Comment by Talon1024** [comment]
Is it possible that you already accomplished the objective, and you expected to be able to "accomplish" it a second time?

**Comment by Shockwave508** [comment]
You're likely correct, as I had only moved close enough to the Totale Macht to pick it up, and didn't cross the linedef as you said.

**Comment by Tormentor667** [comment]
I think I made the line the trigger in case you have one Totale Macht already in your inventory and that you can only pick up one of them.

**Comment by MuadDib90** [comment]
> I think I made the line the trigger in case you have one Totale Macht already in your inventory and that you can only pick up one of them.

Actually it was Ozy on my issue report of this exact problem before releasing E3. :)

**Comment by Ozymandias81** [comment]
Guess still Delta Touch

**Comment by Tormentor667** [comment]
Found the issue and fixed it.
