### ISSUE TITLE
AI actor doesn't react

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#727]
With the latest git version on c2m4, when leaving the truck, there are some enemies coming at you. But here, Douglas doesn't react anymore and just stands there doing nothing.

![Screenshot_Doom_20210529_120243](https://user-images.githubusercontent.com/77861029/120066511-191e7600-c077-11eb-9791-eaf7cce7ded3.png)

**Comment by Tormentor667** [comment]
I remember he never reacted before actually.

**Comment by x3003** [comment]
In the release version he does react.

![Screenshot_BoA_20210529_130920](https://user-images.githubusercontent.com/77861029/120068077-28092680-c07f-11eb-8e7a-2ad1c085ea9f.png)

**Comment by Tormentor667** [comment]
Funny, I wasn't aware of this improvement :)

**Comment by x3003** [comment]
Yes, funny. After the mission he isn't even smoking anymore. Maybe he gave it up, because it was bad for his health ?!

![Screenshot_Doom_20210529_171301](https://user-images.githubusercontent.com/77861029/120120279-76f8ae00-c19c-11eb-86a8-369f380586ff.png)

**Comment by Tormentor667** [comment]
That's because there are two different actors - one static npc with only 1-direction (smoking and animations) and one with full 8-directions, which also can attack.

**Comment by x3003** [comment]
>one static npc with only 1-direction (smoking and animations) and one with full 8-directions, which also can attack

Yes, and both didn't work for me.

**Comment by Tormentor667** [comment]
The 1-direction will never attack, it has no AI but is only a static actor. The 8-directional one should attack though if it has before.
