### ISSUE TITLE
HUD: Directional damage indicators?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#730]
Would it be possible to code in a directional damage indicator that can surround the crosshair, allowing for a full 360-degrees of incoming damage reports without having to look at your mugshot to see where you're getting shot from?

**Comment by AFADoomer** [comment]
Possible, yes...  This is a style change, though, so I'll leave the call on this to Torm.

**Comment by Tormentor667** [comment]
If it is subtle and not distracting, and if AFA is willed to code it, I am okay.

**Comment by AFADoomer** [comment]
See 2ef2547317f54e53c14575add3a415be4ba76455.

**Comment by Shockwave508** [comment]
Tested it out by chucking a grenade at my feet, and it seems to have pinged the damage indicator script several-hundred times in one second, as my framerate sank into single-digits. Also seems like all damage registers at "maximum width", regardless of distance between the damage source and the player.
![Screenshot_2021-05-29-20-45-20-434_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120089348-ec8e4c80-c0be-11eb-93f6-09abf555f2b8.jpg)

**Comment by AFADoomer** [comment]
What was shooting you here?

**Comment by Shockwave508** [comment]
Nobody. I deliberately caught myself in the blast radius of my own grenade. If it's possible, track each damage "source" only once, and brighten the indicator as more damage is accumulated from that source.

**Comment by AFADoomer** [comment]
That's how it works.

The problem is that your grenade no longer exists, so there's no damaging actor to track...  Damage from grenades and mines currently gets tracked as a single "world" damager, and only updates when new damage occurs...  The problem here is that grenades also call Radius_Quake, so cause damage over time..  I'll need to adjust for that.

**Comment by Shockwave508** [comment]
Any status updates on the "Radius_Quake" issue?

**Comment by AFADoomer** [comment]
Try now: 64e126e83733e554f3adefe615520fb662160d6e

**Comment by Tormentor667** [comment]
Just tried it, very well done @AFADoomer , couldn't imagine it any better :)

**Comment by Shockwave508** [comment]
It's working great now; no framerate drops over here!
