### ISSUE TITLE
C2M6_B possible showstopper

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#732]
C2M6_B ...

I'm at sector 4945, but do not yet have the red key to open door sectors 4974 or 4969.
Player cannot proceed further ?

**Comment by AFADoomer** [comment]
Backtrack and find the key.  Have you explored the area at 5280, 5280 (sector 1160)?

**Comment by hawkwind3** [comment]
I cannot get there. I'm trapped at sector 4945. Water area with underwater mines.

________________________________

**Comment by hawkwind3** [comment]
Update ... found the red key at sector 1035.
My original post is indeed a bug. If the player is at sector 4962
and does not have the red key ... player is trapped ... game over.

________________________________

**Comment by AFADoomer** [comment]
And the door at sector 4860 isn't open?  What route did you take to get to the underwater mine area?

**Comment by AFADoomer** [comment]
This should be fixed as of 162198f914a6cd21af5b312b43501c9cd58dee1c.
