### ISSUE TITLE
[3.1] Preparing the release, what's new? (on June 9th, 2021)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#733]
Just to keep track of things, a release date and what we want to achieve for the 3.1 release.

**New Features**

- New Launcher (written from the ground)
- Addons (a total of 12, featuring score, gameplay and look changes)
- Ultra-Widescreen support (21:9)
- New damage and powerup screen indicators (grenade indicator, damage direction indicator, different damage flashing)
- Completely revamped fullscreen hud
- New additional boss battles and enemies
- Achievements system (total of 34, achievement board in the briefing room)
- Countless bugfixes, adjustments and improvements
- Performance improvements
- Replacement and improval of edgy and sensitive content
- Improvements to make the player-placed mines more useful
- Additional rotational sprites for 1-directional enemies
- Sprite improvements and hires additions for numerous sprites
- Includes latest stable GZDoom 4.6

What else did I miss?

**Comment by hawkwind3** [comment]
I have been informed that boa.exe has disabled toggle walk/run. if this is so, I consider this a bad move.
Player should be able to decide whether to walk or run. Having the shift key permanently pressed just does not "cut it".

**Comment by AFADoomer** [comment]
It was never supposed to work, and was a limitation of the old ACS sprint handling.  It's not going to change.

**Comment by Tormentor667** [comment]
What’s new as well for 3.1?

**Comment by Username-N00b-is-not-available** [comment]
Well, 3.1 will mostly be a bugfix update. Out of 560 commits after April 30 more than 150 contain the word 'fix'.
Are there any estimates on the release date..? What is important to finish ASAP, and what can be left for 3.2 or later? Most problems I noticed in my playthrough were not critical for example, I should probably make sublists of 'Important Issues' there...

**Comment by Tormentor667** [comment]
The plan is to release 3.1 next week, I‘d suggest friday. Is this okay for everyone? (especially regarding the remaining critical issues) @AFADoomer @Talon1024 @DoomJedi @Ozymandias81 @doomjuan @Username-N00b-is-not-available @MuadDib90

**Comment by MuadDib90** [comment]
@Tormentor667 
Fine with me. Doing some testing stuff on E3, when I can. All issues are in here #863 and @Username-N00b-is-not-available has already nicely sorted them out.

**Comment by AFADoomer** [comment]
I'm good with that timeline...

Can we tag "Critical" issues with a ❗ or something like it at the beginning of the title so that we can prioritize what gets fixed?

**Comment by Username-N00b-is-not-available** [comment]
We can also use the 3.1 milestone: https://github.com/Realm667/WolfenDoom/milestone/1

**Comment by Tormentor667** [comment]
> We can also use the 3.1 milestone: https://github.com/Realm667/WolfenDoom/milestone/1

Can existing issues moved there somehow? Other than that I'd go for the exclamation mark, so all issues are at one place.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Yes, they can (see Milestone at upper right panel). We can also use both methods simultaneously.

**Comment by Talon1024** [comment]
I'm working on a script which can merge multiple MD3 models together, in order to (hopefully) help with the debris-related performance issues and the perpetually-falling debris issue.

**Comment by Ozymandias81** [comment]
Contains a couple of new eastereggs (Joy Division Album, a new tx from Nosferatu movies not used yet), new brightmaps for additional sprites, fixes for several sprites rotations. And regarding bmaps/fixes, I also guess friday is not feasible, maybe subsequent friday 2nd July? I am aware that there are also Euro 2020 quarter finals on that day too.

**Comment by mcphail** [comment]
What will be the target version of gzdoom for this one?

**Comment by Tormentor667** [comment]
> What will be the target version of gzdoom for this one?

Latest stable

**Comment by Tormentor667** [comment]
@Talon1024 @Ozymandias81 I am okay with releasing it one week later, maybe we need that time.

**Comment by x3003** [comment]
Is framedropping w/ better gfx cards still an issue ? For many ppl this is quite an issue.
It seems that the latest version of windows could have solved this issue (partially ?). Or else the latest version of amd software.
Also notice that when autosave kicks in, there's also a slowdown that ppl see as framedropping.
Could someone w/ a better card check for this ?

**Comment by Tormentor667** [comment]
Well, when the engine saves the game, the cpu is doing some work, this is an engine flaw, we can't change much about it.

**Comment by Ozymandias81** [comment]
Framedropping happens even on ultraoptimized engines such as Quakespasm for Quake when quicksaving/loading , so pretty sure this is unavoidable in any circumstances.

**Comment by Tormentor667** [comment]
I'm in vacation from 1st to 4th of June, so I'd release 3.1 on 5th of June, is this okay for you?

**Comment by Tormentor667** [comment]
I am in a short vacation until Sunday evening, so sorry for the current little activity from me. Maybe it’s a good idea to postpone the release until Friday.

**Comment by Username-N00b-is-not-available** [comment]
Until Friday, 11 June 2021? :-)
I think we should add performance improvements as a separate bullet point to the list.

**Comment by Ozymandias81** [comment]
Maybe let's postpone of one more week yes, 11 would be cool. I will have a vacation since 16th of July to 23rd.

**Comment by AFADoomer** [comment]
All dates are OK for me...

I'm on vacation today through part of next week, then my wife has surgery the next week, then I'm out again first week of August.  Will be able to work on BoA intermittently throughout.

**Comment by Tormentor667** [comment]
Enjoy your vacation all together and best wishes for the surgery of your wife @AFADoomer

**Comment by Tormentor667** [comment]
![Uploading 950F5D04-572A-45E9-B472-FDBC1D9F9B28.jpeg…]()

…and greetings from Austria :)

**Comment by MuadDib90** [comment]
I join the wishes @AFADoomer. :)

**Comment by Ozymandias81** [comment]
Change of trip plan for me, I will leave since 26th for 10 days mostly... Wish your wife all the best @AFADoomer :muscle:

**Comment by Tormentor667** [comment]
Getting back from vacation tomorrow evening and will do some work then. Do you think a mostly finished and bugfree release on Friday 9th of July is doable?

**Comment by Tormentor667** [comment]
Posted some news: https://boa.realm667.com/

**Comment by Talon1024** [comment]
It's out @mcphail @Alexander-Wilms 

GZDoom: [g4.6.0](https://github.com/coelckers/gzdoom/tag/g4.6.0)
BoA: [v3.1](https://github.com/Realm667/WolfenDoom/tag/3.1)

**Comment by Tormentor667** [comment]
Congratulations to everyone involved - 3.2 is released and in my opinion we all really did a great job on that improved version. It wasn't easy, but we made it. Thanks also to everyone testing the game, the betatesters have been doing an amazing job, and it wouldn't be as good as it is without you.

**Comment by MuadDib90** [comment]
>Congratulations to everyone involved - 3.2 is released 

You sure meant 3.1 😅
