### ISSUE TITLE
[HUD] Scuba Gear and Gasm Mask adds an "empty placeholder" left to the other indicators

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#734]
Gasmask and Scuba inactive:
![grafik](https://user-images.githubusercontent.com/10298439/120100072-112a0900-c13f-11eb-875d-23c1101a5612.png)

Scuba active:
![grafik](https://user-images.githubusercontent.com/10298439/120100077-18e9ad80-c13f-11eb-8fde-8c7616890b49.png)

Gasmask active:
![grafik](https://user-images.githubusercontent.com/10298439/120100089-21da7f00-c13f-11eb-855e-4da5c1fa4f3d.png)

I think the system adds space but has no graphic so the other powerups just move right.

**Comment by AFADoomer** [comment]
This should be fixed after 3800c2ba91c8abb776294f88dc0c799f06f8b68d.

**Comment by Tormentor667** [comment]
Confirmed, it works
