### ISSUE TITLE
INTERMAP/Chapter 1: Before you set off on C1M4, Lt. Laz Rojas doesn't mention that you'll be getting a Sten MKII.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#735]
Before C2M5_A, Lt. Laz Rojas mentions that you'll be getting a Kar98K on that mission, and is thus unavailable for purchase.

Conversely, before C1M4, he doesn't mention that you'll be given a Sten MKII at the start of the mission, though it likewise is unavailable for purchase for that mission only.

![Screenshot_2021-05-30-08-22-00-406_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120105809-293e6000-c120-11eb-9ee0-eeabcca03431.jpg)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 @Ozymandias81 If you think that the dialogue change is necessary, I can write the necessary text in English. Should I?

**Comment by Tormentor667** [comment]
I think changing the text here makes sense. Is it necessary to adjust code as well?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Not the code, but rather the DIALOGUE lump in INTERMAP.
OK, I'll take care of both now.

**Comment by Tormentor667** [comment]
Thanks a lot! Glad that you are back and active again btw :)
