### ISSUE TITLE
Inventory Name Tags: Scuba Gear and Totale Macht have incorrect name tags.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#736]
With inventory item names enabled in GZDoom's settings, the Scuba Gear is erroneously referred to as "ScubaGearGiver" when it's selected. Likewise, the Totale Macht is incorrectly referred to as a "Berserk Pack".
![Screenshot_2021-05-30-08-24-49-398_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120106009-f779c900-c120-11eb-9c96-54d1886cfd13.jpg)

**Comment by AFADoomer** [comment]
Should be resolved after 40a49fe2082f4d3685f0ff33ea87d504a0f087d5.  Translations required for most of the new tags.

**Comment by Tormentor667** [comment]
Updated german.
