### ISSUE TITLE
First-person weapon sprites: Change appearance based on current outfit/disguise?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#737]
I couldn't help but notice that most, if not all first-person weapon sprites use Doomguy's gloves, despite B.J. not wearing any gloves himself, in any of his outfits and disguises. Is it possible to have additional weapon sprite sets on a per-outfit basis, which alter the appearance of his first-person arms?

These would involve the Default, Scuba Gear, Prisoner (C2M1), Space Suit (C2M0_B), Scientist (C2M5_B), Camp, and SS uniforms/disguises.

**Comment by Tormentor667** [comment]
The amount of work involved here would be ridiculous in comparison to the gain that we have with the “consistency” effect so this is a definite “no” :)
