### ISSUE TITLE
[Delta-Touch] C1M6: The majority of arched doorways can be clipped through.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#739]
Barring a few exceptions, the tan-colored archways in C1M6 can be clipped through on their sides, either by walking or jumping into them.
![Screenshot_2021-05-31-09-29-28-414_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120209507-62e09b00-c1f4-11eb-81bb-03ed1b9d51db.jpg)
![Screenshot_2021-05-31-09-29-34-801_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120209526-67a54f00-c1f4-11eb-8db5-5621c93d830e.jpg)
![Screenshot_2021-05-31-09-29-51-597_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120209539-6bd16c80-c1f4-11eb-9fed-b5b8c59d6568.jpg)
![Screenshot_2021-05-31-09-29-55-498_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120209552-6ffd8a00-c1f4-11eb-847d-896e2c3d5ac0.jpg)

**Comment by Tormentor667** [comment]
Strange that this doesn't occur with GZDoom but only with Delta Touch

**Comment by Ozymandias81** [comment]
@Shockwave508 please ALWAYS consider to add a "[Delta-Touch] " line when writing an issue, you have to keep in mind that BoA has been developed for GZDoom and to work on pcs.

**Comment by Ozymandias81** [comment]
And just checked withr ecent build of gzdoom, testing from udbuilder. Noticed a minor misalignment, but nothing regarding such clipping since all doors have proper slopes settings and sectors.

**Comment by Tormentor667** [comment]
@Shockwave508 in this special case, can you report the bug to the Delta Touch developers? It's definitely an engine issue.

**Comment by Talon1024** [comment]
This is a problem with the OpenGL ES renderer. Here are screenshots from the same location in C1M6, in both the OpenGL and OepnGL ES renderers, respectively:
![Screenshot_Doom_20210623_034514](https://user-images.githubusercontent.com/6550500/123057326-c74ae080-d3d5-11eb-82cd-3a25aad53042.png)
![Screenshot_Doom_20210623_034422](https://user-images.githubusercontent.com/6550500/123057341-ca45d100-d3d5-11eb-8002-a9774635071e.png)
