### ISSUE TITLE
Language: Detailed health/armor/ammo pickup messages?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#740]
Is it possible to add slightly-more-descriptive pickup messages for health/armor/ammo, denoting how many units of each picked up per pickup? And also by highlighting the parenthesized text below with appropriate colors depending on pickup type?

Examples:

"Picked up a small medkit. (+10 Health)"
"Picked up a medium medkit. (+20 Health)"
"Picked up a field kit. (+40 Health)"
"Picked up a Stahlheim. (+5 Armor)"
"Picked up a heavy combat vest! (200 Armor)"
"Picked up some shotgun shells. (+4 Shells)"

**Comment by DoomJedi** [comment]
With all text related stuff we have to take into account the number of languages we need to translate it into, not sure all original translators still onboard following this.

**Comment by Tormentor667** [comment]
The additions might be a good idea, I have to agree with that. Yes, @DoomJedi , this also means work for the translators - but it's optional in the translations if you ask me - it doesn't break anything.

**Comment by MuadDib90** [comment]
I am still on board, Captain... the deck is already clean. Where do we sailin'? 

Maybe it could be possible to "guess" where to add proper coloring to other languages, if you want me to try...

**Comment by Tormentor667** [comment]
If we add some information in brackets, it's easy to guess where it is, it just needs to be translated as well :)

**Comment by Tormentor667** [comment]
Added detailed pickup messages for everything that made sense to me, let me know if that works (implemented in english and german, other translations need to adjust)

Commit: 273d2cfd0eecc9d57f05f48dee7be1e340a86aae

**Comment by Username-N00b-is-not-available** [comment]
Oh, I remember writing a post in this issue yesterday, but it did not get sent for some reason...
What about making an addon for these messages, providing it as an optional behaviour?
