### ISSUE TITLE
C2M6_C possible switch issue ?

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#741]
C2M6_C ...

Have used the switch at line 19519 and now at the switch at line 18970,
which opens/closes door sector 5553. Seems impossible time wise to get to sector 5555.
It also appears that CapsLock=toggle cl_run does not work with the version of gzdoom used.
Even so, with the Shift key "permanently" depressed, I still cannot get to sector 5555.
Am I missing something ?

**Comment by hawkwind3** [comment]
Just thought I'd add that I'm using BOA.exe dated 4.4.21.

**Comment by Tormentor667** [comment]
I made the ticker 1 second longer but when "running/sprinting", it should be doable without any problems. There is no "perma-run" in Blade of Agony btw.
