### ISSUE TITLE
Reports from russian guy

### ISSUE THREAD

**Issue by DoomJedi** [Realm667/WolfenDoom#742]
Reports from russian guy (with screens).
https://www.dropbox.com/s/8sg9v3hxbdfrla9/%D0%9E%D1%88%D0%B8%D0%B1%D0%BE%D1%87%D0%BD%D0%BE%20%D1%81%D1%87%D0%B8%D1%82%D0%B0%D1%82%D1%8C.pdf?dl=0

I think I'll need Noob help to translate those...unless I just use google translate

**Comment by DoomJedi** [comment]
There are tons of reports here ,what will we do? Tried to use google translate (which you can use as well), just too long of a process for me, gave up.

**Comment by Ozymandias81** [comment]
Some of them looks pretty outdated, they need to be translated though.

**Comment by Username-N00b-is-not-available** [comment]
I think I have time to do this now...

**Comment by Tormentor667** [comment]
@Username-N00b-is-not-available thanks a lot for translating, do you think you can combine the screenshots with your translations somehow? Otherwise fixing this is a terrible work - switching from the translation to the dropbox, back and so on...

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Here it is: [report_translated.pdf](https://github.com/Realm667/WolfenDoom/files/6598004/report_translated.pdf)

**Comment by Tormentor667** [comment]
Thanks alot @Username-N00b-is-not-available , time to rage-fix :)
