### ISSUE TITLE
C2M3: House 5's windows can still be attacked/meleed from outside.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#743]
Issue #637 hasn't been solved completely. Enemies may no longer detect and shoot the player from inside the House 5 building, but the player can still attack them from outside, through the windows. You can even take the shovel to them by standing up close to that house's windows and swinging for the fences.

**Comment by Ozymandias81** [comment]
Rockets can still kill them and that's normal, also even the fact that enemies gets alerted since that comes from the 3d sectors aroudn the house. Concerning the melee attacks, let's see if I can solve it.

**Comment by Ozymandias81** [comment]
Okay solved, windows with such setup must have block hitscans too, will apply to many maps when possible. Thank @Shockwave508
