### ISSUE TITLE
C2M5_A: Open polygon seam on the scrolling terrain.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#746]
While making your way to the front of the train, the west portion of the scrolling background terrain has an open, triangle-shaped seam.
![Screenshot_2021-06-01-13-58-14-321_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120383558-a4ec0880-c2ea-11eb-9119-eabd48d22c60.jpg)

**Comment by Ozymandias81** [comment]
This is sadly an issue between builder and engine that sometimes left open holes on ertain maps. And this one, within c1m4 and c2m3, where one of them. Thanks for let me know, I'll try to fix it.
