### ISSUE TITLE
HUD Feature Suggestion: "Incoming Grenade"/"Gestapo Detection" indicator?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#747]
Building off the foundation of the new directional damage indicator, how feasible would it be to implement a directional "incoming grenade" indicator for standard grenades, SS Übersoldat's shrapnel grenades, and so on? The arrow portion can be rotated a full 360-degrees, and can be repeatedly iterated for however many explosives the Nazis are chucking your way. As for the icon itself, perhaps make several icons, depending on the type of grenade?

**Comment by AFADoomer** [comment]
Yeah, easy enough to add.  

I'm in the process of reworking the damage indicators and the screen shader to use a common back-end array that tracks each individual damage that a player receives (mostly to eliminate duplicate code and so that damages of different types will blend the damage overlay colors instead of just using the last damage color).

Grenade tracking would be a similar implementation.

**Comment by Shockwave508** [comment]
A thought occured to me; is there a possibility of adding detection indicators in a similar manner, regarding the Gestapo in the stealth missions?

**Comment by AFADoomer** [comment]
Grenade indicators implemented in dd796d2ac07da7a20de39504d77e804f05a535d9.  Looking for feedback.

I'm not sure about the Gestapo one...  Is that really necessary?

**Comment by Shockwave508** [comment]
The former is performing beautifully! I will note that the player's own grenades, if thrown too close to himself by accident, don't show the indicator until it's too late to react.

The latter, however, can be safely ignored.

**Comment by AFADoomer** [comment]
Yeah, I intentionally have it not show the player's grenade until at least a second has passed, so you don't immediately see an indicator when you throw one...  That can be tweaked.

**Comment by Tormentor667** [comment]
For me it works perfect as it is now.

**Comment by AFADoomer** [comment]
Yes.  If we want it off by default, that's easy enough to change in CVARINFO.

**Comment by Tormentor667** [comment]
Having it on by default is just right :)
