### ISSUE TITLE
dog doesn't attack

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#748]
In c2m1 with the git version, this dog doesn't attack when you get to him. He's running from left to right and back all the time.
Only when you cross the line (where he's running) he attacks, but when you step back a few steps, he goes into left/right mode again.

![Screenshot_Doom_20210601_234123](https://user-images.githubusercontent.com/77861029/120394373-9a099600-c333-11eb-82a4-602e7be28b5a.png)

**Comment by Tormentor667** [comment]
I guess there is a monster blocking line

**Comment by x3003** [comment]
Yes, he won't go over the line when you run back.
