### ISSUE TITLE
Sprite improvements from Captain J

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#753]
Today I got a pm from Captain J (at ZDoom.org) who sent me a set of sprite improvements, some of them fixes issues with existing sprites, some of them improve what we have and some of them are hd replacements.

I checked the whole set and I have to say it's very solid and good looking work. I think that stuff should be implemented for our 3.1 release. What do you guys think?

Complete ZIP file (updated with instructions, approved by @DoomJedi, already some stuff added by me)
[CaptainJ-Sprites.zip](https://github.com/Realm667/WolfenDoom/files/6594036/CaptainJ-Sprites.zip)

Remaining Spritesheets, could you take care of these @Ozymandias81 ?
[RemainingSpritesheets.zip](https://github.com/Realm667/WolfenDoom/files/6602958/RemainingSpritesheets.zip)

- [x] Additional perspective baggages
- [x] Improved Nemesis sprites
- [x] Crouching nazi rotations
- [x] Additional Dogfood sprites
- [x] Highres Astrostein ceiling turret with rotations
- [x] New enemy (Elite Ubersoldat with GasMask)
- [x] Improved Bat death sprites
- [x] Barrels replacement (tnt, goodie)
- [x] Improved Ubersoldier sprites (with better hands)

Text info from Captain J:

> Graphics:
> BARLC0 and HDFakeItemBarrels- Explosive containers are now bigger.
> (Taken from Jaguar version of Wolf3D by ID Software and Blood by Monolith)
> 
> HDBurningBarrel - Burning Barrels is now bigger and retrospective.
> (Existing Burning Barrel sprites Mixed with Jaguar version of Wolf3D by ID Software)
> 
> SKLTA0 and SKLTB0 - Dry bone piles are now bigger and various.
> (Taken from Might and Magic VI: The Mandate of Heaven by New World Computing)
> 
> NewPhotonLauncher - Replacement sprite for Astrostein level's Photon Launcher. It's shoulder-mounted, not handle-handled!
> (Edited the sprite from Doom version of Astrostein by Laz Rojas)
> 
> HDAstroGrenade, HDAstroArmorShard, HDAstroTurret, HDAstroCan, HDPhotonAmmo and HDTeslaArmor - Astrostein sprites are now bigger and extra-retrospective.
> (Edited the sprite from Jaguar version of Astrostein by Laz Rojas)
> 
> BONEA0 and GOREA0 - Bloody bones are now bigger.
> (Taken from HD Wolf3D sprites project by Ringman)
> 
> HDKleinNebelwerfer - Klein Nebelwerfer is now bigger.
> (Existing Nebelwerfer ammo and Chaingun sprite Mixed with some sprites from Necrodome by Raven Software)
> 
> HDTeslaCannon - Tesla Cannon is now bigger.
> (Existing Tesla Cannon sprite Mixed with M60 from Powerslave by Lobotomy Software)
> 
> UbersoldatenWithBetterHands - Ubersoldat variations with actual visible and normal looking arms.
> HDAlphaMutants - Found some big mutants and they rehashed the existing small ones' sprites. So i've decided to make them unique. Tried not to make them similar to Ubermutant.
> GermanSoftDrinks, HDFlameCanister, mmmpretzels and ThisShouldReplaceTaco - Historically accurate food pickups. Tacos and Hamburgers were just too much hilarious.
> HDFlameCanister, HDFlakJacket, HDScubaGear, HDCandleStand, HDTeslaAmmo - Certain items are now bigger.
> HDBatDeath - Bats' death animations are now in HD.
> HDLoper and HDMiniSub - Certain enemies are now bigger.
> VariousDogFood - I will be honest here, i think every single dog food pickup sprites should be the same, or just keep the key design(bones). Also they're bigger now.
> UBMUJ0 - Ubermutant's 2nd death frame improved. His face looked kinda like a baby.
> HDGunTurret and CrouchedKrautsRotations - Stationary enemies now have all 8 rotations. You can recolor the rest of variations, i hope.
> EliteUberWithGasMask - Elite Ubersoldat with extra detail and weaponry. I honestly hated my version especially the helmet part. It was too silly.
> ExtraPerspectiveBaggages - Never liked them bags floating up in the air.
> ExtraRetrospectiveNemesis - Nemesis with perspective, and retrospective improvement. Tried to make him fit up to 128x128 limitation and it kinda worked!
> NUKGA0 - A proper floating rotten body.
> HailShitler - Ain't that a fitting form for the fearless leader?
> (Edited some sprites from your project)
> 
> Some issues i've found:
> - 2nd, 8th rotation of Gestapo and every single Scientist variation have severely bent neck.
> - 2nd death frame of Mission Pack Ghost sprite is way too blurry and definitely can see it's been photoshopped.

**Comment by DoomJedi** [comment]
>2nd death frame of Mission Pack Ghost sprite is way too blurry and definitely can see it's been photoshopped.
It was not, it's my manual work for WolfTC for Doomsday originally, yes it's an old work of mine, but it's manual.
And I don't use photoshop at all.

**Comment by Tormentor667** [comment]
Do you think you can improve that?

**Comment by DoomJedi** [comment]
First I want to say - I admire CaptainJ spritework for many years now, he also always supported me and my work.
I have no issues with him personally, and sure not as a spriter.

BUT. I have to ask CaptainJ (with full respect to him and again - admiration for his work and his ever support of my spriting, as a pal to a pal) - why did he woke up just now, after I made 5 years of work for this, after mod's release, to replace my work (by his undoubtedly superior work, no question there)?
He followed mods development for years, yet it didn't come to mind he can make better art for it than myself?

It's not the person (love and respect the guy), it's not the work (which is great and superior), but the timing. The timing annoys and frustrates me to be honest. With all do respect (and there is much respect).

I also already made the alternate nazi foods and had effort doing it just recently, which he overwrites by his work. Which even is not superior in this particular case.

**Comment by Tormentor667** [comment]
I think we managed to solve the discussion. I updated the ZIP with the remaining things we can and will add now.

**Comment by DoomJedi** [comment]
Indeed this issue was solved and I want to thank CaptainJ for his ever great spritework

**Comment by Ozymandias81** [comment]
I would have prefer to add them by myself, but I'll recheck the whole work and see what needs to be done. Please leave it to me now.

**Comment by Tormentor667** [comment]
Sorry, I just wanted to support you with this stuff a bit :(

**Comment by Ozymandias81** [comment]
No worries, it's just the way I work... Gonna check now the added stuff.

**Comment by Username-N00b-is-not-available** [comment]
Unrelated to Captain J's work, but about new sprites. Solid_Beard [announced on ZDoom forums](https://forum.zdoom.org/viewtopic.php?p=1191559#p1191559) that he intends to draw sprite variations for some of the soldiers for a mod/addon.
I think it would be technically possible to add them to baseline BoA (if they fit), and in a much easier and cleaner way than DECORATE monster randomizer mods do — just like it was done in this class (see the Variants state and ```PostBeginPlay``` override): https://github.com/Realm667/WolfenDoom/blob/55b6cf7ce458d9dc6e0b7ed25b80d30de41cf134/scripts/actors/enemies/zombies.zs#L1
What does the team think of this? Note that we already have 14k sprites (around half of all the files currently present in BoA), so maybe a little restructurization of the subfolders could be in order.

**Comment by Tormentor667** [comment]
I like that actually, brings some more variety to the mod and if it is doable, I am all in :)

**Comment by Ozymandias81** [comment]
Added all sprites, 126 brightmaps still needs to be included and I already have an idea for the new boss. I just need the name though, any suggestions? Attacks will be bullets, mortars and zyklon mortars, that's why I also added zyklon colored variants for shoulder attacks

**Comment by Username-N00b-is-not-available** [comment]
Captain J's machinegun turret only seems to shoot its center barrel ingame, are all others decorative?

**Comment by Tormentor667** [comment]
Well, if you or @Ozymandias81 are willed to change that, I am definitely okay with it. By the way, other than that, is this issue closed?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 No, not closed yet, @Ozymandias81 wanted to add [brightmaps](https://github.com/Realm667/WolfenDoom/issues/753#issuecomment-856152695).
A bit later I'll see what could be done with the MGTurret.

**Comment by Ozymandias81** [comment]
I'll see if I can correct myself those sprites, if necessary, because I need them done in order to work then for bmaps after.

**Comment by Tormentor667** [comment]
@Ozymandias81 are we done here?

**Comment by Ozymandias81** [comment]
With these yes :)
