### ISSUE TITLE
[3.1] [INTERMAP] Problems with NPC dialogues after C1 and C2 secret maps

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#754]
In previous builds, Gutenburg and Ascher would comment on the destruction of the Eisenmann facility upon finishing C1M0. This doesn't appear to be the case as of now.

**Comment by Tormentor667** [comment]
Maybe this has something to do with @Talon1024 's recent changes.

**Comment by Username-N00b-is-not-available** [comment]
Seems true for Gutenberg, but Ascher displays the correct message ("pre-C1M6", there is no separate message after C1M0 for Ascher):
<details><summary>Text</summary>\cCSir, that was a tough mission, and you were outstanding out in the field! If we keep scoring wins like this, we'll have the \cRNazis\cC on the run, and it'll be game over for them.\n\n\cCBy the way, have you heard the latest? Rumor has it the \cRNazis\cC are searching for the \cFSpear of Destiny\cC now. They must be getting desperate. Whatever. Good luck on your next mission.
</details>

By the way, in the final supermutant lab on C1M0 the sharks float above the purple liquid, not swim in it, but this could be a problem of my installation.

**Comment by Username-N00b-is-not-available** [comment]
This is an important issue. Gutenberg's dialogue is for some reason broken currently.

**Comment by Tormentor667** [comment]
> This is an important issue. Some INTERMAP dialogues (Gutenberg, Rojas) are for some reason broken currently when it comes to secret missions, both in C1 and C2.

Critical yes, but is it just what @Shockwave508 mentioned or is it more? Maybe @Talon1024 can take a closer look at it, he did most of the dialogue settings in the not so long past.

**Comment by Username-N00b-is-not-available** [comment]
The RETURN script ```Return_INTERMAP``` always reset the ```special_dialogue``` variable to zero (in line 209). I moved this to the part of Miller's dialogue which starts non-secret missions (script 101, line somewhere around 1513).
