### ISSUE TITLE
C1M3: Enigma machine model can be clipped through.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#755]
In C1M3, the Enigma machine's model can be clipped through, unlike other table-bound objects.
![Screenshot_2021-06-03-10-09-35-720_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120704101-c8928880-c47b-11eb-9e44-989421c0edc3.jpg)
![Screenshot_2021-06-03-10-09-40-996_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120704113-cd573c80-c47b-11eb-960f-df5c2460d757.jpg)

**Comment by Talon1024** [comment]
That's actually the Feld Hell machine (Feldfernschreiber), not the Enigma machine.

**Comment by Tormentor667** [comment]
But that one has proper dimensions:

![grafik](https://user-images.githubusercontent.com/10298439/120710129-0fa16d80-c4be-11eb-91a9-6d817d7763b3.png)
