### ISSUE TITLE
C1M3: Primary objective "Reach the Flak Tower" completes upon opening the Supply Chest.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#756]
For some reason, opening the Supply Chest will "complete" the Flak Tower objective, despite the player being nowhere near that zone at that time.

**Comment by Tormentor667** [comment]
I can confirm the issue, can reproduce it but it doesn't make sense, so it has to be a code issue @AFADoomer @Talon1024 . 

The chest is assigned to complete objective index 4 (2nd secondary) which is the chest objective but it also completes index 1 (2nd primary)

![grafik](https://user-images.githubusercontent.com/10298439/120709852-ade10380-c4bd-11eb-8b3c-a12b0f3d5de1.png)
