### ISSUE TITLE
Player's footsteps come from rear channels

### ISSUE THREAD

**Issue by mrmatteastwood** [Realm667/WolfenDoom#758]
**Steps to Reproduce:**
1. Launch BoA in 5.1 or 7.1 surround
2. Launch Episode 1, Level 1
3. Walk around outside the HQ

**Current Results:**
The player's footsteps play from rear channels, making it seem like there's somebody following on the player's heels.

**Expected Results:**
Footstep sounds should play from the front channels.

**Comment by AFADoomer** [comment]
I don't think that this is something we can control...  but I'll look into it.

**Comment by mrmatteastwood** [comment]
Yeah, I was wondering if perhaps this had something to do with the engine and/or OpenAL. I remember the same issue on the Brutal DOOM mod, where I "solved" it by disabling footstep sounds in the mod options. Perhaps there's a kind of delay on those sounds that doesn't manifest in stereo, but does in surround? Just spitballing, I honestly don't know.

Side note, BoA is fricking brilliant. I've been aware of it for a few years and patiently waiting for the full version, and now it's here, it's everything I dreamed it would be and more. You guys rock.

**Comment by Talon1024** [comment]
Do all the other sounds play at the correct position? If so, this may be something we can fix. If not, it's probably an OpenAL bug.

**Comment by mrmatteastwood** [comment]
Positioning is correct in all other cases, yeah.

**Comment by Tormentor667** [comment]
@Talon1024 do you have an idea what could be done here from the mod's perspective? Otherwise I'd close this.

**Comment by Talon1024** [comment]
The footstep code appears to play the sound at the player's position, so I don't know what can be done.

**Comment by Tormentor667** [comment]
Let's close this for now, I consider it to be very minor.

**Comment by AFADoomer** [comment]
Agreed.  I have no idea how to fix it, anyway, since the sound plays literally from the player...  Might be able to fiddle with the attenuation, but no idea beyond that.
