### ISSUE TITLE
Table7 (ID 19145) creates a "floating meal"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#759]
![grafik](https://user-images.githubusercontent.com/10298439/120886287-75404780-c5ed-11eb-87b2-2c8507e1c2ad.png)
I think the problem is that these champagne glasses interfer with the meal size

**Comment by Ozymandias81** [comment]
This happen because probably table has been scaled, or the meal actor has been changed. It used to work fine with decorate version.

**Comment by Tormentor667** [comment]
Just checked it, it is not scaled in game. I have no idea what happened to the meal actor in general though.

**Comment by Username-N00b-is-not-available** [comment]
```Table7``` has DoomEdNum 19145, not ```Table1```. The issue also happens to ```Table12```.
@Ozymandias81 Again I don't think that it is a Decorate/ZScript conversion problem, since for some reason GZDoom spawns +NOGRAVITY actors (with A_SpawnItemEx) 8 units higher than the Z parameter specified. Why does it happen and what for??? Does anybody know..?

**Comment by Shockwave508** [comment]
The floating meals are now submerged meals, to the point that the player is literally unable to pick them up, even if he is crouched and standing directly atop them.
![Screenshot_2021-06-11-11-00-55-586_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/121742644-b8a32600-cac5-11eb-809e-c988ff625152.jpg)

**Comment by Username-N00b-is-not-available** [comment]
@Shockwave508 Which GZDoom version were you playing with? Does not happen for me on the latest devbuild:
![Screenshot_BoA_20210612_105938](https://user-images.githubusercontent.com/59409713/121769623-5140b100-cb6d-11eb-9797-cc03e2587edd.png)

**Comment by Username-N00b-is-not-available** [comment]
No, it actually does happen, I can also see that on C1M5... Let's change the spawnheight to 27 again...

**Comment by Tormentor667** [comment]
I think the issue appears with tables being scaled. The table gets higher but the spawn height stays static.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 The tables in C1M5 that display this effect are not scaled, their scale is 1 over X and 1 over Y.
By the way the old version had set the spawnheight to 1.15*scaley, yet there still was a problem (which you reported when opened this issue).

**Comment by Tormentor667** [comment]
Okay, this was just an idea but good if that's not the problem.

**Comment by Tormentor667** [comment]
...such a simple issue, how blind can I be.
