### ISSUE TITLE
Radios continue playing music after being destroyed

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#760]
![grafik](https://user-images.githubusercontent.com/10298439/120887660-7f197900-c5f4-11eb-8a04-3a7cfbb46ff5.png)

**Comment by Ozymandias81** [comment]
This was working previously, but also I remember that those radios were not breakable, or they had external ambientsound. In that case maybe someone changed target tag with something else. Will check.

**Comment by Ozymandias81** [comment]
I would like to know from which map that shot comes @Tormentor667

**Comment by Tormentor667** [comment]
Pretty sure it is C3M3_A, but I got this shot from the russian player who tested the mod (@Username-N00b-is-not-available translated this)

**Comment by Ozymandias81** [comment]
The actor is destroyable, but no one gave to it remove thing special for the external sound.

![C3M3_A at 2021 06 06 18-54-59 948  R3782](https://user-images.githubusercontent.com/11136108/120933085-d30d8600-c6f8-11eb-9f63-b1d4cbbca146.jpg)
