### ISSUE TITLE
Externalize hard-coded data for 'using' wall textures from scripts to a data/config file and generalize implementation

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#762]
As mentioned by @Username-N00b-is-not-available in #519

**Comment by Username-N00b-is-not-available** [comment]
As indicated by the comment history, this was @AFADoomer's idea.

**Comment by AFADoomer** [comment]
Yeah, this is for me.  Just have to add a data file that defines sounds for textures, and a function to do the value lookups at runtime.

**Comment by Tormentor667** [comment]
So after your recent commit, this is done, right @AFADoomer ?

**Comment by AFADoomer** [comment]
Yes.  

I generalized the setup so that if we want to, we can easily assign a unique "use fail" sound to any texture.  The only thing set up right now is the locked doors, basically matching 3.0 behavior.
