### ISSUE TITLE
Explosions and sneakable enemies

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#763]
Sneakable patrolling enemies killed by player's deployable mine explosion do not increase player kill count (to test just enter ```notarget``` on C2M6_B, warp to (5000, 2700), ```give deployablemine``` and place the mine on path of one of the enemies).
Might be already fixed (copied from https://github.com/Realm667/WolfenDoom/issues/384#issuecomment-829908921).

**Comment by AFADoomer** [comment]
Should already be fixed.
