### ISSUE TITLE
Automap and C3M0_B ending sequence

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#764]
If there is a way to forcefully disable the automap right after the screen fades out for the C3M0_B ending sequence, it should probably be added, since you can end up with this (the game will not listen to automap controls in this menu, so it would not be possible to watch the cutscene):

![image](https://user-images.githubusercontent.com/59409713/116683071-c68a6500-a9b7-11eb-824c-30b01d5ea136.png)

**Comment by AFADoomer** [comment]
No good way, no.  There's no ZScript call to turn on/off the automap.  

I could experiment with forcing the dmflags2 CVar value to not allow automap when the finale kicks off, but that's a hack.

**Comment by Username-N00b-is-not-available** [comment]
It seems to work instantly when using the console in plain Doom II, so a switch-on/off in two consecutive lines (triggered right before the menu shows up) could be enough. Definitely a hack, but considering how little the flag does https://github.com/coelckers/gzdoom/blob/4bcea0ab783c667940008a5cab6910b7a826f08c/src/am_map.cpp#L3347, it hopefully won't break the engine down.
***
Hmmm, what about also using the ```1<<18``` dmflags2 for _all_ cutscenes instead of the black graphic we currently have?

**Comment by AFADoomer** [comment]
I tried...  The CVar values that control dmflags can only be changed from specific menu actions, and can't be set elsewhere, so this route won't work.

**Comment by Username-N00b-is-not-available** [comment]
Maybe ```F_StartIntermission``` with an empty intermission could help? This line seems interesting: https://github.com/coelckers/gzdoom/blob/e963010eea58de0c6d3b1c4a03e7271e5449c0cd/src/intermission/intermission.cpp#L1012
It is also exposed to ZScript: https://github.com/coelckers/gzdoom/blob/a172513535486e870baf2d0328d11bbba32042f7/wadsrc/static/zscript/doombase.zs#L464

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Well, it is even more of a hack than the dmflags2 solution would have been, and has an unfortunate side effect (you'll see it for yourself), but here is a seemingly working example for Doom II: [removemap.zip](https://github.com/Realm667/WolfenDoom/files/6609798/removemap.zip)

**Comment by AFADoomer** [comment]
Use -1 as the time count for it to last a single tic instead of a second, and pass an empty string as the background image...  This might actually work if we're resetting the music for finale screens anyway.
