### ISSUE TITLE
Commander Keen actor problems

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#765]
- [x] CKSmirky can teleport into a wall and get stuck.

![Screenshot_BoA_20210430_170016](https://user-images.githubusercontent.com/59409713/116705872-b41f2400-a9d5-11eb-914e-c974620f5d48.png)

- [x] The slug poison flatsprite does not align to slopes.

![Screenshot_BoA_20210430_170416](https://user-images.githubusercontent.com/59409713/116706359-3ad40100-a9d6-11eb-9ec6-66691f5c7c2c.png)

Both could have been fixed already.

**Comment by AFADoomer** [comment]
I can't easily fix the first one.  He gets un-stuck by himself, so not game-breaking, just weird.

**Comment by AFADoomer** [comment]
Slime sloping fixed in d2edab386bda40992e36137d207e12ca7b80ba8c.
