### ISSUE TITLE
The end of C1M0 (Operation: Eisenmann) may be too hard

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#767]
For some people, the end of Operation: Eisenmann (C1M0) at the train station is too hard. Furthermore, there are Allied soldiers waiting there, and doing **nothing**, even though the station is surrounded by Nazis.

I watched a playthrough of that mission on a recent livestream ([VOD here](https://www.twitch.tv/videos/1045660248?t=03h20m00s)). There isn't much health or ammo to be found along the path to the train station, and some players don't want to clear it beforehand.

IMO, it would make more sense storywise (and make the mission easier) to have the Allied soldiers at the train station fighting the Nazis in the area, or to remove all of the Nazi troops from the train station area.

**Comment by Tormentor667** [comment]
Well, having a final battle at the train station sounds fine for me, but we could make them fight the allied forces as well, having a little combat situation here.

**Comment by x3003** [comment]
Well, the battle at the station isn't that bad. I normally clear that out first before going into the building. Think the main problem here, is that he ran out of ammo.

**Comment by Tormentor667** [comment]
I will add some more ammo to the route leading to the trainstation.
