### ISSUE TITLE
[C3M2] Objective inconsistency

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#770]
I took out the radar tower before getting the advice from Ascher to do so.
At this point I wondered what to do next, since I had achieved the primary objective up to this point.
So I then retrieved the tank and brought it back to Ascher. This allowed progression.
What I'm getting at here is this ... should not the retrieval of the tank be a primary objective at the start
of the map ?

**Comment by Tormentor667** [comment]
The player doesn't know about the tank until he finds it, so this can't be made an objective.
