### ISSUE TITLE
Language/Detailed Pickup Messages: Differentiate between 9mm and Rifle "Clips"?

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#771]
I noticed while testing the new pickup messages, that ammo for 9mm weapons (such as the Luger, Walther, MP40, and UMG) and rifles (as in, Gewehr 43 and Kar98k) are both referred to as "clips", regardless of how much ammo is picked up.

Perhaps denote 9mm ammo as "9mm Bullets" instead of "Clips".
And denote rifle ammo as "Rifle Bullets" instead of "Clips".

**Comment by Username-N00b-is-not-available** [comment]
An hour ago @Talon1024 changed it to 'bullets' for 9mm ammo and to 'rounds' for 7.92mm ammo. Thank you!
