### ISSUE TITLE
Achievements implementation

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#773]
@AFADoomer I started a new issue as a base line for this.
If you want to share your thoughts about this, we can help you or maybe suggest something? :)

**Comment by MuadDib90** [comment]
@AFADoomer I saw you (maybe?) plan to implement some achievement icons? Should/can I try to think something up?

**Comment by Tormentor667** [comment]
Did you check the other achievement issue? I will take care of these but feel free to support here :)

**Comment by MuadDib90** [comment]
Oops, I kinda overlooked that one... sorry. Heading there. :)
