### ISSUE TITLE
[3.2] HUD Messages: Obiturary Message issues.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#778]
1) If you are killed by means of any projectile, that projectile's name will be printed above the relevant death obituary. Known prints are Bullet, Fire, and None (for explosions).
![Screenshot_2021-06-07-11-14-14-468_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/121081174-f5a7a980-c7a1-11eb-9883-64d5370d4dd5.jpg)

2) If you repeatedly die from the same enemy that killed you previously, their obituary won't appear, despite having killed you plenty of times.

**Comment by AFADoomer** [comment]
Oops, number 1 is debug code that I forgot to remove.

**Comment by Username-N00b-is-not-available** [comment]
Possibly related to 2: if you warp to a level (```map c1m2```) and quickly type ```iddqd``` after it loads, the 'Inglorious Mode On' message does not appear on screen, it is only written into console.

**Comment by AFADoomer** [comment]
@Username-N00b-is-not-available - Can you confirm if this (iddqd message) is still a problem?  I tweaked the message log to always intercept messages, so I think this is fixed.

I don't know what the obituary problem is.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer

> I tweaked the message log to always intercept messages, so I think this is fixed.

Have you committed the changes? As of https://github.com/Realm667/WolfenDoom/commit/be5ce615c9753e0e85561bb5e6dea4ca41788fb4 the iddqd issue still happens for me.

**Comment by AFADoomer** [comment]
This should all be resolved after 878d1c5bbceb5fabeb3ead75e35d798817d226aa.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Both issues (the repeated obituary one and the iddqd one) still happen for me on latest commits (built 30min ago), sadly.

**Comment by AFADoomer** [comment]
Then I have no clue why it's happening and am not going to fix it.

**Comment by Username-N00b-is-not-available** [comment]
OK :-D
