### ISSUE TITLE
[C3M0_B] Ryan mission

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#781]
C3M0_B ...

- [ ] a) Monster cannot exit the "closet" at sector 725. 
- [x] b) Can partly walk through destroyed tanks at x 5014, y -4625 and x 6448, y -4694.
- [ ] c) Some areas of ceiling of sectors 396 and 1360 render at a different brightness level for some reason.
- [x] d) Telephone way too low at x 7675, y -4114.

**Comment by Tormentor667** [comment]
> Some areas of ceiling of sectors 396 and 1360 render at a different brightness level for some reason.

I don't see that, the sectors have all the brightness level 128.

**Comment by Tormentor667** [comment]
> Telephone way too low at x 7675, y -4114.

This has already been fixed. Do you play the latest version?

**Comment by x3003** [comment]
a) Yes, this happens.

![Screenshot_Doom_20210619_133538](https://user-images.githubusercontent.com/77861029/122641539-3f7b8280-d106-11eb-9da2-fac5ba62b5b7.png)

**Comment by Tormentor667** [comment]
I think I've fixed it, can you try? @x3003

**Comment by Tormentor667** [comment]
> Some areas of ceiling of sectors 396 and 1360 render at a different brightness level for some reason.

Regarding this, there are randomly flickering lights near these sectors for the thunderstorm effect. These are randomly activated and deactivated (as the outside storm). It shouldn't interfer but maybe thats the issue. Other than that I can't see an issue. If it still remains, please share a screenshot.
