### ISSUE TITLE
[3.2] The legacy of DECORATE

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#785]
From the depths of the GitHub server HDDs...
...emerges the resurrected DECORATE issue.

When the code conversion was suggested in #470, a few very valid points were raised by the team members regarding further improvements of the translated code, i. e. rewriting DECORATE hacks that could be implemented much easier and cleaner in ZScript. This means _only_ the ones that could be replaced while retaining the already-existing behaviour: if a feature could only be done in GZDoom by dirty means, it would be silly to remove it just for the code to become 'cleaner'.
I seriously do not know how many of such messy code portions we currently have. If @Ozymandias81, @AFADoomer and @Talon1024 view the cleanup as necessary, this issue can serve as the headquarters for the rewriting initiative. I do not think I could participate myself as actively as it was with #470, but if we manage to implement a plan of work, I'll try to help.

<details><summary>Class diagrams</summary>

As a starting point, here are some 'class diagrams' of everything ZScript in BoA (the tree was gathered yesterday), maybe they could be of some help while recording the progress, or at least building a picture of what is currently going on in those 100k lines of code.
[CSV of all classes](https://github.com/Realm667/WolfenDoom/files/6616971/classes.zip)
[.png with all classes (warning: 10MB)](https://github.com/Realm667/WolfenDoom/files/6616913/graph.zip)
All descendants of ```Base```:
![graph_base](https://user-images.githubusercontent.com/59409713/121194517-797f9580-c877-11eb-997f-4b8e00f01d8e.png)
</details>

Ah, by the way: we still have ```version "3.7.2"``` in the ZScript file.

Edit (10 Jun 2021): list of files in /scripts/decorate that have already been inspected and de-hacked (pun intended)
---
/critters

- [ ] bird.zs
- [ ] farm.zs
- [ ] pollen.zs
- [ ] rats.zs
- [ ] swarm.zs

/hazards

- [ ] barrels.zs
- [ ] electricity.zs
- [ ] fallingrock.zs
- [ ] gasflask.zs
- [ ] mine.zs
- [ ] traps.zs

/items

- [ ] armor.zs
- [ ] astrostein.zs
- [ ] health.zs
- [ ] keys.zs
- [ ] mission.zs
- [ ] powerups.zs
- [ ] treasure.zs

/misc

- [ ] civilians.zs
- [ ] ckeen.zs
- [ ] cutscenes.zs
- [ ] droplets.zs
- [ ] eastereggs.zs
- [ ] exclamation.zs
- [ ] nashgore.zs
- [ ] player.zs
- [ ] teleporter.zs

/models

- [ ] base.zs
- [ ] furniture.zs
- [ ] mapobjects.zs
- [ ] mission.zs
- [ ] obstacles.zs
- [ ] scenery.zs
- [ ] special.zs
- [ ] statues.zs
- [ ] vehicles.zs

/monsters

- [ ] animals.zs
- [ ] astrostein.zs
- [ ] bosses.zs
- [ ] mechas.zs
- [ ] mutants.zs
- [ ] nazis.zs
- [ ] npcs.zs
- [ ] occult.zs
- [ ] panzers.zs
- [ ] prisoner.zs
- [ ] robots.zs
- [ ] russians.zs
- [ ] shared.zs
- [ ] stealth.zs
- [ ] zombies.zs

/props

- [ ] astrostein.zs
- [ ] bath.zs
- [ ] bureau.zs
- [ ] camp.zs
- [ ] castle.zs
- [ ] debris.zs
- [ ] egypt.zs
- [ ] flags.zs
- [ ] furniture.zs
- [ ] gore.zs
- [ ] industrial.zs
- [ ] kitchen.zs
- [ ] labs.zs
- [ ] lights.zs
- [ ] shops.zs
- [ ] street.zs
- [ ] tech.zs
- [ ] trees.zs
- [ ] underwater.zs
- [ ] vehicles.zs
- [ ] walldecs.zs
- [ ] zyklon.zs

/sfx

- [ ] clouds.zs
- [ ] creepyrift.zs
- [ ] explosion.zs
- [ ] fireworks.zs
- [ ] flare.zs
- [ ] fog.zs
- [ ] glass.zs
- [ ] lightning.zs
- [ ] rings.zs
- [ ] skyboxtracer.zs
- [ ] swirl.zs
- [ ] terrainsplashes.zs
- [ ] vollight.zs
- [ ] waterlits.zs

/weapons

- [ ] ammo.zs
- [ ] astrostein.zs
- [ ] browning.zs
- [ ] bullets.zs
- [ ] fakeid.zs
- [ ] firebrand.zs
- [ ] flamer.zs
- [ ] g43.zs
- [ ] granate.zs
- [ ] kar98k.zs
- [ ] kicks.zs
- [ ] knife.zs
- [ ] luger.zs
- [ ] mp40.zs
- [ ] nebelwerfer.zs
- [ ] p38.zs
- [ ] panzerschreck.zs
- [ ] shotgun.zs
- [ ] shovel.zs
- [ ] stenmk2.zs
- [ ] tesla.zs
- [ ] truckgun.zs
- [ ] umg43.zs

**Comment by AFADoomer** [comment]
A lot of the actor's will need minimal work; mostly consolidation into the correct file and some formatting cleanup.

Anything that uses complex Spawn state actions to set initial behavior, convoluted jump statements, or inventory-token-based checks probably should be cleaned up.

**Comment by Username-N00b-is-not-available** [comment]
Yeah, I forgot about the formatting, too, a lot of it was lost in the process of conversion... Let's not remember how :-)
Definitely agree on the initializing and the jumps, where many copy-pasted lines can be combined into a single anonymous function.
As for the inventory checks, most of them seem to be present [on weapons](https://github.com/Realm667/WolfenDoom/search?q=a_jumpifinventory), so hopefullly this would not be too much work.
***
By the way, @AFADoomer, what do you think about reducing the total class amount and simplifying the inheritance tree by merging similar **decorative** actors into one, ```CivilianZombie```-style? If we use arg0/arg1/... instead of a custom ```user_variant``` field, we can avoid editing the maps to convert the actors, because [thing arguments can be assigned to DoomEdNums right from MAPINFO](https://zdoom.org/wiki/MAPINFO/Editor_number_definition). Even in the Base subtree from the 'class diagram' I can already see HelmetlessMarineXX and MarineXX classes, and the crows (which differ only by their spawn flags IIRC) that could benefit from this. Information on possible variants then would be put into GZDB tooltips, of course.
I also had thoughts about the same for **enemies** alongside with decorative actors, though it could be a really bad idea.

**Comment by AFADoomer** [comment]
Yeah, that's the other main thing to look for.  There are a lot weird inheritances and new actors with minor changes that can be consolidated. 

The reason for using a user variable was to allow setting a variant while still allowing. A special to be set on the actor...  but that could be a trade-off.

**Comment by Ozymandias81** [comment]
Some inheritances were made with the old shadows method in mind, and to also exclude some certain actors from thinkers (NOINTERACTION ones) plus instead others to be slightly active (on CUTSCEN# maps). As of now though there should be also a "Fade" state that can be triggered via custom fields which needs to be removed, there was a plan for that to be used in game for the end sequence, where dead bodies should have "fade" away and then the cutscene continue. Thus there are also some peculiar inheritance to look onto models for example, atm a couple of them seems to [behavior differently](https://github.com/Realm667/WolfenDoom/issues/774) from past times and also even meals over tables too

**Comment by Username-N00b-is-not-available** [comment]
Damn, I'm no sniper.

**Comment by Tormentor667** [comment]
I wonder: Is this something that still needs to be taken care of or not? And how much work is involved and how much outcome do we get from investing the effort? Sorry for asking so dumb, but I am simply not used to the code-department of our game.

**Comment by Tormentor667** [comment]
No feedback so I guess we can close this for now.
