### ISSUE TITLE
Minor issue when typing ENDGAME from console

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#786]
Not sure if this may be relevant, but this happens when you type endgame from console.

![Screenshot_BoA_20210608_153440](https://user-images.githubusercontent.com/11136108/121234116-a6da3c80-c893-11eb-8896-a3b2a6a31720.png)

**Comment by AFADoomer** [comment]
I can't reproduce this.

The only thing that I can think of is that somehow your player object was destroyed before the shader event handler stopped running, but I have no idea how that could happen.

**Comment by Ozymandias81** [comment]
Later I will try to describe how to reproduce this, just spent the whole morning trying to add some salt on minds through Doomworld.

**Comment by Ozymandias81** [comment]
Okay so steps to reproduce this issue: build the pk3 with build.bat, rename it as ipk3, drop it on most recent build of gzdoom, once in game during Titlemap screen make sure you have all PPShaders enabled, type "endgame" from console and the issue occurs.
![Screenshot_BoA_20210609_211739](https://user-images.githubusercontent.com/11136108/121415938-8af49a80-c968-11eb-9aea-384adb6a4cb5.png)

**Comment by Ozymandias81** [comment]
Thought it was that. These meh null pointers XD
