### ISSUE TITLE
BJ can't die....

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#787]
... during the training mission. Even when handling the panzerschreck wrong and stepping on multiple mines, he still doesn't die and stays on 1% health. Question is, why not ? He can die on every other mission.

**Comment by AFADoomer** [comment]
It's a training course so the player can learn controls and hazards, and is not not meant to punish the player for failing.

**Comment by x3003** [comment]
Even during a training mission you can die IRL. Especially w/ live ammo.

**Comment by AFADoomer** [comment]
How would you recommend that we handle it, then?  Right now if he dies, the whole level will restart.

**Comment by x3003** [comment]
Just let him die, like a normal mission. If the player saved, he/she can reload. Or else start again from scratch.

**Comment by Tormentor667** [comment]
We will keep the behavior as is, it doesn’t make sense to kill BJ in the training course.
