### ISSUE TITLE
lightswitch only turns off 1 light

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#788]
In the professors room, turning off lightswitch, only switches off 1 of the 2 lights. Done on purpose ?

![Screenshot_Doom_20210606_214710](https://user-images.githubusercontent.com/77861029/121259468-7228ae00-c8b0-11eb-9be8-6817b5204b89.png)

**Comment by Ozymandias81** [comment]
Well because that light gets activated separatedly via a script later... Will fix.

**Comment by x3003** [comment]
With the latest git version, somehow the right light is now off and can't be turned on.

![Screenshot_Doom_20210614_001033](https://user-images.githubusercontent.com/77861029/121823512-ec3ca680-cca5-11eb-905f-dc3dec3ac81d.png)

**Comment by Ozymandias81** [comment]
I still didn't check the map, will do when I can.

**Comment by Tormentor667** [comment]
The right light depends on the chapter you are playing. If you are in C2 and collect mayan artifacts, the light is on. It's off in C1 and C3 though as this part of the lab isn't active.
