### ISSUE TITLE
floating enemies

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#789]
When doing c2m5_a I came across this door which opened and closed all the time.
The answer was that there were guards on top floating in the air, so the door behaved like that.

![Screenshot_Doom_20210606_220454](https://user-images.githubusercontent.com/77861029/121259886-e9f6d880-c8b0-11eb-8929-ac9172576aa9.png)

![Screenshot_Doom_20210606_220757](https://user-images.githubusercontent.com/77861029/121259942-fda23f00-c8b0-11eb-8b94-9842d014f184.png)

![Screenshot_Doom_20210606_220810](https://user-images.githubusercontent.com/77861029/121259954-009d2f80-c8b1-11eb-837a-efd798e5e3ad.png)

**Comment by Ozymandias81** [comment]
This is weird and never happened before, might be a GZDoom bug... Which version did you use? C3 release or recent builds of GZDoom?

**Comment by x3003** [comment]
I use pre27 currently.

**Comment by Tormentor667** [comment]
I think we should block enemies from moving there, that'd be the easiest fix.

**Comment by Username-N00b-is-not-available** [comment]
I approve this happens in game, these three soldiers are pushed to the door:
![image](https://user-images.githubusercontent.com/59409713/121677357-6dd1e000-cabe-11eb-8a71-1aaaf7db91d7.png)
Added monster-blocking lines around them in https://github.com/Realm667/WolfenDoom/commit/891af927667609ad30e2764219f70fecacc7dc02.
