### ISSUE TITLE
[C2M5_A] Train Signal is static on train ride

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#790]
In c2m5_a when riding the train, you see this trainsignal (on the left) running along w/ the train (very funny).
But secondly, the signal is set to orange, which means caution/drive slow. This light should be green instead for full speed.

![Screenshot_Doom_20210606_220617](https://user-images.githubusercontent.com/77861029/121260162-44903480-c8b1-11eb-94f1-93a9dd6a1eee.png)

**Comment by Ozymandias81** [comment]
While signal lights are just set randomly and merely decorative, instead it wouldn't act that way, following the train... Which was your setup for rendering distance?

**Comment by x3003** [comment]
Distance is 8192.

**Comment by Tormentor667** [comment]
Maybe the stop signals are not moving with the "moving floor"? Can you check if the appropriate flag is set @Ozymandias81 ?

**Comment by Username-N00b-is-not-available** [comment]
CODSignal_Light has the following flags (combined from all parent classes):
<details>
		+DONTSPLASH
		+NOGRAVITY
		+SOLID
		+DONTTHRUST
		+NOBLOOD
		+NOBLOODDECALS
		+NODAMAGE
		+NOTAUTOAIMED
		+SHOOTABLE
		+MOVEWITHSECTOR
		+RELATIVETOFLOOR</details>
Tree4 which is also present on the map and does not follow the train has     +MOVEWITHSECTOR
	+RELATIVETOFLOOR
	+SOLID.
Removing NOGRAVITY or DONTTHRUST does not help matters...

**Comment by Username-N00b-is-not-available** [comment]
The inheritance chain is CODSignal_Light<-Obstacle3d<-Object3d<-ModelBase<-CullActorBase<-Actor.

**Comment by Ozymandias81** [comment]
This was surely working before decorate to zscript, and even after afaik... Should definitely belong to optimizations.

**Comment by AFADoomer** [comment]
Should be fixed after 93e96ad27acdebeb72571adb62506f6a4a7d3112.

**Comment by Username-N00b-is-not-available** [comment]
Yes, works nicely now. 
![Screenshot_BoA_20210619_191213](https://user-images.githubusercontent.com/59409713/122648522-4f10c080-d132-11eb-9b65-133d40e6bdf6.png)
![Screenshot_BoA_20210619_191217](https://user-images.githubusercontent.com/59409713/122648529-59cb5580-d132-11eb-8c59-e533cf5a3299.png)
Now for the yellow/green colour...

**Comment by AFADoomer** [comment]
The color's just set with an actor argument...  Look at it in GZDB.

**Comment by Ozymandias81** [comment]
Right, I recall adding switchable states like rocks for signals... and forgot it after the decorate-zscript migration.
