### ISSUE TITLE
Add some kind of "notification“ to the titlescreen regarding content

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#792]
Considering the content that we provide, could we add some kind of title screen addition that explains that

- a) this mod provides fictional content, not representing history 
- b) not representing any form of political ideologies of the modders 
- c) sensitive content that might not be suited for everyone 

After recent discussions this is definitely needed.

*Update*
Something like this maybe?

> **Blade of Agony is a fictional scenario based on the alternative narratives of the Wolfenstein game series by id software and Bethesda and the corresponding canon. It does not represent accurate history, our political stance or thinking of the development team. We reject any form of racial hatred, discrimination, (Neo-)Nazism, anti-Semitism or glorification of the Second World War.**

**Comment by Username-N00b-is-not-available** [comment]
We can build this on the IWADNotice class by the way, from the technical side. The player will have to push a button to get rid of the menu.

**Comment by DoomJedi** [comment]
There is still Sonder disclaimer on the net, you can copy stuff from it.

**Comment by Tormentor667** [comment]
> There is still Sonder disclaimer on the net, you can copy stuff from it.

Can you share that actually?

I just pasted this on the website by the way:

> Blade of Agony is a fictional scenario based on the alternative narratives of the Wolfenstein game series and the corresponding canon. It does not represent the political stance or the thinking of the development team. We reject any form of racial hatred, anti-Semitism or glorification of the Second World War.

**Comment by Tormentor667** [comment]
> We can build this on the IWADNotice class by the way, from the technical side. The player will have to push a button to get rid of the menu.

Yes, I definitely recommend that.

**Comment by Ozymandias81** [comment]
I guess this is the [disclaimer](https://www.moddb.com/mods/sonderkommando-revolt/news/project-status2) regarding Sonderkommando ?

**Comment by DoomJedi** [comment]
> 
> 
> I guess this is the [disclaimer](https://www.moddb.com/mods/sonderkommando-revolt/news/project-status2) regarding Sonderkommando ?

No, disclaimer is a screen that was added as starting screen on the actual game.

You can find it here:
http://deans-wolf-blog.blogspot.com/2014/09/operation-eisenfaust-origins-level-12.html

**Comment by Tormentor667** [comment]
Simply adding a notification that pops up at the first moment the main menue appears would be fine already. @AFADoomer are you capable of creating something appropriate maybe?

**Comment by AFADoomer** [comment]
Yes.  I was planning to have it pop up on engine load, just like (and immediatelyafter) the IWAD checker notification.

Center/middle, BigFont in gray, fade in and slow fade out over solid black background,  then title sequence starts.

**Comment by Ozymandias81** [comment]
So it should work like the saving icon right? But obviously bigger and in evidence, okay.

**Comment by AFADoomer** [comment]
I was planning on large text.

We could add your suggested icon to the PC-13 screen, too.

**Comment by Tormentor667** [comment]
Very good!

**Comment by Ozymandias81** [comment]
Perfect then :sunglasses:

**Comment by Ozymandias81** [comment]
So we have, by [reading this](http://sarahvideo.weebly.com/uploads/4/2/5/5/42553209/1358979_orig.gif):

Violence 4
Nudity 2
Sex 0
Language 2

Am I right?

**Comment by AFADoomer** [comment]
What about if, rather than using a real/defunct rating, we edit the PC-13 image to "PC-M" or "PC-18" and updating the text there slightly?

**Comment by Tormentor667** [comment]
Agreed! Still adding the text at the very top would be an additional thing we should add.

**Comment by AFADoomer** [comment]
Added the disclaimer message and updated ratings screen in 625b5c3e225ba72dff87af21bc341b1fe44caf82.

**Comment by Username-N00b-is-not-available** [comment]
There was a small typo 'as created by by id Software', I fixed it in the CSV.
@Tormentor667, are you satisfied with this version? Is it necessary to translate the text into all remaining languages as well?

**Comment by Tormentor667** [comment]
The disclaimer is almost perfect, I'd just make the text centert-aligned, not left-aligned, everything else is working as is.

**Comment by AFADoomer** [comment]
Yeah, I can do that with a user CVar, if no one has objections.

**Comment by AFADoomer** [comment]
This should be good after 4832dabc1104a28241c3fc6a9954adb3cd4072f8.

**Comment by Tormentor667** [comment]
Thank you!
