### ISSUE TITLE
Blade of Agony v3.0 taken down from ModDB until all issues are resolved

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#793]
After contacting various people, reading Twitter and Facebook comments and investigating a lot, I took down Blade of Agony v3.0 for now until the relevant issues are resolved. We need to take care of things that have been mentioned so far, as they are legit and need to be changed. We need to take these things serious and listen to the people out there, as various points are legit.

@DoomJedi made similar experiences while working on Sonder, and I don't want to have that kind of publicity for us now.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 It's still available, only the unrelated old files were taken down:
![image](https://user-images.githubusercontent.com/59409713/121324158-22ca9800-c919-11eb-9a53-315e7c430979.png)

**Comment by Tormentor667** [comment]
Replaced the ZIP content now with an info file. Is that better?

**Comment by Username-N00b-is-not-available** [comment]
Yes, thank you.

**Comment by Wolfenburger** [comment]
> @Tormentor667 It's still available, only the unrelated old files were taken down:
> ![image](https://user-images.githubusercontent.com/59409713/121324158-22ca9800-c919-11eb-9a53-315e7c430979.png)
> The file itself is 'archived', but you can download it.

Hey just wanted to say I understand why you locked the thread. I can genuinely. As for mentioned @madame-rachelle is a agenda pusher that came in only recently upon the contribution list. I seriously want to make that clear. That person came here pushing their personal beliefs with the disguise it was for the betterment of the community. @AFADoomer you don't call the shots either. Along with you, you're not helping by allowing people to push narratives. Consider that my final comment on the subject matter. Since this website does not contain private messages. Or messaging.

**Comment by AFADoomer** [comment]
Go away.

**Comment by Wolfenburger** [comment]
> Go away.

How about you? You literally notice this person invaded here with their agenda and you're offended that I stood up? It's wrong to stand up for one's belief? Ones ideals?

**Comment by Talon1024** [comment]
Stop acting like a spoiled child who was never scolded by their parents. We've already had numerous lengthy discussions on whether or not to remove the offensive content. We're removing the offensive content and THAT. IS. FINAL. And nothing you say will change our minds about it.

**Comment by Tormentor667** [comment]
> P.S. @Tormentor667 [here are instructions for how to block users from the organization and its repositories](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization).

Even though I do not like blocking people, this turned into a very non-constructive discussion so I did it.
