### ISSUE TITLE
Renaming "Randy Heit"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#794]
After the discussion on Doomworld and the very unfortunate circumstances, we need to rename the NPC. This thread here is for suggestions and ideas. It then can be taken care of quite quickly by search-and-replace on the Google Spreadsheet.

**Comment by Username-N00b-is-not-available** [comment]
I hope you'll forgive me for what I have done in the spreadsheet...

**Comment by Tormentor667** [comment]
I could actually live with it, but I guess we need a less "egoistic" name here. :) Suggestions?

- Roger Herman
- Robert Hunter
- Ronald Harris
- Raymond Hill

**Comment by Tormentor667** [comment]
> I hope you'll forgive me for what I have done in the spreadsheet... (see line 1709)

Search&Replace with "Daniel Gimmer" maybe wasn't that smart as we can't search&replace that anymore without also changing dev comments and other information related to me. Do you think you can change Randi's name for now to "Roger Herman"?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 There was a block of messages of the drunk engineer himself, and a certain line in Lt. BigDave's dialogue, and that's all mentions we had in the spreadsheet. I already manually changed these to 'Hunting' anyway.

**Comment by Tormentor667** [comment]
Thank you!

**Comment by Tormentor667** [comment]
Still reading comments over at Doomworld and I simply can't believe that this whole transphoby is a topic. Really. I never meant to discriminate someone regarding his sexual orientation. I have good friends who are homosexual and I love to hang around with them, I have people around me from any kind of nation and I love the variety and the gain that I have from their experiences.

I would never ever discrimate people with different origins or orientations. This is so far away from me and I get so much negative feedback now through all this. Why should I discriminate Marisa overall? For what reason? She is such an important person for the community and without her, without ZDoom there would be no mods from my side. What benefit would I have to discriminate her through Blade of Agony?

This is so crazy...

**Comment by DoomJedi** [comment]
Call the NPC "DefinetelyNotMarisa".

**Comment by Ozymandias81** [comment]
I have suggested on FB chat to use [Haggis McMutton](https://monkeyisland.fandom.com/wiki/Haggis_McMutton), since it do looks somehow like him and we may adapt the humour from him too.

**Comment by Ozymandias81** [comment]
Ahaha this is for the good then, I always loved that character from MI3, specially in italian language (he is scottish, but in italian language he has a curious sardinian sound ahaha). AYò GUYBRUSH!
