### ISSUE TITLE
guns already activated

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#800]
In c1m5, the 2 guns at the square are already activated before the call from douglas comes to protect the nebelwerfer. Is this by design ? The nebelwerfer self isn't activated yet.

![Screenshot_Doom_20210610_212242](https://user-images.githubusercontent.com/77861029/121584997-5e0cba00-ca32-11eb-867a-b2e8098e6e7e.png)

**Comment by x3003** [comment]
Yes, the player can fire them.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Well, why would they be deactivated before the fight? If the machine guns were 'broken', it's not like some Kraut would come and repair them right after you mop up the central square. It does not affect balance, too, as enemies won't approach from that side before the large invasion attempt. @Tormentor667, what do you think?

**Comment by x3003** [comment]
No, but you can't use the neberwerfer for now, which is only activated when the real battle starts. I thought these were all together activated by the same script.

**Comment by Username-N00b-is-not-available** [comment]
> you can't use the neberwerfer for now
@x3003 Can the player shoot the Nebelwerfer at all? I thought it was just a decoration, a goal to defend.

**Comment by Tormentor667** [comment]
> @x3003 Can the player shoot the Nebelwerfer at all? I thought it was just a decoration, a goal to defend.

Exactly :D I can't tell if that has been changed though. In any case: I have no problem that the machine guns can already be used, this is not an advantage during the map in general so who cares.

**Comment by x3003** [comment]
>@x3003 Can the player shoot the Nebelwerfer at all? I thought it was just a decoration, a goal to defend.

Yes, you can. But only if Douglas tells you, you have 30 seconds to get to the square.
