### ISSUE TITLE
Achievements: Attaining too many in a single run will cause a VM Abort.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#801]
Getting too many achievements in a single playthrough will cause a VM Abort if you meet the criteria for one more, stating that the "user info descriptor is too big". The only solution to the problem for now is to wipe the "boa_achievementrecord" CVAR and start a new playthrough, deliberately avoiding any and all achievement opportunites, just to keep the game playable.

**Comment by Username-N00b-is-not-available** [comment]
I also noticed this earlier today but thought it was related to cheating. CVAR strings have a limit of 256 symbols, so the data probably needs to be saved in a more compact format — or across multiple CVARs.

**Comment by Shockwave508** [comment]
I second the "multiple CVAR" approach. Keep the encryption, but have an individual CVAR for each current and future achievements. There's a reason that mods like SWWM GZ spread things out like this.

**Comment by AFADoomer** [comment]
I'm not adding 30-some unique cvars....  I'll split across a couple of them.

**Comment by AFADoomer** [comment]
Should be fixed after 2ba8caaa9ba75fb59011f07dce251c15ae05fde0.

**Comment by Shockwave508** [comment]
Can confirm that the issue is solved. Safe to close.
