### ISSUE TITLE
Too many changes?

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#803]
At some point, we have to draw a line with regards to how much content we change based on feedback from those who voice their displeasure because they were insulted by the game's content. I don't want to be the next Wolfenburger, but I think we've already done a lot for those who have come out, and I get the feeling that this is the point wherein we'll become complete doormats to the SJWs if we just refuse to say no.

Like, it could get to the point someone asks us to remove a particular thing and we just do so on their command because "it offended them". Because, when we do things like this, it feeds the SJW trolls and makes them even hungrier for "justice" and "political correctness", to the point where they get fat on our subservience.

We may even end up receiving complaints from many OTHER people because we whitewashed history and changed too much of the content to cowtow to the SJW trolls. I remember when EA released the trailer for Battlefield V (another WW2 game!), that a lot of people were complaining about the player being a woman in the army at a time women were not allowed to be in the army, Scottish people wielding Katanas, among other things, and that because of everything EA did with Battlefield V, the game was insulting to WW2 veterans, who many of these commenters were family members of if not WW2 veterans themselves.

When it comes to things like this, we should think about of the pros and cons of making each change, and the bottom line of WHY we're making these changes. I believe the bottom line is to avoid giving people the wrong impression of us, and some of the content we have, like the mission name for C3M1, and screenshots of @DoomJedi's Sonderkommando Revolt mod, were necessary to honor him for all the work he did for us, and I wouldn't like those to be changed.

The last time I was offended by something, I just decided I didn't need it in my life, and moved on, even though I was suffering on the inside, and the majority were not. IMO that's a more mature way of dealing with being offended.

**Comment by Dynamo128** [comment]
I thought the whole idea here was to avoid Tormentor being linked to possibly sensitive stuff given he lives in Germany. What do SJWs have to do with any of this now?

**Comment by Talon1024** [comment]
I'm sure @Tormentor667 knows the German laws regarding these sorts of things. By "SJWs" I mean the people complaining on Doomworld forums and other places.

**Comment by Dynamo128** [comment]
It's exactly because he is German that he is considering some of these changes, not because the doomworld people - or whoever else - forced him to.

**Comment by Tormentor667** [comment]
Thanks for your opinion on this @Talon1024 , I fully agree with this. But as it has been pointed out already: Most of the things are connected to the German law.

To be honest: I know a lot about the law but in some cases I am not 100% sure and that’s why I go for the secure way of „if something is questionable, change it“.

**Comment by DoomJedi** [comment]
So it's only for the law-related remarks?
It's not "those say it offends them, lets remove"?

I dont want you to get into legal trouble because of the mod, even in expense of my tributes etc. Nothing is worth legal trouble.
But as we in general very much agree with Talon on the direction of what he says - are you sure you dont overdo with changes for shitstorm calming reason?

**Comment by Tormentor667** [comment]
Exactly, it's not because of the offensive content for various single individuals, it's just to take care that we do not fear to interfer with german law.

**Comment by Phredreeke** [comment]
if that's the true reason I'd suggest you pass leadership onto someone who is not under german law

**Comment by ZedekThePlagueDoctor** [comment]
> if that's the true reason I'd suggest you pass leadership onto someone who is not under german law

Agreed, this would allow the mod to progress forward unrestricted.

**Comment by Dynamo128** [comment]
That doesn't magically erase his participation in it, so I have no idea what that's supposed to accomplish.

**Comment by Phredreeke** [comment]
Neither does going George Lucas on BoA.

**Comment by ZedekThePlagueDoctor** [comment]
Censoring BoA does not erase participation, it turns it into a watered down version of its former self. With leadership passed on, it can continue forward regardless of German legal issues.

**Comment by Tormentor667** [comment]
Passing on the leadership doesn't change the fact that I have been involved in this.

**Comment by Phredreeke** [comment]
Torm, I realise your concern but you can't put the genie back in the bottle. v3.0 is out there already, you can even find a mega link in a comment on your own moddb page, and the more you change it, the more you increase demand for the unaltered version (which has no disclaimers, actual holocaust footage and the misgendering of Marisa Heit)

**Comment by Tormentor667** [comment]
That's true, but I simply do not want to have this version officially hosted and supported.

**Comment by Ninlhil** [comment]
Out of curiosity, does there need to be a German version that replaces the Swastikas with the Wolfenstein symbol?

**Comment by Tormentor667** [comment]
No, swastikas are allowed to be shown in games since 2018 afaik

**Comment by Tormentor667** [comment]
As no more changes are planned, this can be closed.
