### ISSUE TITLE
"I Am Iron Man" achievement: Doesn't display name and criteria upon acquisition.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#807]
Upon handing over the final Eisenmann file, the game states that you "completed achievement 24", instead of showing the name and fulfilled criteria.
![Screenshot_2021-06-11-11-33-48-877_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/121742121-09664f00-cac5-11eb-8f9b-26de2d0e7765.jpg)

**Comment by AFADoomer** [comment]
Yes, as noted in the last achievements commit, I haven't added unique strings for all of the new ones yet.
