### ISSUE TITLE
[Delta Touch?] [C1M3] Atlantik Batterie entrance displays odd transparent rectangle after door has opened.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#808]
On the way to retrieve the first two explosive charges, approaching the Atlantik Batterie entrance from certain angles will cause a transparent rectangle to appear on the upper-edge of the door after it has opened. Thankfully has no bearing on gameplay.

![Screenshot_2021-06-10-10-00-08-506_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/121742940-2a7b6f80-cac6-11eb-868a-97b98b0c005b.jpg)

**Comment by Username-N00b-is-not-available** [comment]
Does not happen for me on PC.

**Comment by Tormentor667** [comment]
Can you create a few more screenshots from other angles and positions? I have no idea what that could be

**Comment by AFADoomer** [comment]
This is almost certainly a Delta Touch issue.
