### ISSUE TITLE
Damage screen intensity problems

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#813]
If a ```Sniper``` hits you with a bullet, the player's screen gets filled with thick red haze for around a second. This is fine.
On the other hand, if a ```WShotgunGuard``` hits you from point blank range, he can deal around 40 damage (compared to the sniper's 20 to 30), but the damage effect on screen will be very light. It looks like only one of the pellets takes part in the overlay calculations, or they all get overwritten by the last pellet.
IIRC original Doom counted the total damage dealt to player in one tic and used it for displaying the proper palette flash.

**Comment by AFADoomer** [comment]
Should be better after 753f205ee040973b6caf910fd017423aa776c64c.
