### ISSUE TITLE
Stamina recovery after death

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#814]
Well, this is cheat-related, but is quite inconvenient during testing and might uncover other problems, so I'm posting it nevertheless.
After the player dies and enters ```resurrect``` in the console, they do not recover stamina anymore. It can be spent using kicks, or sprint, in which case it will not be depleted (you can sprint indefinitely).

**Comment by AFADoomer** [comment]
This should be corrected in efab7679ec58e46f835114e96d4aa6116a002858.
