### ISSUE TITLE
Lifts too fast

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#815]
In c1m4, these lifts (elevators) are too fast now. Somehow this got changed recently. No human would like this kind of acceleration.

![Screenshot_Doom_20210612_220158](https://user-images.githubusercontent.com/77861029/121788308-93e5a600-cbcc-11eb-9e82-ce154a5cc429.png)

![Screenshot_Doom_20210612_220522](https://user-images.githubusercontent.com/77861029/121788312-9f38d180-cbcc-11eb-8b0a-a4f31e5e7c43.png)

**Comment by Username-N00b-is-not-available** [comment]
There is no acceleration implemented for lifts in the Doom engine, the floor velocity always changes _instantly_ (which would be obviously fatal in real life, no matter the maximal speed attained).
If we make the lifts slower, it will mean that the player will have to idle for more time, waiting until the lift arrives to floor, and this could be frustrating (depending on whether the player's ```patience``` is still > 0).
@Tormentor667, what do you think?

**Comment by Tormentor667** [comment]
I’d keep it as is.

**Comment by x3003** [comment]
>If we make the lifts slower, it will mean that the player will have to idle for more time,

Is this a problem then ? I've seen loads of vids and no one has probs w/ the old (slower) ones.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Do you think if lowering the speed by 25% could be enough?

**Comment by Tormentor667** [comment]
If you ask me that should work

**Comment by Wolfenburgernator** [comment]
> If you ask me that should work

@Tormentor667 I replied to your email. Please stop keeping my personal information public.

**Comment by Tormentor667** [comment]
I removed the issue mentioned, sorry for getting that wrong. Everything’s right now as is?

**Comment by Wolfenburgernator** [comment]
> I removed the issue mentioned, sorry for getting that wrong. Everything’s right now as is?

The thread name isn't showing up in this reference right? For my sanity I'd like this reference silently reworked and not public. Other than that thank you for taking it down. https://github.com/Realm667/WolfenDoom/commit/0c6f3e6c7390f8a5f658a8f894f72c9b64c546ef I just want to make

**Comment by x3003** [comment]
> Do you think if lowering the speed by 25% could be enough?

Yes.

**Comment by Tormentor667** [comment]
Just taking care
