### ISSUE TITLE
Ryan's cross

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#816]
When you point a gun at Ryan in c1m4, there's no cross shown.
But it's shown in c2m2.

![Screenshot_Doom_20210613_003241](https://user-images.githubusercontent.com/77861029/121790409-70782680-cbdf-11eb-9e5b-5b2f4b51b314.png)

![Screenshot_Doom_20210613_003338](https://user-images.githubusercontent.com/77861029/121790410-73731700-cbdf-11eb-9b5b-0648039d3fd5.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 This is because of reasons stated here: https://github.com/Realm667/WolfenDoom/issues/727#issuecomment-851246668
Is it a serious problem anyway?

**Comment by Tormentor667** [comment]
Well, we could simply make the crosshair appear on statist npcs in regular missions as well, is that doable @Talon1024 @Username-N00b-is-not-available @AFADoomer ?

**Comment by AFADoomer** [comment]
It already shows up on statist NPCs.  Any FRIENDLY, SHOOTABLE actor will show it, except that this Ryan is being set to non-shootable in ACS.

**Comment by AFADoomer** [comment]
Should be fixed in 9f65564fbb8e51235529f055e8b525f47958fa80.

**Comment by Username-N00b-is-not-available** [comment]
Yes, it is fixed now.
![Screenshot_BoA_20210615_215806](https://user-images.githubusercontent.com/59409713/122108384-cdb0e980-ce24-11eb-91da-a21171dfceb2.png)
I wonder if there are such 'cardboard' actors on other maps...
