### ISSUE TITLE
Can't shoot through the gate

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#818]
In c1m1, you can't shoot through this gate, so I couldn't shoot the dog.

![Screenshot_Doom_20210613_152136](https://user-images.githubusercontent.com/77861029/121809684-0ce10e00-cc5e-11eb-8353-ec0ab53a6a60.png)

**Comment by Tormentor667** [comment]
Taken care of in 483b320e7b4baa98bce96f0ccaa365e12681d1fc as well
