### ISSUE TITLE
dog is blocked

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#819]
In c1m1, this dog is still blocked and don't attack you when the gate is open.

![Screenshot_Doom_20210613_152702](https://user-images.githubusercontent.com/77861029/121809773-6e08e180-cc5e-11eb-80f2-7226da08d008.png)

**Comment by Tormentor667** [comment]
It's because dog can't traverse the 128 units low gap for the gate. Fixed it.
