### ISSUE TITLE
Alternate "Elsa" sprites

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#821]
Just got this from Captain J, I leave this for discussion if it is an option to use the new ones or the old improved ones.
![BoAElsaRedefined2](https://user-images.githubusercontent.com/10298439/121810147-f340c600-cc5f-11eb-813b-3e7f0573be84.PNG)

@Ozymandias81 by the way, did you add Captain J's sprite fixes for bosses yet?

**Comment by Username-N00b-is-not-available** [comment]
The style of these is honestly clashing with other sprites we have, especially regarding the detail of weapon and uniform.
Is the cap glued to her head, BTW?

**Comment by MuadDib90** [comment]
I must agree with N00b here. Don't make me wrong, but she looks like a steward with a gun, rather than a Nazi minion...

**Comment by DoomJedi** [comment]
I admire Captain J graphic skills, no doubt about that. Big fan here.

But I'm not objective for this topic as this is meant to replace my art (and because of the ever buzzing question in my head "why only now, Captain J? Why only now? I spent 5 years on this project and now you want to remove me from BoA? Do I deserve such treatment, when my only "pay" for this is ability to see others play my art?)

I do think that for consistency reason Captain J needs to redo all Bosses then, if you go with his (graphically superior) direction that has a very different graphic style.
I won't say more - not being objective side on the matter.
This is Torm's project and mod and I respect his choice to go with superior art or to keep the current one.

**Comment by mgrinzPlayer** [comment]
Maybe use it as add-on with "promoted by Realm667 team" text/description?
Since those are asset replacements:

> Well, yes, I think only "asset replacements" (models, textures, sounds, sprites, music) work without restarting the campaign. 
> - Tormentor667

Player can change those back and forth without issues.

**Comment by Tormentor667** [comment]
I put this here for discussion, it doesn’t mean that this is my opinion. Personally I’d stick to the one we already have.

**Comment by AFADoomer** [comment]
I also received a less modified variant from an anonymous source.

![ELSAA0](https://user-images.githubusercontent.com/16618820/121817141-2590fa00-cc45-11eb-8f5f-b8f0e3fdb53d.png)

[Alternate Elsa.zip](https://github.com/Realm667/WolfenDoom/files/6644382/Alternate.Elsa.zip)

**Comment by Tormentor667** [comment]
That could also work and still keep @DoomJedi 's original concept.

**Comment by DoomJedi** [comment]
This is much more loyal to the original, and can fit in case you're bothered by that...nipple feedbacks. In case you do.

...don't want to demotivate Captain J to keep making good new sprites for BoA....

**Comment by Tormentor667** [comment]
Well we don’t have to include all his work but maybe it would make sense to point him to our GitHub and two about things we need improvements for.

**Comment by Ozymandias81** [comment]
I think it is better to stay faithfull to Max style, so I would totally go for altElsa add.

**Comment by Phredreeke** [comment]
I would strongly suggest restoring the original Elsa sprites, as to avoid the appearance of giving in to everything DW asked for (the change can hardly be justified as required by German law)

**Comment by Ozymandias81** [comment]
I added that set of sprites and nothing else, what we decide belong to us first, then we also take in consideration feedbacks but not acting like robots, no worries. We are not giving everything. So we keep chast sprites for Elsa @Tormentor667 ?

**Comment by Ninlhil** [comment]
I'd say either use the new ones with the added bra, or keep the originals. I mean, the entire thing is a homage to "Ilsa; She Wolf of the SS", so moving too far away from that doesn't make sense.

**Comment by Ozymandias81** [comment]
We gonna use CJ sprites for a new female boss, just for the record. And we gonna use chast sprites for Elsa.

**Comment by Tormentor667** [comment]
CJ sprites for a new boss, Else alternate sprites with the bra

**Comment by Ozymandias81** [comment]
Yes I'm doing it.

**Comment by Ozymandias81** [comment]
Once I'll prepare the bmaps for the new boss, we still need fitting sounds for the actor (4 sounds total). Any clues? Same goes also for the new masked boss.

**Comment by Tormentor667** [comment]
For the female use the same as for Elsa. For the mask one I can prepare something fitting.

**Comment by Tormentor667** [comment]
As the enemies are added, we can safely close this now.
