### ISSUE TITLE
Can't get to the intermap

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#822]
When trying to end c1m1, talking to douglas I get an error and don't get to the intermap.

Error: Attempt to save pointer to unhandled type NativeStruct<font>

This work earlier in the day.

**Comment by AFADoomer** [comment]
What's the rest of the error?

**Comment by x3003** [comment]
That's it

![pointer](https://user-images.githubusercontent.com/77861029/121816872-65280800-cc7e-11eb-9fb3-99cf49195066.jpg)

**Comment by AFADoomer** [comment]
OK, fixed in 20603beda3ffed9b07f6bc5d0d1dd46c74f69a70.

**Comment by x3003** [comment]
This one seems fixed.
