### ISSUE TITLE
[3.2] [Chapter 1] C1 playthrough

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#824]
Alright, so I decided to do a quick sanity check playthrough of C1 again, and here are problems and nitpicks I have found (minus ones to be posted to existing issues):

Important Issues (for fixing ASAP)
---

- [x] C1M5: the hedgehogs are not destroyed before the German attack anymore, blocking enemy soldiers and some player bullets. The enemies are still able to go through them, but only if you are far away (likely because the hedgehogs are being culled).

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_213812](https://user-images.githubusercontent.com/59409713/121820881-cdd2ad00-cc9d-11eb-98c6-bb38e9a1e5b0.png)
</details>

End of Important Issues
---

- [x] #886
- [ ] The 'grey' effect (is this color grading?) that appears on INTERMAP before C1M1 (see screenshot 1) after starting a new game does not respect savegames: if you save there, then load an already exising savegame of some other map, the 'greyness' will transfer to the map from the savegame. Type 'map test_ldr' via console, it will start a new game, and the grey effect will perish. Then load the INTERMAP save: it will not have the effect anymore (screenshot 2).

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_173743](https://user-images.githubusercontent.com/59409713/121820051-4420e080-cc99-11eb-9815-233909e08d29.png)
</details>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_173948](https://user-images.githubusercontent.com/59409713/121820054-484cfe00-cc99-11eb-9792-a40a237758a3.png)
</details>

> I think we need a routine here that adds the LUT state/choice to the savegame as well, no idea if this can be done through ZScript though. As of now, it seems that the engine only changes the LUT if a script triggers a change. The engine doesn't care otherweise. Maybe @AFADoomer can come up with something? --T667, 2021 June 26th)

- [x] C1M2: improper setup of blocking lines near the train (pay attention to the right lower corner of the dead dog sprite):

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_184357](https://user-images.githubusercontent.com/59409713/121820506-c3afaf00-cc9b-11eb-99ad-be2712d4e5cc.png)
</details>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_184401](https://user-images.githubusercontent.com/59409713/121820516-d5915200-cc9b-11eb-8e0b-fb1d4b59d9db.png)
</details>
> I unfortunately don't get what the problem is. --T667, 2021 June 26th)

- [ ] C1M2: got 230 of 229 kills.
- [ ] After returning from C1M2 the INTERMAP treasure count became 60. It was 59 before going to C1M2. ```netevent showtreasures``` shows none.

- [x] C1M0: what about adding purple poison and IceWater resistance to the scuba gear?
> Good idea, I agree on that. Can you take care of that maybe? --T667, 2021 June 26th)

- [x] C1M0: sharks are on top of their basins:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_221046](https://user-images.githubusercontent.com/59409713/121820945-2efa8080-cc9e-11eb-92cb-db8033e39f48.png)
</details>

***
Resolved issues archive
---
<details><summary>Resolved issues</summary>

- [x] The scuba gear mask stretches on the HUD stretches to fullscreen. I can imagine how it looks at 21:9. Could it be 'padded' with a texture definition instead (like the kar98k scope), so that it retains its circular shape?

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_182054](https://user-images.githubusercontent.com/59409713/121820173-0a9ca500-cc9a-11eb-8aee-6bf9fe6cf3dc.png)
</details>

- [x] C1M4: devcomment image improperly justified (not centered in available space).

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_204302](https://user-images.githubusercontent.com/59409713/121820585-6831f100-cc9c-11eb-9d85-d6649aa7037d.png)
</details>

> Should be fixed as of bb74c1383b5615ea27acd42a5a13e86b2bc311fd - AFA (14 June 21)

- [x] CUTSCEN1: not sure if it is intended, but the format of the cutscene is cropped to a square:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_210433](https://user-images.githubusercontent.com/59409713/121820752-28b7d480-cc9d-11eb-9581-8a92520cdcba.png)
</details>

- [x] C1M4 (duplicate of #855): something blocks the player's projectiles, very likely the ladder actor. You get sprayed with bullets from MP40 enemies, but your bullets and grenades hit an invisible wall around 8 to 24 units high. Also there is a flat misalignment right under this ladder.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_204508](https://user-images.githubusercontent.com/59409713/121820615-931c4500-cc9c-11eb-908c-4d91fc0f816c.png)
</details>

- [x] By the way, regarding preceding screenshots: this door has its lock on wrong side.

- [x] More on the scuba gear, specifically in C1M2 its current placement trivializes the shark area completely. Also bear in mind that it stays in inventory unlike Doom's powerups; the player will already be able to use it in all subsequent maps, such as C1M4 which also has one. What about putting the suit to a bit more obscure place than an open locker, for example (1457, 1448)?

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_182345](https://user-images.githubusercontent.com/59409713/121821015-b7792100-cc9e-11eb-8e16-4ebbe596a673.png)
</details>

- [x] C1M2: these two red bulbs should be turned 180 degrees horizontally:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_183607](https://user-images.githubusercontent.com/59409713/121820478-a5e24a00-cc9b-11eb-8591-a3c4e754be7b.png)
</details>

- [x] C1M3: lock on wrong side of the door.

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_194805](https://user-images.githubusercontent.com/59409713/121820565-40428d80-cc9c-11eb-87e6-3eb75635edd1.png)
</details>

- [x] C1M5: the spines of these books are on the wrong side (it is better to rotate the flat):

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_213431](https://user-images.githubusercontent.com/59409713/121820787-5270fb80-cc9d-11eb-8c5c-a16d0ce5d638.png)
</details>

- [x] C1M0: some random soldier in a supply chest:

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_215631](https://user-images.githubusercontent.com/59409713/121820917-f9ee2e00-cc9d-11eb-9a65-ad9f319d61f1.png)
</details>

- [x] Ubermutant has missing death frames (just spawn him and kill with the chaingun).

</details>

<details><summary>Obligatory stats screen</summary>

<details><summary>Screenshot</summary>

![Screenshot_BoA_20210613_223857](https://user-images.githubusercontent.com/59409713/121820984-7ed94780-cc9e-11eb-973c-3c904fb4430c.png)
</details>

C1M2 has one more enemy killed than needed.</details>

**Comment by AFADoomer** [comment]
The scuba mask isn't a circle that is stretched; that's the shape of the graphic.

**Comment by Tormentor667** [comment]
Awesome that you took the time to do this. I will work on the fixes tomorrow (while watching the soccer championship ;))

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Here's also one that might have been a GZDoom bug, but I can't reproduce it with Doom II. When you open the menu, the game stops as expected. Navigate to savegames (any of the two menus), press 'delete' on one of them and press 'escape', so it does not get deleted. This will unpause the game while you are still in menu.

**Comment by Ozymandias81** [comment]
Flats and models may depend by some issues introduced in gzdoom, they were not present on c3 release

**Comment by Tormentor667** [comment]
Fixed all I was able to fix in this issue.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 What about the C1M5 hedgehogs? Is it reproducible?

**Comment by Tormentor667** [comment]
As you have described, this seems to be a culling issue and something for @AFADoomer :(

**Comment by AFADoomer** [comment]
Culling doesn't affect anything that has a TID...  but I'll take a look tonight.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 No, this is not a culling issue! The hedgehogs were removed by scripts in older versions IIRC, and now they don't...

**Comment by Ozymandias81** [comment]
Scripts and tags are there, so I think there is a problem with culling system.
![C1M5 at 2021 06 22 13-51-12 352  R3782](https://user-images.githubusercontent.com/11136108/122919793-efe4c300-d360-11eb-8df8-d2954f692aba.jpg)
![C1M5 at 2021 06 22 13-51-01 010  R3782](https://user-images.githubusercontent.com/11136108/122919800-f3784a00-d360-11eb-9647-26a14cab17ed.jpg)
![C1M5 at 2021 06 22 13-50-50 512  R3782](https://user-images.githubusercontent.com/11136108/122919806-f4a97700-d360-11eb-9b89-a79e3415cef1.jpg)

**Comment by Talon1024** [comment]
And that's what I tried to fix in https://github.com/Realm667/WolfenDoom/commit/556617ceff3f37b960cdd12b1652964b448ecefb

**Comment by Tormentor667** [comment]
So does it work now? Was it affected by culling even though it had a TID?

**Comment by Username-N00b-is-not-available** [comment]
Yes! It seems to work.
Issue transferred to 3.2.

**Comment by Tormentor667** [comment]
Just took a look at the remaining issues, nothing I can take care of. What about our coders @Talon1024 @AFADoomer @Username-N00b-is-not-available @Ozymandias81 ?

**Comment by Tormentor667** [comment]
Just took a look at the remaining issues, nothing I can take care of. What about our coders @Talon1024 @AFADoomer @Username-N00b-is-not-available @Ozymandias81 ?

**Comment by Username-N00b-is-not-available** [comment]
This issue is very old and likely done. Can't reproduce the colorgrading issue, and for other two ones someone would have to retest the level... not me this time :-)
