### ISSUE TITLE
Another dog blocked

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#825]
In c1m1, this dog is also blocked as he should attack when the gate is open.

![Screenshot_Doom_20210614_000306](https://user-images.githubusercontent.com/77861029/121823561-4dfd1080-cca6-11eb-8883-e24010bb8e31.png)

**Comment by Ozymandias81** [comment]
There is a line there which blocks the passage for the dog so it won't stuck behind the polydoor once opened, in case it doesn't get killed before. @Tormentor667 should we change it? The change was done for a purpose

**Comment by Username-N00b-is-not-available** [comment]
This way the dog also 'patrols its area' and can lure a curious but unsuspecting player into the AK officer to the left, I think it is a remarkable effect.

**Comment by x3003** [comment]
No one does this. They all shoot the dog first ;)
