### ISSUE TITLE
Minesweeper

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#827]
Correct me if I'm wrong, but I noticed that the depleted minesweeper still stays in the HUD. Is there a way to recharge the minesweeper, similar to oil for the lantern ?

**Comment by MuadDib90** [comment]
Afaik no.
You can either buy a new one, or you can find one on some maps (currently on intermap; C1M3; C3M0_A; -- and maybe one another but I don't remember). Getting a one from a map works as "refilling" to 100 % through.

**Comment by Ozymandias81** [comment]
As MuadDib90 said, you can't. Doesn't work like lanterns, this way you are forced to buy a new one or find a new one inside maps.

**Comment by MuadDib90** [comment]
> this way you are forced to buy a new one 

Exactly.

**Comment by hawkwind3** [comment]
So then, can a depleted minesweeper, which is absolutely useless, be removed from the HUD when it reaches 0% ?

**Comment by MuadDib90** [comment]
I am afraid it is not removed from inventory after hitting zero. Right @AFADoomer ?

And that high rate is on purpose, I think. If not, I'd suggest to keep it this way. (IMHO to have infinite charge, or finite but so much  you are nearly unable to use it all - so you don't mind actualy - it lacks the sense of having something only in little and try to save it, also it removes the stress when using it. -- But that is my point in general, about these kind of things.)

What was it here @Tormentor667 ?

**Comment by hawkwind3** [comment]
I was thinking of a compromise. Still deplete the charge of course, but not so much a rapid rate.

________________________________

**Comment by Tormentor667** [comment]
Well, I'd suggest as soon as the mine-sweeper's energy reaches 0%, it can be removed from the inventory.

**Comment by MuadDib90** [comment]
> 
> 
> Well, I'd suggest as soon as the mine-sweeper's energy reaches 0%, it can be removed from the inventory.

Yeah, that is totaly agree-able.

**Comment by AFADoomer** [comment]
Minesweeper is now removed from inventory when depleted, as of 47d393d84d09a4f136e6a4372a4bce1eea9b9ac9.
