### ISSUE TITLE
[3.1] Pitch after flinch stays as is

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#828]
I noticed that sometimes my viewport pitch stays as is after being injured:

![grafik](https://user-images.githubusercontent.com/10298439/121940887-e058ef00-cd4e-11eb-87ed-78f5d728f2a9.png)

Strangely I can only reproduce this on Astrostein and on this specific place.

**Comment by AFADoomer** [comment]
Interesting.  Any specifics in how to recreate this?  I'm pretty sure this code essentially hasn't been changed for a very long time.

**Comment by Tormentor667** [comment]
Well, I am using today's built of boa.ipk3, C2M0_B from this commit 5093b7d3d0489b3be0fe7c1e985021ddc4a1e29b and GZDoom g4.6.0 from 2021-05-22 (stable). I them warp to C2M0_B, activate buddha, "puke 230" (for the lasers to appear) and run into the room like a kamikaze. When taking damage, there is a chance that the wrong pitch stays.

**Comment by Ozymandias81** [comment]
To reproduce it, simply place the playerstart on a place near enemies, type immediately iddqd but make sure they hit you one time.

**Comment by Talon1024** [comment]
The only reason for this bug that I can think of is the refactored Tilt++ code might interfering with the flinch pitch somehow. However, the refactored Tilt++ code should only affect "tilted" levels, like the airship (C3M5_C) after destroying the engines.

**Comment by AFADoomer** [comment]
I'm having trouble reproducing this...  I was not able to make it happen when this was first posted, and still cannot.

**Comment by AFADoomer** [comment]
That absolutely does not help me.  Am I supposed to be triggering God mode after they hit me?  Before?  During the flinch?

**Comment by Tormentor667** [comment]
My explanation was working to reproduce it but as I said (my comment somehow disappeared) I made a clean installation with GZDoom 4.6 and the latest build and I can't reproduce it anymore so we can close this.
