### ISSUE TITLE
GetMessageTime is way too generous

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#829]
Even with a small message like this, the head continues talking for around **36 seconds**, and the text stays on screen for slightly less than **50 seconds**. (In a slow voice I would read it aloud in 6 seconds.)
It severely messes up with dialogue timing in Ryan battle (and likely in many more other places), he is dead long before his last wish starts printing.
![Screenshot_BoA_20210614_221634](https://user-images.githubusercontent.com/59409713/121947017-3d0fd600-cd5e-11eb-9be5-a74c218e0e41.png)

**Comment by Talon1024** [comment]
Here's the GetMessageTime code:

https://github.com/Realm667/WolfenDoom/blob/d009f1b2bb10b19f9c5a39066eec4264fef76297/scripts/libraries/zstools.zs#L480

**Comment by AFADoomer** [comment]
I can tweak it some...  but it's literally the same as the old ACS version, just transliterated to ZScript.

**Comment by AFADoomer** [comment]
This message only shows up for 5-7 seconds for me...  Both in the real map and in TEST_DLG.

**Comment by AFADoomer** [comment]
Should be fixed in bb74c1383b5615ea27acd42a5a13e86b2bc311fd.  When I fixed the achievement messages to 'stack' their display time when multiple are on screen at once, I forgot to add logic to *not* apply that time 'stacking' to all of the other messages in the queue...

**Comment by Username-N00b-is-not-available** [comment]
Yes, this is fixed, thank you very much!
