### ISSUE TITLE
[3.2] C2M4

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#833]
- [x] There is set some limit to how "low" you can aim when Douglas drives you near the bunker. This limit is... well limiting... in some cases (moving uphill or enemies very close) you can't properly aim (meaning you aim at all, because that limit doesn't let you to aim). Can it be canceled? 
- [x] This was there countless times but it shows again. When you drove to your destination and got out, there are some soldiers, but Douglas doesn't react. I can understand this from the engine view, but it is reeeeealy unnatural and frustrating he just standing there.
- [x]  Could the "you died" message be language specific too?

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 1) Then you will be able to shoot through the truck... You can't always aim immediately, but it is easier to hit targets which you have already left behind, for example. Maybe it could be adjusted a few degrees though, but I wouldn't remove it (well, being the person who proposed to added it in the first place).

**Comment by MuadDib90** [comment]
Ah, OK then. Then just slight adjust would be cool too imho. :)

**Comment by x3003** [comment]
>This was there countless times but it shows again. When you drove to your destination and got out, there are some soldiers, but Douglas doesn't react. 

Well, he does react, but only to the enemies that come out the nearest building. Not to other enemies and dogs.

**Comment by Username-N00b-is-not-available** [comment]
1) @MuadDib90 What happens if I allow the player to aim 12 degrees below horizon instead of 10:

https://user-images.githubusercontent.com/59409713/122190848-e0fe9c00-ce9a-11eb-8813-6272d9640de3.mp4

2) As @x3003 stated, Douglas seems to kill only the first few enemies and ignore the rest. If I activate him via 'use' though, so he tells me that I have to search for the documents, he starts shooting again and does not stop anymore.

3) Added (identifier "DEATH" at line 2309), already works in English and Russian, translate it pls :-)

**Comment by MuadDib90** [comment]
1. Agree, it looks bad. But again, I remember when I was playing it on hardest dificulty, and it was very frustraiting when they were shooting at me, hitting me (pretty hard on that skill), and I was completely "unarmed" in that situation, because there was just nothing I could do to. -- So how about making the turret higher?
2. OK, I understand. So more problems when solving versus keep it. Then I say keep it.
3. Thanks, will do. 👍

**Comment by Username-N00b-is-not-available** [comment]
2) No, I did not mean that, my comment just provided clues for people who know the decorate/zscript BoA internals better than me, @Ozymandias81, @Talon1024 and @AFADoomer.

**Comment by MuadDib90** [comment]
Aha, sure.
Add.3:
Tested it. Sounds OK. But when I approach him quickly, the message about medkits is "delayed". Then may happen a "mayhem" and this delayed message may add to the chaos. (But this is "going to extreme", let's look on that like this... maybe nobody will approach him like this. So this looses its weight.)

On the other hand, when I used a grenade, he got stuck in this position:

https://user-images.githubusercontent.com/73436978/122544405-14713000-d02d-11eb-8760-ef31aea1fb26.mp4

It has nothing to do with cheating (for testing purposes), only a grenade and a coincidence did this. Happend to me only this time. Never before, maybe never in future... Is there a purpose to to deal with it (at all)?

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 Wrong issue? #682
As for the message, well he just says that he used up a medikit, not necessarily the first one in the battle.
Added monster-blocking lines over the arena so Ryan does not end up in this situation.

**Comment by MuadDib90** [comment]
@Username-N00b-is-not-available 
Add.3
All corrections are done - FYI.

**Comment by Username-N00b-is-not-available** [comment]
For 1) offsetting the turret on the truck vertically could work, but it will be graphically inconsistent from the player's view.
It is possible to fix 2) easily I think, but only at the expense of seeing Douglas run in his place...

**Comment by MuadDib90** [comment]
Add1)
And bringing the turret closer to the cab of the truck can't help? (To have a feeling it is "over it"? In reality it surely be like it...)
Add2)
So he just standint there, but shoot, when someone appears in his line of sight is not an option? I'd never guess it could be that complicated... 😅

**Comment by Tormentor667** [comment]
Regarding **issue one**, I'd suggest adding the possibility to aim on a larger field of view and don't care about the fact that you can shoot the driving cabin. In this case "gameplay" is more important than "design". So can someone take care of that code snippet?

Regarding **issue two** I am not sure how relevant this issue really is. I know it's somehow unrealistic but on the other hand: How much work is involved to make it more realistic and is this effort worth the result? I'd like to point @AFADoomer @Talon1024 @Ozymandias81 towards this to decide if it is worth it.

**Comment by Tormentor667** [comment]
Aren't these issues mentioned by @MuadDib90 already fixed? Can you confirm Tom?

**Comment by MuadDib90** [comment]
Yes, they are good now, good work. 👍
