### ISSUE TITLE
Doors never close

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#834]
In c1m1, these doors never close. All other doors in the game seems to do so, but not these ones.

![Screenshot_Doom_20210615_213228](https://user-images.githubusercontent.com/77861029/122124098-19689080-ce2f-11eb-898a-1cb956755eab.png)

**Comment by Ozymandias81** [comment]
That's a decision made since C2 release by DoomJuan and it is important for gameplay reasons.
