### ISSUE TITLE
Doorhandles missing.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#835]
In c1m1 (and maybe others ?) these doors, don't have (moving) handles. These handles look broken anyway. How would someone open a door with these anyway ?

![Screenshot_Doom_20210615_215334](https://user-images.githubusercontent.com/77861029/122126469-11f6b680-ce32-11eb-9946-ce0e95e9e37d.png)

But in another building, you'll find these, which have moving handles.

![Screenshot_Doom_20210615_232420](https://user-images.githubusercontent.com/77861029/122126520-29ce3a80-ce32-11eb-802c-bd71fd7d912e.png)

**Comment by Ozymandias81** [comment]
They have handles, making them move would also require a major rework over textures... but I see you are not playing with boa_dt.pk3 to see displacement materials, which turn them more 3d. Try with that first

**Comment by x3003** [comment]
I play the git version w/o dt.pk3

**Comment by Ozymandias81** [comment]
That screenshot doesn't have and in the end it is a very minor detail, don't you think @Tormentor667 ?

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Here is how it looks with ```boa_dt.pk3```, which can be found in ```WolfenDoom\tools\launcher\distribution```:
![Screenshot_BoA_20210616_110323](https://user-images.githubusercontent.com/59409713/122182118-a7c22e00-ce92-11eb-8fa1-63b07f4fa85d.png)
![Screenshot_BoA_20210616_110327](https://user-images.githubusercontent.com/59409713/122182168-b4df1d00-ce92-11eb-9282-2c0e2133ecb3.png)

**Comment by Ozymandias81** [comment]
Since I don't want to rework brightmaps for these, and also this would also mean to rework displacement materials, I think we can live with these.

**Comment by Tormentor667** [comment]
These are handles but knobs
