### ISSUE TITLE
Weird issue.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#836]
In c1m1, get to this room.

![Screenshot_Doom_20210615_232553](https://user-images.githubusercontent.com/77861029/122127004-d8727b00-ce32-11eb-9dea-42c38d5ffc68.png)

It has a scientist in it. But if you rush the map and don't take the time to save, just run, you'll see a guard, which transforms into a scientist. I've tried it a few times now. It doesn't work when you're slow, only when you sprint.

**Comment by Ozymandias81** [comment]
Could belong to inheritances between actors, since the base code inherit to BasicGuard most probably, but how fast are you running to provoke it? Can you make a video of it? Is it possible only with cheats? Which version of GZDoom? Are you playing with C3 release or a daily build from this repository?

**Comment by x3003** [comment]
Just run and fire fast. No cheats. Latest version of gzdoom. Ofcourse git version of boa....

**Comment by Username-N00b-is-not-available** [comment]
A _crouching_ guard specifically (got this with usage of ```freeze``` cheat: shoot the door from (900, 1040), freeze and noclip into the room):
![Screenshot_BoA_20210616_110855](https://user-images.githubusercontent.com/59409713/122183058-8c0b5780-ce93-11eb-99af-0405407b071c.png)
Has rolling been removed from scientists? It looks like SCNDA frame, which was used for rolling and also for crouching, is absent...

**Comment by DoomJedi** [comment]
>Has rolling been removed from scientists?

Yes, it was utterly unrealistic for non-trained civilians.

**Comment by x3003** [comment]
>Yes, it was utterly unrealistic for non-trained civilians.

Could be, but it was funny though.
