### ISSUE TITLE
[Delta Touch?] INTERMAP/Chapter 1: Douglas' dialogue lingers onscreen if tutorial is completed rather quickly.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#837]
If you blaze your way through the Chapter 1 Tutorial, Douglas' dialogue will persist onscreen long after the tutorial has finished.
![Screenshot_2021-06-14-11-01-24-942_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/122133728-e3151c00-ce02-11eb-8584-a5b8e009703b.jpg)

**Comment by Ozymandias81** [comment]
Delta-Touch?

**Comment by Username-N00b-is-not-available** [comment]
How old is the commit you were playing on, @Shockwave508? If it is before https://github.com/Realm667/WolfenDoom/commit/bb74c1383b5615ea27acd42a5a13e86b2bc311fd, the problem might as well have been fixed.

**Comment by Shockwave508** [comment]
Was without an internet connection for a while; issue appears to be fixed as of the latest commit. Safe to close.

**Comment by Tormentor667** [comment]
Thank you @Shockwave508 for your testing work currently, this is very helpful. Same goes to the other testers as well!
