### ISSUE TITLE
C1M3 unwanted nasty scrolling floors/ceilings plus

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#839]
C1M3 ...

- [x] a) Floors and ceilings of sectors 1023, 1029, 1030 and 1037 have unwanted scroll. And the first four sectors scroll the sidedef textures, not the flat. Somehow linked to the 3D floor and the tag ?
- [ ] b) While at it, the ceiling of sector 1703 should have a brightness of 128.
- [ ] c) Texture on lines 6845 and 13667 should be the same. Can be clearly noticed when using the elevator at sectors 1330/1314.

**Comment by Ozymandias81** [comment]
a) is related to this script, gonna fix target tags on that room
![image](https://user-images.githubusercontent.com/11136108/122433205-4be0cd80-cf96-11eb-8bf8-b8332ee85ce6.png)

**Comment by hawkwind3** [comment]
All issues not fixed. a) is fixed but not b) and c).
c) especially needs fixing.
Sector 2735 can be added to b) .

**Comment by Ozymandias81** [comment]
These have been fixed already by me.
