### ISSUE TITLE
Achievements: Getting several at once results in extreme loudness.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#840]
When obtaining several Achievements simultaneously, the appropriate sound layers over itself several times over, resulting in a brief moment of extreme loudness. Perhaps play the sound only once, if this happens?

In my case, it was with the following achievements after finishing C1M1, all at once:
Stingy With the Ammo
Automatic Weapons
Blast-Resistant

**Comment by AFADoomer** [comment]
Yes, should be able to do that.

Related: I don't particularly like the achievement sound - if anyone had a better idea for that, please submit it.

**Comment by Tormentor667** [comment]
Maybe a classic sound from Wolfenstein 3D would do?

**Comment by Tormentor667** [comment]
**Update** Link to all Classic Wolf3D Adlib sounds
http://www.mediafire.com/file/6hzjvisrtmskeem/Wolf3d_Adlib_in_WAV.zip/file

**Comment by AFADoomer** [comment]
I kind of have all of these alreadyfrom another mod 😉 😛 .

**Comment by Tormentor667** [comment]
...ah... there was something - what reminds me that we need a Wolf 3D TC easter egg for a certain programmer I know... ;)

**Comment by AFADoomer** [comment]
The issue of overlapping sounds should be resolved after ad376e270f2ebd852b8a14ef4545d884a853b9e4.
