### ISSUE TITLE
C3M5_A Falling Debris

### ISSUE THREAD

**Issue by Ninlhil** [Realm667/WolfenDoom#841]
Dunno if this has been mentioned and addressed or what, I did look around and didn’t see anything. In C3M5a, in the corner of a small room just before the long hallway by the entrance to the bunker, there is a piece of debris that just falls endlessly. Again, sorry if this has been mentioned and addressed, just wanted to mention.

**Comment by Tormentor667** [comment]
Thanks for noticing, this has already been taken care of afaik (it was a general problem with the debris), is this correct @AFADoomer @Talon1024 ?
