### ISSUE TITLE
3d actors which die seems to lose always their collision behavior

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#843]
As the title say, several actors such as Flakvierling3d, rolling boulders, planes and so on, tends to lose their SOLID behavior when entering their Death state. I guess this is related to some optimizations inheritances with the Cull system. Any clues? For boulder for example, even if I [edit this line](https://github.com/Realm667/WolfenDoom/blob/master/scripts/actors/boulders.zs#L240), nothing changes. The actor stays non-solid.

**Comment by AFADoomer** [comment]
That's because I retrofitted new code into the awful way the boulders were originally set up in order to make sure the behavior was precisely the same.  The line you changed is in the placed spawner actor, not the boulder projectile. 

The behavior is like this because that's how the old behavior was.  I think the fix to this is to set the bSolid flag to true in the death state of the Boulder actor.

**Comment by AFADoomer** [comment]
All of the other actors call A_NoBlocking or similar in their death states, so become non-solid as a result.

**Comment by Ozymandias81** [comment]
I did add the bSolid flag and also tried removing NoBlocking for Flakvierlings, but nothing changes.

**Comment by AFADoomer** [comment]
The actors aren't losing their solid behavior, their height is being changed to 1/4 of the default height when they are killed - the default Doom behavior. So we just need to remove A_NoBlocking from the death states and add DeathHeight<whatever their height is> to the actor definition.

See 7edb9c6661b11f398ec2254867940e1064672180.

**Comment by Ozymandias81** [comment]
Weird because this wasn't happening on past builds of GZDoom afaik.

**Comment by Tormentor667** [comment]
Indeed. I can remember having a similar problem years ago and then read about the height change.

**Comment by Tormentor667** [comment]
![grafik](https://user-images.githubusercontent.com/10298439/123521598-fc964d80-d6b7-11eb-9e6b-946796e47913.png)

After these fixes, the issue can be closed I guess.
