### ISSUE TITLE
Wrong color ?

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#846]
Why is the word 'key' in yellow ? Why not make the words 'red key' both in red ? Dunno if there are other combo's in the game that could or should be changed.

![Screenshot_Doom_20210614_010209](https://user-images.githubusercontent.com/77861029/122475809-7ac26800-cfc5-11eb-8c4e-ec1a0f136c96.png)

**Comment by Username-N00b-is-not-available** [comment]
I remember a similar message on C2M6_B.
IIRC some months ago it was as you suggest now, and after that @MuadDib90 suggested to separate one word from another. The change is easily done, but an agreement over which form is to stay should be made. @Tormentor667?

**Comment by MuadDib90** [comment]
Yes, I remember that.
My argument on this was to be it more recognizable. Items (in general) are written in yellow, That way they can be easily seen and also read "briefly". And the color of the color word helps to assign it instantly.

As I was for this change, I'd like to keep it, but it is up to @Tormentor667.

**Comment by Tormentor667** [comment]
Well, I tried to do it that way usually as the "key" is the item and the "red" is defined by the color. It isn't necessary though, we can either keep it as is or make it completely "red".

**Comment by MuadDib90** [comment]
> 
> 
> Well, I tried to do it that way usually as the "key" is the item and the "red" is defined by the color. It isn't necessary though, we can either keep it as is or make it completely "red".

I'd fo with the first option, so keep it as is; if you ask me.

**Comment by Tormentor667** [comment]
Are there other strings that need to be adjusted then to this behaviour?

**Comment by MuadDib90** [comment]
Hmm, maybe a couple more...

**Comment by Tormentor667** [comment]
Do you think you can look through the english entries?

**Comment by MuadDib90** [comment]
24 general entries of a kind: "you found \c?COLOR \cFkey"
And about 5 entries as mentioned in the first post.

**Comment by Tormentor667** [comment]
So, what needs to be changed? I thought we keep "\c?COLOR \cFkey"?

**Comment by MuadDib90** [comment]
As for me - nothing. :sweat_smile: There is maybe misunderstanding...
@x3003 only proposed if we should change format of lines as "\c?COLOR \cFkey" to "\c?COLOR key".
So if we don't want to change this, this issue is solved. Everything stays as is. (In format "\c?COLOR \cFkey")
If we decide to hear @x3003 out, what has to be changed are those 29 lines to format "\c?COLOR key".

**Comment by Tormentor667** [comment]
Now I got you, thanks for the explanation :) We are done here.
