### ISSUE TITLE
Dead mechanics give 2 guns

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#849]
In c3m0_b, some of the mechanics give 2 guns. When they surrender they give 1 gun, when you kill them you'll get another one.

![Screenshot_Doom_20210618_001301](https://user-images.githubusercontent.com/77861029/122479179-f1159900-cfca-11eb-829d-d26fffa6fccb.png)

**Comment by x3003** [comment]
I saw it in a vid and it still works with the git version. This is what happens: https://youtu.be/AODwOSC0c9k?t=1033

**Comment by AFADoomer** [comment]
This should be resolved in 0db8baa54a0d77fcfae854053d0ca48ae9b3784d.  Sneakable enemies weren't checking to see if the enemy had surrendered already before dropping weapons.

**Comment by x3003** [comment]
Now he never surrenders anymore, so technically resolved, but not as it should be I think.

**Comment by AFADoomer** [comment]
Unlikely that he never surrenders now, since that code has nothing at all to do with deciding if he will surrender or not.  

More likely, the random behavior just isn't kicking in for you.  RNG is a fickle thing...

**Comment by x3003** [comment]
Well, with the 'old' build he surrendered maybe 7/10 times. Now, 0/10 times. He always keeps shooting instead.

**Comment by AFADoomer** [comment]
I tested it.  It works.

**Comment by x3003** [comment]
Doesn't work for me though.

**Comment by AFADoomer** [comment]
Yet it does for me.  Again, just now.  Such is the nature of randomness....

**Comment by x3003** [comment]
Strangely I couldn't let them surrender w/ yesterdays build, but it seems fixed w/ today's build.
