### ISSUE TITLE
C1M3 tower lift texture change bug

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#852]
C1M3 ...

Texture on lines 6845 and 13667 should be the same. Can be clearly noticed when using the elevator at sectors 1330/1314.

**Comment by Ozymandias81** [comment]
This is a doubled issue, which have been fixed already after #839

**Comment by hawkwind3** [comment]
Apologies, yes, that has been fixed, but I noticed, when taking the lift up, and looking up, the player can also see the change from METLB_08 to METLB_10. Maybe a new texture needs to be made ?
