### ISSUE TITLE
[3.1] Annoying issue with a ladder on C1M4

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#855]
At the top of this ladder on C1M4, the enemies can shoot you and hurt you just fine, but you can't shoot back at them or throw grenades at them. If you try and throw a grenade at them, the grenade will just fall down to the bottom of the ladder. This issue makes this part of C1M4 very frustrating for me.

https://user-images.githubusercontent.com/6550500/122633104-c992ff00-d0a4-11eb-941f-28512b056772.mp4

https://user-images.githubusercontent.com/6550500/122633105-ca2b9580-d0a4-11eb-990a-b2b943b6a62d.mp4

**Comment by x3003** [comment]
Yes, this is a difficult area. When I normally throw a grenate, I do that backwards, so it **bounces** of the walls and hit the enemies.
Or come up fast and hide behind the left crate. But yeah, they react very fast. Maybe someone told them you would come up ?!

**Comment by AFADoomer** [comment]
I think this is a portal transition issue.  

The portal plane is level with the floor of the upper area, and the ladder texture in the lower area is a walkable/wrapped mid-texture (so essentially treated as an infinitely tall blocking line for projectiles).  While you are transiting the portal, the blocking line from the lower area is still affecting the grenades, despite the view having shifting to the upper area.

**Comment by Username-N00b-is-not-available** [comment]
BTW this also happens on ladders from some other maps, see my pinned issues.

**Comment by AFADoomer** [comment]
This is likely not going to be fixable by us.  This is almost certainly a quirk of the floor/ceiling portal setups here.

I have tried all line arrangements, including completely removing both the ladder texture line and the ladder/climbable zone actor, and this still occurs.

**Comment by Tormentor667** [comment]
The only thing I can imagine is removing enemies from there so they cannot instantly attack you, to make this passage not so fucking hard. What do you think?
