### ISSUE TITLE
Room has 2 switches

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#856]
In c3m0_b, this room has 2 lightswitches. You can turn the lights off with one and on with the other and vice verse. Why not make it 1 instead ?

![Screenshot_Doom_20210619_130423](https://user-images.githubusercontent.com/77861029/122641354-04c51a80-d105-11eb-9b20-03c140fb99e1.png)

**Comment by Ozymandias81** [comment]
Because ideally when one enters a room from a different side of a building, should have the switch near the opened door.

**Comment by x3003** [comment]
This is normally not how rooms work, generally speaking.

**Comment by Tormentor667** [comment]
My living room works exactly that way @x3003 :-D
