### ISSUE TITLE
Alarm switch wrong color

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#857]
In c3m0_b, this alarm switch is always in the activated color, even when disabled.

![Screenshot_Doom_20210619_131051](https://user-images.githubusercontent.com/77861029/122641426-9e8cc780-d105-11eb-96cd-4131207ed3ee.png)

![Screenshot_Doom_20210619_131317](https://user-images.githubusercontent.com/77861029/122641434-a9dff300-d105-11eb-9b27-6d65b2db0966.png)

**Comment by Ozymandias81** [comment]
Probably wrong tags used for lights

**Comment by x3003** [comment]
All the other switches seems fine, only this one is affected.

**Comment by Ozymandias81** [comment]
Looks like it is relative to actors themselves, any clues @AFADoomer ?

**Comment by AFADoomer** [comment]
There's a red/purple light in the mutant chamber below it that is coloring it...  Move the panel somewhere else to fix.

**Comment by x3003** [comment]
Now it's moved to this place.... Which is clearly the wrong one.

![Screenshot_Doom_20210620_153909](https://user-images.githubusercontent.com/77861029/122676371-1cbc9d00-d1de-11eb-8e00-33d0334e6529.png)

**Comment by Tormentor667** [comment]
That’s strange, it is placed with a z-height and looks right in the editor.

**Comment by Tormentor667** [comment]
Found the problem, fixed!

**Comment by x3003** [comment]
Now it's in the right position, but you still have that glow which leaks through the floor / wall (also on the other side) which makes the switch looks different. 

![Screenshot_Doom_20210620_213736](https://user-images.githubusercontent.com/77861029/122686760-4217ce00-d213-11eb-9a51-e8017afb9e95.png)

![Screenshot_Doom_20210620_215444](https://user-images.githubusercontent.com/77861029/122686761-45ab5500-d213-11eb-8df7-813bedc7a019.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Moved it under the swastika in an upcoming commit:
![Screenshot_BoA_20210620_231417](https://user-images.githubusercontent.com/59409713/122687085-434df880-d21d-11eb-91c9-1e26f1eff668.png)

**Comment by x3003** [comment]
Wrong again.... Why not leave this one open until fixed ???

![Screenshot_Doom_20210620_235816](https://user-images.githubusercontent.com/77861029/122689541-a0e54380-d223-11eb-80bd-8edf542fa69e.png)

![Screenshot_Doom_20210620_235856](https://user-images.githubusercontent.com/77861029/122689542-a3e03400-d223-11eb-964f-b7111a4a7361.png)

**Comment by Ozymandias81** [comment]
Should be "fixed" now, and since the issue looks easy that's why we close it.

![C3M0_B at 2021 06 21 15-08-56 425  R3782](https://user-images.githubusercontent.com/11136108/122767459-fa408780-d2a2-11eb-9ede-6142ac1ef20f.jpg)

**Comment by Tormentor667** [comment]
> Wrong again.... Why not leave this one open until fixed ???

So much trouble for such a small thing :) Is it fixed now?
