### ISSUE TITLE
Something green

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#858]
In c3m0_b, something green is growing out of the wall at this spot. Maybe remove it ?

![Screenshot_Doom_20210619_131657](https://user-images.githubusercontent.com/77861029/122641497-f88d8d00-d105-11eb-8590-58a86be257ec.png)

**Comment by Ozymandias81** [comment]
Since tree are spawned randomly, that means that one tree oustide needs to be moved from where it is to avoid these issues. Thanks for noticing.

**Comment by Tormentor667** [comment]
Fixed

**Comment by Ozymandias81** [comment]
Dan I have committed fixes for C3M0_B, think you'll have to redo these.

**Comment by Tormentor667** [comment]
I know, I stashed mine and used your copy and reimplemented them :)
