### ISSUE TITLE
The wrong answer

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#859]
In c3m0_b, if you give this guy the wrong answer, there's no repercussion for giving it. So he **should** think you're a spy then and shoot you. Instead you can walk away freely.

![Screenshot_Doom_20210618_214459](https://user-images.githubusercontent.com/77861029/122641654-fed03900-d106-11eb-99f5-837f3a95c64b.png)

**Comment by Tormentor667** [comment]
He doesn't shoot you but he doesn't talk to you either.

**Comment by x3003** [comment]
Well, you can talk to the guy and give the right answer and he talks **then** and give a key. But if you say 'goodbye' he still stands like this forever.

**Comment by Tormentor667** [comment]
...until you say the right keyword. Well, I know what you mean, maybe having him attack you if you say "Goodbye" but that would mean so much hazzle for such a minor thing. It isn't game-breaking, you can talk to him and continue, that's fine I guess.

**Comment by x3003** [comment]
>maybe having him attack you if you say "Goodbye" 

Yes, that's what i mean. And no, it's not game breaking. But, someone pointing a gun at you, wouldn't let you leave....

**Comment by Tormentor667** [comment]
The only thing I could think of is locking the doors until you continue with the dialogue

**Comment by Talon1024** [comment]
I just added a feature which prevents the "Goodbye" option from being added if the Goodbye option is "None".
