### ISSUE TITLE
[3.2] [for Captain J] Sprite improvements and additions - what do we need? What does he suggest?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#860]
Now that Captain J has already offered some improvements and help, I think it is better to organize this here, to keep track of things and create a place where we can discuss our ideas.

So, is there currently anything, Captain J could help us with? Or, Captain J, is there anything you would suggest?

**Comment by Ozymandias81** [comment]
Well I think I have already said it on this thread [what we need](https://github.com/Realm667/WolfenDoom/issues/832) :)

**Comment by Tormentor667** [comment]
> Well I think I have already said it on this thread [what we need](https://github.com/Realm667/WolfenDoom/issues/832) :)

That's only for rotations but thanks for linking, and maybe there is more.
