### ISSUE TITLE
[3.2] C1M6 Issues ...

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#861]
C1M6 ...

- [x] a) Slope misalign at lines 4703 and 4705. Same when at sector 1087. Actually, worth checking all
similar constructs in this map. I realise, as has been mentioned, that gzdoom changes might be the cause.
- [x] b) At sector 2509 and nearby, can only hear the impact of the darts on every second impact. Similar at sector 726 area. My system makes a click type sound on firing/launching the dart.
- [x] c) Web should be on both sides of lines 7155 and 7202 ( or block said lines ) .
- [x] d) Possible wrong Y offset on line 4430. Lower renders black.
- [x] e) Might be a Vulkan/hardware issue, but what seems to be a "gap" shows up at line 3464. When I used the "scope" on vertex 2905, it looked like a slope glitch.
- [x] f) T3815 and T3816 should not have been placed on a line with differing ceiling heights either side.
- [x] g) Is it possible that just the floors of sectors 2184, 2186 etc. etc, have the increased brightness level. Would look better since the ceilings should not be lit.

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3
b) Can't reproduce it. What happens for me:

https://user-images.githubusercontent.com/59409713/123056710-d77fb180-d40f-11eb-92da-20010ddf3af5.mp4

e) 3464 was not parallel to 3447, which has Plane Align action and aligns the sector. Moved the lines a bit, so it is not longer the case.
f) Not sure which ones you are talking about, the map has 3298 things currently...
g) @Tormentor667 seems to have done it but forgotten to mark the checkbox.

**Comment by hawkwind3** [comment]
@ b) I downloaded the mp4 and this plays correctly with WMP. I cannot explain the effect in game for me. Must have something to do with my system.
@ f) UDB screenshot attached
![c1m6](https://user-images.githubusercontent.com/35204218/123094214-fca40c80-d46f-11eb-9cac-5451beb83135.jpg)

**Comment by Tormentor667** [comment]
Fixed f)

**Comment by Tormentor667** [comment]
I just tried issue b) on my computer as well and I encountered the same issue. The death sound is only played each second time. I changed the pattern in my latest commit and the problem is interestingly the same - only each 2nd hit is played for each position. It has something to do with the sound limites.

I added this line to SNDINFO:
`$limit NailHit 12 256`

That made it actually work again
