### ISSUE TITLE
Can't destroy radio

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#862]
In c3m0_b, you can't destroy this radio. Maybe a minor issue, but all other radio's in the game can be destroyed.

![Screenshot_Doom_20210619_102601](https://user-images.githubusercontent.com/77861029/122643641-35ab4c80-d111-11eb-97f1-cc10bde45e5e.png)

**Comment by Tormentor667** [comment]
I think that radio misses a death state/model.

**Comment by Username-N00b-is-not-available** [comment]
I don't think we should add the option to destroy it. We do not have every object destructible, and the Soviets would have given you a good scolding if you destroyed it :-)

**Comment by x3003** [comment]
Well, you can destroy the radio of Juliette in Paris. She wouldn't like that very much either.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 That should be fixed, thank you! Are there any other occasions?

**Comment by x3003** [comment]
Not that I know.

**Comment by Ozymandias81** [comment]
It didn't had intentionally the death state in order to force players eventually not miss transmission coming from that radio, which are different and doesn't happen anywhere else, that I can remember.

**Comment by Username-N00b-is-not-available** [comment]
The unique transmission is on C3M5_B, but the radio is reused on C3M0_B.

**Comment by Ozymandias81** [comment]
All good anyway. :)
