### ISSUE TITLE
[3.1] Epilogue Boxes and Texts issue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#864]
In c3m0_b, this box is a little too big and the text is positioned wrong.

With the release version it looks a lot better:

![box_old](https://user-images.githubusercontent.com/77861029/122652744-9e5ded80-d140-11eb-9096-5b5cce0727b9.png)

With the git version it just looks odd:

![box_new](https://user-images.githubusercontent.com/77861029/122652809-13c9be00-d141-11eb-9713-05dad4fde7d6.JPG)

**Comment by Tormentor667** [comment]
Yes, I noticed that as well

**Comment by AFADoomer** [comment]
This happened when I 'fixed' the box to make sure that the text stays inside of the box in ultra-widescreen.

**Comment by AFADoomer** [comment]
Should be resolved after e486aa70919eefa7925fa282943a1a9f9b765ab1.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer
![image](https://user-images.githubusercontent.com/59409713/122786372-e7d34780-d2bc-11eb-902f-c51a30018c3f.png)

**Comment by Tormentor667** [comment]
Confirmed with the fresh install and latest version:
![grafik](https://user-images.githubusercontent.com/10298439/122816230-bff0dd80-d2d6-11eb-9244-f2f9a951b156.png)

**Comment by Username-N00b-is-not-available** [comment]
For the record: as @Talon1024 stated in https://github.com/Realm667/WolfenDoom/commit/85ebe1ea339611cb61852c163e4cbff70aa4a97f, it works now fine for 16:9 and wider, but there are problems with other ratios. Here is a screenshot for 1280x960:
![image](https://user-images.githubusercontent.com/59409713/123400327-501c7480-d5ae-11eb-81e8-20ec43a40237.png)
@Tormentor667 Is there a reason that the box gets displayed this way? Could it be remade as it is in C2M0_A, for example?
![image](https://user-images.githubusercontent.com/59409713/123400937-f5cfe380-d5ae-11eb-9275-5e036abec79d.png)

**Comment by Tormentor667** [comment]
It works for me on wider resolutions as well:

![grafik](https://user-images.githubusercontent.com/10298439/123471846-ae6d4580-d5f6-11eb-8288-4e5c2f2cb2ec.png)

**Comment by Tormentor667** [comment]
I just tried it again, even resizing the game window on the fly to all crazy ratios didn't break the text. This is fixed.
