### ISSUE TITLE
snipers not firing

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#865]
In c2m5_a, 2 of the snipers are not facing the player. But all of them aren't even shooting, they you just stand there. Even the 2 facing the player don't shoot. As there is no fog they should be able to fire....

![Screenshot_Doom_20210619_211913](https://user-images.githubusercontent.com/77861029/122653809-88076000-d147-11eb-8c6c-495233b2a342.png)

**Comment by Username-N00b-is-not-available** [comment]
Honestly I have zero idea how to fix it. I have raised brightness, removed the ambient smoke generator, removed player/sound environment-blocking flags...
Maybe it has something to do with fade/desaturation, and the snipers are unable to see you in that sector (but you instantly get 3 or 4 bullets in your body if you fly into sector 0 with noclip)? @AFADoomer, could you please help here with visibility?

**Comment by Username-N00b-is-not-available** [comment]
Thank you! This is fixed.

**Comment by x3003** [comment]
Yes, fixed.
