### ISSUE TITLE
weapon is changed after ride

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#866]
In c2m5_a, when you have something else than the sniper rifle as weapon (or maybe none) when riding the truck, the moment you get off it's changed back to the sniper rifle.

![Screenshot_Doom_20210619_212254](https://user-images.githubusercontent.com/77861029/122653896-2398d080-d148-11eb-9de0-be72f4a4ea6a.png)

**Comment by Username-N00b-is-not-available** [comment]
This is a leftover from C2M4 script:
![image](https://user-images.githubusercontent.com/59409713/122654184-4a5c0480-d152-11eb-92aa-4d94de1521a6.png)
which means the behaviour has likely been present for 4 years already :-D
Fixed it, will commit with other two issues.
