### ISSUE TITLE
surprise party waiting

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#867]
In c2m5_a, when you want to come down in this spot, you'll get a surprise party with lotsa solders and a dog.
Can't remember there were so many waiting in the release version, but I could be wrong.

![Screenshot_Doom_20210619_213340](https://user-images.githubusercontent.com/77861029/122654026-d9641f00-d148-11eb-88de-5491d40e2859.png)

**Comment by Username-N00b-is-not-available** [comment]
Yesterday I added a monster-blocking flag to a line so the enemies do not enter between the boxcars, and also an invisible walkable projectile-blocking linedef over the boxcar with the enemies so they do not get alerted by tracers (it does not block bullets below itself, so no gameplay problems).

**Comment by x3003** [comment]
They block them, but there are still a lot waiting for you. Even in the rooms there might be 5-6 guards in.
