### ISSUE TITLE
New C2M1 issues

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#868]
C2M1 ...

- [ ] a) Stand at sector and open door where sector 2290 is. Watch the alarm panel on line drop down a few pixels. This only happens once.
- [ ] b) For some reason the red globe is not shown at sector 5783 , but nearby.
- [x] c) Sector 2299 should have a brightness of 112.
- [x] d) Sectors 5296, 5297, 5246 and 5298 should have a brightness of 120.
- [x] e) Sector 1842 floor brightness should be 152.

**Comment by Tormentor667** [comment]
> For some reason the red globe is not shown at sector 5783 , but nearby.

I don't understand this issue

> Stand at sector and open door where sector 2290 is. Watch the alarm panel on line drop down a few pixels. This only happens once.

Which alarm panel? (think index might help) And are you playing the latest dev version? I am pretty sure that I've fixed this before already by moving the alarm panels.

**Comment by hawkwind3** [comment]
I now just downloaded the latest c2m1 map. a) and b) can be closed. They are fixed in the latest. So all this can now be closed.
