### ISSUE TITLE
What is bmvolcano.png (brightmaps), why is it 6MB and is it actually used?

### ISSUE THREAD

**Issue by Kroc** [Realm667/WolfenDoom#87]
This seems like package bloat and if it is being used, a VRAM killer.

**Comment by Tormentor667** [comment]
It is used (and needed) in C2M6_C

**Comment by Kroc** [comment]
Wouldn't JPEG be more appropriate, it'd be a mere fraction of the size! :)

**Comment by Ozymandias81** [comment]
It's just one texture, also jpeg conversion would mean to break its bright color details.

**Comment by Ozymandias81** [comment]
Nevermind, my fault: forget to crush the brightmap, also I used brutal compression through FormatFactory though and [saved 2mb](https://github.com/Realm667/WolfenDoom/commit/1aa04cd70fa43814e70d3e1364d7332ccdd68493). Thanks Kroc.
