### ISSUE TITLE
[3.1] Tesla armor buying issue

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#870]
@Ozymandias81 @AFADoomer 
AFAIK you should be able to have only 100 % of tesla armor, am I right?
Being able to buy a tesla armor when already having 100 % of regular armor isn't something odd. It should just "transpose" the 100 % of regular armor to 100 % of tesla armor. But I got 200 % of tesla armor... 😄 Cool, but also a strange behavior.

**Comment by Tormentor667** [comment]
Your assumption is right, the different armor types shouldn't stack.

**Comment by AFADoomer** [comment]
Should be fixed in c5c472951cb66b6d0920aba2ea80e36a0ae7c0c2.  

Tesla armor now ignores other armor present, and overrides whatever existing percentage was there to set the amount to 100% (even if you had over 100% before).  If you have enough gold to buy multiple Tesla Armors, they will still stack with each other, up to 200%.

**Comment by Ozymandias81** [comment]
Regarding these kind of issues, since all the code has migrated to zscript, now I am surely the last person to be tagged for these, I can understand a couple of things but I don't handle zscript at all like decorate, so just to let you know it.

**Comment by MuadDib90** [comment]
> 
> 
> Should be fixed in [c5c4729](https://github.com/Realm667/WolfenDoom/commit/c5c472951cb66b6d0920aba2ea80e36a0ae7c0c2).
> 
> Tesla armor now ignores other armor present, and overrides whatever existing percentage was there to set the amount to 100% (even if you had over 100% before). If you have enough gold to buy multiple Tesla Armors, they will still stack with each other, up to 200%.

Nice. :)



> 
> 
> Regarding these kind of issues, since all the code has migrated to zscript, now I am surely the last person to be tagged for these, I can understand a couple of things but I don't handle zscript at all like decorate, so just to let you know it.

That's both of us. 😆

**Comment by Tormentor667** [comment]
Stacking them is a good idea btw :)

**Comment by MuadDib90** [comment]
> 
> 
> Stacking them is a good idea btw :)

Agree. Will the players know about this feature, or should we left it in "let them discover this feature" drawer?

**Comment by Tormentor667** [comment]
That's a good question, I think we should add some information here somehow in the dialogues (additional sentence in Laz' explanation).

**Comment by Username-N00b-is-not-available** [comment]
```...because I'm not coming with you to replace it with another one.``` (CLERKCONV44) ->
```...because I'm not coming with you to replace it with another one. Or two: it is possible to wear two sets at once!```
