### ISSUE TITLE
[3.2] [C2M5_B] Flying saucer explosion needs more deta... I mean debris

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#872]
In c2m5_b, when the flying saucer is destroyed you only see a little puff of smoke. Shouldn't there be a bit more smoke and debris coming down ?

![Screenshot_Doom_20210620_133554](https://user-images.githubusercontent.com/77861029/122676614-15e25a00-d1df-11eb-904f-e25e202c2027.png)

**Comment by Tormentor667** [comment]
This is strange, a huge explosion should be going on. Btw, can you make the title a bit more explanatory?

**Comment by x3003** [comment]
Yes, but after the explosion, some more debris should come down. Instead this little puff of smoke comes...

**Comment by AFADoomer** [comment]
Probably effect culling in action...  The whole sequence was a lag-fest for me before.

**Comment by Tormentor667** [comment]
> Probably effect culling in action... The whole sequence was a lag-fest for me before.

But it looked cool - even with 3FPS :D

**Comment by x3003** [comment]
> [3.1] Explosion in C2M05_B not working anymore 

??? As said before, the explosion works, but maybe there could be some debris falling from the sky. Instead of this little puff of smoke.

**Comment by AFADoomer** [comment]
What are your performance settings?

**Comment by Username-N00b-is-not-available** [comment]
BTW with almost everything off and culling ranges at 2048 a lot of small junk pieces are spawned after the saucer is destroyed (but as for my opinion, they do it way too 'regularly', just falling down — it is not what you would expect from such an explosion. This is a nitpick and does not need to be addressed.)

**Comment by x3003** [comment]
> it is not what you would expect from such an explosion. 

That's what I meant.

**Comment by Tormentor667** [comment]
> Probably effect culling in action... The whole sequence was a lag-fest for me before.

Just tried the explosion and it's definitely a culling issue. The explosion sprites appear for a short moment then instantly disappear, leaving only a small cloud which makes the whole sequence disappointing. Can the culling be completely deactivated for the actor SecretUFO - or actually the special effects that get spawned when it is destroyed?

`class SecretUFO : SwitchableDecoration //3dRealms - no distancecheck for this
{
	Default
	{
		//$Category Models (BoA)/Scenery
		//$Title Secret UFO
		//$Color 3
		+MOVEWITHSECTOR
	}
	States
	{
	Spawn:
		MDLA A -1;
		Wait;
	Active:
		"####" A 35; //just wait 1 sec before spawning effects
		"####" A 0 A_StartSound("UFOLNCH", CHAN_AUTO, 0, 1.0, ATTN_NONE);
	ActiveLoop:
		MDLA A 0 A_SpawnItemEx("UFOCirclePad",0,0,-8,0,0,random(1,8), SXF_SETMASTER | SXF_NOCHECKPOSITION);
		"####" A 15;
		Loop;
	Inactive:
		MDLA A 0 A_StartSound("UFOEXPL", CHAN_AUTO, 0, 1.0, ATTN_NONE);
		"####" A 0 A_NoBlocking;
		"####" A 0 A_RemoveChildren(TRUE, RMVF_EVERYTHING);
		"####" AAAAAAAAAAAAA 0 A_SpawnItemEx("Debris_Tank", random(-256, 256), random(-256, 256), random(16, -16), random(1, 3), random(1, 3), random(1, 3), random(0, 360), SXF_CLIENTSIDE);
		"####" AAAAAAAAAAAAA 0 A_SpawnItemEx("Debris_MetalJunk", random(-256, 256), random(-256, 256), random(16, -16), random(1, 3), random(1, 3), random(1, 3), random(0, 360), SXF_CLIENTSIDE);
		"####" AAAAAAAAAAAAA 0 A_SpawnItemEx("Debris_Metal1", random(-256, 256), random(-256, 256), random(16, -16), random(1, 3), random(1, 3), random(1, 3), random(0, 360), SXF_CLIENTSIDE);
		"####" AAAAAAAAAAAAA 0 A_SpawnItemEx("Debris_Metal2", random(-256, 256), random(-256, 256), random(16, -16), random(1, 3), random(1, 3), random(1, 3), random(0, 360), SXF_CLIENTSIDE);
		"####" AAAAAAAAAAAAA 0 A_SpawnItemEx("Debris_Metal3", random(-256, 256), random(-256, 256), random(16, -16), random(1, 3), random(1, 3), random(1, 3), random(0, 360), SXF_CLIENTSIDE);
		"####" AAAAAAAAAAAAA 0 A_SpawnItemEx("Debris_GlassShard_Large", random(64, 256), random(64, 256), random(16, -16), random(1, 3), random(1, 3), random(1, 3), random(0, 360), SXF_CLIENTSIDE);
		"####" A 0 A_SpawnItemEx("UFONuke", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERPOINTERS|SXF_NOCHECKPOSITION);
		"####" A 0 A_SpawnItemEx("UFOSmokePillar", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERPOINTERS);
		"####" A 1 A_SpawnItemEx("UFOSmokePillar", 0, 0, -512, 0, 0, 0, 0, SXF_TRANSFERPOINTERS);
		"####" A 10;
		"####" A 1 A_FadeOut(0.0001);
		Stop;
	}
}`

It's mostly these things:

- UFONuke
- UfoSmokePillar
- Debris_*****

**Comment by Tormentor667** [comment]
Just tried the latest version - the explosion is completely without any effects. No smoke, no fire. This is critical.

**Comment by Tormentor667** [comment]
Duplicate: https://github.com/Realm667/WolfenDoom/issues/986
