### ISSUE TITLE
[3.1] Are all addons compatible with 3.1?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#873]
I tried all addons at their current state and this is what I got so far:

**addon_behaviour**

> Script error, "behaviour.pk3:scripts/mutant.zs" line 23:
Unknown class name 'EnemyStep' of type 'Actor'
Script error, "behaviour.pk3:scripts/mutant.zs" line 32:
Unknown class name 'EnemyStep' of type 'Actor'

**addon_score**

> Script error, "score.pk3:scripts/scorehandler.zs" line 112:
Cannot convert SInt4 to Struct<Vector2>
Script error, "score.pk3:scripts/scorehandler.zs" line 112:
right is not a member of DrawToHUD

**addon_vampire**

> vampire.pk3:scripts/statusbar.zs, line 95: Function DrawMainBar attempts to override parent function without 'override' qualifier

Everything else at least launches without an error message. I didn't try if they worked though.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 The https://github.com/Realm667/boa-addons repository contains versions which were fixed by me (except vampire.pk3 which has an UI bug and I do not know how to fix it reliably).

**Comment by Tormentor667** [comment]
I'd point @AFADoomer towards this here then.

**Comment by AFADoomer** [comment]
I don't appear to have write permissions to that repository...

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Please give Realm667 team write access to boa-addons, here are the instructions: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/managing-team-access-to-an-organization-repository

**Comment by Tormentor667** [comment]
Should be writable for all of us now.

**Comment by Username-N00b-is-not-available** [comment]
I wonder if we should distribute the addons bundled in one archive with the pk3 and engine, or separately. The addons folder is more than 100MB now.

**Comment by Tormentor667** [comment]
I'd include them. 100MB more or less doesn't matter anymore if you have already 1GB :)

**Comment by Username-N00b-is-not-available** [comment]
BTW you wanted to complete the MIDI pack, please don't forget it :-)

**Comment by Tormentor667** [comment]
I am still at it, currently looking for some more musics from classic Apogee and id games that might fit but I am missing sources for the remaining 28 tracks :)

**Comment by MuadDib90** [comment]
> 
> 
> I am still at it, currently looking for some more musics from classic Apogee and id games that might fit but I am missing sources for the remaining 28 tracks :)

Will you include also E1M1 OST of Doom 1? 😄

**Comment by Tormentor667** [comment]
Well, that's too obvious :D I would like to have more music from older id/Apogee games :)

**Comment by MuadDib90** [comment]
Weeeeell... it is. But also iconic, isn't it. 😄

**Comment by Tormentor667** [comment]
Definitely :D

**Comment by Tormentor667** [comment]
Just finished german translations and also uploaded the final data to my 8bit music addon.

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 @Tormentor667 Could you test the addons, please? I could easily have missed some problems with them, and they might also need some balancing.

**Comment by MuadDib90** [comment]
> 
> 
> @MuadDib90 @Tormentor667 Could you test the addons, please? I could easily have missed some problems with them, and they might also need some balancing.

Sure, no problem. But I'd like to finish testing of achievements, which is nearly done. (Unless it is urgent).

**Comment by Tormentor667** [comment]
Yes I can do that today

**Comment by MuadDib90** [comment]
Ugh... where do I get the addons, please?

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 You can build the addons via the command file in the main folder of the repository, then it is needed to drag the generated files (the ```addons``` folder and various ```.boa``` files) into BoA's folder. To launch these quickly, use the new launcher (for example, just the newest demo: https://github.com/mgrinzPlayer/BoaLauncher/releases/tag/demo14), there will be some buttons for these.

**Comment by Tormentor667** [comment]
Just did some tests, this is what I can say:

- 8bit Music works for me (maybe needs loudness adjusments on some tracks but that's minor)
- Grenades Only works for me (it's fun btw :))
- InstaGib works for me (very hard but interesting gameplay change)
- More Weapons works for me (at least the weapons themselves, it's a nice addition)
- Movement works for me (at least technically, not sure how much fun it is to actually play all of the game that way)
- Score works for me (already made suggestions though)
- Vampire works for me (and is fun, but hard on some places, where you have to backtrack)

Didn't test the other ones.

**Comment by MuadDib90** [comment]
Finally got a chance to test it, after I run it technically with a help of @mgrinzPlayer. (To whom I thanks.) 

So this is my outcome @Username-N00b-is-not-available:
- The best and most fun addon - for me - was "grenades only". I can imagine to play the whole game with this one. Only obstacle is the end, where you are "corned", because you have to use blade of agony to kill all ending bosses - the blade you do have not.
- Low-res addon did not worked for me.
- M2HB addon did a VM abort for me (I even could not end it normally and had to use a Task Manager):
<details>
  <summary>Pic</summary>

![IMG_6964](https://user-images.githubusercontent.com/73436978/124363403-50b2ac00-dc3b-11eb-8f27-7925778041c2.JPG)
</details>

- Movement - did I sense right, that when nothing holding, you could walk faster than normaly, because of the scale to how slow you have to walk when all in backpack?
- Everything else was all right.

**Comment by Tormentor667** [comment]
>     * Low-res addon did not worked for me.

What is not working?

**Comment by MuadDib90** [comment]
> 
> 
> > ```
> > * Low-res addon did not worked for me.
> > ```
> 
> What is not working?

No low-res textures... if applied, they are exactly the same as without the addon. Can I do something wrong?

**Comment by MuadDib90** [comment]
[C2M6_C] - nearly a soflock

Here is an example of part, where you have to break that thing with a grenade, like literaly throw a grenade "at it", so the impact of the throw will "hurt" the device until completely destroyed.

The question is, why a blast itself from a grenade won't break it?
If a thrown grenade didn't have an impact damage, this would be a soft lock.
<details>
<summary>pic</summary>

![02](https://user-images.githubusercontent.com/73436978/124743882-78955e80-df1e-11eb-855b-2a94e3051fd0.PNG)
</details>

**Comment by MuadDib90** [comment]
Also, if you try to load a game with a different (sets of) addon(s), it won't, which is good. But it causes a VM abort. Shouldn't we add some sort of message instead of it?
