### ISSUE TITLE
[3.1] [C3M6_B] If Hitler gets hit immediately, he doesn't appear

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#877]
As the title says, I have noticed and posted on FB team chat [this video at minute 7](https://youtu.be/pOXP2a5fuYQ), done 3 weeks ago, presumably from C3 original release file. Well, while I am not sure if this has been fixed already, I am going to edit lines surrounding Hitler to block projectiles as well then.
Actual state of the zone, before my imminent commit, blocks only players:
![image](https://user-images.githubusercontent.com/11136108/122771555-d717d700-d2a6-11eb-80da-794514990897.png)

Fix attempt:
![image](https://user-images.githubusercontent.com/11136108/122772182-6624ef00-d2a7-11eb-99c2-b41adb4e84ba.png)
![image](https://user-images.githubusercontent.com/11136108/122772231-7210b100-d2a7-11eb-9a03-9bc194c21c7e.png)

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 Have you been able to reproduce the issue on current commits?
There was also this commit https://github.com/Realm667/WolfenDoom/commit/367ca663a498824a405f46720cebe794bbe83184 that added every-tic alpha checks, so the problem should not happen again.

**Comment by AFADoomer** [comment]
This should not happen in current build.  Shooting him early could cause a jump to the pain state,skipping all of the old state-based fade-in logic.  That really can't happen now that the fade-in is handle in the Tick function.

**Comment by Tormentor667** [comment]
@Ozymandias81 can you retry with the latest build and confirm?

**Comment by Ozymandias81** [comment]
Let's see, will cheat from ipk3 rebuilt.
