### ISSUE TITLE
[C1M2] Steurung door only opens on one half.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#878]
When flipping a switch to gain access to the scientist-filled room with another switch, only the left side of the door opens properly; the right-hand side remains frozen in place.

![Screenshot_2021-06-21-10-46-18-624_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/122846966-8e731480-d2cc-11eb-94e1-039839821f0a.jpg)

![Screenshot_2021-06-21-10-46-27-761_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/122846988-9c289a00-d2cc-11eb-94de-d28af62afd0e.jpg)

**Comment by Username-N00b-is-not-available** [comment]
I think it is nice to see something broken in the enemy mechanisms, it reminds you that they are prone to failures too. (If these were wooden doors rather than mechanical gates, this issue definitely should have been fixed.)

**Comment by Ozymandias81** [comment]
I remember that door opened only from that side, but I might be wrong.

**Comment by Username-N00b-is-not-available** [comment]
Yes, and for quite a long time. As seen in a random video from 2016: https://youtu.be/X1umkeAZz3w?t=1560

**Comment by Ozymandias81** [comment]
Then it is intended.

**Comment by Tormentor667** [comment]
It actually was inteded. I will just a spark spawner to make it more obvious that it is damaged.
