### ISSUE TITLE
[C1M1] Rock near the very first gate can be clipped through.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#879]
A rock to the right of the very first gate can be jumped and clipped through.

![Screenshot_2021-06-21-10-27-20-811_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/122847299-09d4c600-d2cd-11eb-8cbf-15b72cd1aa06.jpg)
![Screenshot_2021-06-21-10-27-30-435_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/122847337-19eca580-d2cd-11eb-8a2d-d61a3c248921.jpg)

**Comment by Tormentor667** [comment]
Found it but if possible please use "idmypos = TRUE" so we know where to look :)

**Comment by x3003** [comment]
Yes, this one can be clipped through.

![Screenshot_Doom_20210622_220334](https://user-images.githubusercontent.com/77861029/122991865-cef29100-d3a5-11eb-8b96-e8ee021e37b5.png)
