### ISSUE TITLE
C2M5_B ... another train issue ... maybe

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#880]
C2M5_B ...

With the release version, I noticed a visual glitch when at sector 2919 and looking towards line 9571. Now looking at line 9571 it can be seen that its sidedefs are associated with the wrong sector. It should be sector 2453, not 2297. While the issue did not show itself with the latest map, it still might be worth addressing.

**Comment by Tormentor667** [comment]
I've taken a look at the map but I can't adress the issue as some index numbers seem to have changed after the map has been edited since the release version. If you can reproduce this with the current version, please reopen this issue here.
