### ISSUE TITLE
HQ issues ?

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#881]
HQ ...

a) I've noticed that some times, depending on end/start of a mission, that access to the Mess Hall's stage is either accessible or not accessible. Can the performers stage always be accessible ?
b) I have returned 4 mayan artifacts to Gutenburg, yet mission summary shows 3.
Apologies if these have already been addressed.

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3 For b), which version are you playing (what date approximately)? This was reported in #723, and fixes were done, so it is sad if the problem does happen in newer builds.

**Comment by Ozymandias81** [comment]
Regarding a), it mustn't since the singer may not appear and we shoudldn't disturb the performance anyway :tongue:

**Comment by Username-N00b-is-not-available** [comment]
Well, then it may be time to close. @hawkwind3, if b) happened on a version after Jun 1, please tell us about it here.

**Comment by hawkwind3** [comment]
b) Is with the release version, so may have since been fixed ?

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3 Yes, in #723 Talon1024 said that he had fixed it. Thank you for clarifying!

**Comment by hawkwind3** [comment]
Regarding the Mess Hall stage, is it possible that it can be accessed when the singer is not performing only ?
