### ISSUE TITLE
scuba gear missing

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#884]
with the latest git version, in c1m2, the scuba gear seems missing. Only a small healthpack is / was here instead.

![Screenshot_Doom_20210625_005029](https://user-images.githubusercontent.com/77861029/123342364-ea999b00-d54f-11eb-98f6-7b239eec952a.png)

With an older build from 5 days ago, it was still there.

![Screenshot_Doom_20210625_005710](https://user-images.githubusercontent.com/77861029/123342641-6eec1e00-d550-11eb-80a4-9496d07742bd.png)

**Comment by AFADoomer** [comment]
It was moved elsewhere.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 This means @Tormentor667 has done a good job of hiding it now :-)
Hint: inspect the room with the large conveyor which transports crates more carefully.

**Comment by x3003** [comment]
Atleast I found out that something was different compared to an older build ;)
