### ISSUE TITLE
[3.1] Disclaimer screen: wrong character (N with some diacritics) drawn in place of х (U+0445) in Russian.

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#886]
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/59409713/123402700-b1454780-d5b0-11eb-8521-ca626fb1e97a.png)

</details>

This is not actually an oversight in fonts: 
https://github.com/Realm667/WolfenDoom/blob/master/fonts/bigupper/0445.png
https://github.com/Realm667/WolfenDoom/blob/master/fonts/bigfont/0445.png
It has something to do with code, and could be related with one of the issues in #844 (search for ```HUD problems: words near line beginnings```).

**Comment by Tormentor667** [comment]
This is a job for @DoomJedi and @MuadDib90 :)

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 The fonts have the letters set right, as is indicated by links in the first post... It is likely code-related.

**Comment by MuadDib90** [comment]
I can do it, if it can by repaired by this way, but @Username-N00b-is-not-available says otherwise :)

**Comment by Tormentor667** [comment]
Oh excuses, my fault. But what needs to be updated then?

**Comment by MuadDib90** [comment]
I'd like to help, but don't know how.
@Username-N00b-is-not-available Noob?

**Comment by AFADoomer** [comment]
Does the character print correctly in other places?

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Yes, so it seems. Рас```х```ититель:
![image](https://user-images.githubusercontent.com/59409713/123478286-e8931300-d607-11eb-9a3d-692da144b4bc.png)

**Comment by AFADoomer** [comment]
Thanks.  What about anywhere else that it appears at the end of a word?

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer In fourth skill description there is an ```их```. The achievement in the down-left corner of the table (```Смотри под ноги```, with three skulls) has ```трёх```. First (Story) page of F1 has ```которых```. DEVC3M6_B comment has ```них```. BRIEFINGC1M2_2 has ```наших```. All of these are shown correctly...
As for BIGFONT occurances, I don't think there are any more of them. Changing a level name to something that would have ```х``` 's in word endings again does not trigger the bug:
![image](https://user-images.githubusercontent.com/59409713/123483809-04021c00-d610-11eb-856e-1afaa45f9162.png)

**Comment by AFADoomer** [comment]
This should be resolved in 97cec002c30ab0ff52765b6599953df02a392ef5.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer ```х``` in ```исторических``` indeed works properly, thanks, but the last line does not get shown anymore at all for some reason:
![image](https://user-images.githubusercontent.com/59409713/124029886-4b1c5280-d9fe-11eb-81fd-0ef68884e334.png)

**Comment by AFADoomer** [comment]
Fixed in 29a3820a14b9720edee174365c84b3655ec3fde8.
