### ISSUE TITLE
C2M6_C additional stuff

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#887]
C2M6_C ...

a) Door side issues at x 5764 y 27370, x 5987 y 27593.
b) This does not look right. Screenshot attached.
![gantry](https://user-images.githubusercontent.com/35204218/123499559-ff268200-d67a-11eb-9627-d2f46f689a55.jpg)
c) Can walk through street signs at x 11024 y 16843 and x 10852 y 14516 and x 10306 y 13048 and x 6631 y 8041.
d) Clipping issue. Screenshot attached.
![cable clipping](https://user-images.githubusercontent.com/35204218/123504321-cf3ba680-d69b-11eb-9c05-f50dfc836458.jpg)

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3
a) Fixed.
b) Moved the horisontal part downwards a bit.
c) Made them walkable + projectile shoot-through.
d) Made the wire go to another corner.
A commit is upcoming.

**Comment by hawkwind3** [comment]
Regarding b) I should have clarified. I was meaning that this gantry did not have a top and bottom, like most ( all ? ) other gantries. Now looks wrong for other reasons - the gap. If this gantry cannot have a top and bottom, might I suggest going back to the way it was, and aligning lines 12149, 12148, 12147 and 12150 instead.
