### ISSUE TITLE
HQ mission briefing for C3M1_A

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#888]
HQ mission briefing for C3M1_A

May have already been addressed but I noticed that no one was manning the projector. Intentional ? Are future C3 missions the same ? Just thought, there are other missions where projectors are used and I seem to recall no one was manning them either. Can be closed if deemed a non issue.

**Comment by x3003** [comment]
This is already fixed in the git version.

**Comment by hawkwind3** [comment]
:) So can be closed.
