### ISSUE TITLE
[C3M3_A] Additional stuff

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#890]
C3M3_A ...

Found with release version. May have since been fixed.

a) I believe one destroyed radio now stops recieving, but I found two radios. Do both cease reception on being destroyed ?
b) Some underwater mines clip into the ceiling around sector 1060.
c) Sign offset issue at line 4298 sidedef 8299.

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3
a) Fixed.
b) Lowered the rock floor near the golden items and placed the mines into it.
c) Fixed.

**Comment by hawkwind3** [comment]
I forgot to add these. Consider them ...
e) Door offset error at x 2444 y -4890
f) Toilet is rendering into the table at x 2115, y -5695.
