### ISSUE TITLE
Halftrack doesn't rotate, continues shooting in wrong direction

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#891]
In c1m2, at the end you can go around the halftrack. But when you do that, it's still firing forwards, which looks a bit silly.
Could someone make this halftrack rotate towards the player like the tanks in c3m1 ?

![Screenshot_Doom_20210626_132355](https://user-images.githubusercontent.com/77861029/123511630-a824ab00-d682-11eb-85b1-3eee90efd612.png)

**Comment by Ozymandias81** [comment]
The only way it should rotate would be by moving itself whole, mind you guys. Originally the model didn't had a cannon mounted, I added it after, if I remember correctly. Would be cool to have soldiers inside it too, but mmh spritewise could be  problem, unless we use some "sit" variants with rotations.

**Comment by Username-N00b-is-not-available** [comment]
It would indeed be a great feature (for 3.2 or later, of course)! I have been wishing for it for quite a long time (what is easily seen by the truck on CUTSCEN2). Maybe these could be 'attached' to the vehicles (SdKfz251; trucks, as drivers and passengers; tanks, as on-armor passengers) in a way similar to the toilet soldiers?

**Comment by Tormentor667** [comment]
The sprites "edgy" rotation would clash terribly with the smooth rotating models.

**Comment by Tormentor667** [comment]
Regarding the issue in general, why doesn't the tank head for you anyway?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 It was marked as +STANDSTILL. Removed it in https://github.com/Realm667/WolfenDoom/commit/a51f15245ea59301fc7ca57d99ea6c47304aca29, but this way it clips into slopes a bit when it tries to turn around... Maybe we could widen the flat sector around the tracks a bit and add monster-blocking lines so it does not happen?

> The sprites "edgy" rotation would clash terribly with the smooth rotating models.

I honestly doubt it, especially if the soldiers will not be able to walk inside the vehicles. But we can't know for sure until it gets implemented ;-)

**Comment by x3003** [comment]
It works pretty good.
