### ISSUE TITLE
[3.1] Include "epilepsy warning" disclaimer after the main disclaimer

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#892]
As I suggested it on FB chat a couple of days ago, while DoomJuan seemed okay with this addition, ime it would give BoA a proper fully professional appearance during game start, and we might add entries for it on language in case we must distinct it for every languages in BoA. Some details may be found on this [PS disclaimer](https://legaldoc.dl.playstation.net/ps3-eula/psn/u/u_health_en.html).

I think we should add only following lines:

> WARNING: PHOTOSENSITIVITY/EPILEPSY SEIZURES
A very small percentage of individuals may experience epileptic seizures or blackouts when exposed to certain light patterns or flashing lights. Exposure to certain patterns or backgrounds on a television screen or when playing video games may trigger epileptic seizures or blackouts in these individuals. These conditions may trigger previously undetected epileptic symptoms or seizures in persons who have no history of prior seizures or epilepsy. If you, or anyone in your family has an epileptic condition or has had seizures of any kind, consult your physician before playing.
> IMMEDIATELY DISCONTINUE use and consult your physician before resuming gameplay.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 I think they have a typo, the last part of the message makes more sense as

> IMMEDIATELY DISCONTINUE use and consult your physician before resuming **gameplay, if** you or your child experience any of the following health problems or symptoms: [...]

Maybe we can put the information on possible health problems in one line, separated by semicolons:

> dizziness; altered vision; eye or muscle twitches; loss of awareness; disorientation; seizures; any involuntary movement or convulsion

but possibly it is not necessary.

**Comment by Tormentor667** [comment]
If it is not a strict "must-have", I'd keep it out of the game.
