### ISSUE TITLE
[3.1] Add "AutoStomp" feature to 3.1 (toggable)

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#893]
According to https://github.com/Realm667/WolfenDoom/issues/396 I'd suggest activating the AutoStomp feature to the 3.1 release, turn it on by default but making it "toggable" if players want to deactivate it for various reasons.

**Comment by x3003** [comment]
If the rats leave me alone, I'll leave them alone. And for the rest, I can manage them w/o autostomp.

**Comment by AFADoomer** [comment]
See a2bc0b91bb97117ace95e12901e75ff3c018408b.

**Comment by Tormentor667** [comment]
Perfect, yet another (un)used feature :)
