### ISSUE TITLE
Weird line shown

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#894]
In the viewing room, there's a black distorted line shown. Comes from the right side of the 'screen'. The left side doesn't have it.

![Screenshot_Doom_20210626_234557](https://user-images.githubusercontent.com/77861029/123527287-822cf400-d6de-11eb-98fe-293b9bcc1d13.png)

![Screenshot_Doom_20210626_234926](https://user-images.githubusercontent.com/77861029/123527292-8a852f00-d6de-11eb-8c0e-01815bb03e78.png)

**Comment by Talon1024** [comment]
I think the issue is the "old video" texture not covering the full width of the line it's on.

**Comment by x3003** [comment]
It's fixed.
