### ISSUE TITLE
wrong color around ship

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#895]
In c1m3, this ship has some brown (sand ?) around it. Would be nice if it was the color of the water.

![Screenshot_Doom_20210626_235550](https://user-images.githubusercontent.com/77861029/123527345-e8197b80-d6de-11eb-9490-45c477f9a716.png)

![Screenshot_Doom_20210626_235616](https://user-images.githubusercontent.com/77861029/123527348-ebad0280-d6de-11eb-9bd7-85a986683d85.png)

**Comment by hawkwind3** [comment]
Just to add, that ship should be lower in the water.

**Comment by Ozymandias81** [comment]
The map is intended to be played with fog on, and some scripts are triggered at certain heights over the ship. This is a very minor thing and we could live with it as is. Right @Tormentor667 ?

**Comment by x3003** [comment]
You can't really play it w/ fog on, because the enemy sees you while you don't see them.
And i'm not the only one having problems w/ the fog, several ppl making vids also have this problem.

**Comment by hawkwind3** [comment]
I agree with x3003. I remember on my first playthrough that there was a mission where you had to snipe 4 tower guards to continue. With the fog on that map, they were impossible to see. On my second playthrough, I played with fog off, which I preferred. I believe if fog is off, and shows a bug, it should be fixed.

**Comment by AFADoomer** [comment]
If you decide to play the game in a way that is obviously not intended, that's not the mod's problem to fix...

**Comment by hawkwind3** [comment]
If this is the case, some instruction needs to be stated that fog must be on, or a way to not disable fog.

**Comment by Ozymandias81** [comment]
Fog is present even in Hexen and we don't need these kind of adjustments since actors may behave wrongly on some occasions, like on C3M2. Gonna close it, not necessary.

**Comment by Tormentor667** [comment]
At least I changed the line horizon floor texture so it looks a bit better ;)
