### ISSUE TITLE
C3M3_B further issues

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#896]
C3M3_B ...

a) Four door sides need fixing. The one at x 15873 y 9466, and the other one nearby. Also x 14909 y 11693 and x 15322 y 11686.
b) Texture clash at lines 7743, 8049 etc. 
c) [moved to #906 --N00b]

**Comment by Ozymandias81** [comment]
Fixed a), b) seems to be not present anymore
