### ISSUE TITLE
"Full settings"

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#898]
Can we please (at least for testing, until full release) turn all that options in options menu at start to show ALL at default, and not by clicking "show full options". What is worse, when you "go up", back to the game, you have to turn it off, so when you go again to the menu, you have to click on "show full options" again. It does not stay ON; why? Why? It is reeeeeeally frustrating for me.

Just disable that button and show all options. Can we please? I beg you on my knees... :relaxed:

**Comment by Tormentor667** [comment]
I think we can live with that until Friday 😅
