### ISSUE TITLE
[C3M4] - without gas mask nearly undoable

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#899]
This part here, when waiting to elevator, is nearly undoable without gas mask, if you have not enough medkits and using game glitches.
1. You have to wait to elevator to go down and the all the way up. Takes time.
2. Damage is so strong and quick, you stand no chance agains it.

Only way to do it is to stand on stairs, when waiting for elevator (using game glitch @Username-N00b-is-not-available  mentioned -- do not get hurt if your center of gravity is "in the air", not touching ground), and when already in elevator, pray you have many medkits to restore health until your up there out of elevator.

Idk what can be done. Maybe when in elevator already you do not get hurt anymore? @Tormentor667 
 
![02 without the gas mask, this part when waiting for an elevator is undoable  to much damage for a long time to get up; solution - when in elevator already, no damage anymore](https://user-images.githubusercontent.com/73436978/123541629-cd2e2200-d745-11eb-9527-0d55fe5a0e61.PNG)

**Comment by Tormentor667** [comment]
You are supposed to have the gasmask by that moment. If you have not, you need to go back and get it.

**Comment by MuadDib90** [comment]
Yes, I know; but this is in direct contradiction with achievement "1915". For which (as @Username-N00b-is-not-available said me) you must not pick it up at all and complete level, to achieve this one.

So we have to either change the rules to achieve "1915", or change it here. To be playable.

**Comment by x3003** [comment]
You must pick it up else you can't go outside.

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 An achievement might not at all be the intended way of playing the game.
It is definitely possible to get the achievement **on skill 0** without cheats and glitches, there are just a bit more than enough health supplies to survive five minutes under Zyklon (it is easy to acquire and maintain 200 health/200 armor just before Rastenburg) — I have done it myself on the first try (on skill 0, again — the damage is not so severe then). It would most probably be impossible on the default skill and certainly on Mein Leben, but nobody says you have to gain all these achievements on the highest skill level, the accomplished ones persist across sessions...
I do not think anything should be changed here (except fixing the glitch in the town I noticed and @MuadDib90 mentioned, of course).

**Comment by MuadDib90** [comment]
I have a feeling you do not understand me here. I am not talking about Rastenburg. Which is certainly doable without a gas mask even on Mein Leben (as I played it) - no objections here.

But that corridor, where you get the gas mask, and when exiting that part via an elevator showed in picture, without a gas mask you are getting pretty big damage per second even on skill 0. So big, that I had about 5 to 6 attempts until I finally got up the elevator with only 8 % of lives. (On skill 0, I note.)
And to be able to do it at all, I hadto stand on stairs before aformentioned elevator, to not get damage. Otherwise it is a 100 % undoable. 

So, what I am asking is only slight change. In that, that to achieve the achievement, you need to do not have mask from point  of going through that door you need a yellow key for. That is - from my point - that horrible change, and makes things easier. For players, and also for coders (to search for "best approarch").

Is my try to make it more clearer a success? :)

**Comment by Tormentor667** [comment]
That’s what I understood already before the explanation :) I think we could add some kind of backtracking possibilit to the cellar.

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 The solution you suggested won't be 'easy to coders', so in https://github.com/Realm667/WolfenDoom/commit/7eceb18f0d55da70ccdcbcdfcec488ed6e4076d4 I lowered the poison damage on the sectors near the elevator (selected on the screenshot) from 6 and 8 to 3, and from 3 to 2 in the rest of the damaging ones in the area (to the left of the selection):
![image](https://user-images.githubusercontent.com/59409713/123630762-924bed00-d81e-11eb-928b-1c28bcb4bc52.png)
Hopefully this makes this section easier without the mask. You'll have to use up some medikits anyway, but that's part of the price for the achievement :-)

**Comment by MuadDib90** [comment]
Yes, nice! Thank you for hearing me. That's all I wanted. Thank you. :)
