### ISSUE TITLE
[3.1] [Chapter 1 Intro] Music is absent from both the Typewriter and INTERMAP Intros.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#900]
For reasons unknown. the music from Douglas' typewriter handiwork and the intro to INTERMAP are completely absent. When you actually get into BJ's boots, the music plays normally.

**Comment by Tormentor667** [comment]
I noticed that as well, nothing has changed here though. The scripts work and I can run the music tracks through the console. But they are not playing through normal launch.

**Comment by Shockwave508** [comment]
Can confirm that the INTROMAP music works again. No dice on INTERMAP's intro, though.

**Comment by Username-N00b-is-not-available** [comment]
Here are the results of ```bind p "currentmusic; wait 1; [and so on in the same manner...] currentmusic; wait 1;"```
![image](https://user-images.githubusercontent.com/59409713/124117563-f4a02a00-da78-11eb-977d-e13e42654434.png)
It means that the proper track (INTINTRO or equivalently ```music/INTINTRO.ogg```) is switched on, then it is instantly switched off by _something from BoA itself_ (as NOMUSIC is not a 'standard' lump, it is added by BoA, and neither ```defaultmap``` or INTERMAP definitions contain NOMUSIC). NOMUSIC is not present in any source files as seen from GitHub search, and the map scripts do not seem to contain NOMUSIC except jukebox script 155.

**Comment by Tormentor667** [comment]
This is extremely strange… I mean, it worked before, what had happened here? Engine specific?

**Comment by Ozymandias81** [comment]
NOMUSIC.ogg is a real silent .ogg file and it is present in BoA afaik.
![image](https://user-images.githubusercontent.com/11136108/124384018-cd8f6580-dccf-11eb-8129-ecc34ded7da9.png)
![image](https://user-images.githubusercontent.com/11136108/124384054-f57ec900-dccf-11eb-8550-9218fe7e4214.png)

**Comment by Ozymandias81** [comment]
This line seems it is breaking something
![image](https://user-images.githubusercontent.com/11136108/124384310-d7659880-dcd0-11eb-8c52-309807290055.png)

**Comment by Tormentor667** [comment]
NOMUSIC is used to make the music stop in various cases and situations, it's there for a reason actually.

I noticied also if you directly warp to INTERMAP from the console, the startup version isn't working either. This is a critical bug, we need to find a solution before releasing 3.1 here.

**Comment by Ozymandias81** [comment]
Neither C2M1 works, but instead works on C3M1_A ... I think it could belong to Camera actors or Players, checking. For a moment I thought the issue was with this line on INTERMAP, but it is not the case.
![image](https://user-images.githubusercontent.com/11136108/124611572-dcae1900-de71-11eb-9938-66d3c16f21fa.png)

**Comment by Ozymandias81** [comment]
If CUTSCENE_START is set as ENTER script, we can hear the music for a second, then gets it is stopped... C2M1 has similar setup as on C3M1_A, but for some reasons it doesn't work.

**Comment by Ozymandias81** [comment]
FOUND IT! It comes from HideMap script, if I remove it, it works.

**Comment by Ozymandias81** [comment]
So might it belong to [this](https://github.com/coelckers/gzdoom/blob/e963010eea58de0c6d3b1c4a03e7271e5449c0cd/src/intermission/intermission.cpp#L937) @AFADoomer @Talon1024 @Username-N00b-is-not-available ? Since the ZScriptTools we have has [FState_InLevel](https://github.com/Realm667/WolfenDoom/blob/1c74225170c870c0cb558f42ced494e0732f8015/scripts/libraries/zstools.zs#L561) at the end... Not sure. But HideMap is the problem, that's 100% verified from me.

**Comment by AFADoomer** [comment]
We just have to move the HideMap(true) command to the line before the SetMusic command (maybe with a Delay(1) in between).

**Comment by AFADoomer** [comment]
Should be fully resolved in 582406e97c684030e602aacacbb874280baee4e8.

**Comment by Ozymandias81** [comment]
Not sure if it was needed for INTROMAP, since it was working even before, but that fixed properly the issue.

**Comment by Tormentor667** [comment]
Well done!
