### ISSUE TITLE
[Addon] Score Widget?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#901]
Currenty the "Score" addon shows a red number at the lower left corner. On the one hand, I'd suggest moving that to the upper left below the money, on the other hand I'd make it yellow instead of red. I always connect "score" with "golden numbers" but maybe it's just me :) And icon next to the number like for the cash would be cool as well.

**Comment by Tormentor667** [comment]
Ah before I forget it: Maybe an "onscreen" notice what goodie you got when reaching certain points would be cool either.

**Comment by AFADoomer** [comment]
Updated the score display in 914867404b666c81596a40f4c2fdb33037851c21.  

You get the same reward every 40000 points: 25 health, 64 ammo, and 100 gold.

**Comment by Tormentor667** [comment]
Can we turn this into a data list somewhere where we can adjust what you get each amount of points?

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer By the way, nothing is awarded after you get 40000 points for the first time.

**Comment by AFADoomer** [comment]
Externalized the rewards to the data file in latest commit.

**Comment by Tormentor667** [comment]
Very good, time to set the data file up :)
