### ISSUE TITLE
[Delta Touch][C1M2] Throwing a grenade into the prison's exit crashes the game.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#902]
When reaching the prison's exit with Ryan, throwing a grenade while enemies are pouring from said exit will crash the game. If no enemies are in that area, then everything's fine. Included screenshot shows the exact moment it crashed.
![Screenshot_2021-06-27-10-19-41-641_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/123551027-a1a33b80-d735-11eb-8c9f-eb3590d874fc.jpg)

**Comment by Ozymandias81** [comment]
Delta-Touch?

**Comment by Tormentor667** [comment]
Can anyone reproduce this in regular GZDoom?

**Comment by Ozymandias81** [comment]
Can't reproduce at least by cheating there with GZDOmm 4.6.0, but didn't test with strobelights being active.

**Comment by Tormentor667** [comment]
Same here. @Shockwave508 were you able to reproduce it?

**Comment by Tormentor667** [comment]
Just tested it with a full playthrough of C1M2, can't reproduce.
