### ISSUE TITLE
sparks flying off door

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#903]
In c1m2, there are sparks flying off this door, just if the door got shot all the time.

![Screenshot_Doom_20210627_221516](https://user-images.githubusercontent.com/77861029/123558525-017dfe80-d797-11eb-87fb-3160303c6021.png)

![Screenshot_Doom_20210627_221543](https://user-images.githubusercontent.com/77861029/123558526-0478ef00-d797-11eb-8f51-81379ceaba3e.png)

**Comment by hawkwind3** [comment]
I believe that relates to an earlier report as to why that door does not open. A faulty door. :) I'm guessing you are using the latest map. ... I may be wrong though ...

**Comment by Username-N00b-is-not-available** [comment]
Intended, see #878. The sparks have been added recently by @Tormentor667.

**Comment by x3003** [comment]
>Intended,

Ahhhhhhhhhhhhhh ;)
