### ISSUE TITLE
guards should be hidden

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#904]
In c1m2, maybe these guards could be hidden until the player opens the door ?
Now, it's not a surprise anymore.

![Screenshot_Doom_20210627_222617](https://user-images.githubusercontent.com/77861029/123558596-6afe0d00-d797-11eb-9ec2-9068dd423784.png)

**Comment by MuadDib90** [comment]
While I understand your point, if I think about it, it is just this one instance; no other case I can think of right now. So can we leave it as a "candy" for a player? :)

**Comment by Ozymandias81** [comment]
It has been practically always like this, so better keep things as they are. And I also second MuadDib90 phrase too.

**Comment by Tormentor667** [comment]
It was an easy fix so I did it.
