### ISSUE TITLE
C3M3_A additional stuff added to closed issue #890

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#905]
C3M3_A ...

d) Door offset error at x 2444 y -4890
e) Toilet is rendering into the table at x 2115, y -5695.

Restated here so as not to get "lost".

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3 You could have just posted it there in a separate message, we would have received the email notification anyway :-)
Will fix after some current work.

**Comment by Username-N00b-is-not-available** [comment]
Ah, so you did, and it was yesterday. Sorry :-)

**Comment by Username-N00b-is-not-available** [comment]
@hawkwind3 a) I don't see an error, must have already been fixed:
![image](https://user-images.githubusercontent.com/59409713/123636245-4a7c9400-d825-11eb-913c-89217bddc22f.png)
b) Moved it 16 map units towards east:
![image](https://user-images.githubusercontent.com/59409713/123636617-c080fb00-d825-11eb-9d52-51fcece98757.png)

**Comment by hawkwind3** [comment]
Wrong door in screenshot. I just now downloaded the current map and the door in question is fixed anyway ... case closed.

**Comment by Tormentor667** [comment]
> UPDATE ... Please see the vehicle model at x 4073 y 7207. I'm sure it didn't look like it does before.

Looks fine to me, can you do a new report if it is not working with the latest dev version please?

**Comment by hawkwind3** [comment]
@Tormentor ... Has been fixed as of closes issue # 907.
