### ISSUE TITLE
C3M3_A pics

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#907]
C3M3_A

Some pics ...
![car](https://user-images.githubusercontent.com/35204218/123749871-3efa9d00-d8f9-11eb-9ae1-4b1617803daf.jpg)
![sign 1](https://user-images.githubusercontent.com/35204218/123749890-4457e780-d8f9-11eb-8a52-b6faef21d1ac.jpg)
![sign 2](https://user-images.githubusercontent.com/35204218/123749903-491c9b80-d8f9-11eb-9279-dc0b3685c172.jpg)

Regarding the signs Ozymandias81 previously stated ...

> Mirrored tx will stay as is since that's a style choice, works good in game ime.

What do others think ? Looks wrong to me.

**Comment by Tormentor667** [comment]
I should be able to fix this in the next few days.

**Comment by Tormentor667** [comment]
Fixed the signs.
