### ISSUE TITLE
C1M1 U-Boat

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#908]
C1M1 ...

The U-Boat does not fully move away from the players view. Would look better if it did IMO.

**Comment by Username-N00b-is-not-available** [comment]
Extended the water sector to the south, now the submarine won't get stuck in line 203 so early.
![Screenshot_BoA_20210701_120515](https://user-images.githubusercontent.com/59409713/124098021-d29cac80-da64-11eb-9fe9-47f3fd648917.png)
Will commit and close the issue later.
