### ISSUE TITLE
[3.1] Fonts behave odd...

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#909]
There was some (similar?) problem with one letter in @Username-N00b-is-not-available's Russian language package.
Now (previously not - like couple commits ago) the board shows this:
![01 odd behavior](https://user-images.githubusercontent.com/73436978/123848557-277edc80-d918-11eb-8f82-837d7864837b.PNG)

Is it related to that issue @Username-N00b-is-not-available had and I can't find right now? @AFADoomer

**Comment by Username-N00b-is-not-available** [comment]
It was #886.
Seems very likely that it is related...

**Comment by Talon1024** [comment]
I can't tell what's going on here. However, here are the Unicode code points and binary numbers which represent these characters:

    >>> ord("á")
    225
    >>> bin(ord("á"))
    '0b11100001'
    >>> bin(ord("Ã"))
    '0b11000011'
    >>> ord("Ã")
    195

**Comment by AFADoomer** [comment]
Should be fixed after 9da715588df0e80516d7f97d32429da65fbd9c2d.

Basically, GZDoom's built-in string functions are only partially Unicode aware...

**Comment by MuadDib90** [comment]
> 
> 
> Should be fixed after [9da7155](https://github.com/Realm667/WolfenDoom/commit/9da715588df0e80516d7f97d32429da65fbd9c2d).
> 
> Basically, GZDoom's built-in string functions are only partially Unicode aware...

Yes, it is. Thank you.
