### ISSUE TITLE
[3.1] Developer comments significantly lower frame rate

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#911]
Dead serious: when a devcomment shows on screen, 35 FPS (I have it capped) drops to 27, sometimes even 24, and again becomes as normal when the comment disappears (you can test it easily on TEST_DLG, or INTERMAP, or C1M2, ...) Noticed when testing https://github.com/Realm667/WolfenDoom/commit/4eb07eb134868d2b07ddeca80eaef43e034c6adb (at first I thought it could be because of my changes, but then I reverted them locally and experienced exactly the same problem on older commit).
Does not seem to happen with other message types.

**Comment by x3003** [comment]
Just wanted to report something quite similar, so I post it here instead.
It's not only the devcomments, but also the comments from for example, Douglas.
In c1m1, the framerate drops from 130 to 50 (vsync off) and in the intermap from 80 to 40 or so.

![Screenshot_Doom_20210701_214543](https://user-images.githubusercontent.com/77861029/124182388-115b5280-dab7-11eb-8b47-fa3b972fb046.png)

![Screenshot_Doom_20210701_215028](https://user-images.githubusercontent.com/77861029/124182431-233cf580-dab7-11eb-822e-646edfcc6c65.png)

But it won't happen w/ these new achievement boxes.

![Screenshot_Doom_20210701_214801](https://user-images.githubusercontent.com/77861029/124182620-626b4680-dab7-11eb-8014-7d80ef8d95cd.png)

**Comment by Talon1024** [comment]
It seems like `BrokenString.BreakString` is being called in `DrawMessage()`, which is called every frame by MessageHandler's overridden `RenderOverlay()`.

**Comment by AFADoomer** [comment]
Ouch.  Didn't realize it had that much impact. I'll rework it to call once only...

**Comment by AFADoomer** [comment]
Should be better after 1c74225170c870c0cb558f42ced494e0732f8015.

**Comment by x3003** [comment]
This seems fine now.

**Comment by Ozymandias81** [comment]
So this is solved?
