### ISSUE TITLE
Wrong answer

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#912]
If you finished c1m2 (so before c1m3) and go upstairs to Ascher and use the use-key on him, he says the same thing as before the c1m2 mission (to get the mine detector).

![Screenshot_Doom_20210701_234431](https://user-images.githubusercontent.com/77861029/124193784-b7af5400-dac7-11eb-9d5d-134f250c053f.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 This has been as such for quite a long time. Do you have suggestions on what he should say before C1M3? I don't seem to have good ideas...

**Comment by MuadDib90** [comment]
The question is:
Do he has to necessarily say something, if he has no important info for you for the upcoming mission?
Just thinking...

**Comment by x3003** [comment]
>Do you have suggestions on what he should say before 

Maybe just something like, 'good luck BJ on your next mission, you'll need it'.

**Comment by Username-N00b-is-not-available** [comment]
No matter that he is Miller's aide-de-camp, Ascher has a (much) lower military rank than BJ, and does not seem to be his old friend from the start. This 'Good luck' would be overfamiliar from him...
Maybe we can remove the message before C1M3, could work too. @x3003, do you know any other instances of Ascher's messages carrying over to later missions? Maybe there are some in C2?

**Comment by x3003** [comment]
>do you know any other instances of Ascher's messages carrying over to later missions?

Currently not. Removing the message would be also fine.

**Comment by Username-N00b-is-not-available** [comment]
OK, I'll check myself and commit.

**Comment by Username-N00b-is-not-available** [comment]
Hmmm, when using the debug switch to change INTERMAP state to 'before C1M3', Ascher already has no message...

**Comment by x3003** [comment]
>Ascher already has no message...

That's weird. But I didn't use the debugscript, so the message from c1m2 was still not erased I guess.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Exactly, you are right.
Please never mind my previous comment, it was a problem of the debug switch. https://github.com/Realm667/WolfenDoom/commit/d176799b988b04910f0e6392d6e2b8166260123a removes the conversation from Ascher before C1M3.
