### ISSUE TITLE
[C1M3 - C3M2] Too much fog

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#914]
Maybe a bit less fog would be better. Here, I can't even see the bloody ship. And I'm right on top of it. So plz a little less....

![Screenshot_Doom_20210702_161746](https://user-images.githubusercontent.com/77861029/124294692-44a1ee00-db58-11eb-9128-e90ee1e10a52.png)

**Comment by hawkwind3** [comment]
I'm with ya... but don't hold your breath ...

**Comment by Ozymandias81** [comment]
Using 4.6.0, which is the target for imminent 3.1 release, looks as intended by mappers. The fog would simulate ime the fog-of-war typical in humid places like those, if we want interprete like that. Also you seem to have some brightness/sector light mode messed up in terms of default settings.

![Screenshot_BoA_20210703_172338](https://user-images.githubusercontent.com/11136108/124359197-37523580-dc24-11eb-9a85-f517b46d070a.png)
![Screenshot_BoA_20210703_172415](https://user-images.githubusercontent.com/11136108/124359207-3faa7080-dc24-11eb-8f7d-a07c7a42e782.png)
![Screenshot_BoA_20210703_172506](https://user-images.githubusercontent.com/11136108/124359214-45a05180-dc24-11eb-8e3b-4a8047e9b627.png)
![Screenshot_BoA_20210703_172512](https://user-images.githubusercontent.com/11136108/124359215-476a1500-dc24-11eb-91e9-828b0432462e.png)
![Screenshot_BoA_20210703_172531](https://user-images.githubusercontent.com/11136108/124359217-489b4200-dc24-11eb-8607-992997954124.png)
![Screenshot_BoA_20210703_172543](https://user-images.githubusercontent.com/11136108/124359220-4933d880-dc24-11eb-8cd1-56e998781d94.png)
![Screenshot_BoA_20210703_172615](https://user-images.githubusercontent.com/11136108/124359223-4a650580-dc24-11eb-8909-ee5ddd57936f.png)
![Screenshot_BoA_20210703_172712](https://user-images.githubusercontent.com/11136108/124359226-4afd9c00-dc24-11eb-9995-13e644e045a2.png)

**Comment by x3003** [comment]
I'm not the only one who have probs w/ the fog, some ytubers, like zikshadow (and others) also complain about it.
Always testing w/ the latest gzdoom, btw.

**Comment by Tormentor667** [comment]
I don’t get it why your screenshots look so overbright. @Ozymandias81’s Screenshots show how it is supposed to look like.

**Comment by hawkwind3** [comment]
In the options, go to Option Search, type in fog, and there are various fog modes, and whether fog forces fullbright or not. May or may not help.

**Comment by Tormentor667** [comment]
Did you change that setting by yourself?

**Comment by hawkwind3** [comment]
Yes. I had no help, honestly.

**Comment by Tormentor667** [comment]
Well, we can’t change map settings if people experiment with GZDoom settings at the same moment. I can only say here “play it as it is intended to be played” :(

**Comment by Ozymandias81** [comment]
These are default settings
![image](https://user-images.githubusercontent.com/11136108/124382393-81d8be00-dcc7-11eb-9389-1a132e61a510.png)
