### ISSUE TITLE
No treasure anymore

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#917]
In c1m4, you're given the underwater gear, but when you dive in the hole there's no treasure or anything else. So the gear is completely useless for this.

![Screenshot_Doom_20210702_175156](https://user-images.githubusercontent.com/77861029/124326819-68c8f380-db87-11eb-8215-81c6b96d1a1a.png)

**Comment by MuadDib90** [comment]
The first idea, that comes to mind... Are you far enough? The underwater cavern is in the shape of "?" of some sort, if I am remembering it right.
But if you are, well... it is a problem indeed.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 The layout of the secret has changed from previous versions. Hint: look up...
![Screenshot_BoA_20210703_121310](https://user-images.githubusercontent.com/59409713/124349534-2e4b6f00-dbf8-11eb-8004-72692cb9fb12.png)

**Comment by x3003** [comment]
>The layout of the secret has changed from previous versions

With divingglass on it's a bit harder too see were you need to go to now, so I took it off a bit.
But when you're not in the cave, you can get the message that you found a secret. Just hover above it.

![Screenshot_Doom_20210703_115740](https://user-images.githubusercontent.com/77861029/124350686-5a65f080-dbf6-11eb-978f-44910f41e8a2.png)

**Comment by MuadDib90** [comment]
Yes, you can. That's probably because of Doom legacy.
In vanilla Doom there was nothing like bridges and floors. So something like this could possible never happen.
But maybe it can be "repaired"...? @Username-N00b-is-not-available

**Comment by Tormentor667** [comment]
To be honest I have no idea how to fix something like that...
