### ISSUE TITLE
Can't complete all objectives

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#918]
With a recent git version playing c1m4, you can finish the level, but can't complete the last objective.

![Screenshot_Doom_20210702_175257](https://user-images.githubusercontent.com/77861029/124327008-b9d8e780-db87-11eb-9b90-1d6284be04ad.png)

![Screenshot_Doom_20210702_225307](https://user-images.githubusercontent.com/77861029/124327535-5a2f0c00-db88-11eb-90e6-00f7588abe10.png)

**Comment by MuadDib90** [comment]
My guess is, it is checked, when you "use" Douglas, so it is not seen. 
Maybe we can add a "line of sight", similary to that at the end of C3M4. If in some particular distance from Douglas or closer, the objective will check self. What do you say @AFADoomer?

**Comment by AFADoomer** [comment]
You can complete it...  The line that Douglas is standing on gets tagged to activate the script to complete it, but you won't cross that line unless you run around behind Douglas before using him.
