### ISSUE TITLE
C2M0_B minor

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#919]
C2M0_B ...

Applies to latest ...

The small triangular sectors, like sector 8997, could have the flag ... Not shown on textured automap.

**Comment by Ozymandias81** [comment]
Do you mean to make it show on map then?

**Comment by hawkwind3** [comment]
No. Just the opposite, for it not to show.

**Comment by Ozymandias81** [comment]
We'll keep as they are now, not important and also they give doors sectors a better look in map.

**Comment by hawkwind3** [comment]
Just to clarify ...

Currently, this is the case. I have used sector 8997 as an example ...

UDB currently ...

![UDB current sector 8997](https://user-images.githubusercontent.com/35204218/124409079-faed1980-dd8a-11eb-82d6-a7a765c494c0.jpg)

Currently in-game ...

![Sector 8997 before fix in-game](https://user-images.githubusercontent.com/35204218/124409139-16582480-dd8b-11eb-9c22-10c8d1a47f95.jpg)

UDB with fix ...

![UDB sector 8997 fix](https://user-images.githubusercontent.com/35204218/124409170-253ed700-dd8b-11eb-85ee-b1c705bbd5a3.jpg)

With fix in-game ...

![Sector 8997 after fix _ in-game](https://user-images.githubusercontent.com/35204218/124409211-37b91080-dd8b-11eb-919f-82d89b68a43f.jpg)


You be the judge as to what is better ...

**Comment by Tormentor667** [comment]
Agreed, looks better ingame!
