### ISSUE TITLE
C2M6_B: Kennkarte does not work

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#920]
If I try to show the officer the Kennkarte (passport), the game just says `P_StartScript: Unknown Script 0`.

**Comment by Tormentor667** [comment]
The actor should trigger a certain named script afaik, maybe that got broken.

I noticed that this sometimes happens in GZDB if you change flags that the named acs_executes get reset to normal scripts with scriot number 0.

**Comment by Ozymandias81** [comment]
The map from the C3 release had Kennkarte script triggered around the SSOfficer...
![image](https://user-images.githubusercontent.com/11136108/124382778-6bcbfd00-dcc9-11eb-81e0-7cbdb7ead227.png)

...and now it is like this. When changing specials over a line, sometimes UDB reset some entries, but I wonder if in this case it has been removed to avoid the old Kennkarte issue.
![image](https://user-images.githubusercontent.com/11136108/124382826-a2097c80-dcc9-11eb-9347-6be51426048a.png)
