### ISSUE TITLE
C2M6_B: misplaced door

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#921]
One of the doors in C2M6_B is misplaced, and doesn't cover the entire doorway. Here's a screenshot:
![Screenshot_Doom_20210704_061051](https://user-images.githubusercontent.com/6550500/124381143-e592c500-dc8e-11eb-9eca-25d521f92681.png)

**Comment by Ozymandias81** [comment]
Lol poyobj outside the map
![image](https://user-images.githubusercontent.com/11136108/124382863-cebd9400-dcc9-11eb-9630-c39411831e75.png)
