### ISSUE TITLE
Achievements are not being given

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#923]
I played the first mission w/ the latest git version (fresh start) just now, but at the end no achievements were given. Not during the map, not in the intermap. Are you sure these have been turned on ?

So here, I didn't got the 'Perfectionist' and in the intermap I should have had 'Stingy', 'Automatic Weapons' and/or 'Blast-resistant'
And while checking out #916 a few days ago  I didn't see the 'Liquid Death' either.

![Screenshot_Doom_20210704_160237](https://user-images.githubusercontent.com/77861029/124388781-a55e3180-dce4-11eb-8427-15f387daa9b5.png)

**Comment by Tormentor667** [comment]
Did you make a complete new install or at least clean previous sessions of achievements?

**Comment by AFADoomer** [comment]
Did you cheat at all?  God/noclip/buddha/give will reset progress on most of these.

**Comment by x3003** [comment]
? Did you cheat at all? God/noclip/buddha/give will reset progress on most of these.

Nope, just started from new. No previously loaded file either.

**Comment by AFADoomer** [comment]
I just did a from-scratch playthrough of C1M1 and got perfectionist after the last kill, and stingy with the ammo once INTERMAP loaded.

Did you also start from a fresh .ini file?  Or use boa_resetachievements in the console?  Otherwise achievements from previous playthroughs will not be awarded again.

I'm so, I'm not sure what is causing your problem.

**Comment by Ozymandias81** [comment]
This is the correct way to playtest BoA:

Download GZDoom stable build 4.6.0
Build the pk3 using the build.bat file present in the repository
Rename it as .ipk3
Drop it onto you newly created folder with GZDoom 4.6.0
Play
You can turn off shaders if you don't like them, but for playtesting reasons it is usually better to play the game as is
Do not use old saves, do not copy-paste your old .ini files over, just play it fresh.

**Comment by x3003** [comment]
Well, why am I asking ? I did got the perfectionist a few builds ago. And a few others as well, like the sharpshooter. Nothing has changed in the settings. The only thing that has changed is a newer build. Even with gzdoom v4.6 I didn't get it.

**Comment by AFADoomer** [comment]
What does your achievement summary board look like?  Are the achievements already showing as awarded?

**Comment by x3003** [comment]
You mean this board ? This is w/ today's git version on the middle level.

![Screenshot_Doom_20210706_223216](https://user-images.githubusercontent.com/77861029/124663212-1733a800-deaa-11eb-9282-d2d8e821eb3d.png)

**Comment by AFADoomer** [comment]
No, the achievements board...  'openmenu achievementsummary' in the console or use the bulletin board in the briefing room.

**Comment by x3003** [comment]
I found the board.... But it seems these are saved into the prefs file instead of the saved game file. So if you already have an achievement (perfectionist for example), you can't get it again on a next mission. So you never can get a perfect achievement (or anything else) for all missions. Hmmm.....

**Comment by AFADoomer** [comment]
They are only ever awarded once.

**Comment by x3003** [comment]
Ahhhhhh, I thought it was on every map (hint, hint...).
Plz put that somewhere when you release the game, else others might be also confused.

**Comment by Ozymandias81** [comment]
Not much, because achievements works like Steam ones, that you know once you get them, there is usually no turning back (unless you are playing Ion Fury, which has an achievements reset in game)

**Comment by x3003** [comment]
An achievement reset would be nice.... More hints ;)

**Comment by Ozymandias81** [comment]
There is :)

**Comment by Tormentor667** [comment]
Are these working now so far? We didn’t get any reports yet, or did we?

**Comment by x3003** [comment]
The achievements seems to work, only the confusing thing is/was that it wasn't clear you can get these only one time in the whole chapter. Which isn't much. So when i'm doing the very first level I already picked up 3 or 4 achievements. Can't get these then on the others....

**Comment by Ozymandias81** [comment]
It works like on Steam, again. There are a couple of achievements still present on issues which needs to be fixed or tested apparently.
