### ISSUE TITLE
C1M1 stuka

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#925]
C1M1 ....

A minor issue, but I was wondering if the Stuka model at the start of C1M1 could be 
slanted so its tail end/ small rear wheel would rest on the floor ?

**Comment by Tormentor667** [comment]
Can you share coords?

**Comment by hawkwind3** [comment]
I can do more than that.
It is T2 - Type 20135 at x-128 y -1632.
It is the plane BJ is facing right at the very start of the level.
Maybe nothing can be done, but I thought to mention anyway.

**Comment by Tormentor667** [comment]
Isn’t this a sprite Stuka?

**Comment by hawkwind3** [comment]
I'm surprised you ask that question. It definitely is a model. Start the map and nocliip to those coordinates.

**Comment by Ozymandias81** [comment]
There is no need to be surprised, originally there were sprite-based decorations for decorative planes. I am the one who added models, so in case you have doubts, tag me next time. Here we go:
![image](https://user-images.githubusercontent.com/11136108/124493767-4cf76480-ddb6-11eb-847b-be3ed4293c6a.png)
