### ISSUE TITLE
[C2M6_B] door misalignment

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#926]
![01](https://user-images.githubusercontent.com/73436978/124452884-19e9ac80-dd87-11eb-9b46-3ae448dc3231.PNG)
![02](https://user-images.githubusercontent.com/73436978/124452902-1e15ca00-dd87-11eb-96e5-20e055389850.PNG)

**Comment by Talon1024** [comment]
[Already fixed](https://github.com/Realm667/WolfenDoom/commit/6746a73a5862f8033191011367c969ffd54b3c48).

**Comment by MuadDib90** [comment]
Ah, OK.
