### ISSUE TITLE
Help & info pages

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#927]
Attempt to enter the third page causes VM abort.
Also first word (mostly) of every line is in different color.
(All no matter in what language...)
![01](https://user-images.githubusercontent.com/73436978/124703924-7f5aac00-def3-11eb-88b0-9ef71005029d.PNG)

**Comment by AFADoomer** [comment]
Possibly related to the BreakString replacements that @Username-N00b-is-not-available made...

**Comment by Ozymandias81** [comment]
Happens the same on GLESZDoom 4.6.0 on INTROMAP
![Screenshot_BoA_20210707_194858](https://user-images.githubusercontent.com/11136108/124808104-cdf16000-df5e-11eb-8bbe-0427d30a9b17.png)

**Comment by Tormentor667** [comment]
This is one of the critical things that need to be fixed before a 3.1 release…

**Comment by Ozymandias81** [comment]
Here you are where does the issue happen on Help&Info page
![Screenshot_BoA_20210708_185815](https://user-images.githubusercontent.com/11136108/124962100-816d5980-e01e-11eb-8350-a5be027687ef.png)

If I revert finale.zs editing lines as if they where before BreakString with BrokenLines, INTROMAP works fine.

**Comment by AFADoomer** [comment]
I'll fix these tonight...  Default color for the lines needs to be set in the BreakString call, and I need to update the returned Count value code slightly.

**Comment by Ozymandias81** [comment]
@AFADoomer I did that revert before reading your reply, is it good?

**Comment by AFADoomer** [comment]
This should be resolved as of 88e2c4918d76aa84899202a76dc77ef87ea474ff.

**Comment by MuadDib90** [comment]
> 
> 
> This should be resolved as of [88e2c49](https://github.com/Realm667/WolfenDoom/commit/88e2c4918d76aa84899202a76dc77ef87ea474ff).

Yes, it's workning now.

(Can we do also someting about those last sentences? They are aligned to the block, and for example 3 words accross the whole line is looking really weird. Should be aligned to the left.)

**Comment by Tormentor667** [comment]
> (Can we do also someting about those last sentences? They are aligned to the block, and for example 3 words accross the whole line is looking really weird. Should be aligned to the left.)

Can yo post a new issue for that?
