### ISSUE TITLE
[C2M5_B] - barrel displacement

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#928]
![01](https://user-images.githubusercontent.com/73436978/124776379-b0f96480-df3f-11eb-8710-3a984c772d3e.PNG)
![02](https://user-images.githubusercontent.com/73436978/124776392-b22a9180-df3f-11eb-8873-a4b869e9f112.PNG)

**Comment by Ozymandias81** [comment]
Again why ppl doesn't use my variants?

**Comment by Ozymandias81** [comment]
Use these ones mappers, next time.
![immagine_2021-07-07_202031](https://user-images.githubusercontent.com/11136108/124809768-caf76f00-df60-11eb-97ec-a3a147549344.png)
