### ISSUE TITLE
[C2M5_B] - Door won't open

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#929]
I think it was @x3003 who reported it some time ago, yet here it is again.
You go through all the facility, place all the bombs (which shouldn't affect this), circle the whole hangar, swith on the switch behind the stucked door, and the main door won't open...

![01](https://user-images.githubusercontent.com/73436978/124905834-b6f65080-dfe6-11eb-8b53-6e7f6c7cda7e.PNG)
![02](https://user-images.githubusercontent.com/73436978/124905837-b8277d80-dfe6-11eb-8ed0-2adfbb494d3f.PNG)

**Comment by Ozymandias81** [comment]
The map seems set properly
![image](https://user-images.githubusercontent.com/11136108/124946346-40ba1400-e00f-11eb-9dd8-00be918ccf73.png)
![image](https://user-images.githubusercontent.com/11136108/124946450-52032080-e00f-11eb-9108-f40e73dbc0ca.png)
![image](https://user-images.githubusercontent.com/11136108/124946543-66471d80-e00f-11eb-8e10-d6355d91fa72.png)
![Screenshot_Doom_20210708_171239](https://user-images.githubusercontent.com/11136108/124947182-e8374680-e00f-11eb-8bda-0aa6fcd64c56.png)

**Comment by x3003** [comment]
>I think it was @x3003 who reported it some time ago, yet here it is again.

No, that was on YT in a vid. When I played this map maybe a few weeks ago it was fine for me, I could access the mainroom w/o a problem.

**Comment by MuadDib90** [comment]
Aaaah, so this is my bad... sorry.
I intentionally omitted the passage where the mayan artefact is (starting at those spiral staircase in that deep shaft), but you have to go there; at least for the door switch. 🤦 aagrrhh
