### ISSUE TITLE
C3M3(on older version, may be fixed) - Can go through "mined" level boundary

### ISSUE THREAD

**Issue by devouredone** [Realm667/WolfenDoom#930]
![Screenshot_BoA_20210708_171042](https://user-images.githubusercontent.com/83967245/124936789-84ad1900-e00f-11eb-9680-dd51d04c89ba.png)
![Screenshot_BoA_20210708_171049](https://user-images.githubusercontent.com/83967245/124936795-85de4600-e00f-11eb-8abe-4de723a39ad7.png)

**Comment by devouredone** [comment]
Using fences here(was looking for secrets)

**Comment by Ozymandias81** [comment]
Hi @devouredone , it has been fixed long time ago, there are lines which blocks players
![image](https://user-images.githubusercontent.com/11136108/124938319-7d364180-e008-11eb-9df4-5410eb75d827.png)
