### ISSUE TITLE
Some settings

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#932]
It would be nice if the release version has these as default settings. Maybe they are already set like this, but when not plz consider these.

:x:  Motionblur to off. Nice effect, but can get slow.
> We want PPSHaders being active per default, you can always deactivate them in game. Soon it will be easy with new simplified options. --Ozy81
- [x] Crosshair to on. Lots of players seems to think that the weapon scope is were they should look. And then they miss a lot of shots. Maybe better turn it on ?
- [x] Switch weapon on pickup to off. Seen it quite a lot in vids that players pickup a weapon and then struggle to find the weapon they had previously chosen. This slows down the play a lot.

:x:  Autosave to never. A lot of ppl complain about the lagging. Part of which is caused by the autosave (seen it on many vids, look at the disk icon), which lowers the framerate by 40-80 fps or so. They then assume that the game lags, but it's **simply** the autosave which kicks in. Players can turn it on if they like, but most will save manually.
> Not possible to "never" since it is important to save map progressing wise for anyone playing BoA: maps are longer, each one require different approach and on certain situations it is important that a "checkpoint" is saved to not stress players at all. The stuttering question ends here, it is a very minor issue. It is set pre default now as "Script", so every line or object or event which trigger an Autosave still happens in game, and there are 20 slots total for them. --Ozy81

**Comment by DoomJedi** [comment]
Good list.
Autosave - donnow, has advantages too

**Comment by mgrinzPlayer** [comment]
saves are zipped JSON files. From what I see, it uses Deflate:Maximum.
![obraz](https://user-images.githubusercontent.com/9157726/124972948-3b6ac280-e02b-11eb-9ca6-cd25e790116e.png)
Can we force Deflate:Fastest ?

**Comment by AFADoomer** [comment]
Crosshair is on by default in DEFCVARS, as of a couple of weeks ago.

We can't control the save files...  that would be an engine feature request.

**Comment by mgrinzPlayer** [comment]
Maybe we can hex-edit hard-coded deflate preset?

**Comment by Tormentor667** [comment]
My suggestions:

- Motion blur on
- Crosshair on (already in)
- Autoswitch weapon on pickup on/off, I don't care
- Autosave engine specific

**Comment by mgrinzPlayer** [comment]
I hex-edited EXE, exactly this line:
https://github.com/coelckers/gzdoom/blob/4bcea0ab783c667940008a5cab6910b7a826f08c/src/common/engine/serializer.cpp#L745
(which calls this function https://github.com/coelckers/gzdoom/blob/4bcea0ab783c667940008a5cab6910b7a826f08c/libraries/zlib/deflate.c#L240)

and I forced it to level 1 instead of 8, and memLevel 1 instead of 9.

normal quicksave c2m1, made when you can control BJ, is about 550~560KB
hacked (level=1 and memLevel=1), is about 890~910KB and much quicker.

**Comment by Ozymandias81** [comment]
Regarding saves, this could cause some other side effects, and also even engines like Quakespasm, which are ultraoptimized, have microstutters when saving. I don't think it is worth the hassle, surely not for 3.1 at least. If it will be possible to have it merged on gzdoom itself, I guess we'll save it for 3.2.

**Comment by mgrinzPlayer** [comment]
I made those tests with boa.exe (gzdoom g4.6-pre-195). And those test were with only one .map.json.

> other side effects

from what I see, FSerializer::GetCompressedOutput is used only for:
info.json, globals.json and visited maps (FLevelLocals::SnapshotLevel)

I do not think it can break something...

**Comment by x3003** [comment]
>also even engines like Quakespasm, which are ultraoptimized, have microstutters when saving. 

This is not microstutter anymore. This is annoying for players. I know you wanna give them the best experience they can get, but when they always complain about lagging and atleast you can fix some of it, why not ?!

**Comment by mgrinzPlayer** [comment]
@x3003 which GZDoom version you are using? I could send you patched EXE for testing purposes.

For my old CPU:
>wmic cpu get name
Name
Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
```

I see there is fastcompression save takes about 50% of time compared to the max.compression.

**Comment by Ozymandias81** [comment]
Added mentioned settings by @Tormentor667 on [this commit](https://github.com/Realm667/WolfenDoom/commit/fa8dc708932a4d314c1e6b441030d28fef14b4d9)

**Comment by x3003** [comment]
>I could send you patched EXE for testing purposes.

Nice, but today I don't have anymore time (tomorrow maybe). And the release was today ?

**Comment by mgrinzPlayer** [comment]
Just for testing puposes. It could still be something bigger than microstutter for you.

On my machine Max.Compression save takes 1.5 - 2.0 seconds, and Fast.Compression save still takes 0.6 - 1.0 seconds.

**Comment by x3003** [comment]
>  It could still be something bigger than microstutter for you.

Oh, it's not for me, as I don't use autosave. But a lot of YT-ers (and other as well) have problems w/ it and they complain about it, thinking the game lags, which technically it is, but it's basically they don't understand that the lag they have (on some parts of the maps) is actually the autosave which kicks in.
But the saving mechanism **does** take a lot of fps in general.

**Comment by Ozymandias81** [comment]
We were talking about the autosave/save mechanics instead , and an icon appear on top-right corner of the screen as well when that happens. The stutters you have might be related to something completely different, such as Win10 screwy updates, ssd/hdd issues, apps in background, engine limits that may not be good for you, or something else that I can't think atm.
Read this old [reply](https://github.com/Realm667/WolfenDoom/issues/565#issuecomment-831414071) from a similar issue.

**Comment by mgrinzPlayer** [comment]
> Oh, it's not for me, as I don't use autosave

autosave, quicksave, save from menu, ... , all of them use FSerializer::GetCompressedOutput. I just wanted to test my idea; I do not have other machines with better CPU. If there's no significant improvement then I could already scrap the "Fast.Compression Save" idea.

For me while saving, whatever auto, quick,  ... , it freezes the game for 1.5 - 2.0 seconds.

You wrote
> seen it on many vids, look at the disk icon), which lowers the framerate by 40-80 fps or so

I was curious how "Fast.Compression Save" will work on modern machines, maybe it would be 20-40 fps drop, or 10-20 fps drop...

**Comment by Ozymandias81** [comment]
Well youtubers use stream apps, Discord and Twitch maybe in background, maybe even Steam, and god knows which other apps. Indeed improvements are always welcome, but last word comes from @Tormentor667 .

**Comment by mgrinzPlayer** [comment]
OK. Maybe we should not use "hex-edit" patches on GZDoom.exe. It is already difficult to stay away from false-positive alarms.

**Comment by x3003** [comment]
>Well youtubers use stream apps,

Could be, but that's my simple observation. When they complain about lagging **AND** you see the disk icon onscreen, the game is autosaving. I can't say anything about the ppl saying it on the forum, but I bet they have some similar problem.
I see that's it's been sort of dealt with as the option is set as 'script only'. So that's a good thing.

But it would be nice for testing purposes only to check out that hex edited version anyway.

**Comment by Tormentor667** [comment]
> I hex-edited EXE, exactly this line:
> https://github.com/coelckers/gzdoom/blob/4bcea0ab783c667940008a5cab6910b7a826f08c/src/common/engine/serializer.cpp#L745
> (which calls this function https://github.com/coelckers/gzdoom/blob/4bcea0ab783c667940008a5cab6910b7a826f08c/libraries/zlib/deflate.c#L240)
> 
> and I forced it to level 1 instead of 8, and memLevel 1 instead of 9.
> 
> normal quicksave c2m1, made when you can control BJ, is about 550-560KB
> hacked (level=1 and memLevel=1), is about 890-910KB and much quicker.

I think the approach in general is a good idea but we most propably should suggest this to be an official engine feature of GZDoom. What do the developers of the engine need to know to add something like that? Afterwards we could make suggestions to Blade of Agony (devcvars or whatever) to set things exactly the way we need it. What to you think?

**Comment by x3003** [comment]
Another thing is that I was under the impression that vulkan was chosen as default, but now it seems the 3.1 version has opengl as default. Why the change ?

**Comment by mgrinzPlayer** [comment]
Savegame are written in human readable format (JSON) and then compressed. I think, for debugging JSON files are great.
Whatever **save_formatted** cvar is true or false, it takes time. It would be great if they implement not-text-based savegame format.

**Comment by Tormentor667** [comment]
> 
> 
> Another thing is that I was under the impression that vulkan was chosen as default, but now it seems the 3.1 version has opengl as default. Why the change ?

Afaik this was reverted because not every system is Vulkan-friendly, but I am not sure.

**Comment by Ozymandias81** [comment]
Yes because of that, we had a discussion on ZDForums with Nash as well saying that it wasn't smart doing that move. Also I had to revert the NeverSwitchOnPickup since there are situations in game that's fundamental to have a weapon in hand without selecting it, since players may not be aware (Training Session on HQ has now scripts which forces them because of that, but there are surely some other situations that could be an issue - C2M1 and C3M1 comes in mind, probably Tanks and Truck as well and a couple more that are not script)
