### ISSUE TITLE
Unable to launch (v3.1) due to script error

### ISSUE THREAD

**Issue by l00pu5** [Realm667/WolfenDoom#934]
Error message:
Script error, "boa.ipk3:defcvars.txt" line 13:
Cannot set cvar default for non-config cvar 'gl_texture_hqresize_fonts'

![image](https://user-images.githubusercontent.com/26188377/125136359-fa49df80-e10a-11eb-97f4-84c1d73362b8.png)

**Comment by Ozymandias81** [comment]
Just download again now, link has been fixed.

**Comment by Talon1024** [comment]
I updated the v3.1 tag again for the Snap and Flatpak builds
