### ISSUE TITLE
[3.2] Color/name indicators for player sprites in multiplayer games

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#936]
To distinguish between different players in an online cooperative match, I think it would be good to add some kind of colored indicators or displaying the player names over the sprites instead of creating "colorizable" sprite sets for every single variant we have.

One thing I can imagine is something like this from Batman TC (where the green pointer is changing it's color according to the player color). Another thing would be the player name over the head of the player sprite, also colored according to the player color).

![PLAYA2A8](https://user-images.githubusercontent.com/10298439/125155669-b930ea00-e161-11eb-9dd1-f6b48ed89a1a.png)

Would something like that be doable? I think it's the most elegant way and with less effort doable.

**Comment by Ozymandias81** [comment]
Ah I am familiar with that, you know :tongue:  and those have been implemented for easy skin distinguishable players yes... Maybe we can use the method applied for interactive things, but over players and with translatable graphic indicator for the purpose, just for a simple approach to the problem ( I say simple but dk how to do that zscript wise XD ) ?

**Comment by AFADoomer** [comment]
Should be easy enough to add...  The same coordinate translation code that we already use for the minesweeper and a couple of other miscellaneous things can be used.

**Comment by AFADoomer** [comment]
These are essentially done after d5de6905b08865a1c4683081da4b1b02d33272c4.  Feedback?

**Comment by Tormentor667** [comment]
I am currently at vacation and will be back on 9th of August, I will check this then with my girlfriend. Pretty sure she is looking forward to a coop session. Not. :)

**Comment by AFADoomer** [comment]
Here's a preview shot:
![Screenshot_BoA_20210724_111043](https://user-images.githubusercontent.com/16618820/126874516-9d67bccd-8672-4387-a93b-78c20a2900b9.png)

**Comment by Tormentor667** [comment]
Not bad but maybe you can use this as pointer? (attached hires, so it is easier for you to lowres it - psd is also available if you need it)
<img width="128" alt="pointer" src="https://user-images.githubusercontent.com/10298439/131261793-75d02967-6166-47fa-ae57-b32773e525c9.png">

**Comment by AFADoomer** [comment]
Can you get me the .psd?  I'll need to pull the background out as a couple of image layers so that the color translation will work properly and not change the shade color of the circular border also.

**Comment by Tormentor667** [comment]
Sure, here it is, let me know if you need anything else.

[pointer.zip](https://github.com/Realm667/WolfenDoom/files/7085775/pointer.zip)

**Comment by Tormentor667** [comment]
Were you able to work with the psd file @AFADoomer or is there anything I can help with?
