### ISSUE TITLE
[3.2] Indicating the direction of 1-directional boss monsters

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#937]
For the multiplayer cooperative variant of Blade of Agony we need to find some way of telling the player where the 1-directional bosses are facing. Creating 8-directional enemies from all bosses that we have is simply out of scope so this is a total no-go.

What I though about is some kind of visual overlay maybe that shows the player in which direction the 1-directional boss enemy is facing, something like this maybe.

Enemy facing you:
![grafik](https://user-images.githubusercontent.com/10298439/125155805-7f141800-e162-11eb-8e36-57cb9461da99.png)

Enemy facing left/right:
![grafik](https://user-images.githubusercontent.com/10298439/125155835-981cc900-e162-11eb-95f0-33cb7543bddf.png)

Enemy facing away:
![grafik](https://user-images.githubusercontent.com/10298439/125155863-b4206a80-e162-11eb-9b3a-21a1372a3bbb.png)

This is just a conceptual idea, I am sure it can be made even better :)

**Comment by DoomJedi** [comment]
Large but not totally out of scope project would be to create at least left-right diagonal head rotations for Bosses to indicate general direction of movement.

**Comment by Tormentor667** [comment]
Can you give an example for left/right/back?

**Comment by Tormentor667** [comment]
@AFADoomer I‘d suggest sticking to overlay indicators, can you try to implement something like that? I can do a multiplayer testing next weekend so this would help a lot  :)

**Comment by Tormentor667** [comment]
@AFADoomer sorry for pushing this but this actually the only _big thing_ that is preventing me from doing any official coop beta testings. Do you think you might be able to implement something like that? Or maybe even something better?

**Comment by Tormentor667** [comment]
@Talon1024 I like it as it is now. Anything you consider which needs to be fixed? The only aesthetic thing that I'd change woould be to make the movement of the arrow smooth (interpolating the direction as it changes), is this possible?

**Comment by AFADoomer** [comment]
I added angle interpolation to the base actor for the indicators in 43a0d4a00e6d4ccf76df20da6333d4e6a2cb12e1, as well as adding handling to (optionally, but enable currently) offset the indicator arrow to be drawn "under" the actor's feet.

**Comment by Tormentor667** [comment]
Very cool, this improves the look a lot
