### ISSUE TITLE
VM execution aborted when using M2HB

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#938]
When you select M2HB from within the launcher the game starts, but when selecting a mission, the game fails with VM execution aborted.

![Screenshot_BoA_20210710_095557](https://user-images.githubusercontent.com/77861029/125156462-d8317b00-e165-11eb-9a2d-b767d39180b4.png)

**Comment by Tormentor667** [comment]
![grafik](https://user-images.githubusercontent.com/10298439/125162797-22c4ee80-e18a-11eb-983d-92e9757162da.png)
Works for me.

**Comment by x3003** [comment]
To make sure I didn't had anything in my config wrong, I (just now) unpacked the archive to a new dir, started the launcher and added M2HB. Then started c1m1 on the lowest level. I didn't changed **any** settings from gzdoom nor from the launcher. This gave me an error again.

![Screenshot_BoA_20210710_163147](https://user-images.githubusercontent.com/77861029/125166620-c919ef80-e19c-11eb-976f-33129dea3408.png)

**Comment by Tormentor667** [comment]
Yes, now I get it as well
![grafik](https://user-images.githubusercontent.com/10298439/125167019-9ffa5e80-e19e-11eb-9abb-5b6b79707152.png)

**Comment by AFADoomer** [comment]
What's the purpose of that line, anyway?  It's supposed to save the player's current weapon class (so throws a VM abort if the player has no current weapon), but the variable is never referenced again.  I think the whole line can be removed.

**Comment by Ozymandias81** [comment]
I'll check in a while.

**Comment by Ozymandias81** [comment]
Okay fixed on next commit.
