### ISSUE TITLE
Incompatible load/save

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#939]
When you start with grenades only (and save), and disable this addon later on before restart, you can't load the previously savefile. Gzdoom crashes.

![gzbad](https://user-images.githubusercontent.com/77861029/125157189-bc2fd880-e169-11eb-99ab-5d1b3b84da53.jpg)

![gzbad2](https://user-images.githubusercontent.com/77861029/125157191-bf2ac900-e169-11eb-8173-55a65c103223.jpg)

**Comment by alexey-lysiuk** [comment]
We cannot debug screenshots, so I guess the crash [was fixed](https://github.com/coelckers/gzdoom/commit/cf4c72d4a7403baf0cfda9daa422919c6b05f783) after 4.6.0.

As for the error message, it’s completely normal that you cannot load a saved game that contains unknown classes.
There is no way to make such setup to work reliably except to avoid serialization of classes defined by a mod.

**Comment by x3003** [comment]
>We cannot debug screenshots, 

But you can reproduce it with the steps given.

>so I guess the crash was fixed after 4.6.0

Maybe release w/ the latest version to avoid something like this ?!

>it’s completely normal that you cannot load a saved game that contains unknown classes.

I know, but it still shouldn't crash.

**Comment by alexey-lysiuk** [comment]
> But you can reproduce it with the steps given.

But you can post a complete crash report instead of useless screenshots.

> I know, but it still shouldn't crash.

OK, I would be explicit next time. Please test with the latest devbuild first, and there will be no need in such conversation.

**Comment by Tormentor667** [comment]
You can only load/save games with the same addons being loaded. It doesn't work if you save a game with an addon and load it again without it (or a different addon)

**Comment by x3003** [comment]
Yes, but you would expect that some add-ons didn't have such a big effect. Like the 'disable hints'. If you save it, remove this add-on and load you get many errors. But the only thing you do is to enable the hints. So you would think it's not a big deal. But it is apparently.

**Comment by Tormentor667** [comment]
This is unfortunately how the engine works, we can#t do anything about it.

**Comment by Ozymandias81** [comment]
Anyway it is stated that mod requires to start a [New Campaign](https://github.com/Realm667/boa-addons/blob/main/source/grenades_only/addoninfo.txt#L17)
