### ISSUE TITLE
[3.2] Help & info page(s)

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#941]
Can we do someting about those last sentences of each paragraphs? They are aligned to the block, and for example 3 words accross the whole line is looking really weird. Could be aligned to the left.

![01](https://user-images.githubusercontent.com/73436978/125185003-5b180b80-e222-11eb-9d28-85cfe44dd429.PNG)

**Comment by Tormentor667** [comment]
I’d point @AFADoomer towards this, making the final line of a text block left aligned here instead of justified.

**Comment by Tormentor667** [comment]
Summoning @AFADoomer and @Talon1024 , maybe one of them can solve the text block issues. It's only happening for page 1 and page 2 actually, not for the others. Maybe the new disclaimer text at the beginning has introduced this bug.

**Comment by AFADoomer** [comment]
Should be fixed in 228715540ad7ba70f4c584257f95b87c6532f0b5.

**Comment by MuadDib90** [comment]
Good, works perfectly; also in other languages. Thanks @AFADoomer.
Closing this.
