### ISSUE TITLE
Killing sharks leads to VM abort

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#942]
From ModDB:

When I kill a shark I get booted to the main menu and the console say "
VM execution aborted : tried to read from address zero.
called from FlatNumber.PostBeginPlay at boa.ipk3:scripts/actor/gatekeeper.zs, line 880"
what do I do?

**Comment by Talon1024** [comment]
I guess the person was using the "Score" addon, which spawns numbers to indicate how much points a player received for killing an enemy.
