### ISSUE TITLE
[3.2] [Launcher] Multiplayer

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#943]
@mgrinzPlayer there we go :)

**Comment by Tormentor667** [comment]
Summoning @mgrinzPlayer here, just to make sure he isn't missing the thing. For a proper multiplayer coop release we need the launcher to introduce additional options to let players host and join a multiplayer game.

What do you need to implement these functionality?

**Comment by mgrinzPlayer** [comment]
![obraz](https://user-images.githubusercontent.com/9157726/139599430-e128ef6d-1bd0-4af9-b893-59a288f07204.png)

translation msgids:
```po
#: unit1.rscoop
msgid "Co-op"
msgstr ""

#: unit1.rscoophostip
msgid "Hostname / IP:"
msgstr ""

#: unit1.rscoopjoining
msgid "Joining"
msgstr ""

#: unit1.rscoopplayers
msgid "Players:"
msgstr ""

#: unit1.rscoopport
msgid "Port:"
msgstr ""

#: unit1.rscoopstartmap
msgid "Starting map:"
msgstr ""
```

With settings seen in above screenshot it will execute boa.exe with those parameters:
`-iwad boa.ipk3 +set boa_devcomswitch 0 -join 192.168.31.128:5029`


For those settings:
![obraz](https://user-images.githubusercontent.com/9157726/139600590-39d20ed9-92de-48ba-9a1e-6c5847de8731.png)
it will execute boa.exe with those parameters:
`-iwad boa.ipk3 +set boa_devcomswitch 0 -host 5 -port 5029 +map C3INTRO`

**Comment by mgrinzPlayer** [comment]
Language check:

CS
```
#: unit1.rscoopskill
msgctxt "unit1.rscoopskill"
msgid "Skill:"
msgstr "Úroveň obtížnosti:"

#: unit1.rscoopskill_1
msgctxt "unit1.rscoopskill_1"
msgid "Warming-Up"
msgstr "Rozcvička"

#: unit1.rscoopskill_2
msgctxt "unit1.rscoopskill_2"
msgid "Morning Stroll"
msgstr "Ranní pochod"

#: unit1.rscoopskill_3
msgctxt "unit1.rscoopskill_3"
msgid "Ordinary"
msgstr "Obyčejná obtížnost"

#: unit1.rscoopskill_4
msgctxt "unit1.rscoopskill_4"
msgid "Blazkowicz"
msgstr "Blazkowicz"

#: unit1.rscoopskill_5
msgctxt "unit1.rscoopskill_5"
msgid "Mein Leben!"
msgstr "Mein Leben!"
```
DE
```
#: unit1.rscoopskill
msgctxt "unit1.rscoopskill"
msgid "Skill:"
msgstr "Schwierigkeitsgrad:"

#: unit1.rscoopskill_1
msgctxt "unit1.rscoopskill_1"
msgid "Warming-Up"
msgstr "Aufwärmen"

#: unit1.rscoopskill_2
msgctxt "unit1.rscoopskill_2"
msgid "Morning Stroll"
msgstr "Morgenspaziergang"

#: unit1.rscoopskill_3
msgctxt "unit1.rscoopskill_3"
msgid "Ordinary"
msgstr "Nichts Besonderes"

#: unit1.rscoopskill_4
msgctxt "unit1.rscoopskill_4"
msgid "Blazkowicz"
msgstr "Blazkowicz"

#: unit1.rscoopskill_5
msgctxt "unit1.rscoopskill_5"
msgid "Mein Leben!"
msgstr "Mein Leben!"
```
RU
```
#: unit1.rscoopskill
msgctxt "unit1.rscoopskill"
msgid "Skill:"
msgstr "Уровень сложности:"

#: unit1.rscoopskill_1
msgctxt "unit1.rscoopskill_1"
msgid "Warming-Up"
msgstr "Разминка"

#: unit1.rscoopskill_2
msgctxt "unit1.rscoopskill_2"
msgid "Morning Stroll"
msgstr "Утренняя прогулка"

#: unit1.rscoopskill_3
msgctxt "unit1.rscoopskill_3"
msgid "Ordinary"
msgstr "Как обычно"

#: unit1.rscoopskill_4
msgctxt "unit1.rscoopskill_4"
msgid "Blazkowicz"
msgstr "Blazkowicz"

#: unit1.rscoopskill_5
msgctxt "unit1.rscoopskill_5"
msgid "Mein Leben!"
msgstr "Mein Leben!"
```

**Comment by mgrinzPlayer** [comment]
latest version:
https://github.com/mgrinzPlayer/BoaLauncher/releases/download/Coop/Blade.of.Agony.Launcher.7z

**Comment by x3003** [comment]
This launcher has been build w/ gzdoom 4.6 in mind. The current state of boa **needs** 4.8, so this launcher doesn't work anymore w/ the latest builds. Can someone change it, so it launches w/ the latest versions ?

**Comment by mgrinzPlayer** [comment]
Did you rename "gzdoom.exe" to the "boa.exe"?

**Comment by x3003** [comment]
> Did you rename "gzdoom.exe" to the "boa.exe"?

Thx, you are right. I took the latest boa.ipk3 and put it in the v3.1 drawer not realizing that the launcher loads thru boa.exe instead of gzdoom.exe.

**Comment by mgrinzPlayer** [comment]
Just a reminder, the launcher is ready for simple hexedit modifications ("boa.exe"):
![obraz](https://user-images.githubusercontent.com/9157726/170885644-d40c5029-628a-485e-b937-bf398c5a7325.png)

e.g. for future BoA versions ("boa_directorscut.exe"):
![obraz](https://user-images.githubusercontent.com/9157726/170885722-9c4536d1-95f1-4d6f-a991-e806aa98a469.png)
