### ISSUE TITLE
Episode 3 - Sgt. Ascher's dead body

### ISSUE THREAD

**Issue by devouredone** [Realm667/WolfenDoom#945]
When finishing the last mission of Episode, i noticed that Ascher have at some point disappeared for me. i finished the game, come out of the castle, hear" hey, i am there, come over and find his dead body with exclamation mark"

**Comment by Ozymandias81** [comment]
Can you please detail it better?

**Comment by AFADoomer** [comment]
I think that the Ascher player follower somehow died, so when he was teleported for the finale bridge crossing, the corpse was all that was there.

**Comment by devouredone** [comment]
Indeed. While it is minor bugg as i could still finish the game, i was very confused at one moment when he said "ill be waiting" and then i could not see him until i got closer and realized i speak to a corpse:D

**Comment by Tormentor667** [comment]
Instead of placing the player-follower there, we could just spawn a static actor.

**Comment by MuadDib90** [comment]
> 
> 
> Indeed. While it is minor bugg as i could still finish the game, i was very confused at one moment when he said "ill be waiting" and then i could not see him until i got closer and realized i speak to a corpse:D

The Twist worthy of a Spec Ops-game like. :D
