### ISSUE TITLE
[3.2] [C1M2] Killing sharks causes me to be booted to the main menu

### ISSUE THREAD

**Issue by Mine60000** [Realm667/WolfenDoom#946]
I am using the "efficiency", "more weapons" and "score" addons.
This is what happens:

https://user-images.githubusercontent.com/87269543/125197966-dc28d000-e22d-11eb-9719-0fce5b094037.mp4

**Comment by x3003** [comment]
This should be a dup from #942 which is fixed already. Dunno if the fix already made it in the release version. Else you have to apply it yourself.

**Comment by Ozymandias81** [comment]
Yes it has been fixed already-
