### ISSUE TITLE
[3.2] Training course

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#947]
- [ ] I don't know from when, but with the latest commit if you leave a training course injured, Douglas makes his speach about visiting Bones to get health back, but you get it back instantly; making the visit and the message obsolete.

- [x] Also you can get hurt even by anything other than mines (e.g. panzeshreck), so the message about "live mines" is maybe misleading... can we change it?
@Tormentor667

**Comment by Tormentor667** [comment]
That indeed was obviously changed but should be reverted. 

Regarding the message, I'd keep it as is.

**Comment by Tormentor667** [comment]
> I don't know from when, but with the latest commit if you leave a training course injured, Douglas makes his speach about visiting Bones to get health back, but you get it back instantly; making the visit and the message obsolete.

This is working for me and there is no script that makes the player to be healed anywhere except by Halderman, so I think this can be closed as I wasn't able to reproduce it either.
