### ISSUE TITLE
doors close too late

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#949]
In c3m1_b, these doors should close when the player is in the room and the enemies should come at you. Now you can stand here and still nothing happens. Dunno when or why it was changed, coz it wasn't always like this.

![Screenshot_Doom_20210712_221305](https://user-images.githubusercontent.com/77861029/125361887-46488e80-e36e-11eb-9a91-729cc174da61.png)

**Comment by Ozymandias81** [comment]
As soon as you pick one object, it closes immediately. That's how it is meant to work. Before ppl complained that Boss was alerted too early.
