### ISSUE TITLE
[C3M6_B] castle map improvement

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#950]
@Tormentor667 
Probably a minor thing. But the map layout has changed, so maybe a slight change in the map you can buy can be made. The most significant change is transfer of one secret, and no marked other ones. Minor change was in that circled area layout. 
![10](https://user-images.githubusercontent.com/73436978/125583722-b0ce4bcb-2528-408e-8a88-f42ea2ddc81a.png)
On the other hand, if the inaccuracy of the map is desired (layout, secret positions ect.), then it is OK.

**Comment by Tormentor667** [comment]
Updated
