### ISSUE TITLE
[C3M0_A] - possible dead end

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#955]
![01](https://user-images.githubusercontent.com/73436978/125775316-c4993d1b-f456-4572-bde4-0375183b0cfa.PNG)
![02](https://user-images.githubusercontent.com/73436978/125775331-67cedb73-207c-493e-bdf0-9771972649dc.PNG)

You can jump to the shed's roof, and from there enter the zone behind the fence (I saw someone actually did that - I can confirm it by testing). If you do it before flooding that cave nearby, it is and dead end. Simple solution to this is to make invisible wall around the roof's edge, so you are not able to jump on it.

@Ozymandias81 and as usual "there is one barrel for you". 😃

**Comment by AFADoomer** [comment]
There's a tunnel to the immediate left of your red arrow that allows you to walk on top of the fence (your dashed blue line) and get back to the shed area.

**Comment by MuadDib90** [comment]
****, I forgot that! 🤦  "Not playing the map in context..."
So only the barrel to be repaired.

**Comment by Ozymandias81** [comment]
Fun fact: there were 4 more like that on the map
