### ISSUE TITLE
[Addons] Instagib add-on

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#956]
@Username-N00b-is-not-available 
You should disable the "half-dead" soldier feature when playing with instagib. It doesn't make sense.

**Comment by Ozymandias81** [comment]
I fear that's not easy since hardcoded.

**Comment by Tormentor667** [comment]
I think this could be doable somehow with an override, what do you think @Username-N00b-is-not-available ?

**Comment by Tormentor667** [comment]
@Username-N00b-is-not-available did you have the chance yet to investigate?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Not yet sadly, I've been in a place without an internet connection and will soon return there, but I hope tomorrow I'll have time to help with some issues including this one.

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 Removed them from the game via ZScript in https://github.com/Realm667/boa-addons/commit/f5ba1ad427c687d40d1031e3dcae0023a9de96a2 (they now die just after spawning). I hope this won't result in a VM abort someday...

**Comment by Tormentor667** [comment]
Glad to have you back @Username-N00b-is-not-available
