### ISSUE TITLE
Achievement "Stingy with the ammo"

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#959]
It does not work.
I had way above 25 reloads, and still getting the achievement after level completition. (after C1M1, but hope it is not related)
@AFADoomer

**Comment by AFADoomer** [comment]
Should be fixed as of f1c54abf87d62d97c894c8aef5955946023eab94.

**Comment by Tormentor667** [comment]
@MuadDib90 can you confirm?

**Comment by MuadDib90** [comment]
> 
> 
> @MuadDib90 can you confirm?

Yes, good now. Thanks @AFADoomer
