### ISSUE TITLE
invisible screen

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#961]
In c3m4, this gun has an invisible screen. Would be nice to throw a grenate through that hole (now it bounces off). It works w/ the other gun though.

![Screenshot_Doom_20210716_140620](https://user-images.githubusercontent.com/77861029/125956365-4b715a8b-e519-4cf3-9366-5ecb32dd70d3.png)

**Comment by Ozymandias81** [comment]
That has been added to prevent map breaking issues afaik
