### ISSUE TITLE
toxicity meter

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#962]
In c3m4, in this room, the toxicity meter should always give a readout. Maybe not as big as when you stand next to an opening, but the gas is still in the air, so....

![Screenshot_Doom_20210716_142355](https://user-images.githubusercontent.com/77861029/125957088-5240a40c-dcc0-4465-83a0-966c4098ef6b.png)

**Comment by MuadDib90** [comment]
I don't get you. Can you please specify?

But the one other thing, I am afraid of, is, what is happening here:

![obrazek](https://user-images.githubusercontent.com/73436978/125960915-dfceab67-3dc7-4463-a472-a7d0e75d7f30.png)

Do you have it like this always? Or is it just this one time?

**Comment by x3003** [comment]
When you get close to the ziklon c stream, the toxicity meter (the skull) becomes visible because it's a deadly gas. But the gas is also around the player the whole time, so atleast it should show something. Instead now, it's hidden coz you're not close to the streams.

>But the one other thing, I am afraid of, is, what is happening here:

That's what happens when you activate 'vid_fps'.

**Comment by AFADoomer** [comment]
Number display is fixed in 310a0f80e6eca7df2d822ea9234b960d736504f8.

**Comment by AFADoomer** [comment]
Added handling so that sector damage can trigger the effect indicator to display in b4f8a1d4d11ef1869743b643a4af2c84c187672f.

**Comment by x3003** [comment]
The game doesn't start because of a missing IF and a misplaced ).
It starts w/ this code:

if (
			player.mo.pos.z == player.mo.floorz && 
			!player.mo.waterlevel &&
			player.mo.cursector.damagetype != ""
		   )
		   if(
				player.mo.cursector.damagetype == "UndeadPoisonAmbience" ||
				player.mo.cursector.damagetype == "MutantPoisonAmbience"
		     )
		{ count++; }



if (
			player.mo.pos.z == player.mo.floorz && 
			!player.mo.waterlevel &&
			player.mo.cursector.damagetype != ""
		   )
		   if(
				player.mo.cursector.damagetype == "UndeadPoisonAmbience" ||
				player.mo.cursector.damagetype == "MutantPoisonAmbience"
			)
		
		{
