### ISSUE TITLE
[ZSCRIPT] Invisible with Firebrand

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#967]
If you have the blade chosen, the enemy doesn't see the weapon as dangerous and doesn't react.

![Screenshot_Doom_20210717_083058](https://user-images.githubusercontent.com/77861029/126028817-f5742289-bd82-4478-9f4c-0b76201d22c3.png)

**Comment by Tormentor667** [comment]
He is stunned by the beauty of the sword 😅

**Comment by x3003** [comment]
Everyone is stunned then ;)

**Comment by AFADoomer** [comment]
I can't reproduce this in the current codebase...

**Comment by Tormentor667** [comment]
@x3003 can you retry again with the current version? Is it safe to be closed?

**Comment by Tormentor667** [comment]
No feedback, so I think we can consider this to be solved. @x3003
