### ISSUE TITLE
floating food

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#969]
In c3m5_b, this meal floats.

![Screenshot_Doom_20210717_075124](https://user-images.githubusercontent.com/77861029/126029160-cea3b115-9801-46d1-a75e-91884aae1948.png)

**Comment by MuadDib90** [comment]
Which release this is again please?
I think this has been already resolved for 3.1
(Many reports have been on this already AICR...)

**Comment by Ozymandias81** [comment]
Actor issue with Z choords, fixed in next commit.

**Comment by x3003** [comment]
These meals still float with the latest git version.

![Screenshot_Doom_20210724_213803](https://user-images.githubusercontent.com/77861029/127780541-1a370c41-0b9e-41e4-a0a7-e20d7e7d8a61.png)

![Screenshot_Doom_20210724_213806](https://user-images.githubusercontent.com/77861029/127780622-80355e4c-2e4f-42d3-a94a-bcd73fb4f7b8.png)
