### ISSUE TITLE
invisible enemies

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#970]
In c3m5_b, these enemies are invisible until you're almost on top of them. As they are quite hard, esp the middle one, they should also spawn a bit earlier, so the player can have some distance between them.

![Screenshot_Doom_20210717_074436](https://user-images.githubusercontent.com/77861029/126029250-94f3f223-30b7-435c-8b9d-6fee9bc55ef8.png)

![Screenshot_Doom_20210717_074445](https://user-images.githubusercontent.com/77861029/126029254-8c2bbb0f-b3c0-4f16-9b27-2a88d266b74d.png)

**Comment by Tormentor667** [comment]
Yes, they need to appear much earlier indeed

**Comment by Ozymandias81** [comment]
That used to happen to me as well but didn't find a clue how to fix it... Let's see.

**Comment by Ozymandias81** [comment]
Ah now I remember that I DIDN'T check the issue, in fact it is easy to solve, these are too much near to those bosses

![image](https://user-images.githubusercontent.com/11136108/126065239-d5baa7b4-ff12-4fd4-8c5a-21d48107e9ce.png)

**Comment by Tormentor667** [comment]
What happens if you walk beside the lines?
