### ISSUE TITLE
[C3M6_A] Tank activated too early

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#974]
In c3m6_a, this tank already moves while the gate is still closed. It tries to bash the gate out... Both switches in that room are still off btw.

![Screenshot_Doom_20210717_140917](https://user-images.githubusercontent.com/77861029/126067949-beefb4f0-1b8a-4753-b46f-58a30ee2a4f7.png)

**Comment by Tormentor667** [comment]
Should be dormant and activated as soon as the gate opens

**Comment by x3003** [comment]
Yes, but it's already activated when the gate is still closed.

**Comment by MuadDib90** [comment]
Guys, I think it was always like this, as long as I can remember...
The tank was probably dormant until you pass the first bar gate (after which you have to bring down that APC), but by passing the aformentioned gate he gets activated.


Also as a side note of this thread, as I see the screenshot, the STEN has wrongly set the overlay part (the newly added smooth part of the back of weapon). The right side of it to be precise. Do you see it?

**Comment by x3003** [comment]
Well, I played this map a few times, but I can't remember the tank was active & firing while I was inside of this building.
I was already searching for some stuff left & right of that gate and he wasn't activated then.

**Comment by MuadDib90** [comment]
I can't recall it firing it either (being behind the bar gate which are not open yet), but being active, I do. On multiple ocasions.

**Comment by Tormentor667** [comment]
So what do we suggest now as a solution? Keep it as is or change it to a different behaviour?

**Comment by MuadDib90** [comment]
Huh, it does not break the game. The gate is "seethrough", so it kind of makes sense it moves... I vote to keep it.

**Comment by Ozymandias81** [comment]
Let's keep it, I remember I had to fix the tank inside the hangar, so this should work fine
