### ISSUE TITLE
Toggling damage effects?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#976]
Just out of curiosity and according to this question („performance issue“)

> Great Mod, It was about time to be able to use the STG-44. Although, I would like to know if there is a way to disable the red effect when you take damage, since this when I receive a shot the damage effect causes me to drop frames, especially when there are many enemies nearby and there is no cover.

Is it possible to make the „modern damage effects“ toggable?

**Comment by AFADoomer** [comment]
No.

**Comment by Tormentor667** [comment]
Then we will keep it as is 👍🏻

**Comment by Ozymandias81** [comment]
Maybe someone should create and addon which adds again the old method, that could be the only way I think.
