### ISSUE TITLE
[3.2] Missions primary objectives

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#988]
[C3M5_C]
You are given all 3 primary objectives right away. It would make sense to have them appear after you talk to Ascher. 

[C3M6_A]
The last primary objective of killing Fettgesicht permanently should appear at the end, when you spot him and find out, he is not dead yet - but in zombie state. Until then you (your character) still think. he is already dead.

**Comment by Tormentor667** [comment]
I have just checked the C2M6_A map and it seems already fixed. Please open a new issue if I am wrong.

Regarding C3M5_C, I just fixed that.
