### ISSUE TITLE
[C3M5_A] Leftover debris

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#993]
With the latest git, in c3m5_a, you will find some leftover debris floating. It was cleared from other areas, but not from here.

![Screenshot_Doom_20210722_224036](https://user-images.githubusercontent.com/77861029/126779119-d96ab70f-fb7c-400d-9ead-2db1eafa2c31.png)

![Screenshot_Doom_20210722_224142](https://user-images.githubusercontent.com/77861029/126779128-dfb29b1e-e2b5-4e62-93e4-e5dfb7b96ffb.png)

**Comment by Ozymandias81** [comment]
Does it happen on 4.6.0. stable build, using most recent version of BoA?

**Comment by x3003** [comment]
Yes.

![Screenshot_Doom_20210723_214545](https://user-images.githubusercontent.com/77861029/126833844-289b29e0-ca25-41d9-8601-8ae3d5876990.png)

![Screenshot_Doom_20210723_214718](https://user-images.githubusercontent.com/77861029/126833862-0404d00f-dc4c-4af7-a1a2-64a8d13908f8.png)

**Comment by Tormentor667** [comment]
I can remember that a fix has been made by @AFADoomer regarding the culling, so is this working properly now?
