### ISSUE TITLE
[C3M6_B] - Wolfenstein issues

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#997]
- [x] IDK why, but here is some invisible wall. Not shoot-through able, not pass able.

<details>
<summary>Figure</summary>

![01](https://user-images.githubusercontent.com/73436978/126862248-68983584-1b8f-4465-ac7b-8ce6f743c8d3.PNG)
![02](https://user-images.githubusercontent.com/73436978/126862251-cf371ea4-42c6-4e98-b774-00d55787690f.PNG)

</details>

- [x] This hatch has no boundaries set, it is completely clippable.

<details>
<summary>Figure</summary>

![03](https://user-images.githubusercontent.com/73436978/126862280-a875353b-7539-4c78-845e-e913fa551230.PNG)
![04](https://user-images.githubusercontent.com/73436978/126862281-7c6b59b0-1214-4dcd-b139-558c21a06029.PNG)

</details>

- [x] This radio from under the table in the tower still has not been repaired.

<details>
<summary>Figure</summary>

![05](https://user-images.githubusercontent.com/73436978/126862313-9f02c9fc-691a-4df2-be8f-d259acdf779d.PNG)
![06](https://user-images.githubusercontent.com/73436978/126862318-a2ce6cb0-a7d2-4a46-93b7-441d8b3067fe.PNG)

</details>

- [x] You can enter the dungeon from yard through this bars when crouching. They have no boundaies.

<details>
<summary>Figure</summary>

![07](https://user-images.githubusercontent.com/73436978/126862364-ca295de1-7c9c-4b7f-839f-775da2b9b3c6.PNG)
![08](https://user-images.githubusercontent.com/73436978/126862366-d88c7528-585a-4834-8f37-7be97d121543.PNG)

</details>

- [x] The rope is "fixed" in the midair, not on something. There must be some bug, I remember being this OK.

<details>
<summary>Figure</summary>

![09](https://user-images.githubusercontent.com/73436978/126862411-fb088f28-0145-43be-b5df-4bd73dec032a.PNG)
![10](https://user-images.githubusercontent.com/73436978/126862413-9d112a48-c368-46d5-832b-f655498ba6da.PNG)

</details>

- [x] Also, why there are spikes at the bottom of the well? Can't we put there some treasure for example? For curious and investigative players?

<details>
<summary>Figure</summary>

![11](https://user-images.githubusercontent.com/73436978/126862442-e98510f1-74f7-452a-927d-e88a2c91ee58.PNG)
![10](https://user-images.githubusercontent.com/73436978/126862413-9d112a48-c368-46d5-832b-f655498ba6da.PNG)

</details>

- [x] When medic is surrendering, he counts to achievement "let 5 enemies surrender". But it is instant +1 to achievement, because they can't be killed, so it is not depending on player, if he'll achieve this one.

<details>
<summary>Figure</summary>

![13](https://user-images.githubusercontent.com/73436978/126862492-62fdf27a-6f32-418a-a816-a5466df830c0.PNG)

</details>

- [x] Why there are no walls visible in automap for this room?

<details>
<summary>Figure</summary>

![14](https://user-images.githubusercontent.com/73436978/126862494-be18f04d-73ce-4d72-90e3-7e1dd6260a84.PNG)

</details>

**Comment by Ozymandias81** [comment]
Please test it under 4.6.0 again and tell me if all of this is present. Recent builds of gzdoom may be too early builds with some issues, which I cannot test now.

**Comment by hawkwind3** [comment]
I can comment on the spikes at the bottom of the well. With the 3.0 release, as soon as the player released himself from the rope, even at the end of the rope which is near the floor, the player would instantly die. I suggested spikes. If the player falls from a great height, he should die, so gold here would not help. Suggestion ... I wonder if a small 3d floor could be placed down there off to the side of the well, just short of the spikes and a pickup placed .... potential reward ... potential danger ...

**Comment by MuadDib90** [comment]
> 
> 
> Please test it under 4.6.0 again and tell me if all of this is present. Recent builds of gzdoom may be too early builds with some issues, which I cannot test now.

Tested it under 4.6.0 again. Unfortunately all issues are still present...

**Comment by x3003** [comment]
> IDK why, but here is some invisible wall. Not shoot-through able, not pass able.

Should be fixed in commit #1103

>You can enter the dungeon from yard through this bars when crouching. They have no boundaies.

Should be fixed in commit #1147
